== Chapter 2. Letters from 1788--1796

[.letter-heading]
To Sarah Grubb.^
footnote:[When young,
Sarah Lynes Grubb was governess in the home of woman whose name was also Sarah Grubb.
This letter, and several following, were written by young Sarah Lynes +++[+++later Grubb+++]+++
to her mistress by the same name.
There is a third Sarah Grubb (mentioned below in her letter
to Thomas Dobson) who was the wife of Robert Grubb,
and a well-known minister in the Society of Friends.]

[.signed-section-context-open]
Anner Mills, Eighth Month 9th, 1788.

[.salutation]
Dear Mistress,

I can inform thee the children are all well, and in spirits.
They were in great spirits yesterday evening; so much so,
that it was hard to get them settled; but I got them to sit down after tea,
and read to them.
I believe I cannot keep them as orderly as when you are at home,
yet I hope to do as well as I can.
I wish it was in my power to keep them entirely to your wish,
for it affects me when you come home, and find a deal of labour seems to be lost,
which had been bestowed for their good.
They all give their love to thee and their aunt: may I ask you to accept of mine?

I think to conclude, not remembering anything more now,

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To a Friend (Probably E. Pim).

[.signed-section-context-open]
Twelfth Month 27th, 1789.

[.salutation]
My Beloved Friend,

Perhaps I may tell thee how I have fared this day.
In the morning I was as one dead for some time, as to any spiritual life,
but after a while, S. Lees stood up, and exhorted to faithfulness in a little,
though it might seem indeed very little; and after her,
J+++.+++ T. took up part of what she said, and spoke encouragingly to some,
but said it appeared to her that the pure seed was oppressed,
even as a cart is pressed down with sheaves.

I may say of my poor self, I found this afternoon, that what mercy did not do,
judgment did; for truly the word of the Lord was in me as a fire,
so that I durst not withhold what ran through me; for if I did,
I believed I should be forsaken; and the absence of my Beloved is so great a trial,
that it is hard to endure; but glory forever to His great name,
who makes a way in the sea, and a path in the mighty waters,
He hath caused my poor spirit to know "`the mountains to skip like rams,
and the little hills like lambs`" before His presence; and I, a poor worm,
am made to praise Him on the banks of deliverance.

I have a very bad pen, and not a steady hand,
and it is not very easy to write intelligibly: also there is one waiting to take me home.
I sincerely desire thou, my well-beloved friend, mayest farewell.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Fifth Month 3rd, 1790.

[.salutation]
My Dear Mistress,

Thy letter was handed me this morning.
We were all out yesterday,
but B. thought best to come home with the children after first meeting;
so S. and I stayed the second,
in which dry season was a word of encouragement to some who go heavily on their way,
from S. Lees.
When we came home and had got tea, some friends came in to see us,
which occasioned our reading to be rather late; however, quite unexpectedly to me,
we seemed fastened to silence after closing the book, which, in the end,
was comfortable to my often tossed mind.

[.signed-section-closing]
Truly farewell,

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Seventh Month, 1790.

[.salutation]
My Dear Mistress,

We received with pleasure thy letter. First day afternoon S. A. appeared.
I think her words were, "`Turn ye, turn ye, oh house of Israel; why will ye die?`"
Great dryness and deadness is often my lot, so that I may say,
"`My Well-beloved is unto me as a spring shut up,
a fountain sealed;`" but I know I often bring these times of drought on myself,
by not keeping pure and sincere: so that, though I tell thee my state, I do not complain:
I believe it is good for me that I am afflicted.

[.signed-section-closing]
Farewell.

[.signed-section-signature]
S+++.+++ L.

[.letter-heading]
To Thomas Dobson, of Cumberland, After his Return From a Religious Visit to Ireland.

[.signed-section-context-open]
1790.

In that love which many waters cannot quench, neither the floods drown, do I salute thee;
having often, since thy departure from this land,
had a desire to communicate a little to thee after this sort.
Whilst thou labored in this vineyard, I believe, if I know what sympathy is,
I did sympathise with thee at times;
and although many are the trials of the Lord`'s children and servants,
yet is there not consolatory relief for these?
Their dear Lord and Master took upon Him the nature of poor fallen man; He,
being touched with the feelings of human creatures,
carried our sorrows and bore our griefs; and if He, "`the only-begotten of the Father,
full of grace and truth,`" passed through so many baptisms,
ought not we to rejoice when we are buried with Him in baptism; yea,
to suffer with and for the precious seed?
Oh! this seed, may it more and more,
by the pure love of God shed abroad in the hearts of the children of men,
rise into dominion, and show forth the praise of the great Husbandman;
and may the cloud which was seen to cover the daughter of Zion be removed,
that so that language spoken formerly may be applicable--"`Arise, shine;
for thy light is come, and the glory of the Lord is risen upon thee.`"

And now, dear friend, believing I may write freely to thee,
even as a simple child would talk to one growing in years and experience,
I tell my thoughts:--I much wish and desire to be humble; yea,
continually to dwell in the low valley.
This is often, more often than the morning,
the breathing of my soul to the great Searcher of hearts;
but the unwearied adversary is so busy and subtle,
that I am at times ready to think I shall never attain to that state of purity which,
when under the precious influence of the power of Holy Jesus,
I am enabled to press after.
Oh! truly I am often afraid I shall fall at last a prey to the devourer;
and what shall I say?
May it please Divine Goodness to cut the thread of my life,
rather than that I should be a reproach to the spotless truth, the pure truth.
I trust I feel in degree what I write;
for when I am made sensible of the Lord`'s hand at work in my heart,
I am at seasons ready to say, I will offer unto Thee and thy truth not only my body,
but all that Thou hast given me, only go Thou before; and oh! saith my soul,
May I never run before I am sent.
This is what I am much afraid of.
Oh! do thou, when permitted to approach near the throne of grace, think of me,
and entreat the everlasting Arm of Power, thy Beloved and my Beloved,
that I only follow His heavenly voice, and never the voice of a stranger.
Very slippery, thou knowest, is the path of this life, and many are the wiles of Satan;
if, therefore, I should be caught in his snares, great will be my fall.
One comfort just now occurs to me, "`Greater is He that is in you,
than he that is in the world.`"

I suppose thou hast heard of the removal of that
bright star which did shine in the firmament,
much to the glory of Him who causes the stars to move in their courses; may I not say,
surely if ever one was redeemed from self-love, she was;
but I am not telling the name she went by whilst in the body: it was Sarah +++[+++Robert]
Grubb who was engaged in her dear Master`'s cause in France
and some part of Holland whilst thou wast here;
but I must conclude, desiring that thou mayest farewell.

[.letter-heading]
To E. Pim.

[.signed-section-context-open]
Anner Mills, Twelfth Month 16th, 1790.

[.salutation]
My Beloved Friend,

Although very poorly qualified, I am desirous to comply with thy request;
and may tell thee we got home safe about four o`'clock on third day evening,
and stayed to the sitting at Suir Islaud, which was an awful humbling time to me,
and I believe to more.
J+++.+++ W. was there; he appeared in testimony and supplication.
Also S. S. said, I think, these words, "`The almost continual cry of my heart,
these several days past, hath been, Oh!
Lord, have mercy upon us, for we are brought very low;`" and, after her, S. A. said,
"`The Lord giveth, and the Lord taketh away; blessed be His great and adorable name.`"

I came home poor, very poor; and, instead of being relieved,
my mind is greatly oppressed; but if I am in the great and good hand of kind Providence,
I am glad.
I thought I felt relief and a degree of peace in Cork;
but it hath often been suggested to me since, that I was not always right:
perhaps this is the work of the enemy.
Continue, my dear friend, to breathe for my preservation, who am very weak.
I think of thee a great deal: I hope thou art well.

The children all give their dear love to thee.
I remember the kindness of friends to me whilst I was in Cork.

[.signed-section-closing]
Farewell, saith

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Samuel Davis.

[.signed-section-context-open]
First Day Morning, 1791.

My heart is so full towards thee, beloved friend,
that I seem as though I could not well forbear opening it.
I mean to tell thee of my infirmities and weaknesses, which are many and great,
not merely for the sake of telling, but I think,
where there is a freedom of communication of this sort to a dear friend,
it is in degree consolatory.

It hath pleased the Most High to deal with me lately in a manner to me almost wonderful;
for verily, I have been brought into darkness and not into light; yea,
I was hedged about that I could not get out: my chain was indeed made heavy;
insomuch that I was ready to conclude my soul was never
more to see the glorious light of Almighty Power;
yet, blessed be His name, I had not been long here, when,
out of the depths of my sore trouble,
I was permitted to cry unto the depths of His mercies; and He granted to me,
even to so poor a worm as I, "`the word of His patience.`"
He gave me a resigned heart, let what would befall me; and I felt,
that if I had offended my Beloved, I had no other to look to for forgiveness; and,
through Him alone, was enabled to wait, and trust in the arm of His power: so,
in His own time,
did He cause me to sing praises to His name in my heart for a little season;
but again hath it pleased Him to let me feel trouble and sorrow,
yet I think not to so great a degree.
I fear I have done something wrong.
Ah! dear friend, all my soul desires is to be preserved pure and humble;
and truly it is not without the continual warfare this is to be kept to:
so many are the temptations, and so subtle are the insinuations of the cruel adversary,
that often I think I shall one day fall by this mine enemy:
he does indeed go about "`as a roaring lion,`" seeking
what poor soul he can catch for his prey;
but if we believe, we may, I sometimes think, take comfort in this expression,
"`Greater is He that is in you than he that is in the world.`"
May we lean upon Him and trust in Him; even in that sure Rock,
against which the very gates of hell shall never be able to prevail.
Farewell: I _must_ leave talking with thee, as I have not more time.

[.signed-section-closing]
Thy poor, but affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To her Mother.

[.signed-section-context-open]
Anner Mills, Fourth Month 29th, 1792.

[.salutation]
My Dear Mother,

I had given up writing to thee at this season, but now, finding another conveyance,
I gladly embrace the opportunity.
I know it would be cause of rejoicing to thee to see me at the ensuing Yearly Meeting,
but it seems to be ordered otherwise, so I make no doubt thou wilt reconcile it.
I feel comfortable about it, hoping I am where I ought to be;
and I wish very much it may please Divine Goodness to preserve me in the
right path during my journey in this world (I believe I may say from a
small degree of experience) of trials and deep anxiety;
for though my lot, I believe,--and may I, through Divine mercy,
still continue to think so--is a favored one beyond many,
as to being kept much out of the way of temptation, yet, in every station,
I am apt to think, there are probations and besetments;
and truly it was not intended it should be otherwise.
We are placed here to work out our salvation, so if we had not trials,
the reward would not be ours: without a cross we need not expect the crown; so then,
my dearly-beloved mother, let thee and me lay aside every weight and burden,
all impurity, and run with patience the race that is set before us;
looking unto Holy Jesus, the author and finisher of our faith.
Could we but be clothed with this faith,
surely we should be enabled to quench the fiery darts of Satan; to overcome him,
even the prince of the power of the air, in all his assaults to catch the poor soul.
Oh! methinks I can sometimes feel him close behind me,
waiting every opportunity to destroy me, by his secret insinuations to my mind.
But when I am led to consider that He who is in us
is greater than he who is in the world,
I am ready again to be glad in His name or power;
feeling His holy arm of preservation is still extended even to me,
a poor unworthy creature, ready to fall every hour, but that He holds me up, yea,
invisibly so.
Oh that the whole world could but be persuaded that
there is a possibility of living without sin here;
that all would but believe that they can keep the commandment of our dear Lord and Savior,
who said, "`Be ye therefore perfect,
even as your Father which is in heaven is perfect:`" then would
our conversation indeed be in heaven while we live on the earth.
Please read this part to my father, and remember me to him.
I suppose sister S. is at home:
tell her to be sure learn the fear of the Lord who made her;
it will teach her better wisdom than all the wisdom of this world.
I believe I may now bid thee farewell, much desiring it may be so with thee.

[.signed-section-closing]
Thy dutiful and truly affectionate daughter,

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Cork, Eleventh Month 19th, 1792.

[.salutation]
My Dear Mistress,

It seems as though I could not tell thee that I expect to be with you tomorrow,
which I would gladly do did I think I should have peace therein.
I felt and feel grateful for thy letter; I took it as from a mother, and as a child.
I believe I may tell thee how I have fared.
I have been indeed low; although at parting, and for a time after,
I felt the evidence that I was in the right place (or at
least I thought I felt it) yet greatly was I tried.
Many were my doubts indeed yesterday, in the morning meeting;
but in the afternoon I thought I was in a state of suffering,
and that I felt the approbation of my merciful Creator,
who has a right to do what He pleases with me: in this did I silently and humbly rejoice,
and after meeting felt peace and quiet; from whence I went to E. H.`'s,
where was a humbling sitting.

We got safely and very quietly to Myrtle Hill, on seventh day evening.
Thy

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Myrtle Hill, Eleventh Month 23rd, 1792.

[.salutation]
My Dear Mistress,

It is under deep conflicts I now address thee.
I had much rather be getting towards home; but after deep probations last night,
I felt easier to stay till after First day; and though I would gladly go,
and had told James Abell I intended to do so,
yet I believe should not have peace if I did,
so that I should not be likely to do much good at home in such a state:
indeed it is no pleasant thing to me to stay in Cork:
I think I shall remember this wormwood and gall.

James Abell says, "`Give my love to thy mistress; tell her,
I hope we shall not be sorry for thy staying.
I hope so.`"
He also desires me to tell of the bustles here,
and ask thee is there any such thing with you.
The mobs rise every night.
It is reported they have done much harm in Bandon: they were about the town last night,
and many soldiers were called out.
I believe one or two persons were taken prisoners.

Many times do I think of the dear children, and long to be with them.
May you all farewell.
Thy

[.signed-section-signature]
S+++.+++ Lynes.

[.blurb]
=== A Verbal Communication of Job Scott to Sarah Lynes, When she was Living at Anner Mills, Near Clonmel, 1793.

[quote]
____
Hold fast that which thou hast received--a gift from the holy anointing;
the enlivening influence.
Ay, those who give up when they are young, I believe,
enjoy more of the fat of the land than almost any one else.

Art thou at all aware of the many difficulties and trials which, if thou art faithful,
thou must have to encounter?
or is it, in wisdom, hid from thee?
Be faithful, and thou canst not think how easy things will be made to thee.
I wish thee to be encouraged.
I feel near unity with thee:
don`'t be afraid when thou art brought before kings and princes in Israel,
or in the world.
Thou knowest not what thou mayest have to do yet,
and all do not like to be told the truth.
Thou knowest not what perils thou mayest have to meet with amongst false brethren;
but give up all to the Lord: be faithful.

I am pleased thou art cheerful in thy station: keep low; we cannot be too dependent.
I do not say these things because I believe thou wilt be exalted;
but I know Satan tempts people when they have got to be a little more than they expected.
There is nothing like giving up the whole heart to the Lord,
which I hope thou hast done in a precious degree:
take care thou take up with no other leader but the Lord alone.
It was an excellent saying of Gideon, '`I will not rule over you,
neither shall my son rule over you;
the Lord shall rule over you.`' It is a sad thing when any get above what they ought:
do thou keep close to the Lord.
All things are possible to them that believe: it was a noble saying.
____

Oh!
Thou who sees not as man seest, Thou knowest these things were spoken in thy pure spirit,
which made my heart deeply feel them.
Do thou fasten them therein, as nails in a sure place;
and ever make me grateful for such favors as these.

[.signed-section-signature]
S+++.+++ L.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Anner Mills, Tenth Month 3rd, 1794.

Yes, my dear mistress,
I did think it very material to get an answer from thee to my letter.
I longed for thy counsel, and when I got it, was, I trust, a grateful receiver;
though under very deep conflict; so much so,
that my life seemed of little consequence to me;
indeed I was afraid I was losing my _best_ life.
I know not how I should have got through,
had not the immovable Rock been nearer than I was aware of,
and had not ability been afforded to escape there for my life.
I know great is your maternal care for my preservation:
I also know that you are sensible I cannot be preserved but on this Rock;
I therefore believed it better for me to stick very close thereto;
and notwithstanding the deep distress of my soul,
and the discouragement which I thought surrounded me, I saw no way for real safety,
but to move under what I conceive Divine command; although the language was deeply felt,
"`How dreadful is this place!`"
There is only one source of effectual help, and when this is deeply sought unto,
and some degree of its efficacy felt, do not "`the mountains skip like rams,
and the little hills like lambs?`"

This family is well.
Our dear love is to you all.
Farewell.

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Youghal, Twelfth Month 23rd, 1794.

Thy dear mother is, I think, better in health than we might expect,
seeing how much she goes through, and the severity of the weather.
Thou seest, my dear, that she counts not her natural life dear unto her,
that she may fill up her measure of labour and suffering: mayest thou follow her,
as she is endeavoring to follow her great and good Master;
may nothing be too precious to part with for the glorious reward of a truly devoted soul;
may no consideration hinder the progress of this dedication in thee.
"`Honor the Lord with thy substance, and with the _first fruits_ of all thine increase:
so shall thy barns be filled with plenty,
and thy presses shall burst out with new wine.`"
Many times since and before my being joined to your precious mother,
I have wished that you, her offspring, might, as you grow in years,
grow also in that which will make you wise unto salvation;
and so be blessed with that which will make you, as it does her, truly rich.
May every one of you be under the peculiar notice and regard of your heavenly Father,
saith

[.signed-section-closing]
Thy poor but affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Elizabeth Grubb.

[.signed-section-context-open]
Cork, First Day Evening, First Month 26th, 1795.

I was very glad of the receipt of thy letter today,
not only because I longed to hear from you,
but thereby I have leave to write to thee without professing a concern to do so,
which I have wished to do;
although perhaps this letter also will be full of complaints
concerning myself--my want of patience under necessary,
painful baptisms.
I was, for what I call a long time, in possession of an enjoyment of unspeakable peace,
except at some few intervals.
This was, I trust, enjoyed in the moderation;
for I knew summer was not likely always to continue,
and now I am glad I was favored to feel resignation to accept the dreary winter,
whenever the change of season might take place, which is now come;
for "`the time of the singing of birds`" is at an end,
and the voice of melody is no more heard in my land; yet, praised be my gracious Helper,
I am not without feeling:
the pinching frost has not been suffered wholly to benumb me--no;
for I have this day witnessed a sharing with the precious, suffering seed here.
Oh! my dear, I was and am bound with it.
May the bars of iron not be broken till the Master`'s time.

In meeting today, deep called unto deep in my heart:
the waves and the billows passed over me; yea, my head was wrapped about with weeds:
I thought I could acknowledge with the prophet (in
silent travail) "`I am pained at my very heart.`"
May the all-powerful arm bring His oppressed seed in this place,
out of its imprisoned and deeply afflicted state, saith my very soul.

I have often thought, my beloved friend, that this is a day when we must travel alone,
and often feel "`like a pelican in the wilderness,`" or an owl in the desert;
and perhaps at times be ready to conclude we are comparable to "`the heath in the desert,
which sees not when good cometh;`" but I cannot believe
that this is designed to be our continual lot,
if we endeavor to "`leave the things that are behind,`" and to "`press forward:`"
then I am of opinion our wilderness at times will be made like Eden,
and our desert like the garden of the Lord:
that we shall know the descending of heavenly dew,
causing us to increase in holy verdure; yea,
and to grow up as a root out of a dry ground.

I am glad that these things arise in my heart unsought for to say to thee.
May He who knows what we all stand in need of,
abundantly help us both to walk in the path of holy rectitude.
Please give my dear love to my precious H. Tell her not to lay down her weapons of war,
then they will prove mighty until every thought is brought into obedience.
Could these things happen unto me, if not permitted or appointed by unerring wisdom?
The Lord knows; therefore I leave _all_ to His ordering.
My dear love to N. Tell her to hold out, and seek to increase in well-doing,
that the end may crown all.
Tell A. and S. M., with my love,
I often wish they and I may know an early surrender of every pleasant picture,
or any other gratification called for; so shall we feel superior joys.
I do not forget thy dear mother.
I often feel grateful for her affection to me.
I _love_ her too.
I also remember thy brother;
and a wish just now arose in my heart that he might also believe in the declaration,
_to his comfort_ (not that I think by any means he does not acknowledge to the
truth of it) that "`to them which sat in the region and shadow of death,
light is sprung up.`"
I did not seek for something to say to you all, but one after another occurred to me;
and, in the love in which I have mentioned you individually,
I now bid you so and collectively farewell, dearly farewell.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Elizabeth Grubb.

[.signed-section-context-open]
Dublin, Fifth Month 3rd, 1795.

I think I increasingly feel thee near in that which "`many waters cannot
quench nor the floods drown,`" either in an outward or inward sense,
while we abide with that which is able to sustain the soul,
and which unites the living members of the mystical body of the immaculate Lamb.
Oh! how I crave that thou mayest witness the sealed book to be unfolded unto thee,
by keeping with the "`Lion of the tribe of Judah,`" who alone can prevail;
and I do believe, as thou dwellest deep with Him,
thou wilt at times have to sing the song which can only be sung in Judah`'s land,
"`We have a strong city;
salvation will God appoint for walls and bulwarks:`" thou wilt know thy
habitation (being with the Father and the Son) to be a fortified one,
secured from the noise of archers; for though these may shoot,
yet shall they not be able to overcome in this sure resting-place,
where the flocks of Christ`'s companions do indeed know a resting at noon.
But perhaps thou wilt say, how shall I attain to this?
If thou know not in the manner thou sincerely, I do believe, desires,
go thy way forth in the tribulated path,
even though it be pointed out to be first to the judgment-hall;
for I believe those whose eye is single to the great Master,
are not left in the dark as to the way in which they ought to walk:
then other various dispensations, even until thou become nailed to the cross.
As this comes to be the case,
thou wilt experience that "`precious in the sight of the Lord is the death of His saints;`"
so wilt thou be enabled to fight under the banner of a crucified Savior here,
so as to obtain an everlasting inheritance with Him,
when the conflicts of this life are at an end.
Dear +++_______+++ said in meeting yesterday, "`Cursed be the man that trusteth in man,
and maketh flesh his arm;`" but "`blessed is the man who trusteth in the Lord,
and whose hope the Lord is.`"
Come, let us all, whether separated or not,
seek for ability to go up to the mountain of the Lord, to the house of the God of Jacob,
where He will teach us of His ways, and we will walk in His paths;
for thereby shall we be enabled to fare well in Him.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
Probably to the Same.

[.signed-section-context-open]
Sligo, Third Month 15th, 1795.

We have been longing to hear from you, and particularly about thy dear father;
but we must have patience about intelligence from home now, as we are so far from you:
it is, however, a consolation, that though we may be separated outwardly,
yet nothing outward can hurt a love rightly founded.
Your conflicts, I think, must be great concerning your dear father;
but what a favor to be instructed where to look for, and to be sure of finding,
help at such times, if we rightly seek; but we often ask, and do not receive,
because we ask amiss.
May we, therefore, seek for ability to breathe the pure language, "`Thy will be done.`"
But oh! what reduction it requires to attain to this in all things;
yet I believe it is the only way to be found in a state of acceptance,
and of the number of those believers unto whom all things are possible.
Well, let us leave the things that are behind, and endeavor to press toward the mark,
that we may obtain the prize.
I feel more towards you than I have ability to express.
May you farewell.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sligo, Third Month 16th, 1795.

I feel so much love to thee that I think it almost
a pity to miss this opportunity of writing,
and yet I do not seem to have much to say.
I may, however, tell thee, that I look towards thee as though thou wast in the deeps:
well, my dear,
here the wonders of a great and good Master are to be seen and experienced,
I suppose in the best sense witnessed; yea,
and those who steadily abide there the appointed time, I believe,
are enabled to bring up living stones of memorial, whereby perhaps, not only themselves,
but many others may be instructed.
But why should I talk to thee about things I know so little about myself; but,
if I could at all encourage thee, I should be willing to expose my weakness, which,
I think, I increasingly feel to be very great.
We have been to an appointed meeting here today: merciful help was extended,
and I believe the people in general much satisfied.
I like to join in the feeling of your consolations as well as depressions, and,
when I am sensible of very little else, I think I sometimes feel a love for thee,
thy brothers, and sisters, which is the case at present;
and I suppose this is a little symptom of life:
"`For to him that is joined to all the living, there is hope;
for a living dog is better than a dead lion.`"
Ah! my dear, if we are but kept alive in the root it will do,
let our provings be ever so great.
May it be thy experience to have thy vessel so steered through every storm,
as to be safely landed at the haven of rest at last.

[.signed-section-closing]
Dearly farewell, saith thy truly affectionate

[.signed-section-signature]
S+++.+++ L.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Anner Mills, Fifth Month 5th, 1795.

[.salutation]
My Dear Mistress,

I was very grateful for the receipt of such a kind letter as came to hand yesterday,
and wherein was so much information.

My mind was under a peculiar feeling while Dr. H. was here,
so that I thought it would tend to distress me if I did
not offer a few sentences to him when we were alone,
which he took very kind, he said.
I felt quiet after.
I heard he told somebody the mark was hit to a hair`'s breadth:
it felt very difficult to me to give up to it, and what was said was in much weakness.
In the fresh feeling of much affection and regard,

[.signed-section-closing]
I remain thy

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To her Mother.

[.signed-section-context-open]
Dublin, Eighth Month 24th, 1795.

[.salutation]
My Endeared Mother,

Having arrived here about two hours, I am willing to let thee know as soon as possible,
believing it will be pleasant to thee to hear from thy poor S. L., after being, perhaps,
some time in suspense about her.
We left Liverpool last sixth day, about two o`'clock,
so that we were more than seventy-five hours on sea: I was very sick the first night,
and poorly most of the time, which was, I believe,
increased by the great number of passengers on board the small vessel; there being,
I suppose, above one hundred and seven, twenty-six of whom were cabin passengers.
Not only the beds were full, but the floor also covered,
insomuch that it was almost too close to go into without being sick:
I stayed mostly on deck, notwithstanding, on first sailing, it rained hard.
Instead of Thomas Scattergood and William Crotch, I had two other Friends`' company here;
they not being ready, I thought it much best not to wait in Liverpool;
and come what will next, I can, through abundant mercy,
feelingly acknowledge the Lord my God hath dealt bountifully with me,
and my soul is at present bowed in gratitude.
Oh! may it continue in this humble resigned frame;
for indeed I have no right to expect other than afflictions and trials; these I look for,
now that I have returned to this land; and if, in mercy and wisdom,
they should be handed,
my heart craves to be so resigned as to be enabled to breathe the language,
"`Not my will, but Thine, oh Lord, be done`" so,
by believing in the all-sufficiency of revealed Power,
all things will become possible... All I coveted (if I knew
my own heart) was to stay and return in the right time;
which, if I may judge from the present peaceful state of my mind,
was in good degree the case: but I am still about eighty miles from Anner Mills,
so that I have to write again from thence.
I wrote to M. S. and dear sister, since I left York; but thou wilt, I doubt not,
tell those dear friends of mine, Joseph and Mary Smith, of the receipt of this; and wilt,
I hope, let them know the contents,
as I believe it will be pleasant to them to hear from one to whom
they administered so much kindness for such a long time;
and that language livingly arises,
"`God is not unrighteous to forget their labour of
love;`" because I verily believe it was acceptable,
as though it was to one much more worthy.
My very dear love is to poor +++______+++. Dear love to +++_______+++, for whom I at times travail,
that though, comparatively,
there may be but "`two legs and a piece of an ear`" saved from the devourer,
and even that in his jaws, yet, by submitting to that Power which is alone able to do it,
the remains may, in abundant mercy, be taken from his mouth; yea,
and by that living Divine faith,
which produces that which pleaseth Him who hath been grievously offended,
there may be a being made whole.
Farewell, farewell, saith the heart of

[.signed-section-closing]
Thy affectionate daughter,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To her Brother.

[.signed-section-context-open]
Anner Mills, Fourth Month 29th, 1796.

[.salutation]
My Beloved Brother,

My mind is very often occupied about thee and thy precious charge;
I wish you to be of those whom the Great Shepherd of Israel will, in the day of trial,
hide in the hollow of His holy hand:
then what watchfulness is necessary in order to mind and obey His
will in all things--how closely should we cleave to His Providence!
I have sometimes thought, if this is our happy experience,
we shall know hard things to become easy, crooked things straight,
and rough places plain;
and I believe He will no more forsake these than He did Caleb and Joshua in the wilderness,
when, without murmuring, they encountered many difficulties,
and at last got to the land flowing with milk and honey.
Ah! my dear brother, will _He_ not, whose "`the earth is and the fulness thereof,
the world, and they that dwell therein,`" care for thee and thy children; yea,
thy companion in life also, if you only depend upon Him for help,
and do all things as by His Holy Spirit?
Salute +++_______+++ for me; tell her to give up her heart to the Lord,
and He will be unto her all she wants:
let her take great care she offend not His precious principle in her heart, in word,
thought, or deed.
I wish thou wouldst write to me in return, and tell me all thou canst about you.
I may not take up more time now in this way, so farewell saith

[.signed-section-closing]
Thy affectionate sister,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Elizabeth Grubb.

[.signed-section-context-open]
Cork, Eighth Month 11th, 1796.

It was very kind of thee to write to me,
and very like thee to express what thou didst about the Minute;
and although I do not know that there is much at
present in my mind to write to thee about,
yet I feel that I love thee,
and can fully believe thou canst and dost rejoice
in anything that seems likely to tend to my relief.
I trust I also could for thy sake rejoice,
if thou couldst acknowledge cause for joy and rejoicing of heart in thyself,
and not in another.
This perhaps may at times be done unto Him who remains to
be the help of His people without another intermeddling,
and is, I believe, the reward of dedication of heart and abasement of soul.
Dear +++_______+++ is a striking example, in my view, of willingness to become a fool,
for the sake of his worthy Master; which, I expect,
will enable him to become wise in those mysteries only revealed to babes,
and wise unto everlasting life, as he does not grow weary in well-doing.
Bonds and afflictions await thy poor friend--of such a sort, I believe,
as my natural disposition introduces me into, and which, to be sure,
do not belong unto the Gospel:
I seek to be delivered from these by aiming after more unmixed resignation of soul.

Here is all thy affectionate friend hath in possession at present to communicate;
but I expect thou wilt continue to be near at times in spirit,
if we are mercifully preserved.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Cork, Ninth Month 7th, 1796.

[.salutation]
My Dear Mistress,

I did not expect, when I wrote to thee last,
that I should again address thee in or about this place (though
I think it was left loose) nor did it seem very likely long together,
that it would be the case: even since that time, great hath continued to be my distress;
and on getting up this morning in order to set off behind J. R., it looked very trying.
The prospect of leaving this city unrelieved I had got resigned to,
which still looks likely to be the case.
Dear H. H. is still with me, and is likely to be so whilst I am here.

Thou, it is probable, heard some way or other of our movements whilst dear J. A. was here.
Last sixth day we went to Middleton, which I question being the case,
had he not expressed some feeling respecting it.
He took us to a school which appeared to be for the
education of children in pretty high life:
we had an opportunity to some relief amongst them,
which seemed to them very new at first,
but afterwards they got a little to understand our manner.
From that place we went to the factory,
just in time to see the people coming out to go home for dinner.
They were requested to stop in a kind of shed near the yard, which is a large place:
we sat down on some stone steps, and the people gathered round us:
after a short time they were addressed, and appeared very quiet.
I believe all or most who know J. A., of all descriptions,
cannot but be taken with his loving and affectionate manner.
Several expressed their great satisfaction at that time.
From thence we went to the inn, and the time of holding a public meeting soon came on.
It was large, and I believe tended to some relief.
On seventh day we sat with a few who still remained
of those who had some claim to the Society,
but not in membership.
On First day, great was the suffering of my mind in silence.
J+++.+++ took his leave of Friends, and I did not know, till after first meeting,
of his being really likely to go in the morning.
He said he was willing to stay a day or two,
if I was fully come to a conclusion that this was
the time for moving amongst the people at large here.
I could not say so: it appeared very awful;
and unless he was under the weight of it for himself,
it seemed best to leave it entirely for the present.
I don`'t know that I shall now go farther than my lodging, except to meeting, while here,
save that I have thought of seeing another school, that I mentioned to J. A.,
but way did not open before he went.
I have also thought of seeing L. N.`'s family once more,
and a young woman whom we did not sit with; but unless way opens even for this,
surely I cannot attempt it, and I hope would not dare.
No one that has not been in the same spot can, I believe,
conceive the situation of my mind; whether it is brought on by myself,
perhaps remains to be one time or other made known.

[.signed-section-closing]
With love to all at Anner Mills, I conclude.
Thy

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Miltown, Ninth Month, 1796.

[.salutation]
My Dear Mistress,

For aught I see at present, I am likely to proceed towards home tomorrow after meeting.
I have frequently felt the weight of a public meeting in Cork pretty heavy upon me;
and at times, since coming to it,
thought I had a clear evidence of its being my place to make some attempt to move in it;
but now all is one load of oppression and darkness that may indeed be felt;
yet surely He who makes, for some, these things His chariots,
and "`rides as on the wings of the wind,`" can cause the change to take place,
as easily as a man turneth his water-course in his field.
It is likely, seeing I am now left as alone,
my safety may be in retiring entirely from the field, though I do not feel clear of Cork:
yea, there are other things which feel burdens hereaway; such as, I believe,
were brought from home at first; but surely the ways of wisdom are inscrutable.
May I be enabled to steer safely; and if I now return unrelieved,
ought I not to leave all to Him, without prying into His secret things?

Thus, having pretty openly told thee my present situation, I may, in great sincerity,
bid thee farewell.

[.signed-section-closing]
Thy affectionate

[.signed-section-signature]
S+++.+++ Lynes.
