== Chapter 6. Letters from 1801--1807

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Falmouth, Eleventh Month 21st, 1801.

For several days past thou hast been my companion in meetings and out of meetings; yea,
a sweet sense of the cleanness of thy spirit has covered mine,
so that I thought it no harm to tell thee so,
with a salutation of heavenly love in that life which triumphs over death,
which is precious, being begotten of Him who was, and is, and is to come;
the never-failing source of sufficiency to the waiting soul; such I believe thine is,
therefore trust thou in the Lord thy God forever.
No doubt thy trials are many;
the faithful among you must often be plunged as into the deeps;
but there is a power which is "`mightier than the
noise of many waters;`" this can enable to stand,
as with the ark of the testimony upon your shoulders, in the bottom of Jordan,
the appointed time, and to bring up stones of memorial from thence: this has, no doubt,
from time to time, produced the acknowledgment,
"`Hitherto the Lord hath helped us:`" but why should I thus write to thee,
who am very weak?

From Perran we came here; sat their First day meetings in silence on my part;
were housed on second day; turned out westward on third day,
taking two meetings at Redruth on fourth, one of which was with the people of the town.
In attempting to set forth the dangerous state I believed some to be in,
my spirit obtained no relief; for, if I am not mistaken,
the word was not mixed with faith in many that heard.
This is the place where dear Catharine Phillips lived and died,
but it is not always in such spots that the true seed nourishes the most;
we may be in this, as in all things, instructed;
but I am not saying respecting this place, "`There is none righteous; no,
not one,`" although my mind was oppressed;
perhaps we did not see the cream of the people.
Enough, however, of Redruth; and now let me proceed to say,
that the following day at Marazion, we had a very open meeting; it was also very large.
In that day`'s favor, the language of my soul was,
"`My spirit rejoiceth in God my Savior,
for He hath regarded the low estate of His handmaiden.`"
On sixth day a meeting with the people at Penzance; laborious,
but powerful and weighty in the end: a public meeting: at the Land`'s End on First day;
hard to get through, but it ended well; blessed be the Lord!
He measurably softened the stony hearts.
I walked after meeting to see a dying young man: my feelings were awful, yet,
in deep retirement, I believed all would be well.
"`Cry unto her that her warfare is accomplished, that her iniquity is pardoned,`" etc.,
comforted my mind respecting him.
He died next morning.
He was not one of our name--had been led away from the path of virtue by bad company,
but his sufferings had been great and availing.
I thought I never was more sensible of the powers of the world to come,
than as I sat by his bedside.

The reflection was and is pleasant, that we are on our way home,
having been to the end of the earth this way.
We have had four public meetings in this town, all large; and one in particular,
very relieving.
I thought it was a little like old times with our worthy predecessors,
as was also a large meeting at Penrhyn, when the pressure was such to get in,
that it caused a little disturbance.
I was on my feet, but took my seat in consequence,
after saying that it might be better for some one to go and inform those who were without,
that there was no room; but I soon rose again,
telling the people that no mind need be unsettled,
for I felt the power of God over the meeting; and all ended well,
even in thanksgiving and glory to Him who is only worthy.
I went to this meeting under peculiar discouragement, but had not well taken my seat,
before my mind was sensible of the everlasting truth being in dominion.
Oh! may my soul lie low before the Lord.
I could not have commanded this display of His excellency.
No; I am nothing, but He can arise as the sun in its strength,
and comfort and animate His true seed, that all may redound to His own honor.
I feel the same openness to thee as ever;
desiring the living breathings of thy spirit for my preservation--a poor child.
From hence we think of proceeding to Wadebridge,
taking meetings among other people in our way, and so to the north of Devon,
where there are few or no Friends, bad roads, etc.; but if the great "`I Am`" is with us,
no doubt difficulties will be surmounted.
No rest for me yet, but I am, at this moment, sensible of that which, in some degree,
can say, "`Not my will but Thine, oh Father, be done.`"
I have every reason to resolve--

[verse]
____
My life (if Thou preserv`'st my life)
Thy sacrifice shall be,
____

for He hath caused "`Jordan to be driven back,
and the mountains to skip,`" when I was without might,
and when things were permitted to weigh down my life:
when I was almost crushed under the heavy burden,
then He kept me from removing my shoulder from it; and in His own time He removed it,
showing Himself to be omniscient, and omnipresent, and omnipotent.
Eternally adored be His great name, saith my soul.
Let us pray for each other, that we may so abide under the baptizing influence of truth,
as more and more to be of the babes in Christ,
desiring to be "`fed with the sincere milk`" of the holy word, that we may grow thereby.
That in this day, God may have those among you and us, who are pillars in His house,
is what my mind craves.

We are here with Friends who are very hospitable, and I think,
growing in the root of living virtue.
At present they are under very great affliction.
But whilst we see that affluence and poverty are alike open to spiritual adversity, yea,
to sickness also, and to the varied family and private cross occurrences of life;
whilst this all tells us that our rest is not here, what a consolatory reflection, that,
in rightly yielding to tribulation,
it is the means of strengthening the union with uncreated Purity;
of preparing to join the heavenly host, where peace reigns triumphant,
eternally triumphant, when these few moments terminate!

[.letter-heading]
Joseph Gurney Bevan to Sarah Lynes.

[.signed-section-context-open]
Newington, Twelfth Month 5th, 1801.

[.salutation]
Dear Sarah,

I believe thou mayest rest assured that I do not forget thee,
and that thou art near to what I call my best feelings;
but they are not always--far from always--uppermost.
I rather think travelers, as they want more supply, have more;
but they must not expect we, poor stationary folks,
can always pay them in their own coin.

There are one or two things, respecting which I am not disposed to say much; but rather,
as we read Mary did, to ponder them in my heart.
One is, thy respite from some trying exercises; the other, thy future prospects.
As for me, I think I can judge best of the past, or, however, better than of the future;
and therefore, am disposed to say,
that the little personal share I had with thee therein,
(which was only actually at Croydon, though, may be, mentally at Dunstable,
the other day) has endeared thee to me as much as most things.
I don`'t think I have told thee how I fared after we parted there.
I began to think, before I had got far from the inn gate, that I loved thee too much;
but then there arose a pretty lively appeal to Him
whom we sometimes desire to call our Master,
that I loved thee for His sake: so I jogged on in some tenderness of mind,
and had also a very pleasant ride next morning towards Hertford, from the same cause.
While I am writing to thee,
and thinking of the satisfaction it must be to thee to be thus excused
(as above) there came into my head a few lines I once put on paper,
in imitation of a thought expressed by a Heathen poet, to this effect,
"`Snatch joyful the present pleasure, and leave the future trouble.`"
Methought, why may not the Christian say the same?
so I went a little on, somewhat thus--

[verse]
____
The cross endured, the Christian blest
With incomes of returning rest,
May seize the peaceful calm, and praise
The Guardian of his stormy days.
And while his memory brings to view
The troubles he has travelled through,
He finds his gratitude increase,
For past protection--present peace.
And e`'en if future troubles rise
In prospect to his watchful eyes,
With humble confidence imprest,
(Tried armour of the faithful breast)
The threatening future fails of force
T`'avert him from his steady course.
____

If thou canst pick anything out of these lines thou art welcome.
Well, fare thee well at present.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
J+++.+++ G. Bevan.

[.letter-heading]
Sarah Lynes To Ann Pumphrey.

[.signed-section-context-open]
Melksham, First Month 20th, 1802.

[.salutation]
My Dear A. P.,

My love toward thee is undiminished,
though the correspondence between us is not so frequent as before thou wast married.
I have often had thee very present with me in spirit, well aware,
that although the dispensation we are individually under is, in some sort, different,
we can unite in the acknowledgment that this is a world of trials,
a fight of afflictions; and oh! my dear,
if we are but working our way to the fairer inheritance,
it is worth all the present suffering;
so that I wish we may let patience have its perfect work,
while it is our chief concern that obedience keeps pace with knowledge.
My heart is enlarged in best affection towards thee, dear creature.

We have indeed used all diligence of late; holding meetings very quickly in succession,
and traveling hard: but one of those trying exercises we had together,
is more wearing to the frame than a great deal in the usual way;
and I may acknowledge that one of these overtook my poor tribulated soul at Bath,
a few days since; for after having five meetings there,
it was required to go into the Pump Room,
amongst the giddy and the gay (a great number of
whom were there) and stand as a sign for a while,
without saying a word; and then to declare, as the Lord by His Spirit gave utterance,
for about twenty minutes;
beginning with these words--"`I deem no further apology necessary for this conduct,
which may appear so strange to some of you,
than that I am here in pure obedience to my God.`"
Oh! my dear Ann,
the conflicts this sacrifice cost me were thoroughly
equal to any capacity given me to endure.

I have been almost worn out; my animal spirits much exhausted;
but a day or two mostly recruits me.
We are to hold a public meeting here this forenoon, one at Devizes this evening, etc. etc.

[.signed-section-closing]
Thy truly affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stepney Causeway, Fourth Month 20th, 1802.

[.salutation]
My Dear A. P.,

I find it impracticable to visit all my beloved absent friends by letter,
to whose dwellings my spirit is often wafted in feelings of sincere love,
but I let it suffice to do my best, and leave the rest; believing,
that while mercifully preserved on the right foundation, neither distance nor time,
sea nor land, shall be able to separate us from the love,
begotten and cherished in the fear of the Lord.
Thou well knowest, my dear Ann, that my time has not been mine own for years past,
nor do I feel it so yet, notwithstanding the family visit closed yesterday.
I have had, since coming home, three hundred and thirty-seven sittings of this kind.

I hope, that in fetching water for others,
thou and thy fellows have been watered at times.
I think, were it not for the brook by the way, in my late engagement of a similar kind,
I had many a time fainted.
We are mercifully dealt with.

[.signed-section-closing]
I am thy truly affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stepney Causeway, Seventh Month 14th, 1802.

[.salutation]
My Dear A. P.,

Think not that thy S. L. is less mindful of thee than heretofore,
because of the delay in writing.

In being informed of the bodily suffering thou hast experienced, I assure thee, my dear,
my heart ached; but I summed it up thus:
it will weigh amongst those things that help to sanctify the better part; and is,
therefore, instead of being unnoticed by the Most High, precious in His holy sight.
Ah! my dear Ann,
it seems to me a favor to believe that it is the prerogative of the King immortal,
to recognize the common occurrences of life, to take account of all our little affairs:
surely, if we sanctify Him, the Lord of hosts, alone, and if He is our fear, our dread,
we shall be taught by Him to esteem this a great blessing; and have to acknowledge,
that although, at times, we seem almost crushed under our exercises,
yet He "`weigheth the mountains`" to us "`in scales, and the hills in a balance.`"
Thus may we learn to trust His providence, and rely on His infinite wisdom.
My heart very tenderly salutes thee, and commends thee to so good and gracious a Creator,
in whom I know thou hast, in some precious measure, learned to confide,
and whom thou hast been taught to love.
I desire, that wherever we are, we may be enabled to remember each other for good.
I almost hoped, at one time, to have seen thy face ere I embarked for Ireland,
but now it does not look likely.
My mind has been, and is much humbled in the prospect before me;
and it was not without many tears that I laid it before
my friends in the Monthly and Quarterly Meetings.
They have furnished me with expressions of their concurrence,
and my credentials breathe forth desires for my safety.
Farewell.

[.signed-section-closing]
Thy

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Youghal, Eleventh Month 27th, 1802.

We have got through a large public meeting here,
which I think thou wouldst very well have liked to have been at,
had it happened in thy way;
for we were mercifully overshadowed by the wing of Almighty kindness,
which would have all to be gathered.
My heart was so full of matter that I could scarcely
keep my seat while the meeting collected.
I had to speak, with no want of utterance, for nearly an hour and a half:
the meeting ended in solemn supplication.
We have, I think, been helped with a little help from time to time:
it would be ungrateful to distrust,
or cherish unprofitable discouragement respecting the future,
but really these prospects of public exposure are
things that weigh down the mind very considerably.
Thou hast thine exercises in another way,
and I doubt not of their being as great as mine: we are differently dealt with;
we differ in our dispositions and complexion of mind,
yet we have one common Father and Protector, to whom, with the simplicity of children,
we may individually look for all we want.
This appears to me to be an unspeakable privilege.
Let us, my dear friend, strive to lay our secret cogitations, our cares, fears, doubts,
and sorrows, in His holy bosom.

[.letter-heading]
Joseph G. Bevan To Sarah Lynes.

[.signed-section-context-open]
Stoke Newington, Twelfth Month 4th, 1802.

[.salutation]
Dear Sarah,

Though I believe I love thee as much as usual, I don`'t seem to have much to say to thee;
and yet I begin to think it long since I said something;
and I have also apprehended thou wouldst not be so
well pleased that I had let thine lie by so long.
But consider the evenness of staying at home furnishes less
intelligence to an absent friend than the variety of traveling.
This variety, however, is, I hope, on thy part,
accompanied with an experience of the same gracious help which is alike wanted,
and which comes alike to the devoted, conflicting mind,
unaffected by the succession of scenes; even the mercy which is ancient, and ever new.
So be it to thee, my dear child, saith my soul most cordially--very cordially, however,
for it is difficult to say what is "`most,`" and
therefore I am often afraid of dealing in superlatives.

I think to send off this to-night,
and am rather less vacant in mind from other things than I like to be,
when writing to thee, my dear friend; but I am clear,
that among the mass of things with which my mind is furnished, there are always, I trust,
at bottom, genuine good desires for thee; and now,
that thou mayest be preserved during the remaining part of thy journey, in fear,
in humility, and in confidence in the power that has hitherto supported.
I feel something of the importance of endeavoring to meddle with thee.
Receive none of my words further than they answer to truth,
and when thou hast leisure and freedom, let me know where thou art,
and how it fares with thee.

I am sure (as far as we can well in absence, without special revelation,
be sure) that thou dost continue to believe me

[.signed-section-closing]
Thy very affectionate friend,

[.signed-section-signature]
J+++.+++ G. Bevan.

[.letter-heading]
Sarah Lynes To Ann Pumphrey.

[.signed-section-context-open]
Clonmel, Twelfth Month 15th, 1802.

[.salutation]
My Dear Ann,

The cheering account of thy family which thy last paper messenger brought,
was salutary to thy S. L., who often, very often visits Worcester in idea,
and breathes for the "`blessing of the everlasting hills,
and of the deep that lieth under,`" for some of you in an especial manner,
through your continued and increasing love to the cause of truth, which I know,
with its great Author, has been made dear to thee and thy S. P.; yea,
the prosperity of the Lord`'s work has often been more desirable in your view,
than the increase of earthly substance to yourselves.
Let us be encouraged to go on, seeking first the kingdom of God and its righteousness,
trusting in the promises.

Thou knowest how I used to be led along, when it was our lot to be together;
when we partook together of the "`wormwood and gall,`" in some most trying exercises.

I have, with humble gratitude, to acknowledge that my way now seems less rugged;
the dispensation of so much public exposure being, I trust,
through the holy efficacy of the Spirit, fulfilled, and, in Christ Jesus our Lord,
finished.
Thou canst better conceive than I can describe,
the release my poor mind experiences in being excused going into the streets and markets,
the prison-houses, and the asylums for the sick;
yet my soul hath sympathy in secret with the woes of my dear fellow creatures,
and from this I feel no desire to be exempt.
Since coming to Ireland, I have not been without seasons of probation, but may tell thee,
my dear friend,
that it never was my lot to witness more glorious
liberty in the sacred office of the ministry,
than at some meetings with Friends hereaway;
and then we are not yet out of Munster Province,
so that I know not what is to be met with in the other two.
If, in adorable mercy, preservation is vouchsafed on the right hand and on the left,
all will be well, come what will come; and I think this mercy is all my soul dare ask.

Farewell, my dear, farewell.
It does me good to feel so much attached to thee.
Thy dear S. will take a part.

[.signed-section-closing]
I am thy affectionate friend in gospel bonds,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To her Mother.

[.signed-section-context-open]
Dublin, First Month 2nd, 1803.

[.salutation]
My Beloved Mother,

I left Clonmel last sixth day week,
in company with my beloved H. G. and her brother Joseph:
we travelled in a post-chaise to the Leinster Quarterly Meeting.
Joseph is a very sensible young man, so that, what with his intelligent conversation,
and the reading of Cowper`'s Poems, which John Grubb presented me with,
we had an entertaining ride.
We needed something of this kind to take up our attention in a close carriage,
for there is very little in the country we travelled through,
especially at this season of the year, to occupy one`'s mind;
yet a part of the County Carlow is very fertile, and the scene beautifully diversified.
The Quarterly Meeting for elders and ministers began on seventh day,
and the whole was concluded on third day forenoon, with a meeting for worship:
it was thought to be a time of renewal of strength to many,
wherein the purity of the testimonies given us to bear, was held up to view,
and Friends encouraged to attend simply to the holy principle, which led,
and still leads to the support of these precious testimonies.
Several of the seceders attended,
and the call was reached forth to them to embrace the unchangeable truth,
which perhaps some of their poor bewildered minds have never yet done,
although they once held it in profession.
It pleased my heavenly Father to baptize my spirit,
and prepare me for enlargement of heart and tongue, in the Gospel of Christ,
in these meetings; blessed be His Name!
He chooses the "`things that are not, to bring to nought things that are.`"
His is the power and glory forever.
We had a public meeting for the people at large on third day evening,
in which strength was given to illustrate the doctrines of Christianity.
I was concerned to acquaint the people that, as an associated body,
we held these truths as they are recorded in the New Testament;
and that we believed in both the New and Old, which are like one continued chain,
held together by links.

I understand this testimony was a satisfaction to some not of our Society,
who were acquainted with the departure of individuals from what they, at one time,
professed to believe in.
Both the meetings here this day have, in the end, been seasons of relief,
in being enabled to minister of the word of life.
I desire a grateful heart for the many mercies bestowed;
and oh! may you also continue to witness the mercies of Providence to be new every morning.

We may stay here a week longer;
I think I see two public meetings for me to hold in this city,
and some families to visit, beside the meetings in course.
Oh! may Divine Goodness be near to help.
Without Him we are nothing, and can do nothing.

I have written my beloved mother a long letter,
and may now close it with bidding thee and thine most dearly farewell,
and am

[.signed-section-closing]
Thy truly affectionate daughter,

[.signed-section-signature]
Sarah.

[.letter-heading]
John Grubb To Hannah Pace (formerly Hannah Lynes.)

[.signed-section-context-open]
Clonmel, Fifth Month 28th, 1803.

[.salutation]
My Dear Friend,

It is, I trust, with a mind bowed with awe and fear,
under a sense of the importance of the subject,
that I venture to address thee on a matter which, perhaps,
from thy knowledge of the precious friendship and unity of spirit that
has long subsisted between thy beloved daughter Sarah and myself,
may not be much of a surprise to thee, viz.,
to avow my near and tender attachment for her,
and the desire of my heart to obtain her as a companion
in the closest and most endearing connection in this life.
It is now nearly six years since I acquainted my beloved parents with this prospect,
and obtained their consent to move in it at a suitable time,
which my late honorable father thought was not then,
on account of my endeared friend`'s religious engagements.
In his sentiment I acquiesced,
and have been solicitous to wait for a right opening to take another step.
I have lately apprehended,
that on dear S.`'s release from her late gospel bonds in this land,
it might be seasonable to lay the matter before thee for thy consideration;
and I hope the time is not far distant,
when I may be permitted to converse with thee more
fully than can be effected through this medium;
and have an opportunity of informing thee of any particulars
respecting my circumstances and situation in life,
that may be desirable to thee.

In the mean time, if thou feel no objection,
may I request thee to hand the enclosed few lines to my precious friend?
and now I shall, with the salutation of affectionate regard, bid thee dearly farewell;
desiring that the same good Hand that has, I trust,
laid the foundation of a closer connection and more intimate acquaintance,
may continue near for our help and preservation, in and through every situation in life;
and finally give us an inheritance amongst those that are sanctified.

[.signed-section-closing]
I am thy affectionate friend,

[.signed-section-signature]
John Grubb.

[.letter-heading]
Sarah Lynes To John Grubb.

[.signed-section-context-open]
London, Sixth Month 29th, 1803.

It is a comfort to believe that we, and the matter that engages our deep attention,
are under the notice of an all-wise and merciful Creator:
this I am abundantly persuaded of, amidst all the various cogitations that fill my mind.
+++_______+++ told me, among other things, that thou wast "`gooder`" than myself.
Well, I desire to follow after thine attainments.
I have the comfort of hoping that thou wilt help me;
and if we are but making advances in the right way,
I believe we shall look with a holy indifference at what man, as man, shall think of us.

I think that some of those seasons we have lately enjoyed in each other`'s society,
when we felt the sweet influence of our heavenly Father,
like a sanction to our attachment, may, from time to time,
be recurred to for our mutual and united strengthening.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Isleworth, Seventh Month 9th, 1803.

Sometimes I think it would be a want of right confidence in me,
were I to doubt this matter going forward and being accomplished,
because it seems to me to have been,
and still to be in the ordering of that wisdom which is profitable to direct,
both with respect to time, and the circumstance itself.
I write my thoughts simply, having only in view to assure thee,
that notwithstanding the prospect of separating from my
near relations and friends in my native land is trying,
I am disposed to mind a right opening.

I spent two nights agreeably at Joseph G. Bevan`'s:
he and I took some very pleasant walks alone:
he desired I would make as good a wife as +++_______+++. I thought
I would do my best in filling up the important station,
but felt, as I often do, a fear of falling short.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Isleworth, Seventh Month 16th, 1803.

I seem now almost as if already in Clonmel,
my mind is so much in the prospect of the settlement intended for me.
I often view myself a member of your meeting, and wish for holy preservation; yea,
that if I do go, our habitation may be like his where the ark was, which, it is said,
was blessed.
I well know that this is thy desire also, even so to conduct,
as to come in for the blessing which makes truly rich.
I trust, at times,
I feel thee near in that which is of a more exalted
nature than what is felt in the affectionate part,
and which is more binding than any outward ties:
thus I thought my spirit longed to impart to my dear
friend something of the favor granted in being lately,
in unmerited mercy,
permitted to draw near to Him whose holy bosom is the repository for the cares,
the sorrows, and conflicts of His own children, who are born,
not indeed of the will of man, but of Himself.
Oh! how have I longed to partake more largely of this pure nature; yea,
till the whole lump is leavened: but though it has, after low seasons,
pleased Divine Goodness in this manner a little to replenish my soul,
and fill it with holy desires,
yet I did not intend to be quite so copious in the acknowledgment of it.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Uxbridge, Seventh Month 20th, 1803.

Ah! my endeared friend,
our attachment is not indeed "`the sudden impulse of a moment,`"
but (as thou says) hath its foundation in the deeps,
and hath been proved by many storms.
Oh! may He who hath already blessed it in measure to thee and me,
continue to bless it as a thing of His own (dare I say) preparing.
Many of my dear friend`'s expressions are the fruit of a religion purchased
alone by resignation to the Divine will--the religion of Jesus Christ.
Alas! what would, what could a union like that which we now hope for,
be to either of us without such a possession?

[.letter-heading]
John Grubb To His Sister Elizabeth Grubb.

[.signed-section-context-open]
Isleworth, Ninth Month 9th, 1803.

The meeting yesterday was crowded.
Many friends from London and neighbouring meetings attended.
We sat under the gallery; Joseph Bevan by me, acting the part of father.
I thought much of you at home.
Mary Bevan and Mary Savory appeared in testimony,
before we moved to enter into the solemn covenant.
After this a considerable silence followed: the meeting then seemed about to break up,
when I found my dear S. was under considerable exercise.
She stepped up into the gallery, and was, I think I may say,
favored in a remarkable manner, to preach the Gospel to the people.
She said it was "`unexpected, and a cross to her, to have to move in that line that day;
but it was her chief joy to be found faithful in doing the will of her Heavenly Father;
and the solemn covenant being now entered into,
she felt her mind drawn in Gospel love to the people,`"
to whom she spoke a considerable time,
so that it seemed like one of her appointed public meetings.
She sat down a short time in the gallery, and then returned to her seat by her husband.

Mary Bevan moved afterwards in supplication, and then my dear S. in the same line;
we retired soon after.
The meeting was very quiet and solid, though it was very warm,
and much crowded in some parts.
Upwards of one hundred signed the certificate, exclusive of ourselves.
The bride was again engaged in the exercise of her gift after dinner.
The day was throughout, I think,
marked with that quiet and peace which is so comfortable to my mind,
and I hope satisfies it, without seeking for much beyond.
We have no other intention than to go by way of Holyhead;
and for the sake of the precious charge committed to my care,
I believe I shall not be willing to go to sea with a contrary wind.
My dear love to each of you, and I am

[.signed-section-closing]
Thy truly affectionate brother,

[.signed-section-signature]
John Grubb.

[.letter-heading]
Sarah Grubb to her Husband.

[.signed-section-context-open]
Clonmel, First Month 4th, 1804.

My first letter this year is to thee, my dear.
Nothing could exceed in my heart the tender emotions
which it has felt since thou left me;
but I give thee up to God, whose thou art, and whom thou serves.
He hath, I trust, instructed us, individually and unitedly,
that He ought to have our affections primarily, and that He is a rich rewarder.
Surely His goodness and mercy will follow thee, and repay thy simple dedication.

[.letter-heading]
To Elizabeth Grubb.

[.signed-section-context-open]
Myrtle Hill, Second Month 25th, 1804.

I think it would have done thee good to have been with us
in our late peregrination among the Western hills,
although I believe thou wouldst have got many a fright.
We often talked of thee when on very bad roads:
I think that from Skibbereen to Bantry exceeded all;
there were not only many rocky hills, but some deep places that,
had we been on horseback, I think we should have concluded were impassable in a carriage;
but no accident happened, which we esteemed a great favor.
We had a very large crowded meeting in a store, to satisfaction;
some of the soldiers were particularly solid.
At Dunmanaway the meeting was held in a Methodist meetinghouse,
and we thought it a very good one:
that at Inniskean was attended with some extraordinary power in ministering to the people:
it was held in a mill.
That, and the meeting at Passage, cost me a great deal of previous suffering;
but I have as much satisfaction now in reflecting on them as any others, I think.

[.letter-heading]
To Candia Burlingham.

[.signed-section-context-open]
London, Sixth Month 1st, 1804.

It afforded me considerable satisfaction to see thee at Worcester,
although the time was so short.
I sometimes think we do not want a great deal of
time to find out whether we can salute each other,
as those who are advancing in the path cast up for the redeemed.
In this high and holy way I trust thou, my dear, hast experienced thy feet initiated;
and if sensible that there has been in anywise a slipping, as it were, a little aside,
to gratify the unsubdued will and affections,
I would not have thee be too much discouraged; for,
as my mind hath been turned toward thee,
I have believed that thy Heavenly Father is near to help: therefore look to Him, my dear,
and seek to give thyself wholly into His keeping;
then will thy strength be increased to stand against everything, however small in itself,
that oppresses the pure life in thee:
thus wilt thou come to the experience of the promise,
"`I will be as the dew unto Israel (saith the Lord): he shall grow as the lily,
and cast forth his roots as Lebanon.`"
Oh! it is a precious thing to know the Divine presence to be as dew,
and to increase thereby in spiritual strength and beauty.
I know thou believes it to be so, therefore mayest thou follow after it, saith my soul!

I believe this has been thought, by some solid Friends, to be a favored meeting,
wherein the young people were not forgotten.

[.signed-section-closing]
Farewell, my dear.
I am, in much sincere regard,

[.signed-section-closing]
Thy friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Youghal, Ninth Month 9th, 1805.

I have thought, what do any of us want more than rest--perfect rest?
This is what our immortal spirits aspire after,
while we find that it is not to be obtained by any earthly good.
If this peaceful state is ours at last, surely it seems to me to be worth suffering for,
even by the privation of anything not eternal in duration; yes, health itself.
So let us be encouraged in thankfulness of heart
to press forward toward the place of our rest.

[.letter-heading]
To Ann Pumphrey.

[.signed-section-context-open]
Clonmel, Twelfth Month 2nd, 1805.

[.salutation]
My Beloved A. P.,

It is with peculiar satisfaction that I observe, from time to time,
the undiminished regard with which thou continuest to think of thy S. G. Were it not so,
my feelings would be poignant;
for it is trying to love without a return of the same lively sensation.
Perhaps my mind is almost daily with thee; I know it is often many times in the day,
for thou art as a dear sister to me.
Sometimes I think what an unspeakable satisfaction I should esteem it,
to have it in my power frequently to visit thee personally,
but even then I could scarcely name my feelings sympathy,
because our circumstances are not similar.
I know not what it is to be a mother, much less to be sensible of what,
from time to time, this station (however honorable) must have introduced thee into,
of anxiety, of hope and fear alternately;
and oh! when the hand of death took from thy bosom a darling infant son,
what must not thy S. have felt likewise!
Well, but I was going to remark that your conduct under these vicissitudes,
as evinced in thy letters to me, hath afforded me instruction, as well as,
on your account, comfort; and may I not say, thankfulness?

It is a fine thing, a great dignity conferred,
to be not only united in the solemn covenant of marriage,
with one whom Heaven does not disapprove,
but also to bring into the world beings designed for usefulness,
and the glory of God here, and eternal happiness hereafter.

My mother G. grows more and more feeble, as must be expected now,
for she is of a pretty great age; she has lived an honorable life,
and brought up many worthy children.
Farewell my dear, dear creature.

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
John Grubb to Stanley Pumphrey.

[.signed-section-context-open]
Third Month 9th, 1806.

[.salutation]
Dear Friend Stanley Pumphrey,

My dear Sarah has proposed my occupying a part of
this sheet in writing a few lines to thee,
which I willingly comply with;
and acknowledge thy kindness in transmitting us such a particular
and interesting account of the last illness and final close of
our beloved friend +++[+++Ann Pumphrey]. It tendered our spirits,
whilst we could, I trust, measurably rejoice and give thanks,
in knowing that this humble, diffident servant of her dear Lord and Master,
was so animated and strengthened by His almighty power, during the last awful conflict,
as to triumph, even gloriously, over death and the grave.

How does this reflection tend to blunt the edge of nature`'s sorrow!
Thou must, I think, my dear friend, have felt it as a balm to thy afflicted soul,
even the unshaken evidence that the dear departed spirit is centered in those mansions,
where, as she so livelily expressed it, "`the wicked cease from troubling,
and the weary are at rest.`"
May her pious, innocent example,
be a means of leading us who had the privilege of her company,
either in a greater or less degree, to greater attachment to that principle,
and acquaintance with that power, that did so much for her;
that so we may experience something of what the Apostle did,
that in all things and everywhere, we are instructed.

[.signed-section-closing]
Farewell saith thy friend,

[.signed-section-signature]
J+++.+++ Grubb.

[.letter-heading]
Joseph G. Bevan to Sarah Grubb, Then Traveling in Scotland.

[.signed-section-context-open]
Stoke Newington, Third Month 12th, 1807.

[.salutation]
Dear Sarah,

It is time for me to notice thy welcome letter,
and probably no topic of it is more interesting to thee than thy child.
Often, I dare say, thy mind turns to this little darling;
and the tender emotions of a young mother are often felt.
Nor would I have thee check them unduly, any more than indulge them unduly;
for whilst thou canst believe that thou still prefers thy Redeemer to thy offspring,
I consider thy maternal feelings in a manner sanctified; and I view thee,
and in degree rejoice in thee, as an object of Divine compassion and approbation.
Oh!
Sarah,
I think I feel now the preciousness of being the Lord`'s loving servant or handmaid,
who thinks nothing so delightful as to be helped by Him in His own business;
and I desire for thee that thou mayest, from time to time, as He sees meet,
have such renewals of attraction to Him,
as may bind thee closer and closer in His covenant of love and life.
So be it for you both; for, in going along with my pen,
I wish thy husband to partake of any encouragement to perseverance, if any I can give.
With love to you both,

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
J+++.+++ G. Bevan.

[.letter-heading]
Sarah Grubb To Anne Grubb.

[.signed-section-context-open]
Arbroath, Fourth Month 1st, 1807.

I have no doubt but thou feels for us in this our separation from you,
and in our awfully trying engagements.
I thought in meeting last evening,
of what the Apostle said of fighting with beasts at Ephesus,
for indeed there seems something of the same nature now to combat with.
Although the Gospel day has so long since dawned, the people, in too general a way,
cherish dispositions opposed to the purity and simplicity of this dispensation;
but I must acknowledge, through Divine mercy,
we are enabled to speak in the authority of truth.
The meeting at Dundee was held in the Methodist meetinghouse,
as no other commodious place could be procured.
We understood that the Methodist preacher prayed
in their meeting for a blessing on what had preceded.
We are to hold a meeting here this evening;
indeed we scarcely can get through any town without one,
but I hope we are given up to it without murmuring; nay,
are rather thankful to have the knowledge of the Divine will concerning us,
and I believe that none of you ever felt nearer or dearer to us than now.
Our little darling is, thou mayest be sure, the very frequent subject of our thoughts.
No mother could feel more exquisitely than I do,
but I endeavor to turn my own attention and that of my dear J. G. from the subject,
or it would tend to disqualify for religious service.
On the whole, I think there is nothing that could make this journey tolerable,
but being at times favored to come to the resignation of all into the Divine hand.
Oh! my dear sister,
I do not wonder that S. G. should call this state a "`harbour,`"
for how tossed and tried we are without it.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Aberdeen, Fourth Month 15th, 1807.

John told my brother Joseph of our setting about the little family visit at Kinmuck;
it was accomplished on seventh day, I believe, to mutual satisfaction;
and on First day we had rather a long meeting with Friends, which I thought was,
in the end, favored: perhaps one cause of its length might be,
that both visitors and visited went to meeting with rather
large expectations that we might be refreshed together,
and so had to wait in poverty till near the close.
They seem in general, I think, a nice, simple-hearted people,
and some of them very tender.
We parted in much love.

We were quite hurried to get to Inverary,
to a meeting appointed to be held at four o`'clock:
we did get there pretty near the time, but, on riding up to the inn,
I perceived that the meeting was gathered, which affected my spirits a good deal.
The people seemed rather raw and ignorant,
but we had to acknowledge to the sufficiency of that
Divine Power which ever stands by its own cause,
and returned with grateful hearts to Amos Wigham`'s, with him and his kind wife,
who accompanied us on horseback.

We gave up to have a meeting in a large assembly room here,
and to confine the notice to people of the higher class:
it was attended by many of this description,
and proved a season of much enlargement of heart in Divine love,
wherein I humbly hope truth was exalted.
Now think, my dear, how it was with me, when, after all this,
a cloud seemed still over our prospects of moving forward;
so we fixed to stay and have another meeting that evening in the same place,
and one at the old town today, a mile and a half off,
and to attend the Monthly Meeting here tomorrow:
thus we see how little we can depend upon our own exertions to get forward.
The meeting was large, and the doctrines of truth opened with great clearness,
and much Gospel authority.
Perhaps none of us ever saw so large a meeting, composed principally of gay,
fashionable people, male and female:
several of this description went from here to our meeting today at Old Aberdeen,
which was appointed at twelve o`'clock, and wherein new matter was given,
in the holy freshness and heavenly life; and, as in the other two instances,
much solidity was observed on the part of those who attended.
The meeting this day ended with a very solemn covering,
after my husband had lifted up the voice in supplication.
In the first meeting we understand there were seven or eight of the clergy present.

Our dear little babe engages our affectionate solicitude very strongly.
I often think how hard it must have been to Abraham,
when he was called to surrender his only son.
My heart is often more deeply affected in our present circumstances, than I choose,
or think would be right to suffer to appear.
