== Chapter 10. Letters from 1821--1823

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Bury, First Month 14th, 1821.

During our late journey into some of the southern and western counties,
thy dear brother and myself passed through many difficulties and trials,
some of which are only known to Him "`who weighs the mountains in scales,
and the hills in a balance.`"
There were seasons when my feelings put me in mind of what a servant formerly said,
of being "`pressed above measure,
and beyond strength;`" and yet have I not been entirely crushed:
thus that which seems too much for us, poor creatures, is rendered possible; and,
in all these things, are we made "`more than conquerors,
through Him who hath loved us and given Himself for us.`"
Oh! adorable love of our dear Redeemer!
He gave _Himself for us;_ whereby He hath shown us that the way to life is through death,
and encouraged us to continue with Him in trial,
that He may give us to triumph over all suffering; and that,
not only at seasons in this life, but in the end forever and ever,
with joy unspeakable and full of glory.
But my dear sister,
we have had not _only_ to suffer in fulfilling our duty for months past;
there were occasionally a few hours, particularly in public meetings,
when we were made glad in the sense that the kingdoms of this world
are more and more becoming the kingdoms of God and of His Christ.
How are the combined powers of darkness made to feel the spreading of light and life,
so that they are very busy, mustering, as it were, all their forces against the truth;
which, in many instances, renders the labour in the Gospel very painful and hard,
for the minds of many are intrenched against the simplicity of that which only can stand.

With respect to our religious Society,
we attended but few meetings where we had reason
to believe the seed immortal was in dominion,
yet in the general we were enabled to visit this seed where it lay,
which we esteem a great favor in passing along; and notwithstanding our backsliding,
I trust it may yet be said, "`Oh!
Israel, who is like unto thee?`"
but my fears have been many, lest, through the subtlety of the serpent,
we should more and more lose this distinction,
and become mingled with the world in its spirit;
and lest his various transformations should even prevail with many,
unto the removing them from their places,
like the dragon with his tail drawing down the stars from heaven;
for we have become so wise and so liberal, that,
even with divers of those first in rank amongst us, many things,
once deemed highly inconsistent with our holy profession, are yielded to with impunity.
It seems to a few, that some inexperienced minds are in danger of going out to meet _that,_
and of settling down in that which the true spirit of the Gospel leads from;
and so a scattering day, even in this respect, appears to threaten,
and in many ways are we likely to be spoiled.

But I want to tell thee that my mind is frequently sensible of fellow feeling,
in thinking of thee: I trust, that as often as is meet for thee,
the eagle`'s wings are mercifully granted thy waiting soul,
to rise superior to the most depressing sensations,
as a foretaste of that everlasting prize which awaits the finishing thy course,
when the sanctified spirit shall be eternally united
to those who are made perfect through suffering,
and are singing Alleluia to the Lord God and the Lamb, whose is the kingdom, the power,
and the glory, world without end.
Oh! it is a blessed thing increasingly to know, as we pass through time,
what it is to be so resigned to the Divine will in all things,
as to witness our Redeemer to take unto Him His great power, and to reign over all in us.

Some of the public meetings were so very still,
that when the power had got up into dominion,
on requesting the people to retire into themselves,
that we might commend each other to the Lord in silence, the solemnity has been so great,
without any sound whatever,
that it is like what we sometimes feel at the close of a great Yearly Meeting,
and the congregation seem loth to separate at last.
Oh! how far does this exceed all words; and what a testimony does it seem to me to be,
to silent worship.

[.letter-heading]
To +++_______+++, in Allusion to the Awfully Sudden Death of her Father.

[.signed-section-context-open]
London, Fifth Month 26th, 1821.

I have put my soul in your soul`'s stead, so far as I had capacity,
or that the difference of our circumstances would admit.
My spirit has been lifted up in secret for you, to the God and Father of all our mercies,
that He would be pleased to prove His sufficiency to you, in such a moment of extremity;
this, I trust, hath been the case,
not only in giving an assurance of the change being
a glorious one to your tenderly beloved parent,
but granting you the humble hope of His own fatherly care and protection,
as you continue to love Him.

Oh! how abundantly inscrutable are His dealings with us, His poor creatures;
truly He hath "`His way in the sea,
and His path in the great waters;`" and yet He shows Himself,
to His humble dependent children, to be "`mightier than the noise of many waters.`"
My mind is made thankful in believing that this is your
individual and united experience under the present dispensation;
and however, at times,
the overwhelming surge of affliction may appear almost too much for nature to sustain,
surely the everlasting arms of the omnipotent Lord will be underneath, and in due season,
the darkness of His providence will be made light unto you; therefore, my dear children,
sink down deep in your spirits, and wait upon the Lord Jehovah,
in whom is everlasting strength.
He designs that all things should work together for your good.
Oh! be simple-hearted, dear creatures, and look singly to the Lord,
and you will indeed find that He even fills the wide
chasm made by the relentless hand of death;
that while this awful undeniable messenger separateth forever the desire of the heart,
and the delight of the eye, He who remaineth is the never-failing, never-wavering Friend,
providing everything good for you, spiritual and temporal.
How are friends raised up for us sometimes, in an unexpected manner,
in our probationary state of being,
so that we are ready to acknowledge that we lack nothing;
thus I trust that He who is "`the Judge of the widow,
and a Father to the fatherless,`" will make way for you, dear children.
How did my nature long to be with you, in the very heart-melting scene you have witnessed.
I thought there would be some melancholy satisfaction in mingling my tears with yours,
and witnessing the last sad duty performed,
of committing to the grave the dear remains of my friend your father,
but I felt that the Lord had separated us.

The Yearly Meeting has, I think, so far been remarkably solemn.
Dear Huldah Seers has frequently opened her mouth amongst us,
"`in demonstration of the Spirit and of power.`"
She is a precious woman.
Nathan Hunt was led forth in living testimony divers times, in the Select Meeting.
They were days to be remembered on various accounts.
What a solemn covering was over the minds of Friends,
when George Withy mentioned his prospect of visiting the American Continent,
and when William Rickman gave in a short account of his travels there.
How different a thing it is to be an anointed ambassador for the Author of our salvation,
from that of speaking for hire, or divining for money.
I do not know that the contrast was ever more striking in my view than of late.

I was very grateful for a few lines received from cousin Margaret Grubb;
so was my dear husband: they tendered our spirits.
The mention she made of the consoling sense respecting thy
beloved father`'s preparation for so sudden a call,
bowed my mind in thankfulness; and my dear, thou knowest,
that as he was ready to put off mortality, and be swallowed up of life,
his dear mind was spared the pang of separation from his precious family,
and may be many feelings that otherwise might have pressed on his mind,
in the last hours of life, whereby he might have suffered,
and wherein you must have suffered with him.
Oh! how infinite is the wisdom and mercy of the Almighty.
I have thought in this thing, it will yet be found to call for thankful acknowledgment.

It is instructive to find that our dear cousin Margaret Grubb is dedicated as she is,
and willing to be spent still, in advocating the ever blessed cause of her dear Master,
though now in the decline of health and vigor.
Oh! surely, while the props of nature are giving way,
the building of God is going forward; "`the house not made with hands,
eternal in the heavens.`"
I think her crown of rejoicing will be great and glorious in the end.
It is a brave thing to serve the Lord from youth to old age.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month, 1821.

In the Select Meeting William Rickman gave a short, sweet,
humble account of his visit to America.
I thought I could have said, it was enough; the Master had been with him,
and He had increased him in His own increase;
and the heavenly image and holy likeness were more and more upon him.
I was glad to believe that this dear friend`'s spirit
is centering in that good in which it may,
ere a great while, be lost forever.

_29th._--For my own part I cannot approve of these great committees,
but others think differently.
Last First day my dear J. G. and myself were at Devonshire House both morning and evening;
I believe they were good meetings, the morning one particularly so;
for I thought the life ascended higher and higher, until it rose into dominion,
and we parted with hearts full of praise unto Him who only is worthy.

An address was brought into the Women`'s Meeting,
calling the attention of the inhabitants of Europe to the iniquitous
traffic still carried on in the persons of the African race.
This introduced my mind into great feeling that we might all be
found so cooperating with the Divine purpose in ourselves,
that qualification might be received to promote the
coming of the kingdom of Jesus in the earth,
by our individual obedience and dedication to the Lord in all things.
This was _my_ concern.
This day we have attended Peel Meeting.
I think truth did rise above all, but it was through hard labour for a while,
and plain doctrine was declared.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eighth Month 9th, 1821.

We heard last night that the poor Queen was dead,
and this morning the account is confirmed;
but no doubt you will have the intelligence before this reaches thee.
How very awful the thing seems.
The paper this morning tells us, that she desired, in the last hour, not to be disturbed;
that she was going to a better world.
I suppose the King is now in Ireland,
and that your city hath made great preparations for him.
It is very humbling to remember that he also must "`die like men,
and fall like one of the princes.`"
Alas! how fleeting, how fading, how empty are all the pleasures of a delusive world!

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Spalding, Eighth Month 17th, 1821.

It is worthy of remark, as affording encouragement to persevere in prayer,
that when the disciples appeared to themselves to be in imminent danger,
and cried unto their Lord, "`Master, carest Thou not that we perish?`"
He was "`asleep in the hindermost part of the vessel;`" thus,
according to their creaturely ideas,
regardless of the perilous situation of His followers;
but the sequel proves that it was not so, for, in due season,
He was mercifully pleased to arise for their help; rebuking the boisterous winds,
and the roaring of those mighty, raging waves, which seemed ready to swallow them up.
He is the same yesterday, today, and forever.
But how I write! as one strong in the faith; whereas I feel myself amongst the weakest,
and am almost afraid, that one day or other, I may make shipwreck of faith.
At other times I think I see the possibility of "`hoping
against hope,`" and seek for ability to say in my heart,
"`Lord if I perish, I perish at thy feet; and I will trust in Thee,
though Thou slay me.`"
Indeed I am often drawn to feel after the invincible foundation, and to desire,
above all things, to experience that it standeth sure; having this seal,
the Lord knows them that are His.
Oh! how frequently am I brought into darkness, and not into light; and then again,
in the needful time, light shines in obscurity, and the darkness is as the noonday.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Southgate Green, Third Month 26th, 1822.

I trust thou knowest what it is to experience painful feelings sent in mercy,
or I should say permitted, according to my own idea;
for surely nothing comes immediately from the Source
of happiness but what is truly joyous.
Thy mention of divers dear friends in your city is what we much like.
We hear little of our dear friends on that shore which we left from a sense of duty;
and whatever some may think of it, we know,
that did we see the way back in the light of truth, as we did to leave it,
our return would be with alacrity;
but the Lord knows best how to dispose of His poor little ones,
who cannot go one step without Him, but are like the helpless infant;
therefore we desire to trust in Him in simple dedication, not doubting but that,
if it be His sovereign will to lead us back to Ireland, He will open the way Himself.
After thy letter to me in Yorkshire, we pretty directly turned our faces homeward.
I thought I never held meetings in so much weakness of body, at any preceding time;
however, we were in mercy helped along, and reached home in the tenth month,
with a humble sense of having done what was required of us.
Dear William Tuke, of York, in his eighty-ninth year,
appeared in the full possession of his mental faculties, but quite blind.
Oh! how precious it was to sit by him:
his spirit appears to be quite ready to take its flight
to the glorious regions of Divine light and life,
whenever the awful mandate is heard to put off the mortal man.
This dear patriarch is cheerful and intelligent, even as a youth.

I hope +++_______+++ and +++_______+++ are learning increasingly
from Him who was meek and low of heart,
when, in His adorable love, He took upon Him our nature, and suffered for us.
The humility of Jesus Christ is the ground and foundation of all true religion; yea,
it is the very life of virtue and piety: without it,
in vain is all our pretence to the knowledge of God.
My heart`'s desire is that the great Disposer of events may, in His compassion,
avert the tempest that seems gathering in your land,
and turn the evil purposes of wicked and hard-hearted men to good account;
but surely His great Name is, as much as ever, a strong tower to the righteous.

As I was waiting upon the Almighty the other day, and thinking of Ireland,
my heart was sensible of much sorrow for the dark, distressed state of the people,
when suddenly my inward and spiritual eye beheld, as I thought,
a light shining over the nation, like the sun in a clear day,
and I had to believe that the time would come,
when the darkness would be dissipated by the arising of
the Sun of righteousness in the might of His glorious power;
and I became sensible that many of the poor deluded people,
being kept in ignorance and gross darkness,
were not so highly culpable in the sight of Omniscience as appeared to us;
and my cries were to the Lord,
that He would be mercifully pleased to pardon many of their offences,
and illumine them with His grace.
But how accountable must many of their pastors be,
and those who influence the minds of their fellow-men out of the true fear of God!

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Kennington, Fourth Month 12th, 1822.

The Lord`'s dear little ones are conflicted; even such who have none in heaven but Him,
nor in all the earth beside Him;
who really possess every blessing with reference to the Giver of all good, and in _Him._

Now if those who choose the Lord for their portion,
and the God of Jacob for the lot of their inheritance, have their faith thus tried,
surely it is only that they may experience the trial of
it to be more precious than of gold which perisheth,
and so endure to the end.
Many times I have a hope thou hast been sensible of our real fellowship with each other,
when I seemed as if I could not convey it in words:
indeed I am much of the mind that those who are mercifully
preserved in the blessed oneness of the disciples of Christ,
are truly helpful to each other in their varied exercises,
even without outward demonstration of it, and when far separated in person; so then,
if we are but of the _living_ stones, we shall be fitly joined and compacted together,
growing unto a holy temple in the Lord; and He will walk in us, and dwell in us;
we shall be His people, and He will be our God.
Is not this enough, let it cost us what it will of suffering,
to bring us into such a desirable state?
Since I wrote to thee, my endeared sister, many, very many, have been my tossings,
even as on the mighty billows;
but I humbly trust some of these painful dispensations have
tended more and more to reduce the will of the creature,
and bring into childlike dependence on my heavenly Father.
Oh! for a considerable time I lay as "`among the pots,`" during this last winter;
but I thought may be the Lord would raise me up in His own time,
if it was my endeavor to wait upon Him for preservation,
that I might be kept chaste in my love to Him,
who had been to my soul the chief of ten thousand; and so He did,
blessed be His Name! for I distinctly heard His voice again, and felt His power,
giving me to ascend with the "`wings of a dove,`" which are indeed "`silver,
and her feathers of yellow gold,`" even of that which had been tried in the fire;
so it is good not to cast away our confidence,
when we may seem to ourselves to be as a broken vessel.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Bury, Sixth Month 10th, 1822.

General indisposition has been my experience ever since coming back to this spot,
so that I have more than once thought it was high time to
quit the field of battle. My dear love is to your sweet flock.
Tell dear +++_______+++, the eldest, that the way to be happy is to be good,
to cultivate an early acquaintance with his Maker, and live in His fear.
I love you all tenderly.
Thou and thy precious companion have a great charge,
but I trust you desire to wait at wisdom`'s gate, and that it will not be in vain.
May Divine Goodness bless you in blessing, and multiply you in multiplying,
to the benefit of your dear offspring, and to the prosperity of His cause more at large.

I should have liked to have spent a little time with your dear aged father and mother,
if way had opened for it.
They are abundantly blessed many ways, particularly in their children.
How thankful I should be to see mine bending to the root of life, were they matured;
but I am convinced it is not too soon for me to watch
every opportunity of encouraging their minds herein.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Reading, Tenth Month 7th, 1822.

Thy state of health must have been a trying dispensation, but I trust it has,
like other dealings of a gracious Providence, been blessed to thee,
and possibly through thee to others; for as dear Job Scott says,
"`Sickness is a service which many owe to God;`" and if, by a patient,
humble submission to His Divine will, we can but finish our service to Him in our day,
it is enough, be the work designed us marked out as it may,
by that wisdom that cannot err.
Sometimes, in contemplating the happy condition of those beloved relatives,
now in the enjoyment of uninterrupted rest, who are made perfect through suffering,
and reflecting on the trials of time which _we_ still feel,
I am sensible of something like groaning in myself, and longing to be delivered also,
notwithstanding the awfulness of the subject, and my natural dread of the dark passage,
"`the valley of the shadow of death.`"

I hardly need tell thee that the present are truly fearful engagements,
and that my mind is much led down into baptisms; yet through all,
I have to acknowledge to the almighty aid of Him whom we desire to serve,
and whose to be.
Most of the meetings have been times of peculiar favor, as much so, I think,
as I ever remember; although to visit the immortal life, where it lies,
requires great abstractedness of mind, like sitting "`in the mouth of the cave,
with the head wrapped in the mantle.`"
Oh! sometimes, when in this situation,
how clearly has the state of meetings and individuals been opened to my mind,
even as plain as ever I saw the face of another with my natural eyes;
and in many of those assemblies made up of a mixed concourse of people,
their condition variously has been felt and spoken to, in authority,
which hath produced the language in my heart, "`This is the Lord`'s doing,
and marvelous in my eyes.`"
But oh! my dear sister, what awful ground a true Gospel minister stands on,
in the sacred office!
It puts me in mind of what the Majesty of heaven said to Moses,
"`Put off thy shoes from off thy feet,
for the place whereon thou standest is holy ground:`" indeed we must be thus unshod,
as it were, to receive and communicate messages of grace.
And for my part I find, from time to time,
the preparation as needful as if it had never been known before.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Tenth Month 15th, 1822.

Many a time since we parted, I have looked back to that hour with solid satisfaction,
for I trust "`deep did call unto deep at the noise of the water-spouts`"
being sensible of true sympathy with each other,
in the floods of affliction allotted us in our various situations and spiritual callings.
What a precious thing true unity is!
We feel strengthened in it and by it,
to persevere in the line of dedication to Him who
has a right to dispose of us as He pleases;
indeed it is in many ways "`a good and a pleasant thing.`"
I humbly trust, my dear friend, that this privilege will continue to be ours,
whether together, or separated in person; surely it will be so,
as we individually keep near that Power which hath already done much for us,
and at times hath been marvelously displayed for our deliverance from the waves of tribulation.

As to our engagements amongst those not professing with us,
I think I never had more blessed meetings than in this journey.
The doctrines of the Gospel flow freely almost from place to place,
and such is the gathering influence over us, that it seems to me,
that while these doctrines are declared,
the solemnity increases until the Divine Power is over the meeting as a canopy,
under which we mostly sit in silent, heavenly enjoyment for a short time.
This stillness I consider as a proof that the Lord is bringing the people
more and more to a sense of what it is to worship Him without vocal sounds,
and in it my spirit feels a holy joy.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Witney, Oxfordshire, Tenth Month 17th, 1822.

The present system in this country seems to be,
to give the youth amongst us all the learning their brain can possibly be exercised in,
and all the polish that would render them fit companions
for the great people of the world;
but I think that, even with respect to these things,
we should let our moderation appear unto all men;
nor do I see that there is much prospect in the general,
of the attention of young persons being so turned to the Divine principle in themselves,
as to make it very likely for us as a Society,
to have those valiants and ornaments produced,
which I believe to be consistent with the will of
Him who first gathered us to be a people.
I wish dear Ireland may yet be favored with the native
simplicity and purity of the Gospel,
which prepares for the reception of the holy anointing,
the pouring forth of the Spirit to the exaltation of the great Name,
and the edification of the Church.
There are very many amongst you largely gifted by nature, who,
if they did but fully yield to Divine grace, would be eminent indeed,
in that cause which is "`dignified with immortality, and crowned with eternal life.`"
If the time should come for us to meet on your shore,
I shall expect to see much improvement with respect to some of my friends,
for surely great has been the labour bestowed since we left Ireland.

After my return home I was many weeks very weakly indeed;
my strength seemed nearly exhausted, yet not feeling clear of some places about London,
and being sensible of an enlargement of prospect to these parts,
we could not see the way to resign our certificates, but in the faith,
requested more liberty of the Monthly Meeting; so when way clearly opened,
we left our dear children once more;
committing them to the gracious care of Israel`'s Shepherd.
As usual, we sat down together to wait upon the Lord just before separating:
it was a precious time, so that,
although our dear children had anticipated our absence very painfully,
I believe they gave us up freely to the service of
Him whom they felt to be goodness itself.

I may now tell thee that we have had many meetings
on this journey with those not professing with us,
as well as with Friends; they have mostly been, in the end,
seasons of some considerable relief:
I think the real state of things has been come at and spoken to,
in the blessed authority of the unchangeable truth.
Those meetings which we have held with a mixed company have generally, if not always,
been very crowded, and yet so still, that except by sight,
one would hardly have known that many persons were present.
In nearly all these opportunities, the living power has come into glorious dominion,
after all the baptisms and strippings attendant on such engagements; for I think,
from time to time my spirit is brought into a deep sense of my own nothingness,
even in a peculiar manner; and oh! frequently before meeting breaks up,
my heart is made glad that the Lord alone is exalted.
What a solemn sense of His goodness is mostly afforded in awful silence,
toward the latter end of a meeting crowded with people sitting and standing;
the bodily feelings are lost in a sense of the Divine influence.
Forever magnified and praised be Israel`'s God;
He is more and more bringing the people to the experience of true spiritual worship,
even in the silence of all flesh.
Whether we, as a Society, will become more spiritually minded or not, I cannot say,
but God will be glorified, and truth and its testimonies exalted in the earth,
even until all nations shall flow unto the mountain of His holiness,
which is set on the top of the mountains, and above all the hills.
The dead forms and empty professions, whether amongst us or others,
must yield to the living substance, and the eternal power;
but I fear that many under our name will wither more and more, and be taken away;
so great is the oppression of the life, and so dry are many meetings,
as to their general condition; so that I am often ready to say,
Oh! where is the living sap from the living root?
and while much is doing in works of benevolence, by our members,
there seems but little of that fruit whereby our Heavenly Father is glorified.

I hope the poor people in Ireland are much relieved by the
late exertions and great munificence of many in this country,
and I believe that kind Providence designs to open the eyes of those, in many instances,
who have been in darkness, yea, whom gross darkness has covered.
Somehow, I cannot but look forward for Ireland with hope of blessed days,
through the influence of the Gospel of light and life, and my very soul says amen.
We have, on this journey,
lodged at the house of two aged Friends--William Atkins and wife,
who knew me when traveling this way four and twenty years ago.
The age of W. A. is eighty-five, and that of his wife eighty-eight:
their faculties are clear: they were delighted to see me again,
and were both at meeting with us: the state of mind in which they are is truly desirable;
we took a solemn, and I expect a final leave in this mutable state.
It is encouraging to see the christian travelers
so far safe on their passage to a glorious eternity,
for they seem to have weathered many storms, and to have cast anchor in the haven,
waiting for a joyful landing on the blissful shore.

[.letter-heading]
To Elizabeth Grubb.

[.signed-section-context-open]
Eleventh Month, 1822.

I find it possible to travail in spirit, and sympathize with my friends,
without any outward communication;
and were not this the case with some toward myself likewise,
perhaps it would be worse with me than it is.
Thus, as members of one body, may we be a mutual help and strength,
wherever our outward allotment is!

When the time may come that we shall meet face to face I do not know,
but if it were in the ordering of Divine Providence,
it would be pleasant to me beyond what I can tell.

I hope thou art somewhat relieved from those very distressing feelings,
which have borne down thy mind, and almost absorbed those faculties so peculiarly bright,
and, I have no doubt,
designed abundantly to glorify the Giver of every good and perfect gift.

With a heart glowing with affectionate gospel love I salute thee, and say farewell.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Near London, Eleventh Month 16th, 1822.

The more thou art abstracted, and drawn into a state of waiting upon the Lord,
the more thou wilt come to see Satan, the accuser of the brethren, cast out, and,
as it were, bruised under thee, by the power which is above every power;
and thus thy great and mighty Deliverer will bring
thee up into the light where there is no disquiet;
thus shalt thou be made an heir of His gracious promises,
who "`giveth power to the faint,
and to them that have no might He increaseth strength;`"
and having learned resignation therein,
thou wilt be enabled to invite and encourage others to adopt the acceptable language,
"`Not my will, but Thine, oh Father,
be done;`" so shall thy soul yet be filled with heavenly
joy and consolation in His service,
where perfect liberty is known;
so shalt thou be enabled to bless the hand which has been laid heavy upon thee in affliction.
Let us be diligently watchful with that power which can yet rebuke all unclean spirits,
while herewith we guard against our own untoward tempers and dispositions,
that would lead us to murmur as the children of Israel did in the wilderness,
and were destroyed of the destroyer; and to "`tempt Christ as some of them tempted`" Him,
and were destroyed of serpents.

Oh! my dear child, there is a possibility of treading upon scorpions still,
in the eternal might of our Redeemer, and of knowing what it is to be preserved,
so as to overcome every hurtful and deadly thing.

And now I would just say that my dear companion and myself are about returning home,
having endeavored to fulfill the will of our Heavenly Father,
in an engagement of nearly eleven weeks in visiting Friends and others,
in divers counties hereaway.
We are very sensible of weakness belonging to us poor creatures,
while we have to acknowledge to the dominion of the power of truth in most of the meetings,
even in a marvelous and glorious degree.
I never knew it so generally so in any former visit,
more especially among those not professing with us.
Sometimes these meetings have held long, and the longer the more solemn,
while the doctrines of the Gospel have flowed freely;
and often I have had to say to the people,
"`Were I speaking to you from this time until midnight, and then to day-break,
it would all be to invite and gather to the influence which you now feel;
the blessed power and presence of God.
Let us sit under the heavenly canopy in reverent stillness, a little while,
and feel its preciousness,
beyond what words can set forth:`" and so it has been many a time--oh!
forever praised and exalted be Israel`'s Almighty Helper.
He is doing much, while He convinces us that without Him we are nothing,
and can do nothing.

_+++[+++About the same date.]_--Does trouble spring out of the ground?
Is it thus a spontaneous thing?
Surely no,
but every particle of its weight passes through the
scales in which the mountains are weighed,
and the balance which is in the hand of the Dread of nations;
even lest there should be more than could be supported by His dependent little ones;
so that, with the temptations or trials that assail us, a way is made for our escape.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stockwell, Eleventh Month 17th, 1822.

It is a favor that such is the oneness of the Church of Christ,
that all the members of the body, as they are kept by His power,
are enabled to feel with and for each other,
even without that outward knowledge and intercourse, which is, nevertheless,
very precious, and truly desirable in the Divine will.

Some of our meetings have held nearly three hours,
but it is enough that the Great Name is exalted,
and the Eternal Power raised by its own might into glorious dominion.

I much desire that we may be more and more united
in the inseparable love of our dear Redeemer,
and that He may hold us in His hand forevermore.

In low times we are perhaps ready to call in question that
which we have tasted and handled of the word of life,
as being really such, but "`he that thinketh he knoweth anything,
knoweth nothing yet as he ought to know;`" therefore does it please the Lord
to eclipse all former experience of His goodness before His dearest children,
that they may learn, from season to season, to depend on Him alone.

[.letter-heading]
To Hannah Huntley.

[.signed-section-context-open]
Witney, Eleventh Month 17th, 1822.

It is with feelings of tender sympathy that I have
heard of the trying dispensation allotted thee,
in the illness and decease of thy son.
No doubt thy affectionate and religious solicitude has been great,
but I trust thine Almighty Helper has given thee to see of the travail of thy soul,
and be satisfied, as it respects the exit of thy dear child.
I have thought much about him,
and feel a humble hope that his sufferings of mind and body proved as a furnace,
wherein He was chosen, and that all is well.
Thy dear son was not insensible to the awfulness of his situation,
and I trust the inward groan, the unutterable sigh, were graciously heard and answered,
by the eternal day opening to his view.
I hear he has left six dear children who are orphans;
may they be the peculiar care of the Heavenly Parent!

It is with considerable regret I give up the thought of seeing thee on this journey,
but our way does not appear to open to visit Burford this time,
nor some other places in this county.

Thus I wished to salute thee, my dear friend, both in sisterly affection,
and in that love which, many years back, united us together,
and which outlives all sorrow.
I write this by candle-light,
and cannot see so well as when thou and I were fellow-travelers,
_four and twenty years_ ago, but hope thou canst make it out, so as to understand it.

[.signed-section-closing]
I remain, with sincere regard, thy sympathizing and loving friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
High Wycombe, 1822.

I hope, my love, thou art so good as to find thyself happy.
I think much of thee, as well as of thy dear sister and your brother.
We have had nice accounts from J., which I consider a mercy from kind Providence,
and I feel glad to resign you all to the Almighty, in order to be engaged in His service,
in His own will and way; because, however dearly we may love one another,
we cannot promote each other`'s happiness,
but as we are engaged to do the will of our Heavenly Father;
and we shall be very glad indeed to go home, when He pleases that it should be so.
On First day we held a meeting with the people at Leighton, in the evening,
which was much crowded; many standing within doors, and very many without,
standing in the yard quite still.

I had a great deal to say to them of the goodness of the Almighty,
which they listened to with great seriousness and attention;
and then we were all silent for a little while, being sensible of the Divine presence,
beyond what any words can tell.
After this I believed it right to supplicate,
and at last we separated with much solemnity,
feeling that we dearly loved each other in the love of our great Creator.

Next morning we came on to Berkhampstead; there we appointed a meeting for the people,
which was quite as favored as that at Leighton; and the people who could not get in,
stood outside at the windows, and listened the same way.
They were very still, but there were two men who came in early,
that seemed to intend to be rude, and would sit at the women`'s side,
up near the gallery; however they appeared to grow quite serious after a little while,
for I believe they felt the Lord`'s power that was over the meeting, and so all was well.
Farewell my love.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Bury, Third Month 30th, 1823.

"`All things work together for good to them that love God`"--there is much in it.
We are hereby given to understand that _none_ of our painful
feelings pass unnoticed by the Judge of all the earth,
whose wisdom and mercy are infinite, and we may be assured He is the rich rewarder.
To be accounted worthy to be tried in the furnace,
and to have it heated to more than the usual degree,
is the way to become of the fine gold; for while "`the fining pot is for silver,
the furnace is for gold;`" and it is to such that the living, eternal word goes forth,
"`I have refined thee, but not with silver;
I have chosen thee in the furnace of affliction.`"

The creature will feel distressed, when it feels that it must be nothing,
that the Great Name may be all in all.
We must be willing to lay our bodies even with the ground, to be walked over,
to feel ourselves as the dust, again and again,
if we come to be altogether of God`'s workmanship, and His works praise Him through us,
as well as in us; and most assuredly He will favor the dust of Zion,
and honor those in whom He delights.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Bury, Fourth Month 7th, 1823.

Although it is not very easy for me to write,
yet I take the pen with pleasure to address thee, my friend,
my old acquaintance and _tried friend,_ who has often felt for me,
and for whom I also often felt, and still continue to feel;
having no doubt that many are thy low times, and even perhaps, at seasons,
the language of thy mind may be,
"`From the uttermost part of the earth have we heard songs, even glory to the righteous;
but I said, My leanness, my leanness: woe unto me!`"
Now it is encouraging to recollect, that this distressing state was that of Zion,
the Lord`'s own precious seed; and indeed, were these not tribulated,
how could it be evidenced, to the glory of God and their salvation,
that they are His chosen, and that He keepeth them as the apple of His eye?
I believe, my dear sister, that even so will He keep thee,
and grant thee the reward of the faithful; for who hast thou in heaven,
but thy Almighty Helper; or in all the earth besides Him, that thou desirest?
seeing that thou hast long since proved that good is to be found in Him,
and that even our temporal blessings are possessed in Jacob`'s God,
whom the righteous choose for their portion, and for the lot of their inheritance.
I frequently think how pleasant it would be, if I could sometimes sit down by thee,
and unbend as in days that are past; but seeing that is still prohibited,
it is a favor that we can make use of this substitute for personal interviews,
and a yet greater favor that neither distance of
space nor time diminishes our mutual love,
nor separates us from that which is in itself inseparable,
even the unity of the spirit of our Heavenly Father in Christ Jesus, who are one,
and whose people are one, through all the floods of temptations,
and the waters of affliction or baptisms;
indeed all these painful feelings do but tend to strengthen
the true fellowship which is the bond of peace.
Many times, in my distress, have I thought of thee and some others,
knowing the sympathy that would be excited by my illness,
especially towards my precious partner;
and I trust your tears and prayers have not been unavailing;
he has experienced the everlasting arms to be underneath in the deepest distress,
and witnessed the succour which no human aid could afford.
Oh! how awful was that season when I thought the
ties of nature were about to be dissolved forever;
when, for a moment, resignation to such a stroke was veiled from me;
when I looked to the Giver of every good and perfect gift, to enable me to say amen;
when my very soul clung to life, for the sake of my dear husband and children;
for I saw nothing retained against me that could hinder, or stand in the way to glory:
my sins appeared to be washed away in the blood of the Lamb,
and to have thus gone beforehand to judgment: but let me tell thee, my loved sister,
that _that_ which is impossible to the creature, as such,
was made possible in my experience,
by Him who taught me once more to believe--to believe in His righteousness,
and in the perfection of His wisdom, as well as in omnipotence; so that I could commit,
not only myself, but my all into His hand, as into the hand of a faithful Creator.
It was then,
oh! that was the moment when I received the spirit of prayer in the unerring will of God;
I asked Him to spare me to my family for awhile;
and then I heard His Divine voice--__I knew__ it was His--"`I will spare thee.`"
I bowed in humble gratitude, and said, "`I thank Thee, oh!
I thank Thee.`"
Yet was my mind fully sensible, that in the dispensation which had overtaken me,
I had suffering inexpressible to pass through;
indeed I had not previously any idea that human nature
could sustain the distress of the whole animal system,
which has been my portion.
Oh that it may have a tendency to leaven all my dispositions, more and more,
into the heavenly nature of Him who was nailed to the cross for our transgressions;
for surely it is not for nothing that we have to pass by the gates of death,
nor drink as of "`wormwood and gall;`" but what should I have done,
had it not been for a measure of that healing balm which sweetens every bitter cup?
or where should I have found repose, had not that blessed influence,
which made the Psalmist`'s bed in his sickness, condescended to be near,
a present help in the needful time?
Oh!
I still feel, that without my Savior I am nothing, know nothing, and can do nothing:
when He withdraws Himself I am, in my own sight, truly despicable and wretched;
and to this sense of my condition am I often left, but my soul resolves, in His fear,
to wait upon Him, and not distrust Him, for I have never found a better way.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stockwell, Fifth Month 5th, 1823.

May it please Divine Goodness to increase the number of those amongst the dear youth,
who are "`skilful in lamentation,`" and valiant in the most glorious cause.
There is occasion for it here too,
for few comparatively are prepared for the Lord`'s service,
for want of cooperating with His power in the heart.
My soul is often poured out, as it were, before the Most High,
that He may be pleased to visit our dear children with a peculiar sense of His love;
well knowing that it is not enough to be preserved in a state termed innocent, but that,
if any are brought into a fitness to glorify Him in their right allotments in His Church,
it must be by an acquaintance with the baptism of the Holy Ghost and fire.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dover, Sixth Month 25th, 1823.

The very serious accident +++_______+++ met with, affected me with awfulness on hearing of it.
What an escape he has had!
All these things are teaching,
and should prove incitements to entire dedication to the
service of Him who holds our breath in His hand,
and whose right it is to dispose of our time and faculties as He pleases,
even to His own honor and glory.

I feel much for +++_______+++ and +++_______+++,but yet have a hope
that all their difficulties may work together for good.
Our Heavenly Parent sees meet to suffer us to be tried in a way most repugnant
to our natural feelings, that we may become conformable to His Divine mind,
and that the lowly seed of life in us may gain the ascendancy.

I suppose your relatives are now with you.
It is pleasant to associate in true friendship:
from such intercourse our intellectual enjoyment is heightened,
and we are reciprocally benefited.
I believe that such is the design of our great Creator.
Dear +++_______+++, please say to her, that notwithstanding the happy prospect now before her,
as to temporals, her felicity will be much enhanced by a willingness, in all things,
to become a humble follower of Him who hath exhibited a
perfect pattern of self-denial and true lowliness of mind.
Oh! how precious is true gospel simplicity.

_27th._--I wrote most of the foregoing on fourth day, but was unable to proceed,
from pain in my face, ear, etc.
I had this pain the day I left you, and mostly since;
but it increased so much for two or three days, as greatly to impair my strength,
and was attended with loss of rest and appetite; so yesterday I sent for a surgeon,
who soon relieved me in degree, by making a deep incision in the roof of the mouth,
where he said an abscess had formed,
that at once accounted for the great suffering I had felt.
I am much better today, and hope soon to be restored to my usual state;
but thou seest all these things are against my progressing in health as we hoped for,
by coming all this long way from home.
To speak plainly about our coming again to the seaside, I can only say,
that had I not sought Divine counsel, as I mentioned to thee,
it would have been doubly discouraging, since our tarriance here,
to meet with so much obstruction to using the means for promoting health and strength;
the weather has been unfavorable, and it seems as if I could not keep from catching cold;
but I may confess to the goodness of Divine Providence, in that His power has, I think,
been exalted in some meetings which I have been able to attend,
including the Quarterly Meeting for worship,
and also in some more private seasons of religious retirement.

We had the satisfaction of seeing Steinkopff for a few minutes yesterday morning.
I was under much suffering, lying on the sofa,
when this heavenly-minded man spoke comfortably to us:
he addressed +++_______+++ very impressively and sweetly.
I had never met with him before: he and his wife went pretty immediately to the packet,
and sailed for Calais.

This Dover is a wonderful place, or rather the surrounding scenery.
How grand is the view from the Deal road!
The lofty and venerable castle, the cliffs, the majestic opening between them to the sea,
contrasted with the verdant fields in the valley at the right hand,
the interspersion of trees and villages, with the river gently gliding along,
all inspired my mind with delight, and raised my heart in praise to the Author of nature,
while my body was in pain.
Surely these beautiful prospects must be doubly pleasing in vigour of body, etc.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eighth Month 4th, 1823.

I hope thou hast the reward of peace,
in thy obedience and submission to thy Heavenly Father, who is, I humbly trust,
preparing thy mind to be a dedicated servant of His, a good example to those around thee,
wherever thou art, and to have the blessed reward of the righteous, even in this life.
Thy painful feelings, my precious +++_______+++, are His baptisms,
dispensed to thee for thy good,
that thou mayest be as a clean vessel in the house of the Lord.

I would encourage thee to look to thy dear Savior,
who was wounded for our transgressions, and bruised for our iniquities,
that by His stripes we may be healed.
Oh! how glad I am that He hath measurably made Himself known to thee, dear +++_______+++,
and that thou lovest His appearing.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Norwich, Ninth Month 24th, 1823.

I ought to esteem it a favor to be employed at all by the Great Master,
or to be made sensible of what is His blessed will concerning me,
yet I wanted to get home and be hidden.
We had a brave meeting at Tivetshall.
I do not think I was much short of two hours on my feet.
It seemed to me that the power of truth rose higher and higher,
until it triumphed over all, to the great relief of my mind.
May the Lord have all the praise of His own marvelous works.

I feel my detention in this city very much.
I am a poor insignificant creature.
It must be that the weak things are indeed made use of in the great cause,
or surely I had been left out.
Oh! how do I dread the engagements now before me!
I am so weighed down under a sense of my own insufficiency unto any good word or work;
and yet, in reflecting,
surely it is here I rest in my spirit--that the sufficiency is not of us,
but of Him who calleth us into His work.
