== Chapter 12. Letters from 1825--1828

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Eighth Month 30th, 1825.

The _most_ desirable state of mind before the Father of mercies is that of true contrition,
for He hath said through His prophet, "`I dwell in the high and holy place;
with him also that is of a contrite and humble spirit,
to revive the spirit of the humble, and to revive the heart of the contrite ones.`"

Trials we must have in this world, and what a favor it is,
when they tend to unite us more closely to Him who, for our sakes,
became a man of sorrows, and was acquainted with grief;
whose life exhibited a perfect pattern of true humility,
and submission to the will of the Father.
Surely it is they who have fellowship with Him in suffering, who shall reign with Him;
being even joint heirs in His unspeakable glory.
Oh! adorable mercy, vouchsafed to poor, unworthy man!
How does the thought of such infinite love melt our hearts!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Eighth Month 31st, 1825.

[.salutation]
My Dear Friend,

I am glad thou couldst write me so comfortable and kind
a letter as I received the other day from thy pen;
I say comfortable,
for I thought it breathed a disposition to be directed and supported by the unerring,
all-sufficient principle with which thou art not unacquainted,
as being in us a monitor and guide:
that thou art low and afraid of missing thy way I am not sorry for,
thinking these feelings may induce thee to cry the
more mightily unto the Fulness of Strength,
where no sincere soul supplicates in vain.
I dreamed lately that thou wast indeed low,
and felt the need of an assurance that thou wast one of those who so run as to obtain.
I wish it may be so.
Remember, my dear friend, that "`the race is not to the swift,
nor the battle to the strong,`" but the persevering soul,
or those who hold out to the end, shall be saved.
Oh! that thou and thy dear husband may be much acquainted
with the waiting state to which the promise is,
they "`shall renew their strength; they shall mount upward with wings as eagles,
they shall run and not be weary, they shall walk and not faint.`"

[.signed-section-closing]
Dearly farewell, saith thy affectionate friend,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To her Children.

[.signed-section-context-open]
Hereford, Ninth Month 15th, 1825.

I often think of you, my beloved children,
in looking round at the beautiful scenery as we ride along,
in this county and Worcestershire; almost wishing you could set your eyes upon it.
About Malvern it is delightful.
I remember being on some of those high hills before I was married,
and writing to Clonmel about it, when I related how our company sat down on the grass,
and had to adore the Author of the visible creation, while we admired His works.

I think it likely we may have a meeting here tomorrow, in a great new town-hall.
Richard Burlingham and wife, from Evesham, are with us.
I hope you will be a little family of love, and the God of love be with you,
my dear children.

We must learn to bear trying feelings, even the sense of our own frailty, with patience,
and in a humble hope for a perfect change of heart.
So farewell, all of you, saith your affectionate mother,

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Charlbury, Ninth Month 24th, 1825.

The public meeting was held at Birmingham, to our comfort, it being a living,
powerful time.
Many friends at Birmingham recollected my former labors in and about that place;
and many, whose company I had in those days, both in and out of meeting,
came to shake hands with me, on seeing me again, expressing their love,
and saying they were much pleased;
indeed my hand was quite swelled with taking so many of theirs.
I do try to commit you into the good hand of an Almighty Being,
believing that what He permits is for our real benefit.
Farewell, my dear children.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Tenth Month 4th, 1825.

I know that the times of refreshing are worth waiting for,
and I am not disposed to work myself up into a belief,
that because I have been engaged in so solemn and sacred a work as the ministry,
I must therefore of course be sensible of heavenly consolation,
immediately on my retreat as from the awful field of battle.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Twelfth Month 4th, 1825.

What a long time it is since I communicated a word to thee in this way,
but not so in spirit, for my mind is with thee more often than the day;
indeed it often seems to me, that I travail with thee in some degree,
and of late feel more easy about thee, than was the case some time ago;
for even when it was not with me to send anything by way of letter,
I thought thou wast in a situation which felt to thyself to be that of hourly jeopardy,
and my heart has been lifted up in prayer to thy God and mine, that,
for His Name`'s sake, He would be pleased to help thee with a little help, yea,
to encompass thee by His own omnipotence, that nothing might either harm or hinder thee.
Now I feel encouraged to hope that thou mayest adopt the language,
"`In all these things we are made more than conquerors through Him that hath loved us,
and given _Himself_ for us.`"
Be thou therefore strong in the Lord, and in the power of His might,
even when thine own weakness is present with thee; and hope against hope,
for the trial of our faith is more precious than of gold that perisheth.

Poor +++_____+++! _His_ death put me in mind of Jane Pearson`'s address--"`Lord,
the wickedness of man is great,`" and the reply--"`My mercy is greater.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Twelfth Month 25th, 1825.

[.signed-section-signature]
My Dear Friend,

It is gratifying to me to be assured of thy continued affectionate remembrance,
and I can assure thee that I have not forgotten to love thee,
nor to desire for thee every good that our all-wise Benefactor sees meet;
and may the same blessing be with all thine.
It is pleasant that thy dear husband and thyself could attend the late Quarterly Meeting,
and more so, that you had to experience true profit therein:
may you more and more eye the leadings of truth, even in _all things;_
counting nothing too near or dear to give up for its sake;
so will you be increasingly blessed, and made a blessing.
Ah! my friend, what will all the world be to us in a little time,
when we must answer to the solemn inquiry,
"`What hast thou done with thy Lord`'s money?`"
when having faithfully occupied with our talents will prove
of infinite and everlasting advantage to us.
But it was not with a view of writing thus that I took my pen,
yet we ought to endeavor to "`provoke one another to love and to good works.`"
I am not sorry that thou canst mourn the want of
more Divine life and energy among your little company.
I can believe that you often sit low, but dig deep, and persevere in laboring;
so will the inexhaustible source be opened from time to time,
to the refreshment of the weary soul.

Farewell my dear friend, and believe me to be, as ever,

[.signed-section-closing]
Thy affectionate and grateful friend,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Second Month 14th, 1826.

A letter received yesterday prepared us for the mournful tidings which came this morning.
You know that we do and must feel for you,
but the consolation of so full an assurance that the sanctified, redeemed spirit,
forever rests in the Lord, cannot fail to mitigate even thy sufferings,
in the loss of one who was given thee for a companion, by the mighty hand of Jehovah.
I need not say much now, hoping to see thee.
I had been much with you in mind,
for two or three days before the affecting intelligence arrived;
and the very morning it came, I had thought I would write to thee.
I waited in deep retirement two or three times that day,
and could come at nothing more than a sense of sweet quiet; so I said in my heart,
the will of the Lord be done; in life or death, all is well.
Farewell, my very dear friend;
my spirit commends thee to Him who is a strength to the needy in their distress.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Third Month 26th, 1826.

Although distance by sea, as well as land, separates us in person,
I trust we sometimes commune together in spirit,
meeting at the feet of our Divine Master, who is omnipresent;
beseeching Him on behalf of each other, as well as on our own account,
that He may preserve us by His power,
and pour the consolations of His love into our souls in His own time,
which is ever the best time.

Thou speaks of being much distressed at times,
and even that it is seldom thy lot to experience delight,
by being brought into the presence of thy soul`'s Beloved,
where there remains to be fulness of joy,
and at whose right hand are those pleasures which endure forever; yet, my dear,
I hope the everlasting arms are underneath, to sustain thee in all thy painful feelings,
and that having to drink deeply of "`the wormwood and the gall,`"
thou mayest profitably remember it in days of less suffering,
and be able to strengthen and encourage others to
take the cup of salvation as it is offered,
and to call upon that mighty Name which is thy confidence.
And now, having but little instrumental aid,
it is my hope that thy standing may be the more firm,
even upon the Mount Zion which cannot be removed.
Oh! how tenderly do I feel for thee, being situated as thou art,
and called to so great a work; yea,
my heart yearns toward thee in the love of our dear Redeemer,
to whose safe keeping and succour I am engaged to commend thee,
and indeed thy dear sisters too.
E+++.+++ is as "`the King`'s daughter, all glorious within:`" it is said of such an one,
her raiment is of wrought gold.
Oh! saith my soul, may the King of kings dignify you more and more with this clothing,
which none can bestow but Himself;
and may you thus evince yourselves to be of those
in and through whom His works praise Him!
Ah! He is worthy, my dear children,
that all we have and are should be dedicated to His honor, all the days of our life.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Fifth Month 1st, 1826.

The funeral of our late worthy friend, M. P., was largely attended.
It is a happy release to the dear departed,
whose purified spirit was no doubt fully prepared to join
the triumphant Church in those realms of glory,
too dazzling for us whilst inhabitants of these frail tabernacles.
It is comforting that some of the dear youth promise, by their dedication,
to fill the places of individuals who rest from their labour.

I seldom can speak of _enjoyment,_
when retreating from my feeble efforts for the exaltation
of the great and glorious cause of universal righteousness,
but I am content in the Lord`'s will.
He is, in His own due time, a rich rewarder.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month, 1826.

Oh! my dear,
I may tell thee that the Ancient Glory has indeed
descended amongst us in different meetings,
and the Most High has been for a spirit of judgment in a remarkable manner.

There are many nice young people at this Yearly Meeting.
It seems, with us and you, a peculiar time of favor to this class,
and of pouring out of the heavenly anointing in the ministerial gift.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Sixth Month 6th, 1826.

I take the pen to comply with thy kind request to be informed how I got through
my visit to +++_______+++. First day forenoon was very exhausting to me,
the meeting at Devonshire House being rather long and exercising,
and then I went immediately to the man`'s house,
+++_______+++ and +++_______+++ kindly accompanying me.
He readily admitted us, although he was up-stairs on the bed.
He seemed full of talk: I requested him to be still, and then cleared my mind to him,
and immediately after retired, without any further conversation.
I was enabled to speak very plainly, and in an awful strain,
so that I hoped he felt what I delivered, as a warning to prepare for his latter end.

Be assured, my dear friend, that my mind is frequently turned toward thee,
and thy beloved partner in life,
desiring that every painful feeling may be blessed to you, and through you,
by your becoming more and more the Lord`'s servants,
as I assuredly believe to be His design.
You are increasingly dear to me I trust, in that which endureth,
even when the joys and sorrows of time shall terminate forever.

I hope you were comforted together by the visit of
Isaac Stephenson and his amiable consort.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Seventh Month 7th, 1826.

It is a great and awful thing to be a vessel moving in Him who is the "`glorious Lord,
the place of broad rivers and streams, wherein goeth no galley with oars,
neither doth gallant ship pass thereby.`"

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Chelmsford, Eighth Month 13th, 1826.

I assure thee, my dear child,
that many times my soul commends thee to Him who is everywhere present;
and strong are my breathings to Him, the Lord, for thee,
that thy mind may be endued with grace to enable thee to
keep those good resolutions which I know thou hast formed,
but which Divine power alone can fulfill.

I hear there has been a very nice letter from that dear, worthy American, Isaac Hammer.
I did not doubt but his Divine, all-gracious Master would be with him,
for he seemed to me to be in pure dedication to _His_ call,
and with the eye of the mind continually turned to the heavenly anointing.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Eighth Month 18th, 1826.

And now let me say that I much hope none of the things that are from without,
move thee from the steadfastness which is in Christ Jesus our Lord;
may they rather have a tendency to give thee to stand
more firmly on this invincible Rock;
may you individually experience the truth of that scripture,
"`They that trust in the Lord shall be as Mount Zion, which cannot be removed.`"
How wonderfully has the Almighty dealt with you!
He has not withheld His chastisements, that you might know you were His by adoption;
neither hath the washing-pool been closed,
whereby you might be presented a fit offering unto Himself,
prepared as clean vessels to receive of the holy things which pertain to His kingdom;
and how hath He, your Heavenly Father, borne up the drooping spirit,
when some of you have been ready to faint!
May you not then well say, "`The Lord Jehovah is my strength and my song;
He also is become my salvation;`" and doth He not require that
there should be a willingness to show forth His salvation,
in His own way, according to the pointing of His heavenly anointing?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Ninth Month 2nd, 1826.

I have thought, for some days, when looking toward you,
how greatly the Psalmist was tried many times,
and how he always found refuge in the Lord his God.
One time I think he says, "`Turn Thee unto me, and have mercy upon me;
for I am desolate and afflicted.
The troubles of my heart are enlarged: oh bring Thou me out of my distresses.
Look upon mine affliction and my pain.`"
I believe that the same everlasting Source of sufficiency
will hear and answer your prayers,
my dear cousins; and again my soul fervently commends you, individually, unto Him.

Well, my dear, let us all look beyond secondary causes of trouble, perplexity,
and outward loss, to Him who can turn them all into blessing;
who hath His way in the clouds, and in the thick darkness;
so will His righteousness be revealed in His own time,
when He will give us to offer to Him the tribute of thanksgiving,
and we shall learn more and more to trust in His holy name,
who is worthy forever and ever.
Amen.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Same date.

I remember a time when I was under most trying feelings,
when my soul distinctly heard a language like this, "`Have patience;`" and with it,
as I turned to the voice which spake,
my mind was enabled to sink down into resignation and quiet;
willing that the creature should be mortified and brought into the dust,
which is so needful for us, that, in all things,
the eternal power of truth may be set up and magnified.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, probably 1826.

[.salutation]
My Dear Friend,

By some mistake I find we have brought away a pocket handkerchief,
which I conclude belongs to thee;
surely thou mayest suppose it needful to have an eye to us next time we come;
but are we not (to use an Irish phrase) _honest thieves,_ as we return the goods?

It is pleasant to take a little retrospective view of our late turn-out among our friends:
I do not love you any the less for it;
indeed I have a hope that some of you are rather nearer in union with that Spirit,
which brings the disciples of a crucified Master
into the eternal fellowship of light and of life;
which nothing here below is of itself able to dissolve.
Let us all endeavor to make still further progress in this happy experience,
by standing fully open to the Divine mind in all things.

[.signed-section-closing]
I subscribe myself thy--__your__ affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Chelmsford, First Month 17th, 1827.

None of us ever come to be well-grounded in righteousness, but by tribulation;
and I well know there are times when we seem to be alone in what we feel,
thinking no one ever was introduced into similar distress:
this is in order that we may cleave closely to the Almighty as our Friend,
and not look too much outward.
Surely He who, in the days of His personal appearance among men,
carried our sorrows and bore our griefs, is pleased to care for thee,
and designs that thou shouldst know Him in the character of Comforter as well as Savior.

I hardly need tell thee that my mind is much with thee,
greatly desiring that _that_ good work which is begun in thy heart,
may be carried on and completed, to thy enduring consolation,
and the glory of the Great Name.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Chelmsford, First Month 30th, 1827.

I wished thy dear father to write to thee this time,
but he told me he knew not what to say,
and he thought once a-week quite too often for us to write.
Thy father and I finished the family visit here last First day,
having paid sixty-six visits, besides the dividing of many families,
where they had servants and apprentices.
We think it may be right to sit with the families of the
other two meetings which belong to the Monthly Meeting.

Remember, my love, that the more the capacity is enlarged to suffer,
the more joy also it can receive when the night of sorrow is past;
when the happy morning of delight dawns upon the mind.
While I wish thee to be resigned to the dealings of thy Heavenly Father with thee,
it is also my desire that thou wilt not unnecessarily give way to distress.
Remember that fear hath torment, and cast it off,
possessing something of a holy indifference as to what may be thought of thee,
save by Him who knows the heart.
We must even be content that _good_ people should not highly esteem us.
May Divine compassion and love be with my dear child, saith her affectionate mother.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Fourth Month 13th, 1827.

I find I must be satisfied with the failure of these bodily faculties, sight, hearing,
etc.: the poor tenement gives way, but sometimes I see, with an eye of faith,
as "`through a glass darkly,`" something in store, ever-enduring in its nature;
a life which lives through death; faculties of the immortal part, which,
instead of decaying, increase in vigour;
endowed with capacity to know and enjoy Him who was, and is,
and is to come--the Author and Source of every good; and then again I know nothing,
and am in a state of trembling, and abhor myself most truly.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month, 1827.

I believe that none can fully comprehend the distressing
feelings of one daily sinking under indisposition,
but those who are the immediate subjects of it; yet I know that your minds partake,
in no common degree, with the object of your tender solicitude, in her sufferings.
I hope, however, that you experience the support of those everlasting arms,
which are ever underneath in time of trouble,
for the strength of the Lord`'s tribulated children, whereby their heads, as it were,
are kept above the billows.
May He who pitieth those who fear Him, comfort and strengthen your hearts; even He who,
in the riches of His mercy,
will vouchsafe to be the portion of your dear sister forever.
Oh!
I do humbly trust that the God of all grace is very near to you now;
that He will be more to you than you can ask.
How often does my spirit commend you all into the holy arms of His protection, yea,
and salvation!
He remains to be a Father to the fatherless,
and a Friend that adheres more closely to His humble, submissive ones,
than the nearest outward connections can do.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month, 1827.

This morning the women`'s meetinghouse has been well filled, without much crowding;
and I think there is some cause to hope that the great Legislator,
to whom many of us look, even as the eye of the servant to his master,
has not turned away from us as a people, but is still disposed to do us good.

It is indeed by a surrender of our all to the Lord,
that some of us can be prepared to attend this annual solemnity with any degree of courage,
such as we ought to feel, if soldiers of Jesus Christ.
Great is the exercise of my poor mind, as in former times at Yearly Meeting;
yet when I can see things going on well, I am repaid for all.
It seems to me that the Women`'s Meeting has increased in weight.
We seem, at times,
permitted to dwell a little under a sense of that
want of spirituality which prevails in individuals,
in too general a way,
and consequently in our lesser meetings scattered over the counties;
but if I am favored with anything of true discerning,
the Great Master is pleased to bless the united exercise of those who are engaged in
a secret travail after the resurrection of the ancient and everlasting life of truth;
so that this well springs up again and again, to the watering of the flock.
Oh! blessed be Jehovah!

Our ministry wants correcting in many instances, yea, purging: the Lord do the work,
saith my soul, or else this glory of true, living gospel ministry,
may withdraw more and more, and reach the mountain hard by,
instead of spreading and prevailing among us,
so as to induce those not immediately of our outward fold,
who nevertheless are gifted to preach Christ, to come and say,
"`Let us be called by thy name.`"
The Lord will send forth His word in the earth with authority,
"`in the demonstration of the Spirit,`" and it shall reach the heart,
whether the ear of man be gratified, yea or nay.
But let me not forget that the blessed anointing is pouring out in this day,
on the children of our Society, so that some of them cannot hold their peace;
which shows how unwilling Divine mercy and wisdom is,
to remove the crown of righteousness and of true simplicity, wherewith He hath,
with His own hand, crowned His people; and I have thought, during this Yearly Meeting,
it may yet be said, "`Who is like unto thee?`"
as applying to our community:
indeed all who embrace the Gospel receive the same unction which we profess to wait for,
and to be influenced by; and the testimonies of this Gospel are as immutable as itself.

I tremble for the future sittings of the Yearly Meeting as it regards myself, a poor,
burdened creature; but if the Lord and His truth be exalted, it is enough.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
London, Fifth Month 20th, 1827.

What a blessed thing it would be if +++_______+++ should become eminently
separated unto the Great Master and His glorious cause!
This is never the case, but through peculiar suffering.
We have been rather on the watch for information
of the release of our precious Elizabeth Moore:
a happy change I fully believe it will be for her;
and the more she has been buried with Christ by baptism into death,
the more gloriously will she reign with Him, her Savior.
How truly comforting it is to my best feelings, to think of this dear child of heaven,
which I have long done much more often than the day.
Thy account of dear +++_______+++ is reviving and precious.
Oh! may the unslumbering Shepherd watch over her by day and by night;
enabling her to meditate in His Divine law through each,
even in the night of adversity and in the sunshine of joy;
and may she be eminently qualified to call others home to Him, the Lord.
On fourth day morning we met as a Yearly Meeting.
Yesterday the summary of the answers was brought in.
While we have these statements,
which give the Yearly Meeting to understand how things are among us, as to the outside,
I feel desirous that we may get down to that heavenly source of intelligence,
by which we may be able to feel what condition we are in, as a religious Society,
with respect to an advancement in the truth;
and so be prepared to sympathize and render some true aid to the body,
while we prostrate ourselves in the presence of Jehovah,
with whom is everlasting strength.
Vocal labour has often devolved upon me:
I am sensible of the effects of such exertion on my lungs,
but I consider it a great favor to be anointed for the solemn work of the ministry; yea,
I magnify mine office, while I feel that to me belongs blushing and confusion of face.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dover, Sixth Month 25th, 1827.

Thy kind letter has been forwarded to this place.
We came off sooner than was at first intended,
as I found myself so debilitated that I lost all
prospect of attending our Quarterly Meeting;
indeed the use of my limbs seemed fast leaving me,
nor have I yet recovered from the pain and weakness which
the fatigue of attending Yearly Meeting appeared to produce,
although considerably improved within the last few days.

The situation of the house we lodge in is most beautiful; having a full view of the sea,
the scene is ever varying.
Another family is here, occupying the drawing room, etc.
Last First day they came to the afternoon meeting, bringing one or two with them.
They told me they understood I spoke in our meetings,
and they and some of their friends wished to hear me.
I replied that our meetinghouse doors were always
open for any who pleased to give us their company;
that our meetings were often held in silence;
that I could not say it would not be so when they came, for we waited upon the Lord,
and if we felt anything arise in our hearts to speak,
believing that He would be with us in what we had to say, then we spoke;
otherwise we considered it right to refrain from words.
They, however, came, and I was engaged in the ministry a considerable time.

At Rochester, being there on a First day, and some not of our Society coming in,
I think I had to speak altogether, morning and evening, more than three hours.
That was to have been a day of rest, but it proved one of much exhaustion of strength,
as to the body; yet I can say that the Lord is worthy to be served,
even with our latest breath.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Eighth Month 26th, 1827.

It has been trying to my feelings, so long to withhold a word of sympathy in this way,
since the removal of our precious Elizabeth; I trust, however,
that you are individually assured that my heart is deeply sensible
of the poignancy of that suffering which has been yours,
under so proving a dispensation, and the chasm which still continually presents itself;
but when we consider the weight of glory which the dear departed inherits to all eternity,
in the room of shackles, often hard to bear, from a decaying mortal frame,
shall we not rejoice and give thanks?
ever adoring the name of Him who was her invisible strength, sometimes her song, and who,
in the riches of His grace, did become her salvation forever.

[.letter-heading]
To her Brother.

[.signed-section-context-open]
Chelmsford, Eleventh Month 6th, 1827.

[.salutation]
My Dearest Brother,

I do not like to omit addressing thee with a line or two,
if it is only to say that I think much of thee, with sisterly affection:
we are separated in person, but I trust united in spirit; going on, as it were,
hand in hand, in the tribulated path which terminates in everlasting rest:
how sweet will be that rest,
seeing it is prepared and bestowed by Him who hath washed us in His own blood,
and given us to have fellowship with Him and the Father!
I humbly hope that I am not in a presumptuous spirit, while writing these lines;
being well assured, that if we partake of the rest prepared for the people of God,
it is all of His free mercy.
That I sympathize with thee, my brother, is no marvel;
I have something of the same feelings (which are
of a trying nature) both in body and mind,
being greatly depressed, at times, with infirmity: this complaint,
which pervades the system, affects my nerves very much; I often fear, too,
lest it should put on the form it once did, when I was brought near to the grave;
but why _fear?_
it is the flesh which shrinks from such extreme suffering; besides,
I think my constitution now is so weakened,
that there would be no probability of my sustaining such an attack;
but I will endeavor not to anticipate,
only to stand disposed to meet the Heavenly Father`'s will, who doth all things right.

Perhaps thou art aware that my dear husband and myself are engaged, at times,
in holding meetings with the people at large, in this county:
it is truly a great and solemn work; I may, however,
gratefully acknowledge that we have so far been favored
to experience the Divine Master to stand by His own cause,
and assist His poor servants to labour faithfully.
It is surprising how a mere nothing, like me, should, from time to time,
become a channel for the word of life to pass through,
or even that the physical strength should be sufficient for the exertion,
seeing I am really often very poorly, and equal to little in common-place matters.
I must tell thee that the opposer of all that exalts the kingdom of Jesus,
has seemed to me to stir up his wrath against even the feeble attempts we, poor things,
are concerned to make for the promotion of righteousness and truth;
he has been permitted to beset me with divers discouragements, so that, at times,
I have well-nigh fainted; but the Lord hath held me up,
and enabled me to resist the attacks of the grand adversary, so that I can say renewedly,
"`The Lord Jehovah is my strength and my song; He also is become my salvation.`"
I must now say farewell, being thy very affectionate sister,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Twelfth Month 14th, 1827.

Thou knowest that it is sometimes the case that the Lord`'s dearest
children are permitted to feel distress to that degree,
that they are ready to exclaim, "`Is any sorrow like unto my sorrow?`"
indeed it seems to me that those who are designed to declare
most loudly concerning the efficacy of living faith,
have their portion of this precious virtue most nearly tried,
in order that they may prove it to be an anchor, both sure and steadfast,
in the greatest tossings;
even when the waves and the billows may roll over our poor vessel;
so be not over-much cast down, but endeavor to do thy best, and leave the issue to Him,
by whom "`Wisdom is justified of her children.`"
The enemy of our peace and of God`'s glory,
would sometimes whisper murmuring and rebellious thoughts into us,
and almost make us believe that they originated with ourselves,
that we might despair of victory over ourselves;
whereas the Lord knows how we abhor such gainsaying,
and desire to have our wills wholly lost in His Divine mind;
and if we quietly turn from the evil suggestions of the old serpent,
looking unto the Fulness of strength, I fully believe,
that in all these things we shall be made "`more than conquerors,
through Him that hath loved us, and given Himself for us.`"
Oh! how cheering the hope that eventually we may triumph
over all that could prevent our consummate happiness,
and that forever and ever!
What are a few fleeting years, even were they replete with sorrow,
when put in competition with eternal, ineffable joy?
Let us take heart,
and humbly endeavor to commit the keeping of our souls to the blessed Redeemer in well-doing,
even as unto a faithful Creator and High Priest.

I have not, to this day, discovered a better way than to trust in the Lord my God,
even should He slay me.
To whom shall we go?
Shall we not still wait upon Him whose words are gracious,
and who hath indeed the words of eternal life?
Will not His heavenly ear of pity be open to our cries and sighs, all helpless as we are?
Yes; and He will yet give us to confess, "`I am poor and needy,
yet the Lord thinketh upon me.`"

We may be humble without undue depression; nay,
I am inclined to think that the meekness of Christ leads _from_ a disposition that way.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Twelfth Month 14th, 1827.

[.salutation]
My Dear Friend,

Had I not expected to see thee, on the moving occasion of dear +++_______+++`'s interment,
I think thou hadst received a line from me before that occurred,
for I wanted to tell thee that thy letter was very acceptable, and did me good.
I love to see that thou art not faring sumptuously every day, even in spirituals;
for we are so apt to forget our own frailty,
that to be constantly at the banqueting house might
render us less hungry and thirsty after righteousness,
and so less diligent in seeking, and asking, where our dependence is for every good.

It was much my desire to be with Friends last fourth day week, at +++_______+++,
and had arranged matters accordingly; but near the time appointed to leave home,
my dear husband was attacked with a complaint occasioning much pain: this discouraged me,
and made me hesitate; so that when the chaise was ready, instead of going toward,
I went in it to meeting here; but so strong was my attraction to be with you,
that after meeting the chaise was again brought to the door,
and again my dear J. G. was in great pain, after having been rather better;
then my heart failed me, and I quite gave up leaving him,
but did not feel lightened by it; and what is remarkable,
when it became too late for me to set forward, he grew better,
and has been pretty well ever since.
Thus, I said to myself, "`Oh! thou of little faith "`--indeed, my dear friend,
the little grain of this virtue which may be in my possession, has,
in a particular manner, been tried of late.
Yet thanks be unto Him who giveth the victory, when I have gone forward,
I have had the acknowledgment raised within me,
"`In all these things we are more than conquerors, through Him who hath loved us,
and given Himself for us.`"

Hoping soon to have the pleasure of verbal communication, I bid adieu for the present,
and subscribe myself

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
First Month 6th, 1828.

I am still prevented from making progress in the great work before me,
of holding meetings with the people in this county.
My faith is often nearly tried, but is it not said,
"`the trial of your faith is much more precious than of gold that perisheth?`"
I have truly passed through much probationary exercise since I saw thee;
and again there have been times when all these things
are comparatively light in the scale;
the love of God, and a glimpse of the glory that shall be revealed, preponderating,
to the unspeakable joy of that part which shall live beyond the grave.

I think few have to wrestle like myself, with Him who alone can bless.
Perhaps my mind is naturally more prone to wander from the Source of good,
than is often the case with such as love our Lord Jesus Christ in sincerity,
as I humbly trust I do.
Sometimes I think how glad I should be to have a
soul as innocent and resigned to the Divine will,
as my friend; yet who knows but we may meet by and by where,
instead of fighting with the enemies of our souls,
all is triumph and joy in Him who said to His disciples, "`Be of good cheer,
I have overcome the world?`"
Even so, my endeared friend.
Farewell.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, First Month 12th, 1828.

Few meetings of Friends have ever been more faithfully labored with than this,
or more covered with power and glory than has many times been the case here,
through the ministry of the eternal word.
Surely it would be no marvel if another dispensation came,
even wherein there would be a famine of this word; for I do not apprehend that,
take us altogether, we are as much improved as we ought to be.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Third Month 5th, 1828.

[.salutation]
My Dear Friend,

It often seems remarkable to me, that when thou wast with us,
there should have been so much interruption to our social comfort:
it was as if the pleasant pictures _were_ to be spoiled; we did, however,
as I humbly trust, mingle, in some measure, in a higher joy,
even the joy of which the holy Author of all happiness spake to His followers,
and told them that no man could deprive them of it.
After all my sorrowful feelings many ways,
I do believe that the more unhesitatingly we deny ourselves, take up our daily cross,
and follow Christ, the more of the heavenly treasure, peace and joy,
is laid up in store for us, poor and frail as we are.
So be encouraged, my dear friend,
to endure mortification and suffering in the will of Him
who hath undoubtedly called to a preparation for His service.

My movements for many months past, have been marked with peculiar uncertainty;
perhaps for the further trial of my faith,
and to prove whether I would endeavor to stand in the dedication or not,
under feelings very trying to nature.
It was much my desire to prosecute the engagement of holding meetings with the people,
so as to be released from the service before now, but that has been impracticable.

Thou hast probably heard of the awful event of +++_______+++`'s decease.
We trust he was prepared to go, as he seemed to be more and more fit to live;
being increased, I hope, in the increase of God, although he made no great show,
being rather a retired character.
How true it is, that "`in the midst of life we are in death.`"
He was only forty-five years of age,
and industriously engaged for the maintenance of his family.

[.signed-section-closing]
Thy truly affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Dublin, Fourth Month 26th, 1828.

I am glad thou couldst pray for me;
perhaps I never stood more in need of such intercession.
We have got through the sitting of the Select Meeting this morning.
I think it was a good time: Friends appeared truly glad to see me,
and enquired with much interest for thee.
Brother Joseph gave in the report of the meeting for elders having been held,
and when he mentioned that the Society in this land
was favored still with a living gospel ministry,
I felt thankful, and had to express something of it.

_28th._--We were at Sycamore Alley both fore and afternoon, and I think that it was,
upon the whole, a day of favor: in the morning the power of truth rose higher and higher,
until it was in dominion.
This day has been very exercising, but the good thing predominated in both meetings.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Dublin, Fourth Month 30th, 1828.

This day we have had a meeting for worship, which was, I think, a remarkably favored time.
I never experienced the ministry of the word of life to have more of a gathering effect,
until the blessed and glorious power of truth was over all, for some time,
in profound silence.

I have hoped that thy prayers for me have been availing,
for I think I am unloading by degrees.

_Fifth Month 3rd._--Now I have to tell thee of the conclusion of the Yearly Meeting,
which was with solemn silence yesterday evening.
Friends say this has been a remarkably favored Yearly Meeting.
R+++.+++ Fayle told me the other day,
that the Men`'s Meeting was one of the most solemn they had known for a long time,
and without much preaching.

I visited the Men`'s Meeting: it was an open, solemn season.
When leaving the meeting, my way seemed clear to say farewell,
and to let Friends know of the affectionate solicitude which the
partner of my life had felt and expressed to me for them,
before my coming to this Yearly Meeting.
I believe it was received in that love which he feels for the Society in this land.
