== Chapter 13. Letters from 1828--1830

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Fifth Month, 1828.

Well for thee, my dear,
that thou loves the immutable truth! mayest thou continue to do
so! so will it be thy comfort and support in times of trial,
when thou art under the sensible feeling of deprivation,
with respect to many things that are gratifying to the youthful mind.
Thy Heavenly Father has seen meet to afflict thee,
or rather suffer thee to be afflicted in some measure,
but He hath drawn thy mind near to Himself,
perhaps even making thy sufferings a means thereof;
so that I hope thou knowest what it is to commit thyself into His holy hand,
in the acknowledgment that He knows best what is best for thee.
May this disposition continue to be thine; so will all things work for thy good,
and thou wilt be enabled to preach righteousness in thy life and conversation,
and have thy reward both now and hereafter.

It is not always those who are qualified to be the most _conspicuous_ religious characters,
who are the most acceptable with Him who sees not as man sees,
but it is those who are wise enough to be obedient to the Divine will,
who shall "`shine as the brightness of the firmament;
and those who turn many to righteousness shall be as the stars forever and ever.`"

Now if we do but come to eternal glory at last,
no matter what we have to pass through in this world; for time, compared with eternity,
is but like the drop from a bucket in the ocean--it is lost there.
Yet, my dear,
I would have thee partake of every temporal enjoyment which may be thy portion,
in the will of the Almighty Creator, who giveth us of all things "`richly to enjoy.`"
Improve thy natural understanding by suitable books and study;
it will make thy time pass more pleasantly; but do not risk thy health by these things:
it is not worth while.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Same date.

The Epistle from Philadelphia is thought to be particularly satisfactory.
It is comforting that Friends on that side the Atlantic find strength,
in a Yearly Meeting capacity,
to express themselves so decidedly encouraged to persevere in the good old way.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Seventh Month 28th, 1828.

I am still led forth with the invitation of the Gospel to the people,
to come to the dear Redeemer: speaking, however, in these lofty barns is very exhausting,
the labour of the voice being much greater than in
those houses usually occupied on such occasions;
but if the power reaches to the people`'s hearts, and inclines them to seek the Lord,
all the rest is but trifling in comparison.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Chelmsford, Tenth Month 16th, 1828.

May Divine power and goodness keep thee, my dear sister and friend,
and enable thee to strengthen the weak,
to hold up the hands of those who war against the enemies of Israel,
and give thee thy reward into thy bosom;
may He bless thy children and thy children`'s children!
Come health or sickness, life or death, thy beloved brother,
as well as his partner in sorrow and joy,
do desire to be found in that allotment which Best Wisdom appoints.
My present trials appear to me to be like the breaking of the sixth seal,
when there was "`a great earthquake; and the sun became black as sackcloth of hair,
and the moon became as blood; and the stars fell from heaven,
as a fig-tree casteth her untimely figs.`"
Occasionally I hope that I may be come thus far,
and then there is but one more seal to be opened; and on its opening,
there is "`silence in heaven for half an hour.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Hastings, Eleventh Month 14th, 1828.

What are we without tribulation?
How erring! how wandering!
I blame myself for the absence of that holy confidence,
that humble trust in the name of Jehovah,
which would give me to be less moved in affliction,
and perhaps teach me gratitude for the blessing of having
it in our power to do so much for the promotion of health,
instead of grieving that there is occasion for it.

I look toward Chelmsford with a longing desire still to call it home,
if this might be in the Divine will; but for a considerable time past,
I have felt as if my rest there was breaking up,
and almost as though no more place remained in it for religious labour,
except in winding up; and what shall we say,
but "`Good is the Lord,`" and "`Let Him do as seemeth Him good.`"

If it be right for us to pitch our tent elsewhere, I hope the same glory will go before,
and be the reward, which has been vouchsafed in previous movements.
Now thou knowest, that be this in ever so small a degree,
the certainty attending it stays the poor mind,
enabling it to trust in the "`Strength of Israel.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Probably 1828.

My dear friend`'s letter gladdened my heart,
not only to find that thou hadst such a very agreeable return home,
but that thy mind is so fervently turned toward Him who has already done much for thee,
and who is waiting to perfect His own work in thy happy experience.
It is indeed, as thou remarks, no easy attainment to the creature to say,
"`I am the clay,
Thou art the Potter,`" but the more we endeavor to
commit ourselves to our great High Priest,
the sooner we find the truth of His assertion, "`My yoke is easy, and my burden light.`"
I have missed thy company much; it has, however,
been grateful to my feelings to believe that our
union in Christ is rather strengthened than otherwise,
by the late opportunity we have had of conversing
a little on matters of the first importance to us,
and waiting together on the Lord.
We frequently felt His presence, contriting our hearts,
when we belonged to the same meeting; and I hope,
that although this latter is no longer our lot,
we may be favored to remember each other as at the feet of the Omnipresent Savior still,
and to feel that we are even one in Him.
Be faithful, my dear friend, from time to time,
to the small but clear manifestations of the Divine Mind,
and the Lord give thee a crown of righteousness to wear, even in this life,
unto His own glory.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Clapham, First Month 6th, 1829.

I am resting in this warm house, having some cold,
but it has not hindered me from finishing the family visit in Kingston Monthly Meeting,
which I am thankful to say is now got through,
and I humbly hope without doing harm to that which
it is our first desire to promote and cherish.
Many very favored visits we have had:
the meeting at Croydon on First day was also an awakening, powerful time;
and yesterday at Wandsworth, was the most so of any we have attended there.
I was very, very sorry to miss dear +++_______+++and +++_______+++. Ah! my precious +++_______+++,
we are sure to retrograde if we do not advance in the Christian`'s path,
especially after the extraordinary manifestations
of the love and power of our dear Redeemer.

I think, sometimes, that if I can but see you, my dear children,
grow in humility and in the fear of the Lord,
which is growing in the truth as it is in Jesus,
it will abundantly repay me for all my exercise of mind in the cause of religion,
and all that I feel in leaving my dear family.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
London, First Month 10th, 1829.

Having such very close engagements in family visiting, my mind and body are weary,
or I should have replied to my dear +++_______+++`'s letter before now,
which I was very glad to receive.
We have nearly got through Wandsworth Meeting, and, I humbly hope,
have been assisted by the Great Helper of His people.
Some of the visits have been very extraordinary,
the love of our compassionate and dear Redeemer being displayed to our admiration,
and to the deeply humbling of our spirits, even in gay families.
This is that they may be brought away from their foolish things,
to the meek and humble Savior, who wore a garment without an ornament,
even without a seam.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Wandsworth, First Month 17th, 1829.

I may say that my help and strength has been in the Lord, who was pleased,
in very early life, to give me a sense,
that "`it is not in man that walketh to direct his steps,`"
and was my Rock and my Deliverer in those days.
I went through almost more than I can remember in my past life, both by day and night,
for a long time, before coming on this present concern;
so that I thought of one who spoke of being "`pressed out of measure,
above strength;`" but now, with all that I have to introduce my mind into exercise,
I seem raised above it; so that I can go forward with a degree of cheerfulness,
in this weighty and arduous work;
having received of that which may be compared to the eagle`'s wings,
and to find my place in the high rock, far above the mighty waves of the sea.
I think, in an especial manner,
way has been made in families to declare the word faithfully, and in gospel love,
which is like holy oil, and has spread to each individual, almost without exception.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clapham, First Month 24th, 1829.

[.salutation]
My Dear Friend,

Thy truly affectionate communication handed me yesterday,
confirms me in the belief which I had, before receiving it,
that I am not forgotten by thee,
even when a season of long-continued silence between us occurs; and I can assure thee,
that with respect to myself, I frequently visit thee and thine ideally,
and I trust with an interest as strong as when we used to meet two or three times a week.

It is very pleasant to find that thou canst speak of your
dear children with the prospect of much comfort in them;
this must indeed be esteemed by thy dear husband and thee,
one of your greatest blessings.
It is my fervent desire that their beloved parents may be so increasingly and
intimately acquainted with what the weapons of the Christian`'s warfare can do,
as to enable them to teach the children the use of these:
the scripture saith "`they are mighty through God to the pulling down of strong holds;
to the casting down of imaginations and every high thing;
to the bringing into captivity every thought to the obedience of Christ.`"
Then, when all is subjected to Him who is worthy to reign and rule,
the soul comes to be enlarged in a capacity to sing His praise,
and to ascribe unto Him salvation and strength; serving Him, the Lord,
"`with a perfect heart and with a willing mind.`"
We have, indeed, too few among us so prepared;
for instead of the _whole_ heart being dedicated to the Most High,
the things of time and sense engross it chiefly,
and leave little ability to offer unto the Lord an offering in righteousness.

We cannot, my dear friend, but mourn this,
in our passing along in the present solemn work which engages us; there are, however,
exceptions, which is cause of humble gratitude to the Great Preserver of men, who,
in adorable mercy and infinite love, hath appointed salvation as walls and bulwarks,
to all that will accept it on His own terms.

The strain of thy letter is such as convinces me that thy mind has not
become insensible to the goodness and power of thy dear Redeemer,
who visited thee in early life; and in His being, at times,
to thy spirit like the dew upon the grass,
is evidencing His design to render thee more fruitful unto His glory.

I am indeed glad, in a fresh and living sense, while I write,
that notwithstanding the flatness and dryness in which thou mayest often find thyself,
if thou wait fervently on the Strength of Israel, He will cause thee to grow before Him,
and in His garden, as the lily--and more--to send forth the roots like Lebanon.
Thus may thy spirit _deepen,_ and so be able to stand in time of storm or trouble; yea,
to stand through prosperity and adversity, to the honor of the ever blessed Name;
and I may say these are my desires for thy dear companion in life too.

We are in gospel bonds hereaway, nor do I, at present, see to the end of it.
Our work lately has been visiting families, many of whom are not, in appearance,
the least like Friends; but gospel love reached to these, as well as to others.
It has indeed been a time when this Divine principle manifested itself largely,
and when it penetrated the obdurate heart,
while in a disposition to resist its influence.

[.signed-section-closing]
With love to friends, I remain thy affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To her Children.

[.signed-section-context-open]
Bromley, Third Month 3rd, 1829.

May Divine Goodness be graciously pleased to protect you, every one,
from all that could harm you!
He will indeed keep you from evil, that it may not grieve you, if you are watchful,
and concerned to look to, and pray to Him, the Lord, your Savior and Redeemer.
I often think of that scripture which saith of Zion`'s children,
that they shall be "`all taught of the Lord,`" and great shall be their peace.
This peace is worth obtaining through great humiliation and suffering.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
London, Fourth Month 4th, 1829.

Although the time is short since we parted,
yet when that very great interest is felt respecting
each other which is the case with us,
it is even some relief to write.

My mind is much with my precious family, while, for the Gospel`'s sake,
I am induced to give up the gratification of their society;
but we have no doubt of its being best for us all,
for whatever is in the ordering of Divine Wisdom turns to our real advantage.

Let me charge thee and each of you, to mind what is right and be found in it,
at the risk of your own reputation, or honor, or pleasure: this is what becomes us,
and is worthy of us all.
I charge thee, my dear child, mind not foolish or high things; for if thou dost,
thou wilt ensure to thyself the sorrow of this world that worketh death;
and besides reproach the name of Christ, thy Savior, and bring upon us,
thy anxious parents, much distress.

I am not easy that thou shouldst mimic the vain customs of a delusive world,
for that brings the mind into the bondage of corruption,
and disqualifies for the free service of an all-beneficent Creator.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Uxbridge, Fourth Month 13th, 1829.

We took tea with Sarah Angel, who appeared much gratified with our company.
I went to the China closet,
to see the old round dish that was sent with dessert on the day of our marriage,
filled with various kinds of fruit:
it looked as if it had hardly been out of its place on the shelf,
for _five and twenty_ years.
I made divers calls at Staines on invalids, and met with some old schoolfellows of mine.
They were glad to see me, although we had not met since those days of sorrow (at school).

Fifth day being meeting day at Staines, we attended it:
it was a good and instructive time.
Not feeling liberated, we had a meeting appointed for other people on sixth day,
which was also favored, being very solemn indeed.
Friends and others seemed much comforted.
We had a precious meeting indeed, here, and very large.
The life of truth was over all.

May the Most High have the praise of His own works!
We are nothing, but He is great, and greatly to be praised.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
London, Fourth Month 17th, 1829.

Hitherto, in this journey,
I may acknowledge that the Strength of Israel has
been a present help in the needful time.
Last First day we held a large meeting with the people at Uxbridge.
Previously to going to the meetinghouse I felt so poorly,
and devoid of all sense of anything but my infirmities,
that were it not for the remembrance that I was nothing but a mere channel,
which no good could pass through, until it issued from the inexhaustible Source,
I should have been wholly fainthearted.
It, however,
pleased Infinite Goodness to occasion the doctrines
of the Gospel to flow freely and largely to the hearers,
and His own holy anointing to soften their hearts;
so that once more my soul adopted the language, "`This is the Lord`'s doing,
and it is marvelous in our eyes.`"

It seems as if the Divine Hand was turned upon us as a people, that the dross, the tin,
and the reprobate silver, may be purged away.
This is the day which hath for years been declared of, in the spirit of prophecy.
Yet will the Refiner bring forth a remnant who resemble the gold, with its own lustre,
and bearing the inscription of "`Holiness to the Lord.`"

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Fourth Month 25th, 1829.

The large general meeting in the City I went to under
much exercise and weight upon my mind.
After a considerable time, I found my way to stand up, when my bonds were indeed broken,
and my tongue loosened,
so that I had largely to declare the word of the Lord among us as a people,
even in the blessed and living authority of truth;
this tended greatly to the relief of my oppressed spirit.
My dear J. G. had also a precious, solemn time; beginning with the query,
"`Will ye also go away?`"

Perhaps thou wilt wonder, after all this,^
footnote:[S. G. had visited all the Meetings composing the London Quarterly Meeting,
except two.]
that I should say I only feel as if I had commenced as a laborer in that extended field,
nor do I see to the end;
yet where is the place which my natural inclination does less desire to be found in?
But the will of the Lord be done.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clapham, Fifth Monty 21st, 1829.

To sit in families under a sense of religious duty,
and while assuming the character of a gospel messenger, is indeed an awful thing.
I feel it so, even increasingly, the more I am engaged in it,
and the longer I continue in the sacred office of a minister of Christ;
so that I seemed a little prepared to sympathize with thee, my dear,
in thy early going forth in this way.
I trust it tended to unburden and strengthen thy own mind,
while some enlargement in the precious gift committed to thee,
has resulted from the dedication;
and that the minds of the visited have been made sensible
of the renewed offers of our Heavenly Father`'s love.

If we are called upon to advocate a cause ever righteous and glorious,
should we hold back because iniquity abounds,
and the abomination of desolation is seen standing where it ought not?
Would not that look like coldness of love?`"

[.offset.emphasized]
The following Letter to Elizabeth Grubb, arrived shortly after her decease.

[.letter-heading]
To E. Grubb.

[.signed-section-context-open]
Clapham, Seventh Month 2nd, 1829.

[.salutation]
My Dear and Long Afflicted Sister,

Having learnt that thou wouldst like to receive a
few lines from either thy brother or me,
I am induced to address thee in this way, which I should have done before,
only that I feared that thy present weak state was such as to render it difficult
for thee to bear the excitement of an immediate communication of this kind.
We have indeed felt much for thee.
Thou hast been tried with the absence of the invaluable
blessing of health for many years:
under this deprivation, all sublunary enjoyments are much enveloped as in a cloud;
thus has the sunshine of life been less thy portion than falls to the lot of most;
neither, perhaps,
have the consolations of an eternal and glorious
world been as sensibly poured into thy soul,
as thou hast supposed was the experience of many; but my faith is strong,
that in this late evening of thy day,
the healing wings of the Sun of righteousness will
be known to the immortal spirit as all-sufficient;
even giving strength to rise superior to all depression.
Oh!
I trust, my sister, that _He_ is with thee, who became for our sakes "`a man of sorrows,
and acquainted with grief;`" for "`Himself took our infirmities`"
even more heavily than we are able to bear them for ourselves.
What matchless mercy!
What unbounded compassion towards us poor unworthy creatures!
Farewell, my beloved sister; yea, I believe thou wilt forever fare well in thy Savior,
thy Redeemer.

[.signed-section-closing]
I remain thy truly affectionate sister,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
London, Seventh Month 14th, 1829.

Oh! how I love to see the young people embrace religion fully!
I know it is their truest happiness.
I wish, my dear, thou mayest be careful of thy _words_ and _demeanor._
I often think of you, while I am engaged to declare the truth to the people,
and enforce the necessity of watchfulness unto prayer,
that we may live to the glory of our Creator.
Great is my travail for my children.
The Almighty has done much for you--blessed you abundantly many ways.
Oh! that all His benefits may be regarded, and your hearts yield to His power,
that so you may be His; which I know would render you more happy than anything else.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clapham, Seventh Month, 1829.

There are times when our faith seems all but shipwrecked, yet as we endeavor to be still,
we are kept from being cast away, we hardly know how;
only we are sure it must be that the true Pilot has not deserted the vessel,
as we feared was the case;
and even if this extremity be brought on by outward circumstances,
it still brings us to hope against hope,
and fixes our dependence more firmly on Him who is unchangeably just and true.
Shall we give way to a disposition unprofitably to dwell upon the weakness of our nature,
and so let go our hold of Him who is invisible,
because we see that some stars in the firmament,
which appeared of greater magnitude than ourselves, have fallen?
No; but rather let us look well to our own abiding; let us watch, with all vigilance,
against everything that would have a tendency to occasion us to begin to wander,
in the least degree,
from that sphere in which Consummate Wisdom hath seen meet to place us;
and then the dragon will have no power to draw us down, but we shall see _Him_ in dominion,
of whom it is said that He declared, "`I will punish Leviathan the piercing serpent,
even Leviathan the crooked serpent, with my great and strong sword;
and I will slay the dragon that is in the sea.`"
Thou wilt not consider it in any degree arrogancy,
to speak of our being stars in the firmament.
I believe we are all called up into such a state, and that, as we become obedient,
the Divine hand is known to bring us thus to experience its great and glorious work; yea,
and to exhibit, in our measure, His own beautiful harmony, His blessed order,
His holy economy, who is God over all, blessed and glorified in all His works.

Now, while I write thus, I can freely confess,
that it is not from any feeling of a redundancy of heavenly virtue vouchsafed to me,
but from a sense of content in my own sphere, as a very little star,
while I can rejoice in seeing others more largely gifted and qualified to serve,
and to magnify the great Creator of all things, visible and invisible;
to whom my poor soul ascribes all honor, might, majesty, and renown; and unto the Lamb,
one with Him to all eternity.
Amen!

Very abundant testimony hath of late been borne to
the immutability of the truth as it is in Jesus,
and unto its all-sufficiency to keep us,
and to establish us upon itself as an invincible foundation.
It seems as if our Heavenly Father had afforded, very especially,
the demonstration of His Spirit and power for this purpose,
so that many could not but subscribe thereunto, after all their doubts and fears.
The Great Dispenser of gifts does not all at once remove
the spirit of prophecy from such to whom it has been granted;
in this respect His long-suffering is evinced;
but unless there be a returning to that from which these may have begun to fall,
the gift leaves them by little and little, and the man`'s part is sometimes substituted,
and the devil`'s part too; for Satan knows what we are, and, by his influence,
his servants sometimes know it too.
Did not one cry out, when possessed with a spirit of divination,
that the Apostles were (as they indeed were) "`the servants
of the Most High God,`" who showed the way of salvation?
and do not men of quick perception, who are in the obedience unto unrighteousness,
often recognize their brethren in ungodliness, even where they may not have much,
if any outward knowledge of them:
knowing more of "`the ruler of the darkness of this world,`" they
often more readily discover his subjects than those do,
who are in the allegiance to the Prince of peace; yea,
I believe that they can sometimes speak to the condition of men,
not indeed in the holy and heavenly anointing, but in a spirit at variance with it,
while it mimics its very language.
Tell +++_______+++ and +++_______+++ not to be too fainthearted
in the way which I trust each of them have entered,
believing it to be the only way from earth to heaven, but,
having begun to climb the ladder, to persevere,
and when any may think themselves ready to slide back,
to endeavor to cling more closely unto the defence; like taking hold more firmly,
and with both hands, of the ladder whose top reacheth unto heaven,
although the bottom is upon the earth.
Oh! thus is Christ, the way, represented, who condescends to our earthly condition,
to raise us up into His own heavenly, joyous kingdom.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Eighth Month 20th, 1829.

We are all well, and desire our dear love to thee; feeling much sympathy with thee;
but I hope thou hast the love of thy Redeemer to comfort thee, which is best of all.
He suffered for us.
"`It pleased the Lord to put Him to grief`" even Him who knew no sin.
Do not think, my dear,
that thou art visited with this singular and sore dispensation in displeasure;
I believe it is far otherwise.
"`Be of good cheer, and He shall strengthen thy heart.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eighth Month 22nd, 1829.

I _do_ pray for thee, my dear child, fervently and frequently;
prostrating myself before the Lord on thy account;
and I am well assured that He has set His love upon thee.
Oh! that thou mayest be raised up to magnify His eternally excellent Name.

How very gloomy thy situation must be!
True, the goodness of the Lord is great, in reconciling thee to thy lot;
and I humbly trust that the Sun of righteousness has arisen,
to dissipate the very dense cloud which has been so long hanging over thee, and felt,
as it were, breaking upon thee.

Oh! may the healing, which is in the heavenly wings, reach thy soul, comfort,
and strengthen thee to go forth and grow up as one peculiarly cared for!

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Near London, Tenth Month 13th, 1829.

What labour and sorrow we have in this probationary state of existence!
I often am ready to marvel at the world in general
seeming to neglect the consolations of religion,
for what would become of some of us, were it not for that balm?
yet very little of the _sensible_ enjoyment of this
unmixed good has been my experience for a long time,
only I endeavor to hope that its hidden virtue keeps the soul from sinking.
Never, in my recollection, was my poor mind more near fainting than of late.
Oh! how have I feared for that cause which it has been my engagement to
advocate so publicly! in what condition have I many times gone to those
very meetings which I considered myself constrained to appoint!
Alas!
I have thought, that did the people know my entire emptiness and want of all things,
except the least and almost imperceptible grain of faith,
they surely would not come to meet me.
Multitudes have indeed attended on these occasions, ignorant, totally so,
of _my_ helpless state, without the renewed,
holy influence of that anointing which teacheth all things;
by which even so poor and mean an instrument as myself has been assisted to evidence,
or bear testimony to the truths of the everlasting, unchangeable Gospel; yea,
in the demonstration of the eternal Spirit of God,
and with that power which is of and from this source.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
London, Eleventh Month 30th, 1829.

How nice it is to pursue a little study, to vary your employ,
and to store the mind with useful knowledge!
It is much to be hoped that the powers bestowed will turn to good account,
by being sanctified through the operations of Divine grace.
+++_______+++ is not among those whose gifts are very few, or of the lowest in kind;
may thy mind be strengthened to devote thyself entirely to the dear Redeemer,
whom thou hast loved from a child, because He first loved thee.
Oh! that He may ever be, to thy susceptible heart,
the "`chief of ten thousand;`" so will thy life be
happier than in joining with the spirit of the world,
in any of its presentations, or attractive and delusive pleasures.

Yesterday morning at Gracechurch Street,
it was a remarkable time for the extension of the power of truth.
In the evening a very great meeting was held with the people in the same house;
and oh! forever praised be the Helper of the helpless, the Strength to the needy,
it was a blessed, heavenly meeting: it ended with increased solemnity,
a measure of which had been over us from the commencement of our gathering together.

I feel these things to be very weighty on my spirit; not less so for their frequency;
nor, indeed, can I desire that it should be otherwise;
my prayer is that the Almighty may be graciously pleased
to conduct me through the work to His own honor,
and the abasement of the creature; while, in a sense of my great weakness,
I am ready to adopt the language, "`Who is sufficient for these things?`"
The meeting was very large at Devonshire House;
I believe there were not less than sixteen hundred persons present,
perhaps eighteen hundred, and very many went away for want of room.
I thought it a good meeting, which was cause of great thankfulness,
for it was a mixed multitude.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stamford Hill, Twelfth Month 12th, 1829.

The work allotted me is truly awful.
Sometimes I think of that condition, described as "`standing on a sea of glass,
mingled with fire:`" the harp is given at seasons, even there.
Oh! my dear, I am already in travail about the meeting at Tottenham tomorrow evening.
May Almighty Goodness lend His all-sufficient aid in the needful time,
that His Name may be magnified over all!

As regards family prayer,
I desire that the restraining influence of the Spirit
of truth may keep away from us the strange fire,
which, wherever it is offered, occasions death.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Wandsworth, Twelfth Month 25th, 1829.

I often think of you when my mind is turned to the Lord in secret prayer:
it is the breathing of my soul, that it may please Him to draw you by His love,
near unto Himself; to give you to acknowledge, that "`in His presence is fulness of joy;
at His right hand there are pleasures forevermore.`"
There are no pleasures like these, my beloved child.
I often wish that each of you may be particularly
engaged to lift up your hearts to the Almighty,
morning and evening, to implore His preservation,
and that He would give you to grow in grace and saving knowledge.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Near London, Twelfth Month 31st, 1829.

Being brought low is frequently a preparation to
being raised up to stand on Zion`'s Mount,
with the trumpet to the mouth, to proclaim the word of the Lord;
even to give a certain sound in the ears of the people.

We have prosecuted our views of religious service from time to time,
both among Friends and others, as perhaps thou hast heard.
Last night had a very full meeting at Esher, about nine miles distant from this place.
Our hearts are sometimes filled with a grateful sense of the Lord`'s power and goodness,
on these solemn and important occasions;
finding the people glad to receive the living gospel truths declared;
at other seasons we have to exercise faith and patience,
while there is much labour called for,
without the consoling evidence of the word having free course.

Since I last wrote to thee, my dear, I have, at times, been brought into much conflict,
and deep, painful exercise of mind.
_Now_ I am favored with a measure of the calming influence
which continues to manifest itself down to the present age,
and even to such a worm as myself;
the same that it was in the days of the early Christians,
when they knew it to hush all their fears, while on the boisterous waves.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Probably 1829.

I just want to put thee in mind that when we, poor erring, sinful creatures,
are sensible that the weight of our transgressions is a burden "`too heavy`" for us,
it is by no means a mark that we are forsaken,
but rather a call to endeavor to come to Him who knew no sin, and yet,
in adorable lovingkindness, took upon Himself the iniquity of us all; that so,
in His blood, we might be washed thoroughly from all our pollution and vileness.
We find, that for want of watchfulness and obedience,
we have incurred a debt which we are altogether unable to pay; but,
in humble application to the Lord of glory, who is unsearchable in goodness and mercy,
we find, in due time, that He is as willing as able to release us from it all,
to pay the great debt for us by His atoning sacrifice,
and to set us free from the load that has so sorely oppressed us.

Thine is no new condition,
no solitary instance of being borne down with sorrow and shame,
in seeing thy sins set in order before thee; it is even the case,
in a greater or less degree,
with all who are found in that repentance which is not to be repented of.
I knew it well, early in life, and often since.
To this day, at times, I blush in secret: I feel that to me belongs confusion of face.
Even when my past sins rise up before me,
and the latent corruption of my heart disgusts me,
I could sink into a state of discouragement which would
unfit me for imploring the mercy of Him who died for us;
but knowing that such is not the design of our Heavenly Father,
I am induced to resist the accuser, the enemy of all good and of all peace,
and to cleave to the Protector of such as feel the need they have
of that salvation which they cannot purchase for themselves.

Thus it is, my dear +++_______+++, that having known the terrors of the Lord for sin,
I am induced to persuade others to repent and live;
and I consider this to be one great use which is to be made of my own shame,
and confusion, and oppressive weight, under a sense of being found in the transgression;
even to invite others to the "`Fountain which is set open in the house of David,
for sin and for uncleanness.`"

Let me say that I fully believe thou mayest be brought to the same conclusion,
that it is thy duty, instead of giving way to too much discouragement,
to suffer the painful dispensations thou hast passed through,
to prepare and stimulate thy mind for persuading
and warning others to break off their sins by repentance,
and their transgressions by amendment of life.

We were at Devonshire House Meeting third day, Peel yesterday,
and have appointed a public meeting at the latter place for this evening,
and one at Gracechurch Street for First day.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Probably 1830.

[.salutation]
My Dearly Beloved Sister,

I scarcely am allowed a few minutes to salute thee, being in haste to depart,
but I want just to say,
"`Be of good cheer;`" for surely the "`light afflictions which are but for a moment,
are not worthy to be compared with the glory that
shall be revealed`" in the fulness of time.
What is the present life, when compared with an eternal state?
only like a drop of the ocean.
So toil on: thy reward is sure, in holding out to the end,
in patient continuance in well doing.
Thou art traveling home, never more to be weary or faint, nor to want any comfort or joy.
The Lamb shall feed thee, and bring thee to living fountains of water;
and "`all tears shall be wiped away.`"

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Clapham, First Month 20th, 1830.

And now, my dear +++_______+++,
let me advert to thy plaintive language respecting thy own condition of mind.
Be assured it has been, and continues to be, the condition of many,
even that notwithstanding a degree of willingness to be
found faithfully following the crucified Redeemer,
and to love Him entirely, the weakness of the natural part often gains ground,
so as to occasion painful remorse: thus "`the spirit indeed is willing,
but the flesh is weak;`" and hence the exclamation of one who was warring a good warfare,
"`Oh! wretched man that I am, who shall deliver me from the body of this death?`"
and yet we find that he _was_ delivered,
even as he persevered in watching the soul`'s enemies, and combating with them;
using "`the weapons that are not carnal,
but mighty through God,`" to the "`bringing into
captivity every thought to the obedience of Christ.`"

The same victory will, I trust, be thine through the same means,
which ever works the same end.
That we should be jealous over ourselves is acceptable to the Lord;
and to find ourselves inclined to give the affections too
much to perishable objects ought not to occasion despondency,
but humble us indeed,
and prove an incitement to apply with increased diligence
unto that power which is above every power;
for "`if any man sin, we have an Advocate with the Father,
Jesus Christ the righteous:`" may we draw near to Him,
and endeavor to cast our burden upon Him;
for He hath testified that He will in no wise cast out such as come to Him.
He requires, not that we should look always _upon_ our transgressions,
but _beyond_ them unto Himself, the living Fountain,
in which all that is offensive may be removed forever.

The days of youth are indeed those days wherein we may so come to Christ,
as to witness a preparation for walking with Him in white raiment,
through every stage of life.

As we progress in the spiritual life,
the garments of righteousness and of salvation become whiter and whiter,
and the capacity enlarged to speak the inviting language
of example--"`Come and have fellowship with us;
for verily our fellowship is with the Father, and with His Son Christ Jesus our Lord.`"
Yea, it will be evident, to the glory of the Great Name,
that we know what it is to be purged from our sins in the blood of the Lamb.
Be encouraged, my dear +++_______+++, to hope that better days are in store for thee,
seeing thou dost long after a nearer acquaintance,
a more intimate union with thy Heavenly Father.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Third Month 15th, 1830.

Oh! if my dear children are united to their Redeemer,
in the eternal covenant of His love and life,
what cause of rejoicing it will be to their precious father and myself.
We never desired great things for them in the world, only that Christ Jesus our Lord,
might be to them "`the chief of ten thousand.`"

To +++_______+++.

Stoke Newington, Fourth Month 15th, 1830.

Yet it is true that "`affliction cometh not forth of the dust,
neither doth trouble spring out of the ground.`"
No, no; it is not a spontaneous plant; it is permitted to be sown for us;
to grow up and mature, until it produce what is bitter in the mouth,
but is as wholesome medicine,
that proves ultimately conducive to the health of those who receive it.
Thus is the soul strengthened, so that ability is known to "`withstand in the evil day,
and having _done all,_ to stand.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Fourth Month 11th, 1830.

I know exactly how it is to think that the tide of opposing things is so overwhelming,
that we cannot move forward in the line of religious duty; but, after all,
as we hold our peace, the Lord fights for us, and afterwards we sing His praise.
How glad I am that thou hast found grace to help in time of need,
and art now going forth in the cause of Zion`'s King!
Much do I desire thy enlargement in the Gospel,
and that relief which Infinite Wisdom may see meet for thee.
It is no more than I expected, that thou art again raised up,
and constrained to visit the seed of life in places situated away from thy own home.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month, 1830.

Yearly Meeting, second week.--Once more Friends have cause to be humbly thankful,
in a sense of the condescension of the Great Head of the Church,
in giving us an evidence in our general assembly,
that He hath not cast us off from His presence, nor taken His Holy Spirit from us;
indeed it has been a remarkably favored time so far.

This morning the subject of private prayer was introduced,
when some of us expressed a concern that we might be cautious how
we encouraged any vocal supplication in the time and will of man,
lest we should be found going back again into those mere lifeless offerings,
from which our Society has been called away.
I hope Friends understood each other, and that the matter closed agreeably.

Now I may confess that it seems to me that we, as a people,
are called to still greater humility and perfect dedication; which, if we come to,
will draw down the Divine blessing in an abundant degree; we must, however,
be abased before the Lord, either in the extendings of His love,
or by His judgments being poured out among us still more conspicuously,
and more heavily than we have known of late.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Sixth Month 4th, 1830.

Thy brother`'s character seems to be formed for the best example to others, so that,
wherever his lot is cast, the influence cannot but be good;
his mind appearing to be regulated by the all-regulating
principle with which we are individually favored,
and which it is the interest of every one to submit to, and abide with.
What a comfort to thee, my dear child,
that early in life thou too hast become acquainted
with the unspeakable gift of Divine grace,
which is the sufficiency of the Lord`'s children in all their privations and sufferings!
It often seems to me that thou art the peculiar care of thy Heavenly Father,
and if thou continues to love Him, thy consolation will be great;
for He will give thee to be abundantly satisfied with the fatness of His house,
and thou shalt drink of the river of His pleasures.

Thus will the Lord, thy Maker,
more than compensate for any outward and temporal gratification which,
in His inscrutable wisdom, He may have seen meet to withhold.
It was in my heart to salute thee with this little word of encouragement,
and to assure thee of my continued love.
