== Chapter 15. Letters from 1833--1834

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Twelfth Month 29th, 1832.

Thinking thou and thy dear brother will look for some tidings from us tomorrow,
I may just state that a meeting is appointed at Devonshire House,
for the lowest class of the people, to begin at six o`'clock.
I feel rather nervous, which is no wonder.
I am not, however, without some degree of faith and humble hope,
that the great Almighty Helper of the little ones, the poor and needy,
is ordering all things for the best, as it relates to me,
and the work in which He sees meet to engage His handmaiden; yea,
I trust that all things will work together for good.
I sometimes think of the text, "`He that loveth son or daughter more than me,
is not worthy of me.`"
I know my dear children will wish me well through so important and so
arduous an act of obedience to the will of my Heavenly Father.
May you turn your minds to Him on behalf of His own great cause,
and on behalf of His poor nothing as I am.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, First Month, 1833.

We are right glad of thy lines written yesterday.
What a kind Providence we have over us!
He does not permit us to be introduced into more solicitude or exercise
of mind than we can (with that capacity He has given us) sustain.
I was sorely baptized on seventh day night and yesterday,
which I believe was preparatory to the meeting last evening.
I am much better since that was relievingly got through.
It is indeed an awful thing to meet with many hundreds of one`'s fellow creatures;
a mixed multitude whom we have dared to call together in the love of God,
while we are wholly dependent upon Him who puts forth, for any good word or work.

When I wait on the great Author of our being, and of all our sure mercies,
and think of you,
my mind is not disposed to doubt the gracious providence of our Heavenly Father.
Trials we must have, but, as we profit by them, joy comes likewise in its season,
as summer succeeds the winter, and day the night.

I long very much to be with you.
It is a great comfort to receive such good accounts of our dear absent children;
indeed I esteem it one of those mercies which call for gratitude to our Heavenly Father,
and encourage to perseverance in the path of duty,
in dedication of all to Him from whom we receive every blessing.
I have no doubt of your good desires for us, and for the cause in which we are engaged:
I hope you will remember us in the Divine presence.
I never felt more sensible of my own insufficiency
for any good work or word than is now the case.
These offerings are in a measure of that faith or belief which renders things possible,
that otherwise, or without it, could not be entered upon.
The meeting at Gracechurch Street was very solid, ending with great solemnity.
Some came to speak to me before leaving the meetinghouse,
who expressed their satisfaction,
and said they attended the one I had there some months ago.
The sufficiency for these _fearful_ engagements being
in that power which puts forth in the work,
I have a humble trust that it will be given in the needful hour.
The everlasting Fountain of life and light is my sole dependence.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, First Month 13th, 1833.

We hope thou wilt be able to get through this perplexing
time without injury to thy best feelings.
I would have thee allot a short time every day,
to commit thyself into the care and keeping of thy Almighty Father;
that thy tender mind being brought into a little retirement,
thy strength may be renewed in Him, the Fulness of strength;
so shall thy soul be preserved from taking harm by the distracting concerns of business.
I believe thou art called upon to serve the Lord thy God conspicuously in thy day,
and I should be sorry to have thy mind too much occupied
or absorbed in the things of time.
I take a tender leave of thee, commending thee to the care of Israel`'s Shepherd.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Second Month 5th, 1833.

On First day we had the company of dear Daniel Wheeler at both meetings.
He took tea here.
We found his conversation truly edifying and interesting:
he was all resignation under his trials,
and spoke as if he was not only filled with an assurance that his
endeared wife was centered in everlasting peace and rest,
but that he had a sense of the sweet calm that reigned
in his family under accumulated trial.
He gave us a beautiful and instructive letter to read from a son.
I was ready to say, "`This is the Lord`'s doing; it is marvelous in our eyes.`"

In my deep retirement yesterday,
I sought to present us all before the mercy-seat of our Great Judge,
and to pray for preservation and deliverance,
when the text was brought to my remembrance,
"`I will bring the blind by a way that they knew not;
I will lead them in paths that they have not known:
I will make darkness light before them, and crooked things straight.
These things will I do unto them, and not forsake them.`"
It comforted and strengthened my mind, for I thought,
that although we cannot see the good of our crosses and exercises at the time,
yet those who trust in the Lord find eventually that
things come round to their real benefit.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, Third Month, 1833.

We had a very large meeting at Westminster on First day evening: it was,
like all the rest held since our return from you, remarkably solemn,
and favored with the holy anointing, both as to utterance, and in the silent part.
My soul bows in humble gratitude before the Most High; praising Him for His goodness,
and for His wonderful works, even to the meanest of His servants.

Lately thy dear father and I went to Tottenham Meeting, for I found my mind drawn there,
as thou knowest I do sometimes to other meetings than my own.
I had satisfaction in endeavoring to fill up the portion of exercise allotted me,
and that with a single eye to the Great Head of the Church.
We dined at C. W.`'s. I very much enjoyed being in her company,
and visiting her commodious, but truly humble dwelling.
Your father desires me to say he has, for J., John Barclay`'s Diary of Alexander Jaffray,
one of the Scottish Commissioners of Charles the Second;
to which are added particulars of his subsequent life,
connected with memoirs of the rise, progress, and persecutions of Friends.
We are now reading it, and think it a valuable production.

Altogether yesterday was a sweet day to me;
a day of some degree of ability to give thanks, and, although with trembling, to rejoice.
I was relieved from bodily and mental suffering, and favored to have two nice letters,
which conveyed comfort relative to all my dear children.
I desire to number these things among the many mercies
received from our gracious and heavenly Father,
and I also desire to stand open to His blessed will,
in crosses and trials that may yet await me.
Surely He knows best what is meet for us,
and what will eventually promote our truest interests!

[.letter-heading]
To the Same.

[.signed-section-context-open]
Third Month, 1833.

Thy letter received today is indeed a comfort to us:
though I should be truly glad did our lot fall together,
I am much comforted in the consciousness of thy being in thy right place,
and for the present, at least, may we not hope it is the case with us all?
I must assure thee that I am ever with thee in my mind; but, what is better,
I humbly trust that our heavenly and omnipotent Father watches over us all for good.
May we remember one another before the throne of His mercy!

[.letter-heading]
To a Friend who was Becoming Conspicuous in Political Agitation and Excitement.

[.signed-section-context-open]
Stoke Newington, Third Month 2nd, 1833.

[.salutation]
Dear Friend,

Some unknown hand having sent us a paper, in which is an address signed +++_______+++,
I conclude it is the production of thy pen, and am exceedingly alarmed for thee.
A highly professing Christian; a member of the Society of Friends; yea,
a minister among a body of people remarkable for their peaceable lives!
Surely this address is altogether inconsistent with the name of Christian!
What has a follower of the holy, meek Jesus, to do with political parties,
or with the striving one with another, of the potsherds of the earth?
Ah! +++_______+++, it was once different with thee: "`Remember, therefore,
from whence thou art fallen; and repent,
and do the first works;`" or else further desertion of good awaits thee,
wherein thou mayest look for light, and behold darkness;
and thy soul may be more and more in a state of alienation from the Divine life.
Oh!
I am sensible of much solicitude on thy account.
"`Be sober, be vigilant;`" "`be watchful.`"
Is not the lion, even now, roaring for his prey with respect to thee?
Retire, oh! retire out of all ferments,
and wait upon Him who saw thee in thy tender years;
who accepted the unfeigned humility of thy heart, and anointed thee for His service; yea,
sent thee forth in His great Name, and gave thee fellowship with His chosen ones;
opening thy way to proclaim His living word in His own blessed authority.
Oh!
I cannot but mourn over thee, who art fallen by little and little,
who wast as a star in the firmament.
Where hast thou wandered?
Into what hast thou come down?
Is it not into the corrupt, earthly nature?
and art thou not, in measure,
now under the government of that spirit that rules
in the hearts of the children of disobedience?
Oh!
I entreat thee, in the love of the Gospel,
lose no time in humbling thyself before the Lord: put thy mouth as in the dust; yea,
hide thyself, until the indignation of Him whom thy conduct reproaches,
pass upon the transgressing nature;
if so be thou mayest come to know thy garments again washed and made white in His blood,
who died for us that we might live; and who said, "`My kingdom is not of this world;
else would my servants fight.`"

My husband unites with me in this communication to thee;
desiring it may be received as a solemn warning to consider and amend thy ways.
So saith

[.signed-section-closing]
Thy sincere friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Third Month 19th, 1833.

May Divine Love draw thee into a preference of heavenly
things still more manifestly in the sight of men,
for I know thy heart does primarily value those things that are spiritual,
and are not seen.

Dost thou recollect our friend +++_______+++`'s address to thee,
wherein she repeated how the scripture speaks of Joseph,
the "`fruitful bough by a well;`" and how this Joseph was shot at,
and deeply tried for a season, but eventually triumphed, and was abundantly blessed.
I hope it will be thy case, and that thou wilt increasingly become a blessing.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fifth Month 13th, 1833.

Thy sweetly acceptable letter met my eye on returning from town, where we had been;
the Morning Meeting occurring today.
I am most truly glad to perceive that the bent of thy mind is to that sacred influence,
which is our protection and safe guidance through a world of temptation and intricacies.

Many, many times is my heart raised in prayer for thee, to the great and good Shepherd,
whom I am aware thou desirest to love entirely.
Often draw near to Him in spirit,
and commit the keeping of thy soul to Him in well-doing, as unto a faithful Creator;
even in suffering according to the will of thy Heavenly Father.

I trust and hope that good things every way are in store for thee,
as thou encouragest and cherishest the excellent virtue--patience.

Yesterday we stood round the grave of dear little Thomas Reed.
I thought it a time of consolation,
the evidence being granted of his tender spirit having found
a prepared mansion in the regions of eternal light;
and I had to believe that the gift of resignation
was not withheld from the sorrowing relatives.
On the whole it was a day of considerable labour to me,
having to speak largely in our own meeting, previously to entering the graveyard;
and then in the evening we had a very great public meeting at Hackney.
I believe it was held under right influence, and I feel satisfied.

[.letter-heading]
To the Same.

Well, my dear +++_______+++, I have often told thee, that as thy heart, thy all,
was committed to the Lord from time to time, I fully believed He would bless thee,
and render thee a blessing in thy day.
I still have this faith respecting thee.
The committing ourselves without reserve into the hands of a faithful Creator is, I know,
a great sacrifice, and that which not even a parent can do for the most beloved child,
but it is that in which our truest interest lies;
therefore it behooves us to seek ability from the Fulness of strength,
to make the free-will offering in this way; so shall we receive grace and glory,
and no _good thing_ will be withheld from us.

[.letter-heading]
To the Same.

So, my dear +++_______+++,
endeavor to cast all thy care upon Him who is always caring for thee,
even when thou considerest thyself the most abandoned from His presence.
Wait upon Him in the silence of all flesh; feel after Him, thy Redeemer,
patiently and perseveringly; so will He be found of thee in His own due time,
even as a very present help;
and thou wilt clearly discover that His everlasting arms are underneath;
that thy drooping spirit has been sustained by the invisible power of thy Redeemer,
thy Savior.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, 1833.

For weeks past I have expected to hear something of thee and thine,
but am still disappointed, which induces me in this way to enquire after your welfare.
Think not that I can be wholly indifferent towards
those to whom I have once attached myself;
this is not in the composition of my nature.
Amidst the many and painful conflicts which for months have been my experience,
and even those solemn and weighty duties in which I am engaged, my mind often,
very often, turns toward thee and thy dear husband, with your interesting family;
wishing you all the truest happiness to be enjoyed by probationers,
and which I know is out of our reach, save as we come to love God entirely,
and so become conformable to His blessed will:
then they who have but little of this world`'s goods possess "`the
pearl of great price;`" while the seemingly favored ones,
who may abound in the outward, prove, that without the one thing needful,
the soul wanteth; yea, is in leanness, in poverty.

[.letter-heading]
To a Family who Lived Near J. and S. Grubb, at Stoke Newington.

[.signed-section-context-open]
1833.

Sarah Grubb takes the liberty, in christian love, through this medium,
to express her sincere regret,
on hearing that her friends Glennie contemplate removing to beyond the Atlantic.
Much does S. G. desire that the family she now addresses
may be rightly guided in so great and arduous an undertaking.
The scriptures tell us that "`it is not in man that
walketh to direct his steps;`" and in another place,
"`The steps of a good man are ordered by the Lord, and He delighteth in his way.`"

Many are the unforeseen difficulties to be encountered by strangers in a strange land;
under the pressure of which, there is nothing so safe, so comforting and precious,
as an acquaintance with the Lord Jesus Christ,
who was "`meek and lowly in heart,`" and has invited us all to learn of Him,
that we may find rest unto our souls in this wearisome world.
Thus parents being themselves subjected to the Divine will,
are prepared to train up their dear children in the love and fear of Almighty God;
whereby one is helpful to another, and families harmonize together;
being endeared and united in that which neither crosses, afflictions,
nor even death itself can dissolve.

The writer of these lines heartily wishes for her neighbours,
to whom she sends this farewell salutation, every blessing seen meet for them,
by Him whose is "`the earth and the fulness thereof; the world,
and they that dwell therein;`" believing, that as His counsel is humbly implored,
all will eventually be well.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Colchester, 1833.

We have got through another public meeting,
one having been appointed here for last evening.
It was very large,
and we have thankfully to acknowledge to the condescension of our gracious Master,
in being renewedly a very present help in the needful time.
Oh! it was a good meeting,
crowned with a solemnity that I trust will long be remembered by many.
I was very much exercised before the meeting, and was brought low indeed,
until it pleased the Lord to raise me up once more, in His power and blessed authority.
_How_ I marvel that such a mere nothing should thus
be constrained to engagements so truly awful!
Some remarked to thy father how much they wondered at the stillness of such a congregation;
saying they never knew the like before.

[.letter-heading]
From Sarah Grubb To John Wilbur.

[.signed-section-context-open]
Stoke Newington, 5th, of 6th mo.
1833.

[.salutation]
Dear and Valued Friend,

My address to thee must be short,
for I have been much engaged from day to day during this Yearly Meeting, having,
in the intervals of the various sittings, many Friends at my lodging in town,
and at night a house full here, besides visits from elders, etc. Oh,
how often have I thought of thee! and how painfully have
thy forebodings of mischief among us been realized!
Alas, the enemy of all good has prevailed to no very limited extent;
and the insidious spirit that showed itself last year, appears now to be mighty indeed,
speaking great swelling word, and, for the most part, has had the preeminence,
both in meetings for worship and discipline.
This being permitted, has, however, opened the eyes of many,
who were before unwilling to think that things among us were such as called for alarm.
I, for one, am rather relieved,
in the open manifestation of error in doctrine that has taken place.
I wished for farther opportunity to lay down my burden in the meeting at large,
and requested it, without effect; but am satisfied in doing what I could.

There have been awful moments among us,
when the state of things was clearly laid open in Truth`'s own authority.
I understand, that a visit from the elders is impending for me;
may I be enabled to keep in the quiet, holy habitation.
The same individuals who were crying peace, peace, last year, have done so, this year,
with increased boldness; yea, a lying spirit is gone forth, and many are believing it;
yet some are distinctly evincing the true spirit of prophecy,
which declares against all that would devise an easier way to glory,
than by the true ladder.
We have with us here our loved niece, Ann Moore; I think her already a brave soldier.
I leave a scrap of this sheet for her to cover, and will now take leave.
Am glad dear Ann Coning has written largely to thee.
Charles Osborn lodged here last night; he leaves this land now soon.
Farewell.

My husband and children love John Wilbur.
Hoping we may be near in spirit still,

I remain thy afflicted and affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one Deeply Tried.

[.signed-section-context-open]
Sixth Month, 1833.

The state of the poor weak frame sometimes occasions those dispensations,
sent in best wisdom, to be in some sense misunderstood.
Now thou considerest that all thy distress is in consequence of unwatchfulness.
The grand accuser is not wanting in his insinuations,
that he may prevail on us to despair of being found worthy (through unmerited
mercy) of the gracious care and safe keeping of Him who wounds to heal,
and in whom it is our duty and interest to confide; even as one did who declared,
"`Though He slay me, yet will I trust in Him.`"

Now it is not like a brave combatant with the world to sink so.
Rise up nobly against the cruel assaults of the enemy of peace.
"`Take unto you the whole armour of God,`" saith
an experienced servant and follower of our Lord;
even one who knew what it was to be pressed beyond strength, and out of measure.

No strange thing has happened to thee,
my +++_______+++. These fiery trials are to fit us for the Master`'s use,
by convincing us that the trial of our faith is more precious than of gold that perisheth.
Look at the text alluded to above, which speaks of the armour.
And now I commend thee to Him who carried our sorrows and bore our griefs,
in a body of flesh, and who loves thee, my dear and precious +++_______+++.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Sixth Month 6th, 1833.

If we had been much edified together, the fatigue, etc.,
of such close work as our late Yearly Meeting might be thought little of; but,
on the whole, this annual assembly has proved more discouraging,
in the review of our state in this land, than I have ever known it.
I am sorry to say that I fear many of the most active among us,
are going back into things which our community, in the beginning,
suffered much in coming out of.
Where this will end time must reveal.
Surely we shall yet be a distinct people; at least this is my humble hope.
The same testimonies will, however, be borne, and the same standard flocked unto,
which have been upheld by this people; for they are of the everlasting,
immutable Gospel of our Lord and Savior Jesus Christ.
We never had so much company before,
which may be in part accounted for by the existing state of things among us: some came,
I trust, as we read was the case formerly,
when "`they that feared the Lord spake often one to another,`" then again
we are visited to be reprehended for our plain dealing in meetings,
and because we cannot go with the present stream of communication,
which seems to us to carry off from that pure, dependent state,
in which there is an abiding sense of the truth of that declaration of our holy Helper,
"`Without me ye can do nothing.`"
I have often thought, for weeks past, of poor Lady Guion,
when people scarcely left her any time for rest and quiet;
but we may retire to the measure of the Divine gift in ourselves on all occasions,
and wait upon the "`still, small voice`" of truth, which is a great mercy.

[.letter-heading]
To Mary Capper.

[.signed-section-context-open]
Stoke Newington, Sixth Month 10th, 1833.

[.salutation]
My Dear Friend,

Thy salutation of love by letter is precious to us,
as the long-continued friendship thou hast evinced has always been;
and now I may say that this address of thine is reviving to our minds.
How encouraging it is to see those who made many
sacrifices in early life for the truth`'s sake,
not rest in past experience, even of the Lord`'s goodness, but be as those who remember,
that "`he that thinketh he knoweth anything,
knoweth nothing yet as he ought to know;`" and even in old age,
are concerned to go on learning of Him who said, "`I am meek and lowly in heart.`"
Ah! my dear friend, this Yearly Meeting has exhibited much thou wouldst grieve to see,
and thy dear lines to us convinced us of thy sense thereof.
We have not indeed been able to see eye to eye,
but we have widely and manifestly taken a different
view of the state of our religious Society.
Some of us thinking with thyself,
that we see a sorrowful departure from primitive or godly simplicity,
not merely in the external appearance, but also in that of higher importance,
even christian doctrine,
I am glad that thou canst so fully subscribe to the "`anointing which is truth,
and is no lie;`" the unction from the Holy One,
as an internal evidence manifested in the soul.
What shall we do,
if we suffer ourselves to be drawn from this blessed Spirit of the Savior of men,
or the measure of it which is given to all, for our profit?
Where, but within our own hearts, shall we find the Comforter and the safe Guide?
Surely the holy scriptures direct us to Christ within, the hope of glory;
but _now_ we are told, that in looking for _inward_ direction, we subject ourselves to error;
and that the Gospel is to be found in the scriptures, where there is "`clear,
comprehensible truth,`" and "`a direct message from God.`"
True, the scriptures come by inspiration of God, yet, in my view,
the same inspiration must be with us,
to give us to comprehend their spiritual meaning and application;
because the natural man, by all his head knowledge and finite capacity,
even though he may compare scripture with scripture, and acknowledge to their harmony,
is, nevertheless, the natural or unregenerate man still,
without the operations of the Spirit in his soul;
even that which is the Divine gift to all men, and which, I conceive,
brings all who adhere to it, into a converted state,
whether they be favored with the inspired writings,
which tell of the blessed and holy Redeemer, or whether they be ignorant of them.
Must it not be our experience,
in order to partake of the benefit of the death and sufferings of Christ,
to be brought into obedience unto righteousness?
and what can do this for us, but the power of God, or name of Jesus,
which is immediately made known to us by inward revelation thereof?
In short, my dear friend, I feel alarmed in seeing that we, as a community,
are in great danger of leaning to the understanding of man,
in this day of the truly surprising "`march of intellect;`" and that,
for want of trusting in the Lord with all the heart,
we are going off greatly from first principles;
intermingling indeed with that which is not distinguished by gospel simplicity,
but which has a tendency to bring us to be satisfied with many things, out of which,
as a people, we were brought by a strong hand and a stretched out arm,
which delivered from the iron hand of cruel persecution,
as well as from all false dependence in religion.
All will not, however, thus return, either to the maxims and customs of the world,
or to the beggarly elements, to be again brought into bondage; a precious seed remaineth,
and will remain, however hidden,
in which the real life of the crucified Immanuel will be found;
and who will by and by come forth, and shine as the children of Him who is light,
and in whom is no darkness at all.
Yea, I believe it shall yet be the earnest inquiry,
relative to such as abide in the truth through all,
"`Who is she that looketh forth as the morning; fair as the moon, clear as the sun,
and terrible as an army with banners?`"
Ah! my long loved friend, I am persuaded that thou dost know what thou professest;
and the possession of the truth as it is in Jesus,
has been thy primary concern in the different stages of life: thou hast now, at times,
the certain evidence of having been kept from following "`cunningly
devised fables;`" and I humbly trust that the saying of Him who
enabled thee to separate thyself unto Him,
from all that is found in the apostacy, will be realized to thee--"`Lo,
I am with you alway, even unto the end of the world.`"
Amen, saith thy ever affectionate friend

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Eighth Month 13th, 1833.

At Chelmsford I was disposed to be found simply attending
to whatever might be required of me,
whether in silence or words; but the meeting was not to the refreshing of my own soul.
At the close of that with Friends, a public meeting was proposed and agreed to,
which proved very relieving to my poor burdened spirit.
The ancient, the everlasting power was truly in blessed and glorious dominion.
The house was full: it is calculated to hold eleven hundred.
I was full of heaviness before this meeting, but came back to the room where,
three hours before, I had groaned, and sighed, and prayed,
with a heart now replenished with gratitude and praise.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, near Colchester, Ninth Month, 1833.

[.salutation]
My Dear Friend,

Thy interesting and sisterly communication of last month,
merited an earlier acknowledgement.
I am glad thou hast been enabled to fulfill the prospect
of religious service that was before thee.
We shall surely find our account in minding that the day`'s work keeps pace with the day,
that in the end we may be ready to enter into rest; yea, a fixed,
glorious rest from all our labour.
I think I never knew such a trying time in my day as the present.
Some of us seem permitted to find peculiar difficulties in pursuing our course.
I cannot close my eyes to the wide deviations from our ancient testimonies,
which is, I believe, fast leveling us with the world at large.
I grieve, I mourn over these things in secret.
Sometimes I tell my sorrow publicly, under the constraining influence of gospel love;
and I have a word too, for the bowed down ones; but I am told again and again,
that my views are not correct;
in fact that there is no occasion to take up such a lamentation for us in this day.
Since I saw thee I have received divers visits,
which have not been of that kind most likely to strengthen
my hands to do what they find to do;
but through all, I could only endeavor to sink deep in my spirit,
and seek to have my reasonings hushed, my painful cogitations silenced,
that I might distinguish the voice of the true Shepherd.

Some of us see the necessity of being ranged conspicuously
on the side of primitive Quakerism,
and warning faithfully of the danger of things creeping in,
that from their nature and tendency must divide; must indeed, separate,
whether there be an outwardly drawing the line of division, yea or nay.
In fulfilling the will of our Heavenly Father, we must endeavor to leave _consequences,_
and run the risk of being ourselves wounded by the arrows of the archers,
and perhaps even carry the marks of our engagements with us,
like scars from head to foot, to be seen to the end of our day.

Ah! that which is opposed to the truth soon gains ground, when at all disseminated.
Truth, however, will obtain the victory in the end, and triumph over all.
Oh! that those who continue to hold it most dear,
may never barter it for any consideration whatever.

[.signed-section-closing]
I am thy sympathizing and affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Ninth Month 26th, 1833.

It was peculiarly joyous to me to find, by thy letter,
that peace and heavenly delight attended thee in resigning thy certificate.
How does even a short period of this Divine sense of consolation compensate for any
sacrifice or suffering attendant on obedience to the will of our Heavenly Father,
and inspire us with a desire still to run the ways of His requiring!
Mayest thou be strengthened to work the work of thy day as it passes;
not procrastinating, lest weakness ensue.
I find it very necessary for me to use diligence still,
for the Lord`'s own fit opportunity is not at human command,
and it would be sad to die a fool at last, through negligence.

The meetings we have had with those not of our Society,
have been truly unburdening to my heavily laden spirit.
As for those we have sat with our own dear people, but little relief has been obtained.

In the large Quarterly Meeting at Chelmsford I found my lips entirely sealed,
and that at Bury was not like former times.
I did speak, and found myself constrained to allude to the occasion for sorrow,
because of great departure from primitive purity and simplicity, etc.;
warning of the consequences hereof;
speaking also of the incalculable mischief already produced.

Thou mayest see how hard it is to get along now, in the line of service allotted me.
Sometimes my nerves are much affected, so as to deprive me of rest,
which thou knowest to be extremely distressing.

My husband and I returned yesterday to this place,
after attending London Quarterly Meeting, to which I felt attracted.
In that of Ministers and Elders,
I was enabled to declare plainly what the fashionable doctrine now preached among us,
would lead to;
and to warn us of the danger attached to leaning
to our own understanding in spiritual things, etc.
This great Quarterly Meeting looked awful to my mind,
but I knew it was to follow my Master I gave up to go so far in order to attend it,
which was every way a sacrifice.
As regards the Women`'s Meeting, I have brought the burden of the word back again,
although I felt like a vessel wanting vent;
yet I do feel conscious of having endeavored to stand faithful.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Tenth Month 21st, 1833.

Some do indeed appear to be followed by trials and crosses attendant on a state of probation,
much more closely than others; and exactly in the way too,
which their natural feelings most shrink from;
but we find it a vain effort to desire the choice for ourselves,
with respect to those tribulations that we do know are to be met with in our pilgrimage;
neither can we conclude on what is best for us; so that after all,
our only refuge is the eternal Rock of salvation, in every exigency;
and yet we find it frequently extremely difficult to flee there,
away from all the extreme sensitiveness and disquiet of the poor, frail creature.
Nevertheless it behooves us to seek this "`shadow
of a mighty Rock,`" in the weary land where we sojourn;
this covert from heat and from storm;
even He who is also "`as rivers of water in a dry
place;`" for should we not otherwise perish?

I hope nothing will be able to move you or us from our steadfastness
as to the faith in the revelation of our holy Redeemer,
by His Spirit in our souls as an abiding principle of light and life;
and oh! may nothing be able to prevent our increased acquaintance herewith.
I am indeed made abundantly sensible of the very
great frailty and weakness to which I am subject;
yea, which for the most part encompasses me about; yet to whom shall I go,
or to whom shall any of us turn,
but to Him who carried our sorrows and bore our griefs in a body of flesh;
and who is in us, our all-sufficiency,
although He often appears for a season to be deaf to our cry;
and when the vessel is tossed on the mighty billows,
and we are doing all in our power to help, is, as it were,
"`asleep in the hinder part of the ship.`"
Ah!
He will in due time "`arise,`" and evidence that the cry of the poor,
and the sighing of the needy, is not in vain.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Eleventh Month 19th, 1833.

No doubt you remembered us and our solemn engagement.
It was a very crowded meeting, and it is thought hundreds went away.
It proved a time of laboring in the Gospel,
and I believe may be acknowledged as a season of renewed favor.
I remarked to this family that my work had been pulling down old buildings;
that the dust was choking,
and the crumbling walls in some apparent danger of breaking the head:
thy dear father replied, "`_Thine_ was not broken: it was a good meeting, and ended well.`"
They say the states of the people were remarkably spoken to,
which they knew to be the case from their acquaintance with circumstances.
The meetings at Bardwell and Bury proved solemn times to my exercised mind,
but hoping so soon to see you, I need not now enter into particulars.
As for +++_______+++, it is very remarkable;
but I rejoice that you are favored with a just sense,
that all these things are under the control of that
wisdom and power that is inscrutable to us.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, Twelfth Month, 1833.

This day, on returning from a meeting by +++_______+++, like a conclusive Quarterly Meeting,
your joint letter lay on the table in the parlour,
which of course I was ready to open with eagerness;
and may now assure thee you need not suffer a moment`'s anxiety about us.

Yesterday we gathered in about as large a body as
I have ever seen at the Quarterly Meeting here.
First +++_______+++ kneeled.
After this offering, Elisha Bates stood up as soon as appeared suitable.
He spoke nearly all the rest of the time we were together,
which was until about a quarter past twelve.
He is indeed mighty in the scriptures, beyond any one that ever I heard.
Oh the eloquence with which he spoke!
Really it did _seem_ to bear down all before it.
I never, in my life, witnessed the like.
There is, nevertheless, a "`but`" in my mind.
I have heard the most decided applause and approbation,
and I have _not heard anything else._

A conference such as I wished for, is proposed by Thomas Shillitoe,
and I hope will shortly take place.
The meeting today was very large: it held two hours and a half:
the vocal engagements were chiefly by +++_______+++and +++_______+++.
I have been wholly shut up except in the Select Meeting,
but I quite believe I am in my place.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Twelfth Month, 1833.

I fear, lest by the powers properly belonging to the mere man,
attempts should be made to work the works of the Holy One, who, we may recollect,
said to His followers, "`Without me ye can do nothing.`"
Oh! my dear, there seems but little now to be met with, of that pure, simple,
deep waiting for, and moving in the ancient and everlasting power,
which was so eminently our dependence once, and our glory too, as a people.
The work of modeling us anew by human efforts goes on,
and the cry of peace and prosperity is loud.
Safety appears to me to be proclaimed in the midst of danger.

In the country where we have labored of late,
I have found some considerable enlargement among those out of the pale of our community;
and at the Quarterly Meetings for Essex and Suffolk, some way was made for me; in Essex,
to call from a worldly spirit,
and warn very forcibly against the approaches of that which would deceive
"`with enticing words of man`'s wisdom,`" with which I did believe they
would be assailed beyond what they yet had met with;
but in Suffolk I found a strong opposition to the simplicity of the pure Gospel,
and had to go forth, as it were, sword in hand, against this subtle spirit,
Oh! it was a sore combat, yet I found that there was a gaining ground more and more,
until at length victory was indeed obtained, and truth triumphed gloriously:
still I had to say that I feared there would be a
rallying again in the camp of the enemy,
because of the pride of man; but oh! the sweet peace that, after this engagement,
flowed into my heart!
It was indeed more than a compensation for all I had suffered;
and early next morning that declaration of our dear Lord was livingly applied to my soul,
"`Your joy no man taketh from you.`"

In the Select Quarterly Meeting in London,
I felt constrained to speak of our dangerous state, and call from that which,
however specious, was making the head sick and the heart faint, in our body as a Society.
I felt a mighty current against my testimony, but was enabled to deliver it faithfully,
and to invite from all that would insinuate itself as an evil disease, yea,
a noisome pestilence walking in darkness--more to
be dreaded than that which laid low the earthly tabernacle,
and brought it to the silent grave.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Twelfth Month 29th, 1833.

Poor Daniel Wheeler has been tossing about with contrary winds for many weeks,
near Spithead.
He has written some very instructive letters to different friends,
and sent them from the ship.
He seems to be in a most desirable frame of mind.
What a brave thing it is, my dear +++_______+++,
to be entirely resigned and devoted to the Divine will,
as is the case with this dedicated servant of the Most High.

Be assured I bear thee on my heart continually.
I much hope thou waits upon the Lord.
It is good to retire every day, once or twice,
and prostrate ourselves in secret before Him who sees from
the beginning to the end of all that relates to us,
His creatures,
and I am persuaded designs to overrule all for the
ultimate good of those who seek His guidance,
and who love Him as thou desirest to do.
Farewell for the present.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, First Month, 1834.

I hope in two or three weeks to be with you again,
and take my pleasant walks with my precious +++_______+++.
Thy dear brother has our sympathy and our prayers.
Let us not give way in the least to a disposition of discontent,
or as thou properly styles it, "`murmuring:`" who knows, but if we do so,
the same _fulness_ may be dispensed,
which was the case with the ungrateful and impious people
who hardened their hearts in the wilderness travel;
even notwithstanding they had seen the Lord`'s wonderful works;
and so it pleased Him with whom nothing is impossible,
to bring upon them great abundance, and with it great cursing;
for while in the midst of this plenty, death came over them.
How far preferable is it to have the best life preserved in the trial of faith,
than to become carnally minded, and without this holy keeping;
although we might accumulate wealth, and therewith feed the sensual appetite.
Oh!
I am glad in the assurance that none of us are craving after _great_ things;
and I do humbly trust that the Most High will appear on our side one day,
and convince us, one and all, that He giveth to those who love Him, "`grace and glory,
and doth not withhold any _good_ thing "`--anything that is really good for us.

Let us, as thou sayst, "`number our remaining blessings;`" yea, may we not forget--

[verse]
____
E`'en crosses from _His_ sovereign hand,
Are blessings in disguise.
____

I shall be glad, I think, to get to quiet Lexden;
hoping we may be comforted in each other.
I think of you individually, and with most tender interest;
and I do ask a blessing for you, my dear children.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
First Month 9th, 1834.

Yesterday was our Monthly Meeting.
I think the meeting for worship was a good time.
I was glad to be there, although I had been but middling since First day,
with something of a cold.

I think a deal of thee.
Surely thou art under the peculiar care of thy Heavenly Father,
who marks thy sincerity and love to Him,
and who hath made thee measurably acquainted with the coming and power of thy Redeemer,
even in thy own heart.
I would have thee seek to strengthen thyself in His mighty Name,
and do His will faithfully; then all will ultimately be well with thee.

I fear poor Daniel Wheeler cannot yet get off.
I heard a beautiful letter from him the other day, and as I have thought much of him,
it seems to me that he is a chosen vessel unto the Most High.
They are greatly to be felt for: they live on board the vessel,
and are often drenched with rain,
and the sea finds its way into the lower parts of the ship;
dashing with violence from end to end of the vessel, so that they cannot keep dry,
nor use exercise.
We ought to wait upon the Lord on their behalf,
in whom dear Daniel resignedly places his whole confidence,
while yet he is much alive to his situation.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, First Month 13th, 1834.

[.salutation]
My Dear Friend,

I scarcely know how to think that thou wast refreshed, and thy faith confirmed,
by what was dropped this morning in the ministry.
It was the language of my heart,
"`This will not do;`" for it appeared to me to be a cry of peace, peace,
where no true peace is.

I could not subscribe to the communication as being "`heavenly,`"
yet it seemed to me to be the exact _semblance_ of it.
Is there not a danger of endeavors being used to gain over a champion
to that which is estranged from the cross of Christ,
and the commonwealth of Israel?
I was reminded by what occurred in meeting today,
of what fell to my lot to express in the Yearly Select Meeting;
that there might be so fine an imitation of precious gems,
that none but connoisseurs could discover the counterfeit.
Oh! the depth of this species of Mystery Babylon`'s devices.
It seems to surpass in subtlety almost anything that has ever tried our Society,
and is calculated, in a wonderful manner, to beguile the unwary.
What need we have to dwell where the spirits can be tried, whether they are of God,
and where our own spirits can be kept subordinate to the pure, meek,
yet steadfast principle of truth.
Ah! it is indeed an awfully trying time,
but "`the cup of trembling`" will one day be taken out of the hand of an afflicted remnant,
who are willing to be "`of no reputation,`" that they may stand firm to
the immutable testimonies of the Gospel of our dear Lord and Master;
continuing to "`fight the good fight`" of faith;
to profess a good profession before many witnesses;
laying hold of that which sees to the end of all darkness, sorrow, and perplexity;
and is the eternal recompense of those who grow not weary in well-doing.
So mayest thou, dearly beloved friend and brother, be kept by,
and fare well in Him whose thou art, and whom thou dost serve;
even the Lord God and the Lamb; to whom be ascribed all might, majesty, and renown,
forever and ever.
Amen.

[.signed-section-signature]
Sarah Grubb.
