== Chapter 17. Letters from 1834--1836

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Evesham, Tenth Month 6th, 1834.

I seem to feel it so long since talking to thyself,
that I embrace an hour for this employ--it seems more like
a mouth since leaving you than scarcely ten days.
R+++.+++ and A. B., as well as many others whom I meet,
welcome me most cordially within their borders.
We had a very, very large meeting in the town-hall, or shire-hall,
at Evesham on First day;
concerning which I have to acknowledge to the mercy of our Almighty Helper,
who was eminently with us, after all my previous suffering,
and deep sense of the fearfulness of these steps, even under the full conviction of duty.

_Ross, 7th._--The dear old woman Friend here received us with joy.
The public meetings exhaust me a good deal,
but what could life be spent in to so much advantage, as being given up in body, soul,
and spirit, to the Divine will?
Surely it is this that produces real comfort now,
and enables to lay up a good foundation against the time to come.
Oh! that my beloved may more and more be put into
a capacity for adopting the poet`'s holy resolution--

[verse]
____
My life (if thou preserv`'st my life)
Thy sacrifice shall be.
____

Thou hast felt the lovingkindness of the Lord, and known His call,
"`Give me thy heart:`" let all thy affections be centred in thy dear Savior.

_8th._--Well! the dreaded engagement of last evening was got through with safety,
the great Captain being the bow and the battle axe; yea, the shield and buckler;
blessed be His Name!
Oh! I humbly trust truth had the dominion.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Hereford, Tenth Month 8th, 1834.

I closed a letter to thee at Evesham on First day,
before going to the great meeting there.
My soul was under baptism and exercise for the service when writing.
It proved a time of renewal of strength in the Lord`'s work,
for I humbly trust He raised the power of truth into dominion.

I had thought of getting through Ross without a meeting with the inhabitants,
but found it would not do;
my mind being made sensible of the secret intimation to seek an
opportunity to invite the people unto Him who is "`the way,
the truth, and the life.`"
They were long gathering, but I believe the Lord was eminently present; opening,
through a mere nothing, the truths of the Gospel,
and drawing the congregation to the blessed influence
of the spirit and power of Christ in them,
that there might be the hope of glory by and through Him.
The Friends here (many of them) are so loving, and seem so thankful that we have met,
it is contriting to my mind.

Yesterday did indeed seem to be "`a day that the Lord had made.`"
I could not find my way to stand up early in the meeting,
but seemed to myself like a vessel heavy laden,
waiting for the tide to get under weigh safely; and at last rose,
and was helped wonderfully to declare the truth, to my own great relief, and, I believe,
to the arousing of the careless, and comforting and strengthening the precious seed,
that felt unspeakably near to my life in Christ.
The meeting held nearly three hours, and closed very solemnly,
after near access in prayer and thanksgiving: many not Friends were present.
Perhaps I never felt more exhausted than when this great meeting was over,
nor more as if I had been taken into the hand of the Great Master for His own purpose,
as a mere channel, and was now again quite empty, and poor, and weak in my own eyes.
I had thought that it might be enough,
so that I looked toward being excused from holding a public meeting;
but no--I must have one this evening in the shire hall.
Oh!
I hardly thought that so much of this was in store for me;
how should I have been able to support the weight all at once?

[.letter-heading]
To the Same.

[.signed-section-context-open]
Worcester, Tenth Month 13th, 1834.

We had a very great meeting on sixth day evening at Hereford:
I found it rather laborious, but we had best assistance,
and a sense covered the assembly of that influence
which is stronger than all that gainsays it.
I was under the necessity of appointing a meeting for the inhabitants here last evening:
it was crowded to excess, and as at Hereford, many went away for want of room.
Here also I found it somewhat laborious, the people`'s views being very much outward;
yet, through Divine mercy,
I seemed led safely through a long testimony to the spirituality of the gospel dispensation, etc.
We had here likewise a precious covering, which increased, and the meeting closed;
prayer and thanksgiving having been offered up to
Him who remains to be the Helper of the helpless.

I have been this morning to visit dear old J. P., who is in his ninety-fifth year.
He seems in a heavenly state of mind, and appears so patriarchal,
that he quite resembles the ancient Jacob,
according to the account of him left on sacred record.
Yesterday we dined at T. B.`'s. They have a son who is greatly afflicted,
but oh! my mind was led to behold transcendent loveliness in him,
which did enliven my soul, and I had to tell him so.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Uxbridge, Tenth Month 18th, 1834.

We had a crowded public meeting at Charlbury, which was a remarkably impressive,
indeed I may say awful time.
The people were mostly of the peasantry, but were very quiet.
The meeting closed with prayer and praises to the Most High.
At +++_______+++ yesterday I thought the life of religion was very low:
had to call the people to more diligence in the great work of salvation.
I felt a deal about a public meeting there; it, however,
seemed clear to me that there was no auxiliary, and that, for want of this,
I might be excused; as if a meeting was appointed,
there seemed no probability of sufficient notice being given.

20th.--The meeting at Jordan`'s has been much owned and favored.
More came than could get in, and they stood outside with their umbrellas up,
for it was wet.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, Eleventh Month, 1834.

We went to Croydon as proposed.
Our quarters were at +++_______+++`'s:
her house is like a model of what belongs to self-denial in furniture, etc.
There seems to be much genuine humility in her character: she is exceedingly kind to us.
We began the visit to the families on fifth day (at Devonshire House);
are going on diligently.
Your dear father generally speaks in the families.

This is thy time of life to mingle in suitable society; it improves the mind,
and opens the way for acquaintance with passing events, which cannot fail to be useful,
both as to the present time,
and also in regard to the years to which life may be lengthened.

We are in usual health, but begin to feel rather exhausted,
and look toward getting to you soon.
If it please the Great Master to give us a little rest of mind and body,
we shall be thankful.
Perhaps I never paid a religious visit anywhere,
that occasioned me more deep exercise of mind than this in which I am now engaged;
indeed I do not recollect any quite so laborious,
for the life of religion is very low in families, and often in meetings too;
but if we are getting on with our day`'s work,
and preserved from injuring the precious cause of truth,
it will prove an unspeakable favor.

[.letter-heading]
To J. H.

[.signed-section-context-open]
London, Eleventh Month 13th, 1834.

More frequently than the returning day, do I remember thee and thy dear family.
I have looked for some account of dear, suffering +++_______+++, and your circle generally,
but have met with no one to give me any information,
nor have I received any letter from Uxbridge since we parted.

I do feel much interested respecting you,
and want greatly to be able to visit you in idea as you are situated.
We know that the will of the Lord is best for us, and that it is not to be controlled,
but submitted to; therefore the more we seek resignation,
the more will wonders be wrought for us; our hearts being prepared to adopt the language,
"`Great and marvelous are thy works, Lord God Almighty.
Just and true are thy ways, thou King of saints.`"
May the Most High be pleased to lend the aid of His Holy Spirit,
by which hard things are made easy, and the bitter cup is sweetened;
and oh! may He bless tribulation to you, my long, tenderly beloved friends,
and to your offspring;
accepting the travail of the parents`' souls for their dear children,
and the sigh of some of the children for others of your family,
whether under the same roof or not.

Farewell.
I am, in the bonds of the Gospel, and while sensible of weakness and much trembling,

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Twelfth Month 12th, 1834.

I thought the Quarterly Meeting at +++_______+++ very exercising,
and could not obtain relief in the meeting for worship, where, after divers had spoken,
my dear J. G. uttered a few lively sentences, which it seemed right for me to allude to,
and a little apply to the condition of many.
In the Women`'s Meeting there was more liberty.
I should have been glad if the shutters had been
raised which separated us from our brethren,
but had not courage to make the request,
after hearing in London that some disapproved of my doing so, when there before.

Please let our dear friends in +++_______+++ know of this letter,
and that the retrospect of our late engagements in that quarter is not without
a humble hope that we were getting on a little with our day`'s work.
I am persuaded that such as you and +++_______+++ must come in for the reward of disciples,
in your willingness to assist those who professedly
go forth in the name of the Great Master.
As for me, I seldom am in any other state, on returning home, than under trial of faith,
which is now the case;
and I feel deeply my great unworthiness to rank among the soldiers of the Lamb,
or to be noticed, as I have recently been,
by those whose first concern it is to honor His blessed cause.

It does not appear to me that Essex Quarterly Meeting
is wholly clear of the mischief of novel doctrine.
My spirit was sensible of its existence, and borne down under it,
as well as with a great deal of the prevalence of the love of the world,
and the things of the world; which, it is to be feared,
with many almost excludes the love of the Father.
Oh! how oppressed is the pure immortal seed;
and through what labour of soul does the rightly exercised mind visit it;
and how long it often is before such rise superior
to that which bears down the life of God in our meetings!
Yet is He, the Mighty One, still with those who wait upon Him; yea,
and He will be with them, to His own praise and the edification of His people;
blessed be His excellent Name!

The query naturally arises with me.
Why should I go to Suffolk?
but I desire to leave all in the hands of Him whose
right it is to dispose of us from time to time;
and should so poor a creature be called to suffer with Him who said,
"`The servant is not greater than his Lord,`" etc., and,
"`It is enough for the servant that he be as his
Master,`" surely my soul shall rejoice and give thanks:
my wish is to be just what He pleases, no matter how despicable.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Twelfth Month 21st, 1834.

If I never wrote thee a word, nor had verbal communication with thee,
believe me thou art engraven on my heart, all trembling as it is in these perilous times.
My dear friend +++_______+++ is frequently in my remembrance,
with religious and affectionate solicitude that his race may not
be rendered more difficult than ought to be the case,
by any undue pursuit of things relating to the present life.
Time is short, and the clay is clogging.
Oh! my soul yearns towards this long-loved brother,
with tender and fervent desires that he may "`so run as to obtain.`"

The Quarterly Meeting at Ipswich on third day was to me a memorable time,
for my Master raised me up in His own authority, so that I seemed, in my measure,
as an adamant, harder than flint;
or as a brazen wall before that which opposed itself to the truth:
the relief this season afforded may be better conceived than described.
It is, under any circumstances,
cause of true rejoicing to be brought into the capacity to endure hardness,
and suffer reproach for His sake, who, in adorable condescension, and love unutterable,
became a man of no reputation, for a sinful world.

It is with feelings of deep and tender sympathy,
that I hear of the continued sinking of nature with respect to dear Mary Hull;
but a humble hope attends my mind,
that the purified spirit wings its way to those regions
where temptation and sorrow are not known.
Still, who can but be moved at the ravages of sickness, of suffering, even unto death?
It involves the affectionate parent in poignant grief; the brother, the sister,
the friend, in the sense of a mournful chasm, not to be filled by any earthly gift;
for whatever blessings may be added to a family,
"`that which is wanting cannot be numbered.`"
May the Eternal Fulness Himself be graciously pleased to sanctify
the trying dispensation to dear William Hull`'s family,
and enable survivors to rejoice in His mercy, and be glad in His salvation.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
First Month 2nd, 1835.

[.salutation]
My Dear +++_______+++.

I cannot help feeling the separation from thee just now a good deal,
but apprehending it cannot well be otherwise in right ordering for a few days,
I must leave it.
I have ventured to appoint a public meeting for First day evening, at Gracechurch Street;
thy sympathy will again be awakened:
the expression of it in thy communications already received, is sweet to me.

May our loved +++_______+++ endeavor to accept the gracious invitation,
"`Come unto me all ye that labour and are heavy laden, and I will give you rest.
Take my yoke upon you and learn of me; for I am meek and lowly in heart,
and ye shall find rest unto your souls.
For my yoke is easy, and my burden is light.`"

Ah! it is coming to Him, and learning of Him true meekness and lowliness,
that renders hard things easy; for, in resignation of soul,
we are then able to cast all our care upon Him who "`hath borne our griefs,
and carried our sorrows.`"
Truly "`in returning and rest shall ye be saved;
in quietness and in confidence shall be your strength,`"
amidst the many trials and perplexities of life,
which none escape, however varied in form, or hidden from mortal eye.

And now, hoping, trusting, expecting, and believing we may very soon meet,
I subscribe myself

[.signed-section-closing]
Thy very, very affectionate mother,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, First Month 15th, 1835.

I left London very much depressed.
Perhaps it never fell to my lot to obtain so little substantial
relief in any previous going forth as a minister;
notwithstanding it cost me great conflict and suffering to leave home,
and also again to show myself in London;
but it behooves us to become willing to endure the misconstructions
even of those we greatly prefer to ourselves,
when our words and conduct too, appear to them to be erroneous,
while we can appeal to the Searcher of all hearts,
that we have nothing in view that is of a sinister nature,
or that desires anything contrary to His holy will.

I suppose thou dost not think that anything was elicited at the Morning Meeting,
calculated to render Friends of the old school less uneasy than they have long been,
respecting the novel opinions that are afloat.
I confess that my apprehensions were rather confirmed,
for there seemed to be a disposition to cover and gloss over the unsoundness,
so as to make it less tangible than when so much caution in expression was not observed:
however this likewise will, sooner or later, be detected,
and made manifest by that Spirit which "`searcheth all things,
even the deep things of God;`" yea, "`the hail shall sweep away the refuge of lies,
and the waters shall overflow the hiding place,`" however we may
fortify them in the strength of that wisdom which is from beneath.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, First Month 25th, 1835.

How grateful it was to receive a letter from thee,
just after my setting out on the journey westward:
the encouragement held out helped to strengthen my faith:
what was expressed relative to my leaving my dear family,
at a time when pestilence was carrying off divers around us, was very striking,
and thy words had been previously in my own mind.
It did indeed please Infinite Kindness to spare us the trial of
any "`evil coming near the dwelling,`" which was left under an
awful sense of the constraining influence of gospel love;
and perhaps it never fell to my lot to obtain more relief in any engagement of the kind,
than was the case generally by my labour on that journey.
On arriving in London, however, after the accomplishment of what had been before me,
I could not see the way home; a field of further labour opened there,
but how different have been my feelings in getting through the service!
But little openness appeared in the minds of the visited, except in a few instances,
either as to families, or exercises of a more public character.

Oh!
I was greatly oppressed.
I felt much exhausted in coming back from London.
I fear the evil root is spreading and strengthening itself in a hidden way.
What the end will be time must reveal;
but certainly there seems little room now for the simple way of preaching
that Friends have always been distinguished for in their ministry.
I am glad of the extract from William Law`'s writings which thou sent me.
I recollect being pleased with his sentiments many years ago.
He appears to have been a deep-spirited Christian.
I was greatly treated by the company of R. B. for some days,
in my late journey to Hereford, etc.
How sweet and refreshing it is to be able to recognize the precious life of truth immutable,
one with another.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
1835.

Mayest thou,
and may thy dear wife be enabled to put on more and
more strength in the name of the Lord;
to prove yourselves faithful burden bearers in the present oppressive time; that,
as laborers in the Lord`'s vineyard, you may reap and receive wages,
and gather fruit to life eternal!
It is not for us to seek obscurity when such may not be our allotment in Divine ordering;
nor to flinch from reproach and shame for the sake of our dear Master,
and His ever-glorious cause.
While writing I remember dear R. Reed, and consider, that in her measure,
she is given up to serve the Lord in solitude;
and although she may not conspicuously bear the burden and heat of the day, yet,
in that way appointed (as this is held on in) the "`penny`" is made sure;
even that which is soul-satisfying, and more than which, who can obtain?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Second Month 10th, 1835.

You have both been fellow-helpers of us, from time to time,
in our feeble efforts to fulfill public duty, in obedience to our Divine Master:
may He be known graciously to recompense your labour of love,
and may we be more and more united as children of the same spiritual family;
even in that which knows no change, and which cannot be divided!
Do tell dear R. R. that she is often in my remembrance, and I feel for her sufferings,
amidst my own pressure, which sometimes seems almost beyond strength;
so that I fear lest the hold should be let go,
while striving to cleave to the invisible and invincible arm of Omnipotence; but still,
at times, there is a hope felt, sure and stedfast;
and I do conclude that we had better hope even against hope;
for when there seems nothing present with us to cheer our drooping minds,
it behooves us to watch against casting away our confidence,
and so being beguiled of our reward.

I fear there is a confederacy among us, which hath not the sanction of His spirit,
who still sustains the name of "`Counsellor,`" with
those who feel that without Him they can do nothing.
But surely "`the Lord will do a marvelous work among this people,
even a marvelous work and a wonder; for the wisdom of the wise men shall perish,
and the understanding of the prudent shall be hid;`" even when the simplicity of truth,
its wisdom, and its power, shall be raised into dominion again.
How shall the meek then rejoice in the Lord,
and the poor know what it is to joy in the Holy One of Israel!`"
for the house of Jacob shall not be ashamed,`" seeing that
the dependance of this wrestling seed is in the Lord alone,
in whom is strength everlasting.
It is exceedingly gratifying to us to receive intelligence
of our dear brethren and sisters,
and to know when and where the right thing prevails.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Third Month, 1835.

I have but a short time to spend in this way,
but am desirous of acquainting our dear children with our welfare,
during this Quarterly Meeting.
Yesterday and today have been times of renewal of strength to some of us.
I was favored with a brave, courageous time, both days,
in defence of our ancient principles; so that I feel easy,
which is no small mercy to so poor a creature.

My dear love is to +++_______+++and +++_______+++. I am glad in the
hope their simplicity in religion is blessed to them.
May they maintain it! "`The Lord preserveth the simple.`"
It is a precious thing to be sincere, humble, and faithful,
in the sight of Him who sees not as man sees,
and whose ways are declared to be infinitely higher than the ways of man,
even as the heavens are higher than the earth.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fourth Month 1st, 1835.

I have been with you in thought almost unceasingly, since we parted; and often,
very often, have my petitions been put up to the Lord on your behalf.
No doubt, my dear, it is, as thou art favored to see,
much better for us to submit to the will of our Heavenly Father,
than to please ourselves; for He does indeed know, and He only,
what is for our real interest.
"`All thy children shall be taught of the Lord,
and great shall be the peace of thy children.`"
And if the teaching is sometimes by discipline, severe to the natural part,
seeing it is in wisdom inscrutable to the understanding, but perfect in itself,
the "`torment`" is worth enduring.
"`Wisdom tormenteth with her discipline.`"
Your poor, insignificant mother can subscribe to this truth from living experience.
I should have had less peace now in my old age, but for having been, in early life,
and many a time since, disciplined under the cross of Christ Jesus,
my dear Lord and Savior.
Neither can we make choice of our trials, but must endeavor to leave all to Him who,
in His own body, "`bore our griefs and carried our sorrows.`"

[.letter-heading]
To Mary Capper.

[.signed-section-context-open]
London, Fifth Month 26th, 1835.

Thy sweetly encouraging and instructive lines must be acknowledged.
How truly kind it is of thee thus to remember us from year to year;
and how precious is this manifestation of thy continued sisterly, yea, christian love!
Here we are once more attending the Yearly Meeting.
Our family are much struck with thy communication, so lively,
and so adapted to our present circumstances.
The thoughtfulness which attends me has a tendency to impair my health: I suppose,
however, that this shattered tenement will hold out just long enough.

My dear husband heard thy letter with grateful feelings.
Probably thou hast heard of his having nearly lost his sight,
but the inward eye is not dim.
He has nobly evidenced clear-sightedness during the present Yearly Meeting,
and a trying time it is!
Oh! the want of true simplicity, of best wisdom, and of keeping to the power of truth!
It seems as if there was danger of idolizing the human understanding now,
and bringing all things to the test of reason; so while we say we see,
our blindness increases to an alarming degree;
and not a few (it is to be feared) are stumbling upon the dark mountains,
having wandered from the safe abiding in the lowly place;
comparable to the situation of the people of the Lord formerly, when it was said,
"`As the vallies are they spread forth,`" etc.

Again and again has the right thing been raised into the
ascendancy over that which would have taken its place,
and which sought to keep down the lowly life of the Lord Jesus.
We have been thankful in feeling that it was limited;
but oh! there remains to be great occasion for lamentation.

I was constrained to request a meeting to be appointed for our youth,
which the Yearly Meeting complied with; and where, I humbly trust,
we felt the gathering arm of Him who is the good Shepherd, and who careth for His sheep.
This concern, so truly formidable in prospect, has much relieved my poor, exercised mind.

How happy for thee to be brought through the ocean of life to thy present calm haven;
waiting to be safely landed in those regions where all is peace; yea,
joy unspeakable and full of glory.
So farewell in the Lamb, who doth lighten that country; and who, with the Father,
is the everlasting light and glory thereof.
I remain Thy affectionate friend in tribulation,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To a young Friend.

[.signed-section-context-open]
1835.

Divers in the last stage of life are removed from laboring in the spiritual harvest, who,
I have no doubt, have gathered fruit to life eternal, and thus their works follow them.
Now we look for preparation and qualification in the rising generation,
and in those of some maturity of age;
that they also may "`reap and receive wages,`" even soul-satisfying reward,
while employed by the Great Husbandman in the whitened fields.
The operation of that power that can fit for service
has been known (blessed be the Lord);
may this be abode with, and fully submitted to!

[.letter-heading]
To one of her Children

[.signed-section-context-open]
Sudbury, probably 1835.

How very interesting is thy account of our beloved friend.
Oh! it is indeed sweet and precious to be able to see a
soul sinking into the Source and Author of all real,
lasting enjoyment!
I have long been without a doubt that this prepared spirit
of hers would find "`joy unspeakable and full of glory.`"
A glory suited to the capacity of all the Lord`'s redeemed is given them to the full;
and whether the five-talented, the two, or even the one,
the joy of their Lord is soul-satisfying, is full of glory.

I think I visited this congregation pretty thoroughly in the morning,
standing perhaps an hour.
I was marvelously helped--no merit of mine.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Probably 1835.

It is with thankfulness we receive the pleasing account of you which thy letter conveys.
Oh! may our Heavenly Father enrich you with spiritual blessings, to His own praise,
and your stedfastness in Him who is "`Alpha and Omega,`"
in the experience of His poor children,
as they seek to be faithful in His sight.

So our dear aged friend has departed.
Dear creature!
How sweet! how happy!
No more sense of the sinking of nature under a wasting disease;
no more suffering of mind or body.
My heart is ready to say, "`Blessed be the Lord, who, in the fulness of time,
releases His dear children from the shackles of a mortal frame.`"

This morning, at +++_______+++`'s,
we met our friends +++_______+++ and +++_______+++. The latter ministered to us all.
She spoke to my real condition,
and encouraged me to believe that the armour of righteousness,
on the right hand and on the left, with which it had pleased the Most High to clothe,
would still be the covering; the weapons being "`mighty through God,
to the pulling down of strong holds,`" etc., etc.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Sixth Month 21st, 1835.

I want to know how it was with one,
who at times felt the tendering influences of the love of a crucified Savior.
How glad shall I be to find that the survivors had the consolation of
an assurance that the spirit was mercifully accepted in the Beloved;
not that I consider such a manifestation necessary, nor that it is always given,
when even all is well, abundantly well forever;
but oh! when the Comforter is heard to say,
"`iniquity is pardoned;`" the warfare is accomplished, heaven is obtained;
how does this lessen the poignancy of that sorrow which
the severing hand of death brings to a sympathetic,
affectionate heart!
We have now passed much of our day,
and in the retrospect perhaps we see that we might have improved it more,
and have spent it better.
I know that it is so with me,
that I am at times ready to be "`dismayed`" at the seeing of it,
and bowed down at the awful call, which even the infirmities of years proclaim,
"`Set thy house in order,`" etc.;
but let us be encouraged to press toward the mark for the prize; hoping,
that as we are so engaged, we may win the crown that fadeth not;
for great and unfathomable are the tender mercies
of Him who is our Judge and our Savior too.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Seventh Month 5th, 1835.

Truly it is no light thing to come up to the great city, at least to some of us,
who have found it a place of great oppression, and of combat, with very little auxiliary;
not but what I appreciate the brotherly kindness,
the affectionate attention and help of which I have been, at times, an unworthy partaker;
but oh! how few there are,
willing to come forth nobly in the cause of our adorable Captain and Chief;
hating their own life for His sake and that of the Gospel!

There have long been wanted more efficient arrangements in London and elsewhere,
for the suitable care of traveling Friends,
in that way which would bring the expenses to the national fund.
In divers instances the expense of travelers is too heavy, even to oppression,
in poor Monthly Meetings.
I wish, and have wished for years,
that the subject might claim the attention of the Meeting for Sufferings.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Ninth Month 16th, 1835.

The Quarterly Meeting yesterday was very small.
There seemed a little way to open for me to unburden, which I thankfully embraced.
I think the meeting was favored in degree.

Whether under any peculiar exercise of mind or not, my dear children are present with me,
in fervent desire for your preservation and establishment in the blessed,
unchangeable truth: and I believe that the many conflicts permitted to attend you,
are surely designed to have so desirable a tendency,
that you may be settled in that which outlives all sorrow and disappointment,
and which certainly renders hard things easy, and sweetens the most bitter cup.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Tenth Month, 1835.

It is when we are drawn from expecting to be satisfied with things that are seen,
and are temporal, having our affections set upon things that are not seen,
and are eternal, that we come into the possession of substantial happiness,
and a peace that remains,
even under the tossings and trials that are to be met with in this chequered scene,
and which we all have to witness in some way or other.

I have thought,
how different is our situation from that of the immediate followers of the blessed Immanuel,
who were "`in hunger and thirst, in cold and nakedness,`" etc.:
who went about in goat skins and sheep skins; "`of whom`" indeed, it might well be said,
"`the world was not worthy.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Twelfth Month 6th, 1835.

As for our beloved brother in another part of the world, Daniel Wheeler,
it is really marvelous how way is made for him, from time to time,
to bear testimony to the power of his Divine Leader,
and to show the insufficiency of all that properly belongs to the mere man.
Oh! it is this simplicity, this keeping to the wisdom and power of Christ Jesus the Lord,
that will indeed promote the Redeemer`'s kingdom in the earth;
which kingdom must take the place of that of darkness,
until all is put down that opposeth itself to the righteous government of Him,
whose appearance among men produced the language, "`Glory to God in the highest,
and on earth peace; good will toward men.`"
How I wish that all who profess to be ambassadors for the Immortal King,
would "`cease from man;`" but there seems to me to be occasion for jealousy, lest,
acting out of the influences and movings of the anointing, some, even under our name,
should lay stumbling blocks in the way of such as
are enquiring the way to Zion with their faces thitherward.
I trust, however, (with thyself) that wrong things are more and more discovered,
and the subtlety of the serpent marked,
so that his real character is not hidden from many honest-hearted ones within our borders,
who perceived not, for a while, that he was laying waste amongst us,
as a religious Society.

I observe thy remark that our American brethren have got before us--yes,
because we closed the eye, shut the ear, and hung down the hands,
as regards the mischief which had so long been at work.

Many religious communities, as well as their individual members,
have not yet seen the fulness of the gospel dispensation;
and if these live up to what is made manifest, in and by the light afforded,
I never could doubt either their usefulness,
or their acceptance with Him who opens the mysteries
of the heavenly kingdom to His little ones,
as they are able to bear them.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Second Month 12th, 1836.

I have a letter from +++_______+++: she is rather low herself.
+++_______+++ and wife have resigned their membership.

Never fear! there will be Quakers still.
I hope, however, many will follow the example of these Friends,
that we may remove what hath let, and will let, the great work of the Lord,
while it is mixed up with the Society.

The Lord of glory bless you, my children; but first, and above all,
with that which can alone give you to grow in grace.
I often looked at you in my mind lately, as getting on well,
when I could be quiet from the cogitations of my natural disposition.
What should I do, were it not for the strong Tower, to which such a poor,
feeble creature, may flee, and be secure, while the floods lift up their voice without?
Oh! what I feel about thee!
It seems to me it is indeed required to dedicate
the whole man to Him who is worthy of all;
to bear the needful preparation, and to be found faithful in His service.
He would indeed lead in Wisdom`'s ways, whose ways are pleasantness, and her paths peace.
Yet this is that Wisdom which at first tormenteth with her discipline.
It is all in order that she may deal out her bread,
which nourishes and strengthens the inner man;
and that there may be a partaking of the wine that she hath mingled;
even for the replenishing and gladdening that part which cannot
be satisfied with anything short of the uncreated substance.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Second Month 27th, 1836.

And now, my precious +++_______+++,
let me charge thee to endeavor to get nearer and nearer to thy dear Savior,
who would increasingly give thee to walk with Him in the "`fine linen,
clean and white;`" the righteousness of those who
resign themselves to be sanctified by Him.
Ah! this clothing is worth having; purchased for us by the blood of the Lamb immaculate,
who freely grants the lovely robe to all who are willing
to submit to the refining operations of His blessed Spirit.
It is true that we must come through much or great tribulation,
to obtain the rich covering; and surely thy youthful days have been, often and many,
days of deep suffering: thou hast been as one that went down to the sea in ships:
hast seen "`the works of the Lord, and His wonders in the deep:`" thy bark,
all tossed and tried,
has been like "`a drunken man,`" who "`reels to and fro;`"
and again thine Almighty Helper delivered thee.
He designs to show forth His own glory through thee, as well as in thee.
Oh! stand at His disposal.
He hath brought thee through a day of cloudiness and of thick darkness;
of perplexity and treading down:
shall He not be magnified in giving thee now to stand on the "`sea of glass mingled
with fire;`" (a state of danger) but where the harp of victory is found in the hand,
with the song in the mouth, "`Great and marvelous are thy works, Lord God Almighty.
Just and true are thy ways, thou King of saints/`' who shall not fear thee?`"etc.

It is profitable to retire each day, and, in nothingness and in silence, seek the Lord.
It helps us.
It may not seem to profit at the time, but it no doubt is praying in secret;
and our Father who sees in secret rewards us openly,
by correcting our proneness to trifle away the strength of the mind,
and checking our natural temper;
for there is something in all which requires the regulating power of Jesus Christ,
who was meek and low of heart.

I hope thou art aware that my soul breathes this
advice in unspeakable tenderness towards thee.
So farewell.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Third Month 20th, 1836.

Oh! the wisdom of this world! what mischief it does by meddling
with that which it cannot comprehend! but I do believe that
the simplicity of the Gospel will yet prevail over it all,
even within our pale; and Babel builders will be confounded,
as indeed they have ever been.

I wish not to anticipate the coming Yearly Meeting: there is, however,
a class very active at such times,
who can accommodate themselves to circumstances and to persons too,
so as to hold fast their own reputation.
These try my feelings greatly, for it is such who,
not being decidedly and openly for the good cause, and that which changeth not,
nor avowing themselves on the side of those who have gone away from us,
are secretly retarding the work that must divide and scatter,
and remove all that will not bear the scrutiny of the light;
and many dear young people are staggered by their means.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Third Month 24th, 1836.

My hope is that the Lord is already beginning to heal us as a people,
and that He will speak to us "`with stammering lips and
another tongue,`" than that we ourselves have chosen;
that all may fall and turn backward, that is in the contrariety to the Divine will,
and oppresses the precious life.
I cannot do with that spirit, too prevalent now in a sort of middle rank,
which turns with the wind, like a vane; not having the stedfastuess which is in Christ,
but pleasing self; unlike Him whose cause they would fain have it believed they espouse.
If Christ "`pleased not Himself,`" as the scripture testifies,
how can we be His disciples, who would not risk the loss of all things,
that we "`may win Christ, and be found in Him?`"
Perhaps there is nothing that we find more difficult to surrender,
than our esteem with those whom we really prefer;
even as serving the Great Master with manifold gifts bestowed upon them,
while our own appear to ourselves to be few, and comparatively very small;
but I believe that it is essential to our acceptance with our Judge and Savior,
that we should be single-eyed, and if He calls to it, fight His battles single-handed,
like little David with his sling, and the smooth stone from the brook,
"`hastening and running`" at the Lord`'s fit opportunity,
without hesitating to discover what such and such will think of us.

I am longing to receive some intelligence of our dear tribulated, yet dignified brother,
Daniel Wheeler.
Surely prayer, begotten of the Most High,
has been and is often put up on behalf of one so eminently endued with faith to persevere,
in the dedication of his all to the promotion of that truly grand object,
the reception of the kingdom of Jesus, by all nations;
so that the will of God may be done on earth, even as it is done in heaven.

Since our Monthly Meeting,
I have had some further engagements of this awful nature
(holding public meetings) and through renewed mercy,
to much satisfaction and abundant relief; which latter continues but a short time.
Oh! the baptisms of my soul!
I frequently feel such suffering, and apparent desertion of all good,
that it is indeed only by endeavoring quietly to keep hold of the shield of faith,
that I dare to prosecute the view of meeting the people, an unprepared,
unqualified handmaiden, until the power arises,
like the bubbling up of a well of living water, and reaches forth to their conditions,
even as streams, in the abundance of that love which would refresh and baptize,
and gather all to the "`pure river of water of life, clear as crystal,
proceeding out of the throne of God and of the Lamb.`"

It is very evident that, of myself, I am indeed but a worm;
and this worm sometimes has the foot of man set upon it.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, 1836.

It gladdens my heart to peruse those lines which
acknowledge to the insufficiency of self,
as to the performance of anything, however small,
for the ever glorious cause of that truth which we (as a people) profess,
and which will stand to the end of the world.
If, in all things, we learn to have reference to our own Almighty Helper,
we shall experience Him to be a very present help indeed, in the moment of extremity.
Thy poor mother can testify to that wisdom, that power, that simplicity,
in which we can do all things; for it is not we that speak or act,
but the Spirit of our Father within us.
I was engaged in the gift committed to me yesterday,
and in almost every meeting that has occurred since leaving you;
the Lord of the harvest being pleased to fill the cloud, and command the rain.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Fourth Month 3rd, 1836.

Oh! my dear +++_______+++,
keep close to the power and the wisdom thy mind is instructed to revere,
and which assuredly dwells within.
As for the things appertaining to this life, no doubt all will be granted that is meet;
in seeking first the kingdom of heaven (as thou desirest
to do) all other things will be given;
for our Heavenly Father knoweth that we have need of all these things.

We are much pleased with the remarks made by thee and dear +++_______+++ on
the letter from +++_______+++ +++[+++a letter from an individual expressive of disunity]:
there appears to be no use whatever, in laying myself open to controversy by reply,
only simply acknowledging the lines addressed to me.
Tell dear +++_______+++, that so far from being moved by them, my mind was in sweet peace,
sitting down in meeting today, and I was led forth to minister to those present;
nor would I have you discouraged at outward, any more than inward crosses;
for nothing shall offend those who love the Divine law,
which is of the Spirit of life in Christ Jesus,
and which setteth free from the law of sin and death.

I hope thou art designed to be one who "`warreth,`"
and who is not to be entangled with worldly cares,
to the hindering of pleasing Him who hath chosen thee to be a soldier.

Farewell, my dear and precious +++_______+++.
