== Chapter 19. Letters from 1837--1838

[.letter-heading]
To her Son.

[.signed-section-context-open]
Fourth Month 8th, 1837.

Thou and thy dear sister have my sympathy, as well as tender love;
and often does my soul breathe to the Father of mercies for you,
that you may still be led about and instructed by Him, and, like Israel of old,
taught to soar aloft as upon the eagle`'s wings.
Do read the text, "`As an eagle stirreth up her nest,`" etc.

How pleasant it will be when we can see the advance of summer!
We have now passed six months since the commencement of winter,
and really I think these few last days exceed in severity of weather;
but let us remember the covenant with the seasons,
and look forward to the flowers appearing on the earth, etc.

I seem wonderfully spared going out to meetings these few months.
I cannot expect the exemption to last much longer,
but hope to be kept in a waiting state, even "`as the eye of the servant to his master.`"

We are reading the life of William Penn: it is what my J. G. much likes to hear.
We have got as far as his recall from Ireland.
Dear young man! what true christian fortitude he possessed,
and what devotion of heart to his Maker!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Fifth Month 11th, 1837.

I am led to enrol the prospect of recovery among the many mercies of a gracious God,
which have been made known to so unworthy a handmaiden, from time to time.
It is not but what I was favored with a sense that, as related to myself,
it were better for me to depart;
for I did believe that I should be forever with Christ my Redeemer,
who hath washed me in His own blood.
Oh! eternally magnified and praised be His adorable Name!
He would have all come to the knowledge of Himself, and be saved.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Fifth Month 15th, 1837.

I am constantly thinking of thee and dear +++_______+++,
much desiring your progress in the way cast up for you;
the path of the redeemed of the Lord.
They "`shall come to Zion with songs and everlasting joy upon their heads.`"
Yes, for they deeply experience the judgments of the Most High upon the transgressing nature,
and also His adorable mercy and lovingkindness;
so these learn in the school of Christ to sing the song,
"`which none can learn but the redeemed from the earth.`"

Do thou, my dear +++_______+++, dwell under that power which, in measure, yea,
a precious measure,
has already been so dispensed as to work redemption to a certain degree for thee.
To be created anew in Christ Jesus,
and established in the righteousness which is His own,
often proves a work of considerable time; of years told over and over;
but do not grow weary nor faint under it,
for its blessed effects and precious fruits are worth waiting for with all perseverance.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fifth Month 23rd, 1837.

Yesterday I was very much discouraged about stopping from home,
feeling quite as if my health would not admit of my attending the Yearly Meeting,
but was favored to rest last night, which appears to have built me up again,
so that I have sat through this morning`'s meeting of nearly four hours.
Yesterday I found my way to express, in the first meeting,
what appeared to me to apply to our state as a part of the body at large;
and then I met our friend +++_______+++, but did not go to the second sitting.

[.letter-heading]
To the Yearly Meeting of Friends now Assembled.

[.signed-section-context-open]
1837.

[.salutation]
Beloved Friends--Brethren And Sisters,

Being prevented by illness from mingling with you at the present time,
I take this method of evincing the interest my heart is sensible of,
for the prosperity of truth,
and the maintaining of our ancient testimonies in their own character,
in that life and wisdom which is eternal.

First, I would address those who endeavor, in the fear of the Lord,
to uphold that standard which may not be lowered to meet the views
of such as do not come to the fulness of the Gospel of Christ.
Deep is the sorrow, and many are the baptisms and sufferings of the faithful,
in the present day;
but the Great Head of the Church will bless their exercise and travail, to themselves,
and to the edification of the body;
therefore "`let nothing move you from the steadfastness which is in Christ.`"
These will be enabled to adopt the language, "`Our feet shall stand within thy gates,
oh Jerusalem.
Jerusalem is builded as a city that is compact together: whither the tribes go up,
the tribes of the Lord, unto the testimony of Israel,
to give thanks unto the name of the Lord.
For there are set thrones of judgment, the thrones of the house of David.
Pray for the peace of Jerusalem: they shall prosper that love thee.
Peace be within thy walls, and prosperity within thy palaces.
For my brethren and companions`' sakes, I will now say, Peace be within thee.
Because of the house of the Lord our God I will seek thy good.`"

And oh! may all beware of choosing a path that looks pleasing to the unanointed eye,
and as though it must end in life and salvation, but not being straight and narrow,
to the aspiring, unsubdued mind of man, will, sooner or later,
be found to diverge into the broad way that leads to destruction!
An insidious spirit, ready to draw from the true fold,
is still amongst us in different degrees; but the Lord will more and more discover it,
by that which searcheth all things; however secretly,
and with whatever subtlety it may now be at work.
It hath done, and is still doing great injury to the rising generation of this people;
"`a people near unto the Lord.`"

Its voice is causing many of them to go from hill to mountain, as scattered sheep;
and great will be found to be the responsibility of those who have induced them
to turn a deaf ear to the monitions of the Good Shepherd in their own hearts.

And now, dear children, do you turn inward to Christ your Redeemer, who died for you,
that you might have blessed union with Him, and be valiant for the truth upon earth;
and ultimately find an interest in Him,
which brings to the full fruition of eternal glory.
The Lord hath not cast off His people,
but is still willing to gather and to own them amongst the nations;
and the "`Gentiles shall yet come to His light,
and kings to the brightness of His rising.`"

In that love which hath, during my day, enabled me to give up my little all,
for the sake of Christ, and His everlasting, immutable Gospel,
I tenderly salute every one of you, and bid you farewell.

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, 1837.

Finding myself in much need of _daily_ retirement,
and full prostration of soul before a merciful and all-sufficient Helper of the helpless,
and so often experiencing much composure of mind and temper,
from waiting upon Him in secret, I highly recommend the practice to my precious children.

The Quarterly Meeting was to me trying.
I had to speak a considerable time in testimony--others followed.
The meeting had then held pretty long,
but it seemed right for me to promote silence again, and then kneel;
when I was longer in that posture than ever I remember to have been without utterance.
At length I had to break forth, "`What wilt Thou do for thy Great Name?`"
as the language of some baptized spirits;
and to allude to those who had already perished "`between
the porch and the altar;`" crying,
"`Spare thy people, oh Lord;
and give not thine heritage to reproach;`" and to ask a blessing
on the travail of the true servants and handmaidens left,
as well as that those who were dead, might yet speak to the hearing ear.

The youth were livingly brought into remembrance,
and this Society (Friends) were alluded to as the _visibly_ gathered Church, etc.
In my offerings I seemed to have ability given from the Fulness of Strength,
but still I came home with a heavy heart, finding little to console me.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Sixth Month 24th, 1837.

[.salutation]
My Dear Friend,

I was so ill, both in London and since, as scarcely to be able to put pen to paper;
indeed it was under much weight of indisposition that I left home,
but my mind being drawn to the Yearly Meeting, the attempt was made.
On second day morning I attended the Select Meeting,
and communicated what was on my mind; after which I was not able to stop,
and did not get to the afternoon sitting.
Had an interview that day with our friend +++_______+++,
and managed to sit pretty nearly through the truly fearful meeting of third day,
where I was the first to express anything but unity with the concern laid before Friends.
Many followed me in the same strain.

I was not at the adjournment, but understand that more objected then.
However, the prospect was ultimately encouraged, and a very full certificate issued.
I may say that my place seemed to be _that which I stood in;_
in decidedly giving my judgment, as an individual,
that it would be best to lay the concern aside at present.
I fully concur in the belief of some valuable Friends,
that the disaffection in this country arose out of the unsound writings, etc.,
of the Friend in question.

I confess that nothing short of an acknowledgment of error,
and deep sorrow for the past (though done with good intentions)
appears sufficient to satisfy my tried mind,
with respect to one so influential,
and whose sentiments on things of great importance to us as a body,
are published to the nations.
What occasions me the most sorrow is, that in this day of sifting as from sieve to sieve,
we have, in a Society capacity, retarded the great work,
and owned much which the Great Lord of the heritage
has appointed should be winnowed away.
Oh! the consideration hereof weighs down my spirit;
and because there appears at present no remedy, my soul weeps in secret places,
and I go mourning all the day long; yet there is, at times, a humble but sure hope,
that there will be a discerning more clearly between thing and thing;
between the covering that is not of God`'s Spirit,
and that which He prepares and grants to those who are truly watchful,
and dependent upon Him alone.
I trust that, among our youth, some see with an evidence indubitable,
that nothing will avail but a new heart; which cannot be effected,
save by the inward operations of the hand of the holy Redeemer,
who sitteth "`as a refiner with fire, and as a fuller with soap.`"

I was particularly struck with thy allusion to my not being without knowing tribulation;
for at the time I received thy letter, I was pressed down with painful feelings,
which increased until what I had to suffer (particularly in the great
city) became fully equal to any capacity afforded to sustain it;
but my poor mind was mercifully favored to witness,
that such a helpless worm was under the notice of
Him who "`weigheth the mountains in scales,
and the hills in a balance;`" so that not an atom too much is permitted to come upon us.
I shall be glad of further information from thee of how thou fares,
and whether thy dear sister is still a sufferer or not.
I trust that if patience has already had her perfect work,
or still a little may remain to be effected,
as the service due to a Master richly rewarding, the immortal spirit triumphs over all,
through Him who conquered, and still is known to conquer, death, hell, and the grave.

[.signed-section-closing]
Believe me to be, very sincerely, thy affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Seventh Month 17th, 1837.

We do continue to love you,
and desire an increase for you in that which makes strong in the Lord,
and in the power of His might.
Few there are who seem, in this day of perplexity, of darkness, of cloudiness,
and of treading down, to be prepared to put on strength in the name of the Lord;
to take indeed the whole armour of God unto them; being girt about with truth,
having righteousness for a breast-plate, the helmet of salvation,
the sword of the Spirit, and above all, the shield of faith,
whereby the fiery darts of the wicked are quenched;
nor do many among us know what it is to have the
feet shod with the preparation of the Gospel of peace;
for how do a multiplicity of things, pertaining to the present life,
prevent a full dedication of all to the Most High,
that He may work both to will and to do, of His own good pleasure.
No doubt the disposition is felt with more than a few, which led one to enquire,
"`What shall I do, that I may inherit eternal life?`"
but when it is found that the purchase-money is their _all,_
then comes hesitation and sorrow.
But why do I write thus?
It was not premeditated; yet I often look round in my mind, and am ready to query,
Oh! where shall we go to find valiants in Israel?
or where may we _hope_ that, in a rising generation,
there are those so humbled under the Almighty hand,
as to promise a restoration of judges as at the first,
and counsellors as at the beginning?
But enough of this plaintive song.
I know that the seven thousand shown to the mournful prophet of old,
were _only_ seen in the light of truth;
and may we not hope that the same Power which preserved them,
has many hidden ones now reserved to Himself, that may yet shine forth as the light,
in the kingdom of their Father;
evidencing that they live under the government of His Holy Spirit.

I wish your visit to Ackworth may be productive of satisfaction,
and encourage a prospect of useful and truly baptized members of the Church of Christ,
from among the dear children.
Often do I desire that our little ones may be deeply impressed
with a sense of the necessity of having the heart tendered;
the living, eternal word, inwardly revealed as a hammer, to break the rock in pieces;
that so, in early life, the stony heart being removed, and a heart of flesh given,
they may manifest a susceptibility as to the best feelings,
and be so wrought upon as evidently to become what they are, by the grace of God.
This is superior to all that can possibly be done by human efforts,
in cultivating the rational powers,
and in storing the mind with outward knowledge and literature,
however good in its place all this may be.
My love is to dear +++_______+++ and wife.
I was comforted in their simplicity, and desire after best guidance, when last with them.
May they keep near to that which can alone build them up in safety,
and give an inheritance among all them that are sanctified!
It is the simple whom the Lord preserveth through all.

And now, my dear friend,
may I say that my husband and I do wish to sympathize with those among you,
who desire to pray for the prosperity of Zion, and the peace of Jerusalem;
which can only be promoted by judgment being laid to the line,
and righteousness to the plumb-line;
not by passing over that which meets not the line measured out by the truth.
What is your Monthly Meeting doing with delinquents;
with persons gone back to the beggarly elements, as if, having begun in the spirit,
we could hope to be made perfect in the flesh?
Are these faithfully labored with, in the love of the Gospel?
and if they refuse to lend an ear to wholesome counsel,
are their works testified against, to the clearing of truth?
Sometimes I am ready to conclude,
that if the retrograde steps of some are not reproved and condemned _officially,_
the hands of some who would have been made use of to this end,
will be weakened more and more; until their holding back,
from what is termed charity and the like, but what, in reality, is slavish fear,
causes them to be beguiled of their reward.

Oh! that, in the Quarterly Meeting of London and Middlesex, there may be found such as,
through deep humiliation, may be raised up in a righteous zeal, saying, "`Here am I;
send me;`" even in handling the discipline, that it may be put in practice,
in the blessed authority of the Gospel; and acted in,
under the influence of that wisdom which is "`first pure, then peaceable, gentle,
easy to be entreated, without partiality and without hypocrisy, full of mercy,
and full of good fruits;`" for in all this,
there is nothing that would admit of bartering one
of truth`'s testimonies for the ease of the flesh,
or sparing that life which is to die by the sword of the Lord.
No; Agag must yet be hewed in pieces,
and there must be no sparing the best of the sheep and the oxen,
on any fair pretence whatever.
May the great and mighty Jehovah arise, in His own time,
and by the means which He shall choose,
for the deliverance of His people from whatever brings into bondage,
and oppresses the precious seed!
Amen.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Tenth Month 16th, 1837.

Now I beg the favor of some information relative to thy health,
and how both thou and thy wife are getting on in your journey through a world of vicissitudes,
in which it is very evident we have no continuing city,
but are to seek one that is to come; which indeed hath foundations,
whose "`builder and maker is God.`"
Yea, we are to prepare for an inheritance therein, as the first concern of life.
Then will He who gave Himself for us,
be graciously pleased to "`present us faultless before
the throne of His glory with exceeding joy.`"
Here is the recompense for all our suffering, in resignation to the will of the Father.
Surely the weight of glory that shall be revealed to the ransomed ones,
far exceeds _that_ of sorrow and pain endured in this probationary state.
The last public meeting was a few miles from Colchester,
for the cottagers scattered through that part of the country.
Never did I go to a meeting under more suffering,
my mind having been for days bowed down, as if the woes of the wicked were upon me;
and perhaps never did the word of the Lord, through so mere a nothing,
flow more freely to the people, nor reach to their states more fully,
so far as I have experienced.
The meeting was very large.
They came several miles in some instances.
Many were outside the barn, very quiet;
and I really think it might be thankfully acknowledged that the
power of the Lord was over all--to Him alone be the praise,
for indeed His own works do praise Him!
My dear husband and I attended the Quarterly Meeting at Bury,
which was a time of painful exercise, although I found the anointing _with_ me,
in the vocal labour that fell to my lot.
Few seem to me to remain amongst us,
who persevere in the path cast up for the self-denying followers of Immanuel crucified.
Few indeed, in this good old way, in which our forefathers were as a shining light;
and yet I hope we still have hidden ones secretly embracing, yea,
_purchasing_ the ever blessed, immutable truth, on its own terms:
not wishing to enter into, or repair to argument,
to convince them of that which is self-evident, but simply submitting to Divine grace,
that what they are, they may be by it.
I humbly trust that the Great Head of the Church
will bring such a state more and more into view,
to His own glory, and the edifying of the body in love;
even that love which is in Christ Jesus; which "`neither death, nor life, nor angels,
nor principalities, nor powers, nor things present, nor things to come, nor height,
nor depth, nor any other creature,`" shall be able to separate those from,
who trust in the Lord with all the heart, and lean not to their own understanding.

I feel a jealousy lest truth should still suffer,
for want of clear discernment in the leaders of our people; and indeed,
for want of that fervent charity,
that would by no means compromise the principles held so dear by the first Christians,
and by our early Friends, after a long and dark night of apostacy.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Earl`'s Colne, 1837.

We have enjoyed each other`'s company, and taken Isaac Penington as a third.
Oh! _that_ dear man!
Little did _he_ dwell upon his bodily ailments, which were often grievous;
but his mind was over them in the Lord;
so that it might be said he lived above the sufferings of a delicate frame,
subjected to hardships and privation which looked likely to terminate his earthly existence.
I hope to be instructed.
Nothing can exceed the kind attention of my dear friends of this house.
May they be rewarded; as I believe what is done is truly in the name of discipleship!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Twelfth Month 23rd, 1837.

In _bonds_ have _I_ been most truly, and _thou_ hast been _bound_ with me, and _I with thee._
Neither of us are disposed to want sympathy towards such as are in adversity,
not forgetting that ourselves are also in the body.
Old and almost worn out as I feel, my spirit does yet travail with and for thee;
I trust in that which outlives all pain and sorrow.
I may now adopt the language of the Psalmist, and say, "`The Lord hath chastened me sore,
but He hath not given me over unto death.`"
I trust _now_ the dispensation is changing.
I had quite resigned my child for a better inheritance
than the present state of being affords.
I could not desire to hold her,
if Inscrutable Wisdom saw meet that she should make
her escape from all temptation and suffering:
true, my heart was bleeding, but I said amen to the Divine will.
I tried to be still in my spirit, and not to reason on my singular affliction;
so I hope the everlasting arms have been underneath, invisible to me.

Above all have I sighed and mourned for the state of things among us, as a Society.
I do believe there never was such general falling away; such erring in vision too,
and such stumbling in judgment: scarcely any true discernment seems left us.
The acts of the Society, in some instances,
have been utterly inconsistent with our principles; so that it may be confessed that,
in our sanctioning what is irreconcileable with the truth, even in a Society capacity,
we have given away our strength like Sampson,
and we have surely "`changed our glory for that which doth not profit us.`"
Some tell me to recollect "`the cause is the Lord`'s.`" This I do not forget;
but some of us are commanded to sigh in measure, like the prophet,
who was to sigh deeply; yea, to the "`breaking of his loins.`"
Others see nothing to sigh for.

I had a letter this morning from a friend,
chiefly to enquire what was my view of the text in Peter,
"`We have also a more sure word of prophecy,`" etc.
He mentions receiving a tract on "`Misinterpretation of Scripture.`"
I should just wish him to know that I have seen it, and entirely differ, in my views,
from the author.
It is like the "`Beacon.`"
I often feel as if this tenement was giving way; but still think, with thee,
my "`strength may be renewed`" a _little,_ both naturally and spiritually.

Do thou be valiant, and fight the Lord`'s battles, in His own spirit and eternal power;
all flesh being silent before Him.
So dearly farewell.

[.letter-heading]
To her Son.

[.signed-section-context-open]
First Month 2nd, 1838.

Well, my dear +++_______+++, I wish, with thee, that our _late,_ and indeed _present_ trials,
may have a tendency to strengthen our best resolutions,
as they have exercised our faith and patience in no slight degree:
but what a mercy it is to be kept from casting away the shield,
or arraigning Divine Wisdom, even when without a living,
sustaining sense of our painful feelings being noticed by our Heavenly Father;
of whom it is said that His compassions fail not,
therefore the sons of Jacob are not consumed--the generation of the wrestling seed.
Jacob wrestled for the blessing of the Most High, through the night of darkness,
even until break of day; and to him the language of mercy and justice eventually was,
"`As a prince hast thou power with God and with men, and hast prevailed.`"
How encouraging to perseverance!

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
First Month 10th, 1838.

I am glad thou canst hope for a continuance of that providence
which has hitherto been over thee in a remarkable manner;
so that though tried and tossed mostly for years together,
the everlasting arms have been underneath, invisibly sustaining and carrying through,
to the fit time for deliverance.
Do thou be indeed watchful, as thy letter so sweetly expresses is thy desire to be,
"`over every word and thought, as well as deed.`"
Nothing else will do for us, poor, erring creatures;
and this watching is the unceasing prayer, graciously regarded,
and answered by preservation.
So be encouraged in thy holy resolutions, and the Lord bless thee,
to His own praise and thy lasting peace.
No doubt He will order thy steps aright, in thy looking to Him.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, First Month 14th, 1838.

Oh! that the young people would pursue ardently the things that are most excellent,
and as worthy of them, while their energies are in full vigour;
for shall we offer on the altar of God only that which is as the refuse?
Oh! may it be forbidden!
As regards my own state,
it is much my desire that all which may be still left me of fading and diminishing strength,
may be first devoted to the Guide of my youth,
and Him who hath been pleased to permit me to experience "`great and sore
trouble,`" but mercifully kept me from making shipwreck of faith.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Second Month 7th, 1838.

Truly thou art still disposed to act a sisterly part toward thy poor friend.
Most of those with whom I have been intimate in my day have left me:
thou art not one of these.
May it yet be proved that our friendship is on the basis
which the vicissitudes of this life do not shake,
much less destroy.

I have long felt deeply interested in the best welfare of thyself and family,
as I trust thou art well aware.
Much do I desire that the things which are of this world,
may not be suffered to choke the word in the inward parts,
and render unfruitful toward God in any instance among you.
How soon will all be over with us here! and then we must
give account of what we have done with the gifts bestowed;
and whether we have, above all, sought to glorify God with body and spirit;
remembering they are __His__--not _ours._

It is no small consolation to me to be assured that
there are indeed a few amongst us as a people,
who are precious in the sight of the Great Head of the Church;
spared in the day that He makes up His jewels,
even as a man spareth his son that serveth him; for "`they shall be _mine,_
saith the Lord.`"
Of this number I trust dear +++_______+++ is one; and that there are others,
in Scotland as well as here in England, and elsewhere likewise.
Notwithstanding the shaking of the earth, and of the heavens also,
that we have felt and do feel, the righteous,
who keep their ranks under the banner of the Lamb,
will "`shine forth as the light in the kingdom of their Father.`"

[.letter-heading]
To J. H.

[.signed-section-context-open]
Sudbury, Second Month 8th, 1838.

[.salutation]
Beloved Friend,

Thy unlooked for testimonial of continued remembrance and love, received yesterday,
claims an early acknowledgment.
I assure thee it is no small comfort to me to know that I share thy sympathy,
also that of my dear friend, thy husband.
Many times does my mind recur to years that are over and gone,
when you kindly noticed the poor little messenger, who was running to and fro,
in obedience to what appeared to be the will of my Heavenly Father.
I have never ceased to love you since, nor to feel my heart, at times,
glow with gratitude, for the true kindness, help,
and hospitality met with at dear Uxbridge.
Some who befriended me,
are gone to receive a recompense of reward for their labour of love in many ways;
and some who remain, are filling up their measure, and coming through great tribulation,
in, or for, the full preparation to be forever clothed in the white raiment;
their garments being washed indeed, in the blood of the Lamb.

It is with much satisfaction that I find thee bearing testimony
to the all-supporting hand of the Most High,
both as relates immediately to thyself, and those nearest to thee,
in this world of trouble: and most truly glad am I,
that none of thy immediate family have departed from the first principles of Friends.
Nothing better will be discovered,
wherein to partake of that rest which is prepared for the people of God;
and those who have gone from these principles, into notions and speculations, must,
I am persuaded, feel at seasons, the want of an acquaintance with the leadings of Christ,
the great and good Shepherd, who maketh His flock to lie down in green pastures,
and leadeth them beside the still waters.
Nothing, nothing will give true peace, but taking upon us the yoke of Him who,
in that prepared body, learned obedience by the things which He suffered; who says,
"`Learn of me; for I am meek and lowly in heart;`" with the gracious promise,
"`and ye shall find rest unto your souls.`"
Thy account of dear +++_______+++ (although affecting with
regard to her sufferings) is sweet to me,
as she seems to increase in that which outlives all pain and sorrow.
How kind of dear R. F. to mention me, as feeling interested about my health!
Ah! she is a precious plant in the Lord`'s heritage, fruitful to His praise!
Thou remarks, "`What a small remnant we are likely to be, as a Society!`"
Yes, small indeed; but I trust that the scripture may yet be verified,
in the little few who keep to the ancient and abiding foundation,
"`The remnant of Jacob shall be in the midst of many people, as a dew from the Lord.`"
I think, with thee, that amidst all our defection,
the principle of truth is spreading in the world; yea, it will gain ground more and more,
although the various sects of Christians are too _showy_ in religion (if I may
say so)--not enough concerned to feel after and embrace the substance,
while high in profession.

We have a third class in our Society,
who appear to me to stand at present in the way of
our arising in ancient simplicity and brightness,
more than those who have separated themselves,
and even opposed the old school with much violence;
and that is the class who would compromise, and if possible, mix up light with darkness,
that there may be no breach of what they miscall charity, love, and unity.
Oh! this daubing with untempered mortar!
It must all be judged down, sooner or later, by the wisdom and power that is from above;
to make way for the immutable and blessed truth, as it really is in Jesus!

May the Lord be magnified in all His works, for He pulls down to build up,
and He wounds to heal.

I have not written so long a letter these many months; the employ does not suit me well.
I will now take leave, in the feeling that I am thy sincerely affectionate,

[.signed-section-closing]
Though deeply tried friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To Mary Capper.

[.signed-section-context-open]
Clapham, Fifth Month, 1838.

[.salutation]
Dearly Beloved Friend,

Thy sweet and precious letter has done me good.
Oh! how delightful it is to see that some hold on their way,
in this day of grievous wandering and backsliding!
This Yearly Meeting convinces us that we are still too generally a revolting people;
and my portion of labour has been much in the line of laying open our condition,
and calling back the wanderers, and the rebellious;
for it seems to me to be a day of renewed visitation.
The heavenly wing is extended to gather into safety,
while yet many are not prepared to come under it,
for want of being sensible of their danger, and their own helplessness.
There is, nevertheless, a little band of humble, simple ones,
who feel their entire dependence upon the Almighty Helper;
and these are very near and dear one unto another, whether gathered in one place,
or wherever they are, and however circumstanced.
Among such is thyself, kept, through Divine mercy, in the holy oneness;
maintaining the unity of the Spirit in the bond of peace: and although some of thy steps,
now late in the race, may be very heavy and painful,
I do believe thou wilt find the end to be crowned with peace and full satisfaction,
in Him who giveth not the race to the swift, nor the battle to the strong,
but sealeth the salvation of the persevering, and rewards them with His glory forever.
So mayest thou be enabled to thank Him and take courage;
for "`say ye to the righteous that it shall be well with him.`"

My children feel the tender regard expressed for them in thy communications to me.
We seek not great things for them, any more than for ourselves,
either as to temporals or spirituals, but true Wisdom, whose ways are pleasantness,
and her paths peace.
Many are the baptisms, even in youth, known to such as yield to the preparing power,
which brings to a holy settlement on the sure foundation.

It is very sweet and confirming to some of us, as to our faith,
to see Daniel Wheeler returned safe and sound in every sense; and to hear him tell,
in a few sentences, of what he has seen of the works of the Lord,
and His wonders in the deeps; and to testify to the sufficiency of Divine grace,
as he has witnessed it in himself and others.
He says that if he had entertained any doubts before (which was not the case)
concerning a measure and manifestation of the Spirit being granted to all men,
they would have been removed by what he has seen among those whose
situation in the world left them in ignorance as to the outward,
yet acknowledged to the reproofs of the great and good Spirit in their own hearts.

I may now take leave of thee, my very dear friend; and remain, I humbly trust,
in the fellowship of the Gospel, and also as a partaker with thee in tribulation,

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
London, Fifth Month, 1838.

There was company not of our Society at dinner yesterday--five persons.
I was constrained to address them and all the rest present.
This sacrifice brought much peace to my mind.
I was led to declare how the people called Quakers had gone back again into the world,
etc., etc.
I have not yet found my way to utter a word in this great assembly.
My state, as relates to the ministry committed to me, has put me in mind,
for these two days, of Joshua, when he was to compass the walls of Jericho,
but to do no more until he received fresh command as to time, etc.;
then the walls fell down of themselves, as the will of the Lord was abode in,
and the fulness of time waited for: so I trust patience will be granted me,
and a strict adherence to Divine direction, in my little way of serving Him.

I have now, since writing the above, been to meeting at Devonshire House,
where my mouth has been opened in a rather short testimony,
and to some relief to my exercised spirit.
I found it needful to be _very_ careful to mind the right time,
both in leaving my seat and in taking it again.

There is now a strong endeavor to bring us to unite both in word and in thought.
We have need to be "`wise as serpents,`" as well as "`harmless as doves.`"
There never was a time among us, when things were just in the same state;
when nothing but standing single-handed seems at all safe.
We dare not look for that assistance one from another, that used to be strengthening;
and yet no doubt those are still left,
who "`maintain the unity of the Spirit in the bond of peace.`"

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Near London, Fifth Month 23rd, 1838.

Yesterday afternoon it seemed required of me to express humble thankfulness that,
after all,
the Almighty is willing to "`cover us with His feathers,`"
if we are but disposed to come under the extended wing;
but that He will have nothing thus protected, that feels not its own helplessness;
nothing that has self-sufficiency,
or sees not the danger of being away from the Heavenly Parent,
even for a moment--repeating the text, "`How often would I have gathered thee,`" etc.
Then I had to declare that He who is a "`jealous God,
and will not give His glory to another,`" would yet send forth His word to sift us,
and take away, and blow away the remaining chaff,
by "`speaking terrible things in righteousness;`" for "`What is the chaff to the wheat,
saith the Lord?`"
Oh! the mixture, the mixture that is amongst us!
It is seen in our sitting together, it is painfully to be _felt;_
but how precious is the sense,
that a living remnant is preserved on "`the foundation _already laid,_
another than which cannot be laid.`"
How near and dear are these one unto another, in the everlasting love and life of truth!

Before I left the meeting,
I feared to withhold a warning and call to examine our motives in attending these meetings,
which we were privileged to have the opportunity of doing;
putting us in the remembrance of the possibility of partaking with the disciples outwardly;
even dipping with them, in the presence of their Lord, in the same dish,
and then going out for the purpose of betraying the innocent life, in the darkness,
and with a kiss; and how He who is truth declared, "`It had been good for that man,
if he had not been born.`"

This morning Daniel Wheeler`'s certificate from the Morning Meeting was read,
and the Minute of same Meeting on his lately returning it;
also testimonials from missionaries, etc., of his labors being most truly acceptable.
Daniel Wheeler then gave in a concise account of the merciful
dealings of the Most High with him in his travels,
and how he had been helped along through great difficulties;
while he often had to say to corruption, Thou art my father; and to the worm,
Thou art my brother and sister.
There was a Minute made of the account rendered in by himself,
and of Friends`' thankful feeling respecting him.
It was all very beautiful.
That which dropped from his own lips was heart-tendering, and abundantly satisfying.
Oh! the dear servant of the Lord!
He is as humble as a child; while capable of ascribing glory, and power,
and dominion to the Lord God, and the Lamb that sitteth upon the throne.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stamford Hill, Fifth Month 27th, 1838.

Feeling inclined to attend Newington Meeting today, I am here.
The meeting was very large: divers spoke.
It was a very exercising season, but I felt relieved in some measure.
Daniel Wheeler came to me afterwards, and asked where I was going to dine; for, said he,
"`thy people are my people.`"
We were led harmoniously to labour.

28th.--This morning, in meeting,
my way opened to encourage Friends who had the weight of things,
to be like those who bore the ark of the testimony on their shoulders,
in the bottom of Jordan, until the people all passed over,
that we might be able to bring up the stones of memorial;
in the Lord`'s time raising our Ebenezer, etc.
And before the meeting closed,
I laid before it my concern to see Friends together (if practicable) both men and women;
also those who have lately gone off.
I know not how it may be: there is no house belonging to the Society large enough.
The Men`'s Meeting is to be acquainted with it this afternoon.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
London, Fifth Month 29th, 1838.

Yesterday I was obliged hastily to close my letter.
There was a deputation from the Men`'s Meeting,
to tell me my concern was most cordially united with,
and that the Yearly Meeting was disposed to do anything that might meet my views.
I have had but one poor night, with all my fearful exercises in this momentous prospect;
for such indeed it is to me.
I have often thought what a mercy it is to be thus cared for;
also that my sufferings in the winter were truly permitted in great wisdom,
not merely for my own sake, but for the sake of the great and good cause.
Indeed I believe that if we are entirely the Lord`'s, to be, to do,
and to suffer what He pleases,
we shall all find that we have to experience something of what the Apostle spake of,
when he said, "`I fill up that which is behind of the afflictions of Christ,
for His body`'s sake, which is the Church.`"

We used to speak of these things together.
Mayest thou be qualified to promote the spreading of that kingdom which "`is righteousness,
and peace, and joy in the Holy Ghost.`"
Let patience have her perfect work,
and all things will have a tendency to fit thee for the Great Master`'s use.
His service, although very mortifying to the flesh, is nevertheless truly honorable,
and truly peaceful.
Thou hast had much to pass through,
and mayest still be plunged again and again into the deeps;
and yet has not the Most High evinced His care over thee,
as a tender father careth for a precious child; that,
being rightly disciplined and instructed,
ability may be given to "`bring forth things new and old, out of the heavenly treasury?`"
There is no chance of the women`'s house holding the numbers likely to come,
for even today it was crowded to excess;
but I desire to leave all to the control and guidance of Infinite Wisdom.
I well know that all my own thoughtfulness is unavailing.
Without Divine aid we can do nothing for His honor,
who remains to be all-sufficient to those who humbly trust in Him.

[.letter-heading]
To a Niece.

[.signed-section-context-open]
Sudbury, Sixth Month 20th, 1838.

Although I cannot doubt thy being assured of my tender sympathy with thee,
as a mother watching the sick bed of a beloved child,
yet do I wish to tell thee that my mind is indeed very much with you;
and it is my heart`'s desire that this very trying
dispensation may be blessed to each of the family.
Our Heavenly Father sends afflictions in His love to us;
designing to give the sense to our souls, that we are truly adopted by Him; and we read,
that "`as a father pitieth his children, so the Lord pitieth them that fear Him.
For He knoweth our frame;
He remembereth that we are dust:`" so then He will not lay more upon us,
than He giveth us ability to support.
I know thou and I both keenly feel illness visiting our families;
but oh! when it brings to the extremity of suffering,
in seeing one who made a part of our flesh and our bones, obliged to yield to the cold,
relentless hand of death, this is indeed hard to bear;
and only mitigated by resignation being granted,
and by the consoling belief that _that_ which is torn from us,
is dearer to the Lord than it was even possible for us to witness,
as regards our affectionate attachment.
This, I trust, is thy consolation,
and that of other near relatives of dear +++_______+++. Is he yet struggling with mortality?
or has he dropped these shackles, and taken wing; soaring above every painful feeling,
and resting forever in the arms of his adorable Redeemer?
Do let me know how it is with you.
I remain thy affectionate, and feelingly interested aunt,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, probably Sixth Month, 1838.

There appears to be far less disposition to oppose
the right thing than for many years past.
A restraining influence has been felt,
as regards the vaunting spirit that showed itself so much latterly;
and I do think that I never knew more precious fellowship
than was felt by the real Friends,
one with another.
These are endeared to each other, in a still greater degree, by what they have suffered,
and continue to suffer for the truth`'s sake; for there remains much to deplore,
that has a tendency to scatter the flock,
and to beguile such as look outward for instruction and satisfaction,
instead of having the eye to the heavenly anointing that is truth, and no lie.
Great has been the exercise of my mind, and the weight brought upon me; but I have,
through Divine mercy, been enabled to lay down my burden in two great meetings,
one for the men, and the other for the women;
together with those who have recently gone off from us.
Oh! it was an awful engagement.
I had to lay things open, as shown me, or as the gift led to it;
and to hold out an invitation to come to the pure, inexhaustible fountain,
away from all that is as muddy waters;
declaring that the Great Head of the Church would render
unavailing every effort to model us anew as a community,
and renew us in the original character of our Society.
I was strengthened to speak for four hours, with but little intermission.
Thus are we still followed; the word not going forth, "`Let Ephraim alone;
he hath joined himself to idols.`"
I do humbly hope that better times will come to this people,
to whom the Most High hath declared, "`You have I loved, and you will I punish.`"

Thou seest I am raised up again in the service of my Great Master,
to whom I desire to devote my failing energies,
as I humbly trust the prime of my poor day has been His.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Seventh Month 23rd, 1838.

The parcel from my beloved friend came to hand on seventh day evening,
in which was enclosed thy note,
acquainting me with the dubious state of your dear son`'s health.
My heart is alive to sympathy; and how should it be otherwise than peculiarly so,
as regards you--friends long known, and as long rendered dear to me;
I trust not from selfish motives, but from an interest which, on early acquaintance,
was produced in my heart, as to your real felicity.
Kind indeed have you been to me--particularly thyself;
entering into my feelings of solicitude, excited from time to time,
by adverse circumstances, especially such as related to illness.
How then can I but feel keenly the present anxiety,
occasioned by the somewhat precarious state of a child claiming constant,
tender attention?
Yes, I do indeed enter into the hopes and fears which must assail the minds of the dear parents;
yet am I made thankful that the dear object of your
care is endued with patience under suffering.
Oh! surely Divine Wisdom does indeed dispense that which is best for us,
while we know not what is in store to be revealed;
only believing through His mercy all will be well
with those who love the Lord Jesus Christ in sincerity.
Often, very often do I remember your dear invalid,
when prostrating myself and my all before Him who chastens every son whom He loveth,
and even scourged all whom He receiveth.
No doubt there is much to correct, much to be taken away, like being purged from dross,
that the ear may be open to the discipline of the cross of Christ.

May patience yet have her _perfect work,_ that the whole will of God may be wrought out,
to His glory who worketh all in all,
and to the peace of the soul panting after true rest.
