== Chapter 20. Letters from 1838--1839

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Eighth Month 9th, 1838.

Will my beloved friend excuse my anxiety to know how you are getting on?
I want to enter into sympathy with +++_______+++, not only as the son of friends dear to me,
but also as one for whom my spirit has often been introduced into exercise and travail,
that he might so come under the Divine hand,
as to be formed for the praise and glory of his Redeemer;
and possessing that peace which even the sufferings of the
poor frame cannot deprive the Lord`'s dear children of.
"`Thou wilt keep him in perfect peace whose mind is stayed on Thee,
because he trusteth in Thee.`"

What an uncertain world is this!
Is not Dr. S.`'s removal truly awful?
Is it the case that our dear friend +++_______+++,
has avowed a concern to visit Van Dieman`'s Land?
I should be glad to hear more than the mere rumor.
These are days of extraordinary occurrences, and times when, from various causes,
the nations of the earth seem, as it were, to be drawing nearer to each other;
may we not hope, preparatory to there being "`one Shepherd and one sheepfold.`"
Oh! that our children may yet be instrumental to this great end
and blessed design of the ever faithful and all-beneficent Creator;
not that I desire gifts for them otherwise than is altogether meet in the Divine counsel.
I well know that we may, and have no doubt many do, serve the Lord in obscurity,
by submitting to His will, and in all things having reference to Him.
Job Scott says, "`Many serve the Lord in sickness,
and death is a service we _all_ owe to God.`"
What remains for us is, that we seek "`to have that mind in us,
which was also in Christ Jesus.`"
The dear Son of God, while in unutterable anguish,
submitted to the purpose of the Father; saying, "`Not as I will, but as Thou wilt.`"
Resignation is a gift to be waited for,
and is never withheld eventually from the soul that perseveringly seeks it;
and oh! when obtained, how does it prove like a harbour of safe anchorage,
after being tossed with tempest, and bereaved of comfort;
and how is the land that was far off, now seen with an eye of faith!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden Mill, Ninth Month 13th, 1838.

Day after day have I been engaged to seek the Lord on behalf of your son;
and while desiring sincerely that nothing may be
spared that ought to be given to the hammer,
the sword, or the fire, my prayer has been,
that so far as consistent with His will who doth right,
the sufferings of the dear invalid might be mitigated.
Oh!
I have not forgotten that we have to do with a Judge who "`will not contend forever,
neither will He be always wroth; for the spirit would fail before Him.`"
He remembereth mercy in the midst of judgment, to such as fear Him;
may nothing prevent His great and gracious designs
from being answered in this sore trial.
I look further than to the immediate object of affliction;
I look round upon the dear and interesting family of which he is one.
I want that the painful dispensation should prove a blessing to all;
that the things of time may not have more than their due place in the mind;
that the things of eternity should be primarily pursued;
that no pleadings of the flesh should prevail,
to the retarding of the great work of redemption,
but that from living experience the song may be sung, "`which no man can learn,
but those who are redeemed from the earth.`"
Oh! for deepening in the root with thee, my dear friend,
and with thy loved partner in life;
that your fruit may more and more be unto holiness (unlike
the still unholy world) and the end eternal life.
All helpless as I am,
it is my concern to wait on the Fulness of strength on my own account, and to be enabled,
in the Divine will, to comfort them who are in trouble,
with the same comfort wherewith my Heavenly Father hath comforted myself.
And it is my desire to remember such as are in adversity, being in the body likewise,
and therefore continually subject to adversity.

May your dear children, every one,
be taught to look at our dependent state as finite beings.
We have nothing that we have not _received._
The air we breathe is not our own, any more than the portion of health vouchsafed.
How humble we ought to be; how meek and low of heart;
and it is such who are truly exalted.
Oh! for your family being dignified with the gifts and graces of the Holy Spirit;
that every natural endowment being sanctified,
they may be found of the number on whose characters "`Holiness to the Lord`" is inscribed,
by the Divine finger.

I often think of my last pleasant visit to you;
and how interesting to me was the parting with some in particular.
"`Things most excellent`" were, I believe, thought of reciprocally;
even things whereby one may edify another.
May these things be more and more in the ascendancy with each of us!

[.letter-heading]
To a Niece.

[.signed-section-context-open]
Lexden, Ninth Month 16th, 1838.

It is with much concern I find thou art still disposed to dwell
on the late trying scene of dear +++_______+++`'s sufferings and removal,
with gloomy reflections;
and I now take the pen to say that I do believe the dear child is in as
much enjoyment as his innocent and purified spirit has capacity for;
therefore do leave it as much as possible,
believing in the mercy of Him who saw meet to bereave you of one He lent you for a season,
and has fitted for an early exit from this world of temptation and sorrow.
Dear youth! if, in the struggles of nature, he was as though pursued and worried,
we may well attribute the distress to a weight of disease pressing on the animal system,
and by no means extending itself beyond the poor, afflicted frame.
Surely he loved the Lord, and even longed to be with Him forever: then he saw,
beyond all his conflicts, into that kingdom, none of whose inhabitants can say,
"`I am sick;`" and where there is no sorrow, but all "`tears are wiped from the eyes.`"
Do, my dear, wait upon the Source of all consolation;
and may He enable thee with true christian confidence to adopt the language,
"`Why art thou cast down, oh my soul?
and why art thou disquieted within me?
Hope thou in God; for I shall yet praise Him, who is the health of my countenance,
and my God.`"
Truly my heart feels deeply for thee.
Let me entreat thee not to ruminate on the painful _past._
Thy tenderness has been almost too great,
and couldst thou have known how to prevent anything likely to be injurious,
thou wouldst most gladly have done it; so now leave the subject,
and turn thy attention to present duties every way;
and may the trying dispensation be blessed to each of your circle!
The Great Superintendent of the universe does not design our ruin,
in permitting trouble to assail us, but that,
being "`chastened and not killed,`" we should be the more prepared to cleave to Him,
as our Heavenly Father, and cry to Him,
in the language of "`Abba;`" being His adopted ones, and dearly beloved of Him.

[.signed-section-closing]
Thy truly affectionate aunt,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To her Son and Daughter J. and E. G., Shortly After Their Marriage.

[.signed-section-context-open]
Sudbury, Tenth Month 27th, 1838.

[.salutation]
My Dear J. and E.,

Having been but poorly since my return home,
and the complaint affecting the nerves a good deal,
I felt almost incapable of addressing you before.
This day I am favored with less of that disqualifying indisposition,
and gladly take the pen to assure you that my mind has been
much turned towards my dear children at Lexden;
earnestly desiring the best of all blessings may be afforded,
now that I consider you as entering together into the concerns of life;
requiring the daily, hourly guidance of an all wise Director.
Oh! it is like a vessel untried, launching forth on the mighty ocean;
unable of itself to steer aright, or combat the difficulties it meets;
but as the great and good Master is on board, some confidence may be humbly entertained;
for even when He seemed not to heed the conflict that His disciples experienced,
when in danger, He was their safety and their deliverer, in their calling upon Him.

May you, my dear children, never consider yourselves capable of steering your own course,
but look to Him whose ways and thoughts are infinitely higher than those of finite creatures,
even as the heavens are higher than the earth.
Yet is this the day of your might;
this is the time to seek the Lord that He may be found of you,
so as to put into a capacity to serve Him with a _perfect_ heart and with a willing mind,
in your day; to give unto Him the glory due unto His Name.
It is not with our failing energies that we are to expect
so to walk worthy the vocation wherewith we are called,
as to be prepared for that happy testimony as applied to us,
uttered by the great and just Judge, "`Let her alone; she hath done what she could.`"

The way to ensure Divine approbation is to live each
day in conformity to the holy mind of our Creator,
as we may be favored with His leadings,
by a simple reliance on the grace mercifully vouchsafed;
making every sacrifice called for at our hands; not despising the day of small things.
I am almost sure dear E. will (in minding the day of her
visitation) see the necessity of self-renunciation;
which begins with a little,
but which is not complete until we come to adopt the language, "`as having nothing,
and yet possessing all things.`"

And dear J., has not the Lord permitted your union,
that individually and unitedly you may acquiesce with His will,
and assist each other to ascend the holy mountain,
where He is not only as refreshing dew, but where He teacheth His ways,
and strengthens the resolutions to walk in His paths--the
ways of pleasantness and the paths of peace.

I do not know if you were told of our being mercifully permitted
to draw very near to the throne of grace in your dwelling,
immediately preceding our leaving that dear spot!
Oh! it _was_ precious!
You seemed to be placed before the Father of mercies
as children for whom His blessed Spirit yearned,
that you might be His in time, and forever.
We were made truly thankful for being brought as it were into a cloudless atmosphere,
in petitioning for you and for ourselves, under a sense that we are poor,
helpless beings; that without Christ we can do nothing; but that nevertheless,
through His strength, made perfect in weakness,
we are able to do all things according to His will.

All our dear love is to you.
Do, my dear children, watch over your own hearts and one another for good.
And the God of Jacob defend and bless you, and the Almighty Helper of Joseph be with you.
Amen, saith your affectionate mother,

[.signed-section-signature]
S+++.+++ G.

_Without date._--It seems to me that our Heavenly Father
has a gracious regard towards you both:
the feeling was precious to me under your roof.
Trials we must all have in this probationary state,
and they are designed to work together for our good.
Oh! how sweet it is when the Most High smells a good
savor in the dwellings of His dear little ones,
as I hoped yesterday was the case.
Farewell, my dear children.

[.signed-section-closing]
Your ever sympathizing and affectionate mother,

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Eleventh Month 20th, 1838.

Many times, both by day and by night,
my poor heart is raised in aspirations to the Most High,
on behalf of some of you in particular, and for the family together,
that the Divine visitations may be known;
and oh! that they may be humbly received and abode under;
proving like the refiner`'s fire, and like fuller`'s soap.

The Great Hand would thoroughly effect the work designed; watching its progress Himself,
and not permitting anything to harm the soul thus preparing for perfect union with Him:
delivering, in due time, from the most painful feelings,
and granting an entire fitness for His own use.
How gladly would I see or know,
that every member of thy family were as the purified and precious metal,
bearing the inscription of "`Holiness to the Lord,`" in characters so legible
that they might be read even by all who may be conversant with you;
or how I should rejoice in witnessing the blessed work of
the "`Fuller with soap,`" making whiter than snow,
even where, in passing along through life,
and coming in contact with the spirit of this world,
there may have been a partaking of its nature;
for as it is hard to touch pitch and not be defiled,
so it is hard to mingle with that which is opposed to the true spirit of Christ,
and not be corrupted.
It is high time for some of us to see that, through adorable mercy,
we have on the wedding garment, the fine linen, clean and white,
which will bear the scrutinizing eye of Divine justice.

And may the dear young ones be aware how it behooves them,
as they value their truest interests,
to yield to that living power and influence which regenerates the soul,
and leads into a separation from conformity to this world, in its vain, yea,
its evil customs, its friendships, and its foolish fashions; all which,
while they alienate from the love of God, are themselves passing away,
and will leave their votaries nothing but vexation of spirit.
It is those who receive the Redeemer in the way of His coming,
to whom _power_ is given to become the children of the Highest;
born again of that which is incorruptible; for they can overcome every obstacle,
in believing implicitly in the appearance of Him
who bade His disciples to be of good cheer,
for, said He,
"`_I_ have overcome the world.`" May we be kindred
spirits in that world where there is no groaning,
being in bondage!
May we be prepared to rejoice in dropping these mortal shackles,
and being forever at liberty to praise and glorify the Lord God, and the Lamb,
who has washed us in His own blood!
The like desire lives in my heart for all thine.
I want such as your sons and daughters to range themselves
nobly on the right side of things in their day,
through the preparing hand, which qualified many in the early period of our Society,
to show their fervent love to the cause of truth; in which cause they became,
in some instances, "`lion-like men.`"
For although there are, I trust, in all religious professions,
those who are promoters of the coming of the Redeemer`'s kingdom on the earth,
living up to the light afforded,
yet does it seem to me that this people are peculiarly called
to exalt the testimonies of the unchangeable Gospel,
even in its meridian effulgence.
Let not our children conclude,
that if there ever was utility in our plain and peculiar manner of life,
and unceremonial worship, _that_ has long since ceased;
for surely the Lord will have a simple-hearted people still,
and a people who hold christianity in its native purity: yea,
our offspring are designed to come forward, and practically adopt the language,
"`I am the Lord`'s;`" glorifying Him with their bodies and with their spirits;
for He is worthy of their energies, while in their full vigour,
to be sanctified for His own blessed purposes,
and that all His gifts should redound to His honor.
Do give my sincere love to all, and say that I am persuaded there is no real peace,
or lasting and solid satisfaction,
out of dedication to Him to whom we owe our life and breath.
So farewell.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Twelfth Month 30th 1838.

It is with much concern we find that dear +++_______+++ is so unwell.
How abundantly inscrutable are the ways of Divine Providence!
and yet no doubt they are all "`just and true.`"
Thou seemest to acknowledge this in thy affecting lines received last night.
Amidst all my painful feelings, it is no small comfort to me that you love the Lord,
and can believe for yourselves, that He deals with you in wisdom, which being infinite,
that which is finite cannot comprehend it.
Thou, my precious +++_______+++,
hast been again and again taught to leave all in that Hand which
hides the children of the Heavenly Father in the day of trouble.
When Zion mournfully spake, "`The Lord hath forsaken me,
and my Lord hath forgotten me,`" this was set forth as being utterly out of the case;
even more impossible than that a woman should forget her sucking child;
for He who is love itself declares, "`Behold,
I have graven thee upon the palms of my hands; thy walls are continually before me.`"
As for thee, thou hast been marked out, as it were, for disappointment and trial;
being again and again thwarted in thy earthly pursuits;
yet do I believe that all thy tribulations are to
prepare the way for thee to hear the language,
"`I have refined thee, but not with silver.
I have _chosen_ thee in the _furnace_ of affliction.`"
Here is where the most precious metal undergoes the preparation
for the service of the Great Head of the Church,
or is made fit for being one of the vessels in His house; bearing the inscription,
in legible characters, "`Holiness to the Lord.`"

It is cause of rejoicing that thou hast reference to Him who knew no sin,
yet took our manifold infirmities and transgressions upon Himself,
that we might find rest and salvation in Him.
"`We cannot indeed bear the whole weight.
He knows it, and saith, "`Come unto Me, all ye that labour and are heavy laden,`" etc.
Oh! what a mercy that His holy bosom is the repository of all our sorrows and perplexities!

My prayers are to the Source of all strength and consolation,
that He may be your sufficiency.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
First Month 4th, 1839.

What thou hast, remember thou hast _received;_ if indeed, it be of that which is good;
for "`every good and every perfect gift is from above,
and cometh down from the Father of lights;`" and the strong are to bear with the weak,
and all are required to be willing to compassionate the faults of others,
and even to suffer with and for such as err.
Thus, my dear, wilt thou be prepared for a pillar in the house of the Lord; able,
through uprightness and humble dependence on the Fulness of strength,
to support considerable weight in the building, the Church;
whose workmanship is that of an all-skilful hand,
redounding to the honor and glory of Him who is mighty, and whose wisdom is consummate:
who requires passiveness on our part, that He may make us what He would have us to be.
The groundwork of all that qualifies for serving our Creator is humility.
What a sad thing it is, that in this day, some stars in the firmament, even amongst us,
a highly favored people, are in a wandering state from their allotted sphere.
All this is for want of abiding in true humility of heart,
and is a great grief to the little, lowly ones.

[.letter-heading]
To One who Took a Prominent Part in the Secession From Friends, at the Time of Beaconism.

[.signed-section-context-open]
Sudbury, First Month 13th, 1839.

[.salutation]
To +++_______+++.

Thou wast as a star in the firmament; not of the first magnitude, yet,
in the allotted sphere,
promoting and exhibiting the lovely economy of Him who is
the Author of all true harmony and order in His own works.
Oh! that,
if the things which belong to thy soul`'s peace be not forever hid from thine eyes,
thou mayest receive of the true "`eye-salve,`" and look from whence thou art fallen;
seeing clearly how thou didst lend thyself to the suggestions of a luciferian spirit,
which first caused thee to become as a wandering star; when thou never meant,
in that early time of thy departure from the truth,
to be brought so far off as is now the case; but,
strengthening thyself against the strivings of the seed of life within thee,
that would have humbled thy heart in a sight of thy outgoings,
thou didst become more and more prepared for the attacks of the cruel adversary,
who was watching thy unwatchfulness,
and who at length assumed the form and character of "`the dragon,`" who is declared of,
as drawing down some of "`the stars of heaven to the earth.`"
He has been but too successful with thee and others;
bringing into that which is of the earth, earthy, from the Heavenly One,
even Christ Jesus, the Heavenly Man; whom you extol in words,
but whose government you deny in conduct;
and the spirituality of whose doctrine you set at nought,
as assuredly as the wise builders ever did set at nought this very Christ,
"`the Head-stone of the corner,`" and the "`Foundation already laid,
another than which no man can lay.`"

Many professing the great and awful name of Christ,
"`who gave Himself a ransom for all,`" are now "`worshipping they know not what.`"
Because of the hardness of their own heart, some, once enlightened,
are taking darkness for light, etc.;
for they know not that they are glorying in their shame,
and that they are of those "`who mind earthly things.`"

Thy dear wife, as well as thyself, did walk lowly with the lowly Jesus once:
then you walked safely.
Had there been an abiding with the crucified Immanuel,
He would not have failed to declare unto you, as you were able to bear it,
"`all things which He had seen of the Father.`"
He would have deepened you in true, vital religion;
and clothed you more conspicuously with "`the garments
of salvation,`" and the "`robe of righteousness.`"

Should this expostulation from a trembling one be received, and the heavenly anointing,
the unflattering witness for _truth,_ answer,
or be allowed by you to answer to what I have penned, in tender travail for you,
then shall I have cause to rejoice for all the painful
feelings which have long been mine,
in mourning over your state, both day and night, before the Lord;
in whom I long that peace and rest may be found by each of us.
Amen, saith thy true friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Second Month 6th, 1839.

We want often to pass through the fire, and through the floods,
that we may be fully prepared to receive the blessed language,
"`But now thus saith the Lord that created thee, oh Jacob, and He that formed thee,
oh Israel, fear not: I have redeemed thee; I have called thee by thy name.
_Thou art mine,_`" etc.
Such are heirs indeed of His promises, although they may wait for the fullfilment thereof,
through many tribulations.

It is no small joy to me, who am now much laid on the shelf,
to find that the Great Head of the Church is raising
up those whom I believe to have received from Him,
more than ever were entrusted to myself, of His gifts, for His own honour,
and for the promotion of the most glorious and worthy cause on earth.
Oh! may He prosper the work of the hands of all who wait for His qualifying power:
living in Him spiritually; moving in Him; having their being in Him.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Second Month 16th, 1839.

I feel much for my dear husband and H., in concluding to leave them for a season;
yet seeing me daily drooping under indisposition,
occasions great solicitude on their part;
and what I labour under incapacitates me for contributing to their comfort;
so that I hope,
should it please Divine Providence to restore me
to a tolerable degree of my former strength,
by the projected change for a while,
we shall reciprocally find ourselves rewarded for giving up to a painful,
temporary separation.

We are both feeble now, and likely to be subject to infirmity attendant on old age.
It is often a consolation to me that I feel not reproached with a want of early dedication,
few as my gifts have been,
and little as I have done for the promotion of truth and righteousness.
It is, however,
delightful to my soul to take a retrospect of the
gracious dealings of the Most High with a poor worm,
all wretched without Him; in whom I do still desire to live, and move, and have my being,
in the most exalted and important sense.
May you be qualified to serve the great cause more
effectually than it has been my ability to do!
May you be of those who abundantly labour;
who receive wages from the all-beneficent Rewarder, and who gather fruit to life eternal!
Amen.

[.letter-heading]
To her Son.

[.signed-section-context-open]
Second Month 20th, 1839.

Having this morning received rather a poor account of thee and E.,
I am inclined to send an early reply; feeling much with you,
and desiring to minister comfort, if possible.

What a world of trial, what a fight of afflictions we have!
This warfare, however, will be sure to terminate in victory,
if we "`commit the keeping of our souls to Him in well-doing,
as unto a faithful Creator.`"
May it be each of your happy experience, as well as my own!
We cannot do better; and there is, even in this present life,
"`great recompense of reward,`" in not casting away the confidence.
We must endeavor to hope, as I perceive thou dost,
that we are visited with trouble in mercy.
It is my faith that not an atom of the weight that presses upon
us is unnoticed by Him who "`weighs the mountains in scales,
and the hills in a balance,`" who, even when those great hailstones fell,
spoken of in Revelations, appointed to each its own proportion,
not to destroy that which would redound to the glory of His name,
who is righteousness and truth, but to make way for the establishment of His own kingdom.
Surely it seems to me that our Heavenly Father has you under His peculiar care;
waiting to come, and to take unto Him His great power,
and be known to reign over all in your happy experience;
that so the song of praise may be received;
even "`Alleluia`" to the Lord God and the Lamb, who sitteth upon the throne.

Thank Him for past mercies, and take a little courage.
Wait daily upon your Almighty Helper.
Prostrate yourselves and your _all_ at His feet.

On second day I came here.
Before leaving home my suffering was great from nervous pain,
which continued most of the journey in degree: I am, however,
better since my arrival here, than has been the case for weeks back.
Much do I hope that the change of air and scene will be of use.

I am told that +++_______+++ enquired after me, and remarked how grievous it is,
that at my time of life, I should be under such delusion,
and thereby deprived of happiness; for that _I could not be happy._
Were I to consider it worth while, I might let her know that,
through my manifold and various tribulations, I do witness that it is a true saying,
and worthy of acceptation, which we read in scripture,
"`Thou wilt keep him in perfect peace whose mind is stayed on Thee,
because he trusteth in Thee.`"
All false peace will fail, and all false and polluted rest will be broken up,
while that which is perfect remaineth for the people of God.

I would not have thee be unnecessarily cast down
in the retrospect +++[+++of what thou alludest to]
but leaving the things that are behind, and reaching forth to those that are before,
in the little strength afforded, press through every difficulty toward the mark,
for the prize of thy high calling of God in Christ Jesus.
So, my precious J., farewell.
My dear and best love to E., who will take her share of this.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Second Month 27th, 1839.

Remember that my mind is constantly with you,
and my consolation is that your Heavenly Parent is dealing with you in wisdom and mercy;
so do not be too much discouraged.
Remember that scripture, "`Why art thou cast down, oh my soul?
and why art thou disquieted within me?
Hope thou in God; for I shall yet praise Him, who is the health of my countenance,
and my God.`"

What a journal is Thomas Shillitoe`'s! I never found in any one,
more of attention to Divine guidance _in all things,_ and _always;_ nor more plentiful,
blessed results and precious fruit, from being wholly given up to the Lord, in body,
soul, and spirit; through all perplexity, trouble,
and sore exercise of faith and patience.
How unspeakably glorious must be the crown he now inherits forever and ever,
after bearing his cross so faithfully to the end of time!

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Clapton, probably Third Month, 1839.

I am much better, which, with other favors,
demands gratitude to an all-gracious Providence--

[verse]
____
Good, when He gives, supremely good;
Nor less when He denies.
____

My chief prayer for myself is, to be endued with a meek and quiet spirit,
in which I can say, "`Not my will, but Thine be done,`" oh! my Heavenly Father!

+++_______+++`'s state interests me much.
May it not be possible that she should feel it wrong
to put the negative upon the proposed union?
and is it not better to hope she will be enabled
to discern the will of her Heavenly Father?
Many thought I was under a cloud when we wished to leave Ireland,
and see how it has proved otherwise.

I wish Friends may be careful not to mar the work on the wheel,
with any who may be newly convinced, but there is a disposition to caress too much.
I hear the conference with Friends last evening was not to satisfaction,
which I am sorry for.
It was indeed a fearful concern.
They wanted a Fox, a Penn, or a Barclay.
We should surely depend on nothing short of what was,
to the sons of our morning as a people, tongue and utterance, mouth and wisdom,
which none of the adversaries of truth were able to gainsay,
when these valiants were called to controversy by the Great Master.

We had, the other day, a visit from an extraordinary man, +++_______+++,
which I wish to tell you a little of.
At present he is without being united to any sect, having given up his chapel,
and ceased to preach publicly.
He appears to see with our first Friends very much,
as to the fundamental doctrines of Christianity.
Some of his writings put me in mind of Isaac Penington, so deeply spiritual.
He took a seat by me on entering the room,
and poured forth the effusions of his heart like a perpetual stream,
for a length of time; I never knew the like exactly.
Several times I hinted that we must again and again be emptied,
all which he most freely admitted,
but said that now he could not confess to any other than a fulness not his own.
To me he said, on rising to depart,
I was "`older in the truth than himself;`" and repeated, "`this God is our God:
He will be our Guide even unto death,`" etc.
"`If,`" said he, "`your Society does not rise up out of its present unbending state,
and serve the Lord with holy fervency, He will _shake_ you and _shake_ you,
until He bring you to nothing.`"
to which I replied, "`We _have been_ shaken and shaken,
and the purifying hand is still upon us;
and it is my belief we shall not cease altogether to be a distinct people,`" etc.
He expressed himself as being "`very glad the Great Hand
was felt to be upon us for good;`" and thus we parted.
He appears to be about fifty-five years of age; is a married man; was,
when about twenty years old, an infidel;
and became enlightened by the immediate influence
of the Spirit of truth in his own heart;
and was kept from running after the "`lo! heres,`" etc.;
and is still afraid of looking to _man,_ either by books or otherwise.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Clapton, Third Month 19th, 1839.

On First day I attended Newington Meeting: was largely engaged in the ministry,
much to my relief;
a very solemn sense of the Lord`'s power and love being over the assembly.
+++_______+++ turned to me when the meeting closed, saying, "`This is marvelous.`"
Ah! it is when we are weak, that we are strong in the Lord,
and in the power of His might: to Him be all the praise, saith my soul.
Amen.
It is indeed good to be "`Worm Jacob,`" waiting, again and again,
for the time when the joyful language is heard, "`Fear not, for I am with thee,
to deliver thee.`"

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Clapton, Third Month, 1839.

I went to the Quarterly Meeting "`in weakness, and in fear,
and in much trembling;`" and there have I been raised up this day,
to speak "`in the demonstration of the Spirit and
of power,`" for more than an hour and a half.
It was a very extraordinary time.
The standard of truth and righteousness became conspicuous before the people,
and the gainsayers were much silenced, as I _felt_ to be the case.
Towards the close I had to make acknowledgment on my knees,
to the dominion of the truth amongst us;
and to supplicate for the hastening of the day when all
"`nations shall flow into the mountain of the Lord`'s house;
it being established on the top of all the hills.`"
This address was short and living; ending in praises, yea, _high_ praises; even Alleluias.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fourth Month 11th, 1839.

Before receiving thy sorrowful letter of yesterday, it was in my heart to write this day.
Although I am constantly thinking of you, poor dear afflicted ones,
such has been the exercise of my mind in a religious way,
that I seemed scarcely qualified to take the pen to you,
especially as our arrangements were not quite settled.
Now we have concluded to hold a meeting here on First
day evening for the people at large,
and on second day to set out, hoping to spend third day with you.

I wonder how my dear +++_______+++ is in health, amidst the cloudiness, the storm, yea,
the whirlwind which sometimes surrounds; and how dear +++_______+++ is in mind,
under bodily weakness.
Nothing was withheld by me when last with you,
for nothing arose to communicate in the anointing; yet I felt deeply.
Ah! the ways of Infinite Wisdom are indeed past finding out.
The Most High "`maketh the clouds His chariot,
and walketh upon the wings of the wind;`" yet in the end, His dear children, His adopted,
His chosen seed and generation,
are given to see that all the while He was coming for their salvation,
even when it might seem to their natural minds that certain destruction awaited them.
How then, does it behoove us to trust in the Lord with all our hearts,
and lean not to our own understanding.

We cannot but feel deeply interested about you, while we may be ready to say,
"`If the Lord help not, whence shall I help?`"
But oh!
I humbly trust He does and will help--most effectually.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fourth Month, 1839.

I want to mention what is in prospect for me.
I went to Haverhill yesterday, and, in attending the Monthly Meeting,
informed Friends of a prospect of going to the General Meeting for Hereford, Worcester,
and Wales; also, should strength be afforded,
then to proceed to attend the Yearly Meeting in Dublin.
It is an act of faith.
I have not felt the poor body in what might seem a fit state for such an undertaking,
yet I well know it can be made to answer the end by Him who can, in every sense,
give power to the faint, and increase might to them who have no strength.

It is now time to get ready for meeting.
Farewell,
my very dear +++_______+++. May the "`everlasting arms`" be underneath in all thy exercises.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Fourth Month 30th, 1839.

Oh! heaven is worth attaining through all that prepares for an inheritance there;
through all which purifies, and prepares to adopt the language, "`Oh! death,
where is thy sting?
Oh! grave, where is thy victory?`"

The meetings hitherto have been favored times, at least so far as I have witnessed.
On First day they were solemn seasons; that in the evening particularly so,
and very crowded.
I had five meetings on the way to Holyhead, which proved lively opportunities,
although some were very searching.
Many of a more private character have also fallen to my lot, both in England and here.
Sometimes this poor frame is much exhausted, but on the whole,
I get on with more strength than I could reasonably have expected.

_Fifth Month 1st._--We are just come from the usual meeting for worship, which was long,
and from some circumstances, rather trying.
There is, however, a weighty body of Friends still in this land,
who have at heart the prosperity of truth,
and who are willing to suffer with the suffering seed,
like being "`grieved for the afflictions of Joseph,`" for that which is unjustly imprisoned,
under, or by "`the accuser of the brethren.`"
This grand adversary is attacking our Society in this nation with a bait entirely new,
and not easily defined;
but I trust he will be "`stilled`" before much devastation takes place.
I feel a great travail and exercise on my spirit with respect to it,
and I believe others do the same.
Oh! that the heavenly ear may be mercifully bowed to the sighing of the heavy-hearted.
It may be that Friends had scarcely trembling enough mixed with their rejoicing,
when they saw themselves spared from that which prevailed so much to our hurt in England.
If ever there was a time in which "`he that thinketh he standeth`"
should "`take heed lest he fall,`" it is peculiarly needful now.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Dublin, Fourth Month 30th, 1839.

I feel sincerely for thy dear mother in her afflicted condition of body,
and for thy dear father, as the tender partner of her life with all its probations.
And you, their loved offspring, partake, no doubt, according to your capacity, with them.
"`What a comfort it is to have children susceptible of affectionate
interest in the feelings of their parents,
and in all that concerns them;
and to see our dear children alive to their best interests too!
Thou, my dear, art favored to choose the Lord for thy portion;
the God of Jacob for the lot of thine inheritance:
keep this blessed inheritance by continually watching
against all that would beguile thee of thy reward,
designed thee in this world _measurably_ as a foretaste of an everlasting possession,
in store for such who hold out to the end.
I trust and believe that all will be well with thy mother by and by.
That scripture presents itself,
"`For I reckon that the sufferings of this present time are not worthy
to be compared with the glory which shall be revealed in us.`"
Our sufferings, while pressing heavily on us, seem more than momentary;
but will doubtless, when eternal joy and peace are about to take their place,
prove short indeed.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Dublin, Fifth Month 1st, 1839.

First day was a memorable one,
the evening meeting being as open and as favored as any I can remember.
On seventh day there seemed a quiet over Friends in the Select Meeting,
and I was engaged, both on my feet, and in a solemn address to the Almighty One;
especially begging that He would own us in the more general assembly.
The meetings of Women Friends have also been favored, so far as I witnessed.
The kindness of friends is very striking;
I believe there have already been hundreds to see me.

Thy last letter is very precious to me.
I believe thy reward will be sure in thus giving me up.
I do indeed bear thee on my heart, and hope thou wilt still be comforted.
He to whom we have dedicated ourselves and one another,
is the source of all consolation and strength.
He hath said, "`I will never leave thee nor forsake thee.`"

I have been rather hoarse since First day with long speaking:
it is a wonder my lungs hold out as they do.
It seems indeed, as dear S. remarks,
as if Divine Providence raised me up for this service; and He makes the way for me.
Cousin S. F. is truly hospitable and kind; we have every accommodation.

[.letter-heading]
To +++_______+++, a Friend in Ireland,
who Took a Conspicuous Part in the Secession From Friends in That Country,
About This Time.

[.signed-section-context-open]
Dublin, Fifth Month 7th, 1839.

[.salutation]
Dear +++_______+++,

How is it that we have not (as heretofore) enjoyed
each other`'s company during this Yearly Meeting?
We used to "`take sweet counsel together,`" and could
rejoice in the all-preserving power of truth,
while yet we were in trouble.

Thou didst admit that I was the same still.
I sent to thy lodging yesterday morning, to ask thee to come and take leave,
but thou hadst left town.
Ah!
I think thou dost not feel towards me as formerly,
and my views are just those that I have always had in my religious profession,
and in which we have been so strongly, and so long, sweetly united.
Day and night do I travail for thee,
that thou mayest see how it is with thyself and others.
There is at present a cloud over thine understanding, and until it be removed,
thou canst not admit of having fallen into error.
Oh! wait, deeply wait upon Him who is both able and willing to enlighten thee again:
then would all those who were tenderly united to thee in the truth,
receive thee with joy; I for one.
It would be like healing balm to be able to feel
thee in the same precious nearness again;
thou who stood so long as an upright pillar.
What has warped thee?
There is a remedy.
There may be restoration, if, without delay,
all is yielded up into the hand of Infinite Wisdom and Strength;
and if there be an acknowledgment of having unguardedly given way
to that spirit which is seeking to sever instead of cement.
This noble confession will do much good, and may be instrumental to bring back wanderers,
and to keep others from going out.

Once more let me say, my loved friend,
that which would interrupt our wholesome discipline, is out of the life of Christ,
who is Head over all to His Church, and who loves His Church as His own body.
Beware how thou lends thyself to anything out of the holy harmony,
out of the blessed life, out of the true light, out of the inseparable love of God.
Oh! may He make manifest to thee that this breach of unity in this nation is all done,
and doing in the dark.

I thought of poor James Nayler, and the women`'s deceitful cry with him,
when he was getting under that grievous delusion,
concerning which he owned he felt unable to come out;
but we see the hand of the Lord brought him out, as he came to lean upon it;
his eyes being anointed to see himself in bondage and in error,
and his heart bleeding with sorrow.
He did not intend to do wrong willfully, but giving way a little to an unrighteous zeal,
was led on until he came under a dense cloud.

Ah! dear +++_______+++, consider these awful things, and be timely warned.
Take not thyself away from us as a Society,
but retrace those steps that have caused thee to turn thy back on the fold.
So dearly farewell.

[.signed-section-closing]
I remain, with love unfeigned, thy sincere friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Fifth Month, 1839.

Ah! my dear +++_______+++, thou art indeed mistaken.
I did the very reverse of lending my ear to reports calculated to impress me unfavorably,
as regards thee or others.
It was my care to be preserved from judging anything,
until the Lord should be pleased to come.

I can say that, before seeing for myself how things were,
my mind was much disposed to hope that thou wast as free from undue bias,
as thou art from insincerity; but I became convinced,
in the opportunity R. B. and myself had with thee and the other friends,
who so kindly gave us your company, that there was a dimness,
and a disposition given way to, which, if not checked, would lead from true meekness,
and submitting ourselves one unto another in love; maintaining the good order of society,
without which there must be confusion, and, instead of church government, anarchy.
So then, is it not better to bear our burden patiently, even if we see that,
in some respects, acts of monthly or other meetings,
are not in accordance with our individual views of what is right?
waiting thus to know what interposition may come from the Great Head of the Church,
to satisfy our exercised minds.

I am persuaded it is our place, as members of the body, to be subject to the body.
Who ever prospered, in the best sense, by either going out,
or acting in a way to be disunited?
Especially,
when did such as have once shown themselves deeply concerned for the upholding our principles,
in their native character of simplicity and purity?

There is, in _this_ Yearly Meeting, much remaining to be done away,
before we are prepared to assume the lustre which
attracted the minds of many in our early times,
and induced men to glorify Him, whose workmanship we were in our beginnings.

I believe the Divine hand is upon us in this day,
for the great end of again refining the gold that has become dim,
and the most fine gold that is changed, that He may be honored,
and His own dear people made glad in Him, and one with another.

May we be willing to bear our allotted portion of exercise and suffering;
keeping our habitations in the truth,
and "`committing ourselves to the Lord in well-doing, as unto a faithful Creator.`"
So farewell, my long-loved friend, and believe me to be sincerely thine,

[.signed-section-signature]
Sarah Grubb.
