== Chapter 21. Letters from 1839--1840

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Sixth Month 8th, 1839.

I seem capable of little that is likely to interest others,
and truly glad and thankful I am to learn that some, in the vigour of both mind and body,
are prepared to advocate the great and blessed cause of truth,
both among us as a Society, and more at large.
Others, I humbly trust, are under the forming hand,
and will become overflowing vessels likewise.
It continues to be my lot to labour in the ministry of the word,
both in my own particular meeting, and in the general assemblies.

How cheering is thy intelligence of some of the engagements and
dedication of divers gone forth on the most important errand,
even that of inviting souls to Christ.
And again it is truly consoling to find that +++_______+++
keeps his hold of that invisible arm,
which enabled him to bear his testimony against the innovating notions
and erroneous principles which threatened blindness to himself,
as well as scattering to others.
May the Great Head of the Church abundantly bless the true magnanimity evinced
by his confession of the "`Son of man before men,`" and of his own imminent danger
of denying the inward and spiritual manifestation of this Savior of men.
I wish that many may be induced to return,
who have wandered as wandering stars in our day; but oh! the humility,
the great mortification of the mere man which becomes necessary,
almost brings one to the mournful language of the prophet, as regards some,
"`there is no hope;`" and the wilful blindness of others leads to the painful conclusion,
that they are not likely again to come out of captivity, or see their native country.

My spirit is made sorrowful too, on account of the absence of tenderness in our youth.
Where is the heavenly dew that did once descend on the branches of our vine?

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Sixth Month 30th, 1839.

I think of thee as one moving in the sphere allotted in best wisdom, and therefore,
in thy yielding to the will of thy Heavenly Father, thou art, in thy measure,
promoting and exemplifying the beautiful economy of His government and blessed work;
and I would have thee encouraged in humility and holy fear,
whereunto thou hast already attained unto anything good,
to mind that same thing which has so influenced thee, and walk by the same rule; that so,
holding out to the end, thou mayest receive the precious prize.

How pleasant it is sometimes, as in the sunshine, to see beyond this vale of tears,
although as through a glass darkly, into the world of joy unspeakable, and full of glory,
where all tears are forever wiped from the eyes, by the hand of the Lord God Almighty.
Farewell.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Seventh Month 12th, 1839.

It seems peculiarly inscrutable to me that we should
necessarily be so widely separated just now,
but still there is some stay to the mind in the consciousness
of doing as well as one knows how;
and it behooves us to learn to trust in Him whose compassions fail not.

I have dwelt much lately, with reference to thee,
on the dealings of the Most High with His people of old,
when they were in the wilderness, where they were so marvelously cared for.
Oh! the love, the gracious regard manifested! "`He led him about; He instructed him;
He kept him as the apple of His eye.`"
"`As an eagle stirreth up her nest, fluttereth over her young,
spreadeth abroad her wings, taketh them, beareth them on her wings;
so the Lord alone did lead him, and there was no strange god with him.`"
Thus is He waiting to do for us, in the wilderness of this world,
as we are engaged to look to Him; yea, to choose Him for our portion,
and for the lot of our inheritance.

Be assured you are not forgotten by thy tenderly and deeply interested mother,

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Brecon, Seventh Month 18th, 1839.

The Select Meeting was held last evening.
It was more of a searching time than I anticipated.
Friends are very kind and attentive to poor me.
I write this with a trembling hand and heart;
the weight of religious exercise is awfully heavy.

_Hereford, 19th._--There were three religious opportunities at the inn,
with the great company at Brecon: it was, on the whole, a time of suffering to me.
There seems to be cause for mourning, within the compass of this General Meeting.
My spirit did not rise altogether superior to the oppression felt;
yet there is a precious remnant among Friends hereaway, as well as in other places.
Nothing can exceed the kindness and attention of these Hereford friends.
May they be recompensed from on high, for they are succourers of many!

Last evening a person supped here who attends Friends`' meetings--mayor of the town.
Some of his family have come among Friends.
I had a remarkable time.
I am now writing in a very beautiful house, situated in a spot truly delightful,
above the town; commanding a very fine view of both town and country.
What rich scenery there is in this county of Hereford!

[.letter-heading]
To the Same.

[.signed-section-context-open]
Worcester, Seventh Month 21st, 1839.

At L+++_______+++ Friends seem to be of the old school.
I was much comforted in the family where we lodged,
to see them so simple in every respect.
They have four dear children.
At the meeting at L+++_______+++ there were, I understand, three preachers, dissenters;
and what is remarkable, without knowing that,
I had to speak particularly on the ministry of the Gospel;
yet somehow I have not been able fully to lay down my burden there or elsewhere, lately.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 10th, 1839.

Great is my desire that the dealings of Infinite
Wisdom may be blessed to each individual among you,
so as to induce more perfect dedication of the gifts
bestowed by Him who grants five talents to some,
while others receive but two, or even one.
May we all keep in mind that the period is approaching,
when the solemn query will be heard, "`What hast thou done with thy Lord`'s money?`"
Oh! that it may not be found buried in the earth,
or otherwise than having answered the blessed purpose of the great Donor.

Often,
very often do I long to know if thy health and spirits are a little recovered from the
depression unavoidable under circumstances such as thou wast long tried with;
and which terminated, as regarded the object of tender care and sympathy,
with such a lively hope of eternal rest and peace;
so that there is occasion to rejoice and give thanks,
rather than lament the loss of his society, much as you must all feel it.

I cannot fully express the earnest desire of my heart
for those who survive their loved brother,
that there may be a disposition cherished to pursue, in the first place,
things most worthy of them, and which make for peace.
How does all that is perishable and transitory, sink into comparative insignificance,
before the view of that which concerns the soul`'s welfare, here and eternally;
and how truly dignified is the state of such as serve the Lord "`with a perfect heart,
and with a willing mind!`"
Without this devotedness to the Most High,
what would even the wisdom and greatness of Solomon avail?
It would not,
it could not give man to be found in the situation
answerable to his high calling of God in Christ Jesus;
even that of being "`made a little lower than the angels,
and crowned with glory and honor.`"
Tell your dear children the old woman they paid such kind attention to,
when it was our lot to meet, always thought as she now writes,
since ideas were at all formed in the youthful mind.
May they timely, yea, without delay,
be so wise as to "`lay up for themselves a good foundation
against the time to come;`" that,
should they even live to old age, they may possess substantial happiness:
that "`when the grasshopper feels a burden,`" the
intolerable burden of disobedience be not their portion.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 16th, 1839.

It was very kind to address thyself to me in an epistle
calculated to raise the mind into a feeling of encouragement,
that the blessed seed of the heavenly kingdom would yet reign within our borders;
and that the true followers of our great and good Master may hope, even now,
that "`the cup of trembling`" will be taken out of their hand in the Lord`'s time,
despite of all that oppresses the Divine life.
My faith, though one of "`the least of all,`" has been,
from the commencement of the terrible shaking we have witnessed, and which is still felt,
that the "`Most High`" will yet show Himself on the side of those
who "`stand still`" from all the efforts of the mere man;
that these shall "`see the salvation of God,`" being
prepared to say "`amen`" to His permitted,
as well as appointed dispensations; ascribing unto the Lord God and the Lamb, blessing,
and glory, and wisdom, and thanksgiving, and honor, and power, and might.

Deeply interesting to my feelings are the contents of thy letter,
and much do I desire the interposition of Omnipotence,
to stem the torrent which is laying waste the Lord`'s heritage in no common degree.
Overturning must come; and again overturn He will, and still overturn,
until He reign whose right it is, even the "`King eternal, immortal, invisible;
the only wise God.`"
Yet how mournful it is that, under the mask of promoting the kingdom of Jesus,
it should be betrayed and dishonored, as in this day;
and the very life of Him who exemplified meekness and lowliness in a body of flesh,
trampled on and persecuted.
Oh! how delightful the thought that we yet have those among us,
who are willing to be the companions of Him who, for the sake of fallen man,
made "`Himself of no reputation:`" with Him they ascend Calvary`'s mount, and when,
with Him also, they are followed and caressed, they withdraw and hide themselves,
as He set the example; not striving, nor crying up their name among men,
but the very reverse.
"`He shall not cry, nor lift up, nor cause His voice to be heard in the street.`"

I wish we may be humbly bold in the Lord`'s cause.
"`Were this more general, I think, with thee, there would be less of squeamishness,
and that fear which is slavish; for "`perfect love`" casteth this out,
while false love cherishes so great a bane to the edification of the body,
and the advancement of truth.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ninth Month, 1839.

Thy letter received this morning, gives a more discouraging report of poor,
dear +++_______+++. It would seem a favor if her sufferings were not much further protracted,
but how consoling it is that the mind can stay itself on Omnipotence,
and thus know a safe anchorage on the rock of eternal salvation.
What thou writest of your state reminds me of the scripture,
"`We glory in tribulations also: knowing that tribulation worketh patience; and patience,
experience; and experience, hope,`" etc.

How wonderfully hast thou been sustained,
my dear +++_______+++! Surely "`this is the Lord`'s doing: it is marvelous in our eyes.`"
May the everlasting arms continue underneath all the billows that pass over;
and I humbly trust this will be the case.
What a balm in life is true, vital religion!
To such as possess this treasure, the name of the Lord is indeed a strong tower:
they run there in adversity, and are safe.
Dear children, may this be your refuge from storm,
your hiding-place in the day of trouble.

Farewell, my dear +++_______+++. I am, in tender feeling for thee and thine,

[.signed-section-closing]
Thy affectionate

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Tenth Month 4th, 1839.

In this dispensation of the Gospel of Christ Jesus our Lord,
by whom is come "`grace and truth,`" we are convinced
that tribulation permitted to the faithful,
is no mark of Divine displeasure.
We may even glory therein, knowing by experience,
what great things it worketh in and for the passive, resigned soul.
Oh! it is an honor to be made mighty to suffer in the will of the Lord:
we may be brought the nearer in blessed union with Him who "`was a man of sorrows,
and acquainted with grief;`" and all for our sake: yea, "`He was cut off,
but not for Himself.`"
Many will follow the Great Captain of our salvation, while "`Hosanna to the Son of David,
hosanna in the highest,`" is sung with delight and triumphantly,
who nevertheless leave Him, rather than become of no reputation for His sake,
and partake of His sufferings and anguish.

There is no doubt much existing that calls for our "`speaking the truth
in love;`" that love which breathes lasting "`good will to men;`" especially
to those among men respecting whom we cannot but feel much affectionate,
as well as religious solicitude.
We are not to spare these any more than ourselves;
and is it not the heartfelt petition of all who would be found
eventually in the holy likeness and blessed image of Christ,
"`Let not thine hand spare, nor thine eye pity`" that in me,
which militates against the reigning of the seed immortal?
Thus it seems to me that true "`charity begins at home,`" and in exercising it,
we may promote a "`growth in the truth,`" in our own community;
even through Him who remains to be Head over all to His own body;
"`from whom the whole body, fitly joined together,
and compacted by that which every joint supplieth,
according to the effectual working in the measure of every part,
maketh increase of the body, unto the edifying of itself in love.`"
Here is no preference given to "`men`'s persons because
of advantage,`" but a holy and precious oneness;
the real, not nominal unity, of the one Eternal Spirit.
Oh! how precious a bond is found in this! indissoluble by death itself.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Lexden, Tenth Month, 1839.

What a favor it will be if poor E. is but gently let down into the arms of the relentless,
cold messenger; and this is what she asks in submission.
Oh! it is truly delightful to see her as she is, brought into humility;
that humility that goeth before honor, the honor from above;
a dignity beyond all the glory of a fading world, granted in its various degrees,
even as the soul`'s capacity becomes fitted for its participation.
Last evening, in sitting by the bedside, I was put in mind of the lark ascending,
and still rising higher and higher; singing as it goes,
the praises of the Sovereign of the universe.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Sudbury, Tenth Month, 1839.

I had to exhort Friends today,
to mind and keep to the overshadowing of heavenly goodness, with which we are favored,
sometimes early on gathering;
and to express my belief that it would (as cherished) increase,
even until we became baptized as one body,
witnessing the Lord Jesus Christ to be our head and our life.
Oh! what should we do without religion; the religion of the heart; true,
vital Christianity?
wherein self becomes of no reputation,
and in which we really and sincerely hate that in us,
which militates against our becoming wholly subordinate to the Spirit of truth.
I am without the shadow of a doubt,
that this state of submission to the Divine mind brings to the rest,
to which we are invited by the blessed Son of God Himself--"`Come unto me,`" etc.
Watch well thine own mind, my precious child,
that thou mayest be favored with lasting peace.

I do not know but I may be prevented attending the General Meeting at Hereford;
and if this be the case,
an incomparably more exalted Christian than myself experienced
what it is to be "`hindered,`" before it came to my turn.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eleventh Month, 1839.

At length the scene closed forever, and the sufferer +++[+++Her daughter-in-law, E. G.]
was released from all her pain, and sense of oppression and sinking.
The spirit seemed joyfully to take its flight to the happy regions of eternal life.
Nearly the last word articulated was "`glory.`"
Ah! my dear, to part with those we dearly love, for even a better world,
brings sorrow indeed; and the severing stroke makes the heart to bleed;
but how different the feelings in seeing any dear to us wander from the true sheepfold,
and the pastures of Divine life, unto the dark mountains as it were,
among beasts of prey.
Oh! for these I mourn, as well those among you, as in this land:
for some especially my soul is very sorrowful,
because they had known the protection of the Good Shepherd in no common degree,
and were delegated by Him to encourage and invite others into the right way.

Truth, however, knows no change, and its Author is "`the same yesterday, today,
and forever.`"
Nothing will do for any of us but to learn of Him.
He teaches meekness and lowliness of heart, whereby rest may be obtained,
the "`yoke found to be easy,
and the burden light,`" because it consists in taking
the Divine will upon us instead of our own.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eleventh Month 17th, 1839.

Your little company are very present with me.
Much do I desire that a blessing may attend your present
lawful and likewise expedient pursuit of health.
A privilege it is indeed to possess a tolerable share of that which, in my estimation,
stands first on the list of sublunary enjoyments;
for without it we are rendered more or less incapable
of taking pleasure in the creatures of God,
while we may see much in His visible works to call forth our adoration.

This morning (as well as many others) being early awake,
I had my thoughts wafted to +++_______+++, with an earnest, religious,
and affectionate solicitude that He might be with you, who filleth all space,
and who taketh cognizance of us in every situation; that He, I say,
might be with you as Guide and Protector; yea, as the promised Comforter--the Holy Ghost,
whom the world cannot receive, because it is not congenial to its spirit;
therefore the world knoweth not this Comforter; it doth not acquaint itself therewith,
for it is opposed to its nature; the one being heavenly, and the other earthly;
the one being of eternal duration, the other perishing with the using.

Set thy affections on things above, my dear +++_______+++, yet mind thy duty in temporals;
for a neglect of the latter indicates that disposition unto which
a woe is attached--"`Woe to them that are at ease in Zion.`"

We have many calls on our energies, even from the sphere allotted us in best wisdom;
let us then watch, lest, while we sleep, the enemy sow tares among the wheat,
and we be mixed up with what must be burned or consumed.
Oh! my dear, my loved +++_______+++, I want thee to profit abundantly by the permitted,
as well as appointed conflicts and disappointments experienced.
Thou hast been dealt with in no common way,
for the Most High has designed to refine thee, but not with silver;
to choose thee in the furnace of affliction, that thou mayest be as gold;
as the gold seven times refined, on which "`Holiness to the Lord`" may be inscribed,
even in characters peculiarly legible.

Now it seems to me that the grand adversary of our peace, and of the glory of the Lord,
is watching for a moment when thou mayest be a little, a very little,
and inadvertently off thy guard, to succeed, if possible,
in his attempts to bring thy poor dear mind into a desponding state; or, failing in that,
to divert from the true centre, by alluring and bringing to created objects,
in which present relief may be experienced; which, if joined in with,
would frustrate the will of Him who would that we
should know all things to work together for our good;
yea, and for the promotion of His glory.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Twelfth Month 19th, 1839.

I do believe that,
in thy bowing with submission to the will of Him "`who doeth all
things well,`" He will distinguish thee as one who fears Him;
and thinking of thee, the words that occurred to me on my bed yesternight were,
"`The angel of the Lord encampeth round about them that fear Him.`"
+++_______+++ fears my name.
I will care for him in this his extremity,
as he is engaged to look for protection where thou hast ever found it.
Thus my mind has been stayed amidst much tossing as with tempest,
even in sympathy with thee,
my dear +++_______+++. Oh! fall to the Rock that is higher than thyself;
so will it prove a refuge for thee now, and in every time of trouble.

It seems as if I could not give up the prospect of
being in London at the next Quarterly Meeting.
I commend thee in my mind to thy Heavenly Parent,
whose watchful eye is not to be put in competition
with that of the most tender earthly connection.
Trust thy Father above, I entreat thee;
and try to leave all painful cogitations at His feet, who groaned, who sighed, who wept,
who agonized in a body of flesh, in sympathy with,
and in a great degree even for suffering humanity.
Ah!
He knows that we cannot bear the load which presses on us sometimes,
without being crushed, therefore a way is opened to come to Him, when heavily laden,
and under great oppression, and to learn of Him meekness and lowliness of heart.

Come, my dear +++_______+++, come to Him, thy Savior; "`a covert from heat and from storm;
a hiding-place in the day of trouble; as the shadow of a great rock in a weary land,
and as rivers of waters in a dry place.`"
Farewell.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Near London, Twelfth Month, 1839.

I was very dull and weighed down in mind: went to meeting heavy and sorrowful:
I thought never was my mind in a more burdened state,
and sat under it a considerable time.
in silence.
After some time I stood up with a clear opening, but soon found my way closing up;
and mentioned to the meeting that,
although the constraining influence of gospel love induced me to leave my seat,
it would not do to stand among them without the ability
was given from above to deliver what was my sense of things;
and I did sit down, in which my poor mind felt peace.
I leave thinking how far any enlargement may be mine; believing that, if watchful enough,
right guidance will be vouchsafed:
and should it be my place to come home even as I left it,
I trust my mind will be enabled to exercise patience and faith too.
I have felt leaving you very much indeed this time,
yet am enabled to commit my dear family to the care of our Heavenly Parent,
omnipresent and omnipotent.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clapton, Twelfth Month 27th, 1839.

The interview with thee this evening has proved quite a relief to my mind.
How few there are with whom one can unbend, and speak freely,
on subjects of great interest; but there are a few who, in the Divine fear,
take sweet counsel together in this day, as formerly,
and feel the strength of true unity.
This is indeed a "`good and pleasant thing.`"
May we be favored to witness it through all trial!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Twelfth Month 31st, 1839.

In the midst of all I have met with to try me, within the last two weeks,
"`Jerusalem is found to be a quiet habitation;`" repairing to which,
my soul feels ability to praise the Most High,
in permitting His poor handmaiden to be buffeted, and even grieved sorely;
believing all will work together for good.

Farewell, my.
dear friend.
The language of my heart is, "`Let the righteous smite me, it shall be a kindness:
and let him reprove me, it shall be an excellent oil, which shall not break my head.`"

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
First Month 22nd, 1840.

It is not well, my dear and precious +++_______+++,
to dwell on little occurrences beyond their due weight.
Common-place and every-day matters are not to be overlooked,
because in these we may find either domestic comfort,
or what I should call the very reverse:
then we are to know that it is binding on us to observe
our greater duties in the first place--"`doing the one,
and not leaving the other undone.`"
This is my motto through life.

Let me entreat thee to remember, that we are called upon to be prepared to say,
from living experience, "`Faint, yet pursuing.`"
It is only as we wait upon and obey Him who waits to be the strength of Israel,
that this can be the case.
Israel is the seed or generation which did wrestle,
and doth still wrestle for the Divine blessing, even through the darkest season,
all night, until the "`breaking of the day.`"
My dear +++_______+++, believe it,
"`The expectation of the poor shall not perish
forever,`" therefore "`Gird up the loins of thy mind,
and hope to the end.`"
It is the girdle of truth we are to take, and that I know thou valuest and believest in,
as enabling to stand uprightly.
Put on the whole armour of God.
Read of it as set forth in the Holy Scriptures;
and may the ever victorious Captain be with thee,
my dear +++_______+++:may He give thee to go forth against the vaunting Goliath,
who has already enabled thee to be too strong in Himself for the paw of the lion,
or that of the bear.

Ah! my dear, let nothing rob thee; let nothing beguile thee.
"`Be watchful, be vigilant, be sober.`"
Be not too much depressed, neither give way to any presentation,
promising relief to thy suffering mind, out of the will of thy Heavenly Father,
thy Savior and thy Judge.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
First Month, 1840.

Yesterday it seemed best for me to attend the funeral at +++_______+++. At my
request the company stayed a few minutes after the meeting broke up,
and I had to speak in a way that could not be done with propriety in a large,
mixed assembly.
Many tears were shed, although things were plainly set forth.
As for the departed, I had to say that,
"`in fear and trembling,`" it was with me to express
my belief that the preparation for rest,
yea, joy beyond all which this world affords, was mercifully experienced,
although unseen by mortals.
I told the bereaved Friend there was no more for me to say to him (when he turned back
to take my hand) except that I believed I should remember him before the Source of all-sufficiency.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Second Month 18th, 1840.

I am aware thou hast been singularly dealt with, yet the trials allotted are, no doubt,
such as, in Best Wisdom, are most adapted to work the end designed.
May patience have her perfect work, that thou mayest be brought forth,
in thy Heavenly Father`'s time, as into a large place;
partaking of the glorious liberty of the children of the Highest.
My soul does send up aspirations on thy behalf, to the throne of grace;
desiring thy help and thy stability through all.

Do thy best, my dear, and try to commit the keeping of thy soul to the Lord,
who graciously compassionates us in perplexity and tribulation.

I had cherished some hope of being free to return home,
after the great meeting on First day in the City,
but am yet in the bonds of the Gospel hereaway.
Have been at Southwark Meeting this morning,
which proved a fresh opportunity to relieve my mind a little of its burden;
yet do I feel that, in my measure,
I am bearing about in the body the dying of the Lord Jesus;
craving that His life may abound also in this mortal flesh, to His own praise.

It is not in meetings only that I have weighty exercise, but, without much intermission,
I do indeed go bowed down in my present allotment,
and yet cannot desire it otherwise before the period arrive when
my Great Master may give permission to put off the harness,
and witness some rejoicing in His mercy and in His salvation.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Probably Second Month, 1840.

The Morning Meeting is over.
I have had close work there, but feel peace.

Oh! what a time that meeting was to me!
I came to it under great exercise.
Had addressed the young people at Clapham this morning, including their visitors;
and had a meeting with the servants last evening.

I do hope that the hand of the Almighty is turned upon divers in this day,
to prepare individuals for advocating the blessed cause of truth in its own character;
and my mind is in some degree comforted in the belief,
that the Great Head of the Church has condescended to regard
those who have turned to Him in His smiting us as a people;
and that He is turning His face towards us, in our still deplorable condition; so that,
while sadness is the covering of my poor spirit,
in beholding the desolations made by the grand adversary,
who watches his opportunities to pull down and destroy that
which has been established among us through much persecution,
I can feel the tribute of gratitude arise in my heart to the compassionate Judge,
for that He is visiting "`this vine,
and the vineyard which His right hand hath planted;`"
even after "`the boar out of the wood,
and the wild beast of the field,`" have occasioned such devastation;
and they who have passed by,
seeing the "`breaking down of her hedges,`" have plucked her with impunity.
The prayer of my heart is that yet the branch, made strong by Omnipotence for Himself,
may be renewed and bring forth fruit, to the glory of His Name.
It seems to me that yet the precious has to be distinguished
and separated from the vile more thoroughly,
before complete restoration is known; perhaps especially so with us,
who may be now reckoned first.
"`The last shall be first, and the first last.`"
How nice it is for me to have those at home, and a few here,
who can feel for me under my exercises!
They are great for my capacity.

There are some who keep with each other in spirit,
through all the overturnings to be met with; but where do they stand,
and where is their shelter?
Is not the Roek of ages the sufficiency of such in all their exigencies?
Yea, that which remaineth because it cannot be shaken,
is a "`hiding-place in the day of trouble; a covert from heat and from storm;
as the shadow of a great rock in a weary hind;
and also as rivers of waters in a dry place.`"

[.letter-heading]
To the Same.

[.signed-section-context-open]
Second Month, 1840.

Yesterday I had a brave time in the morning at Newington Meeting.
I went there much weighed down, and not looking for ability to speak; but,
waiting on the gift, was constrained to leave my seat, and stand, I think,
nearly an hour.
My spirit was much baptized for the evening`'s work,^
footnote:[A public meeting at Devonshire House.]
which, through adorable mercy, was, I think, well got through.
I cannot say the power was in all the glorious dominion I have at times known,
but the truth prevailed; and it was a time of awful warning, and invitation too,
to come to the Savior.
"`Oh London!`" was in my voice repeatedly; and, "`this great,
this wonderful city;`" "`this metropolis;`" "`the mart of all the earth.`"
Then I had to quote Cowper, "`Thou great resort,
and mart of all the earth,`" on to the end of the passage;
and to say that God was jealous of His honour, for the idol, mammon,
had taken the place of Him, the only true God, and that in a great degree:
that I believed the Almighty was now frowning over this populous city;
that the clouds had again and again been filled with tempest,
and yet He had manifested His compassion: that now He was calling,
that there might be a turning to Him who had in degree smitten,
that He might be glorified over all, etc., etc.

I understood it was doubtful if there had ever been so large an assembly there.
It was thought the people were remarkably still.
There were two thousand notices sent out and distributed very extensively.
I believe your prayers were heard and answered, for the meeting.
It was different from my last of the kind in that great house.

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Second Month, 1840.

There is, almost without intermission, in my present visit to this city and its vicinity,
a laboring under a sense of the bonds of the Gospel,
to the bowing my spirit as with a weight of suffering; only after meetings,
for a very little while, I am eased in measure.
This I account a great relief, like a brook by the way.
I do feel myself among the very least and the weakest,
of those whose first desire it is to be the Lord`'s.
May adorable mercy and goodness still follow me,
a poor creature; or how can I hold out to the end?

[.letter-heading]
To the Same.

[.signed-section-context-open]
Uxbridge, Second Month, 1840.

I am a little cheered by meeting with some real Friends here,
but have a dread of tomorrow, and much more dread of getting back to London,
not knowing what may be in store for me there;
yet I do try to rest in the will of my dear Master,
who no doubt hides the future for wise purposes.
I am doing what I can to get home without a burden,
but cannot promise myself that it will be so.
When I get home, I hope to take a little ease, of which my frame seems to stand in need,
for there has been much to wear me.
Let me not complain, however.
What is there to complain of?
The Lord has been pleased to make my way for me,
and I have found great place in the minds of some gay young people.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Third Month 6th, 1840.

This morning early, being long awake, I remembered the scripture, "`What be these,
my Lord?
These are they who have come through great tribulation, and have washed their robes,
and made them white in the blood of the Lamb.`"
It was strengthening to my poor mind, for I am still in tribulation;
while it seems to me that, having done as far as made known, the Master`'s will,
I am permitted to suffer; yet I hope with a degree of cheerfulness,
and in the full persuasion that there is nothing worth living for,
out of the Divine mind.

[.letter-heading]
To her Son.

[.signed-section-context-open]
Sudbury, Third Month 22nd, 1840.

[.salutation]
My Dear J.,

Thou art much in my remembrance, and how should it be otherwise with thy mother?
a mother who bears her children on her heart before the Lord,
in desire that their chief concern may be to approve themselves unto Him.
He sees not as man sees, and His ways are infinitely above our ways,
even as the heavens are high above the earth.
Oh! that my dear children may never forget their
daily dependance upon Him for right guidance,
and for ability to "`serve Him with a perfect heart, and with a willing mind,
remembering that, "`if they seek Him, He will be found of them; but if they forsake Him,
He will cast them off forever.`"

We may be drawn from Him so many ways,
that it highly behooves us to watch every avenue of the mind, lest we be beguiled,
and so the Divine purposes concerning us be in any way frustrated.
Do thou watch, my loved J., my precious and only son,
do thou watch diligently over thy own heart,
that thou mayest be one of those whom the Lord keepeth day and night.

But why do I write thus?
Thy trials have taught thee that there is no safety but in the care of the Good Shepherd.
Ah! my dear, He still cares for thee,
that thou mayest be His entirely--not at thine own disposal,
but attending to the voice which keeps from all that would alienate from Himself.
Mind and listen attentively,
so shalt thou know that there is power in His word to preserve thee on every hand,
and to sanctify all thy sorrows in thy blessed experience;
giving thee to acknowledge to the righteousness of His dispensations,
in His permitting thy pleasant pictures to be marred
by His coming in the day of awful visitation,
and in thwarting thee in thy projects, which appeared to be both lawful and expedient.
Oh! that all things may but work together for thy good, my son;
that He who is Lord of all may be magnified in His dealings with thee,
and in His will through thee.

I attended the Quarterly Meeting at Ipswich,
through a deal of suffering from pain in the limbs, etc.;
but am glad I gave up to be there.
This day I can scarcely stand,
so that I was obliged to relinquish the idea with which I rose this morning,
of attending our own meeting.
I am really much of an invalid, neither do I think that medicine can help me.
Thy dear father seems nicely, dear man, but very feeble: his dear love is to thee.
I must now lie down for a while, and try for a little more ease, by change of position.

Farewell.
May goodness and mercy follow thee all the days of thy life,
saith thy sympathizing and tenderly affectionate mother,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Third Month, 1840.

My mind is often with you in sincere and earnest desire
that nothing may harm any one among your circle as a family,
especially such who love our Lord Jesus in sincerity.
Now those of thy household who profess to love Him much, do love sincerely;
this is my impression.
Some there are, who have much to be forgiven, who,
if they will come to the feet of Jesus, and wash these sacred feet with their tears,
and wipe them with the hairs of their head,
will "`love much,`" and be forgiven all their transgressions.

Ah I what would thy dear +++_______+++ and +++_______+++ have done under their tossings,
and in their distresses sometimes, but for this Rock in a weary land?
the eternal, unchangeable Rock.
Nothing can move it; let us all, and individually flee to it therefore.

My dear brother in tribulation, this refuge is for thee.
The world may be compared to a wilderness, to a dry and thirsty land, in thy experience,
where no water is, no refreshment for thy poor, weary, thirsty spirit;
yet is there for thee "`rivers of water in a dry place.`"
Only do not say in thine heart,
"`It is for those who are able rightly to seek what would relieve them; not for me,
who have no power.`"
Remember, the Lord "`giveth power to the faint,
and to them that have no might He increaseth strength.`"
Wait on Him, and be of good courage.

I hope, with thee,
that the liberty for marrying first cousins will still be withheld by the Society.
Those who let their affections out in this way do, I apprehend,
bring themselves under a cloud; and it would be much to be regretted,
should such a thing come forward and be received,
so as to render the body of Friends responsible.
This is my humble view of the subject.
Perhaps I speak this by permission only.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Fourth Month 7th, 1840.

How often do I think of the necessity of making use of the day,
of walking while there is a little light; to get on, even feebly,
with the remainder of my travel through the wilderness of this world;
for it would be deplorable should the night come before I have finished,
and stumbling be my experience, not knowing how to make straight steps.
My poor energies are failing, and I feel like a worm,
and a worm on whom the foot of man has been set;
yet so long as any renewal of strength is mercifully given,
it is my desire to move on in that path opened to the view by the Guide of my youth;
trusting that the same will be the staff of old age.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fourth Month 9th, 1840.

What clearness would be given, if indeed the true "`eye salve`" was applied for;
but how sorrowful that a substitute is so much introduced;
even human prudence and worldly wisdom!
Sometimes the language forcibly occurs,
"`What wilt Thou do unto thy great Name,`" in the midst of this people?

I did attend the Morning Meeting under fearful and deeply exercising feelings,
and was enabled to lay down a heavy burden in a searching testimony.
I trust, with thee, that the Great Hand is laid upon some, however hidden,
to prepare them as standard-bearers, who dare not have recourse to expediency,
but who may be found faithful in the Church;
nobly standing for the honor of truth in their day; for surely this immutable,
eternal truth, must prevail over all error.

Farewell, my loved friend.
We seem hastening toward the period when, I humbly trust,
faith and hope will be consummated,
and joy unspeakable and uninterrupted be our blessed portion forever,
through matchless and adorable mercy.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Hereford, Fourth Month 20th, 1840.

The public assembly in the evening was large, and truth was largely set forth; yet,
while sensible of being clothed with its authority,
I found myself among those who were much unacquainted
with the operations of the power in themselves,
and whose attention was too easily diverted from
what was going forth to them in the love of the Gospel;
so that I had to put them in mind of the importance of my visit to Hereford,
both as regarded myself, and those who heard me.
It was on the whole, however, an impressive, solemn time.
The meeting with Friends in the morning was favored, and an awakening season.
I sat during my communication in that opportunity, but was able to stand in the evening,
for which I was made thankful.
On the whole my health is improved, and I may acknowledge to much peace,
in laboring according to the ability granted;
so that there is encouragement to bear all things,
and to be given up to the Divine will invariably.

Having seen Friends collectively at the General Meeting seems an abundant relief,
for my way was largely opened to lay down my burden there,
and I understand it was an uncommonly full attendance from all parts.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fifth Month 6th, 1840.

Bitter indeed are those feelings with which we mourn over what is without remedy;
thinking, that were it possible to recal past scenes and occurrences,
we would gladly act a somewhat different part from what we now reflect on.
Oh!
I am one who can adopt the above expressions from painful experience;
yet is there a balm for our wounded spirits--oh wonderful!
the matchless love of Him who took upon Him our nature;
who Himself was blameless.
This love is the healing balm,
for He takes upon Himself that which would be too much for us to bear.
Let us therefore try to lean upon Him, and repose our agonized spirits in His holy bosom.
