[quote.epigraph, , Hebrews 11:4]
____
She, being dead, yet speaks.
____

== Preface.

In committing to the press the following pages,
it was not our intention to have preceded them by any remarks of our own.
Circumstances have, however, arisen, which call for a few words from us as compilers.

We find that an apprehension prevails with some friends,
that our mother destroyed her papers shortly before her death,
and left an injunction that nothing should be published respecting her.
We believe this report to be without foundation,
and a portion of the present volume was carefully preserved by herself,
and endorsed in her own hand-writing.
When about thirty-two or thirty-three years of age,
she destroyed some journals which she had previously kept,
and never resumed the practice.
She also strongly objected to any testimony concerning
her being prepared in the usual way,
from a fear of the exaltation of the creature,
and a belief that these documents often had that tendency;
but we think it will be seen that the same objection does
not apply to the publication of what came from her own pen.

The materials which fell into our hands appeared so very valuable and instructive,
that it became a question whether we ought to take upon ourselves
the responsibility of withholding them from our friends;
and on serious consideration, it was felt to be a duty to give them publicity.

In the somewhat difficult work of selection,
it has not been easy always to avoid repetition,
without injury to the meaning intended to be conveyed;
but we have endeavoured faithfully to perform our task--to
do justice to the memory and character of the writer,
and to the principles of the Society of which she was a member;
and we believe that the work will be acceptable to those who truly value these principles,
and who desire that they may still be maintained in their ancient purity.

[.signed-section-signature]
J+++.+++ Grubb.

[.signed-section-signature]
H+++.+++ Grubb.

[.signed-section-context-close]
Sudbury, 11th Month, 1848.

[.asterism]
'''

[.centered]
=== Minute of Bury Monthly Meeting.

_A Minister deceased.
Sarah Grubb, of Sudbury, widow of the late John Grubb, aged about sixty-nine years,
a Minister fifty-two years; who died the 16th day of Third Month, 1842,
and was interred in Friends`' Burial Ground, at Sudbury, the 23rd of the same._

_While we deeply feel the loss of this faithful and
long devoted servant of her great Lord and Master,
we think it right, in accordance with her own expressed desire,
to refrain from issuing any testimony respecting her;
desiring we may be instructed by this evidence of her deep and
unabated concern that no honour might be given to the creature,
but that all the honour and the praise might be ascribed to that Power,
whereby alone she was what she was._

[.signed-section-signature]
Wm. D. King, Clerk.
