[#children, short="Address to Her Children"]
== An Address to her Children Written at Several Different Periods.

Stoke Newington, 28th of 12th Month, 1832.

My Dearly Beloved Children,

Being now in the sixtieth year of my age,
and not knowing how long it may please Infinite Wisdom
to leave the ability for employ of this kind,
I embrace the present time to commit to writing some short account of my past life;
hoping the perusal of it may be blessed to you.

I was born at Wapping, London, in the year 1773.
My father`'s name was Mason Lynes; he was, by trade, a block and mast maker.
My mother`'s name was Hannah Holdway.
I have been informed that they both came of respectable
families in the middle class of community,
and were each favored to experience something of vital religion.
My dear mother has spoken to me of the tenderness of my father`'s conscience,
and of the day of Divine visitation to her own soul in early life.
She was a beautiful person, and much admired when young;
but could not see her way to enter the married state,
until she had an offer of the hand of the plain, simple-hearted Mason Lynes.
She has related to me an instance of my father`'s sense of religious duty,
as being worthy the first attention.
Having some urgent business on board a vessel lying in the river,
that was to sail at a certain time,
he allowed some work to be done on the First day of the week, which I understand,
cost him many weeks of bitter remorse.
He was in great repute for upright dealing; and being of industrious habits,
had realized some property,
when it pleased the Lord to call him from every worldly pursuit,
and every tender tie in nature, to a fixed state of existence in the world of spirits.
Those who best knew him, and witnessed his departure,
were comforted in the persuasion that an entrance into the everlasting
kingdom of God was abundantly ministered to him,
through redeeming love and mercy, which is in Christ Jesus our Lord.
I well remember his taking a final leave of his seven children, one by one.
While he labored hard for breath, he counselled us severally to fear and love God.
I was then about six years old.

Two years after this solemn and deeply affecting event,
the three youngest of us were placed at "`Friends`' School,`" Islington,
or then Clerkenwell.
The change was severely felt by us who had come from every comfort,
to endure sore privations;
but our heavenly Father blessed all to my mind--even He who had
visited me by His love when not more than five years old;
so that I delighted then in the "`Divine Songs`" of Watts,
which an amiable elder sister had made me acquainted with,
at that early period of my life.

At school I sought the Lord;
feeling His power in my heart operating against the evil propensities of my nature;
yet to these corrupt inclinations I many, many times gave way;
and for this I was brought under great condemnation,
even as early as when nine years old; so that I bemoaned my condition,
and have begged and prayed at that period, for a better state and a happier.
I went on sinning and repenting for years; still my love for good books increased,
and for good people.
We had few books.
The Bible, and one or two journals of Friends, are all that I can recollect reading;
and I really valued them as highly as I was capable of doing in this my childhood.
When I grew to about thirteen years of age, I began to discover something about me,
or in my mind, like the heavenly anointing for the ministry;
for the Lord had revealed His word as a hammer,
and had broken the rock in pieces in my living experience;
and I was contrited under a sense of power and love; saying even vocally, when alone,
"`Lord, make me a chosen vessel unto You!`"
I could even then utter good things,
and have done so to my schoolfellows in select companies;
and once I saw several in tears while I spoke to them.
I was not, however, sensible of a Divine requiring to do as I then did.

Soon after I was fourteen years old,
a friend from Ireland took me into her family to attend her children, who were young,
there being four of them.
This situation was as a fresh ordeal to me.

At one time I wrote thus--

"`3rd of 6th Month, 1791.--Oh the deep distress and sore anguish of soul which I now feel!
It is beyond expression; yet, out of the depth of my tribulation,
have I been permitted this morning to cry unto the depth of His mercies,
whose compassions fail not.
Oh! there is something in me which perhaps is not of His pure Spirit;
that wishes it might please Him to cut the thread of my life,
or that I might go into some solitary place, where I might mourn and none know it.
But I find another language, peradventure more profitable to attend to,
'`Is this keeping the word of my patience?`'`"

I was then eighteen years old; had come forth as a minister,
yet discovered great need of further refinement,
both for my own acceptance with the Lord, and that I might be fit for the Lord`'s use.
Truly I had to abide the fiery furnace.

With respect to my first appearances as one called
to speak in the high and holy name of the Lord,
they were in great fear,
and under a feeling that my natural inclination would not lead me into such exposure,
for I shrunk from it exceedingly; and often have I hesitated,
and felt such a reluctance to it,
that I have allowed the meeting to break up without my having made the sacrifice: yes,
when the word of life, in a few words, was like a fire within me.
Great has been my mourning through these omissions of duty,
although but seventeen years old when I first gave
utterance publicly to a sentence or two;
and I had opened my mouth in private many months previously,
under the constraining influence of the Spirit of truth;
being without the shadow of a doubt that it was indeed required of me,
poor child as I was.
I had sweet consolation in coming into obedience;
and after a while was surprised to find,
that although I stood up in meetings expecting only to utter a little matter,
more passed through me, I scarcely knew how.

Thus the gift grew, and much baptism and suffering was my portion from time to time:
the great work of my salvation and sanctification going on,
while I was occasionally induced to invite others to the needful
acquaintance with Him who came to redeem us from all iniquity.
I have never known an easier way to favor with the Lord of life and glory,
than that of passive submission to all His holy will concerning me,
even under dispensations most proving and mortifying to the fleshly mind.

I lived nearly ten years in the family to which I went from school, namely,
that of Sarah Grubb, of Anner Mills, near Clonmel, Ireland.
Never, all that time, could I see my way to change my situation; for,
through all the difficulty that lay in my way of fulfilling my religious duty,
I believed that the Great Master had some good end which He designed to answer,
in permitting me to be as it were cramped in the
gift dispensed to me as a minister of Christ;
and my faith was at times renewed and confirmed,
that if I would patiently endure to the end, my reward would be sure.
Thus I was mercifully enabled to "`wait all the days
of my appointed time until my change came;`" until,
in the clear openings of truth, I was led back to my native land, to my near relatives,
and sent forth largely to publish the glad tidings of the Gospel.
I had been some journeys while a servant in Ireland,
but now a very wide field of labour opened before me; and,
with the consent of my Monthly Meeting, I travelled much, up and down in England,
both among Friends and others, for some successive years;
and many blessed and powerful meetings we had, to the praise of His excellent Name,
without whom we can do nothing, and are nothing.
For some considerable time I was joined by my beloved friend Ann Baker,
daughter of Samuel Baker of Birmingham, and afterwards wife to Stanley Pumphrey,
of Worcester.
We passed through tribulation together, which, as well as experiencing some rejoicings,
had a strong tendency to unite us in true sisterly love and friendship;
and in it we were preserved to the end of her course,
which was finished with holy triumph many years since.
Neither has death itself dissolved the heavenly bond by which our spirits were united;
even in that which outlives all probation.

It pleased the Lord to call me into a path much untrodden,
in my early travels as a messenger of the Gospel; having to go into markets,
and to declare the truth in the streets.
This sore exercise began in Cork, Ireland;
but it was only in one instance required of me in that nation: in England, however, many,
very many such sacrifices I had to make in pursuit of peace;
and in pure obedience to the will of my Heavenly Father I gave up.
No one knows the depth of my sufferings, and the mortifying, yes,
crucifying of my own will, which I had to endure in this service;
yet I have to acknowledge to the sufficiency of Divine grace herein.
Many times I had brave opportunities on these occasions,
to invite the people to the Lord Jesus Christ,
who manifests Himself in the conscience as a light,
and who would discover the evil of covetousness and of all unrighteousness;
leading and teaching "`to do justly, to love mercy, and to walk humbly with God.`"
Hundreds, possibly thousands, who would not, even though requested,
come to meet us in a house, or place of worship,
have thus felt the power of the living God,
in hearing tell that He rewards every man according to his ways,
and according to the fruit of his doings.
In some instances we were rudely treated.
Once in a great town (Leicester) while I was speaking in the market,
there came two men who looked really furious.
They said the mayor ordered me down; coming toward me through the crowd that stood round,
evidently intending to pull me down from where I stood; but I observed them,
and looking at them, their countenances fell,
and they appeared to have no power to touch me: however,
as they came with an order from the mayor of the town, I told the people how it was,
and commended them to their inward Teacher--Christ.
When we obeyed the order, and were leaving the place, some said,
had it been a mountebank who stood in my place, he would have been allowed to proceed;
but that which drew their attention to God was prohibited.
Others who were light and wicked, reviled us.
I had, as usual, some dear and tender friends among the brethren,
who accompanied and stood by me in such great exercise.
These partook of the insults offered--the people throwing at them:
indeed somebody was unfeeling enough to bring hot melted lead and cast at us;
some of which was found on some part of the clothing of one dear friend.
I retired to my chamber at a friend`'s house, after this bustle;
and oh the sweet tranquillity that filled my mind!
I thought it a foretaste of that glorious rest prepared
for the children of God in His eternal kingdom.

At Durham a clergyman came in a rage, while I was preaching in a market place,
wanting some of the people to hale me away; but they took little or no notice of him,
and he passed on.
Next day we appointed a meeting for First day morning, in a hired room in this dark town;
and, as was usual, posted up notices.
These were torn down, and we were informed, that if we held the meeting,
we should be heavily fined.
The meeting was nevertheless held, and owned by the great Head of His own Church.
At the close another was appointed for the evening of the same day,
and a large heavenly meeting it was.
We tarried there all that night, but heard no more of the threatened fine.
This was but one of several visits to Durham.
It is not my intention, in writing a narrative,
to enter much into detail of my journeyings from place to place,
but to leave my dear children some testimony to the sufficiency
of that Name in which we are called to confide,
and to encourage to come up in faithfulness to all truth`'s requirings.

Once, when young in the ministry, being at an inn with the family with whom I lived,
I heard one of them say she had placed a handkerchief in one of the chambers;
and on going to fetch it, could not find it.
Immediately my mind was impressed with a sense that
a young girl whom I had seen in the house,
had stolen the handkerchief.
I was astonished at my conviction of this fact,
for I had by no means a disposition to suspect any one of evil.
It was not, however, to be suppressed;
for I saw with clearness she had committed the theft:
what showed it me was the light of the Lord, which came like lightning into my mind.
I ran to enquire for the girl, who came, not knowing my business with her.
I looked at her, and in the fear of the Lord told her she had stolen the handkerchief,
which she dared not deny, and it was produced.
Then I spoke to her; the power of the Lord accompanying what I said,
in a wonderful manner, the girl turned very pale, almost like a corpse.
I continued to declare of the exceeding sinfulness of sin,
and to warn the young creature for perhaps twenty minutes.
While the Lord`'s word was passing through me,
a servant was cleaning the floor of the room where we stood;
one apparently of the very lowest of her class.
She felt so struck by the authority with which the communication was attended,
that she raised her hands with astonishment.
The mother of the young girl came to me before we left the inn,
and asked me how I could tell that her daughter had taken and concealed the handkerchief;
to which I replied,
that I was made acquainted with it from a sense given me by the Spirit of truth in my
own mind--the anointing which could not only give me to be without doubt in this thing,
but also did influence all that take heed to it, so as to lead them out of sin,
and bring them to live godly lives.
I told her she had this gift of God in herself; that all the children of men had it,
or a measure of it; and warned her to take heed to it.
I understood they were all Papists who heard me speak.
After this was over, and we passed away from the place,
I was so overcome with what had occurred, that I could not refrain from many tears.

Another time in my life have I been alike filled with the
mighty power of the Lord in the sacred work of the ministry.
These two instances were extraordinary.
The second was in the case of a member of our Society, a high professor,
but who was of a contentions spirit.
It came upon me to set before him his corrupt and dark state,
and to warn him of the day of the Lord who searches all hearts;
that if he did not speedily repent, and humble himself as in the dust,
this day would overtake him, bring him down, and he would come to nothing.
I was engaged to keep my eye upon him,
while thus addressing him in the dread of the Most High:
he attempted to look at me once or twice in defiance, but he could not hold up his head,
nor oppose the power: he grew quite pale, and was some time silent,
as we sat together after.
When, however, we were about to separate, he began to rail against me for what I had said.
His words seemed but as chaff before the wind.^
footnote:[This man, in a few years, came to nothing.
And though then he had a grand house, and kept his chariot, he lost all his property,
and is at this day supported by others.]
After this also, my bodily powers seemed so shaken, that I was quite weak,
and obliged to lie down for a while.
Thus did it please Infinite Wisdom to show forth
His own mighty power through a mere nothing.

Another remarkable exercise I had,
which lay as a perpetual burden on my mind for one whole year.
It was to go, on the day called Christmas Day,
into the great cathedral called St. Paul`'s, in London.
Shortly before the time arrived, I acquainted some friends with my concern.
They did, I believe, tenderly sympathize with me; and having been engaged,
for some time previously, visiting in the City, both Friends and others,
in company with two friends, they both felt much for me, and one offered to accompany me.
About the time the people were to assemble, we two women went into the worship house;
taking our places in a gallery not far from the pulpit.
The bishop preached.
There did not appear to be a large congregation:
they gave marked attention while this man repeated something called a sermon;
it was not long.
He then immediately kneeled, and uttered words in the form of prayer;
but I may acknowledge I was not prepared to witness anything
so dry and formal as his communications were altogether.
It seemed to me like nothing more than the mere repetition of words,
devoid of all that could render them impressive to the hearers.
No sooner had the bishop risen from his knees, than he retired without sitting down,
or looking at the people:
his attendants seemed to be in waiting at the door of the vestry room, as I supposed.

Now while the bishop was withdrawing, I asked, in a loud voice, if the service was over.
This I repeated, expecting an answer;
but two of the officers of the place came and led me away
(my companion following) toward the large entrance,
where the people rushed after us to gratify their curiosity,
while the men told us we must depart, and not speak there: however,
I turned from the great door, and addressed the audience for a short time,
to the relief of my own mind: indeed,
for this act of dedication in giving up to so singular a thing,
I was favored with a time of the flowings of sweet peace in my
own soul--that which the world can neither give nor take away.
When we met my endeared friend J. G. Bevan, who was anxiously waiting for us outside,
I felt inexpressible joy, in which I believe he partook.
My heavy burden was laid down, and I was like another person.
At least for twelve months had this matter occasioned me to go bowed down,
although I was mostly engaged traveling in the work of the ministry.
I did not consider that in this instance of obedience,
the way opened for enlargement in preaching the true Teacher,
Christ Jesus--the everlasting Bishop of souls;
but then I was favored with a belief that the acceptance stood in the obedience,
and my soul blessed and praised the Lord.

Various have been the peculiar calls to religious duty,
of which my mind from time to time has been made sensible;
once having to walk through Worcester streets, and to speak in the markets there.
As I passed along I was drawn to address a recruiting sergeant who was near me:
I spoke to him in the dread of the Most High, and had to allude to his employ.
At first he seemed ready to be scornful, but as I proceeded, he changed countenance;
looking pale, and held down his head, not answering a word.
The like has occurred with others.
At another town in particular, I recollect seeing a young woman under a gateway;
I think it was at Carlisle.
She was conversing with a man who stood by.
My mind was arrested with a belief that I ought to
warn her of the awful consequences of sin,
and to turn her to that of her Savior in her own heart, that would lead from,
and redeem out of all iniquity.
She listened without any reply; looking as if she would have fainted:
the man also waiting to hear me out.
Children and young lads who would follow us from place to place in a town,
have often been overawed in my turning to them,
and charging them to love and fear their God.

At Bath I had to go to the Pump Room,
and declare the truth to the gay people who resorted there.
This was a time very relieving to my sorely exercised mind.
In these days and years of my life, I was seldom from under some heavy burden;
so that I went greatly bowed down; sometimes ready to say, "`If it be thus with me,
oh You who have given me a being, I pray You take away my life from me.`"
At length I saw to the end of this trying dispensation.
I saw clearly that it was fulfilled,
like other dispensations that had been allotted me in inscrutable wisdom,
and which all have had a tendency to "`crucify the flesh,
with the affections and lusts;`" even bringing into a disposition
to "`bear about in the body the dying of the Lord Jesus,
that the life also of Jesus might be made manifest in our body.`"
Oh! it is good to say amen to the whole will of God concerning us:
to be patient when brought to a low estate, and "`make not haste in time of trouble.`"

In the year 1801 I wrote thus:--"`Oh! my Heavenly Father,
You have seen me in the depth of tribulation, in my many journeyings and travails.
When, in obedience to the holy leadings of your Spirit, I went forth,
You did take cognizance of me: when I felt the woes of the wicked,
when I passed by the gates of death.
It was your power which supported me when no flesh could help;
when man could not comprehend the depth of my exercise.
Without You I could not have gone, bearing my cross, into the public streets,
into the hurrying markets;
warning the people of your justice in '`rewarding every man according to his works,
and according to the fruit of his doings:`' inviting all to love and fear your great,
your holy Name.
By You have my feet entered the prison-houses, and my tongue declared of your goodness:
holding forth the invitation to be acquainted with You in your Christ,
and be set free from the bondage of corruption:
to come from under the law of sin and death, into the glorious liberty of your Gospel.
You have many, many times led me into the sick ward, unto the bed of languishing,
and unto the rolling pillow.
You have given me to minister of your word to the afflicted,
and to put my soul in their soul`'s stead, in some degree.
You have enabled me to lift up my voice as a trumpet, not only to your gathered Church,
but as it were to Jews and Gentiles.
Without You, oh You fulness of strength, I am less than the worm of the dust.
May You only be forever exalted in, by, and through your poor child;
and let nothing be able to pluck me out of your hand.
Amen.`"

I am far from acknowledging myself to have been without unwatchfulness,
even while preaching to others.
Often, very often, have I mourned over my frail erring nature;
and bitter anguish has at times taken hold upon me,
in a sight and sense of my wretchedness without my Savior.
Yes, to this day do I find shame and confusion cover me,
because of my lack of strict adherence to the all-preserving principle of Divine grace.
In it lies our sufficiency, as certainly as was the case with any in any age;
for it is the manifestation of Christ Jesus the Lord, who came in the flesh,
and is come in the spirit, to save us from our sins.
There have been seasons mercifully afforded me, notwithstanding all that I deplore,
when an evidence has been granted that my past sins were remitted,
and that He who had brought my soul through tribulation,
had also washed me with the water of regeneration,
and purged me from my iniquities in His own blood, of His own free mercy;
to whom be ascribed salvation and glory, now and forever, Amen.
And oh that I may be vigilant--that I may be kept low in the fear of the Most High;
"`lest, when I have preached to others, I myself should be a cast-away.`"

In the year 1803 I was united in marriage to your dear father.
After leaving Anner Mills, and while on board ship, crossing to England,
a secret caution seemed given me, to beware how I listened to any proposals of this kind.
And although it was my lot to be tried therewith in more than one instance,
in this my native country,
I was kept from encouraging the thing (there being a lack of clearness
in my mind respecting it) until the fulness of time came,
that your beloved father and myself were to enter
into the solemn covenant with each other,
to share the toils and joys of life together.
Oh I have no doubt, not the least,
that Divine Wisdom pointed out the suitableness and propriety of our becoming each other`'s;
and He has been with us from time to time, through all the vicissitudes experienced.
Yes, in blessing He has blessed us, and rendered us a blessing to each other.
He has enabled us to go, as it were, hand in hand, while pursuing the path cast up for us.
He has been graciously pleased to sustain us in many trials;
evidencing that He knew our souls in adversity, and, in His own time,
has brought deliverance.
May His works praise Him still, even by and through His unworthy children!

The tribulations attendant on illness, and twice that of death, have been heavy.
In one of my long fits of illness,
and while several of our household were visited with indisposition,
my dear husband and I held certificates for travelling.
Great, truly great, was the trial of my faith;
and much did I seek to commit all into the Divine hand, again and again.
At length, while yet confined (I think) wholly to bed,
my soul distinctly heard the voice of its Well-beloved,
saying in the very language of Scripture, "`Rise up, my love, my fair one, and come away.
For, lo, the winter is past, the rain is over and gone; the flowers appear on the earth;
the time of the singing of birds is come,
and the voice of the turtle is heard in our land.`"
Oh! my mind was prepared to understand and receive this gracious answer to all my prayers,
my sighs, and my groans.
I saw indeed that of myself I was vile; but He who, to me, was the chief of ten thousand,
had again and again washed me in His own blood;
and I found my spirit united to Him in the covenant of His own life,
in which I bowed my heart and gave thanks.
From this time I rapidly mended in health; and before long,
we left home to accomplish the service of the Gospel before us.

We have seldom been easy to stay at home more than a few months at a time,
even since it has pleased the Almighty to vouchsafe to us our precious offspring.
When nursing you, I was led to engagements in the ministry around our dwelling;
and when my loved babe, my first-born, was but eight months old,
I left her for five months, to travel in Ireland, Scotland, and England;
my dear husband accompanying me.
This, and many such sacrifices, have cost my nature much suffering;
but I have apprehended them called for,
as the first-fruits of all bestowed upon us by our bountiful Creator.

In 1818 I wrote as follows:--

"`Clonmel, 25th of 6th Month.--Having for some years believed that the Lord,
who has a right to dispose of us as He sees fit,
was drawing my mind to a residence in England;
and being aware of the very great importance of such a step,
many and deep have been my conflicts,
and great the searching of heart to know that the
call was indeed in that which cannot err.
I acquainted my dear companion in life from time to time with my views;
and knowing that I was much pressed down by the weight of this concern,
and being himself truly desirous of following the leadings of truth,
he surmounted the great difficulty of bringing his
mind to consent to go out from his native country,
and from his kindred, and to leave also his business and property,
and to live away from it, where he possessed nothing, but must draw his outward support,
from time to time, for himself and family, from his own land; being resigned to all this,
and to the very great reluctance of friends to part with us.
We acquainted our Monthly Select Meeting with what lay upon our minds,
in the 3rd month last.
From them we met with much discouragement,
and continue to meet with it from all but a very few, who, in this thing,
are enabled to look beyond '`things that are seen, and are temporal,
to those that are not seen,
and are eternal.`' My beloved husband is favored with a sense that it is right to go;
and there seems no reason for us to be greatly moved, or to draw back.
We are not likely, in removing, to promote our worldly interest,
but are brought to a willingness to give up all to the Lord.
He can bless the little, or cause a blast to come upon that which is more.
The opposition we meet with is like a host: our friends find it hard to let us go,
and many reason strongly against it; which if we had done,
we should not have mentioned it to them.
I see plainly, that should we be led forth from this place,
it must indeed be by a patient reliance on the strong hand,
and the outstretched arm of Him who is mighty, and has already done for us great things.
My beloved J. G. had, some weeks back, to supplicate the Great Name in a remarkable line,
and with great solemnity, that He would make our way,
and enable us to erect an altar to His wonderful and excellent Name,
where He might appoint.

"`28th of 6th Month.--Many times of late,
have I thought on the dear Redeemer`'s condescending goodness and mercy,
in enduring temptation for our sakes.
It is an unspeakable consolation that we have Him, the great High Priest,
to look to in all our trials;
who being Himself '`touched with a feeling of our infirmities,`'
knows how to succour us in our greatest temptations.
Oh Lord keep me, I beseech You, low in your fear.

"`5th of 7th Month.--Some among us have given me plainly to understand,
that they believe me to be under a delusion with respect to the
prospect of removing with our family from this place to England.
How then is it, that while this concern was ripening, it pleased the Lord to be with me;
to send me forth in His name through this nation;
to grant the living and blessed authority of His Spirit in declaring the truth?
Yes, even just before disclosing my views, how did I go in His fear,
and visit the meetings in this province of Munster: the humbling,
baptizing power of truth being, from place to place, in blessed dominion;
so that several felt it like a farewell visit,
and some said they believed the Great Master was about to remove me,
at least for a while, from this Quarterly Meeting.
I was truly of their opinion, and strengthened in my views as to leaving Ireland.
After a painful interview with some friends on this subject,
my dear husband had it from the Lord,
to encourage me to attend to the pure openings of truth; saying,
'`Your God whom you serve continually, He will deliver you.`' Even now,
under all I have to bear, I find that the name of the Lord is a strong tower,
where my soul finds refuge.
Were it not so, how could I adopt the language as I do, '`Cast down,
but not destroyed`' etc.? Indeed I have lately felt,
that were it not for the invincible fortress which
is open to the oppressed and bowed down,
I must have been destroyed by that which is without.
Blessed be Jehovah, the Lord of Hosts; and blessed be my Rock and my Redeemer!
Ah! He knows the simplicity with which He enabled me to look to Him in this great exercise;
and to Him I appeal, who knows that I have no motive in wishing to remove from this land,
but to follow His holy leadings, to act in His counsel,
and to prosecute my day`'s work in His fear.

"`9th of 7th Month.--I assuredly believe, that as I look to Him who is almighty,
He will yet raise me up out of my present depressed condition;
that He will give me to see that all things work together
for good to those who love Him with the whole heart;
for in my measure '`I am persuaded that neither death, nor life, nor angels,
nor principalities, nor powers, nor things present, nor things to come, nor height,
nor depth, nor any other creature,
shall be able to separate`' His dedicated children from His love '`in Christ
Jesus our Lord;`' who encouraged His disciples in the language of,
'`Be of good cheer,
I have overcome the world.`' It is certainly trying
to be suspected of having self-gratification in view,
by professing a call to England; but I am made willing to suffer reproach,
and to pass through evil report, for the sake of a good conscience.
Had I anything in pursuit but the will of my Heavenly Father,
how could I hope to be supported, or look for the divine blessing,
which is only to be found in our right allotment?
How could I again expect the protection of the Good
Shepherd for myself and my dear family?
I should surely be most ungrateful,
were I to presume to take us all from the situation in which
Divine Providence placed me fifteen years ago,
which is as in a '`south land;`' and where I have found
also '`springs of water:`' where I have been every way prosperous;
the Great Disposer of events bringing about that
which I long foresaw to be His gracious design;
even uniting me, in the most endearing earthly bond,
with one who has ever been a man of clean hands,
and among the faithful has stood with singular uprightness.

"`16th of 7th Month.--Again and again have we looked toward complying
with the earnest desire of our friends to remain where we are;
but finding no light upon it, nor feeling any rest therein,
we have concluded to give up all, and obey our Divine Master;
and forthwith intend to prepare ourselves and our family for the journey.
We are not without the unity and tender sympathy of a few unbiased minds,
which proves strengthening and consoling.

"`6th of 9th Month, 1818.--We had a heart-contriting farewell meeting on the First day,
consisting of Friends of our Monthly Meeting,
including Clonmel and Garryroan particular meetings.
All opposition appeared to me to give way in the minds of those present,
who before were much against our leaving them;
but truly the Lord`'s everlasting power was in dominion.`"

We left Clonmel the 9th of 9th Month, 1818, for Bury, in Suffolk;
for to this place my inward eye was directed, although I knew not why.
It was only while pursuing our journey that we either heard of,
or had liberty to make much enquiry for a habitation.
We arrived there the 10th of 10th Month, with peaceful feelings.
Our habitation was very inferior to that which my husband had built for us in Ireland,
and which we had just left;
but I may gratefully acknowledge that I believe this quiet spot,
with the fine bracing air of the place,
had a great use in strengthening the constitution,
both of my beloved husband and our children.
The meeting was small to which we now came to belong; we were, however,
but little at home; that is,
my husband and I--still it was our lot to travel in the work of the Gospel.

I wish to narrate an illness I had some years ago,
which was attended with great bodily suffering; and it being tedious,
brought me very low.
The pain I endured was excruciating.
Tedious days and wearisome nights were appointed me for weeks together; and for a season,
I thought that my sufferings would terminate in death.
I earnestly waited upon the Lord, and it was frequently the language of my heart,
"`Oh! my Heavenly Father, when will You be pleased to send forth your word and say,
'`It is enough?`'`" Being under a great weight of illness,
and looking toward dissolution,
I was opened into a view of the love of my gracious Savior toward my soul;
feeling assured that nothing stood in my way of acceptance
with the Judge of quick and dead.
I saw clearly that my transgressions were forgiven;
that all defilement was purged away in that living, blessed "`fountain,
opened to the house of David, and to the inhabitants of Jerusalem.`"
I had a degree of foretaste of eternal glory: I saw the light of heaven: I beheld,
as "`through a glass darkly,`" something of His majesty who sits upon the throne,
and the ineffable brightness of those garments worn by the redeemed.
I had no doubt of being admitted to their blessed company,
should it please Divine Wisdom to cut the thread of my life.
I relate this with reverent humility,
and in the unreserved acknowledgment that I felt assured,
if presented faultless before the throne of my Savior`'s glory,
it would all be of His free mercy and infinite lovingkindness
to one of the least of His family.
I think it was given me to say, "`Not my will, but Yours be done.`"
As to the restoration of the poor afflicted frame, I did, however,
find myself much exercised about my loved family;
and one morning I was engaged to petition that I might be spared to them,
when I became sensible of receiving the earnest of my prayer;
these words being heard in my soul,
"`I will spare you;`" and that scripture occurred to remembrance which tells us,
that when Jacob had made an end of blessing or commanding his children,
he gathered up his feet in the bed, and gave up the ghost.
I believed that I might yet be of use to my beloved family in the Divine ordering.
Immediately I wished to call you and say, "`Your mother lives;
the Lord will raise me up again:`" but such was my weakness,
I could not request to see you.
I was worse after this time than before, yet never wholly lost sight of recovery.
(This illness occurred at Bury in 1820.)

At Bury we resided five years,
when it seemed right to remove nearer to the Quarterly Meeting of London.
Our way opening to take a house at Chelmsford, in Essex,
we settled down there for the space of six years; often going up to London,
and traveling to other parts.

For some time while at Chelmsford,
I had to believe that our lot would one day be cast still nearer to the great metropolis;
and after having Chelmsford for our home as long
as we were sensible of its being our right place,
we removed to Stoke Newington, near London, where we have resided three years.
There seems to be much wisdom in the leadings and
instructions of the Great Shepherd usward.
We have not dared to guide ourselves, nor to conclude,
because we have felt at home for a season,
where Divine Providence has set the bounds of our habitation,
that it was to be our "`certain dwelling place`" to the end of our day,
but have again been made willing, from time to time,
to have our rest in this respect broken up;
which is no pleasant thing to that part that would like to be able to say,
"`take your ease.`"

Now in this place, our dear children know that we have no tie but that of religious duty.
One is settled in life in Suffolk, the county where we were first led from Ireland;
two are in Essex; so that we can still adopt the language,
"`Lo! we have left all and followed You.`"
Oh! our morning light, be pleased to be our evening song.

You are aware, my dear children, that all we have we owe to the Lord.
He was pleased to take back the precious gift of your lovely infant brother,
many years ago.
Your father and I dared not murmur, but pursued diligently the path of duty still.
You are spared to us; yet, for the sake of the answer of a good conscience,
our place of abode is many miles from you all; not one of us repining that so it is,
nor you wishing to hinder us from pursuing the Divine will.
May Almighty kindness be with you;
giving you also to know the voice of the true Shepherd, even Christ;
who does lead His own forth, does go before them, and gives unto them life eternal:
proving, in the blessed experience of His sheep,
that none are able to pluck them out of His holy hand.

In this place, so near the City, we find our exercises and religious duties to fill up;
and it has often appeared remarkable to me, that it was not until,
from the infirmities of age, we became unlikely to travel much,
that our lot was cast in so wide a field of labour as is found here,
within the circuit of a few miles;
where we have many meetings of Friends quite within a ride of a morning: besides which,
we have again and again to hold religious meetings with other people.

In this work we are now engaged.
Many very deep baptisms of spirit does it occasion me,
yet if I may but be found in the divine will, it is enough.
What signify the "`light afflictions which are but for a moment,`" seeing
they are not worthy to be compared with the "`glory`" that shall be revealed?

I may here remark, that from youth to this last stage of life,
I have had but few intimates; and in some of those few, I have been disappointed.
Friendship, true friendship, is indeed a precious thing--a rare gem--hard to find.
It is, however, to be met with here below.
It is unchangeable as the source from which it springs.
Its value is equally known and appreciated in prosperity and in adversity.

Concluded these lines 10th of 1st Month, 1833.

S+++.+++ G.

* * *

"`7th Month, 1834.--For a number of years past it has been my lot to warn friends,
and particularly in the Yearly Meeting in London,
against a spirit of subtlety that would draw us from an
attention to the inward manifestation of our blessed Savior,
the Lord Jesus Christ;
for I have long seen that some of those most prominent
and influential characters among us,
never have been altogether of the Lord`'s own forming, either as Friends,
or as ministers of Christ: and now many, very many,
have embraced something short of Him who remains to be the fulness,
and are settling on the surface of things--building on the sand;
highly extolling in words, the "`One Offering,`" which, indeed,
is to be appreciated with feelings of adoration and heartfelt gratitude;
but these know not of what they speak,
while they preach up a literal faith in Christ crucified,
and endeavor to bring people from a pure dependence
on the leadings and unfoldings of the Spirit of Christ,
or the inward and heartfelt power and coming of Christ within, the hope of glory.
Many ministers of our Society are sliding,
and others are already gone from that which first called them to the preparation,
and then did really bring them into the sacred office:
much of this is to be traced to their adopting the
views and sentiments of those mentioned above,
who never wholly left their own works,
but have sought to bring all things to the test of reason,
instead of to that "`Spirit which searches all things, even the deep things of God.`"

Oh that my dear children may walk in humility and fear before the Lord, in this evil day;
that they may be sheltered from all that is airy and notional in religion,
being covered with the Almighty wing; for it is written,
"`He shall cover you with His feathers.`"

During the Yearly Meeting this spring, great was the exercise and travail of my soul,
which produced the following effusions in my pocket-book.

"`1834.--After the third sitting of the Yearly Meeting.
The appearance of things among us is very specious;
an exact resemblance of what should be known, felt,
and evidenced in the Church of Christ, through His own power, who is the second Adam,
the Lord from heaven--the quickening Spirit;
but the absence of this quickening Spirit is, in my apprehension,
mournfully and oppressively felt,
while '`Mystery Babylon`' mimics it in various ways--in language, in orthodox sermons,
in dissimulation of love, in solemn silence, not the solemnity of the Lord`'s own power.
We have a zeal among us which draws from the influence and
motions of the inward anointing into creaturely activity;
and we are so blind, in many instances, as to mistake Babylon`'s streams,
where go the '`gallant ships,
and the galleys with oars`' for the '`place of broad
rivers and streams,`' where none of these are found.
Our predecessors suffered much in avowing the leadings of the Spirit of truth,
which brought them away from all will-worship; shall we, with impunity,
trample upon the testimonies of the everlasting Gospel,
which they embraced at the risk of the loss of property, personal liberty,
and life itself; and which they maintained through the hottest persecution?
Our Society has thus stood on higher ground than any of those around;
shall we descend to the level of things in the religious world (at large)?
Or shall we profess more full light on the truths of the Gospel than was their experience,
and so deceive ourselves?
Surely they did come to the meridian brightness of
this last and most glorious day and dispensation,
and to the summit of that '`holy mountain,
where nothing shall hurt nor destroy;`' and unto which '`all nations`' of the
earth '`shall flow.`' With all the prying wisdom of this present age,
we shall find nothing beyond what these dear servants
of the Lord were privileged to obtain.
Oh that, by full dedication of heart to the Most High,
we may be found in their footsteps;
even in the narrow way that leads to '`life everlasting.`' Amen.`"

"`19th of 11th Month, 1838.--My dear children will be aware,
that since the date of the foregoing,
great have been the shaking and sifting that have come upon us as a Society:
every foundation has been tried,
yet that which cannot be shaken still evidences itself to be the invincible,
eternal Rock, on which Christ Jesus builds "`His Church,
and the gates of hell shall not prevail against it.`"
For years past the mourners in Zion have had to wear sackcloth, and sit on the ground,
with ashes on their heads, except when the Lord has lifted them up,
and clothed them in the beautiful garments,
to show forth His mighty power in and through them.
Some has He made very skilful in lamentation in these days:
He has also given them to be mighty to suffer in His cause,
and He will take the "`cup of trembling`" out of their hand,
placing it in the "`hand of them that afflict them.`"
The Most High is able to put the harp of victory
into the hands of His dear servants and children,
with the song also in their hearts and mouths, "`Great and marvelous are your works,
Lord God Almighty; just and true are your ways, O King of saints.`"
It may be confessed that we are made very desolate as a people,
because we changed our glory for that which has not profited us;
and in a Society capacity, have turned judgment backward;
sanctioning publications and ministry which are not in accordance with
the true doctrines of the unchangeable Gospel of our Lord Jesus Christ;
and which, therefore, the few among us who have stood fast in the Lord cannot own:
the heavenly anointing and blessed harmony of truth not being in these things,
but wisdom of words substituted and held up.

Thus have we been in a worse condition, as I apprehend, than in former trials;
because the body did not then become responsible, by its acts,
for that which is out of the true unity, and the wisdom from above.
And now it seems to me that the Lord`'s power and the Lord`'s wisdom have so far prevailed,
as to lay low the Philistine nature--prostrating it on the ground in great measure,
and scattering that which sought to lay waste the inheritance of the Mighty One of Israel:
yes, and that head will soon be cut off, that reared itself on high;
but we must come clean out from all that opposes itself to the simplicity, the purity,
the wisdom, and the power which is forever and ever.
I believe the great Head of the Church will purify His people--not cut them off in anger;
and that the "`remnant of Jacob shall be as a dew`" from Him,
"`in the midst of many people.`"
Blessed be His adorable name!

S+++.+++ G.

+++[+++The following prayer was found detached from the above manuscript,
and probably was written at Chelmsford,
while suffering from a most distressing nervous malady.]

"`Oh!
Lord God Almighty, I have again this day borne testimony to your name, that it is good,
and worthy to be trusted in.
You know that I have done so renewedly, as at other times for many weeks past,
under a load of infirmity which almost overpowers my mind and body.
You know with what difficulty I turn from the suggestions of the enemy,
that I am not able to speak, or to stand;
and that if I attempt to declare anything in our assemblies, I shall be confounded,
and bring dishonor on the ministry of your word.
You have given me to witness him to be a liar,
for your heavenly anointing preserved me while standing in your dread;
and this anointing was in the words, '`Blessed be your name, oh Jehovah!`' And now You,
without whom a sparrow falls not to the ground, oh! if it be consistent with your wisdom,
relieve me of this distressing malady, which destroys all my earthly comforts,
which wastes my strength and flesh,
and which seems to wait to swallow up my life and soul: but it has its bounds set by You,
whose word has said to the proud waves, '`So far shall you come,
and no further.`' My faith is in You, oh Physician of value;
and in your power do I trust.
The sufferings of your poor creature are not hid from You.
Oh speak the word only, and I shall be healed;
or grant me that which is sufficient--even your grace;
that when the moment of deliverance comes,
I may find myself more fully united to You in the eternal covenant of your light,
your life, your love; and that your great name may be exalted over all.
Amen.`"

S+++.+++ G.
