== Chapter 3. Letters from 1797--1798

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Liverpool, Fifth Month 14th, 1797.

We got well here about twelve o`'clock last night; were thirty-six hours at sea.
I was very ill the first day, so that I went to bed,
and stayed till within a few hours of landing; not finding staying on deck would do,
as I have known it before; however, I was better than some others;
almost continually thinking of my dear friends in Ireland, sleeping or waking,
some of you are nearly constantly with me.
I must labour after depth of spirit,
that so the will of my all-wise Creator may be known, and ability felt to obey.
I feel a very poor creature indeed, at present:
my help must be alone in Him who is from everlasting to everlasting.
It is time to go to meeting: this is First day--we did not go to bed till two o`'clock:
we are at R. Benson`'s: their kindness is great.
May you all dearly farewell; and it just arises to you, my dear,
"`Trust in the Lord with all your heart, and lean not unto your own understanding`"

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
London, Sixth Month, 1797.

I feel not satisfied, my dear mistress,
to let your brother leave this city without addressing you again,
if it is only to tell you I continue to love you and yours without dissimulation;
and to add to this, that I am a poor, exercised creature,
sometimes almost ready to style myself forsaken, and grieved in spirit;
less than nothing (I expect you can understand the term) and altogether vanity.
I wish to be preserved from saying,
"`What profit is it unto me that I have walked mournfully before the Lord of Hosts?`"
but the labour is hard, to get to pure unmixed resignation in all things; nevertheless,
surely "`in quietness and confidence`" must be my strength,
if any continues to be revealed, which, in the moment of greatest extremity,
has hitherto mercifully been the case.

I cannot describe what my soul feels for you all separately and together;
please tell the dear children so.
Oh! that I could convey to you the sensations which my mind is sensible of,
in that which, I trust, neither sea nor land can divest us of.
To the all-wise direction and providence of a faithful
Creator and compassionate Father I recommend you,
in tender sympathetic love, which, to the full, cannot thus be set forth.
May we labour after that spirit and power,
whereby we may receive capacity to keep our ranks in righteousness,
and be made perfect in Jesus Christ, the great and holy pattern in all things:
very dearly in Him may you, and may you all, farewell.
Your

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To one of Sarah Grubb`'s Children.

[.signed-section-context-open]
London, Sixth Month 22nd, probably 1797.

[.salutation]
My Dear +++_______+++,

I am much obliged by your intelligent letter.
It is among my little comforts to find A. B., J. J.,
and your dear aunt Margaret occupy with their precious gifts:
tell dear Margaret I love her dearly, and I love all the family.
"`Although the fig-tree shall not blossom, neither shall fruit be in the vines;
the labour of the olive shall fail, and the fields shall yield no food;
the flock shall be cut off from the fold,
and there shall be no herd in the stall,`" yet I most assuredly believe,
they may rejoice in the Lord, and joy in God, who offers to be their salvation.
Oh! that holy preservation may be near to uphold the mind,
that faith may not be shipwrecked in the greatest tossings conceivable.
I love you all dearly:
oh! if I could convey the solicitude I feel in a
peculiar manner for all your spiritual good,
I should not be backward.
May the everlasting Arm be near you all; may He sanctify the exercise begun in yours,
and at times felt also in your dear sisters`' minds, that so, in all,
the seed of His kingdom may so have dominion,
that "`the glory of Lebanon may be given unto it;
the excellency of Carmel and Sharon;`" that things in heaven, things in earth,
and things under the earth, may bow to the name of the child Jesus:
thus I believe you will know His name to be a strong tower; and,
your righteousness being of God, you will flee there,
and find safety amidst your various probations,
even as they may increase for your sanctification.
My heart salutes you individually.
Dearly farewell,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Elizabeth Grubb.

[.signed-section-context-open]
London, Seventh Month, 1797, First Day.

It is in my heart to address you, my dear,
not merely by way of an acknowledgment for your very
acceptable and comfortable letter of 24th ultimo,
neither for one received since from +++_______+++,
for which I feel there is abundant cause to be thankful, seeing that, between you and me,
neither distance nor time, heights nor depths, nor anything else,
has yet broken the fellowship, begotten, I humbly hope,
in the truth of our Holy High Priest,
but I want to give you any comfort or gratification in my power; and this afternoon,
in meeting, you were, for a while, much the companion of my thoughts:
afterwards I forgot you and all things else,
in the pursuit of doing the will of our Heavenly Father;
for when my heart is warmed with holy fire, and the command issued to offer a sacrifice,
I mean of that kind wherein we are obliged to appear
openly in the cause of Him who lives and abides forever,
all outward objects seem to me to vanish, the mind being lost for a time in vision: this,
according to my apprehension, was the case with me this afternoon at the Peel.
You need not suppose that I forget you; no, I remember you at times to my comfort;
desiring also that it may please Infinite Kindness so to preserve,
and even keep as the apple of the eye, that we may be one another`'s joy in Him,
He being our Alpha and Omega.
I believe He designs to bring about in its fulness, in your experience,
that "`the fruits of the Spirit are love, peace, joy in the Holy Spirit;`" and,
by enabling you to pursue the path of holy rectitude,
in Him who never fails to unfold it to the rightly reduced mind,
make you a star shining more and more in the firmament of His power here;
consequently of those who shall everlastingly shine in full lustre hereafter.
He knows the secret exercise of yours and all our minds;
He graciously regards the groans unutterable, and, in His own time, will answer,
if we wait patiently: His reward, then, is found to be with Him, and His work before Him.

I have not been trying to muster up anything of this
kind for you (that would be poor stuff);
my pen can hardly run fast enough for the words, or the matter that arises in my mind:
I long you may not, in any measure,
fall short of the inheritance designed for you to
purchase by an entire submission to the will of God,
only fully known by the mind being centred in Him alone,
and the dependence purely fixed on the revelation of His power in the heart.

All that happens to you or me, in inscrutable, yet unerring wisdom,
must be in order that we may more fully know the habitation of our spirits to be invincible;
that, feeding on the flesh and blood of Christ,
the soul may be nourished up unto eternal life,
and that we may answer the end of our being here.

I doubt not but all you say about Cork is true.
I feel very solicitous at times about many things in Ireland,
and at intervals almost forget I am not there; but again when I look at +++_______+++,
and some other secret exercises about places here,
I awfully remember I am not in Ireland.
Was it not that, in deep conflict, my soul can, through mercy, make the appeal,
that being here was not sought for by me, I should often "`faint in my sighing,
and find no rest,`" when "`grief seems added to my sorrow`" but at this moment,
as well as other times, I feel that there is cause to magnify the Lord,
and rejoice in God my Savior, for He graciously regards my low estate.

Assure dear Hannah, with as much affection as I am capable of,
that I cannot at present think it is the design of the Great Shepherd of His own sheep,
this separation should be without its own peculiar use to us.

_Second Day Night._--Thomas Scattergood has returned from Uxbridge,
where he has been ill of a nervous fever.
This letter was omitted to be sent yesterday, and I have nothing more to say,
save that poor Thomas Scattergood has been very ill all night.
I am just going to meeting; my poor mind, yesterday and today, peculiarly tried;
but unto whom shall we go at such times, but to Him who has the words of eternal life?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Eighth Month 15th, 1797.

I hardly know how to apologise for not writing before,
as I gave my dear +++_______+++ to expect it would be the case after our Monthly Meeting,
which was held last fourth day; and the result of it, with respect to myself,
was to obtain a certificate for some counties in this land,
particularly northward (this is the way it is expressed);
and that day dear Thomas Scattergood came to see me,
took me into a room from the company,
and queried what was to become of the other affair--that of the families in this meeting.
I said it must be left.
"`Ay,`" said he, "`two burdens on your shoulders at once: well,
you do not know what use it may be of, your mentioning them both at one time.`"
So I told him my mind had been perplexed, lest it should not be right,
as Friends thought it a mixture.
He seemed as if he was aware of my feelings,
and intimated how unacquainted people were (even those who often had, as it were,
to sit in judgment) with these exercises or burdens, and the true nature of them;
and also cautioned me against listening to the old adversary, when I might be out,
if he should try to persuade me I was wrong,
and had attempted what I could not accomplish--that of two concerns at once.
He charged me to keep to my gift, let it turn which way it would.
My heart was abundantly humbled under a grateful sense of
the care and wonderful kindness of Israel`'s Shepherd.
I met with this dear exercised man again on First day, at Tottenham,
where he made way for my relief in meeting, and took very kind notice of me afterwards;
got me to go with him to Thomas Horne`'s, and, in a religious opportunity,
spoke of some of the dealings of the Most High with him in his travels abroad,
and said some present would know changes of dispensations,
many strippings and deep probations of spirit; but there was no need to be discouraged.
Thus He, who is everlasting in lovingkindness, either immediately or instrumentally,
gives unto us what we stand in need of; and I feel a wish you may be encouraged hereby,
for I believe very many have been your conflicts of late, perhaps in a peculiar manner.
I have no doubt but many are the struggles of spirit
that many of you feel in visited Clonmel.
I remember the conflicting meetings,
the difficulty to get to the well of everlasting life;
and can cordially sympathise with the little exercised flock among you,
even in my sittings here and elsewhere, as well as at other times.

Since writing to my dear +++_______+++, my time has been fully occupied,
pretty much between this house and my dear mother`'s, she being poorly,
and desiring my company as much as possible;
M+++.+++ S. also wishing me to stay as much with her as convenient, she not being well,
and often low-spirited.
I have had many invitations to spend some time in families in and about this city;
but I decline, as you may suppose,
and I hope not to accept anything of the kind merely as a visitor,
except I believe it right;
neither do I seem as though I might have any intimate but M. S.

Tomorrow is the time I look towards setting out for Staines Monthly Meeting,
without an expectation to return, and without a companion;
about which I am a little encouraged,
as Thomas Scattergood mentioned to me it was better not to urge any one; and that,
in America, he had sometimes known it best to go out alone,
and afterwards somebody had rightly turned up as a companion.
He said, "`by keeping to your gift, and being helped through this journey,
it may make you stronger for the next;`" and he expected I should be helped through.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Buckingham, Eleventh Month 4th, 1797.

[.salutation]
My Dear Mistress,

You have perhaps heard of the way in which I now tread--a way which I knew not; a way,
at times, which nothing could reconcile to my nature,
but an apprehension of its being the will of Him who does all things right.
This makes crooked paths straight, and rough places smooth.
I am hardly able to tell two days beforehand where I may be.
The same friend whom I mentioned is still with me: she is a kind, sympathising companion.
We have had many very large meetings;
and although what I call preaching the Gospel is seldom got to,
without obstruction of various sorts,
partly on account of the mists of darkness wherewith many minds are clouded,
yet it is generally a satisfaction that we meet with openness in some,
and have cause to believe the petition is more and more answered--"`Give ear,
oh Shepherd of Israel; You that lead Joseph like a flock,
You that dwell between the cherubims, shine forth.`"
Sometimes, after a meeting of more than two hours,
the people can hardly be persuaded to withdraw, saying meeting is not over;
and they often wish for another; but we seldom find this required of us,
and are generally glad when, through adorable mercy,
our lives are given unto us for a prey,
so that we can escape with them to the next place,
and come under renewed baptism for what is to come; nevertheless, at one or two places,
partly for lack of sufficient room, I believe, for those who would come,
we have appointed a second, whereby more relief has been obtained.

Many of the roads we travel are very bad, being cut across the country,
and not very much used, except by farmers.
The other day I went with some friends to seek a place in a large village, for a meeting,
and was so frightened at the road, that I was obliged, as I thought,
to alight from my horse, giving a friend the trouble of getting me over a sad miry place,
as well as my horse, and then lifting me up again: I confess I was ashamed afterwards,
and thought I had lost most of my courage; but I tell them,
I never saw such roads in Ireland.
We were once up to our horses`' knees in mire, and at another time I leaped my horse.
+++[+++Here part of the letter is missing.]

We went the other day to see a great woman,
to request leave for the room over the market-place,
for a meeting with the inhabitants of the town of Watlington.
I was not easy without being one of those who went, and yet I came away burdened,
and left the town so; but, next day, thought myself obliged to go to her, which,
with another friend, I did; and she admitting us into her company,
we had a very satisfactory opportunity, which she received well,
and was very still while I was speaking.
+++[+++Part of the letter missing here.]

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Banbury, Eleventh Month 20th, 1797.

Yesterday your lively and instructive epistle of Eighth Month came to hand,
and when I read it, I said in my heart, surely, though apparently out of date,
it is come in the right time.
I cannot help esteeming it a favor that I am not
yet forgotten by some of those whose desires are,
I believe, heard in an acceptable time.
We stayed about Shillingford a long while, and I passed through bitter conflicts;
I dare not doubt their being altogether best for me,
and perhaps they helped to fit for what befel me from day to day,
almost during our continuance there; for we had many public meetings,
etc.--seventeen or eighteen since I wrote, and many among Friends,
but have not seen it right to appoint any among the latter, except one at Buckingham,
where we also had a meeting with the inhabitants in general.
I thought it might be safely said concerning it, the Lord`'s power was over all,
in an extraordinary manner.
Some other meetings of this kind have been like it,
and I think especially when we had them in large rooms,
where the people have come in great numbers, and notwithstanding been accommodated,
so as to be able to keep quiet.
Such a one was at Abingdon, in the town-hall:
I suppose there were fourteen hundred at least.
We had before had one in the meetinghouse, but could not be clear.
This place (Abingdon) is six miles from Oxford,
where we had three meetings with the people, all much favored;
and yet I am not relieved about that city.
We tried for a larger place than our meetinghouse, but could not procure it then.

You can believe, without my saying much of it, what plunging my mind had there,
and concerning it, when not there:
it seemed as much as my faith or patience was equal to,
yet I got some relief by going to visit the prisoners in the Castle;
for I went under a heavy load indeed, and the Great Master was with me by His power,
and the poor creatures had the Gospel preached to them: they were very attentive,
and seemed glad.
Just as we came away, the word was in me like fire, to the keeper,
for I believed he was not far from the kingdom of God;
so I told him this kingdom was within him,
and as he submitted to the simplicity of the Gospel, he would see all things clearly.
Last evening a very large meeting was held in this town to some relief,
although there was much to get through before the Gospel could be preached.
I believe I was on my feet two hours and a half, and the farther I went,
the more it seemed to make way in the people`'s minds; till at length,
(blessed be His name,
who has promised to be with me while my eye was single to His power) truth was in dominion,
and it seemed rather a disappointment when they were told meeting was over,
though it was nearly nine o`'clock.

Last week my dear friend Elizabeth Roper left me, which proved a great trial, as she had,
for more than two months, been a tender, sympathising companion;
but I was obliged to resign her, for she said her time was come,
and it would be presumption in her to attempt going farther,
though she loved me in a manner she had hardly known with any one before.
She wept much, but I could not at all, though I felt much: however,
another friend offered that day, who is with me now.
I met with Ann Baker of Birmingham,
and was not easy without telling her I wished her to consider about joining me,
when we might meet at Birmingham.

The low spots my mind is in at times, you know I cannot describe:
if it prove at all like receiving the "`white stone,
wherein is written the new name which no man knows,
save he that receives it,`" my soul is bowed even in gratitude for the dispensation.

Dear Thomas Scattergood has been at Sheffield some time,
of which I suppose you have heard,
as it is said he had a meeting in a place which held
three thousand people--that it was full,
and many went away: this is not the only one, for he had many in that place,
to the astonishment of the people,
he was so filled with the power of Him who is almighty.
This I believe;
we are never more peculiarly under the notice of the Shepherd of Israel
than when the sensible enjoyment of His presence is the most withheld,
in His inscrutable wisdom.

Farewell in the Lord your God; may He hide you in the hollow of His hand,
and divest you of all slavish fear, says the heart of

[.signed-section-closing]
Your affectionate, though tried friend,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Birmingham, Twelfth Month 4th, 1797.

Notwithstanding it is not long since I wrote to your family,
perhaps not more than two weeks, dated Banbury, I seem inclined to address you,
having thought much of you of late,
and been desirous you might not let your spirits sink below the life of truth in you:
this I believe many do, which tends to no good, either to themselves or others.
Oh! how I wish to be the least strength to any of you herein,
if it is only by the deep inward attention of spirit in fellowship with yours.
There are seasons when I think I am made partaker hereof with some of you,
my dear friends in Ireland, for which fellowship I am thankful.
Here I may acknowledge, great is the kindness of many friends towards so poor a creature;
yet my attachment to a place where I knew many heights and depths for so long, and where,
I humbly trust, through adorable mercy,
all wrought together for a degree of furtherance
in the great and necessary work of sanctification,
is likely to exceed anything yet known here; although my dear,
here likewise many proving times have been in wisdom permitted and appointed; yes,
and what is more, and more than anything to be desired, the great "`I Am`" has granted,
as far as I am at all able to judge, resignation in a great degree,
to these turnings of His all-wise hand.

I believe the Most High designs there should be an arising,
shaking from the dust of the earth, and putting on the beautiful garments;
and that many of the dear young people are preciously given up to His honor;
acknowledging that "`Worthy, worthy is the Lord God,
and the Lamb who is redeeming them by His blood, to receive honor, power,
and dominion in all, by all, and through all.`"
Among other people, great is the openness in many to hear the Gospel published,
though to this there remain obstructions; yet the power rises high in many meetings,
in setting forth the purity and excellency of the glory of God,
in the face or appearance of His Son Christ Jesus our Lord.

May you all dearly farewell, which we may through all,
by keeping our ranks in righteousness.
Do tell me how you and dear Ireland fare; I hear dismal accounts of it.
Many attempts have been made for T. S., and some were for S. L. before,
to get the town hall at Oxford, to hold a meeting;
but they compared it to admitting the enemy into their fortifications:
I suppose it would hold several thousands.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Birmingham, Twelfth Month 12th, 1797.

[.salutation]
My Very Dear Mistress,

Yesterday I received your valuable epistle,
together with the acceptable additions from the beloved children.
My dear companion`'s name was Elizabeth Raper; but she has left me several weeks,
which was a close trial to us both,
but she thought it was not right for her to come any further,
and I afterwards thought it proved so, for she could not have borne riding on horseback,
and some of the roads H. H. and myself went were impassable for a chaise.
I had with me, for several hundred miles, R. E., of Amersham, an elder, and an elderly,
yet active man; he manifested much fatherly regard and care,
and said he had great satisfaction in giving up to come,
though much in the cross to his natural disposition.
I admire his innocency and openness: nothing he said hurt me,
though he often freely communicated his mind: before we separated he acknowledged,
that while we were together,
he was frequently made sensible of something very comfortable when sitting by me,
which I think a great favor.

Since I wrote you last, have had a deal of traveling,
and many meetings in very foul weather; I have been wet through several times,
and for some miles the snow was so heavy I could hardly see,
it coming so thick in my face; my companion, riding double, fared better.
That day we rode from Eatington, in Warwickshire, to Warwick, ten miles,
to a ten o`'clock meeting,
and had another in the evening with the people who do not profess with us, which,
notwithstanding the severity of the weather, was large, and, in a good degree,
divinely favored, as was another the next evening at Coventry.
Blessed forever be that Power that does all things right!
Our journey to Coventry was almost dangerous, but we were not easy to stay at Warwick.
A friend who accompanied us cut the snow several
times out of the horses`' feet with a knife,
or they might have fallen.
We got to this place, coming through a deal of water,
from the great rain that followed the snow; sometimes we could see nothing,
for a long way before us, but water.
However, we have been mercifully preserved from accidents or cold very much.
My health seems bravely, except at times a pain in my chest.

Here I feel still bound, although I have sat some distressing meetings in silence,
or nearly so,
and in others have been a little enlarged in the gift mercifully vouchsafed;
have also sat in fourteen families.
What I have done has been through inexpressible pain, and in one instance, particularly,
where I had to tell a young woman who appears in meetings,
that hers was a floating ministry, and the Lord would have none such.
Oh! I could not help it, let the consequence be as it might;
the word was like a sword in my soul till I gave up.
I remembered I could not choose what to do, and what to leave undone, and yet be accepted.

Dear Ann Baker says she feels her mind engaged to accompany me for a while from here;
her precious gift seems to be used in much purity and simplicity.

My mind is often occupied about dear +++_______+++;
tell him my soul feels solicitous on his account; so much so,
that I have thought of writing to him.
Oh! that he may be one of the believers, unto whom all things are possible;
he must then assuredly believe in the simple revelation of that eternal
Power that has eminently visited and brought his mind under close exercise:
so will the "`mountains skip like rams,
and the little hills like lambs,`" at the presence of the mighty God of Jacob.
Oh! how different will the face of all things appear;
his wilderness shall be made like Eden, his desert like the garden of the Lord:
he shall have to say rejoicingly,
"`Let my Beloved come into His garden and eat His pleasant fruits.`"
"`I am my Beloved`'s, and my Beloved is mine: He feeds among the lilies.`"
How is this, at the present moment, illustrated in my view on his account.
I do think all he has to do is,
simply and unreservedly to resign himself into the hands of a faithful Creator;
not approving in part, and disapproving in part, the works of Omnipotence,
but approving the whole, and saying, "`Your will be done.`"
Solomon in all his glory was not arrayed as these are;
these shall be clothed with the whole armour of light.
Amen, says my mind herein toward dear +++_______+++.

Did you ever know of so many out together on religious service in the two nations as now?
I long we may accept the present large offer many ways of everlasting kindness, mercy,
and truth.

I must conclude, although my heart is as full as I can express of love, of sympathy,
and of desire for you all, particularly for you:
"`feeling has no fellow,`" and I do hope you feel I love you dearly, dearly,
and hope you will remember me still.
Dearly all farewell.

[.signed-section-closing]
Your truly affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Birmingham, Third Month 5th, 1798.

[.salutation]
My Very Dear Mistress,

My mind is much with you and yours in sincere affection, and I trust, at times,
in fellow feeling in your various conflicts,
perhaps in the Lord`'s turning and overturning in the secret of your own souls,
some of you particularly.

It seems long since I addressed any of you in this way;
I hardly know why it should be so; but it is more unaccountable, perhaps,
to you and to me, that the date of this should still be Birmingham, the same as my last,
now nearly three months ago; but so it is.
Yet, as you have (it is likely) heard, we have not been all this time here;
we went to attend the Quarterly Meeting at Worcester,
and were unexpectedly detained from this place about five weeks,
passing through much probation, having public meetings, etc.
Since our return we have had considerably more than a hundred opportunities in families,
having frequently had two in one family, and attended many meetings,
but have not appointed any, yet feel bound in spirit, and cannot rightly make our escape;
if we could, I believe it would be cause of gladness.
Many have been our trials here and various;
perhaps I have never known closer proving of spirit on several accounts; yet believe now,
while I write, all things are designed to work together for good,
if the intention is but pure,
and resignation to the Divine will honestly endeavored after in all things.
I am ready to conclude, at times, I have many deaths to die,
before the Divine will is wrought out in me; peradventure,
in the progressive advancement of this painful, yet necessary work,
it is that this Divine will may be wrought out by us and through us: well,
Divine aid is the alone sufficiency; where else can we centre?
unto whom shall we go?
He has the words of eternal life, even He who speaks in righteousness,
and--oh! precious annexed language--"`mighty to save!`"
He has, my dear mistress, even to my soul, many a time since I saw you,
proved Himself omnipotent; for which, repeatedly,
has my mind been bowed in reverent submission:
in the moment of extremity He has been my Deliverer.
Yesterday (First day) was a time of uncommon exercise.
I had been silent at several meetings and two burials,
save a short testimony in one of them, and felt, on going to meeting again,
poor and empty, without any expectation of being qualified to minister to others;
but "`while I was musing, the fire burned;`" then I spoke what flowed unpremeditated,
not only in testimony, but supplication: but oh! between meetings,
the suffering was unutterable, save in mental groans to Him who, I believed, existed;
who knows all hearts.
Thus I lay on the bed most of the time till we must go again,
not knowing that He who hides Himself in wisdom,
would be pleased to put a new song into my heart,
and command the utterance thereof in words, as was afterwards the case, both in meeting,
and in a family in the evening: then I said, It is good to trust in the Lord.

I wish, as for myself for you, dearly do I wish it, He may be your all in all,
sanctifying every secret or visible trial to you.
Many times of late, by night as well as by day, the language of my heart in effect is,
"`Bless her, oh compassionate Father; bless her and hers,
not only with the fatness of the earth, but with the dew of heaven;
that so there may be a pleasantness unto yourself,
a holy verdure:`" thus has my spirit been wafted to your habitation,
when I have remembered the exercise of soul that assailed me there, at different times,
in different shapes.
When I reflect that I might have done better at some periods--have been more meek,
more submissive, and have had thereby more true firmness, more fortitude,
yet can I throw myself into the arms of adorable mercy and say,
"`There is forgiveness with You,
that You may be feared;`" yet can I be glad in that His love unites us in spirit now,
as it did at times, through all.
The dear children every one, are affectionately in my thoughts, and poor +++_______+++;
I wish her well, now and forever, with all my heart.
May all the dear children cultivate truest wisdom,
by an inward attention to its dictates: I cannot now, with pen and ink,
say how they individually come into my thoughts.

This may serve as a little testimonial of my continued, undiminished love,
but I confess myself not equal to the expression of what my mind feels for you;
in which I bid you farewell,
hoping it originates in something that I could not of myself manufacture.

[.signed-section-closing]
Your sincerely affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
John Burlingham to his Wife.

[.signed-section-context-open]
Dudley, Fourth Month 26th, 1798.

[.salutation]
My Dear,

Although my brother is intended to be the bearer of this,
and would inform you verbally respecting me and our dear friends,
Sarah Lynes and Ann Baker, yet I do not feel excused without briefly saying,
that yesterday is, I hope, not to be forgotten by us their companions, and I trust, many,
many more.
You may remember I told you S. L. had spoiled my night`'s rest.
I may say it was a very great trial to me, and not the less so,
from seeing S. L. in such a distressed, low spot; which, more or less,
continued until within a little distance of Wolverhampton.
She neither saw nor spoke to any Friend there, except those at our quarters.
On inquiry we were told the most suitable place to
speak would be from the upper window at the inn,
but that not feeling right to S. L., we left her to take the helm.
She said to A. B., "`you take R. B.`'s arm;
I will take J. B.`'s;`" so she led me the way into the market.
After making a short stand, she began to address those around her,
and had not spoken many sentences, when many shed tears, struck dumb, as it were,
with amazement; indeed the power was so great, and so evidently felt,
that fear was taken from me.
After a very solemn,
but short opportunity (having hold of my arm all
the time) she went more into the centre of the market,
which is a very large one, and seeing a butcher`'s block,
without asking any questions to whom it belonged, she and Ann mounted it,
my brother and self standing on each side.
A large audience collecting immediately, she addressed them for about one hour,
to the satisfaction, I believe, of most that could hear her.
When she got down, great was the anxiety of many to shake hands with her,
which numbers did, and also expressed their thankfulness.

By this time the farmers, many of them, were gone and going to dinner;
we therefore went to the inn, the people making way for us to pass respectfully:
when there, S. L. did not seem quite easy in thus missing the farmers, but,
understanding a number of them were dining at the ordinary,
she concluded to offer herself to them as soon as they had dined.
My brother went and asked them the question: the chairman immediately replied they,
or he, had no objection.
My brother and self accompanied S. L. and A. B. into the room.
We were asked to go up to the top, but S. L. declined, and sat down at the bottom.
During a space of about ten minutes`' silence,
several interruptions took place by people coming in.
If I may give a description of S. L.`'s engagement at that time,
agreeably to my own feelings, both then and since,
I must say that her elegance of language, pertinent matter, persuasive energy,
and above all, the crowning authority and power, I think I never witnessed exceeded,
if equalled.
When she had done, she instantly began to withdraw; when the company, every man,
rose from his seat, though silently, yet most respectfully; they showed,
at the same time, good manners, and also assent to what they had heard.

On inquiry,
we found the company she had thus been addressing was composed of gentlemen farmers,
several attorneys, and one clergyman; the latter had heard her in the market:
the chairman, we apprehend, was the high sheriff of the county.
So we see how her language; was suited to the company, and she knew nothing,
until afterwards, as to who they were.

After the opportunity in the market, S. L. found other work.
The Methodist meetinghouse being offered,
she did not feel freedom to go without seeing the towns-people: the offer was accepted,
and those who belong to the meeting, say two thousand people, were within the walls.
Many hundreds could not get in.
I believe it was a favored season; her mind pretty comfortably relieved,
but she is withal, so worn down, she concludes to rest today.

[.signed-section-closing]
I conclude in haste, and remain your affectionate husband,

[.signed-section-signature]
John Burlingham.

[.letter-heading]
Sarah Lynes To +++_______+++.

[.signed-section-context-open]
Dudley, Fourth Mouth 29th, 1798.

Ever since I received your letter of 9th instant, I have longed to reply,
but could not till now,
not only because of engagements to fill up my time pretty closely,
but because of the sore exercise of my spirit from day to day,
in all which I can now rejoice and give thanks.
When this joint letter of yours came to hand, we were at Worcester again,
and my heart beat high on opening it.
I had longed to hear of you, and how you went on,
particularly as the sad doings in Ireland had reached my ears; yet, through all,
I seemed to hope Almighty aid would be your support under every difficulty--you,
whom He has gathered under His own holy direction; you,
whose hearts He has disciplined to the cross of His dear Son.
Oh! there are seasons when my spirit bows for myself,
and for individuals in and about Clonmel particularly,
that we may be of those whom nothing can harm,
because they are simply and singly followers of that which is good:
surely this makes the life pure enough to be "`hid with Christ in God.`"
What, surely, what can we do better,
than seek to rely in resignation on the simple guidance of that Wisdom which is infinite?
for then it increases in us, and the more we are acquainted with it, the more we love it,
and are made partakers of its bread, and the wine which it has mingled:
thus may we be helped on, and the soul nourished up unto eternal life.

My dear +++_______+++ knows surely that my love and fellow
feeling with her cannot by me be fully expressed.
I fear she has again been anxious in not hearing from me:
it is not a lack of inclination, but I may say,

[verse]
____
How can my pen portray the deep distress,
How paint the anguish of a heart that bled, etc.
____

Because of these most trying feelings of late,
I could not tell you how much I remembered you, even through it all.
I believe for more than a week I had not one quiet hour.
I told you of going back to Worcester; it was after attending a burial at Birmingham,
at which there was a great multitude, and I was helped to set forth in a good degree,
the efficacy of the living eternal power of God working in the soul,
for its thorough sanctification, justification, and everlasting glory:
this was the most relieving time to me of any in Birmingham.
Next day was the Select Quarterly Meeting in Worcester, so we proceeded,
and were detained, visiting families, etc., for three weeks.
We had often the company of those of other societies at meeting,
and appointed one for the topping people of the city, which was not very large;
and although we had satisfaction in being "`unprofitable
servants,`" doing that which was our duty,
my spirit has never felt relief in Worcester.
We left it last third day after the Monthly Meeting,
and next day had to go to Wolverhampton market, and speak to the people in two places,
also to speak to a large number of what are termed gentlemen, who dined at the inn:
we yet could not get away without a meeting in the evening,
and it was thought fifteen hundred got into the house, and very many could not.
I had another opportunity with my fellow travelers that evening, which closed the day,
and next morning we came here to breakfast: had, that day, two private opportunities,
and saw the next day`'s work, which, in prospect, seemed enough for nature,
yet so it must be; for we went to the market-places at Stourbridge, had one family visit,
and came here again next day, which was yesterday;
and oh! we must needs go to the marketplace here likewise, and so we did.
We have this day (First day) been at two meetings, which,
in consequence of the people knowing we were here, were crowded, but what is better,
were much favored: many came from the country round about,
and I believe many of their souls were truly hungry and thirsty.

At Wolverhampton there were many hearts tendered,
and we were sensible of much holy aid to fulfill all the apprehended will;
yet as soon as this was done, my spirit as it were was again in the deeps: yes,
my dear friend, and so it has been nearly throughout this last week;
but this evening I am quiet, and seem bravely, notwithstanding all.
But who can understand these things?
Very few can know what it means, or why it should be so;
and I can`'t give you such an idea of the dealings of the Most High with me as I wish;
you will, however, make my dearest +++_______+++ a sharer, and you must feel the rest,
if you are permitted.
It is the language of my spirit, "`Great and marvelous are your works,
Lord God Almighty,`" etc.
Dearly farewell in the unmixed, inexhaustible source of all-sufficiency.

[.signed-section-signature]
S+++.+++ Lynes.

We return to Birmingham, and bonds and afflictions seem to await me everywhere.
The Lord is our strength.
Oh!
He is great, and greatly to be praised.
His is the kingdom, the power, and the glory, forever.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To one of Sarah Grubb`'s Children.

[.signed-section-context-open]
London, Fifth Month 25th, 1798.

I feel disposed to endeavor to tell you a little
about how my mind has been engaged concerning you,
and all the family at Anner Mills, from time to time: it is indeed in love unfeigned,
accompanied with a desire that Heavenly Goodness may be with you,
as an all-sufficient Helper, in and through all.
I have not the least doubt of its being His design, therefore oh! that from day to day,
He may be simply and singly relied upon.
I cannot suppose but your minds are individually and unitedly exercised before Him,
and this is precious to my soul; for if this exercise is not flinched from,
nor mixed with the natural will and wisdom,
it will cause all things to be sanctified unto such; so that,
in their spiritual measures,
the depth of that exercise will so increase as to cause a dying daily, yet living;
and the life of these is by faith in the Son of God:
hence these are on their way to the blessed experience
of being filled with all His fulness:
the mystery of the language,
"`because my Redeemer lives I live also,`" is to such unfolded.

Well, my dear, my heart is enlarged,
but here I leave you all to Him who is omniscient and omnipotent,
and will begin to say that the Yearly Meeting has now sat seven times;
and though we may say that it surely does not rain on every field at once, yet,
speaking in a general sense, I believe the Lord Almighty has so far bowed the heavens,
and come down among us,
as that He has again evinced that this people He has formed for Himself,
and still designs they should peculiarly show forth His praise.
May the present visitation of Divine love be accepted to us as a people; for if we,
as it were, hold our peace, the stones of the street will cry out; seeing that,
in the most expressive language, that of the whole tenor of the life of man,
God Almighty will be glorified.

All the American Friends now in England, are here, and have exercised their gifts.
Yesterday forenoon we did no business, for many were engaged in exhortation,
or supplication; among whom was William Savery, who came to visit us.

I send by J. B. a little box, in which is a small portion of my knitting,
while traveling; for your dear mother, a few labels; for your aunt, a watch string;
for you (some words missing) I am almost ashamed of the colour,
it being a new thing for me to choose colours.
I excuse myself, and conclude, if it was to do again, I should have it otherwise:
none of the knitting is perfect; constant attention could not be paid to it.
I send to dear A., a thimble; to R. and J., a little watch-hook each:
hope you will accept these trifles in the love meant.
I have heard speak of "`love in a nut kernel.`"

I have sometimes desired you might know that I am, in general,
as well in health as when with you.
I lately lost my voice, but have got it again.
Farewell.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Friends of the North Monthly Meeting, Warwickshire.

[.signed-section-context-open]
Sixth Month 10th, 1798.

[.salutation]
Dear Friends,

In the fresh feeling of that life and power which first gathered us to be a people,
separated to serve the living God, and which, I humbly hope,
drew my mind to visit you personally, do I now salute you;
desiring you may so adhere to the precious gift of grace in yourselves,
as to be increasingly made and kept alive in Him,
who has thereby called you to glory and virtue.
I know that there is cause for some of you, who are standing first in the tribes,
as well as others, to bend more implicitly to this Divine call, that,
in the sight of the Searcher of hearts,
you may serve Him in holiness and purity all the days of your lives;
"`whatsoever is not of faith is sin.`"
There are many things that are not brought forth
by the living faith of the Gospel of Christ,
which the world even approves, which are, nevertheless, iniquity in the sight of God,
and which are seen to be so by those who are quick of understanding in His fear.
This faith, which works by love to the purifying of the soul,
would keep you in holy order, when engaged about your lawful concerns;
and in your meetings, whether for worship or discipline;
for it is that which puts a man into the capacity
for producing those works which please God,
and a purity of dependence on the simple leadings of His own Holy Spirit.
Who is there among men, brought into the practical part of true and revealed religion,
that dare lean to their own understandings?
Surely none; but, feeling sensibly their own inability, as men, to work the works of God,
they ask for that wisdom which comes down from above, which "`is first pure,
then peaceable, gentle, and easy to be entreated; full of mercy and good fruits,
without partiality, and without hypocrisy.`"
Oh! that you may thus ask, and you will receive, keeping your ranks in pure righteousness.

I remember that I told you these things, while present with you; but now, being absent,
I endeavor also to "`stir up the pure mind by way
of remembrance;`" letting it keep pace with knowledge,
which is not a knowledge that puffs up, but the simple unfolding of the Divine will.
There are among you, who are near and dear to my life, in Christ:
these are the little ones; unto these I now put the language, "`Fear not, little flock,
for it is your Father`'s good pleasure to give you the kingdom.`"
You, I mean, who "`have none in heaven but Him,
nor in all the earth you desire out of Him:`" your foundation
will stand through the shaking of the heavens and the earth;
for, it being purely of God, it has "`this seal, the Lord knows them that are His.`"
These among you are an oppressed remnant, but their fortress is the fulness of strength.
Oh! that you who, though professing the same faith, are so far from the same practice,
as to be the followers of the world in its bewitching and fluctuating spirit,
may awake to righteousness, and sin not; may gather your wares out of the land,
even coming out of Babylon, and be inhabitants likewise of this invincible fortress.
How often has this language been sounded in your ears before now, "`To your tents,
oh Jacob; to your dwelling-place, oh Israel!`" and will He who is rich in mercy,
and just and equal in all His ways, always strive with us?
We do not know how soon He may deal with these according to their folly; and,
because in the day of His mercy there was a turning the back, and not the face, He may,
speaking after the manner of men, "`laugh at their calamity,
and mock when their fear comes.`"
I feel my heart enlarged to all in Gospel love,
that those who are afar off may come near; and those that are near,
may acknowledge the might of the God of His people the world over.

There are among the dear young people, male and female, who are near,
and will be nearer, if they are faithful to what has been, and is made known to them:
these must look straight before them,
singly eyeing that all-sufficient Power that has visited their souls with its illuminating,
quickening influence; so will they go forth and "`grow up as calves of the stall.`"

"`Now unto Him that is able to keep you from falling,`" I commend you, with my own soul;
desiring that, by His witness in yourselves, you may be able to know what part of these,
lines belong to you as individuals.

[.signed-section-closing]
Your true friend,

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Uxbridge, Sixth Month 16th, 1798.

I want to repeat the assurance of my continued heartfelt solicitude for you,
as well as to say, that I account it a favor having, previously to my leaving London,
another written testimonial of being in your remembrance still,
amidst your anxiety and trouble in the confusion of the land.
I was making ready for this place when it was handed me, at Joseph Savory`'s,
having been most of the time of our stay in London, among my dear relatives,
when not engaged in meetings, etc.
My heart feels, but I cannot say what, with respect to dear Ireland; and particularly,
my endeared acquaintance are much in my thoughts: you are one of these, be assured;
and I have prayed (if the sincere breathing of my soul may be termed so) that,
in the Divine will,
you may be enabled to bear your part of this heavy
burden and heat of this day of sore tossing;
bear it, so as to be thereby deepened in the root of everlasting life.
Now I have not the least doubt of this being the design
of Him who does all things right concerning you,
although you cannot think it will be so, seeing all seems darkness and distress about it.
Oh! learn to stand still, if you possibly can, in your habitation, that thus you may,
in the Lord`'s time, sing of His salvation in your soul; and may it be so with you all,
dear creatures.

We went to the Monthly Meeting at Brentford; returned here, and oh! my dear,
next day we were under the necessity of going into the market twice,
to declare the counsel of the Searcher of hearts to the people.
He was in this, and other things, all we needed,
though my faith was tried to a hair`'s breadth.
Nothing, sure, can compare with this one thing in any of our engagements; all else,
when this is full in prospect, looks comparatively small; but we can set up our Ebenezer,
and say, "`hitherto has the Lord helped us.`"
May He keep us and guide us all everywhere in His counsel,
and afterwards receive us into glory!

I believe the Most High has joined my dear yokefellow and me together;
we don`'t see light on moving from this place.
I wish to adopt the language, "`Lord, make me quiet in your will.`"
It is thought many people will come to meeting tomorrow.
Oh! that I may be preserved in my right allotment!
I feel many of you as epistles written in my heart.
The God of all true succour be with you, now and forever, says my spirit,
bearing up in every exercise; even so, Amen.

[.signed-section-signature]
S+++.+++ Lynes.
