== Chapter 4. Letters from 1798--1799

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Nottingham, Seventh Month 14th, 1798.

[.salutation]
My Very Dear Mistress,

It has been in my heart, for many days past,
to give you some written testimonial of my continued affection, and indeed, I may say,
fellow feeling with you and yours in this day of trial;
by day and night you are much in my thoughts, with many others in poor Ireland.
Past occurrences are frequently brought to my remembrance with heart-aching sensations,
that many late peaceful abodes are now disturbed by the ravages of war; and peradventure,
many more will yet share the same fate: nevertheless, the Lord is righteous;
He will keep them so as that all things will work together for their substantial good;
and these turnings and over-turnings may hasten the time,
when "`Glory to God in the highest, and on earth peace,
good-will toward men,`" will be the general breathing language of mankind in their conduct,
because of the illustration and fulfilling of the Gospel dispensation.
Oh! may the Lord of all power and pure consolation comfort you, every one,
by His presence in the time of need.
I must leave you individually to Him.
I often most dearly commend you in my spirit to His providence, as I do at this time.

I often think, if I had left Ireland to escape trouble,
great would have been my disappointment,
for close conflicts have been my portion from time to time, since coming to this nation;
some of which have proved equal to anything I could have formed an idea of,
and beyond it: yet, with heartfelt gratitude to Him who does all things right,
I can say, He has been all to me in the needful time;
but oh! if I dare ask anything of myself,
it seems to be that the work might be cut short in righteousness.
I turn from the thought, lest it should be unacceptable to so gracious a God and Father.

Since leaving London have had to go to many market-places to speak to the people there,
as well as having very large meetings indoors,
most of which have been seasons of enlargement and of some relief,
generally after deep poverty and searching of heart: thus am I led along,
and it is many times the language of my heart when most relief is obtained,
"`I have done but that which was my duty to do.`"
It is to my mind as clear as the day, that, let us be how we may occupied in this life,
while we are unreservedly at Divine disposal, and no longer,
are we in the full discharge of this duty, which will bring its reward.
Sometimes, in the public exposures, great openness is among the people;
at others very little;
but we have been for the most allowed to appear as
long as seemed pointed out to our minds;
as at Uxbridge, Amersham, Wycombe, Luton, and Northampton; but at Leicester,
two very fierce-looking men would have had me down in their fury,
almost without my knowing why;
my not going until I fully understood that the mayor sent them,
gave me an opportunity of just telling the people
that I believed that opportunity would have its use,
and that I was clear in the sight of the Most High thereby.
We got quietly away from them all, and had peace:
some of the people round were in tears before we were disturbed,
and many appeared grieved in their hearts that I might not stay longer,
but I thought the Lord would turn it to good, and so it was;
for next day being First day,
the meetinghouse was crowded by persons from both town and country,
and some of the topping folks that are seldom seen at such opportunities.
The Almighty was pleased to appear in both meetings,
giving authority in the awful line of the ministry,
which yet did not thoroughly throw off the burden for that town,
so we had a very large meeting next evening in an assembly room:
I thought truth might be said to reign at last, for which our minds were humbly grateful.
We had to go next day to the two jails and the infirmary,
all of which we visited generally, and got away that evening to Castle Donnington,
the abode of Ruth Follows:
she appeared pretty well in health and cheerful--very lively in the ministerial gift.
We attended a marriage next morning--the meetinghouse very full of people,
and truly comfortable it was altogether;
but though it was easy to minister of the word of
life among that large gathering of solid people,
my mind was much tried with a prospect of returning that afternoon to Loughborough
(a town we came through the preceding evening) to have a meeting in a warehouse,
but help was near in the time of need, to my unspeakable satisfaction,
and we got from Loughborough the next morning, proceeded to Derby,
had a large meeting in the county hall same evening, wherein,
though there was close doctrine to some, inward consolation was felt.
We came here last night, after visiting the jail at Derby,
and going to see a religious woman who earnestly desired our company:
also paid a visit finally to the few who appear under convincement at that town,
perhaps ten or twelve, who sit down together in one of their houses twice on First day:
there appeared something substantial among them, found through much searching of heart.
I forgot to say we had similar engagements at Northampton, in the jails and infirmary,
as well as having two large public meetings.

This place has already been a scene of bitter conflict to my spirit,
having had to go to two places in the market this morning.
I have been straitened almost as unto death, till it was accomplished,
but got through without molestation,
though some would have had me driven away from the first place.
My soul is now thankful for a little quiet so far,
but tomorrow is a day in prospect to be dreaded much,
unless there is ability to hide as in the bosom of Omnipotence;
for this is a great place, and the roof of Friends`' meetinghouse broke in,
so that we are under the necessity of having two dissenting meetinghouses,
one in the morning, the other in the evening.
Friends think our having been so exposed today, will bring very many to us tomorrow:
we know we are nothing out of holy help, so must leave all, if we can, to this power.

[.signed-section-closing]
Dearly farewell all, as if named, your truly affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
John Burlingham to his Wife.

[.signed-section-context-open]
Nottingham, Seventh Month 16th, 1798.

[.salutation]
My Dear,

The seventh was a memorable day.
We got to Leicester in time for the market, which we attended.
After Sarah Lynes had been on her feet about ten minutes, the people very quiet,
and some in tears, she was interrupted by one of the mayor`'s officers,
who came pushing through the crowd, and ordered her to desist,
saying it was by the mayor`'s directions.
I told him I would call on the mayor, and requested he would be quiet a little time.
Presently came two more, in a furious manner, like bull-dogs,
and would have used violence, to all appearance, but the people began to interfere.
S+++.+++ L. told them, that under what she then felt, she was afraid of no man.
She told the people she hoped she should be clear of their blood,
and that some good would come out of this.
Soon after she came down from the chair, a young woman belonging to a shop just by,
requested we would walk in.
After stopping about ten minutes, we walked quietly to our inn.
Many people were much displeased at the interruption.

James Cook (one of the corporation known to me) called
on the mayor to tell him I intended waiting on him,
to explain my friend`'s motives, etc.
I do not know what he said respecting me, but the mayor began to make excuses,
and to palliate the matter.
S+++.+++ L. desired no invitation might be given for First day;
however I went to the meetinghouse with other Friends, and by adjusting the seats,
made room for about fifty more.
In the morning James Cook was there, and several aldermen, with other principal people.
I believe none went away dissatisfied--many quite the reverse.
In the afternoon many of the principal people who were there in the morning, came again,
and many hundreds that could not get in; otherwise it was a very satisfactory meeting.

On second day morning I had my work allotted me in Leicester,
which was to fit up a place for a public meeting that evening.
I told Cook I preferred the hall, and, as I wanted to see the mayor,
would run the chance of being refused.
We called again and again, but could not see him, nor learn where he was:
at last I saw the high alderman (mayor last year) who, I believe,
was the man most concerned in the orders respecting the market.
He told me, in pointed terms, how much he disapproved of preaching in market-places.
I heard him out,
and then told him he had now given me an opportunity of explaining that business.
I then gave him an account of S. L., her general and particular engagements;
also my views in thus leaving my home and family to accompany her.
I told him various places where I had attended her
without any interruption till the present,
and that no disturbance took place then; the people being very quiet, and some in tears,
till the instant the mayor`'s officers came to disturb us.
I told him I was firmly convinced her concern was right;
it had carried its own evidence with it.
I begged him to consider what he thought could induce a modest young woman, as she was,
thus to expose herself;
that she saw a description of people in the market she could
not see in any other way (which was an unanswerable argument).
I adverted to myself,
saying he must suppose it could not be a very pleasant thing to my natural feelings,
to become a spectacle in a market-place.
I felt ability to tell him my mind, and he seemed not disposed to reply,
only said he would give us credit for our good intentions: with respect to the hall,
he must refer us to the mayor.
We called again--still not to be seen.
No time was now to be lost; we therefore got another place,
which had been used as a playhouse, now an assembly room:
very close work I had to get it ready in time; I went without my tea.
Before S. L. and Ann Baker came, near a thousand people, it was supposed, were collected.
S+++.+++ L. was on her feet in less than ten minutes, and after she had stood an hour,
her voice mended to my admiration; she had much power and command of it:
she stood nearly another hour: people seemed as though they were nailed to the floor.
Her conclusion was very solemn.
She adverted in a very few words to what had passed in the market;
it was short but striking; I doubt not many felt it.
I felt myself well repaid for the great exertions I found necessary in doing my part,
although, compared with hers, but as the drop in the bucket.
Third day she paid a visit to the jails and the infirmary.

On seventh day S. L. had two opportunities in the market,
in the first with the butter-women: a constable came, and was much disposed to interfere,
but was prevailed on to desist: that with the farmers was solemn and quiet.
One farmer came thirteen, and another seven miles to meeting yesterday;
I conclude in consequence.

Various circumstances seem to rivet me to S. L. and A. B. at present.
I hope this journey may do instead of my usual recruit at the sea-side.
I have much wished it might: I had rather be thus employed.

[.signed-section-closing]
Your affectionate husband,

[.signed-section-signature]
John Burlingham.

[.letter-heading]
Sarah Lynes to Hannah Burlingham.

[.signed-section-context-open]
Sherburn, Eighth Month 3rd, 1798.

[.salutation]
My Dear Friend,

I have thought of writing to you many a time since
your dear J. B.`'s continuance with us,
poor pilgrims, but you know I do not like much of this as a matter of form;
therefore hope you could, without a written testimonial,
be assured of my tender feeling with you, yes, and with yours;
and most heartily do I desire the Fountain of Good may be your all-sufficiency,
not only now, in the absence of the nearest and dearest connection in life,
but also when he may be favored to return.
This, I have no doubt, will be your blessed experience,
if your minds are seeking to centre in Him.

It has many a time been the language of my spirit,
when it has been wafted to Catharine Hill,
"`The eternal God be your refuge,`" one and all.
Now in order that we may be thus privileged, He who does all things to us,
and concerning us, right, sees fit to try and prove,
not only by secret unfathomable dispensations, but also by more visible tribulations.
Then let us, oh let us endeavor to leave all to Him, and say,
"`Your will be done,`" thoroughly done: nothing like this, my dear friend;
nothing so glorious in its effects:
and though we have many a struggle to get to the "`nevertheless not my will,
but Yours be done,`" yet the struggle maintained in the grain of faith received,
does it all in due time.
Thus in blessing may you be blessed, and in multiplying may you be multiplied;
for it is an increase in the increase of God, or of perfection leading to glorification.
After this manner do I bid you all farewell in the Lord; and I may say,
if it is any comfort to you,
that indeed I am not unmindful of your dear husband`'s
trying seasons in this arduous engagement with us,
but I am pretty quiet about even the doing and suffering,
believing it is all designed to be blessed to him for present and everlasting good;
so I hope you and your precious family at home give him up freely,
as one of the willing in Israel.
None of us desire his stay (we dare not do it) longer
than the pointings of that which cannot err,
appear to (may I not say) demand it.
While this is the case, home could not be a home to him,
nor his company a blessing to you;
and I have no authority to say anything respecting the space of time until he may return:
I believe Best Guidance is near him.

Now with dear love I conclude.
Love and a kiss to the children.

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
Sarah Lynes To John Burlingham.

[.signed-section-context-open]
Whitby, Ninth Month 10th, 1798.

I was glad in your return, and I was sorry: glad,
in that you would be able to see for yourself how things were,
and that it might make your dear wife easier.

I have thought that the Lord`'s little ones must know what it is, as it were,
to lay the body even with the ground, to be walked over; which, nevertheless,
does not hurt the life, that life which is hid with Christ in God.
"`How pure,`" (says S. R. G.) "`must be this life!`"

How many are the dispensations, my dear friend, necessary for us,
to be of those thus redeemed.
May you so abide under all,
as to know the grace you have received to be your sufficiency in this work;
and oh! may I! I was sorry in parting with you, as a kind helper and dear friend.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sunderland, Eleventh Month 3rd, 1798.

Truly I have undergone many secret cogitations on your account:
does this manifest a disposition not willing to leave you to the Lord`'s disposal?
for I do not know.
If so, then I have renewed cause to endeavor after greater acquiescence;
for now I am also in fears and doubts,
hunting even the newspapers for accounts from Ireland,
peculiarly because of some of my much loved friends there.

At Newcastle we had to surmount much difficulty in the path cast up for us,
as it appeared necessary we should not only have very large meetings,
but go into the markets: in all we had cause to say, "`What ailed you, oh you sea,
that you fled?`"
etc. The next place in view was Shields; there, too, had many large meetings;
stayed ten days, visited Friends, as well as others,
and came here more than two weeks since.
Many things have befallen us, but all now seem to be good.
We had several meetings with Friends, and many with others, not only here,
but round about, seventeen in all, besides having to go into the streets or markets.
Ann Baker being ill, I had to go without a female, and obtained relief.
Next day I wrote thus:--"`Had, on my bed, to scrutinize concerning the engagements,
and desire all in me might be done away that breathed
anything out of the will of the Father,
and that He would be with me in future.
Oh Lord, You only know how my soul partook of the wormwood and the gall yesterday,
in endeavoring to move in the line of apprehended duty in your sight:
You were graciously pleased to support me in it, and bring me through it; for this,
and all your dealings with me, to this day, my soul blesses your holy name.`"
In the street a man spoke roughly to me, and bade me begone;
that that was the place to sell, not to hear my nonsense.
I stood till I felt the power, and then replied, he must be serious one day or other;
and that was also the place to clear my conscience, the Lord God having laid it on me;
he said no more, that I heard of, and the people behaved well.

At Newcastle I met with a man who is not joined in profession with any religious sect,
who appeared very glad he had heard me declare the truth, for he said it was truth,
and his heart rejoiced when any spoke in the power of God,
for all ministry without it is vain.
He said he had a nephew, like himself,
not easy with the forms of worship made use of by most people,
who was endued with this power, although he naturally had an impediment in his speech,
so that he spoke to the tendering of many hearts, and was not sixteen years of age.
Now, although I do not seem able, at present, my dear friend,
to give you much that will do you good, yet, be assured,
I feel much for you in your exercises and sore baptisms, and desire the Lord Jehovah,
in whom is everlasting strength, may be with you continually,
even though you may not be permitted to know that He is near at times.
The language now sweetly arises, "`Lo, I am with you alway,
even unto the end of the world.`"
Do, when you can, give me a few lines, even if it should be like your last,
without beginning or ending, or rather without address or signature.
Once more wishing you God speed,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
S+++.+++ Lynes.

_Same date._--My dearly beloved H. G., how precious are your few words to me:
how do I long it may be as you say, "`that neither heights, nor depths,`" etc.,
may ever be able to separate us from the love we are partakers of, one with another.
I am very well, and often very happy.
We are going further on the sea-coast, where are no Friends, to have some meetings.
At Tynemouth tomorrow.
Farewell.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Warkworth, Twelfth Month 2nd, 1798.

Notwithstanding it is only eleven days since I sent a few lines to your sister,
it seems as though I could hardly forbear simply telling you, that in my exercises since,
you have been, perhaps every day, the companion of my mind.
I have remembered many of your sayings of old, and felt you near my spirit; indeed,
it is not new to me thus to be your companion,
although it has not been in my power to express much of it:
when I have been writing to others,
I have almost wished you could know how very dearly I have loved you.
Do you continue the same as when we were personally together?
suffering both in mind and body, and supposing you make little or no progress, after all,
in Divine life?
that you are not advanced in the experience of so dying to yourself,
as to live to Him who died for us?
If so, my mind can, even this moment, sympathize a little with yours,
for it is a discouraging apprehension; yet is it not possible to be groundless?
May we not think ourselves worse than God sees us, as well as better?
Therefore my affectionate counsel to you is, to dwell as little as possible on the past,
and endeavor to take courage; thanking Him from whom all our blessings flow,
for His unspeakable gift;
even seeing you have a measure of that which was His tried apostle`'s sufficiency.
You know it pleases Divine Goodness to work in a hidden way, in refining us for Himself:
have we, then,
more to look after than humble submission to His holy will in doing or suffering?
Oh! that this may be your whole endeavor, and I fear not for you,
but that blessed contentment will be granted your panting breast.
I view you as one who would not knowingly be satisfied, either in yourself or others,
with anything which is not of God`'s creating,
or that has not the sanction of His Holy Spirit.
I wish thousands were in this disposition; for surely in this seeking,
the promise will be verified that they shall find: so for you, my much loved friend,
my heart says,
the Lord grant you ability so to acquiesce in simplicity
with the secret turnings of His holy hand,
as that you may see of the desire of your soul, and be satisfied in yourself.
Thus I commend you to Him who, having made man`'s heart,
knows the most secret thoughts thereof.
I will now proceed to say how we have got on.
I think my last words were,
"`going to Holy Isle;`" accordingly we made for it that night: it not being accessible,
except when the tide is out,
we had to wait an hour after riding eight miles in high wind and hail,
that almost cut our faces:
it was about six o`'clock when it was thought safe to cross over on the sands,
three miles: we had two guides, one a chaise-driver, who had often been there,
and another, a fisherman of the island; but although they went first,
if I had not believed we were in the way of our duty,
I should have been in a most sad fright, for all before us was, in appearance, sea;
and after awhile we got in deep water, nearly up to our horses`' bellies.
I was in perturbation; so much so, that I could with difficulty proceed,
and so was my A. B.; but I was almost in hysterics, my spirits were so affected.
It was no light matter to have two heads of families,
two young men--one expecting soon to be married--besides Ann and myself, in,
what I thought, danger of losing our lives, and all on my concern.
Well, we got safe over, and had two meetings next day,
so as to liberate us the next morning, when the tide suiting, and by daylight,
we got very well to the other side again: had two meetings at villages,
two miles distant from each other, and it being moonlight,
went five miles further to lodge.
We have not been among Friends since at Shields; came to this place yesterday;
have had two large meetings today, which is First of the week.
These have been more comfortable than the last week`'s meetings,
for truly they were throughout more laborious than I can describe:
we have had also several private opportunities.

[.letter-heading]
To Hannah Huntley.

[.signed-section-context-open]
Newcastle, Twelfth Month 11th, 1798.

[.salutation]
My Dear Friend H. Huntley,

I want you not to suppose, that with respect to me it is, concerning you, "`out of sight,
out of mind,`" for truly it is not so; my love to you is, I hope,
of that kind which "`many floods cannot drown;`" and particularly of late,
you have been near.
I wish your encouragement, with my own, to go on in the way cast up for us,
although many may be our difficulties within and without: yours differ from mine,
and we both have our share.
I was near saying however, I believe you find what your capacity, in the Lord,
seems equal to at seasons, and so do I. Oh! then,
that we may be so wise as to endeavor to resign all into the hands of Omnipotence,
for it is in Him alone that pure help and refuge is to be found.

While I thus write my soul is exceeding sorrowful;
the Most High has some end in thus trying me, which may be hid from me.
As far as I know myself, my fervent desire is to be found in His fear and counsel,
and in that alone.
So here I rest and proceed to tell you, that we got here on First day evening the ninth,
after being absent from Friends four weeks,
having meetings to the amount of twenty-seven, and traveling nearly three hundred miles,
many times on bad roads and in rough weather.
My dear Ann Baker and myself are both finely; we have great cause to be humble and good,
for we are helped through many difficulties.
I cannot, you know, plan much,
but it would be no matter of surprise to me if we were at York Quarterly Meeting again.
We have been to the extremity of England in the north;
so that does it not seem as if I would go the length of my chain,
as my certificate extends only to England?

Poor Thomas Scattergood has received an account of
the death of his daughter by the fever,
in Philadelphia; he is very low I hear,
notwithstanding he appears to bear this affliction with much fortitude and resignation.
What a remarkably tried man he is!
Well, none are proved beyond what they can endure, through seeking after holy aid;
so may this be all our search, says your affectionate friend,
in best wishes to all your house and friends.

[.signed-section-signature]
Sarah Lynes.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Darlington, Twelfth Month 21st, 1798.

[.salutation]
My Dear Mistress,

I wish you to be assured my love is not diminished toward you and yours;
you are the frequent subject of my thoughts, yes, of my solicitude.
I often fancy myself in your family as heretofore,
and a partaker of pleasure and pain among you:
this is particularly the case in my sleep, as to pleasure and pain.
I see I have never had too little of the former, nor too much of the latter;
for oh! what nailing do we take to the cross; it is many times still hard to be resigned.
Since writing to Anner Mills last, many and sore have been the conflicts of my soul;
we have been among a people,
many of whose hearts appeared so uncultivated as to need the plough;
they nevertheless received us civilly in general:
with some of them we had the satisfaction to believe they were
measurably willing to be more given up to the great Husbandman.
We were a month away from Friends;
had in that time seventy-seven meetings and some private opportunities;
also visited a prison, travelled two hundred and fifty-four miles north of Newcastle,
and returned to Newcastle the ninth of this month.

Durham was a Nineveh to me; we reached it the fifteenth, and soon after arriving,
had to turn out in the streets and markets (although it
was snowing) to declare the word of the Lord to the people:
how had my spirit been straitened till it was accomplished!
I do not think I had ever, for so long together,
endured so much suffering as for many days was my lot, preceding this awful day; however,
in deepest humility, I can acknowledge to you, my much loved friend,
that in the moment of extremity I was not forsaken:
the Lord on high is indeed mightier than the noise of many waters.
He was pleased to be mouth and wisdom, tongue and utterance; although,
while thus endeavoring to clear my mind in one of the most public places,
a man came with much seeming consequence to endeavor to put a stop to it,
this did not hinder in the least: I had, beside my dear Ann Baker,
several kind friends with me.
My strength was exhausted with exercise before going out, but afterwards I was bravely,
and visited the prisoners that evening, forty-five in number,
who appeared glad of the opportunity.
Friends procured a room for a meeting next day, and gave notice in town and country,
both verbally and by printed papers:
some of the latter were put up in conspicuous places in the town, but these were all,
I think, torn down before night.
We thought this manifested a spirit of opposition, at which we did not marvel,
as it is a town abounding with idle clergy; one of them, being also a justice,
seemed to have no mind we should hold our meeting next day so publicly as we meant;
so informed the person who granted us the room, he was liable to a great penalty by law;
but after a little stir all was settled, and the meeting next day was large and favored;
at the close of this, we gave notice for another:
this latter meeting was to great relief--truth got into dominion;
the great Name was supplicated; the doctrines of the Gospel preached with Divine power,
and very largely; women`'s preaching, election and reprobation, water baptism,
and what is called the Lord`'s Supper, were particularized and clearly set open.
Our souls bowed in gratitude for these two days`' help and counsel,
in which all man-made ministry was decried and set at nought.
We had a precious season of retirement at our inn, and another at parting,
with most of our company who had come to Durham, but were not for proceeding with us.
George Sanders, of Whitby, has been our kind helper for nearly four months.
Oh! that I may never forget my own nothingness in
being helped within and without from time to time;
this ought to abase me in the dust, and, if I know my own heart,
it is not unfrequently the case.
Well, you will excuse my circumstantial way of writing;
I have not at present any lively communication,
and I thought you would like just to know how I get along.

The day after the Monthly Meeting here, we had a meeting five miles from this place,
and returned to lodge: this was such a meeting as I never before saw;
for soon after we were in, two men, very much inflamed by liquor, thrust themselves in,
and began to talk and laugh loud; they would not be prevailed on to go out,
nor to sit quiet within, so Friends brought (unknown to Ann Baker and me) a constable.
A+++.+++ B. had just appeared, and warned the wicked to the awing them, in some degree,
I do think: the constable ordered them away, but instead of obeying him,
they went to fighting in the midst of the people.
It became a dreadful scene of confusion and wickedness.
I could not have supposed my mind would have been so tranquil in such a trying time;
but so it was, that I kept my seat, and not once said in my heart,
I wished we had not appointed the meeting.
I believed it would settle, and so it did wonderfully, in less than half an hour,
so that the men were kept out, and a good meeting it proved in the end:
the fighters were wounded, but not very materially; and one girl got a blow on her head,
but not so as to injure her much: it was a marvel to us that more mischief was not done,
as they threw each other over the forms.
Our G. S. saw the men the next day, and they appeared sorry for their conduct,
so that we hope they will amend their ways.
We returned here in a good degree of peace, attended Friends`' meeting yesterday,
which was at length lively, through long waiting;
had a very large precious meeting last evening with the people of the town,
and have appointed another today six miles off.
We think it likely we may reach the Quarterly Meeting at York;
have nevertheless enough to consider of before then:
it is as much as we can do to live one day at a time.

Thus I have given you a long history, but wish I had some intelligence to convey,
rather of things not relative to my movements, but really I have not.
I hear very little that I could write about; so, in a great deal of affection,
I must say farewell, in best desires to all the family.

[.signed-section-closing]
Once more dearly farewell.

[.signed-section-signature]
+++[+++Not signed.]

[.letter-heading]
Sarah Lynes To John Burlingham.

[.signed-section-context-open]
York, First Month 15th, 1799.

[.salutation]
My Dear Friend J. B.,

Not your communication but your silence, stimulates me to use the pen a little,
partly to say, why have you ceased to give us a line at times?
and partly to assure you you are affectionately in our remembrance,
and frequently the subject of our converse.
My dear Ann Baker wrote to you from Allerton on seventh day,
previous to two large meetings there, to which we went in fear and trembling,
as indeed we mostly do to such assemblies; nevertheless, in retrospect,
there is no cause for complaint;
for the power of the Lord had the dominion in both meetings.
Next day, at Easingwold likewise, the unchangeable truth got uppermost,
although it was a time, as well as others, of decrying superficial religion,
and forms without substance.
We reached this city on the twenty-fourth,
and have got through a visit to the families of Friends.

My heart is, even now,
warmed with that love that is "`strong as death,`" to that dear man of God,
T+++.+++ B. I most affectionately desire he may know the winding up of this life,
so full of trouble,
to bring him the blessed experience of having "`fought the good fight,
and kept the faith,`" that so the crown of righteousness
may be forever and ever the reward.
And oh! that you, my beloved friend, may likewise so fight as to obtain.
How did the apostle fight?
Was it not so as, from time to time, to keep his body, or nature, under;
even in subjection to the Prince of Peace.
My soul in, I trust, a little fellow-feeling with you,
breathes for your acceptance with the Father of spirits,
by your thus maintaining the warfare.
Let us believe in the power we feel within, which is of God; that,
thus believing even in its sufficiency to work, in us and for us, to our redemption,
we may yield implicitly thereto, and thereby stand in our ranks in true righteousness.
I know many are your secret cogitations,
and perhaps the jealousy you sometimes feels over yourself, may be,
and is blessed to you.
May the Most High increase the travail of your soul after Him,
and grant you therein the desire of your heart.
Yesterday we parted with our kind friend, that humble-minded man, George Sanders;
it brought us to reflection, and nature was pained.
I suppose we shall have two or three public meetings hereaway,
and then make for Sheffield, where, I have no doubt, bonds and afflictions await us;
but ought these things to move us?
No; I most assuredly believe, that when darkness and distress overtake any of us,
we should endeavor to stand still, judging nothing till the light again appears,
and that then we shall "`see the salvation of God.`"
Oh how glad I am I can now say so!

Well, I have not much to add: may just say I have sat ten meetings here in silence,
I believe rightly so,
and have been glad in my beloved companion`'s appearances in most of them.
Now dearly farewell, says

[.signed-section-closing]
Your true friend,

[.signed-section-signature]
S+++.+++ Lynes.

Remembering, with great affection, every one of your sweet flock.

[.letter-heading]
To Samuel Hull.

[.signed-section-context-open]
York, First Month 21st, 1799.

[.salutation]
My Dear Friend S. H.,

Very often of late, have you been the companion of my mind,
in affectionate desire that you may know the good Hand to be near,
to sustain you in every trial and difficulty which may be permitted to befall you,
and to lead you on hereby in the way everlasting.
I wish you not to suppose in low times,
that because you feel yourself poor and stripped of good, you are,
in the eyes of Omniscience, cast off as one unworthy of His favor:
this may at seasons be almost the conclusion in retrospective view,
when former omissions and commissions may stare us in the face;
when we may see that we have not come up in such faithfulness to the Holy will,
as might have been the case, had we made use of the means graciously afforded:
this scene may be sometimes magnified, in your sight, beyond reality; but,
my dear friend,
shall we not endeavor to "`leave the things which are behind,`"
even reaching forth unto those which are to come;
keeping in view "`the mark for the prize of the high calling of God,
in Christ Jesus our Lord.`"
Surely, if this is your engagement,
your strength will be renewed and increased in Him who is the fulness of strength.
I feel His love in my heart for you while thus writing, or I am mistaken;
your spirit is near to mine, in the tenderness which this love causes.
I desire no temptation or trial may be found too hard for you, but that,
by dwelling near Him who has visited,
who has been as the bright and morning star in your soul, He may prove the Finisher,
as well as Author of your faith.
I desire this also for your dear partner in life; my love flows towards her.
Please tell John and William I have not forgotten either of them or theirs, in dear love:
the dear friends at Uxbridge and Amersham are near to us.
We do not know when we may leave this York; we feel still bound in spirit:
are now principally engaged in meetings and villages round about;
but today has been occupied in visiting the infirmary and a spinning school.
This concern lay heavy on me for some days;
so that getting through it as well as we knew how, is some relief.
tomorrow is the usual meeting day here; what is to come after I cannot say,
but I hardly think that will liberate us: may we only aim at being in the Master`'s will,
then all will be well.
This is my desire for my absent friends, with my own soul.
In this, farewell.

[.signed-section-closing]
Your truly affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
York, First Month 26th, 1799.

Perhaps it is a low time with you--a time wherein you may be ready to say,
"`How long will You forget me, oh Lord?
forever?
how long will You hide your face from me?`"
If so, may you, my dear friend,
endeavor to believe that His covenant is as sure with the night as with the day;
so will He most assuredly keep you in the hour of darkness, and in His time,
cause the day to bring all its rejoicings to your soul.
How often have you known Him thus to work for you!
Why need I tell you of these things, who am myself in deep suffering of spirit,
in doubting and in fear?
Surely it will not do to cast away our confidence, because of this being our condition;
therefore I have said to my soul, "`keep your hold, and if you perish,
perish in this endeavor.`"

I have been looking back,
and do not remember such a succession of probations
for so many weeks as has now been my lot;
but is it not designed for some wise purpose, unseen by me?
What I am surprised at is, that I appoint meetings, etc., in this state; but so it is;
for since the visit to the families of Friends here,
we have had many public meetings at villages round about;
have also paid a general visit to the infirmary here, and to the city prisoners.
In the former we had four solemn opportunities with the patients,
several of whom where much tendered; but one girl, in particular,
who I suspected to be far from a good character, while I was standing by her, speaking,
burst into tears.
I had to tell her the arms of mercy were wide open to receive her.
The portion of relief or quiet granted,
from endeavoring to do this bit of work faithfully, was more reward than I looked for:
my soul was deeply plunged into distress previous to this visit.
We had one season with the superintendents.

I have heard of +++_______+++`'s death,
and that it was rather thought to be occasioned by the rough usage of some of the rebels.
I should be glad to know as much of things of this nature as is proper to write.
My mind is many times sorrowful about Ireland: and how is it among Friends?
Are they increasingly of one heart and one mind?

_28th._--Yesterday being First day, we were again with Friends in the morning:
my A. B. was silent; I was not,
although this silence had been my lot for ten meetings before, not all successively.
We had a very large public meeting here last evening,
which was favored with light and life from the Lord God and the Lamb, so as,
for the time, greatly to dissipate the gloom which had hung over my mind.
We are to have another today, and perhaps one tomorrow.

If I should ever see Ireland again, how different the scene!
Oh! what some of you must have passed through during such a day of treading down;
my soul feels with and for you, in measure; I cannot to the full.
Shall I ever see some of you to converse on these things, face to face?

I had a letter this morning from my former dear companion, E. Raper, very encouraging;
her language is, "`Your love was never more precious than of late.
I believe you were never more frequently the companion of my mind,
in a degree of that sympathy which is far beyond words:
my spirit is sometimes dipped into such a sense of the bitter cups handed unto you,
as a test of your faith and obedience, and no doubt in mercy,
to deepen your spirit in the root of life, that, according to my small measure,
I can say, '`deep calls unto deep.`' When the apostle was deeply tried,
the encouraging language was,
'`My grace is sufficient for you;`' and have you
not many times been favored with the blessed experience,
when vain was the help of man--when the secret cry of your soul has been,
'`Oh Lord I am oppressed; undertake for me.`' You have passed, and, I doubt not,
are still passing through the dispensations of seed-time and harvest, summer and winter,
heat and cold, day and night; and so long as the language of your spirit continues to be,
'`to do your will, oh God, is my joy`' you will, no doubt, again have to acknowledge,
with songs of deliverance,
'`He makes my feet like hinds`' feet.`'`" She farther speaks of her desire we may,
at the winding up of all things,
be enabled to appear before Infinite Purity as the prophet did--"`I beseech You, oh Lord,
remember now, how I have walked before You,`" etc.
This, with more like it, has this good woman communicated; and,
in telling you that you have been oftener with me than every hour, for days past,
I may say, all this is the language of my soul to you, according to my measure; yet,
perhaps, I could never find words to speak thus.
I renewedly remember, in feeling feeble and stripped,
while this work is in prospect of public meetings, etc., your language to me once,
"`that you had heard the best preparatory qualification for religious movements is,
not to be sensible we have any;`" in this I endeavor to rest,
leaving all to Him who is omnipotent.
Most affectionately thus do I commend you to Him, with my own soul, my endeared friend,
and say farewell.

[.letter-heading]
To one of Sarah Grubb`'s Children.

[.signed-section-context-open]
Sheffield, Third Month 17th, 1799.

Your late remembrance of me in the epistolary way is grateful.
I think I have not a greater joy than to understand the numbers are increased,
who are willing to account the reproaches of Christ greater
riches than all the treasures of this fading world,
whether of gold and silver, or wisdom and honor.
My heart often yearns toward you in natural affection,
and at times in something that will live beyond it;
even feeling the purity of that influence which breathes undefiled rest.
I long every one of you may be so obediently given to the will, way,
and work of Omnipotence in you, as to know your souls anchored in Him,
through the greatest tossings now attendant, or that may be attendant; and,
as dear S. G. said, experience such an interest granted in Him,
as to give victory over death, hell, and the grave.
Ah! my dear E., this is being made "`more than conqueror through Him who has loved us,
and given Himself for us.`"

We have been closely engaged for three weeks, visiting families here,
and taking meetings in course;
none of the latter have been without many of the towns-people at large,
and they have all been lively, which is a great favor.
We have had more than one hundred private opportunities, but have not yet done:
we may perhaps find work enough (without seeking any) till next fourth day week,
when the Quarterly Meeting is to be held at Leeds.
Dear E. H. is a precious companion to us--a sweet baptized spirit.
She had many difficulties to encounter in joining herself to us;
not among the least is her dear father`'s declining health:
he seems gradually going to a better country.
Oh! the inexpressible good to be felt near him,
even as one who has well nigh finished his course,
for whom a crown of righteousness is in store.
Oh! may the God of all power be with you all.
I feel more than I can express about you, in the present state of things:
in supplication this afternoon my soul remembered you, in which I was and am glad;
believing it was not of myself, in which, indeed, "`dwells no good thing.`"

Well, my dear, with a heart warm with affection, I most tenderly say,
in the best sense of the word, farewell.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Seventh Month 1st, 1799.

After wading through exercise in both meetings, to get at the pure life,
and lifting up my voice twice in testimony and once in supplication,
as also once in a religious opportunity in a family,
I had the comfort of reading +++_______+++`'s dear, kind letter, in this little cottage,
to my endeared mother and sister, who were both, with myself,
much affected with the manifested kindness and tender care coming from you.
And oh! dear +++_______+++ while I contemplate the ways of Omnipotence,
and firmly believe He does all things right and best,
how is my sympathy excited with you in your late exercises,
and perhaps in your present conflicts.
I feel for you, but cannot help you; yet this is my comfort,
you know Him who can help under the most crucifying dispensations.
It is no doubt hard for you all, at all times to say, "`The Lord gave,
and the Lord has taken away; blessed be the name of the Lord,`"^
footnote:[Alluding to the death of some near relatives
of the friend to whom the letter is addressed.]
yet, as this disposition is cultivated,
does it not cause the mountains and hills to be removed?
How does the language sweetly occur while I write,
"`with everlasting kindness will I have mercy on you, says the Lord,`" etc.
With respect to yourself in particular, I feel as though I almost dared to say,
there are seasons to your tried yet innocent, and in some precious degree,
sanctified mind, wherein heaven is as brass, and earth as iron;
well then--"`Thus says the Lord, your Redeemer; although, for a small moment,
I have hid my face from you, yet with everlasting kindness will I have mercy on you.`"
Surely you well know this promise is to be our possession,
through our keeping the word of His patience;
let us therefore be encouraged so to do in the deepest affliction,
when the ways of wisdom are totally past our finding out.
I write this, not from having gained experience,
but from a heart replete with desire that all the designs of Infinite
Goodness may be fulfilled in and concerning my dear friend;
and not only you, but all of you,
notwithstanding you may be more learned in Christ`'s school (who
suffered for us all that we can possibly suffer) than myself;
and I know you can understand me in what I write,
however deficient the expression of my feelings may be.

It is a great satisfaction to my relatives and myself,
to be permitted to partake of each other`'s society;
and although it is my experience still that this is a state of probation,
I am thankful to have been employed as has been the case for nearly two years;
and that the time for retreat was so clearly seen, as to admit of no doubt at all.
I could hardly have believed it, had any body told me it would be so.

I have often thought of Mary Peisley since coming home,
for very many have been the solicitations of kind
friends to go and recruit at their habitations,
which are larger,
and have attached to them more of temporal abundance than our little home;
yet these things are all nothing to me; this seems the place for me at present.
While it was my lot to travel about from place to place,
many (as you are aware) were the baptisms dispensed; and, at seasons,
it was as if my soul was plunged into as deep distress as
could be sustained with the degree of capacity granted me;
and no example, however bright of itself, afforded lustre to my path;
that not only the sun was in my view darkened, but the stars withdrew their shining.
Oh! you know it is hard to keep the faith and the patience at such times,
but it is a blessed thing to keep constant, and be a true believer through all;
far more blessed than we can describe: is it not being a true believer,
to endeavor to stand still in the dark?
for it brings to the acknowledgment, even to the full,
"`Great and marvelous are your works, Lord God Almighty;
just and true are all your ways,`" etc.
Yes, my dear friend, does it not increase our union and communion with Perfection himself?
Now, in humility of mind it is my language, "`You know, oh my heavenly, merciful Father,
and unerring Guide, how I have followed You in my late travels,
in the cross to my own will, and in your fear and dread, into large congregations,
into markets, unto the habitations and beds of the sick,
and sometimes to the houses of the great, with a message from You;
sometimes to individuals in the highway, at others, into jails and prison-houses:
this among those who are not professing the truth as we do;
as likewise to those who do.
You have been pleased to make my feet as hinds`' feet,
and lifted up my voice like a trumpet,
to show this people their transgressions--the house of Jacob their sins.
You have made me a comforter to the comfortless and the weak.

[verse]
____
For all I bless thee, most for the severe.
____

I am now under a sense of being helpless, as the worm in the dust, without You!
Oh keep me here continually, and be my all in all.
Amen.`"

Thus do I also commend you to the inexhaustible and unmixed Source of sufficiency,
and say dearly farewell, in much love.
