== Chapter 5. Letters from 1799--1801

[.letter-heading]
To one of Sarah Grubb`'s Children.

[.signed-section-context-open]
London, Seventh Month 24th, 1799.

It may perhaps appear long that you have looked for a compliance with your request,
to let you have a little of my scribble; but now, time and inclination uniting,
I am desirous there should not be any further delay.

You have often been the subject of my thoughts since seeing you,
and my heart continues at times, both sleeping and waking,
to glow with affection towards you, together with your dear mother, aunt, and sisters.
It would be highly gratifying, in the disposition of mind I sometimes feel,
to see you at Anner Mills; but as that must be left, I endeavor to picture you in idea:
and oh! my dear,
when there is ability sensibly to desire for myself the greatest blessing of all others,
even Divine preservation, my soul cannot forget you, my distant friends,
yet who are in one sense near: may He who has not failed to do much for some of you,
so be sought unto in all, as to be found as a wall on every hand.
I want that we should be encouraged to feel after
Him in our different situations and allotments,
so that an increase in Him may be our experience.

I have continued to assist in keeping school, and taking in a little needlework,
since the Yearly Meeting; so that my hands, with that and attending meetings together,
have been pretty full.
My mind has often felt sensations of gratitude to my Heavenly Father,
in permitting me this little space of time without traveling,
wherein I have enjoyed the society of my endeared mother, etc., in their humble dwelling;
but there does not seem a probability of much continuation of it, for I was constrained,
in our last Monthly Meeting,
to leave with Friends a prospect of visiting families
belonging to Gracechurch Street Meeting.

It seems nearly time to say farewell for the present,
which I do in more tender regard than my pen will set forth.

[.signed-section-closing]
Your friend,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Ninth Month 23rd, 1799.

I am diligent in getting to my own meeting, but it takes a deal of time,
and I am often hurried; but with all my troubles and bodily exercises at home,
I am very frequently told how much better I look than when traveling;
indeed I find home agrees with me very well.
I left home this morning to attend our Select Quarterly Meeting, and it being a long way,
have not got back to dinner.
I am ready to conclude, my dear,
you resolved not to endeavor to give much intelligence of the state of your own mind,
when you favored me with the lines I am replying to;
but although you may think it of no use to try to convey your feelings to any mortal,
and yet secretly may lament your state, which do you not compare to a wilderness?
I say, nevertheless, He who gave Hagar to acknowledge,
"`You God see me,`" even He regards your low estate,
and will reward according to the purity of the intention; so be consoled in hope,
and trust wholly in Him, who gives "`beauty for ashes,`" etc.
I love you much while writing, as at other times,
and desire you may be strengthened to stand in your allotment.

I have now returned home, and have eaten my supper with mother, who is talking about you,
and asking what sort of a friend you are: I reply, with my pen in my hand,
"`She thinks it a fine thing to be a preacher;`" at which she smiles,
and wonders you are so unlike the generality of mankind.

Friends in London take more notice of me than I could expect;
particularly Joseph G. Bevan and his wife, and R. C. and his.

Thomas Scattergood I understand is in the north;
but I don`'t know much about such good folks, so cannot inform you;
only I must say my Ann Baker is really likely to go into
the land of matrimony before a very long time.
I wish it may prove a blessing to her.
You don`'t say anything like any of you setting off for that land: how is it?
Do you think of staying where you are all your lives?
You will think me in a droll humour; well,
if it is not unseasonable when this reaches you, I think it allowable;
but if you are in affliction, shall be sorry I gave way to my natural volubility.
I am not infrequently with you in my dreams,
and long to have an interview with you when awake, but that must be left;
so in commending you to the all-wise Disposer of events, with myself,
I take my leave at present.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Stepney Causeway, Tenth Month 2nd, 1799.

[.salutation]
My Dear Friend Sarah Grubb,

I have long wished to manifest my continued, undiminished regard you-ward,
by thus addressing you; and one pretty fair opening presented to my mind,
which having been let slip, warned me against a second omission of the same kind;
for you well know we cannot always feel ability for this employ.
Your family are the daily companions of my affectionate remembrance and solicitude:
I do hope the eternal arm of Omnipotence will be your succor,
even "`although the blast of the terrible ones may be like a storm against the wall.`"

Yesterday, through the medium of a letter from my beloved H. G.,
I received the mournful intelligence respecting the secret workings of the wicked,
in their plots and cruel designs; how dear Clonmel was by them intended for destruction:
this account has awakened emotions of tender sympathy; please tell her so,
with my dear love to them all; and while my mind has contemplated the subject,
it has adored the wisdom of Infinite love and compassion.
Cries are raised in my soul unto Him on your account, and I remember the declaration,
"`You will keep Him in perfect peace whose mind is stayed on You,
because he trusts in You,`" and, "`They that trust in the Lord shall be as Mount Zion,
which cannot be removed;`" so that I am consoled in hope that you,
who endeavor to love Him with all the heart,
will experience His holy help in all adversity from without or from within;
even should He see fit to vouchsafe this help in
such a way that you cannot know He is near,
but are ready to conclude He stands afar off from your cry;
"`For my ways are not your ways,`" says the Lord,
"`neither are my thoughts your thoughts; for as the heavens are high above the earth,
so are my thoughts higher than your thoughts.`"
Sometimes I have believed my spirit has witnessed fellow-feeling
with yours in secret travail on various accounts;
and now how does my heart yearn, while writing, towards you and yours with best desires;
the extent of which I must leave you to conceive,
for my pen will not reach the description: but while so desirous of not only the present,
but eternal good of my beloved friends, let me not forget my own interest,
by being too inconsiderate of my duty.
Truly I find it a task daily repugnant to nature,
to be engaged fully to stand open to holy conviction,
watching against the many propensities that would frustrate Divine intention,
were they given way to; and I am afraid at this moment, that since my return home,
in a particular manner, the watch has not been sufficiently maintained;
so that my present situation of mind is that of looking
for judgment "`to be laid to the line,
and righteousness to the plumbline;`" and oh! for
acquiescence with the Hand that does all things right.
Notwithstanding this acknowledgment,
I may say that my soul has been not infrequently
bowed under conflict and exercise of various kinds,
since being permitted to have the company and help of my dear relatives.
One day lately,
I thought my state might bear some faint resemblance in miniature to dear Job Scott`'s,
when he describes it as making his flesh sore,
or causing his body to feel as though he was ill.

When the visit to Friends`' families of Gracechurch Street is to be moved in,
I cannot exactly say, but feel it growing rather heavy:
my natural disposition flinches in some degree from the arduous engagement,
but it is only arduous by comparison;
and I ought to be thankful that it is not to go into the public places,
seeing that it seems to be the Divine will that an easier track should be followed,
at least for the present.

My pen scribbles the language of my heart, in commending you to Him who can say, "`Peace,
be still,`" and the storm shall cease;
oh! may He be to you and many others among you (to whom
I feel flowings of love) the source of all-sufficiency.
Amen, says your affectionately

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
Thomas Scattergood to Sarah Lynes.

[.signed-section-context-open]
Uxbridge, Eleventh Month 6th, 1799.

[.salutation]
Dear Sarah,

I think you and I have not exchanged letters since we were in Ireland together.
I felt near sympathy and love towards you then, and I don`'t know that it has diminished.
My heart has gone with you in your arduous journeys in the north;
and following you (in part) in the same line,
the good savor you have left behind has been very pleasant.
Oh! may you be always preserved in the same meek and humble condition,
a grateful receiver of the many mercies and favors bestowed on you;
for you well know it is by being reduced into littleness and nothingness,
that such are made instruments in the Divine hand.
You have been, in my apprehension, a child dandled on the knee;
you have been favored with clear prospects,
and a heart given you to answer them with cheerfulness.
This was my situation when younger in the labour;
but now I must be content with less sight, and walk by faith.
The Master best knows what is best for His servants:
perhaps it never may be your lot thus to be tried; and however it may be, whether so,
or continued in the customary manner of open vision,
be faithful and do your work in the daytime.

I feel unity with your prospect of the family visit: dwell deep,
and you will be favored to speak the word faithfully.
Baulk not your testimony,
and then you will receive the reward which the Lord gives to them that know Him.

My love to your mother and sister, and accept the love and sympathy of your poor,
exercised brother in bonds,

[.signed-section-signature]
T+++.+++ Scattergood.

[.letter-heading]
Sarah Lynes To +++_______+++.

[.signed-section-context-open]
London, Second Month 19th, 1800.

I believe my pen had been employed before now,
in acknowledging the receipt of your last acceptable, relieving, but plaintive lines,
had I not thought it very soon to write again, and it seems soon now;
but being at Plough Court this afternoon,
out of the noise of our little folks at Stepney Causeway,
and withal having the heart-ache,
am willing to please myself by conversing thus with you.
I have perhaps, nevertheless, very little to say worth your notice,
and do not apprehend it will be my lot to administer anything like the rod.
Is it not said _that_ is for the fool`'s back?
and must not I be convinced of your being one of that description,
before I can think it your due?
However, my dear friend,
I am sure of feeling enough desire for your real
good to be willing to speak to your state,
did I know it.
If that be at this moment hid from me,
yet am I aware that your disposition to be jealous of your own purity of intention may,
and perhaps sometimes does, prompt you to conclude differently to the true witness.
Have you not, at seasons, found yourself out in this?
You know I mean you are apt to estimate below the _truth,_ when measuring yourself;
but I have marked the hand of Divine Wisdom you-ward from year to year;
how it has renewed your faith and confidence in everlasting sufficiency,
by its gentleness as well as constancy; and oh! says my soul, may it never leave you,
but succor still every virtue, to the glory of Him who is worthy of glory,
and to your own consolation in Him.

_24th._--I was interrupted in this letter by going to a public meeting,
which Thomas Colley of Sheffield appointed; he has had several in this city,
being here for that end.
Thomas Scattergood is also here,
and was powerfully engaged in a meeting T. C. appointed last evening,
for the young people of our fold.
T+++.+++ S. and W. C. with three others, took tea with us, besides Joseph and Rachel Smith.
Do you not think we were highly favored?
William does not think Friends of Gracechurch Street need,
or should be in a hurry to remove me by recommendation to another meeting,
though I now live in Ratcliffe quarter.
I mostly trudge to town to meeting First and fourth days, perhaps two miles and a half,
but am rather attached to that large mixed meeting,
where I lately witnessed the holy oil to flow from house to house.
I have more than once, after lifting up my voice like a trumpet on First day morning,
had an anonymous letter sent me, expressive of some disapprobation with the discourse,
as they call it; but these things are not of much account in the balance,
for I think they must be cowards and afraid of the light,
who do not choose to let their name be added to their admonitions.
But though I keep pretty much to my own meeting, it is not wholly the case.
I sometimes attend Ratcliffe and others: was at Westminster on fifth day,
at a marriage between Thomas Christy and Rebecca Hewlings.
I went with a burdened mind, not intending to go to the house to dinner;
but having no opportunity in meeting to get clear,
was induced to alter my intention and be one of the company, without a wedding garment.
We had a table nicely spread;
but I lacked the best sauce (hunger) as is mostly the case with me on such occasions.
After dinner nothing occurred to liberate me, and not till after tea,
when we gathered into stillness;
and several bore testimony to that which is unchangeably excellent,
and Thomas Scattergood appeared in supplication;
but I felt bound in spirit to the very last, when feeling the holy anointing to minister,
relief was obtained.
In writing thus freely to my beloved friend, I remember the language,
"`I am the Lord your God which teaches you to profit;`"
and oh! that I may never move without Him,
let the suffering be what it may.

I must bid you now farewell; which I do with a heart warmed, even while I write,
with that which breathes undefiled rest and peace in Him who is holy.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Settle, Fourth Month 5th, 1800.

[.salutation]
My Beloved Friend Sarah Grubb,

Very often have I wished to write you a few lines, for many months back.
I do hope not to be forgotten by you, although so far and so long separated;
on my part I can truly say my mind is often wafted into your habitation,
and visits you individually in tender affection and solicitude;
desiring that the blessing of Heaven above and of the earth beneath,
may be continued to you in the Divine will; that so His name,
who is the great Superintendent, may be magnified, and your "`peace may flow as a river,
and your righteousness as the waves of the sea.`"

The three Quarterly Meetings (Leeds, Lancaster, and Kendal) were to me seasons of relief.
I had attended three for York successively, when out with a certificate before;
but after each and all of them, my spirit was deeply burdened, not being able to unload:
now how different!
And but for being of the same sentiment that I remember your once expressing,
that ministers were not often competent judges of meetings,
I would say truth had the dominion, particularly at Leeds;
and through great struggling and wading, at Lancaster and Kendal;
the latter of which was, on the whole, more eminently favored than that at Lancaster.
I am glad of this employ between the two meetings here,
for my mind is not in a state for company,
and I don`'t like secluding myself from friends.
On this account I often sit under painful inward conflict,
while those I am with think all is smooth and well, or at least some of them.

If you have not already heard it, and it be worth telling, I may add,
that since the resignation of my certificate, after last Yearly Meeting,
I have been solicited for marriage by a young man of London.
He has got his final answer; my judgment being clear, that I might not encourage him.
He is of good character, and in good business.

_Leeds, 7th._--This is an odd sort of letter,
but hope you will receive it as the best written testimonial of my endeared regard,
that my shallow capacity is at present equal to produce.
I write so little in general,
that I have not enough practice to make much of it worth perusing.
We sat with Friends at Settle yesterday morning,
and their meetinghouse was filled with others in the evening.
Though for a while last night, in meeting,
it seemed like going under the mountains to feel after the seed in the people`'s hearts,
way was gradually opened, and life became predominant; for which my soul,
in humble gratitude, praises that great Name,
which is the place of refuge for the upright in heart.

I believe I shall remember you at your approaching Quarterly and Yearly Meetings.
May everlasting goodness and mercy be with you.
Amen.

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To Hannah Grubb.

[.signed-section-context-open]
1800.

My dear Ann Baker`'s marriage was attended with sweetness.
She appeared in testimony previously to their taking each other by the hand,
and twice in the day afterwards: as I was to meet my companion at Birmingham,
I had the privilege of seeing her home,
and staying at Worcester from seventh day till the following fifth,
during which time I was mostly indulged with social satisfaction,
but had one meeting with the people at large, and two with Friends.
We made an excursion to Malvern, eight miles distant from Worcester,
where we were delighted with the admirable display of the beauties of nature,
in the country; but, without attempting a task I am unequal to,
that of describing the scene,
I hasten to tell you that I think we had a mark that this innocent
gratification was not displeasing to our Heavenly Father;
for, as we had descended a little below the summit of the highest hill,
sitting down to rest on a bank,
an uncommon degree of Divine light and sweetness spread over my mind,
under which I recollected a dream I had in the winter,
and felt the opening of life to tell it to my companions,
and that the reality was then my experience.
I dreamed I was on an eminence, surrounded by my fellow creatures in their habitations,
and under great exercise for myself and them,
when serenity and sweetness preciously diffused itself into my soul,
and my tongue was loosened to sing "`Alleluia, Alleluia.`"
The relation of it,
together with enlargement through the Gospel light vouchsafed at the time,
broke us all into contrition.
My dear Ann said a little matter, and supplication was poured forth,
with thanksgiving and praise to Him who shuts and none can open,
who opens and none can shut.
We went home under the consoling persuasion that He mercifully cares for His little ones.
I felt the incomes of love and life so strong, while thus, as it were,
unbent with my dear Ann,
that we reckoned it might be intended to answer the purpose of the forty days`' food.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Carlisle, Ninth Month 8th, 1800.

Somehow you have been uncommonly the companion of my mind for several days past,
in a flow of love, and, I think, best fellowship;
though these feelings have not been lacking towards you at many other seasons,
when I have not been prompted to disclose it, by sending you a paper messenger.
My consolation respecting you and some others of
my dear friends in Ireland and elsewhere is,
that as they keep their ranks in righteousness,
their habitations will be found invincible,
through all their conflicts from within and without.
It has seemed to my unworthy soul, at times,
as if I could behold many near and dear in the covenant of life,
filling up their measure in the militant Church,
under the holy banner of the ever victorious Captain;
and notwithstanding some of these may not be in very conspicuous stations,
I have no doubt of the reward being to such,
equally with that of others who appear more in the front of the battle.

I want you to gird up the loins of your mind,
and be strong in Him who has hitherto been with you,
by His invisible power sustaining your exercised spirit, when you could not know it.
Whatever your present circumstances may be,
my heart craves for you a holy confidence in the Eternal Rock.
"`The name of the Lord is a strong tower; the righteous runs into it and is safe.`"
I know, if you could believe yourself one of this number,
your spirit would often have more rest from trouble;
but your endeavors in the Divine fear have not been, neither shall be in vain,
in the fulness of sufficiency: so that, dear creature,
however long and painful the struggle, persevere in the resolution,
I will get me "`into the clefts of the rock,
into the secret places of the stairs,`" in desire to be
again and again acquainted with that voice which is sweet,
and that countenance which is comely; even to enjoy His presence,
and receive His renewed instructions, who is to you the chiefest of ten thousand.
Do I not feel something of a certain evidence of Divine truth,
that thus He will be still and increasingly to your soul, "`Wonderful, Counsellor,
the mighty God, the _everlasting_ Father, and the Prince of Peace.`"
Whether we meet again in mutability or not,
I hope we shall be inseparable in the best sense--seeking
an increase of acquaintance with,
and in Him who is immutable.

You have many visitors lately from this land: it will be well if you are mutually edified.
I wish it with all my heart.

We met with David Sands at Darlington, who was making for Scotland.
He had been at York, principally to see a great woman who is likely to join Friends.
I think her name is Elizabeth Sanderson, but she has the title of Lady.
His visit was very satisfactory,
she appearing in a disposition of mind willing to "`endure the cross,
despising the shame,`" though she suffers much from her connections.
She was about purchasing a stuff gown, and objects to costly clothes,
equally with gaudy ones, which seems to me instructive.

Now, to tell you a little respecting our pilgrimage,
I think we have no reason to do otherwise than humbly thank God, and take courage;
having hitherto been helped through.
Yet, my dear friend,
our conflicts have often been equal to the capacity granted to endure,
so as not to make shipwreck of faith.
At Darlington the bitter cup was drank of going into the markets,
and declaring the Lord`'s word to the people: I dare not doubt of its being His word;
for, as with consuming fire,
I think my own willings and runnings were surely subdued preparatorily.
This I frequently find I am called to submit to,
for how apt to be choosing and refusing is this natural mind!
We were unmolested, and there appeared to be openness to receive,
in the second place especially, which was also the last.
I go, as heretofore, visiting my dear fellow creatures of most descriptions,
whether in hospitals, in prison-houses, or at large in the world.
At Appleby we had, besides a public meeting,
a solemn season with the poor things confined in the jail, who were not great in number,
and, I believe, have suffered hard imprisonment, some for years.
It was affecting to see some of their countenances so dejected,
in going round to shake hands with them: four or five were laden with irons.
Lately my spirit has been pretty much in secret mourning and lamentation,
feeling my own frailty,
and being sensible of the miserable condition of some high in profession, who,
nevertheless, are making beds for themselves, and stretching upon couches; yes,
as to the spirit of this world, are taking in large draughts,
like drinking wine in bowls;
even that wine which mystery Babylon presents in her golden cup:
but these are not "`grieved for the afflictions of
Joseph;`" and when the gracious call is going forth,
"`Come out of Babylon, my people,`" etc., they are evidently asleep in a spiritual sense.
Yet I remember that there are many under our name,
whose spirits are very different in the holy sight; whose tents are goodly;
whose dwelling-places are beautiful; whose fortification is the fear of the Lord;
whose language is, "`Walk about Zion, and go round about her: tell the towers thereof.
Mark well her bulwarks, consider her palaces,`" etc.;
and I have no doubt but this Zion of God, this true Church,
will call a nation that she knew not,
and nations that knew not her shall yet run unto her, because of the Lord her God,
and because of the Holy One of Israel in the midst of her;
and I often feel grateful in being a member of this Society.
My mind is more revived in writing to you this evening, than it has been for many days,
perhaps weeks back; though I did get some comfort by weeping a few nights past,
till hours after midnight, which did not unfit for next day`'s travel and two meetings.
Yesterday we were at Wigton; had a meeting with Friends,
and another very large one with the people indiscriminately;
came nine miles this morning to meeting at Moorhouse, and from there here four miles.
I feel pretty well on the whole, though I have no appetite, and am weak;
but in expectation of some sleep curing me.
I don`'t know what would become of me many a time, were it not for "`balmy sleep.`"

[.letter-heading]
To Ann Pumphrey +++[+++formerly Ann Baker].

[.signed-section-context-open]
Allanby, Ninth Month 13th, 1800.

[.salutation]
My Dear A. P.,

We have wrought as hard lately,
as at any time when you and I were partners--gone to bed late and risen early,
having sometimes two or three religious opportunities,
and travelled four or five miles to a half-past seven o`'clock breakfast.
Doesn`'t my Ann think we earned what we partook of?
Your accounts, my dear, seem very pleasant about your change of scene in life;
I long for an interview with you again, but must have patience.
We were under the necessity of going into the market-places at Darlington,
which you know to be a very sore exercise,
but Divine help was revealed in the needful time.
We were unmolested, and in the corn-market there appeared some considerable openness.
You may recollect how +++_______+++ spoke respecting the
engagement of exposing ourselves in the markets,
and seemed to think it might be better to visit the villages instead; but I assure you,
when I was under the exercise, she being at Darlington at the time,
it brought her to the weeping cross in sympathy.
It does me good to see the wisdom of the creature give way.

I should be glad of an epistle from you, but I will not be unreasonable in my requests,
lest I should encroach too much on the time of a wife and mistress.
Your S. L. cannot plead excuse in these engagements,
but every sphere in life demands our time and talents,
where we are solicitous to move rightly in them.

[.signed-section-closing]
Your very affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Kendal, Tenth Month 24th, 1800.

[.salutation]
My Dear A. P.,

It is with difficulty that I can retire to address you in this way,
but not without strong inclination.
It is likely your dear S. P. is yet on his travels,
and I wish this may reach you while that is the case, as you may often be lonely,
however kind your relatives are.
I feel for you both in the necessary separation,
but remember unto whom _all_ things are to work together for good;
and it may be well that you should live loose from each other,
as from every temporal good or social joy.

Did not I mention, when enjoying your society at Worcester,
an apprehension that this journey would be extremely exercising to faith and patience:
such was my secret sense at that time, and so it has proved, and is likely to prove.
I have frequently, in recurring to my feelings then, remembered the declaration,
"`I tell you these things before they come to pass, that, when they come to pass,
you may believe.`"
Oh that I may but be one of those true believers, unto whom all things are possible;
for it seems to me that the dregs of the cup of suffering are yet to be drank of,
as it relates to this turn-out from home.

How did you hear of the engagement in the market-place here?
I need not attempt to describe the situation of either soul or body under it to you;
but may say the engagement is no easier by repetition.
I think I suffer as much as ever about these things; perhaps more, if possible;
as the fear of riots in the markets presses upon me, and also upon friends;
yet this has not excused me, as they (my friends) cannot take the burden.

I am called upon to go out to tea.
I must send my love in a bundle, and leave you to unpack and distribute it.

[.signed-section-closing]
Your affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Blackburn, Eleventh Month 20th, 1800.

Since my last we have had many ups and downs,
and been so closely engaged as hardly to allow time to do the needful for the body.
We stayed at Lancaster three days, had two large relieving public meetings,
besides one with Friends, and several family visits;
and I have to tell of once more enduring the cross of going into the market-place,
and speaking to the people.
We also visited the castle,
where nearly two hundred of our fellow creatures were imprisoned:
the chaplain who attended them was very kind, making the way for our admittance,
and choosing to be with us himself.
He afterwards thanked us for the interest we appeared
to have in the welfare of the poor prisoners,
and was at both the public meetings.
I thought the different engagements at Lancaster proved
more truly relieving to my spirit than is often the case;
for which, and many other blessings,
I desire to bow low in gratitude to Him whose hand is full of blessings,
and who does not fail to dispense of them to His humble dependent children.

I think it is the genuine sentiment of my mind,
that it is not right for me to expect to convert sinners,
or to do any more in thus laboring, than to acquit my own conscience of condemnation;
if this may be the happy issue, surely it _ought,_ surely it _will_ satisfy.

[.letter-heading]
To Sarah Grubb.

[.signed-section-context-open]
Liverpool, Twelfth Month 19th, 1800.

[.salutation]
My Dear Friend Sarah Grubb,

I sit down once more to assure you, from my own hand,
that you and yours are not forgotten by me, although the fourth year is now revolving,
and more than half gone, since I had a personal interview with you,
and but very little epistolary correspondence has passed between us; nevertheless,
perhaps we have daily visited each other in mind.
I am sure, on my part, this has been the case; and I have sometimes hoped we were near,
in some precious degree, in that which is unchangeable.
Oh! says my soul, may this increasingly be our experience,
however differently circumstanced as to the things of this fading scene; that so,
being more and more leavened into the Divine nature,
we may be presented faultless at last before the throne of grace, with exceeding joy.

Since last Yearly Meeting, my engagements in a religious line with my dear friend M. S.,
have been mostly very close: we have passed through some deep conflicts together;
and at other seasons, through adorable mercy,
been enabled to acknowledge the works of the Most High are great and marvelous,
and _all_ His ways just and true.
This has, I hope, endeared us to each other beyond even what natural affection can do.
We reached this place a week back, and on seventh day, according to what I long expected,
it appeared laid on me to go into the markets here;
but Friends thought best to acquaint the mayor with the prospect, to obtain his sanction,
which he altogether refused; saying,
that if he had found such a procedure in the markets,
he would have put a stop to it as highly improper.
At this none can marvel perhaps, who employ their understandings in the matter,
especially now;
the minds of the populace being so generally discontented
with the very high price of provision:
yet the mayor at Lancaster stood by, while I was engaged in the public market there;
and the one at Kendal readily granted leave.
However, this prohibition was the means of excusing my poor bark the exposure;
an exposure crucifying to my nature beyond description;
and I was soon left without a doubt that my Heavenly
Father accepted the will for the deed.
On First day we were with Friends in the forenoon,
and had a large meeting with others in the evening.
Friends`' meetinghouse contains fourteen hundred people: it was a solid meeting,
and Gospel ministry flowed rather freely.
These are awful concerns, you know; and I often think, in the forepart of a meeting,
and many other times, Surely it is too much for me;
but when the mind can leave all to Him,
before whom all nations are but as the drop of a bucket,
it finds an anchor in the midst of conflict.
I found at Warrington, that by some means I had taken a heavy cold,
but we went from house to house there,
till it was time to set off to an appointed public meeting at Prescott.
We reached Prescott in time, and a large meeting it was, being held in the town hall.
My voice was nearly gone before it, yet the speaking part devolved upon me,
which was got through with great difficulty, but hope no harm was done to the cause.
We reached this place again on fifth day morning, and I have been confined since,
but feel better this evening:
after this night I hope not to give these dear kind friends the trouble of nursing me.
You will probably conclude we quarter with R. and S. B., who have a large house,
and large hearts; the latter being, I have no doubt, sanctified through many probations.

My dear regard is to my Clonmel friends,
and many others whom it will not do to particularize;
but it is a consolation to me to find that friendship, founded on virtuous principles,
is not dissolved by distance or time, in the separation of the body.
Farewell, my dear friend; may the holy Arm of Omnipotence surround you and yours,
in this day of perplexity and treading down, says

[.signed-section-closing]
Your affectionate

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stepney Causeway, First Month 17th, 1801.^
footnote:[Written about the time that many seceded from Friends in Ireland.]

On reading my dear +++_______+++`'s letter, how did my heart ache for the situation of some,
and feel thankful that others were mercifully preserved:
how complicated the emotions of my soul; but I centered here,
even in reflections like these--"`Your arm is omnipotent, oh Lord.
You are also the omnipresent and omniscient God.
You know the depths of Satan.
You will keep those that look to You; You will save them; yes, You will keep them,
both small and great, '`as the apple of your eye.`' You will magnify your power,
for You will not give your glory to another, nor your praise to the work of men`'s hands.
Through your goodness and your truth,
all things shall work together for good to those that love and fear You;
blessed forever be your name.`"

It is cause of thankfulness that dear +++_______+++ is
so strengthened and favored in his allotment;
and oh that many more may be raised up, in this day,
to the fulfilling the promise abundantly, I will put saviors, or watchmen,
upon your walls, who shall never hold their peace, day nor night.
Through the varied scenes that are to be witnessed, they shall not be at rest or at ease.
The serpent that beguiled Eve is beguiling very many
from the simplicity of the truth as it is in Jesus:
well is it for those who keep their habitations in this unchangeable, ever blessed truth;
for no enchantment or divination shall prevail against such; and though others may,
for lack of watchful dependence upon the source of all-sufficiency,
wander in their imagination,
and look for what they may call a higher and more glorious dispensation,
they never will come at it: they may strain their eyes, as it were,
even until they become blind, and so stumble at noon-day, as if it were night,
but God has revealed the last dispensation in the Gospel of His dear Son.
Oh may this Gospel, this one eternal power unto the salvation of the souls of men,
be more and more spread and illustrated in the world,
according to His holy will and purpose, says my soul;
that so as it relates to the general, as the sun that rises in the east,
and shines from one part under heaven, even unto the other part under heaven,
the coming of the Son of Man may be.
_His_ coming may be, at whose name or power, every knee must bow, and every tongue confess,
of things in heaven, and things on earth, and things under the earth.
I believe it is so with individuals who singly eye the light in them,
that it comes to shine more and more, until the whole man is full of light;
until all is brought into holy conformity, and leavened into the Divine nature.

Yesterday my dear companion came with me here;
we had reached her habitation the night before, having been traveling about seven months.
We have returned to comfortable homes in our different allotments in life;
she to her worthy husband, and I to my dear mother, etc.
No time was lost that I know of.
I have much to be thankful for, yet am not sensible of a redundancy of heavenly good;
far from it; neither do I wish for this,
believing it is in Divine wisdom otherwise ordered.
You are very kind in your manifested care respecting your S. L.,
as it relates to settling in life.
I look upon changing my condition for a married life, as very important;
and think I should not venture to do so,
upon any other ground than that it was clearly in Divine wisdom for me:
with this clearness, I apprehend we are not likely to mistake the person or place,
but rather to be assured fully in these points.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stepney Causeway, Third Month 1st, 1801.

This afternoon meeting has been, to my exercised mind, a season of renewed consolation.
I had not long taken my seat,
before the precious virtue of the heavenly life filled my soul,
which continued most of the time; so that my heart thanked God, and took courage,
in a resolution to trust in Him, and endeavor to do His will.

[.letter-heading]
To S. and A. Pumphrey.

[.signed-section-context-open]
Stepney Causeway, Sixth Month 4th, 1801.

Oh! my much loved friends, my heart aches with the thought that we are now separated;
so that there is no way for me to be at the interment
of our precious little H. She was indeed,
a sweet pattern of meekness and resignation;
my mind yearned toward seeing her again in mutability,
but there was something that prevented--that forbid.
I do not know clearly what this something was,
but I do know that it was my earnest wish to be at Divine disposal; and perhaps,
when we endeavor thus to steer aright, we should also endeavor to leave the event,
hoping that we shall be mercifully preserved from erring _greatly._
Thus I seek to console myself in the present instance,
and be assured my spirit is with you, and will be so.

[.letter-heading]
To her Mother.

[.signed-section-context-open]
Bristol, Ninth Month 18th, 1801.

[.salutation]
My Beloved Parent,

I wrote you such a hasty scrawl the other day,
I wish now to endeavor to send you a few lines that may a little make up for it.
Our dear John Hull came yesterday afternoon with John Wilkinson.
I met with him just as I was going into a public meeting in this city,
and was much pleased to see him.
The meeting was large, and I think, highly favored;
dear George Dillwyn was much engaged therein, both on his feet and knees:
it is cause of encouragement to my mind,
to see him so lively in his appearances of this kind; through a dependence, no doubt,
upon the never-failing arm of Divine strength;
for where people think they can do without so much of this,
after being many years engaged in the ministry, I observe they dwindle into dryness;
and though their words may be very good, they are often _but words._
I think the Quarterly Meeting here, has been a time of refreshment to the souls of many:
a remarkable solemnity was sometimes over us.
I wish you may be favored in the same way, if consistent with best wisdom,
in yours that is approaching.

I believe my friends will not allow me to say much more to you, my dear mother,
at present; they are continually coming in.
Although I have written as fast as I could, I have met with many interruptions.
This is not much better than the last.

[.signed-section-closing]
I am your truly affectionate daughter,

[.signed-section-signature]
S+++.+++ Lynes.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Congersbury, Ninth Month 21st, 1801.

Since my last letter, I have been traveling on pretty much in the old way,
with this exception, that all my engagements have been in doors; for this,
and many other favors, I have abundant cause of humble thankfulness.
We made but little stay at Bristol,
but think it likely our lot may be cast that way again.
I went to see +++_______+++ at his lodging at the Wells.
John Waring took me in his chaise, and neither of us were sorry we went.
A few minutes`' solemn silence came over us before we separated,
and I had to break this with a few sentences for his encouragement;
believing the great and necessary work was being carried on,
and would be accomplished to his everlasting joy,
as he looked to the power which he had been made acquainted with.
Oh! my dear friend,
how my heart was contrited under a sense of Divine mercy in this
visit--a man that once seemed to have little or no trust in God,
now wooed to Him by His everlasting love; and through a yielding thereunto,
is almost in the state of David, when he said,
"`Surely I have behaved and quieted myself as a child that is weaned of his mother:
my soul is even as a weaned child.`"

[.letter-heading]
To Ann Pumphrey.

[.signed-section-context-open]
Plymouth, Tenth Month 11th, 1801.

+++[+++After alluding to the death of a friend.]--These are awful mementoes, yet,
until they are felt upon ourselves or our families, we do not, in a general sense,
make the right use of them, nor always when this is the case;
but where individuals are concerned to receive them
as messages from heaven to invite us there,
no doubt they will have the blessed tendency to loosen from all visible things;
giving to the mind a holy indifferency,
that it may more perfectly be devoted to the best of Masters.
Oh!
I am ready to say, when will this be my attainment?
for even now, for a few months I seem as if I was afraid to leave all to the Lord,
respecting my dear connections at home.
I know nature is allowed to feel its attachments in pure subjection,
but I am afraid I feel them without this; very, very often apparently forgetting,
that with all my care, they must and will be conflicted, as well as myself; and that,
if their sufferings are in the will of Heaven, and they look to Him,
without whose notice "`not a sparrow falls to the ground,`" He will keep them _in_ all,
and deliver them _out_ of all.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Perran Walk, Tenth Month 31st, 1801.

Now I may say a little of our travels.
We left Plymouth on fourth day, and got that evening to Landrake,
having been with Friends in the forenoon, which was a farewell season.
We had a public meeting the evening before, that finished such,
and glad enough we were to find a liberation.
I thought, after we had left the town of Plymouth,
I felt as clear in my spirit as it was possible to be, but no rejoicing either,
on account of any _extraordinary_ manifestation of Divine power through me; for,
on taking some retrospective view, I was ready to think that had not been the case;
but I find that a quiet mind is indeed a great treasure.
I may say that we proceeded, having meetings on the way, at Saltash, Landrake,
Germain`'s, Ashingford, and Looe: all these with other people,
and one with Friends at Germain`'s; so that in steering for Liskeard by First day,
we took six meetings in three days, traveling mostly on very bad roads;
but I don`'t know that ever my animal spirits were better to persevere through difficulty,
or my mind much more calm under similar circumstances.
Thus are we helped along from time to time; but there are seasons, my dear friend,
wherein my mind and body seem nearly to have exhausted all their strength;
notwithstanding my friends often think I get along easier than many,
because my conflicts are not very apparent.
On fourth day we got six miles to a meeting of Friends at Mivagissy,
and had a public one in the evening: this,
as well as some other opportunities of the kind,
was almost like a meeting with our own Society for stillness;
the people in this county being remarkably serious,
and observing a decorum that excites surprise, when one looks up,
and sees them exceedingly incommoded for lack of room;
but there is lacking a ceasing from their own works in their religious exercises,
the sense of which among them, is often oppressive to the life.
On fifth day we reached this place, and have had a public meeting,
chiefly with the dependents of the friend at whose house we are (namely, Dr. George Fox) and
who owns, or has a considerable share in copper mines here.
I suppose about one hundred and fifty people collected on the occasion.
They seem to be much of the description I have hinted at.

[.letter-heading]
To Ann Pumphrey.

[.signed-section-context-open]
Falmouth, Eleventh Month 13th, 1801.

[.salutation]
My Dear A. P.,

It is pleasant to reflect on the likelihood of your
getting a little into church service abroad.
I wish goodness and mercy may be with your band.
Perhaps you are now in the engagement; if so,
no doubt there are low seasons appointed and permitted;
for I am of the mind that the seed lies low in some parts where you may visit; yes,
very low: but there is nothing for the Lord`'s servants to fear, with any slavery,
who are simple-hearted and faithful; whose confidence is in Him, the fulness of strength.
But although I thus scribble to my dear Ann, I am weak, and very weak:
have lately thought that there is great need for me now
to beware that I get not into too easy a condition of mind;
for I have not quite such close exercise as when we were fellow-travelers,
as it does seem to me that the dispensation of visiting market-places is fulfilled;
I have not been once engaged in this way on this journey:
what a favor! yet you will conclude that all is not smooth.
No, my dear, there are still sources of unspeakable conflict;
but nothing ever was like what I have just now alluded to,
and of which you were often a partaker with your S. L.; except, to be sure,
the affair relative to that great place in London, Paul`'s,
which was even worse than markets.

We have lately been holding public meetings along the country as heretofore,
but with this difference, that I have passed through several places,
and felt nothing to cause us to stop; whereas it was once uncommon to miss one place;
and somehow we have met with very few hospitals and prisons, as in time past,
so that my way has been more plain; but in some meetings, chiefly made up of Methodists,
particularly in this country, I can scarcely live:
the seed immortal is deeply oppressed with, as I conceive, their lifeless performances,
in which they evidently place so much confidence.

My heart salutes you in much love and religious fellowship.

[.signed-section-closing]
Your truly affectionate

[.signed-section-signature]
S+++.+++ Lynes.
