== Chapter 7. Letters from 1811--1814

[.letter-heading]
To Martha Brewster, When on a Religious Visit in Ireland.

[.signed-section-context-open]
Youghal, Ninth Month 1st, 1811.

[.salutation]
Beloved Friend,

Poor and weak as I am every way,
I cannot help coveting you should know that very often you are the companion of my mind,
I will not say in fellow feeling,
because it is not likely I can be fully aware of your tried state; but I have felt,
and do feel much for you,
yet have no doubt but the Shepherd of Israel continues
graciously to watch over you and care for you:
"`Many,`" it is said, "`are the afflictions of the righteous,
but the Lord delivers him out of them all.`"
I have remembered that Job is spoken of as being
deeply sensible of the sufferings of his own body,
so that many other things were comparatively light; but, in this sore temptation also,
he served the Lord; and that Hand which is invisible supported him,
and brought through all.
So, my dear friend, though you may be ready to say, with another of the Lord`'s children,
"`You have hedged me about that I cannot get out;
You have made my chain heavy,`" yet will the same Divine Hand bring forth,
in His own time, and prove His covenant to be perpetual, never to be forgotten;
for He will be Himself "`the glorious Lord,
a place of broad rivers and streams,`" in your blessed experience.
But do I forget myself?
I write to one of the experienced handmaids of Jesus, and I am, when proved,
apt to sink too low: this has been the case of late,
for mind and body have seemed more exhausted than I almost ever remember to have felt:
to be sure the depression of spirits that has accompanied
me might be attributed to physical causes,
and then, in these sinking times,
the unwearied enemy does not fail to whisper discouragement.
Sometimes, however, in thinking of you, and other of my friends,
whom I much prefer to myself, I have felt such a sweetness, and so much love,
that I have almost termed it fellowship:
and then I recollect that "`to him that is joined to all the living there is hope;
for a living dog is better than a dead lion.`"

My John`'s dear love is to you;
he and I sometimes recur to the precious little season of
retirement we had when you were about leaving us,
and think we have traced in your communication the marks of a true prophetess.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Dublin, Fifth Month 1st, 1812.

I continue to look towards London,
although this prospect is with much dread of sea-sickness,
and very great reluctance to stay from home;
but if we will not move in the light while we have the light, it may be withdrawn,
and leave us in darkness and sorrow.
I wish you could know how greatly my mind is exercised in this city,
and in thinking of London; indeed it seems to me that the right-minded,
and especially the active members among us, have great need to go down into the deeps,
and wait the Lord`'s time; depending singly on His holy arm,
to bring them where they can erect their Ebenezer before the people.

I have remarked, since coming here, that Friends`' tables are very consistent;
and that coming out of meetings, and other times,
they seem glad to speak to each other in love.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Bangor Ferry, Fifth Month 9th, 1812.

This morning I wrote a few lines, informing you of our safe arrival at Holyhead,
after a passage of upwards of thirty hours.
Part of the time was particularly distressing to me.
I thought of you and our dear children, and that I could fly to you;
but on endeavoring to look beyond these feelings,
to Him whom I thought I was obeying by attempting such an undertaking, I found,
after a hard struggle, something of the calming influence of His Spirit,
through which the soul can be resigned to suffer; so that after this,
things were made much easier to me, and I became reconciled to my situation.
We came thus far agreeably, so far as anything can be agreeable,
in my present state of being an exile from you, my love, and the children;
but I have no consolation to look to, save the invincible Rock,
which no doubt will still prove a place of refuge, if my poor mind does but flee to it.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Birmingham, Fifth Month 12th, 1812.

It feels a little trying to sit down again to address you,
without receiving one line from your dear hand since we parted; however,
I must tell you a little more of my journey;
and indeed there is no way I can be employed just now,
so desirable to myself as that of talking to you,
in the only way within reach at present.
Oh!
I feel this coming over to be just such a sacrifice
as it was in anticipation--hard to the natural mind;
but herein is my stay--I have to place the whole account to religious duty;
and however I have been tossed and tried since our hands separated one from the other,
I now assuredly believe it is no delusion, no fancy, or imaginary dream;
therefore I trust in the Lord, and stay myself upon my God and your God,
whose sweet presence I was favored to know,
when in the chamber with our dear little ones,
as they lay asleep the morning I left them.

The journey through North Wales is not so pleasing to me as through South Wales,
but the loftiness of the rugged mountains strikes
the mind with something of solemn grandeur:
there are also other bold views to be seen, passing along--cataracts, deep rocky valleys,
torrents rushing along the bottom, amazingly rapid;
and much that might be dwelt upon by the pen of a traveller more
capable of painting scenery than your poor S. G. On First day morning
we had our little silent meeting together at Capel Curig:
thus we were literally the "`two or three,`" and I thought
how precious were a few moments of true quiet.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Ratcliffe, Fifth Month 15th, 1812.

Your feeling so calm on going home is, I think,
a confirmation of the rectitude of our united conclusion,
that it was best for me to come, and for you to stay.
It is not anything short of Divine power that could
make these hard things tolerable to us;
let us then be encouraged to trust and believe in Him who is faithful.
I esteem it a great favor that you can give me so
good an account of yourself and the precious children.
My dear mother is come, and we have had an interview up-stairs.
She seems, I think, very nicely; and you may be sure, rejoiced at our meeting.
Her faculties seem very bright and clear.

18th.--Yesterday I was at Ratcliffe Meeting in the morning, which was very small,
yet not silent,
for four of us women Friends had something to communicate--Mary
Capper and Mary Lewis of the number.
I went to dinner at J. Capper`'s, where I met my dear friend J. G. Bevan.
I thought him less altered than I expected, and less dim too.
He said he was glad to see me, as far as he could be glad in anything.
He spoke of you with much affection, and of your gift in the ministry with much unity.

I want to tell you of our meeting with Henry Hull, first in the meetinghouse,
then at Mildred Court.
He said he never visited any place he could reflect on with greater satisfaction,
than his visit to Ireland.
He saluted me as though I had been a near relation.
This dear man has received no account from home since twelfth month.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fifth Month, 1812.

Your letter comforted my heart,
and really humbled me under a sense of the unmerited kindness of our merciful Caretaker.
Yesterday and the day before were rather fatiguing to me.
On fifth day morning I closed my letter to you, and went to the women`'s meeting,
where I felt much that seemed likely to be communicated,
but only made a few observations in a concise way, now and then.
We dined in a large company, at T. C.`'s; and short as the time was,
had a religious sitting, the vocal engagement of which fell on me;
but what was very much more formidable, I expected, that on going to meeting again,
I should have to ask liberty to visit the men`'s meeting;
which came indeed on me in a powerful and weighty manner,
so that I mentioned it immediately when the meeting
had opened by the reading of the First Minute,
and M. D. directly offered to accompany me.
When we sat down in the men`'s meeting,
I thought the word of the Lord was like a fire within me; and when I spoke,
it seemed to myself as if it not only made its way through every obstruction,
but that the pouring forth of it caused the earth to tremble.
M+++.+++ D. spoke for a short time, after these effusions had flowed from my full heart;
and then I kneeled, and came away under the feeling of what is said on this wise,
"`Serve the Lord with fear, and rejoice with trembling.`"
I was, however, favored with quiet; and again, in the women`'s meeting,
had to make a few remarks in the gift bestowed;
but nothing like setting my mind at liberty, full liberty.

This family (where I now write) are very kind;
the father and mother improving characters: indeed many of my old friends are so,
which is a great satisfaction to my mind; and here are many,
very many nice young people to be seen at this assembly.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Ratcliffe, Fifth Month 28th, 1812.

I have had many painful cogitations since I left home,
but then I know that I am here in the obedience of my will to the Divine will,
or else I am ignorant indeed respecting everything good.
When the epistle for Ireland was read in meeting yesterday,
Martha Brewster spoke very nicely,
and addressed us who had made the sacrifice in coming over.
I think the conclusion of last night`'s sitting was
favored with a sense of good in a remarkable manner:
all the meetinghouses were open in the morning.
I went to Devonshire House.
M+++.+++ P. was much helped to speak, at which I rejoiced,
for I love to see the aged crowned with life in the ministry.

I am very anxious to lose no time,
but I must also try not to make any cause of regret to myself,
as I hope this visit to England will serve me for many years: we are, to be sure,
short-sighted though, after all.

[.postscript]
====

P+++.+++ S. (Afternoon.)--I kept this open till after post time, and now,
my dear and ever-valued husband, I have received yours of seventh day last:
it is as a cordial to my heart:
I was ready to prostrate myself before the Lord for this renewed mercy to my poor mind.
The meeting this morning was a time of favor on the whole.

_Fifth Month 30th, 1812._--I fixed to write this morning,
but have scarcely been able to collect my thoughts,
in sympathy with our dearly beloved Henry Hull,
who has a most affecting account from home.
He has lost some of his nearest connections by a malignant fever:
the tender tie of husband and wife is dissolved; one of his sons is no more;
his mother is also gone, and some others not so immediately of his family.
I have not seen him since the mournful tidings reached his hands,
but I understand it is the younger of his two sons: it is, however,
difficult to learn all the particulars,
as the family where he lodges have taken him into the country.
I spent most of the time out of meeting yesterday with him,
and tried to comfort him about not hearing from home.
Alas! how short-sighted we are! but probably the mind of
this dear friend might be in some degree prepared for trouble,
as he seemed very anxious about home.

The men`'s meeting is now over: we concluded last night.
We came to William Allen`'s to dinner.
William Grover said that they had a very precious, baptizing time this morning.
The singular trial of dear Henry Hull was spoken of,
which had a moving effect upon the meeting.
The unerring wisdom of that Providence who had inflicted
this dispensation was alluded to;
so that W. G. said, under the influence felt,
the mind could become reconciled to almost anything.
The conclusive Minute of the meeting is such as Friends could formerly write.
It speaks of the goodness of the Almighty,
and ends in giving praise and glory to His Name.
Ah! my love, what an unspeakable, unmerited favor is such condescension!
The women`'s meeting has been, I think, much owned too;
and many important truths declared "`in the demonstration of the Spirit, and of power.`"

====

[.letter-heading]
To the Same.

[.signed-section-context-open]
Bromley, Sixth Month 1st, 1812.

At the last sitting of the meeting of ministers and elders,
dear Henry Hull`'s case caused many tears of sympathy to flow.
His certificate was produced, and some alterations and additions made,
in consequence of his afflicted and singularly trying state.
We came down to Ratcliffe to lodge, and were at meeting there yesterday morning,
when I was much opened into different states.
In the afternoon Henry Knight took me to Plashet, to visit dear H. H.: he was on the bed;
seemed unable to speak to me, but wept and groaned.
I sat by him a while,
and tried to comfort him by putting him in mind how different this
sorrow was from that of our relations departing from what is good.
He showed me the letters conveying the sad tidings: they were most movingly expressed.
Everything seems to have combined to make the affliction
the most moving to the sensibility of the human mind.
The dear young man his son,
had a prospect of marriage with a young woman who loved him entirely.
He charged his relations to look upon her as a sister.
Dear Henry showed me a letter he had managed to write to his eldest son yesterday forenoon,
which I mean to get a copy of to show you.
I stayed with him instead of going to meeting in the afternoon,
which I believe was acceptable to his poor tried mind.

Yours of last third day is just arrived:
what a mercy that you have such comfortable intelligence for your poor wife,
who so dearly loves you and our little ones.
Surely it ought to encourage me not to make too much haste home, which I can hardly help.

_Tottenham, Sixth Month 4th, 1812._--A friend who has spent some time, within a few days,
with Henry Hull, says he is quiet.
This dear man appears to bear his singular trial with holy acquiescence,
while his nature feels it as much as can be conceived.

Joseph Bevan is gone up to the Meeting for Sufferings.
We took a farewell of each other, and had a sweet little opportunity previously.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Gloucester, Sixth Month 9th, 1812.

Your cordial salutation, how sweet and pleasant to your own wife,
so long separated from you; and that you can say you are well,
I esteem a great mercy to my too anxious heart,
which is generally in a pant when I am about to break the seal of your letter.
To have such a companion for life, who can feel for me every way,
oh how humble and good it ought to make me.

I have gone through a great deal with the many solicitations
of friends to stay a few days longer;
the one half I can`'t tell you, but being, according to Rebecca Bevan`'s phrase,
"`very stoical,`" I was not easily dissuaded from my purpose;
and did not allow the warm solicitations of friendship to prevent
me from making all the good speed in my power to return to you,
and the precious charge mutually ours.

When we got to H. K.`'s,
we had not anything whatever in readiness for our journey (seventh day morning,
about ten o`'clock) but about one o`'clock we were prepared without any unpleasant hurry:
spent some agreeable hours with these dear friends, taking dinner and tea with them,
and parted under a solemn, sweet covering of Divine love.
First day at Uxbridge was not spent in idleness; for besides the two meetings,
which were remarkably favored, we had four private opportunities;
and separated under a truly desirable, heart-tendering feeling.
We had a religious sitting with several friends at Wycombe,
who called in after breakfast--left Wycombe about nine o`'clock, and got in here late.
I mean to step into all the Friends`' houses here, which are but four in number.
They want me to let them go to meeting tomorrow instead of next day,
but I do not choose to give them any such precedent.

Poor dear Henry Hull is to be at Uxbridge today.
He has received several letters from home,
since the very mournful account more than a week back:
the latter intelligence is of the soothing kind,
the disorder having pretty much disappeared.
All the remaining family he left were in usual health,
only his youngest son had met with an accident,
the wheel of a wagon having gone over him, but from this he was recovering.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Milford, Sixth Month 14th, 1812.

I have just received your letter,
and as I have a few moments before the packet sails this evening,
I wish to say that we are waiting here for a fair wind; as it seems nearly contrary,
we are at present reluctant to go.
Nancy and I are well--were at Haverford West Meeting this morning.
We stayed their meeting at Gloucester on fifth day; came on to Newport afterwards,
having concluded to come by Neath, which would put us in a way for calling on friends.
We breakfasted at Cardiff, at the house of Thomas Redwood, who attended Yearly Meeting.
He is come from among the Methodists.
He, his wife, and eldest daughter, are in membership with Friends.
We had a religious opportunity with them, and another in the evening at Peter Price`'s,
where we took tea.
With this latter visit several of the family were much affected.

The depression of my mind after parting with my mother and sister, has been very great;
perhaps partly owing to my affectionate sympathy with them.
They, as well as many others, seemed to think my stay very limited,
after an absence of five years: indeed, my dear,
what I have gone through with the earnest entreaties
of my friends on this side the water,
has tried me a good deal; but I always kept firm, and did not, I think, stay one day,
or half a day that I could avoid with propriety,
when I might proceed toward our dwelling, to meet you,
and to return to the duties of our dear family.
What to do now about leaving this place I cannot tell, but, after all our haste,
to be kept here is dull.
My dear sister feels it as well as I.

I think, with respect to myself, my baptisms have been many and deep in this journey;
but then I do not know that ever I was favored with more
Gospel authority in the exercise of the ministerial gift;
never was I more sensible that it is the Spirit of Christ which speaks through His anointed;
that they are but the channel which conveys the living water.

I had put this in my pocket, intending to go this evening, but there has come on a storm,
and the wind has changed more against us, so that we must try to have patience.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Milford Haven, Sixth Month 16th, 1812.

Well, my love, we must endeavor after resignation.
Here we are still, the wind being quite contrary, and sometimes very high.
I wrote a few lines to you on First day, and added to them yesterday forenoon;
after which we concluded to go, but a storm coming on, not only altered our minds,
but that of the captain, who is still detained here.

We are kindly cared for (at Daniel Starbuck`'s) and do not
know that we could have done better in any respect,
relating to our movements; so that, as our being here is nothing of our own,
we must endeavor to be quiet.
I write this, to run the chance of its meeting you before I get to you.

I shall try to look to the Lord, whose name is a strong tower,
and hope you and the rest of our dear relatives, will do the same.
This detention certainly proves particularly trying,
but let us remember that all things can be known to work together for good.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Waterford, Second Month 4th, 1813.

I have not forgotten my promise that you should receive
some intelligence from me by this post,
and may tell you sister Hannah has been able to get out today,
and we have taken four families.
My dear sister has spoken beautifully in each of the sittings.
The first visit was to Elizabeth Ussher`'s. I hope it may
please the Almighty to strengthen our dear H.;
indeed I think there was some ability to pray for it today.
I believe she is not sorry she made the sacrifice in coming.
I am trying to cheer her what I can,
and I recollect that it is frequently the case that one gets a
deep plunge in the onset of an engagement of this kind.

_Third Day._--We have sat in four families today.
H+++.+++ has been more enlarged in her gift this day,
than I recollect to have been witness to before.
She so evidently raises the life in families, that her company is very desirable.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Waterford, First Day.

H+++.+++ is evidently separated by the Master for this work,
receiving the fresh anointing in almost every opportunity.
She supplicated in meeting this day.

_Second Day._--The meeting last evening was but small,
I believe partly owing to the inclemency of the weather:
it proved rather a laborious time, although the people were very quiet,
and many Gospel truths were declared.
John Wigham followed me in testimony; there was no offering in supplication.
I whispered to him at the close, to give notice for tomorrow evening,
which he did with great sweetness and propriety.

The visit to Friends`' families here, so far as it is gone through,
has tended much to the casting off a load, with respect to me;
for I have been made willing to say anything which was clearly opened, and I think,
in "`treading as upon high places,`" have known what it was.
to "`dip the foot in oil,`" so as that nothing has
been crushed or hurt that was truly alive,
and even so as not to offend those who may have been
opposed to the plainness of the Gospel of truth.

_Waterford, Second Month 15th, 1813._--We have paid sixty-five visits,
but I find we have about thirty, at least, yet to pay; which, along with the meetings,
will be likely to take up this week fully,
and may be next First day may finish or wind up.

I found, before meeting yesterday,
that my mind was in a way likely to produce something weighty and powerful;
and indeed the second gathering of the people was much to my relief in the end.
The meeting was large and solid.
I think it was what Job Scott would have called "`blessed and glorious.`"

_Waterford, Second Month 18th, 1813._--As Hannah intends writing herself,
I need not say much about her; but I often thought, since coming here,
you would have been surprised if you had heard her in the gift, it was so beautiful.

I often conclude, that when we are at home,
and not so sensible to the incomes of light and life, we may be as acceptably filling up,
in our measure,
"`that which is behind of the sufferings of Christ,`" for the body`'s sake,
as when occupied in the way you and I lately were together.

_Waterford, Second Month 20th,
1813._--I think of you and our dear little children a great deal, and very tenderly,
but I hope soon to have the comfort of seeing you and enjoying your company,
though I fear not on second day,
as my mind dwells a good deal on a public meeting for the higher classes,
which would not, I believe, answer, except in the middle of the day.
As for tomorrow, I really think it is likely to prove enough for my strength,
without seeing those not in profession with us,
for I feel the awfulness of going to meeting in the morning already.

I want to tell you a little about the meetings yesterday;
indeed I think we may say that truth rose into dominion in both:
that with heads of families was very searching, and yet baptizing.
John Wigham said a little in that opportunity,
in unison with what I had been engaged to declare,
but no one spoke to the youth beside me: it was an open time,
and helped to remove the load from my poor heart.
And now, only for tomorrow and the next day, I should be pretty light;
but I must have patience, and try to be simple-hearted and faithful,
trusting in the Lord alone, who knows that I desire nothing in these engagements,
but the advancement of His glorious cause, in me and through me.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Twelfth Month 16th, 1813.

You may be sure, dear friend, that my mind is often led to visit some of you in idea,
and to sympathize in measure with you in your sorrow,
which I doubt not is still very deeply felt, and will continue to assail the heart,
at seasons especially, to the awakening every tender emotion; but while this is the case,
and that the assistance which our late beloved brother +++[+++William Wright of Cork]
afforded in the affairs Society, is much missed among you,
I trust the unmixed and inexhaustible Source of wisdom and
strength will prove His all-sufficiency again and again.
When we consider, that although it pleases Him to make use of instruments,
with Him is the power to work with or without these,
does it not strengthen us to leave all to Him, and trust in Him, the Lord Jehovah,
in whom is everlasting strength?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, First Month 13th, 1814.

I am unwilling to let my J. G. go to Cork, without saluting you in this way,
if it is only to say how much I desire to be present in spirit, with Friends,
at the approaching solemnity in your city; for although absent in body,
I am not without feeling much travail of soul,
that the unchangeable truth may be exalted among you.
Oh that those who prefer the Lord`'s blessed cause to their chief joy,
may get down deep in their spirits, and feel after the pure, meek life of Jesus,
that they may move therein, and in it dwell.
It is thus that the followers of the Lamb have ever become victorious with Him;
and may you be encouraged in the remembrance, that to those who thus wait,
the full assurance of Divine aid is granted; as in the language, "`Fear not; lo,
I command you; go forth; be humbly bold.`"
These words, by dear Job Scott, have often proved strengthening to me,
when I have been hesitating and reasoning, because I was a child.

I am glad that there is a memorial of our beloved W. W.,
thinking that such a life ought to be recorded,
to the magnifying that Power which is all-preserving, all-sanctifying;
and in the hope that hereby others may be induced to enroll
their names among the disciples of a crucified Lord.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Clonmel, First Month 16th, 1814.

My mind is much with you, and at the Quarterly Meeting, though no doubt it will be small;
several have, however, risked much difficulty to get to it,
through this inclement weather;
and I trust the Ancient of days will be graciously
pleased to give His little ones to become as David,
and the house of David as the Angel of His presence,
for His great and adorable Name`'s sake,
and for the encouragement of these in His right way, even the way everlasting.
You feel the weight of things,
and are well acquainted with making sacrifices for the sake of
that cause which is above and over all worldly considerations;
and I do believe your reward is sure;
that the promises of the Most High will be sealed in your experience,
with an everlasting seal.
You know that it is said, "`you have need of patience, that, having done the will of God,
you may inherit the promises.`"

[.letter-heading]
To the Same.

[.signed-section-context-open]
Clonmel, First Month 21st, 1814.

If you are detained in Cork till after First day,
I trust it will turn to the glory of the Great Name; and oh! says my soul,
may the end of this memorable Quarterly Meeting be eminently
crowned with life--that life that by its purity,
its meekness, its wisdom and patience, wearies all its opposers,
and eventually triumphs over the combined powers of darkness;
showing itself to be invincible.

I think it is no loss to you to be a good deal at your lodging,
and I had such a sample of the christian-like hospitality there,
that I believe you may be easy.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
1814.

Oh! my dear +++_______+++ look with a single eye to the Holy Leader;
steadily follow Him through all:
ever wait for the glory that goes before the Lord`'s redeemed, anointed ones;
but wait not for man, nor tarry for the sons of men;
so shall the same glory be your rear guard.
Thus will the light be about your path, and about your bed;
even your rest being that prepared on high,
it shall assuredly prove itself to be a glorious rest,
when your mind has been bowed down; yes, when you have lain under heavy pressure,
and have reproached yourself as the cause,
I have believed that even these painful feelings would have
a tendency to deepen you in the root of the Divine life.
In our infancy in the ministry we are sometimes dealt with as by stripes,
while yet Divine compassion is such, that as a father pities his child,
so does the Lord pity us.
He evidences that He knows our frames, and remembers that we are dust; thus,
in the gentle chastisements of His dear children,
does He give them increasing capacity to call Him Father, and so feel that they love Him.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Dublin, Fifth Month 3rd, 1814.

I wrote a few lines yesterday;
you would see that it was not likely for us to sail last evening,
the wind being contrary, and I fear it is very much so still.
I am very desirous of getting away, on several accounts.

After you were gone, I felt very solitary to be sure; I retired to my chamber,
and turned my heart to Him whose wisdom, I believe, has separated us.
I was made sensible of some precious ability to supplicate His great Name,
that He would be with you, my beloved partner, comforting you by His love,
and upholding you by His power; yes, and I had renewedly to hope, in His mercies,
that we might yet be blessed and consoled in each other.
The dear children were also brought into remembrance, with sweetness.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Fifth Month 12th, 1814.

We are likely to sail this day.
I feel much better satisfied to make the attempt today than I have done yet.
My sweet little children, as well as yourself, are much the companions of my mind;
sleeping and waking, my love flows to you.

_Shiffnal, Fifth Month 14th,
1814._--I have not before addressed you since I was
favored to arrive on this side the water.
At Holyhead brother Samuel wrote,
which I thought would inform you as much as I was then able to do, for I was, as usual,
exhausted with sea sickness.
I consider it among the many mercies of a gracious Providence,
that I was enabled to give up to cross the water when I did,
for I do not believe that there was a day since the Yearly Meeting,
when we should have had only sixteen hours passage.
We have got on very well; indeed I am much better than I could expect,
but am desirous of getting as fast as I can to London.

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Fifth Month 16th, 1814.

I feel far away from you and my children--perhaps the further on account of the
length of time it is probable I may be detained on this side the channel;
but I trust we are both enabled to look to Him who can sweeten every bitter cup,
and make hard things easy; indeed,
when I consider the glory and excellency of that cause, on which account we are parted,
I do not wonder even at the constancy of the martyrs.

My fellow travelers were very agreeable,
and I am now among those who are as attentive as possible,
and seem as glad to see me as though I was their own;
but I feel a secret sadness underneath all, in being separated from you.
The meeting I was at this evening was, I thought, very extraordinary;
and that this forenoon held more than four hours, yet it did not appear very tedious:
there was something felt, I think, of the overshadowing of the heavenly wing.
What a mercy it is that, in a collective sense,
we continue to experience the circulation of the Divine life!

I went to see J. G. Bevan before meeting;
he appears to me to be many years older than when I saw him last.

_London, Fifth Month 19th, 1814._--I have ventured to kneel once in the Women`'s Meeting,
and, yesterday afternoon, spoke in testimony to some relief; but it is a dreadful thing,
speaking in these great mixed meetings; for,
although we are all members of the same Society, many and various are our conditions.
E+++.+++ C. is very careful not to take up a great deal of time,
yet she has sweetly and livingly appeared in two sittings.
This day I came to Ratcliffe Meeting: it was small; it was searching labour,
and yet comforting and encouraging to the few honest-hearted.
My dear mother is with me; she looks wonderfully well and handsome.

J+++.+++ G. Bevan said I was to give his love very sincerely to you, and added,
"`I love him above other men in your land.`"

_21st._--Now I may tell you that, after I had written to you,
and said that I found it a dreadful thing to speak in these meetings,
I had indeed to venture again, and that after Friends had sat long and were weary;
but I rose with saying, that I knew Friends were fatigued,
yet that if it pleased the Lord to cause His power to arise into glorious dominion,
we might almost forget the inconvenience of the poor body;
so my Almighty Helper made the way for me to proclaim His word with awfulness.

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Fifth Month 11th, 1814.

When closing my last to you on seventh day morning, the twenty-first,
I had it on my mind to visit men Friends, and so it continued through First day;
and yesterday I proposed going to the opening of the meeting in the afternoon.
A message was accordingly sent in writing,
and a written answer returned--that it was not a suitable time.
Well, a second proposal was made this morning,
and agreed to:--it was a time of much imitation and warning,
yet were the Lord`'s servants encouraged by the revival of His promises; in short,
I was strengthened to get through, to my humble admiration.
It was a sacrifice indeed to give up to go and visit my brethren in so large an assembly.

On First day I was in a full meeting, at Gracechurch-street, in the morning,
and likewise at Devonshire House in the evening:
at the latter I do believe were one thousand seven hundred people.
I could not but yield, in both these instances, to the powerful influence of Gospel love,
and was enlarged; indeed my tongue has been, as it were,
much loosened to speak of the Lord`'s goodness, and of His wonderful works,
at this Yearly Meeting; neither has my soul been without its baptisms;
for all I desire to bless and praise the Holy Name.
Now I want to tell you that A. Jacob,
who has been a most attentive and affectionate fellow traveller up to this city,
seems constrained to offer herself to go further; it is not my seeking,
but it feels very comfortable to me, and therefore I hope it is right.
Dear G. S. is here; he kneeled today, in Southwark Meeting,
in very lively and solemn prayer, which brought me likewise to prostrate myself,
with these words, "`Amen and Amen, Lord God Almighty, holy and true,
who are worthy of all honor, glory, dominion and power, forevermore.`"

_London, Fifth Month 28th, 1814._--I do not think I ever was at such a Yearly Meeting,
for the covering of solemnity,
and proceeding in the business with so much life and harmony;
the meetinghouse was more crowded, too, than ever I remember to have seen it before;
there was scarcely a gathering that many were not obliged to stand.

I told Friends last evening that I thought we could now rejoice in those tribulations,
which had been the means of bringing some of us to this Yearly Meeting;
inasmuch as we felt the heart-contriting influence of the love
and power of our Holy Head;--that if we were ready to say,
(as I had penned to my beloved companion in life) that we
wondered not at the constancy even of the martyrs,
might we endeavor, when separated, to feel, often to feel,
after the same precious sense of good which we had partaken of together, etc.
E+++.+++ Coggeshall had spoken before in testimony, and, immediately after I sat down,
she kneeled in a lively prayer, which was the last vocal offering;
and the pause which ensued after the reading of the
Conclusive Minute was very solemn and sweet.
Your quickness of understanding in these things must
make up for the deficiency of my pen,
for I cannot give a just description of the meeting; many, however, were in tears.

_First day, 29th._--I have been to Devonshire House Meeting this morning;
it was largely attended by Friends and others,
and your S. G. was largely engaged among them, to advocate the cause of righteousness.
Blessed be the Lord, who makes His strength perfection in our weakness!

G+++.+++ S. seems to be a brave advocate in the ministry of the doctrines of Christianity.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Sixth Month 2nd, 1814.

How often have I recurred to the few minutes we sat together in the car,
when I felt as if I was going to make a sacrifice of every temporal comfort,
and when but little of the best stay was discoverable to my poor mind: then there was,
nevertheless, a little that I could just lay hold of,
which I felt before leaving my pillow in the morning; and then your tender heart,
my dear friend, was touched with my sorrow, and you tried to comfort me.
Now I can, through adorable mercy, already acknowledge,
that what I have seen of the goodness of the Almighty towards His people,
was worth some bodily suffering, and some deprivations too.
This Yearly Meeting has been favored with more of
the overshadowing of Divine love and ancient power,
than was ever before witnessed by me in a collective sense;
for it was the case from sitting to sitting.
And now I must ask you to salute +++_______+++ for me:
I feel affectionately desirous of her growth and establishment in that which is immutable;
may she be humbly bold to follow the leadings of Israel`'s Shepherd,
so will she never be forsaken of Him, but have to rejoice in His mercy,
and be glad in His salvation.
Can we ever be too much dedicated to the Lord, who has granted us so much of His grace;
who has richly endowed us with noble faculties,
and designs that we should be ever with Himself?

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Colchester, Sixth Month 7th, 1814.

First day at Chelmsford was a laborious day to me; what I had to do was trying,
yet I felt as though I had discharged myself faithfully.
We then went immediately to the prison, to visit four of our young men,
who were there on some military account.
They were all under the age of twenty, except one about twenty-two.
We had a meeting with them, but I thought they were not all alike; one of them, however,
seemed to me to be a very desirable youth.
I hope they may each be deepened by this occurrence.

You will not be surprised to hear that we had a public meeting in the evening;
their large new meetinghouse was greatly crowded, and a very solemn time it proved; yes,
it may be said that the power was in glorious dominion; blessed be the Lord!

On coming here last evening, dear John Kendal sent for me to his room:
he sits up but little now, but his mental faculties are unimpaired:
he knew me directly--we parted in love.
I had not been long from the Select Meeting until he again sent for me, and said,
"`My dear friend, it is with reluctance I can part with you;
what love I feel--I never loved my friends as I do now,`" etc.
The Select Meeting here was, I believe,
as large as our Yearly Meeting of the same description.
I had to speak in testimony and supplication,
rather tending to desire more fervency of spirit.
The Quarterly Meeting is now over; there was a meeting for worship first,
of nearly two hours and a half.
I sat rather long in silence,
and indeed I thought it required deep indwelling to be clear in the Shepherd`'s voice,
which at length put forth in rather a searching testimony:
there was much to wade through, but eventually truth was above all,
and a blessed invitation went forth to the youth.
Dear Isaac Stephenson and his wife are here; also a woman Friend, who is blind,
from Norfolk, named Sarah Bleckley.
She and I visited the Men`'s Meeting:
the Women`'s Meeting was likewise favored with lively counsel.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Coggeshall, Sixth Month 9th, 1814.

I may, through mercy, say that my health is as good, or better than when we parted,
though my head has not been quite well, these two or three days, owing, I believe,
to the great exercise of my mind; for I need not tell you, that to visit meetings,
greater or smaller, requires deep digging.
When the life is, however, found, and rises into dominion at last, it is enough.
We were at their Week-day Meeting yesterday at Colchester,
and had a great public meeting in the evening.
They were both extraordinary seasons indeed,
for the word of the Lord went forth with great power;
but with respect to the evening meeting, I never knew more openness,
nor the deep mysteries of the kingdom more clearly unfolded to my view,
than while speaking to the people.
Oh! how glad they seemed to hear the real truth declared;
and never was my poor spirit brought nearer to the throne of grace in solemn,
fervent prayer,
in which it felt as though the many hundreds collected joined with one accord.
All glory be given to Him without whom we are nothing;
may His own works praise Him more and more, says my soul!
And oh! how pleasant it is that my beloved husband is endued with capacity
to travail for the prosperity of the one same blessed and glorious cause!
May the unfailing Source of help be your sufficiency.
I have, I think, in the opening of life, had sometimes to tell the people in public,
that I have left a tenderly beloved husband and some precious children,
in obedience to the will of my God, which has affected many minds.

We went to take leave of dear John Kendal in his bed,
and I have sat by him different times, much to my edification and comfort;
indeed he seems in such a very precious state of mind,
that to be with him is like having a foretaste of heaven.
Anne Jacob saw him twice, and was wonderfully struck with his heavenly-mindedness.
He is now in his eighty-ninth year; his faculties quite bright,
and his heart overflowing, as he himself said, like an overflowing stream, with love.
On my taking leave he said, "`Farewell in our gracious Redeemer.`"
He seemed reluctant to part, but said it must be,
though he did not think we should ever meet again here on earth.

_11th._--Since writing the foregoing,
I have got through what seemed to open as religious duty in this place.
Yesterday we sat with Friends in the morning, and, as it respects my exercise,
the meeting was a time of deep wading; and yet, as I said,
I thought I heard the panting of the babes in Christ,
and I was mercifully favored to visit the different conditions to my relief.
Friends are not numerous here.
We had a meeting with the inhabitants more at large last evening;
it was gathering all the time, which tried my feelings much,
but I do not expect all smooth.
It seemed a good deal like pulling down old buildings, and, as I think somebody says,
"`I was sometimes afraid that what little life I felt,
would be smothered in the rubbish.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ipswich, Sixth Month, 1814.

I think dear John Woolman says, when he was peculiarly plunged into suffering,
"`I remembered that I had called You Father, and I felt that I loved You.`"

I have been led to consider that those whom Divine Goodness designs to dignify,
and enable to speak to others of His ways, must have their sore exercises,
that they may speak that they know, and testify that they have seen,
and their hands have handled of the good word of life.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Ipswich, Sixth Month 15th, 1814.

You says what a pleasant account R. F. gave of me; you know, my dear,
that I consider a cheerful demeanour due to society, as far as it can be maintained;
therefore I often have a smile on my countenance in the midst of sadness;
yet I cannot say but sometimes the weight of sadness is removed;
but oh! when the afflictions of the Gospel, and the full sense of my absence from you,
both press upon my heart at once,
I am almost incapable of assuming an air of pleasantness.

I sent you a letter from Coggeshall, since which we have been at Kelvedon;
lodged at Mary Proud`'s--we could not, I think,
have more real attention paid us in any place.
There is a Friend of that meeting named Joseph Docwra, who had one child,
a son of about eighteen years old; he was at this place, and taken ill,
on which account he was removed home, and, after three weeks`' indisposition,
it has pleased Divine Wisdom to remove him from his
mournful parents--he now lies a corpse.
You would be astonished at seeing a letter I have perused from his father:
it is written in a disposition that evinces so much resignation and true composure.
They are very nice Friends, and this youth was of exemplary life.

At Kelvedon we had two lively meetings, one with Friends in the morning:
at that in the evening, great was the enlargement in Gospel love,
even as a living stream.
