== Chapter 8. Letters from 1814--1818

[.letter-heading]
To the Same.

[.signed-section-context-open]
Woodbridge, Sixth Month 16th, 1814.

We arrived at Ipswich about two hours before the sitting of the Select Meeting,
at which I was silent.
The sittings of the Quarterly Meeting were trying,
yet I ventured to speak in that for worship, and close, searching labour it was,
wherein the fall of Babylon was set forth, and the lamentation of her great men,
and the merchant-men, etc.; yes, and I was enabled to offer up living prayer to God,
yet my spirit remained burdened, but in the evening I visited the Men`'s Meeting, etc.,
and through plain dealing,
wherein I thought it was "`dipping the foot in oil while
treading on high places,`" I became in a great degree relieved;
for though we are required to "`show the people their transgressions,
and the house of Jacob their sins,`" how can we reach the heart
except we take along with us this holy softening influence,
which is like precious oil?
The Women`'s Meeting was visited by Isaac Stephenson,
and I was engaged to follow his testimony, which also tended to unburden my mind.
Yesterday I was at their Week-day Meeting,
and again engaged in a warning testimony and fervent supplication,
the produce of much deep wading of spirit.
We likewise appointed a public meeting for six o`'clock in the evening,
as I could not believe it right for me to stay from the Week-day Meeting here,
eight miles from Ipswich.
The evening was unusually close and warm, and the meeting very large, so that not only I,
but hundreds besides, were overdone with heat; but oh! this was as nothing,
for the Lord was graciously pleased to overshadow the assembly
with a wonderful sense of His Divine power,
while I was as a channel through which the glad tidings
of the Gospel were conveyed to many souls,
and which proved to them as living water to the thirsty.
Thus was it a blessed, heavenly meeting, ending in prayer and thanksgiving.

We are here at a simple dwelling, belonging to a nice, plain looking Friend,
named Martha Jesup.
The meeting this morning was small, yet not without laborious exercise.
One is appointed for the inhabitants at six o`'clock this evening.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Norwich, Sixth Month 20th, 1814.

I assure you that were I to give way to what I sometimes feel,
of the sense of my separation from you and our precious little ones,
I should almost weaken the powers of my mind through this means;
but then I remember that good soldiers of Jesus Christ
endure hardness for His cause sake,
and so I try to get above these feelings,
and so I would have my very dear husband endeavor to do, and quit yourself like a man.

I shall write again and again,
as way continues to open for my procedure in the
arduous path in which I now renewedly tread.
I find it is the same way I took many years ago,
wherein it pleases the Lord to try my faith in His power,
and to place my dependence on Him alone; and often, very often,
does He fulfill what dear +++_______+++ predicted in our parlor,
for "`His Name is magnified as in former years.`"

Well, I think my narrative left off at Woodbridge, where we had a public meeting;
the people were collecting all the time, but truth triumphed at last,
and the meeting ended with solemn prayer.
Next day we went, as proposed, to Lowestoff, calling at a Friend`'s house,
the only one on the way; but were excused having any public meeting,
which I esteemed a favor, as I needed rest of both mind and body.
We were now nine miles from Yarmouth; word had been sent to Friends there,
that we should be with them seventh day afternoon,
and they were requested to find some more commodious
place than the meetinghouse for a public meeting.
When we arrived, we found they had accepted of the theatre,
and distributed seven hundred printed notices,
so there was nothing for it but to be quiet;
yet you may be sure the exercise was increased by the kind of place we were to meet in;
and, on the people`'s rushing into the theatre in the evening,
all was terrible noise and confusion; however the house was soon filled,
and then they shut the doors, and as many were thought to go away as the house contained.

I was certainly much stayed on the Lord throughout,
and when I began to speak to the people, they were soon quiet,
and there was no more confusion or bustle, though many were sadly pressed.
The sight of such a large number, so close together, was awful;
but my blessed Master gave me to speak "`in the demonstration of the Spirit,
and of power,`" and all was well; glory to His Name!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Norwich, Sixth Month 22nd, 1814.

Many are my conflicts, and deep the wading of my spirit, as I pass along in these parts,
yet I have great reason to be thankful for the assistance
which is renewed from time to time,
so that, in the present solemn engagement, I can say, "`when I am weak,
_then_ am I strong.`"
We have had many favored meetings with those who do not profess as we do;
indeed the power has been over all in most of these assemblies.
With Friends sometimes I am put in mind of that part
of [.book-title]#Pilgrim`'s Progress,# where he tried,
I think, to awake some who had taken up a rest by the way;
but alas! the efforts used were in vain.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
London, Sixth Month 27th, 1814.

When I closed my last at Norwich,
I had not time to tell you much about the Quarterly Meeting.
My exercise in it was great, but the power in expressing my feelings rose high.
I visited the Men`'s Meeting too,
and requested the members of the Select Meeting to meet
me at the close of the first sitting of the Quarterly Meeting,
when I cleared my mind of a great weight I had felt toward them.
We had a meeting with Friends of Norwich,
and in it I was enabled to invite them to a close
attention to the principle by which _that_ meeting,
which had not been the most consistent, might witness the language verified,
"`The last shall be first.`"
The public meeting was rather more laborious than perhaps would have been the case,
if the notice had been more freely circulated, for the people were very long in coming.

We arrived at Bury next evening, and found Martha Brewster very poorly; she has, however,
a certificate for Scotland: she is a true Christian, I think.
We had a meeting next day for the people at large, and stopped Friends at the close,
which seemed to answer very well, only I knew there had not been enough notice given,
which is no uncommon thing as we pass along.
After being at Maldon yesterday morning, we came on here,
and I attended Select Meeting this forenoon.

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Sixth Month 29th, 1814.

Ah!
I have indeed often thought it was well for sister Hannah
to be centered in her eternal habitation of repose,
yes, I trust more than repose;
for surely her conflicts are succeeded by everlasting glory.
Hers was no common mind: perhaps there does not a day pass without my having this,
my beloved friend and sister, much in my remembrance.
May I not say she is the companion of my mind, and has been so,
ever since her purified spirit took its flight.

Last night I went to see my long known and beloved friend, J. G. Bevan.
He appears to be rapidly declining; his legs swell, and his debility is great,
but his mind appears to be in a very desirable state, and his temper so pleasant,
that his company is quite delightful, although I am sure he is a great sufferer.

And now I may just tell you, that the large Quarterly Meeting yesterday _was,_
in the first sitting, extraordinary to me.
For a while I sat as much a blank with respect to any Divine opening,
as it was possible to be, but, suddenly and powerfully,
I was sensible of the sacred impulse to speak, beginning with, "`There is a river,
the streams whereof make glad the whole city of God,`" and was
led on to describe the purity and clearness of this river (as in
the Revelations) and those who were of the city of God;
also, in a searching testimony to the earthly-minded and negligent,
and to show how the Almighty would work with respect to the state that is called,
as it were, _first,_ to show forth His praise; that these,
in continuing to rebel and refuse, will be rejected,
and the stones of the street raised up;
for that the Lord will exalt His truth in the earth, and be glorified, etc.
The visited children that were disposed to yield thereunto were addressed.

[.letter-heading]
To the Same.

[.signed-section-context-open]
London, Seventh Month 6th, 1814.

Last sixth day I closed a long letter to you,
since which time we just took a ride of thirty miles
to attend the Quarterly Meeting at Guildford,
and returned this day, so that I only now received your sweet and valuable lines.
Oh! how your account of the Preparative Meeting warmed my heart.
I do hope that our young people, favored with so many merciful calls,
may be induced to yield to _that_ power which offers
to form and sanctify them for the most glorious purposes.
My heart yearns toward many of this class in our land.
On First day I was at two meetings at Gracechurch Street;
that in the morning was very much crowded.
Such a meeting as this was, I think occurs but seldom:
I had no painful reflections on my own account respecting it.
I told them I was thankful I had not been among them in excellency of speech,
but in the plainness of the Gospel.
The meeting in the evening was for other people, and proved relieving in the end:
blessed be the Lord, truth had the glorious ascendancy and reigned triumphant.
After meeting, a foreigner asked many questions about me, etc.
Being acquainted with the motive that induced _us_ to separate,
he seemed very earnest indeed to know more about Friends, and asked,
"`What books do you study to enable you to preach?`"
and upon being informed that we preached not from study,
but depended on that which can give the immediate capacity or ability,
he wanted to know where he could obtain any of our writings,
whereby he might learn more of us; so he was directed to a Friend`'s house for some,
and I have not heard of him since.

Dear John Hull is thought to be mending.
I saw him on First day: he was very tender in his spirit, which, you know,
is nothing new with him.

Great is my portion of suffering in this city,
where the Divine economy is so grievously broken in upon,
that the works of the visible creation are abused,
and great is the bondage and oppression under which both man and beast groan.

This is the place where many enrich themselves at the expense of much health,
and what is worse, of virtue too, and are absorbed in the things that perish.
Here likewise,
how hardly do many earn a poor pittance for themselves and their wretched offspring.
Hundreds of these seem regardless of all else but trying
to get a bit of bread anyhow (not like our poor Irish,
who will gain a little knowledge of the world they live in,
because they will _stop_ to enquire).
But what do I say?
Is not a _great,_ great deal being done to enlighten the poor, and better their condition?
and are not very many engaged in advocating even
the cause of their brethren in distant nations?
Ought not all this, together with other considerations of the pleasing kind, make glad?
yet I cannot be glad in London, but am ready to say,
Oh! the mischief of vast and populous cities; for still _depravity,_
and its consequent misery, stalk before me daily.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Seventh Month 8th, 1814.

When I first went to Ireland,
it was under very unfavorable circumstances as to much outward consolation,
but it pleased the Lord, the God of Abraham, Isaac, and Jacob, to grant me patience, and,
in the end, to bless me with spiritual and temporal blessings;
so that I could long since say, "`My soul does magnify the Lord,
and my spirit has rejoiced in God my Savior;
for He has regarded the low estate of His handmaiden;`" and indeed
I feel myself unworthy of all His mercies and of His truth.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
London, Seventh Month 12th, 1814.

I have taken leave of my dearly beloved friend, J. G. Bevan;
it was a solemn and affecting parting.
Yesterday morning was the time when we finally said farewell.
_He_ wept and _I_ wept.
I had previously spoken to him in the line of ministry,
when he seemed greatly tendered indeed.
I told him that you wished, if it was suitable, I should give your love to him,
to which he replied, "`Oh always suitable, and always acceptable.`"
Ah! my dear, he is almost gone, I think.
His mind is in a most desirable state.
I thought my feelings respecting him _delightful._

On First day I was at Devonshire House both morning and evening.
Many of us will, I believe, long remember the meeting with Friends in the morning;
for the word was declared with great power, as much so as I ever recollect, I think,
and several were much broken.
In the evening there were not less, I fully believe, than eighteen hundred people,
and many went away for lack of room.

_Uxbridge._--Many have been my conflicts in that vast and populous city (London);
now I have left it, and my poor mind and body need rest.

I heard on second day that Thomas Scattergood was no more.
He was only four days ill: his disorder was a fever.
He was mostly sensible.

[.letter-heading]
To Joseph G. Bevan.

[.signed-section-context-open]
Uxbridge, Seventh Month 15th, 1814.

[.salutation]
My Dearly Beloved Friend J. G. B.,

When we parted, I did not expect so soon to address you,
but on saying something to dear John Hull of your having written to him,
he appeared surprised, for he has not received your letter;
and as his disappointment is great, he requests me to tell you so,
and likewise to say that he thinks of you much; that this day, as he lay thinking of you,
and remembered the humility of your heart,
he recollected with sweetness the passage of Scripture,
"`Light is sown for the righteous, and gladness for the upright in heart.`"
This dear friend has been very ill for two days past, but is better this evening.
He seems to be in a very desirable state of mind,
and told me that he was not sorry for this trying dispensation,
believing it to be in mercy.

And now, my endeared friend, allow me just to say,
that I believe I shall long remember our last interview;
for although the very tender emotions of my heart found their way in some sort of expression,
I have scarcely ceased, I think, to have you before my view, with some blessed assurance,
as I apprehend, that the Lord your God is with you, and will be with you,
so that all your painful feelings will be, in His time,
turned into everlasting joy and consolation.
Why then, should I yield, as I do,
to that tender sorrow which some felt in taking their leave of another apostle of Jesus,
so that it drew from him a language like this, "`Why do you weep and break my heart?`"
but you will, you must forgive me, my long preciously beloved friend,
and bear with my weakness.

I long much to hear of you; I might have a few lines at High Wycombe,
addressed to Thomas Edmonds.
My dear Rebecca will surely spare a few minutes,
when her attention is not requisite for you, just to relieve my anxiety.

I have been very much indisposed since leaving London, owing, I believe,
more to mental than bodily exertion, although I had much of both.
We attended Monthly Meeting here on fourth day; were at Amersham Meeting yesterday,
and are going to a public gathering here this evening.
The time approaches, and the thing is awful.
I must take my leave, being, in more affection than I can convey through this medium,
yours,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
1814.

You ask, am I acquainted with feelings of fear, etc., on waking,
with respect to a subject that was agreeably concluded on over night?
I can tell you that I am not wholly ignorant hereof,
but then I do not mind these morning clouds, for if I did,
and make very minute observations, as of the wind, I fear I should neither sow nor reap;
so I would not have you take too much notice of these feelings, only,
when a thing is comfortably concluded on, leave it so;
this will save you a deal of unprofitable thought.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
High Wycombe, Seventh Month 16th, 1814.

We arrived here last evening, having taken a solemn leave of dear John Hull.
Oh! my dear, it is very affecting to see him so disabled,
for you may remember that he was very active, and to be among Friends and others there,
and feel the loss his illness is to community, is really cause of sorrow;
but he is in a sweet, resigned state of mind,
and his beloved companion in life much supported.

And now let me say, as is often the case, I really feel myself a poor creature,
and sometimes am ready to sink into discouragement,
in these awful engagements of holding meetings, etc.;
but knowing that nothing can be gained hereby,
I rather try to commit myself into the Divine Hand, and hope in the Lord Jehovah,
that He will keep me from being _greatly_ moved, and renew my strength of mind, yes,
and of body too.

Your recurring to the language uttered in supplication on my account,
is particularly seasonable.
May it please the Most High to hear your prayer, and grant me preservation,
even for His own blessed cause`' sake.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Buckingham, Seventh Month 21st, 1814.

Thinking of Burford is a great lesson to me, for had I not been in too great a hurry,
when there two years ago, my mind had now been more at ease respecting it.

Since writing the foregoing, we have been at meeting here.
Oh! what an awakening opportunity it was.
The meeting was appointed for Friends _only,_ and they are but few in number,
but I was engaged to speak twice on my feet, and then in solemn, fervent prayer.
A nice little man sat next me, a minister;
he and his wife have but £20 per annum to live upon, I understand.
My last to you was closed a short time before the public meeting at Wycombe:
the meetinghouse was full; many went away for lack of room: it was very warm indeed,
but I did not mind the inconvenience of the poor frame.
Many, I believe, were thankful in being there.
On second day we partly rested, but two or three private opportunities occurred;
for which, however, if I had not believed that truth required it, and opened the way,
I should have thought myself very unfit.

We went to meeting at Tring yesterday, six miles on the way here; where,
though I felt very poorly,
I was engaged both in testimony and supplication in an encouraging strain,
but I did not know that things were as high as sometimes; yet, when I lifted up my eyes,
oh! the tears of tenderness that were strewing all about me;
and when we came out of meeting, almost all the young people were wonderfully broken;
some of them took my hand, and could hardly speak for weeping.
It was truly delightful and consoling,
to see that the power of the Lord had reached them, and that they were so near the truth.
I need not tell my endeared companion in life,
that nothing belongs to the creature of glory or praise, but to the Lord alone.

I feel trembling of heart now, in looking toward the meeting this evening,
because it is a great and awful thing to call the people together,
and to attempt to speak in the name of the King immortal; besides I am but weakly,
yet I know that if the Lord require this of me,
He can strengthen mind and body--to Him I desire to look.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Worcester, Seventh Month 26th, 1814.

The public meeting at Buckingham was not so large as was expected,
yet there was a good degree of life attending, for which my poor mind felt thankful.
I believe many were impressed with the truths of the Gospel.
First day was spent at Birmingham with our Society,
the two meetings being both such as interested my feelings much.
I was largely engaged in the ministry among them,
and after supper we had a precious season in the family where we lodged.
After feeling what I did in that opportunity,
I found myself quite at liberty to leave Birmingham,
so we moved toward Worcester on second day.
After we had got near Bromsgrove,
the men Friends proposed that _they_ should be at the trouble of driving, by dividing us;
the change had not been made many minutes,
till the horse which I was behind stumbled and fell, jerking us out.
None of us were, however, materially hurt, that we know of;
I am bruised much more than the others, and feel more shaken with the fall,
but am able to get on without much difficulty.
Anne, dear creature, behaved with great fortitude and affection on the occasion.
It was a very awful thing to happen,
and I consider it a great mercy that none of us were killed on the spot,
or more hurt than we are.
On our getting to Worcester I went to bed, but got up in the evening,
and appointed a meeting for yesterday at ten o`'clock;
it was attended by Friends and some others, and was a solemn, heart-tendering season.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Gloucester, Seventh Month 29th, 1814.

We had the meeting at Tewkesbury as proposed; a few attended who were not Friends,
and it was favored, in some precious degree, with life,
especially in solemn supplication.
After supper several friends came in, and a religious opportunity occurred;
many young people being there, for whom I felt much Gospel solicitude.

I seem clear of this place, for the present, however;
having been enabled to use plainness with Friends yesterday morning,
and had a pretty full and living meeting in the evening with others,
although it thundered and lightened at times,
during the whole of the time we were assembled.

Probably this may be nearly or quite the last time I address you,
till seeing you once more.

[.letter-heading]
To a Niece who had the Care of her Children in her Absence from Home.

[.signed-section-context-open]
Swansea, Eighth Month 2nd, 1814.

It is matter of great consolation to my mind that you are preserved in usual health,
and causes my poor heart to flow with gratitude to
_Him_ who graciously takes cognizance of us,
and _that_ continually.
Ah! my dear, He knows what it has cost me to leave all, and to continue thus long absent;
but, blessed be His Name!
He still grants the resigned state to me; even now, that I am so near you,
I believe my line is to turn my back upon Milford, when favored to meet your uncle there,
and move toward Bristol, taking some meetings by the way.
My love is to my precious children;
I hope they are willing to resign their dear father to come over the great deep,
to be engaged in the service of their Heavenly Father, and to help their poor mother,
who likewise desires to be given up to serve the Lord.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Gisborough, Ninth Month 14th, 1814.

I often feel desirous that you yourself may be comforted,
both temporally and spiritually, which I trust will be the case,
as you endeavor to live up to what you know of the Divine will,
and are earnestly desirous of _growing_ in that which is unchangeably good.
I wrote to sister Nancy the other day; my health had then been poorly for many weeks,
so that I got along with more difficulty than any can imagine,
but those who know how to sympathize with the low and afflicted.
_Now,_ through Divine mercy, I am considerably relieved.
Oh! what a blessing is health!
I am a poor, tribulated, absent sister, separated from my dear children and family, in,
what at least I believe to be, the bonds of the Gospel.

[.letter-heading]
To A. E. and A. Grubb.

[.signed-section-context-open]
+++[+++Probably 1814.]

[.salutation]
My Dear Sisters,

It is depressing to my feelings that we should be so separated.
The _occasion_ of our being deprived of each other`'s
society renders it additionally trying.

The dispositions of Divine Providence are, however, unerring;
let us try to acquiesce in His dealings with us.
He takes judicial notice of us at all times,
and will not fail to reward our humble resignation a hundred fold.
When brought low, may we wait in _faith_ for brighter days;
so will the Sun of righteousness arise, in His own due time,
and dissipate all the clouds of dismay; yes, He will come "`with healing in His wings.`"

[.signed-section-closing]
Your affectionate sister,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Cork, First Month, 1815.

We have got on remarkably well, and accomplished the journey by three o`'clock.
T+++.+++ and M. W. appear glad to see us.
I have not been in good spirits today,
but I studied my little French book a good deal of the way,
and almost had the conceit to anticipate the reading
of Fenelon and Guion _some day_ in their own tongue.
These pious individuals had surely learnt to possess their souls in patience,
which I greatly fear I am deficient in;
but if I fast from spiritual as well as temporal delight, let me fast in secret;
I will try, as it were, to "`anoint my head and wash my face.`"
So, my dear, if you hear that I am very cheerful, remember this resolution.

_First Month 15th, 1815._--M. H. is here:
she supplicated at the close of the meeting yesterday,
that it would please the Almighty to be with us during this Quarterly Meeting; and,
with respect to this morning, it has seemed to be the case,
for there was considerable life felt in the offerings that were made.
I had thought that may be I might be silent in the assembly; and that,
if I knew anything of what was good, things were going on very well,
for which my mind felt grateful; but I soon after began to fear, that if I held my peace,
some confusion would cover me, for interrupting the current of life,
in the stream of ministry, which I thought I saw flowing sweetly,
proceeding from the Source of all good; so I ventured on my feet.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Cork, First Month 17th, 1815.

I got through my little _say,_ respecting my late journey, to the satisfaction of my mind;
it was comprised in a very few words.
M+++.+++ H. went with me into the Men`'s Meeting,
where I was enabled to allude to your joining me on the other side the Channel,
and it seemed with clearness.

The Select Meeting was a remarkable time.
The state of Youghal Select Meeting came first;
then a concern spread about Friends in the ministry, that they should avoid sounds,
tones, etc., and several spoke.
At length cousin Margaret Grubb expressed something,
so exactly answering to what you wrote about the ministry
(mixed with caution) and even mentioned those words,
"`The time of the singing of birds is come,`" that my poor heart beat violently,
and the impressions were such as to induce me to tell Friends of your exercise,
and to ask leave to read part of your letter, which was readily joined in with,
and seemed to bring with it great solemnity.
I came in here directly on our breaking up, and wrote this,
my hand and heart still trembling with what I have felt this day.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Third Month 6th, 1815.

I think I can hardly do less than acknowledge to
the kindness and mercy of the Great Shepherd,
who caused me intelligibly to hear His voice to come to this city;
for He is making good His promise to be near to help.
My health is better than I had any reason to expect, and above all,
He is affording His light, the aid of His Holy Spirit from one visit to another:
sometimes His blessed power rises into glorious dominion,
to the melting and tendering such as have been too negligent in time past.

I often think of the encouragement handed me by some of my friends before I left home,
and find they were right in their belief that the Lord would be with us,
although we have indeed to be baptized, and rebaptized for ourselves and the visited.
Think not, my dear +++_______+++, in what I say,
that I rejoice as one that puts off the armor; no, I find it still fast about me;
but I extol and adore the wisdom and power of Truth in its leadings;
desiring to be fully subject thereunto--surely nothing
else can keep us in the way in which we should go.
Oh! how awful a thing it is to move in the manner which we profess to be called to.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Second Month 27th, 1816.

My dear mother`'s hope is similar to our own, that we may get well through here,
and return to you in peace; but there seems a great deal to be done and suffered,
previously to our meeting you again.
We are still prosecuting the visit, and with humble gratitude I may say,
we are helped with a little help.
Oh! it is an awful thing to visit families: no one knows what I pass through,
nor how languid I feel; yet, at seasons, I trust I shall be brought to acknowledge,
with respect to this engagement, "`It is the Lord`'s doing, and marvelous in my eyes.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Third Month 11th, 1816.

Yesterday was pretty fully occupied, for we had a public meeting at Meath Street,
besides the two meetings in course at Sycamore Alley,
and we visited an individual at the rise of the first.
I was mercifully helped to get through, without more fatigue than when less engaged.
These religious opportunities were all attended with Divine life and power.
The meeting at Meath Street was very large, and many children getting in,
they became very noisy after I sat down, and the meeting was near a close,
upon which I rose, and remonstrated with them; they listened quietly,
while I told them how the Almighty destroyed some wicked children formerly,
who mocked at what was good, etc.
I then found my way open to supplicate the Great Name,
all which time a good degree of silence was observed, but they began again to laugh,
etc., which renewedly brought me on my feet to speak to them for their conduct,
and the meeting became solemn on separating.
On the whole, we have great cause to be thankful.
They went away in an orderly manner.
It was a very large meeting,
and in a part of this great place where the people are least civilized.

[.letter-heading]
To Abigail Grubb.

[.signed-section-context-open]
Dublin, Third Month 16th, 1816.

[.salutation]
My Dear Sister,

Often, since coming here, I have thought of writing to you, but was discouraged,
lest I should not be able to do it in such a way as to interest your feelings;
and I have very often told you and our other dear sisters,
that you are in my affectionate remembrance; indeed I think much of you,
amidst my own struggles to get through the mass of religious
concern which was before me on leaving home.
You, my dear sister, are, I trust, filling up your day`'s work another way;
and if this be the case,
I believe eventually it will matter little by what
means we are brought to receive the sentence of,
"`Well done, good and faithful servant; you have been faithful over a few things,
I will make you ruler over many things: enter into the joy of your Lord.`"
Many, I believe, are your secret cogitations, and perhaps your fears at times,
respecting your own spiritual state;
but my mind is often comforted in looking toward you,
hoping that you have obtained a precious degree of life, even as through death;
though this life may be "`hid`" (from your view at times
it is) "`with Christ in God;`" so that my dear sister,
you have reason to say, "`Though I walk through the valley of the shadow of death,
I will fear no evil, for You are with me; your rod and your staff they comfort me.`"
Surely He whose name is Almighty, will be your all-sufficiency, as you look to Him;
for "`the needy shall not always be forgotten,
nor the expectation of the poor perish forever.`"

We are by degrees tightening the load,
or breaking through the _mass_ I mentioned with respect to this place.
_It_ may seem rather a large expression, but really, my dear sister, it felt no less to me,
nor did I ever more clearly see the impossibility of accomplishing what was before me,
but as the Divine Arm was extended marvelously for my help.
I have often been much discouraged, from my feelings of body,
but when I have in every sense found I was weak, then was I strong;
for the Lord has made His strength perfect in weakness.
Oh! blessed and praised be His ever adorable Name!
It matters not how we are reduced if He is exalted, and His truth reigns over all,
in us and through us.
I sometimes hope it may ultimately be so here, as indeed it often is in families; but,
though some living testimonies have been borne in meetings,
and some solemn supplication vocally offered up to the Father of mercies,
it still seems to me that we have only been, as it were, going round the walls yet;
that the time has not yet arrived to proclaim, "`The sword of the Lord and of Gideon.`"
Whether we may be thus permitted to rejoice,
in everything yielding to the Divine word or not, I desire to leave;
the will of the Lord be done.

We held another very large meeting at Meath Street, last fourth day evening,
which was very solemn, and the truths of the Gospel were largely opened:
there being thirsty souls present, it seemed to me that they heard the word with joy.
It does not feel as though that meeting had closed these public and awful engagements.
It appears that we have paid one hundred and forty visits in families,
and yet there remain above forty.
I was thinking that may be tomorrow week would clear us out.

[.signed-section-closing]
Your sympathizing and affectionate sister,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To a Niece.

[.signed-section-context-open]
Dublin, Fourth Month 29th, 1816.

Please give my dear love to brother and sister Davis;
I know they will think of us who are assembled here,
and some of us poor things especially.
My dear brother`'s tender sympathy has proved a cordial to my mind,
when almost ready to conclude myself fainting--tell him so, and he will understand it.
Oh! if we are members of the one mystical body, we shall feel with and for each other,
in seasons of sore trial.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Belfast, Ninth Month 16th, 1816.

Yesterday we had as large a public meeting as I ever remember to have seen, except once;
and it was, I think, a time of renewed help, even wonderfully so:
among more than a thousand persons there was not the least noise,
and a very remarkable solemnity in silence before we separated.
I was almost surprised to find a continued weight on my spirit after all,
but the issue is that another meeting is appointed to be held this evening,
at the Academical Institution, quite at the opposite end of this large and populous town.
It is a very fine, strong building, and every way calculated for the purpose.

I have now again to look deeply to the inexhaustible Source of help and strength.
It is a marvelous thing in my eyes, that any one so insignificant, yes, I often think,
even despicable, should apprehend herself called to these awful engagements;
but God "`chooses the weak things of this world to confound the wise,
and the foolish things of the world to bring to nought the
understanding of the prudent,`" and it is not for me,
a worm, to say, "`What do You?`"
but be this as it may, my dear +++_______+++,
I think no one ever felt more humiliation and awful fear than I do.
The baptisms of my spirit are, at times, such as may be termed agony.
Oh! may Divine mercy and goodness strengthen to endure hardness,
as one who would willingly be a good soldier of Jesus Christ.

_Ninth Month 17th._--The meeting yesterday evening was very much crowded,
and proved another season of Divine favor.
I was comforted in hearing the voice of my dear companion,
and to find that his testimony had the effect of
gathering the assembly into solemn silence.
I thought, in the meeting, and afterwards, that the pure,
simple doctrines of the Gospel were gladly received, even as it is said,
"`Doctrine shall drop like rain,
and speech distill as the dew`" and really I was
ready to conclude it was worth all I suffered,
to be sensible that thus the Almighty is graciously pleased
to make way for His truth in the souls of men;
but I soon get down again, as was the case this morning before I rose from my pillow;
yet I do endeavor to be still, and wait as a servant, disposed to receive fresh commands.

We have now taken solemn leave of this family.
There are two children, a son and daughter, nearly grown up:
they were affected to many tears in the opportunity.
We had also the company of a very solid man, an officer, whom A. W. brought to breakfast:
most of us shed tears of contrition, in which he joined,
and took a most tender leave of us.
He appeared to feel my J.`'s supplication,
for he asked that all present might be enabled to bear the cross,
and strengthened to pursue the line of holy direction;
alluding to the text which speaks of being strengthened out of Zion.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Ninth Month 30th, 1816.

Yours which conveyed to me the moving particulars of dear +++_______+++`'s last hours,
met me here on fifth day evening.
I had previously received the affecting tidings of her removal, by a letter from home:
it overtook me at Drogheda, a large town twenty-four miles north of this city;
we were just then preparing for a meeting with the people,
and had procured a place that would hold two thousand persons; think then, my dear,
what my feelings must be, when under such an exercise,
to receive the intelligence that +++_______+++was no more.
I stayed pretty much in my room at the inn until meeting time came;
the house was about half filled,
and I was mercifully assisted to get through that great exercise,
to my humble admiration.
We were, to be sure,
comforted in reflecting that your dear +++_______+++ had given those around
her reason to believe she was going to be released from all trouble,
but you know my tender feelings would be greatly touched.
I obtained relief in tears, for though _I_ also believed she was gone well,
how could I but feel sorrowful emotions?
Well, my dear, she is gone; and I desire to prostrate myself, in grateful acknowledgment,
to that Providence who has, I trust, in wisdom and mercy, taken her to everlasting rest.
Oh! what should I do but for this consolatory hope?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Mountmellick, Third Month 26th, 1817.

It has pleased the Most High to give us great liberty of spirit in a very solemn meeting.
Oh! how the stream of Gospel ministry flowed in its purity and in its plainness,
and how did it pass all obstruction, and break through, until it became,
in the blessed power, as a river that could not be passed over.
The meeting ended in solemn, fervent prayer;
and in thanksgiving and praises to Him to whom alone belongs all the glory.

My dear companion was considerably enlarged, and endued with living authority,
to the rejoicing of my spirit; but, my dear +++_______+++, we were not to dwell here;
we were filled to be emptied, and empty we are till again filled.
May we wait on the unmixed and inexhaustible Fountain.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Moate, Fourth Month 4th, 1817.

I cannot tell you how constantly I am thinking of you,
nor how much we converse about you, amidst our great exercise of mind in this journey.
Now it always seems to me that you would find most relief,
in endeavoring to look from yourself, and your deeply depressing feelings,
to Him who "`carried our sorrows and bore our griefs.`"
Do try to commit yourself entirely to Him, your blessed Savior,
who is ever ready to receive us, as we seek resignation, and to grant us this great _gift._
Oh!
I have often experienced,
that when I sought willingness to suffer as long and as much as the Lord pleased,
my distress was mitigated, and those painful feelings,
which proceed from some derangement of the system or frame, were more easily borne,
because He can make hard things easy, and, with the balm of His Divine love,
sweeten the bitterest cup; therefore "`we glory in tribulation also,`" etc.
I know, my dear,
you had better not allow your mind to dwell so much on the way in which you are affected.
I forget who says, "`Are you in trouble +++[+++or darkness]
heed it not (or to this effect); for if you do,
it will but increase upon you;`" and then recommends looking up to Him who is above all:
now I can write thus to you from a degree of sympathy,
for I know what it is to be tried in the very same way;
and to look from one`'s self to the Lord, who can gather us up to Him, out of,
and away from all darkness and sorrow,
is that in which we receive capacity nobly to endure,
and say amen to all His dispensations.
So, my dear, farewell in Him, who is, I believe, permitting you to be sorely tried,
that He may bring you to a fitness to walk with Himself in white raiment.

[.signed-section-closing]
I am your truly affectionate

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Sixth Month 19th, 1817.

However we may be drawn by our natural feelings,
to account for sorrow from causes that are secondary,
it is surely much our interest to look beyond all these,
to Him who can give us to be of the number to whom all things work for good.
Does dear +++_______+++feel after the dew which can cause a growth and increased fruitfulness,
to the praise of Him who has called her with a high and holy calling?
There is no one thing relative to the religious state of our Society in this land,
more discouraging to me than the lack of tenderness
and true humility so seldom seen among our youth.
Much of this precious sense of the Divine influence is not, I think,
to be met with in very many places where it has been
my lot to visit within the last year and a half;
but if an individual here and there, mercifully and peculiarly met with,
would fully submit to the power, I believe these would have many followers.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Blenheim, near Waterford, Third Month, 1818.

Well, he is gone! (Dr. Atkins) a truly valuable member of the community; happy, however,
for him to be taken from the evil to come,
to be admitted into the realms of eternal light and life,
with the redeemed of all generations.
How can we, with these sublime views of his change, continue to mourn and lament his loss?
Shall we not rather give thanks?
and oh! shall we not earnestly desire that _we_ likewise may so run as to obtain;
looking steadfastly to the same power, even the Lord Jesus,
the Author and Finisher of our faith.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Cork, Third Month 16th, 1818.

It would be unnecessary for me to attempt a full
detail of my distress in the way to this city,
and, should I even make the attempt, description would fail me; suffice it to say,
that while my beloved companion united with me in awful silence,
at the little inn on this side Rathcormack,
I thought I distinctly heard the Divine voice, saying,
"`You have resigned your all to me, I will care for those who are left.`"
I need hardly add that this was enough;
the way to proceed on our journey was clearly opened,
and I did not dare any longer to look back:
were it not for the solemn remembrance that this voice which I allude to,
is a "`still small voice,`" I had not passed on from Rehill,
nor even have proceeded as far as that place;
but the Lord is "`not in the earthquake,`" nor "`in the whirlwind,`" nor "`in the fire.`"
Well, my dear friend, it is not for us, poor, short-sighted beings,
to query why we are thus conflicted, but to seek after patience,
and repair to that Name which is "`a strong tower.`"
Yesterday was, I think, a day of some good tidings to Friends here,
for we had to believe that it is the good will of the Most
High to bring about a blessed revival in this meeting.
We took a solemn leave in the afternoon,
putting Friends in mind that this is more than "`the
third time`" that we have come to them,
and have not spared; the meeting closed after fervent prayer,
and committing all to the Lord.
My poor frame was and is sensible of much debility, but I will not talk much of that now.
It looks as if Youghal lay in our way to a quiet return home, so that,
although it is trying to think of going there,
especially after our summer visit in that place,
yet it is no doubt better to check the disposition
to reason against the simple openings of truth,
lest we should darken Divine counsel.
Now, while I seem to write as one who had confidence,
it is under a sense of as great weakness as was ever my experience;
neither did my poor mind ever dwell more on my own
nothingness and insignificance every way,
than in this little turn-out from home.
Surely it is no wonder that I should be greatly afraid of missing my way,
or letting go my hold of that wherein only there is safety.
