== Chapter 9. Letters from 1818--1820

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Third Month 28th, 1818.

In the evening of yesterday a meeting was held for those not in membership with us,
at Sycamore Alley; the meetinghouse was pretty full,
and it proved to be a time of renewed favor.
I was very much exercised previously to it, and greatly exhausted after it,
but it was so well got through, I have only to be thankful.
I think we have had one hundred and sixty family visits,
and last night`'s meeting was the fifth, so that one would think we were near a close;
but I look towards First day with considerable weight on my mind,
and have only to do as I have often been instructed, commit my all to the Lord,
whom I have ever found worthy to be trusted in;
but oh! how great is the reduction of the creature which these things require,
and the will must be crucified again and again.

How often, since coming here, have I thought of Paul`'s going up to Jerusalem,
and wished to imitate his example.

On First day morning we had a very large meeting, wherein great solemnity prevailed,
and the members of our Society were addressed in Divine authority,
much to the relief of my mind.
In the evening we had a crowded house, and I thought all my preparatory sufferings light,
compared to the delightful sense of the dominion of that eternal Power,
which was gloriously manifest from first to last.
The meeting closed in great stillness, after solemn supplication,
wherein many secretly united, and one or more uttered, Amen, Amen.

Thus my dear, we have indeed reason to bow low before the great and mighty Jehovah,
in whom is everlasting strength.
He is indeed worthy to be praised and trusted in.
Everlasting high praises to His adorable Name, says my soul.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Fourth Month 26th, 1818.

Oh! that my dear children may love and fear God.
Oh! that their minds may be tender and contrite.
It is the first blessing their father and mother ask for them.

I miss my beloved brother (Davis) wherever I go; no marvel that I should do so here.
Ah! we could converse together in great christian freedom,
for He was a disciple of Him who exhibited pure meekness and true lowliness; and who,
for poor sinful man, became of no reputation.
Very few of these disciples appear to be left to come up to this general assembly,
but there may be hidden ones, who, in the fulness of time,
may be prepared by the same Divine Power to confess Christ before men.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Fifth Month 4th, 1818.

The important business I communicated to you, as we walked together,
almost absorbs my mind and that of my dear husband.
We hope to sit down again with our friends here in a few days,
that they may have an opportunity of waiting on the great Leader of His people with us.
I much desire they may be favored to see and feel where we are, on what ground we stand,
and to whom our eye is turned individually;
indeed I seem as though I could not endure to act without the unity of my dear friends.
My mouth has been closed, as to the ministry, ever since Yearly Meeting,
which has likewise been the case with my J. G.,
except in a short petition the first meeting day after we came home.
The prospect before us is truly awful,
both as it relates to ourselves and the present stripped state of the Society here;
yet how shall we dare to say, "`What do You?`"
or how can any of us choose or refuse?
Is it not our interest to leave all to the Lord,
simply pursuing that path on which the light shines with clearness;
for in a little while this will prove of the greatest consequence to us all?
I endeavor to keep in view, that to the obedient followers of the crucified Immanuel,
tribulations will cease and difficulties come to an end,
being succeeded by that consummate felicity which shall never end.
May we therefore press after this pure and perfect obedience unto life.
Oh! may not only we who are seniors be so engaged, but the dear children, Moses-like,
choose rather to "`suffer affliction with the people of
God,`" than to enjoy "`the pleasures of sin`" for a moment;
having an eye to the glorious recompense of reward.

[.letter-heading]
Martha Ussher to John and Sarah Grubb.

[.signed-section-context-open]
Waterford, Eighth Month 29th, 1818.

My dear and valued friends John and Sarah Grubb will, I hope, excuse the liberty I take,
in addressing a few lines to them before their leaving this land,
of which sad news I did not hear till yesterday.

Though I think I may say it has troubled me much,
even like unto parting with my own flesh, yet I have been kept from murmuring,
by this language passing through my mind,
"`Cannot the Lord of the vineyard do as He pleases with His laborers?
Knows He not best where they are most needed?`"
If the part they have been so long digging and watering, brings not forth fruit,
the laborers will be taken away from them; yet,
considering myself as one of the most undeserving and unprofitable, I cannot but mourn.
My dear husband, too, returned from Clonmel last Quarterly Meeting,
so tendered and comforted by both your ministry, of which he has often since spoken,
that, on his account too, the prospect of such a loss is truly discouraging.

I know I am not worthy to take up any of your valuable time, engaged as it must now be,
yet I could not resist the desire I had to be revived in your remembrance,
and to crave that you would, my dear, dear friends, intercede for me, a poor worm,
and for my dear husband, when favored with access to the mercy-seat.
With dear love to S. R., to your daughter, and Jonathan, I remain, my dear friends,
in affection that unites beyond the narrow bounds of this life,
and that distance cannot lessen,

[.signed-section-closing]
Your friend,

[.signed-section-signature]
Martha Ussher.

[.postscript]
====

I purpose returning to Cappagh on fourth day.
Had time permitted, what a favor my dear husband would have esteemed it,
to have seen you both.

====

[.letter-heading]
Sarah Grubb to her Sister-in-law, Mary Davis.

[.signed-section-context-open]
Swansea, Ninth Month 5th, 1818.

I assure you, that with respect to yourself and some others in dear Clonmel,
the proverb of "`Out of sight, out of mind,`" is far from applying to me; indeed,
your prediction relative to our journey has hitherto been so fully verified,
as to make some of us remember you with more than common interest; but,
had this not been the case, I believe I should have continued to feel you near,
in that under which we were mercifully allowed to separate.
Oh! my dear sister, could we ask for more than was granted in taking leave?
The omnipotent Lord manifested the sweetness of His love,
which calmed the natural feelings of the mind; this was, I think, the case throughout,
in parting with our friends;
otherwise our poor minds could scarcely have sustained the trial.
I have frequently thought of S. R. G.`'s poem,

[verse]
____
How can my pen portray the deep distress,
How paint the anguish of a heart that bled? etc.
____

Even in getting to my dear friends and old acquaintances here,
I still feel like a stranger in a strange land with my family;
but I have believed that the Lord graciously designs to sanctify it all, and by and by,
as we are faithful, to give us brethren and sisters on this side the Channel too;
so that we ought rather to thank Him, and endeavor to take courage,
than to look at the gloomy side of things; indeed my dear John is marvelously supported,
and enabled to trust for the future; for all which I wish to be grateful.
We do esteem it a favor to have the sympathy of our
friends in this time of peculiar trial of faith.
Well, my dear sister, I hope you and some others will be enabled to pray for us, that,
in all, the Great Name may be exalted.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Bury, Tenth Month 3rd, 1818.

It must be some departure in ourselves from the all-preserving influence of truth,
which can take away the love of Christ Jesus our Lord.
Oh! how is my heart at times filled with a sense of this love to many of my friends,
whom faithfulness to our heavenly Leader has prompted me to leave,
and come over here like a pilgrim; and how has my loved companion been made willing,
from the same cause, to unite with me in this great and awful movement,
not finding any true peace another way.
Well, my dear friend,
we have surely been led out by the same Divine Hand which was with Abraham, and,
in our measure, known Abraham`'s Friend to be ours.
What a mercy!
I do feel sweet peace, while endeavoring to procure a dwelling here:
if this calmness be a little lengthened out to us,
I think we may do well enough in a humble dwelling;
indeed I never did desire great things.
How do I desire that truth may prosper in dear Ireland.
Nothing could support me in the tender regret I feel in this separation,
but a consciousness that it is in pursuit of duty,
and in order that the day`'s work may keep pace with the day.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Bury, Eleventh Month 28th, 1818.

My beloved sister will perhaps think me long silent,
especially considering the mournful event +++[+++The death of Anne Grubb]
which has taken place since the receipt of her sweetly acceptable letter to me,
but really the feelings of my mind have surpassed the power of expression.

Oh! my dear sister, I not only deeply sympathize with the partner of my life,
and with his bereaved relatives, in this sudden stroke,
but I feel myself also an object of pity,
as being likewise bereaved and plunged into a state of astonishment,
which requires to stand still, to cease from reasoning, and retire to the Lord:
in endeavoring to do so, and in nothing else, have I found quiet; yes,
I think the still small voice has been heard, saying, This also is in wisdom,
and in mercy too.
I am mostly under a load of depression from day to day,
but when I go and sit down in our little meeting here,
it is wonderful to me how the Lord breaks in upon my spirit;
and it is almost invariably my lot to minister of the things of His kingdom,
and our little company are measurably contrited together.
Our late dear sister Nancy used to love to hear of the spreading of truth,
though in ever so small a degree: she delighted most in the things of God,
and made them her primary concern.
Oh! the many ways in which she sought to promote the coming of Christ`'s kingdom,
as well as the temporal good of community;
and yet how has it pleased unerring Providence to deprive us all, forever,
of such a friend.
Oh! how inscrutable it is.
Our minds derive some solace, however,
in learning that the same Providence has hitherto
wonderfully supported your minds in so great a trial.
My dear John appears to bear this affliction too, as becomes a truly christian mind;
for although nature deeply and poignantly feels this final separation,
that it is even as "`wormwood and gall,`" yet he is enabled
to have reference to the Lord as dispensing it,
and I have reason to believe that it is in some degree
sweetened by the infusion of Divine love.
Oh! this is as healing balm; may it continue to be vouchsafed to you,
our loved relatives on another shore.
Surely, without it, we are as a broken vessel; at least I know,
in the absence of this heavenly virtue, I am ready to style myself such.
Oh! the inexpressible tenderness which, I think I may truly say, I feel towards you all.

Very often I place myself in mind among my friends,
with whom I was most intimate in dear Clonmel,
and seem to want to mingle my tears with theirs, not only in affectionate sympathy,
in tender sorrow, but in mourning for lack of those who are valiant in the Lamb`'s army.
Dear R. speaks movingly of the stripping time being come.
The Lord has truly done strange things.
It is a loud call to those who remain, to give unto Him "`glory and strength,
to give unto Him the glory due to His name.`"
Who can say but that then He will do more for His
heritage than any of us can ask or think?
but, if His all-powerful, chastising hand, be not seen in these things;
if blindness that has happened still remains,
we may fear that yet further deprivations will be permitted,
and a day of desolation overtake, so that it may be said,
"`How does the city sit solitary that was full of people!`"
My dear sister knows that my soul has long travailed that the former might be the case.

And now allow me to repeat my humble hope, yes, sometimes I think sure confidence,
that the God who has been with you all your life long,
the Angel of whose presence has conducted you so far,
still graciously designs to be with you, to lead you safely through all,
to the "`fountain of living waters, and to wipe away all tears from the eyes.`"
Oh! when we can look into the regions beyond this vale of tears,
how do our souls seem to receive fresh vigour to run the race set before us,
however difficult it may at times be to us; for we are gathered up to Jesus Christ,
who trod the path before us; and we receive of His heavenly virtue, His Divine nature.
This living substance, this flesh and blood, which gives life, is worth waiting for.
My dear sister, farewell in Him, who only can communicate it;
and may you all farewell in Him.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Haverhill.

Our minds have been revived this evening,
in a feeling of that which is separate from defilement.
Oh! how truth has reigned, in one family in particular: blessed be the Lord,
who changes not, and whose truth is the same that ever it was,
and leads into the same obedience unto life.
We saw a dear child about eight years old, in tears this afternoon,
while Gospel ministry flowed to her and the rest of the family, as a flowing stream.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Wellingham, near Lewes, 1818.

Never admit a thought that it will do for you to pass along as others do,
in a line of mediocrity, and so get to rest and peace at last,
without the exposure which is the lot of some for the truth`'s sake;
rather say in your heart, "`Lord, what would you have me to do?`"
so will the dispensations of a gracious Creator be abundantly blessed to you,
and you will escape that state of cloudiness and insensibility, which, sooner or later,
overtakes the soul which is not given up to the service of our great Master.
Clearness of vision is mercifully granted to all those with whom, in early life,
obedience keeps pace with knowledge;
and the joys of the heavenly kingdom are the certain portion
of all those who do not cast up a way for themselves,
nor limit the Holy One of Israel; but who, in simplicity of heart,
follow a crucified Savior.
It is thus that we come to experience the rough places to be made smooth,
and the crooked paths straight; yes,
that we are taught to sit down in the kingdom of God,
having fellowship with all the faithful seed, even as with Abraham, Isaac, and Jacob:
in this kingdom is found joy, gladness, thanksgiving, and the voice of melody;
and thus we see that all our sufferings are more than compensated,
because this is the joy which no man, nor any number of men, nor devils,
can possibly take from us.
This is the sense of that everlasting kindness with
which Divine Goodness has mercy upon His chosen,
for He says, "`For a small moment have I hid my face from you,
but with everlasting kindness will I have mercy on you.`"

I speak of the good things of the kingdom, as revealed and granted in this life,
but I speak not as being myself full and abounding at present,
yet as being content in the will of my Heavenly Father,
who best knows when and how to dispense the riches of His grace.
Oh! that my eye may be ever turned to Him, and my dependence only on His arm of salvation.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Bury, Second Month 1st, 1819.

Remember that the promises of God are not yes and no, but they are yes and amen forever.
Therefore is it said, "`Why do you say, oh Jacob, and speak, oh Israel,
My way is hid from the Lord, and my judgment is passed over from my God,`" etc., etc.;
and then, "`He gives power to the faint,
and to them that have no might He increases strength.
Even the youths shall faint and be weary, and the young men shall utterly fall,
but they that wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles, they shall run and not be weary,
and they shall walk and not faint.`"
Thus, as we wrestle with Him, and aspire after Him, the fulness of strength,
He surely is known to give us to rise superior (I
was going to say) to all that torments us.
Oh! there is nothing like endeavoring to wait upon God.
All the advice of earthly physicians will be unavailing to you,
but the Physician of value will come with healing virtue, at an unexpected moment,
as you look _from yourself_ up to Him.
What can I say more?
This is my firm persuasion.

I know the effect of your complaint may be counteracted,
by first of all recollecting how unworthy _self_ is to take up so much attention;
and waiting upon the Lord would give a very lively and instructive recollection hereof;
and then there would be capacity to exert yourself in the cause of religion,
and for the good of civil community.
Ah! my dear, have not many in this glorious cause suffered cruel tortures of body?
and what if you, by the permission of Providence, suffer perpetually what,
to your apprehension, is even worse than the greatest actual pain:
is it not for you to endure all in reference to Him,
whose capacity for suffering was greater than that of any of the children of men?
so that there is nothing we can feel, but He has felt for us, in a body of flesh,
and to a greater extent.
Ah! you must try to come near Him in your spirit, that He may give you to wait His time,
as did the woman we read of, who still importuned Him, and was His humble suppliant,
until her _faith_ had the testimony of Divine approbation as a seal:
the moment of relief arrived, and she rejoiced in the Rock of her salvation.

You say you know your suffering is not from lack
of resignation to the awful stroke permitted,
in the removal forever of your loved sister.
I believe you; but there is no doubt with me,
that the poor frame is still more susceptible of those peculiarly distressing feelings,
to which we can give no name sufficiently appropriate, nor can any comprehend them,
save by the experience of their trying effects; hence the need there is to repair _fully,_
and with all possible speed, where description is not requisite,
in order to receive a _sure remedy._

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Southgate Green, Second Month 11th, 1819.

Many, very many have been my sore conflicts of mind, since we took leave of you,
my dear sister, and many, no doubt, have been yours; but if, in all these things,
we become "`more than conquerors through Him who has loved us,
and given Himself for us,`" tribulation will but more intimately unite us with Himself;
giving us to discover, with increased clearness,
that state which is altogether the workmanship of God, even the holy city,
the new Jerusalem which comes down from Him out of heaven,
and which is _prepared_ as a bride adorned for her husband.
Some near and dear to you and to me, have, through suffering, become already prepared,
and entered into the joy of their Lord;
when _we_ can scarcely hope for the same consummate felicity,
when _our_ poor souls are left in darkness and distress,
let us wait on Him who hides His face, whose glory is veiled as in an impenetrable cloud;
let us importune Him with unutterable sighs.
Oh! surely we shall hardly be cast off forever!
Is not He, to whom we have been accustomed to look,
a Friend to the needy in their distress?
Ah! my dear sister, none, whose experience has not been alike painful,
can form any just idea of the sufferings of my poor mind, even now;
but to whom shall we go in our trouble, save unto Him who has the words of eternal life?
These feelings, so repugnant to our nature, may be a necessary ordeal,
to prepare the vessel, as a channel through which the holy oil flows.
Oh! my soul, have patience.
I would not, however,
have you suppose that your poor friend has not known
other and more joyous moments in this place;
yes, my sister, I have felt the power in dominion in my soul;
I have witnessed the reigning of the immortal seed, when waiting upon God.
At one time in particular, in solemn silence, I could say,
my Beloved "`comes leaping upon the mountains,
skipping upon the hills;`" He made haste to help me;
there was no obstruction allowed to prevail--I was mercifully favored to see Him,
the Lord my God, sitting upon His throne:
I knew that the Lord Jesus Christ had taken unto Him His kingdom,
and my heart sang Halleluia.
Oh! do ask for me, that I may be as willing to suffer as to rejoice,
when such is the mind of my Heavenly Father, that His own works may yet praise Him, in,
by, and through me.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Third Month 19th, 1819.

Many times, since leaving your loved shore,
I have hoped that the step we took would not appear a hasty one to you,
as it truly was not to us; but then we wished to accommodate our movements,
so far as was at all consistent with our peace, to the views of our dear friends;
some of whom were hard of belief,
with respect to the necessity of our coming over before spring; so for a while,
we said little about it,
till at length it felt as though the anger of the Lord would be kindled against us,
for disobedience and inattention to His _fit time:_
thus we were at length made willing to risk all things, in giving up simply and freely,
unto the manifested will of our sure Leader and heavenly Guide; and I may confess to you,
my dear friend, that I have not since repented this full surrender,
nor has my loved companion in life.
Oh! how fully did he acknowledge to the sense which was on his spirit,
some time before he left Clonmel, that,
in refusing to yield implicitly to our duty in this thing,
we were in danger of being plunged into still greater trouble, and real perplexity:
and I may tell you that he has repeatedly testified to the goodness of the Lord,
in enabling us to yield obediently to His sacred command, such as was uttered to Abraham,
in the language of, "`Get out of your country, and from your kindred,`" etc.
Yes, my dear friend, if we are not able to distinguish this same eternal,
unchangeable voice, how then can we be of Abraham`'s seed?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month 21st, 1819.

_Fourth Day._--The meetings were laborious and dull to me,
my mind being under considerable exercise and weight, and, as it were, shut up,
not seeing any way to move; but I heard some friends say there was a solemnity,
especially on our meeting together.
I found, as I have ever done,
that it is safe to be quiet in one`'s spirit under suffering, and as in a cloud;
and I was resolved not to "`stir up, or awake`" the soul`'s "`Beloved,
until He pleased;`" so yesterday morning my bonds were broken, in solemn prayer,
in the Women`'s Meeting,
and I had a draft to sit in that of the Men`'s. Oh! it was an awful time indeed:
the Lord gave me to feel it so, in unlading among the brethren.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month 24th, 1819.

If ever we meet again in mutability,
may it be with an increase of the heavenly image and holy likeness!
The inscrutable dealings of a gracious God bring to this,
as we humble ourselves under His mighty hand;
and so we may come fully away from our fallen and undone condition,
and be made fit for union and communion with the Author of our salvation.

My heart is very sensible of much affectionate and religious
solicitude in the welfare of my dear friends among you;
the Lord will, indeed, work for the honor of His name in Ireland,
whether the privileged members of our Society will be faithful or not;
but the people can never come to anything higher,
or more safe than that with which we profess to be acquainted.
May the dear young Friends be induced to retire from the delusive,
fluctuating spirit of the world, and turn their views to the city of the great King,
even Zion, beautiful for situation, when beheld in the true light.
She indeed is on the sides of the North, but her foundation being sure, no storm,
no trial, shall ever prove too mighty for her.
Oh! then, may we not, with holy propriety, say to our beloved youth, "`Walk about Zion:
mark well her bulwarks: count her towers.
God is known in her palaces for a refuge,`" etc.

This Yearly Meeting has so far not been left without best help,
and what bows my heart most of all in gratitude is,
that solemn silence covers us at times.
In this is the power and the life, which were before words,
and remain when words shall cease;
but I consider that we are condescended to in unmerited mercy,
for we are too generally of the revolters and backsliders,
and I find that the people love eloquent orations better than to yield to the anointing,
which is truth, and no lie.
Something I hear, which induces me to say, Truth is truth, though _all men_ forsake it.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month 26th, 1819.

I trust some of us at least, are as epistles written in each others`' hearts,
not with pen and ink, but by that influence which remains to be all-preserving,
all-sanctifying.
How have I desired that this unchangeable power may be more and more known to you,
my dear, after this manner, that so you may grow up in Christ Jesus our Lord,
unto the glory of God, for such I believe you know is your calling;
and what if your spirit is often plunged into conflict, and that you should, at times,
be ready almost to conclude there is no such thing
as being established on the Rock of ages.

I have often been similarly tried,
and I believe all who wish to serve the Lord are at seasons thus proved; yet if,
in such temptations, we endeavor to cease from our own cogitations and arguments,
this everlasting foundation is again and again revealed to us,
and we are mercifully enabled to build thereon,
so that no storm overthrows our dependence.
Be encouraged therefore, to "`trust in the Lord with all your heart,
and lean not to your own understanding;`" so shall you know assuredly for yourself,
that in Him, "`the Lord Jehovah, is everlasting strength.`"

When dear young people give up all to the Lord,
it makes way for unclouded prospects in religion, and they escape many perplexities;
and if Divine Goodness sees fit to prove them in any singular manner,
it is only that they may be more richly qualified to show forth His praise.

We cannot find our interest in anything short of giving all up to best direction,
and sometimes I think, should it please the Lord to lay us on a sick bed,
we should then be thankful that He had enabled us to be dedicated to Him in health.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
London, Fifth Month 30th, 1819.

Ah! loved Clonmel, shall we not call loudly upon the dear _young_ Friends,
to turn with all their hearts to that Power which is undiminished,
and which never did change, being in itself immutable?
Oh! shall we not entreat those who are in the prime of life,
to cleave closely to the Rock of ages, which is a foundation that never can be shaken;
that so all things of a painful and sorely distressing nature,
may but tend to their establishment, instead of their being greatly _moved;_ that the Lord,
in the riches of His goodness, may yet raise many up to evince that "`truth is truth,
though all men forsake it.`"
I have a travail and care on my spirit, that the truth may prosper in the minds of many,
and that the still threatening time of more withering and dryness,
may be averted (as it were) by visited souls fully giving
way to that redeeming influence which follows them.

It was a favor that I became relieved of a very heavy
burden only a few hours before being quite laid by;
for I had it on my mind for days, to speak the word faithfully in the Women`'s Meeting,
as I had been enabled to do in the Men`'s, in an awful strain,
relative to the state of our religious Society;
and so now I have not that to weigh me down;
indeed I never recollect attending a Yearly Meeting where my share of
the burden felt more fully equal to any capacity of mind and body to sustain;
but I have been pretty quiet and easy on this bed,
for I thought I felt nothing like condemnation,
having endeavored to do the Lord`'s work in His time and way,
so far as I was favored with the knowledge of His holy will;
but then my movements are not so much in the smooth way as some,
and I get hints to try to be a little more like others,
lest what I say should not be well received; and yet again I am the same thing,
for when the Lord raises me up in His power I fear no man,
having humble confidence in His Name: but I believe none know the depth of my sufferings,
nor how much I am permitted to have the sentence of death in myself.
May He, who only is able, keep me from falling, lest, after having preached to others,
I become a castaway.
We take a deal of suffering to bring us to a holy
and blessed establishment in the immutable truth,
but it is mingled with consolation.
I hear that Friends had a few minutes in the last sitting of the Yearly Women`'s Meeting,
of solemn silence, which, as it far surpasses all words,
is cause of humble thankfulness and living praise.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Spalding, Eighth Month 17th, 1819.

We have been very diligent hitherto, having had twelve meetings,
several of them with the people at large;
and many visits to families have fallen to our lot,
although not in the regular way of family visiting; and I may acknowledge that so far,
I have thought all previous suffering more than compensated by the gracious help vouchsafed,
from time to time,
in giving a clear sight and sense of things where we have been engaged,
and also ability to speak thereto,
"`in demonstration of the Spirit and of power;`"
yet it is often through inexpressible wading of soul,
that the seed immortal is visited where it lies,
and strength obtained to lift up the voice, to lift it up, and not to fear; yes,
and then the mind is introduced again into a sense of great wretchedness (may I not
say?) in seeing its own unworthiness and incapacity for anything truly good.
Without an endeavor to be still,
I think I should surely be incapable of cherishing the grain of faith to believe that
a poor creature dare make any further attempt to proceed in so awful an embassy.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ross, Eighth Month 31st, 1819.

We have long talked of being at G+++_______+++, but have been hitherto withheld; indeed,
our path has been one peculiarly exercising to our faith,
having seen but little before us; so that sometimes, I believe,
our friends have rather marvelled at our lack of
capacity for planning with respect to our movements;
meetings with people at large have presented one after another,
much to the baptizing of my spirit, and reducing the creaturely will;
some of them have been very relieving seasons, wherein truth was in blessed dominion;
at other times,
great has been the labour of spirit and suffering with the immortal seed under oppression,
when the power has not risen very high throughout the meeting;
but I am not sure that the life of truth may not
have been as effectually visited at such seasons,
as at those wherein more sensible consolation was witnessed;
for no fountain can rise above its level,
and where the precious life of Christ lies low in the souls of men,
it is a mercy to be kept with it in the ministry of the word,
wherein we are sometimes made instrumental to the
removing that which obstructs its arising.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Calne, Ninth Month 10th, 1819.

After my husband closed his letter at Gloucester,
we went to the meetinghouse and sat about three-quarters of an hour,
but very few of the people coming,
I found that what I had told Friends in the morning was realized,
that a meeting in that comparatively small house would not be likely to answer my purpose,
but I yielded to their wish to try it.
We told the small company collected how it was,
and that it was probable they would be informed next day,
of the time and place for holding a meeting with the inhabitants.
Accordingly, through much discouragement from without, we got the town hall,
and a large meeting it proved to be; and perhaps one more largely favored I never knew,
for the doctrines of truth flowed freely, even without obstruction,
I believe for an hour and a half at least, and the meeting closed in solemn silence,
after a few sentences uttered in living prayer and praise: so that,
after all I had passed through in that city, the language was raised in my mind,
"`Thanks be to God which gives us the victory, through our Lord Jesus Christ.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Bury, Twelfth Month 1st, 1819.

While I was busied in my family affairs, my loved parent was taken ill,
and alas! in one week from this seizure, she was gone forever.
Dear creature! she was very sweet in her spirit, and soon gave herself up,
saying that death had no terrors for her;
and sometimes her joy was so great in the prospect of a glorious eternity,
that she sang praises, with a melodious voice, unto her God;
so that it was delightful to be with her.

We are indeed tossed and tried; our building seems to be shaken to the very foundation;
yet I believe that there is a foundation that can never be removed;
and if we are but found thereon, all our besetments and every storm,
as from the north and the south winds,
will but have a tendency to fix us firmer on this invincible Rock;
so that I wish we may take courage to commit all to the Lord,
in that humbled state wherein we can say, "`Though He slay me, yet will I trust in Him.`"
I have long been persuaded that trouble does not leave us as it finds us:
we are either more intimately united to that Purity which is uncreated,
or we are more widely separated therefrom; now,
in proportion to the tenderness of spirit which becomes ours under suffering,
so are we grown and growing in the heavenly image, and holy likeness;
so that I know of nothing so desirable as a broken heart and a contrite spirit; and,
if we wait in passiveness on the Lord, I believe He will give it.

Do tell me how it is among my dear friends around you;
whether there is anything like revival, or ability to gird up the loins,
and become valiant for the unchangeable truth.
I should be glad to hear of many breaking forth, as on the right hand and on the left;
being separated from the hindering things, and chosen for service.
I feel much interested in the welfare of many in dear Ireland;
you may tell my friends so,
and that my loved partner and I have not an easier path to tread,
than was the case when on the same shore with you.
But it is perhaps much as we expected:
it was not with a prospect of finding the way to the kingdom less tribulated here,
that we gave up to come,
but that the day`'s work might be known to advance in some measure with the day,
and that we might have the answer of a good conscience.
Very little settlement, as in a ceiled house,
has been ours since our residence in this country; and when abroad,
we find comparatively little to answer to the life,
the heavenly anointing which is given at times in the work of the ministry; to be sure,
we have at seasons known it to be over all, especially in large public meetings;
blessed be the Name of Jehovah!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Southgate Green, Bury, First Month 23rd, 1820.

I wish, if possible,
to encourage you to cast all your sorrowful feelings on Him who suffered,
who _died_ for you.
Oh! do try in everything which afflicts, and which besets you,
to have reference to your dear Redeemer, your Savior:
it will prove of infinite advantage to you, for "`eye has not seen, nor ear heard,
neither has it entered the heart of man,`" what God has in store,
and will assuredly unfold to this state:
how the darkness of His Divine providence will all come to be light in due season,
when He shall see fit to reveal His righteousness in the sight of His sanctified children;
having, through dispensations abundantly inscrutable to their understanding,
changed them from glory to glory, by His own eternal spirit.
Endure therefore, the present groaning as under heavy bondage; yes,
be glad and rejoice therein, as coming upon you for your refinement;
designed to incorporate, as it were, into the very nature, the essence of Jesus Christ,
the immaculate Lamb of God, who takes away the sin of the world;
who washes us in His own blood, that we may be without spot, or wrinkle,
or any such thing; even ultimately faultless before the throne, with exceeding joy.
Ah! can we expect thus to reign with our Lord, unless we submit to suffer,
as well as to do anything He pleases?
not that I believe Him to be the Author of evil, but, by His permission, much befalls us,
unto which we are ready to give this term; and how impatient are our spirits under trial,
until calmed by the Divine influence, which it is much our interest, as well as duty,
to wait for.
I think you speak of feelings, which you seem to marvel should be yours: do you forget,
my dear +++_______+++, that He who was holy, harmless,
and undefiled (not like us poor frail sinners) felt an infinite weight of trouble,
of anguish inexpressible, for our sakes?
Do you not call to mind, that when the nails had pierced His hands and His feet,
that when lifted up on the cross to suffer a cruel and lingering death, He,
the dear Son of God, cried out to His Father, "`Why have You forsaken me?`"
Thus has He trodden the tribulated path to ineffable glory, as it were before our eyes,
that we may be encouraged to follow Him _through all;_ to come to be heirs of God,
and joint heirs with Jesus Christ.
Oh! let us try to conclude, when seemingly abandoned by all that is good, that,
if we perish, we perish at the feet of our Lord, as humble suppliants;
while yet no words can possibly describe the mournful,
the painful state in which we lie prostrate.

Thus, having thought a great deal of you, I watched for a little openness in my mind,
to portray my tender solicitude, my affectionate feelings of sympathy,
as well as my blundering pen is capable of.

I write this on First day afternoon, previously to a public meeting which,
in great awfulness, we have ventured to appoint in this town.
I might tell you a deal of my own deep exercises,
and of travail which has been my portion mostly, for several months,
but perhaps this is not expedient; I shall therefore add but little more,
than that we are now beginning our engagements,
for which last Monthly Meeting liberated us.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Earlham, near Norwich, Third Month 31st, 1820.

I have, ever since leaving dear Ireland, as well as before,
cherished a consoling hope that the Lord is at work in many minds, unseen as yet,
but to be made manifest in due season, for His great Name`'s sake,
and for the support of those testimonies which are of the unchangeable truth;
for whether, by mingling with the world, we, as a people, still fall away more and more,
or not, the fundamental principles which we profess will be embraced; yes,
the time will come to Ireland, when they who sit in darkness shall see great light;
and to them that are in the shadow of death, light will spring up; blessed be the Lord!
I know, that for Zion`'s sake, you mourn before Jehovah, but I humbly trust,
the more of this,
and the more glorious the preparation to put on "`the garment of praise for the
spirit of heaviness;`" and when we come to receive "`beauty for ashes,
the oil of joy for mourning,`" how does the season in which we have suffered,
seem to have been but "`for a small moment:`" thus may your Redeemer,
who has mercy on you, gather you with His everlasting kindness into a union with Himself,
which shall never be dissolved, says my soul.

Our line of religious duty has not been confined to our own Society,
but we have many _more_ public meetings; most of these latter are seasons,
wherein He who "`leads Joseph like a flock,`" sends
forth His light and His truth among us:
sometimes it is over all; yet this is seldom the case, but through considerable labour;
but, when the obstruction comes to be removed, even by word and doctrine,
it is an unspeakable favor. With respect to Friends,
I confess my poor mind is scarcely ever fully at liberty.
I often think of what Job Scott said,
"`There is a deadness and a form which my spirit
hardly rises superior to the oppression of,
during the whole of a meeting;`" but I believe that the Gospel will more and more spread,
both in this and other nations.
I look forward to Yearly Meeting with something of dread, not joy;
for it is hard for the little, lowly seed of life to rise into dominion;
it being a time and place wherein there is much lack of true simplicity;
but it is well that we should keep in view, that "`unto us it is given,
not only to believe on the name of the Lord Jesus Christ,
but also to suffer for His sake;`" there is a portion of suffering dispensed in His time,
for His sake, though not like what befell the first Christians.
It is now _spiritual_ imprisonment, and _spiritually,_
the Lord`'s servants are sensible of being stoned, and of being wounded.
May we dwell deep in spirit with the eternal Power, in which alone is our preservation!
Surely the sons of Zion will be raised up, as against the sons of Greece;
and the truth must be spoken, although opposed to the wisdom of the wise!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month 27th, 1820.

The winter is gloomy, but it has its own peculiar benefit;
it teaches us to reverence the Divine Hand, and to feel our dependence thereon.
I love to see my friends made sensible of the necessity
of waiting for that Divine voice which,
in due time, is heard in the soul truly chaste to God; even saying, "`Rise up, my love,
my fair one, and come away.
For lo, the winter is past, the rain is over and gone; the flowers appear on the earth;
the time of the singing of birds is come,
and the voice of the turtle is heard in our land.`"
May this be your happy knowledge of the righteousness, the mercy,
and the truth of Him who is forever the covenant keeping God; yes,
"`the joy and song of many generations.`"
Perhaps my soul never adored His wisdom and power more,
than now that I am at times under great weights and burdens;
but again He "`leads me to the Rock that is higher than
I,`" and He Himself sets my feet above all the mighty billows,
and gives me to sing the new song, even to string the harp of victory and say,
"`Great and marvelous are your works, Lord God Almighty; just and true are your ways,
O King of saints.`"
Oh! it is a most blessed thing to come to know that the Lord`'s own works,
and they alone, praise Him.
Let us, therefore, my loved friend, lie low before Him;
seeking to say amen to all His dealings with us, even in the darkness of His providence,
that He may work in us, both to will and to do, according to His good pleasure;
so shall we witness Him again and again, to make darkness light before us,
and the crooked paths straight.
The rough places shall be made plain, for the glory of the Lord shall be revealed.
These are times abundantly worth waiting for,
even as long as that Wisdom which is infinite, shall please.

I have not yet seen Ireland forgotten by Him whose bowels
are said to roll toward His people with compassion unmerited.
Oh!
Ireland,
how many of your children are under the peculiar eye of Him whose name is Almighty,
in order that He may raise up, separate, and qualify for His service;
and whether our Society come to be more conspicuous through faithfulness or not,
I believe that one day the Lord`'s own true Church
will be seen "`coming up out of the wilderness,
clear as the sun, fair as the moon,
and terrible as an army with banners;`" for the darkness
shall not be able to endure its glorious light,
and shall therefore flee before it; blessed be Jehovah!
Some of the sittings of this Yearly Meeting have so far been agreeable, even, I think,
beyond some former times; the business being less interrupted,
and sometimes there has been the overshadowing of good in a humbling degree;
but there is, nevertheless, much danger awaiting us as a people,
of our not increasing in brightness, according to our high calling in Jesus Christ.
We are yet faithfully warned--may we receive it.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month 27th, 1820.

Oh! that we may be more and more gathered, for I believe we have temptations which,
if yielded to, will scatter, will lay waste and destroy; will even hug us up,
and being of the subtle serpent, will press out the pure, innocent life.
Something of this kind I have had to declare, even as the word of the Lord;
for it weighed me down, and was like a fire within me, day after day,
and night after night,
until the Lord my God opened the way to lay down my burden for Friends`' acceptance,
in which I find some relief; but still my poor mind is sensible of much travail.
Oh! that the will of my Master may take the place of my own will,
until He set up and establish His kingdom, an everlasting dominion, in my soul,
and until He fully give me to endure all things for His Name`'s sake;
that there may be a filling up in my measure, however small,
that which remains of the sufferings of Christ for His body`'s sake, which is the Church.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Folkestone, Tenth Month 30th, 1820.

The Lord`'s dignified servants are rendered such through baptism,
and those who are raised highest in His power, have their proportionate deep plunges:
so do the works of an Almighty Hand praise Him in these and through these.

That such is your calling I cannot doubt, therefore put it not from you,
nor choose a path for yourself, lest you frustrate the Divine purpose,
and be found among those who rob God of His honor,
their own souls of inestimable treasure, yes,
and the Church of Christ of that portion of service designed it,
by these being placed in their own allotment there.

We have not yet seen Nathan Hunt, but hear of him as a valiant in the most glorious cause.
I thought, on leaving dear Ireland,
that the Lord would be pleased to send His messengers, one after another, to your nation,
and my spirit is often made thankful in its having been the case.
It is a proof of His fatherly care, and that He is still looking towards many,
to raise them up for His Name`'s sake.

Poor Clonmel!
I do believe there is a little seed, in a tender state,
under the gracious care of the great Husbandman,
and designed to bring forth fruit to His praise.
My mind has sympathy herewith: it seems to me to lie much among the dear young people.
Oh! may these be so watchful over their own hearts,
that there may be room for this immortal life to grow and increase,
and to overspread all: so may there yet be a revival,
and the Lord may place His name among you: indeed,
wherever the lot of these may be cast, as to the outward,
they will glorify the Holy Name by bringing forth much fruit.

It is a consoling reflection, that while with you, I endeavored to act faithfully,
according to my measure, and feel clear of dear Ireland in my spirit.

The public meetings are, I think,
mostly much favored with the resurrection of Divine life,
the doctrines of the Gospel being opened "`in demonstration of the Spirit and of power.`"
Our prospect is through Sussex, Hampshire, etc.; so into the West.
At this season of the year it looks particularly formidable as to the outward,
but I trust we shall be cared for.
I think we never had a more tender parting with our dear family than this time.
