== Chapter 11. Letters from 1823--1825

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Twelfth Month 25th, 1823.

There are times when the tried vessels, in possession of living faith and holy patience,
can adopt the language, "`When He has tried me,
I shall come forth as gold:`" such should not, therefore,
be too much cast down in a sense of being, as it were, alone:
this is a part of their proving, even to feel their situation as a peculiar one,
and their path as untrodden,
that the Great Name may be abundantly magnified in and through them.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Probably 1823.

It seemed to me that the savor of your mind in returning
from +++_______+++ was sweet and acceptable in the Divine sight,
and so I humbly trust it remains to be.

The dealings of inscrutable Wisdom you-ward have been of no common kind.
He has dispensed much that is peculiarly trying to nature,
because He has set His love upon you,
and designs to qualify you increasingly to glorify Him.

Oh! be humbly bold, when required in any way to serve the Great Master,
who has enabled you to be a shining light among the people in your daily conduct.
He would, I believe, give you, as it were, to exclaim,
"`Oh that men would praise the Lord for His goodness,
and for His wonderful works to the children of men.`"

Look simply and singly to Him, and He, even the Almighty One,
will sustain you by His invisible power, give you faith and courage,
and bring you through all, to His praise.
Amen.

This morning, during our few moments`' retirement together, I felt you, as I believe,
very near my spirit in the Lord; and then it opened to me,
that "`light is sown for the righteous, and gladness for the upright in heart.`"

My mind became convinced that your Savior and Judge, who sees in secret,
accepts the sincerity and uprightness of your heart; and I had to believe,
that by patiently continuing to do as well as you know how,
in the midst of weakness and frailty, you will, by and by, come to the reaping season,
and have to rejoice in heavenly treasure.
So my dear +++_______+++, faint not; be of good courage,
and your Redeemer will strengthen your heart.

We, poor creatures, are not dealt with according to our deserts,
for then our spirits would utterly fail before the Most High,
but we are favored with the adorable,
unmerited mercy of Him by whose stripes we are to be healed.
Lay hold, then, of the hope set before you, and gird up the loins of the inner man,
and stand for the truth upon earth.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Probably 1823.

Oh! my beloved +++_______+++, are you growing in grace, and in saving knowledge?
Is your acquaintance with your Savior more intimate
than was the case in days that are past?
Remember that we either advance in true and vital religion, or else we lose ground,
which latter is of lamentable consequence.

Surely the Most High designs you to be a dignified instrument in His hand,
and the earlier you are prepared for this, the happier for you.
Do try to be inward with your dear Redeemer, and, as I have said before,
never let a day pass without endeavoring to prostrate yourself before Him.
This would lead you to great humility and self-denial,
and enable you to take up the cross daily, in nothing more than in this one thing,
of governing the temper, wherein your mind would be disposed to oblige all around.
I know you often wish to be what your Heavenly Father would make of you,
and be assured this is not impossible;
but we must "`strive to enter in at the straight
gate,`" because our corrupt nature would hinder us.

My soul often commends you to Him who is able and
willing to do exceeding abundantly for us all,
even more than we can ask or think; therefore let not your tender mind wander from Him,
your blessed Redeemer, who has powerfully visited and called you,
and made you to feel His unmerited love.

[.letter-heading]
To one of her Children

[.signed-section-context-open]
About the same time.

Having been desirous of entering into all your painful feelings,
and sympathizing in those dispensations which inscrutable
Wisdom may see fit to prove you with,
my dearly beloved +++_______+++, my mind has often been,
and continues to be turned to the Lord on your behalf; and sometimes,
when I am ready to petition for you,
that the present occasion of uneasiness to your mind may be removed,
I have felt my natural wish for your temporal enjoyment yield itself to the Divine will;
for I believe you to be the peculiar care of your Heavenly Father,
who "`chastens every child He loves,
and scourges every one whom He receives;`" therefore be not dismayed if He "`refines you,
but not with silver;`" if He chooses you in the furnace,
even trying you as gold is tried, that you may be holiness to Him, the Lord.

Look to your dear Redeemer in all that is humiliating,
and remember that His visage was said to be "`marred more than any man`'s,
and His countenance than the sons of men;`" and may He bless, preserve, and sanctify you!

[.letter-heading]
To a Daughter on Leaving School.

[.signed-section-context-open]
1824+++.+++

[.salutation]
My Dear Child,

Having some experience in the path which now opens to you, I wish, if possible,
to be instrumental in affording you instruction and
encouragement in your future steps through life.
Take, therefore, the affectionate counsel of a tender mother.

Place the fear of God continually before you; have reference to Him in all things.
He has not only given you a being, but endowed you with a good understanding,
and granted you many blessings: let it be the sincere language of your heart,
"`What shall I render unto the Lord for all His benefits?`"
so will He teach you His Divine law, and enable you to delight therein.
Thus will you possess religion; real, vital Christianity.
It is the greatest of all treasures; befriends the godly through this world,
and leads them to a better.

What are we without religion, even in our best state?
We know not how to estimate our existence, nor any of the blessings offered;
how then can we truly enjoy them?
In distress, in sickness,
in the dark and gloomy seasons which will overtake us sometimes,
in the course of our journey, what have we to flee to for safety,
if unacquainted with the Name which is the power of God?
Therefore, my dear child, "`get wisdom;`" "`forsake her not`"--"`the fear of the Lord,
that is wisdom.`"

Never give way to a fretful disposition.
To repine at the crosses and difficulties attendant on our probationary state,
betrays a little mind, and lack of resignation to what Heaven permits; besides,
it renders things trying in themselves, still more bitter; therefore,
whenever tempted with peevishness, seek, with all your might, to be quiet,
and wait upon the Lord, who will bring you near to Himself, and convince you,
that with Him who is light, there is no disquiet; and so He will grant you peace.
Your enemies are your own natural evil propensities: to overcome these in the Lord,
is a most glorious victory.
Your dear Savior is able and willing to grant you this victory with holy triumph.

Give no place to an envious disposition; it would corrode your mind,
and prevent the incomes of heavenly love.
The sweet and the bitter are more equally dispensed than man perceives.
We cannot of ourselves promote our happiness, but, by watching against all wrong things,
we may become strong in the Lord, and in the power of His might,
to avoid all that would render us the authors of our own misery.
Be assured, my precious child, that if there is not tranquillity in your own breast,
from allowing the all-regulating principle to operate there,
you never will find true felicity in any situation which may fall to your lot;
and while a kind Providence may permit you to be surrounded by temporal good,
you may be without capacity for enjoying His bounty.
Be wise, therefore, and submit early to the humbling power of truth,
that it may be well with you in time and in eternity,
which is the desire and prayer of your affectionate mother.

And now, with respect to domestic economy, let me say,
for your future comfort--do everything in its season: although it may seem very often,
at the moment, as if this method was inconvenient and troublesome,
you will find your account in it.
You will hereby save much of your precious time, and avoid confusion and hurry.
Make suitable arrangements, and be sure to observe them.
Have few servants; treat them kindly,
but give not up your own judgment to gratify their will,
lest you lose that government which is essential to the comfort of a family.
Be industrious, but be not in the habit of doing that yourself,
which properly belongs to the servants; for this only renders them negligent.
Be sure to manage everything with frugality and prudence;
you will have the more to spare for the needy.
Look well to your household in all things.
Let your countenance be as sunshine to your family, through the calmness of your temper.

Be not over anxious in trouble, but endeavor to leave all to the Lord,
in doing according to the best of your capacity;
and thus let your whole life bring glory to Him who is worthy of all glory, honor,
and dominion, forever and ever.
Amen.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Chelmsford, First Month 4th, 1824.

It is one of our greatest comforts in our passage through life,
to have that intellectual communion which is the product of true friendship,
such as I trust ours is; having, for its basis,
that love which none of the vicissitudes of a mutable world can destroy, and which,
I trust, strengthens with an increase of years,
while these do not fail to bring with them new trials.
No doubt you can acknowledge to fresh difficulties within the five years of our separation,
which your mind had not anticipated, and so can I;
but if all these things tend to whiten our garments,
and render us more fit to walk with the Lamb immaculate, we may even rejoice therein,
and give thanks.
You will say, that if we could believe this was the case,
it would be cause of rejoicing indeed.
I admit that there are times of great darkness in
the providence of the Almighty toward His poor creatures,
wherein we seem to be abandoned from good,
and even as though His mercies were "`clean gone forever,`"
yet even then it behooves us to exercise faith and patience,
whereby we are brought into a condition of mind to hope against hope,
and eventually to be glad in all these sufferings;
and if the weakness of the poor frame be such,
that we fear it incapacitates for heavenly mindedness, I believe that our upright,
though feeble endeavor, to draw nigh to the fulness of strength,
is an acceptable offering, and will not go without its reward; for "`He knows our frame;
He remembers that we are dust.`"
What a consolation, that thus we have the holy compassion of the Highest,
whose regard is unto the lowly; so do not be too much cast down, my loved friend,
my sister, for I humbly trust you are one of these lowly, and that,
seeing the best life has been preserved hitherto, the command will still go forth,
in all your strippings and provings, "`Touch not the life.`"
Many times does my mind commend you unto Him who
has condescended to be with you in six troubles,
who surely yet waits to be your sufficiency through all.

We are at times sensible, through the unmerited kindness of the Great Shepherd,
that our feet are still guided in the way of peace.
My dear companion has, at times, been enlarged in the heavenly anointing, in this place.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Fourth Month 5th, 1824.

The meetings, both in Dublin and here, have been times of very deep digging;
the spring of life lies low, and that of the ministry in unison with it;
but through a great deal of labour, the power made its own way, even into some dominion,
in each meeting; and in that of First day morning here, it was over all,
to the praise of the great and ever adorable Name: many felt it,
and worshipped the Lord in the blessed sense hereof.
Several friends have said to me,
speaking of the things that have happened here since our residence in England,
they were previously set forth with great clearness; one said,
"`as plain as if they had been left in written characters on the gallery.`"

At Coalbrook Dale we were detained from fifth day night until second day morning,
finding a stop in our minds, after having seen Friends together on sixth day,
even after preparing to leave the place.
It was much against the natural will and wisdom, to give up to be there on First day,
but I know too well my own short-sightedness, to reason away my sense of duty;
so besides meeting again with Friends, we had a large public meeting,
and I think I never was quite so near sitting down
without proceeding with what was before me,
in any meeting where this was not really the case, when suddenly the power arose,
and a very favored time it proved,
the people`'s minds being at length awakened to a sense of the truth;
but the poor frame felt the effects of this hard battle,
for it was immediately after this that I had the first attack of spasms.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dublin, Fifth Month 1st, 1824.

Your truly kind and interesting lines met me here,
and would have been noticed in this way before now, had not my mind been much conflicted,
respecting whether to give up attending the Yearly Meeting in London or not;
having felt considerable exercise and concern about visiting families in Clonmel,
and seeing Friends in Cork.
This latter prospect is likely to be pursued,
it appearing to be in the way of our feeling clear of Ireland;
and you know how very awful it would be to me to cross the water,
and apprehend that anything here was left undone.

The Yearly Meeting here is now got through,
except that we expect tomorrow the meetings for worship will be very large,
as being the last day of Friends meeting together,
and many of other societies attend at such times.
I do not know whether I may be permitted to get out or not, having taken a heavy cold,
which affects my lungs, and has nearly deprived me of my voice.

Our minds are much affected in sympathy with the state of our Society in this land,
for although there are a few up and down, who feel the weight of things,
we think that fathers and mothers are greatly lacking;
the number being lessened within a few years,
and the dear young people without many examples to look to.
It is, however, a day of powerful call, and of tender visitation,
which evinces that yet this religious Society is not forsaken;
and the meetings have closed very solemnly in this general assembly.
The Quarterly Meeting held in Clonmel, for the province of Munster,
was also a memorable time in the conclusive sitting.
Ah! poor Clonmel! "`How has the Lord covered the daughter of Zion
with a cloud in His anger,`" may indeed apply to that meeting;
and yet there is, as it were, a very small remnant, who sigh and who cry,
to whose supplications I believe the gracious ear is bowed, and who, I hope,
will yet be a blessing there.

_Second Day 3rd._--Yesterday was a memorable day to me, and perhaps to some others.
I was very poorly in the morning, and my voice far from clear;
the soreness and tightness of the chest considerable; but wishing to get to meeting,
I ventured, and to my utter astonishment, found my voice as clear as usual,
and no pain in speaking for a very long time to a large crowded audience;
the power of truth rising higher and higher,
until the dominion thereof was generally felt;
and although I was on the bed most of the time between the meetings,
and took but little nourishment, I was enabled to be at the second, and to declare,
with a strong voice, the doctrines of truth again very copiously;
the meetinghouse being greatly crowded, and many not of our Society attending.
The meeting ended in thanksgiving and praise, after which I came to my lodging,
and again lay down, but was in a large company of Friends here after tea,
wherein supplication seemed called for, and was uttered audibly.
Thus, my dear friend, I have been prepared to say, "`This is the Lord`'s doing,
and marvelous in our eyes.`"
This day I keep house, being hoarse,
and fearing to inhale the air in an open carriage like ours,
or else we might have been on the road to Clonmel.
My chest is very sore, and in a state of irritation.

I think this Yearly Meeting has been much favored on the whole.
Notwithstanding the many things to obstruct the circulation of the Divine life,
it did make its way in most of our gatherings, to the humbling our minds,
and to the honor of the Great Name.

I feel much interested respecting that with you now approaching,
and desire that Friends may be sensible of the humbling power of truth among them,
and that true simplicity may be abode in.

Oh! how do I long that your beloved partner may be "`chosen,`" as well
as "`called,`" even as it relates to his own place in the Lord`'s Church.
Is it not almost time for the man of business to be left for the man of God?
I know that my dear friend, your husband, loves that which is unchangeably good,
and desires its prosperity,
but I want him to be more fully at liberty for the Lord`'s service.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Clonmel, Fifth Month 26th, 1824.

There are many precious children in this nation, whose hearts are sometimes tendered,
but how applicable is the language, "`The daughter of my people is become cruel,
like the ostriches in the wilderness;`" and how many young men there are,
who are strangers and aliens to the commonwealth of Israel: some of these,
husbands and fathers, who acquaint not themselves with the Shepherd`'s voice,
and who are stumbling upon the dark mountains.
But our painful feelings are not without an accompanying
hope that it is a time of renewed visitation to many;
and sometimes, in meetings and families, truth has reigned triumphantly,
to the praise of the great and adorable Name of the long-suffering Creator, who,
while He shows the house of Jacob his sins, and Israel his transgressions,
is calling out of everything that stands opposed to His blessed kingdom of righteousness,
peace, and joy.

My sense is, that if there be not a turning to the Lord with full purpose of heart,
the prophets, the true prophets, will be dumb, and not able to speak,
and that because of the people continuing to join themselves unto idols;
and the Lord will yet make the remnant of Jacob as a dew among many people,
and a remnant it will indeed be;
and the Lord will more and more send forth His light and His truth in this island,
so that those who sit in darkness shall see a great light,
and they who are in the region and shadow of death will behold the springing up of light;
and, in their believing in the light, shall they see more light,
and take the places of the once highly favored and powerfully visited ones;
and the Lord will yet be glorified in Ireland.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, no date, probably 1824.

Indeed, my dear friend, I do remember you before the Most High in my prayers,
and I remember yours too,
notwithstanding the need I have myself of the prayers of those
who desire well for that cause which I so publicly profess to advocate;
for truly there often seems occasion to ask that it may not be said,
"`a standard bearer faints,`" even with reference to your poor correspondent;
but it is encouraging to recollect that even a great
and deeply experienced apostle of Jesus said,
"`lest by any means, when I have preached to others,
I myself should become a castaway;`" which shows that he had to combat
with temptation at that advanced period of the christian life:
shall I then (far behind him) expect to be exempt from besetment,
or a humiliating sense of frailty?
Let me rather cleave to the same Power which was his sufficiency,
and that of all the children of God in every age.

So you got on nicely the day of the marriage.
We spoke of your company many times in the course of that forenoon.
I am comforted with your account of the wedding altogether.
I think we often find a solemnity on the occasion of marriage,
as a sanction on high to the ordinance, seeing it is of Divine origin.
I wish that these young Friends taking each other in marriage,
may be a time of solemn covenant to them both, with the Bridegroom of souls;
and that their desires may be circumscribed by the
same spirit which influenced Jacob to ask,
not for the great things of this world,
but that the Divine presence might be with him in the way that he took,
which evinced his concern to be found in the right way; and so he was blessed,
and made a blessing in his day.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Sixth Day, 1824.

I must send you a line, both to acknowledge your sweet letter with the grapes,
and also to let you know that our dear boy is going on as well as we could expect.
He desired I would give his love to you,
and express his obligation for your kindness to him: he enjoyed the grapes very much.

I remember that the blessed Master said, "`Why are you so fearful?
How is it that you have no faith?`"
Oh! may we not cease to call upon Him, and patiently wait for His arising,
when there shall yet be a calm.
He has often brought my soul out of adversity, and given me to rejoice in His mercy,
and be glad in His salvation;
and shall I not even again praise Him as the health of my countenance, and my God?

_First Day._--May the dew of Heaven abundantly rest upon your spirits,
and those of your dear children;
that it may be witnessed as far surpassing all the fatness of the earth,
and render you fruitful unto His praise, who created us for a great and glorious purpose,
even that we should give unto Him glory and strength;
the glory due to His name in this life, and reign with Him in joy ineffable,
in the world of spirits.
So dear friends farewell.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, 1824.

[.salutation]
My Dear Friend,

Well, we are come home at last (from Ireland) but we were
perhaps never more sensible of the need of best guidance,
than relative to our return, as to the right time and way;
indeed we were detained much longer than, at one time, was expected,
but not in the pursuit of temporal gratification,
for of this we partook of very little during our absence;
it was in religious engagements, and often in sore travail of spirit,
that our time was filled up; nevertheless we can acknowledge,
that to be at Divine disposal is our interest as well as duty;
and although this excursion has cost us considerable every way,
we find the retrospect produce a quiet which is worth obtaining at its own price.

I suppose your family circle is now complete.
This is pleasant,
especially when we see the design of a temporary separation answered in a good degree.
My heart`'s desire is for you, that, above all things,
you may seek to be conformable to the Divine will;
for it is in pursuit of this knowledge of the power of God that we are most truly blessed,
and made a blessing; otherwise we may make researches in vain for true felicity;
grasping as at phantoms, and pursuing shadows.

I long to know how it is with our Bury friends in general,
and what sort of meetings you have;
whether or not the heart-tendering influence of truth is much felt among you.
I hear M. F., senior, is very ill, which awakens tender emotions in my heart,
both on her own account, and that of her sweet, amiable daughter:
the feelings of the latter must be poignant in the threatening separation.

You will please give my love to all our friends around you,
and be assured I still love you so well, that I can in truth subscribe myself

[.signed-section-closing]
Your friend, in undiminished regard,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Seventh Month 13th, 1824.

And now for something about poor Ireland.
I certainly cannot say I saw that improvement which I looked for among the peasantry:
they and their habitations looked as wretched as ever.

With respect to Friends, I thought the Yearly Meeting, though much favored,
upon the whole, with the extendings of Divine love, which is all-inviting,
nevertheless exhibited much cause of mourning, even beyond what I feared.
Clonmel was a suffering place to us, in visiting the immortal seed, and so was Waterford.
We found less to press us down in Cork, although it is a very large meeting,
and there is no minister belonging to it now, nor any elder among the men:
the living power of truth had the ascendancy in both
the meetings we attended in that place;
and indeed, in each place where we visited, it triumphed at times;
so that it was a season of renewed visitation to many, Garryroan not excepted,
where the word of the Lord was like the lightning from the east,
which illuminates and breaks through all obstruction,
to the exaltation of the Great Name.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Chelmsford, Eighth Month 1st, 1824.

We may be restrained from expressing our sympathy, even when it is strongly called forth;
and I am aware that Best Wisdom sometimes permits that outward demonstration
of our fellow feeling should be much hidden from each other.
How often is my mind brought into travail for your meeting in dear Clonmel!
The retrospect of our late visit is peaceful, nor would I, as an individual,
have avoided the suffering and labour for any temporal advantage
that might have been gained by staying at home,
although there were seasons when I seemed pressed almost beyond strength,
and out of measure; and I really thought, that merely as it regarded myself,
I could have been willing, in the Divine mind,
to have laid down my natural life for the sake of Ireland,
could it even in degree promote the gracious purposes of the Almighty,
with respect to many in that nation; for great and glorious indeed are these purposes.

What a pity that the lack of obedience on the part of those powerfully called,
should prevent their being chosen; yet is this mournfully and conspicuously the case;
and I often fear it will still be so, because I see the hindering things still prevail,
and many are overcome of evil, instead of overcoming evil with good.

The cup of life is mingled with the bitter, as well as the sweet; and were it not so,
we should be ready to forget that this is not the place of our rest,
that we are but pilgrims and strangers here below,
and ought to be diligent in seeking another and a better country of uninterrupted bliss,
where joy unspeakable and full of glory is the eternal portion of those who,
"`having come through much tribulation,
have washed their garments and made them white in the blood of the Lamb.`"
Oh! animating consideration!
Is not this worth a world of trials and a fight of afflictions to obtain?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Ninth Month, 1824.

[.salutation]
My Dear Friend,

The Quarterly Meeting here being now over,
it seems almost time for me to acknowledge your kind letter,
inviting us to attend that of Suffolk, to be held at Bury.
Were we influenced by our affectionate feelings alone,
they would lead us to sit down once more among you,
but circumstanced as we are at present, there seems a propriety in our staying at home,
unless prompted to leave it by a sense of religious duty.
Nevertheless, my dear, kind friend,
be assured of our interest in the welfare of those among whom we
have so often experienced the overshadowing of Divine love,
and for whom, in our measure, we continue to travail;
desiring that the purity and blessedness of the immutable truth
may take the place of all that stands opposed to its Divine nature.
This large Quarterly Meeting has been a time of great excitement to my mind,
so that I feel to need a little quiet.
We have, nevertheless,
to be thankful for the renewed mercies extended in a collective sense,
for I think we may say that the meetings yesterday closed under a precious
sense of the goodness and power of our blessed Master.

[.signed-section-closing]
With love to you and yours, I remain, your affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, probably 1824.

[.salutation]
Dear Friend,

Let me just say that I do not forget you,
and that my desire is for your advancement and establishment in Divine grace,
seeing that is not like this mutable world, but ever enduring in its nature,
and soul-satisfying.
Now, if we come to a holy settlement in the truth,
it must be by obedience keeping pace with knowledge,
for we cannot of ourselves choose the time for offering
the sacrifice of the natural will,
in those things which may be pleasing to the flesh,
any more than Saul could meet Divine acceptance by
sparing the best of the sheep and the oxen,
to sacrifice in Gilgal, instead of where and when the Lord commanded him;
so see that you be faithful in whatever may be manifested to you in the light of Christ,
that in this light you may come to see more light,
and that your example may shine forth to the bringing others to glorify
the Name of Him who is worthy to be honored with all we have and are.

We have had many trying circumstances since I saw you, dear +++_______+++,
but my faith is not shaken with respect to our coming
to this place in the will of our Great Master;
and it is a mercy to be enabled to rejoice in His
salvation when outward things look gloomy,
and to know that He makes the feet like hinds`' feet, to run the ways of His requirings.

[.signed-section-closing]
I remain affectionately, your sincere friend,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
1824.

Dear and precious child, what a favor it is to be, as it were, singled out,
as one peculiarly tried and sifted, that so,
the precious being separated entirely from that which
will not endure the fire or the sieve,
the Lord`'s own works may abundantly praise Him,
and the soul be enlarged in capacity for living joy, in proportion to its sufferings.
How often does my mind desire for you the meekness of Divine wisdom,
in every varied feeling, that, enduring hardness as a good soldier of Jesus Christ,
you may become increasingly valiant for His Name;
not that I would have any of us suppose,
that because we have been brought through fire or water, we therefore know anything,
save by the fresh unfoldings of truth; but if there be a continuing in Christ,
then is there also a waxing stronger and stronger in His Name, unto His own glory,
who is all in all.

Somehow, in thinking of you, a few words of James Nayler`'s occurred to my remembrance.
I refer you to Sewel`'s History,
where you may find him speaking to this effect:--"`There is a spirit that I feel,
that delights to endure all things, in hope to enjoy its own in the end.
It sees to the end of all temptations; its crown is meekness;
its life is everlasting love unfeigned;
it keeps its kingdom by lowliness of mind in God alone;
it can rejoice though none else regard it, or own its life.`"
Please to take notice, that when I thought of these things,
I had not recollected reading the passage for years.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Tenth Month 5th, 1824.

We are now about going out a little to visit some
of the meetings constituting this Quarterly Meeting.
There is much of a dead calm which overspreads our meetings,
and which sometimes the power of truth rises superior to,
while at other seasons it continues throughout,
to the great grief of the minds of those who are diligent in labour.
Oh for some old fashioned Friends`' meetings!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eleventh Month 11th, 1824.

+++[+++After alluding to illness in her family]--Thus it
is permitted that we should be tossed with tempest,
but I hope against hope, for I can appeal to the Searcher of hearts,
that we have desired to do His will (even perfectly) here on earth,
as it is done in heaven, and have counted nothing too near to part with,
to follow the leadings of His Holy Spirit;
so that surely He will not now utterly forsake us,
though "`He makes the clouds His chariot, and walks upon the wings of the wind.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, First Month 16th, 1825.

Having been favored to get through the family visit in this meeting,
I seem more at liberty to talk a little in this way,
than while under the weight of that important engagement.

I was able to be at meeting today,
which proved to be the winding up time after the visit to individuals.
I rather looked for it this day week, but no way opened.
Today the key of David was known to unlock the gates, which,
without Him who alone has this key, must remain insuperably closed.

I do not think, my dear friend, that our being here at present,
can be any other than in the providence of the Most High,
for notwithstanding the many trials with which we have been assailed,
there seems a settled persuasion, ever since we came,
that our steps were not directed to this spot by our own understanding; besides,
our service for the Lord lies much this way.
How long it may continue to be the will of our Heavenly
Father to permit the same feelings to attend us,
I trust we desire not to know, for it ill becomes us to take thought for the morrow.
What should we do but for the humble hope that the Father of mercies
takes cognizance of His poor creatures every moment,
and directs all the occurrences to which we are subject, for our good?

All our love awaits you; mine especially to your dear partner,
for whom I continue to travail that he may be enabled to have his
attention primarily turned to improving his Lord`'s money;
that the answer of "`well done`" may be joyfully received in its fulness at last,
as well as in measure now.
Do salute him for me in the Lord.

[.letter-heading]
To Martha King.

[.signed-section-context-open]
Colchester, Second Month, 1825.

I assure you, my dear friend, it is no light thing to be a member of Chelmsford Meeting,
which is large and interesting: there are, indeed, burdens to bear,
something like standing in Jordan with the weight of the ark upon the shoulders,
until the people pass over.
Our late visit to the families was attended with relief:
the Lord revealed His power and spirit from time to time,
so that the authority and love of the Gospel made its own way,
and was generally in some degree of dominion;
and some of the succeeding meetings have been highly favored,
the contriting influence of truth spreading and prevailing over all.
We have also visited many other meetings in this county,
in all which I think we may say Ancient Goodness was near,
so that the ministry of the word flowed to the people like a living stream.
It would now seem as if I had written fine things with respect to our getting on, but oh!
I often feel left to a sense of my own nothingness,
in a manner more humiliating and depressing than I can tell you.
It is the Lord`'s power that I wish to magnify, and if I glory, it is in my infirmities.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Third Month 7th, 1825.

I am persuaded you have not been without your share of sorrow since we parted,
but I trust the language of the Great Master to His disciples formerly,
may apply--"`You shall be sorrowful,
but your sorrow shall be turned into joy;`" "`and your joy no man takes from you.`"
So it is worth being a partaker of the sufferings of Christ,
to have this joy that He gives, in its full fruition, to all eternity;
but not only in the end of time is it the portion of the righteous,
a foretaste is given now, and is as a brook by the way, replenishing the weary traveller,
and giving fresh vigour to run the race set before us.
Say not, my dear sister, that this brook is closed to you through your unworthiness,
but remember that even the seeking, panting soul,
is permitted to feel something like the tongue failing for thirst, yet,
in the moment of extremity, the promise comes to be fulfilled,
"`I the Lord will hear them, I the God of Israel will not forsake them;
I will open rivers in high places, and fountains in the midst of the valleys;
I will make the wilderness a pool of water, and the dry land springs of water.`"
Surely He who sees the integrity of your heart,
will give you to be one of those who inherit His promises;
therefore lift up your head in hope,
and doubt not but the very feeble endeavors of your
mind are accepted by our gracious Creator.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Fourth Month 8th, 1825.

I can remember nervous suffering so severe as is by no means to be described:
I tried hard to lean on the bosom of the Lord Jesus
(who was for our sakes a man of sorrows once,
in a body of flesh) and, through His mercy, I did obtain a little quiet,
but how transient, how momentary was the rest!
Ah! it was permitted to be interrupted by that part in which our poor souls groan,
being in bondage, and longing to be delivered; "`not for that we would be unclothed,
but clothed upon.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Fourth Month 24th, 1825.

Your little note is sweet to me; it breathes unabated love and true friendship.
I hope you, my dear friend, may,
in a few months (may I not say weeks?) have to be thankful
for another precious gift added to those already sent,
and for your health being mercifully preserved.
I wish this joy for you and your dear partner (in submission to
the Divine will) even as I should for my own near relatives.
It is said in Scripture that children are "`a heritage of the Lord;`"
so then He sends them that we may be enriched hereby;
and when we consider that they are beings designed for eternal glory, should we not,
even in this view of the subject, account it an honor to be entrusted with them,
besides the use which they may be of in their passage through time,
both in civil and religious life?
All these things ought to cheer you, my dear friend, who have so many blessings, and who,
I know, desire to number them with reverent humility before Him from whom all good comes.

There is a Bible Meeting now sitting in Chelmsford:
it will be well if both speakers and hearers all mind what that good book tells them,
and then they will not be of those who say, "`Lord, Lord, open to us,
for we have done mighty works in your name,`" but who,
for lack of conformity to the Divine mind, are not acknowledged, after all,
by the Lord of life and glory.
I do indeed, my dear friend,
feel deeply interested in the happiness of your dear +++_______+++,
which happiness we know depends upon an obedient
attention to the secret call of the Heavenly Father,
which says, "`My son, give me your heart.`"
We who are parents are often made sensible that this obedience
is an act which we can in no way perform for our dear children,
but let us pour forth our prayers that the Almighty may
be pleased to draw them with the strong cords of His love,
that they may feel powerful inducements to be His, by unreserved dedication.
I feel sometimes a little encouraged to hope that our intercession is acceptable,
and that, in consequence,
the Father of mercies does visit our offspring by His special grace.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stockwell, Fifth Month 21st, 1825.

In the first sitting of the Yearly Meeting,
dear Martha Smith was enabled to supplicate that the Divine presence would be with us:
her offering was evidently the means of bringing solemnity over the meeting,
and I really think it continued to the close of that sitting,
which you will join me in acknowledging was a good beginning to the Yearly Meeting;
and I believe that many do feel this to be an uncommonly still time, and much favored.

Yesterday I was at Devonshire House.
The meeting held about three hours, and was a highly favored season.
Many not of our Society attended:
the doctrines of the Gospel were clearly and largely opened,
and truth did appear to be over all.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Chelmsford, Sixth Month 1st, 1825.

The Yearly Meeting was, on the whole, a time of much favor,
even to thanksgiving and praise.
I was often put in mind, from what I felt, of the ancient, compassionate,
and moving language of the Heavenly Father,
respecting His people formerly--"`Is Ephraim my dear son?
Is he a pleasant child?
for since I spoke against him I do earnestly remember him still;
therefore my bowels are troubled for him; I will surely have mercy upon him,
says the Lord.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Same date.

How often is it the case, that in endeavoring to follow the leadings of truth,
and to do the Divine will, we find the verity of the declaration,
"`You have need of patience;`" may we be enabled to keep the word of patience still,
for I believe this to be the way for us to be kept in the hour of temptation,
which does come, and must come, even to try all that dwell upon the face of the earth.
There were two visits to the Men`'s Meeting (during the Yearly Meeting) and,
what is singular, I was present at each; for in the first instance, dear Martha Smith,
of Doncaster, proposed my going with her,
and the second was a visit that I had to pay to our brethren near their conclusion;
both tended to my relief, for my exercise was great,
and in the first I was witness to the overflowing
cup of dear M. S. in an extraordinary manner.
I want to say a little of this Friend.
She was about five years in a low state of mind,
which she described in the Select Meeting, as darkness blacker than that of midnight;
and said that the dragon`'s mouth was wide open to swallow her up,
so that no language could be found sufficiently appropriate
to set forth the distress she was in;
and that in a moment the light broke forth, dispelled all her gloom,
and she could sing Alleluia to the Lord God and the Lamb, her great and mighty Deliverer.
I have been with M. S. sometimes, out of meeting, while in London,
when she was also like a vessel that must have vent
to declare of the Lord`'s goodness and power,
and to invite all to partake thereof.
Strange as it might seem for me to go twice to visit our brethren,
especially as I was much opened and enlarged the first time,
I could not rest without making the attempt the second time;
and indeed it was quite a different thing from the first,
for it was speaking to those who had been witness to the
goodness of the Almighty during the Yearly Meeting,
and to some hundreds who were added to the number there when I went before.
Oh! it was a solemn time indeed:
there came such an awful silence over that large assembly,
and under this it separated--praised be the Lord!

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Sixth Month 5th, 1825.

I am comforted in knowing that Divine Providence has been pleased
to give you the continual feast which a contented mind affords,
and I hope you are favored often to feel His good presence to be near you,
who is your Heavenly Father, "`in whose presence is fulness of joy;
at whose right hand there are pleasures forevermore;`" not indeed
like the fading pleasures of this transitory world,
but ever enduring in their nature, and soul-satisfying.

I believe your tender mind has sometimes felt it to be so,
and that you are not without understanding, in some degree, of what I now write;
and I wish to encourage you to wait upon the Almighty,
to experience His goodness and power to be near you,
which will more than make up for all your trials, my dear child;
and so He will give you of His Holy Spirit,
still more and more to enable you to serve Him in your day; yes, if you seek Him,
He will dignify you, and make you as the "`King`'s daughter,
all glorious within;`" and you will have to acknowledge that all the dealings
of the Most High with His children are in wisdom and mercy;
and in learning to put your trust in Him,
you will know that everlasting strength and all-sufficiency are with Him, the Lord.
