== Chapter 14. Letters from 1830--1833

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sandford Place, Seventh Month 18th, 1830.

Last evening the parcel arrived with the feast of letters, we each receiving one.
My dear S.`'s to me is grateful to my heart.
What occasion of thankfulness there is, in the renewed mercies of our Heavenly Father!
He has evidenced that He heard our prayers,
and has led us hitherto by His own Divine hand; so that I hope we can all say,
"`It is better to trust in the Lord, than to put confidence in princes.`"

[.letter-heading]
To the Same.

[.signed-section-context-open]
Sandford Place, Eighth Month 21st, 1830.

I wish you not to avoid any right sense of just reproof from the inward monitor,
and that I may be able more fully to understand your condition, and, in the Divine will,
be instrumental to aid your mind.
I know, my dear, that,
in order to our becoming decidedly such characters
as our Almighty Father would have us to be,
we must pass through trying dispensations; and the best thing to be proposed,
under feelings of this nature, is patience; which, when truly exercised,
not only works experience, but bears up the soul, when tossed as with tempest,
and not comforted.

I have no apprehension that you are utterly forsaken of the great and good Shepherd,
who looks after the wandering lambs, and gathers them with the crook of His judgments,
so that they come to love the fold of safety,
although it confines them from many outgoings which
afford a momentary gratification to the natural mind.
I would have you often commit yourselves into the hands of your Heavenly Father.
If you have _words,_ use them: if not, seek them not.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Ninth Month 2nd, 1830.

We have indeed a merciful High Priest, who pities our infirmities.
A minister of the Gospel has trials to pass through, peculiar to that calling,
and which are also humiliating in no common degree; but,
so far as my experience has come, I would by no means shrink from such feelings,
for they have a powerful tendency to prepare for
intimate communion with Him who was reviled,
who was spit upon,
and whose blessed words were deemed the words of one possessed with a demon!
Further--I am abundantly persuaded that increased qualification
is eventually known for exalting that Great Name which was blasphemed,
and continues to be so at this day.
I write not this with any particular allusion,
for we are much ignorant of your concerns of late.
When dear sister +++_______+++ so kindly wrote to me about
the mournful bereavement in their family,
the task was so great to her, that she entered into no other subject.
Ah! my dear,
how deeply affecting is the dissolving of these ties--the most
tender and endearing earthly relationship severed as in a moment,
by the scythe of death!
How does it invite us to live loose from every perishable object,
and to set our affections on things above; things ever-enduring and soul-satisfying,
in which kindred spirits, released from mortal shackles,
find all that was lacking here below, to give them consummate happiness;
every alloy being forever removed!
And ought we not to rejoice for those who are already entered into this perfect state?

We do not feel as if we had missed our way in coming here,
after all our conflicts on the occasion;
indeed I think both my beloved husband and myself have felt,
and continue to enjoy true quiet, many times, under our present humble roof; and this,
you know, is better than great riches; yes, it is possible to rejoice in the Lord,
and be glad in the God of our salvation, when temporal blessings are removed.

[.letter-heading]
To Robert Fayle.

[.signed-section-context-open]
Stoke Newington, Ninth Month 17th, 1830.

[.salutation]
My Dear Cousin,

Thinking as I do, of you for many weeks past, with affectionate interest,
I may as well tell you so.
Inscrutable Wisdom has seen fit singularly to prove you and your dear companion in life,
by permitting the interruption of that almost invaluable blessing--health,
and by removing from your parental charge, repeatedly,
the endeared objects of your tender, yet pleasing solicitude.
The Divine Parent saw fit to take these lovely children to Himself.
The Giver of every good gift has a right to dispose of His own;
and He knows when and how to deprive us of these beloved ones,
so as to profit the bereaved.
My heart has heaved the sigh of sympathy, and felt with you as a sister,
in contemplating these piercing strokes to our nature,
even while I have desired that you might be enabled to refer all to Him,
without whom a sparrow falls not to the ground, and who said,
"`You are of more value than many sparrows.`"
But who is it that our Heavenly Father chastens?
even those He loves, and "`scourges every son whom He receives.`"
That He has, in a precious degree, received you as His child, I have a comforting belief;
having accepted you in the Beloved; in Him who is our adorable Mediator and Redeemer;
and surely it is His gracious design to increase the preparation of your spirit,
for still more intimate union and communion with Himself; yes,
ultimately to present you faultless before the throne of His glory with exceeding joy;
joy very far exceeding all the painful conflicts of mind and body,
which tend to sanctify and fit the immortal spirit to live and reign in glory ineffable,
with Him who has washed you in His own blood;
to whom the purified spirit ascribes salvation forever and ever.
I salute you in more fellow-feeling and tender regard than I have ability to set forth.
My dear husband having written to your brother Thomas,
I shall not burden you with many messages of love, only to your wife, our cousin,
whom we do remember with yourself, as being in adversity;
but we are comforted in the belief that the Most High will
graciously evidence that He sees you in adversity,
and watches over your souls, to deliver in His own time.
Our love is to your dear children.
May Heavenly Goodness manifest His providence as being abundantly over them!

I sometimes view, with peculiar interest,
your valued present to me many years ago--a seal with the motto, "`__Fideli certa merces.__`"

Farewell, my dear relative and friend;
long known and increasingly beloved by your far distant, yet nearly sympathizing friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Third Month 27th, 1831.

I have been at meeting today.
It was an extraordinary meeting: the stream of gospel ministry flowed freely along,
and near access was felt in prayer.

He who has "`His way in the sea,`" whose footsteps are not seen,
has been my help in suffering.
I can say that I have risen at the midnight hour to supplicate His mercy,
and to beg that I might be kept by His power; that, for the sake of my beloved husband,
for the sake of our dear children, but above all, for the sake of the truth itself,
nothing might really prevail against me, to render me
as a broken bow.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Fourth Month 14th, 1831.

We have rejoiced in the tidings of your being enlarged in your ministerial gift,
and that the power of the Lord is with you.
I hope you, and your companion in the service at Waterford,
were much relieved by that act of faith and obedience.
Cousin T. Fayle must be much alive to his bereavement,
his dear and only brother being taken away;
but how must the afflicted widow feel this separating stroke!
Oh! it is very moving.
R+++.+++ is a general loss likewise.
He was one of the few active, consistent members of our Society there;
but who shall do other than give thanks on his behalf,
in the belief of his having become an inhabitant of the fairer city,
where "`none can say, I am sick;`" neither is there any more pain, nor tears;
but the full fruition of joy unspeakable, and full of glory?
Ah! my dear, if we do but come here at last,
what are the most trying and inscrutable dispensations we may pass through,
in fitting us for such eternal peace, ineffable delight?
As Job Scott said, "`lighter now than vanity,
except as they are clearly seen to have contributed
largely to the sanctification of the soul.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ipswich, Fifth Mouth, 1831.

The meeting is got through, and I am much relieved, feeling truly thankful;
for it has been all I could wish--a multitude of people,
and the power of truth rose higher and higher,
until it was in blessed and glorious dominion.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Stoke Newington, Sixth Month 4th, 1831

No doubt you frequently feel the infirmities attendant on advanced age;
this is part of the labour which, if rightly submitted to,
meets its reward in a world to come, "`where the weary are at rest.`"
Be of good cheer, my long-loved sister;
take the few remaining steps of your race with a
humble hope of eternal repose in a mansion of glory.
You have loved your God and Savior many years; in your measure travailed for Zion,
sincerely desiring the prosperity of this true Church, wherever found upon the earth;
and I trust the testimony will go forth concerning you,
in the day of righteous retribution, "`She has done what she could.`"

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sandford Place, Sixth Month 21st, 1831.

Oh! my loved children, I was often, in my early days, unrefreshed in spirit,
after having waited on the Lord of glory in the very best manner I was capable of,
during the time set apart for public worship;
but I can say that we do serve a good Pay-master; yes,
that it highly behooves us to be given up to Him in all things,
for He is from everlasting to everlasting, "`faithful and true.`"
I do not know why, but it seems with me to tell you, my precious children,
that the prayer of my heart has this day been, in a peculiar manner, "`Oh!
Lord, lead me in the _right_ way to the end: rather take away my natural life,
than that I should cease to be your hand-maiden; and I beseech You,
bless my children after me, and render them capable of your sacred impressions.`"
Now my dear +++_______+++,
do not think that this serious detail of my feelings is a prelude to my
being freed from the shackles of a mortal and probationary state of being.
I believe no such thing, but, in our separation, I pray for you;
and I have little doubt that the omnipotent Lord is watching over you for good.
You may and ought to adorn the doctrine of God our Savior,
even in your secluded situation, by your example among those where your lot is cast;
and this is what we wish for you, that your reward may be great.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Colchester, Tenth Month 2nd, 1831.

I have transacted the main business I came here about, and I did think myself,
that the aid of "`the Comforter,`" the Spirit of truth, helped to make things easy;
and indeed, I have throughout felt quite cheerful, and my physical powers renewed,
as well as the spiritual strength;
all of which I esteem as unmerited mercy to one of
the weakest of the Heavenly Father`'s family.
I am just come from meeting.
On sitting down with Friends, and inwardly gathering to the unfailing Source of good,
I found my mind nearly united to a few simple ones--meek
and lowly ones--and sat delighted in the sense of it,
although I knew that I was not among valiants or mighty men,
and also that many exceptions to those children of God were present; but oh!
I have been for once permitted, as it were,
to celebrate the Mighty Name with harp and pipe, even on the holy mountain.
I thought it like a song in the night,
for how is the day turned into the shadow of night, in this time, among us!
We were favored with another living meeting in the afternoon.
I thought of Job Scott`'s terms, "`blessed and glorious.`"

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Tenth Month 13th, 1831.

I address this to you, acquainting you with my getting home well,
and finding all here nicely.
I read "`Keith`" nearly all the way, while the daylight lasted.
He seems to be a very enlightened Christian,
and to have gone deeper in his inquiry after truth than the generality of writers.
His "`Evidence`" of the truth of the christian religion,
derived from the _literal_ fullfilment of the prophecies, is most interesting:
at the same time, in a solitary instance here and there,
he seems to lean more to the understanding of the _mere man,_ than quite suits me.

[.letter-heading]
To her Husband.

[.signed-section-context-open]
Lexden, Eleventh Month, 1831.

I am persuaded it is our _reasonable_ duty, even to suspend our worldly concerns,
to render to our all-beneficent Creator that which is as the first-fruits.

I often think we have great reason to be thankful
in being blessed with every earthly comfort,
and we ought to number our blessings.
Many are made sorrowful in grey hairs, by things that have not come nigh us.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, 1831.

The meeting at Tottenham on First day evening was much crowded,
Friends having taken pains to circulate the notice widely; and what is above all,
the Great and Eternal Fulness was graciously pleased to bless their labour and my exercise,
without which all would be fruitless.
Oh! it was a good meeting.
My spirit felt relief indeed, in opening the doctrines of the Gospel to the people,
largely, and with living, blessed authority.
Then a precious silence ensued: again, thanksgiving, praise, and prayer,
were offered up to the throne of God and the Lamb; after which,
and a solemn pause at last, the meeting closed.
My soul is encouraged to confide in Him who is the strength of His poor dependent ones,
and to ascribe unto Him all might, majesty, and renown; to lie low before Him,
and to wait for the fresh openings of His mind and will.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, Seventh Day Evening (probably 1831).

I need hardly tell you that I have thought of you continually,
and also of your dear brother.
The aspirations of my heart are to the Author of blessing on your behalf,
and _that_ very frequently.
Surely He will care for you, even as your Almighty Father.
Be encouraged to serve Him, the Lord, with a perfect heart, and with a willing mind.
Never be ashamed to confess the holy Redeemer in all His manifestations,
and faithfully follow His leadings.
None of us can do better than this,
nor can anything short of such dedication render us as happy as we may be,
even in the things of time.

I rather dread tomorrow, lest there should be anything out of joint as it were,
or the christian cause not exalted: but it is better not to anticipate,
but to be inward with the Lord, both now and then.

_First Day Afternoon._--The funeral today was attended with
more parade than suits my ideas of christian simplicity.
I had no active part to take, but I felt in silence, especially at the graveside,
a full assurance (as I believe) that the innocent
spirit was glorified through the blessed Redeemer.
I said in my heart, Oh! the silence of the grave! and yet I heard the songs of heaven;
I heard Alleluia to the Lord God and the Lamb; yes,
I heard praise from that very spirit which had, so early in life, taken wing,
and fled to the realms of eternal bliss.
Oh! my children, life is worth living, when it brings to this consummation of hope,
and centres in the eternal reality of happiness.

Much do I bear you on my heart; yes, before Him who is omnipotent and almighty.
You know that even this separation is that we may prove to the world,
that we love Christ before son and daughter.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Second Month 12th, 1832.

We are not young now; may we be more and more of those who are made wise unto salvation!
It is the converted, the humble, simple-hearted, who are thus favored.
How delightful to see those who have entered the last stage of life,
growing in the heavenly nature,
becoming increasingly prepared for an everlasting inheritance in the kingdom of glory!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Third Month 3rd, 1832.

Your precious letter, received this morning, has much contributed to our comfort.
We are truly glad to find that your dear mind was favored with the most enriching blessing--peace;
at least, that in some measure this was your portion; indeed I hoped it would be so,
when I bore you on my heart before our compassionate Father,
whose omniscience beholds the sincerity of your soul.
True, you have found yourself to be a frail, erring,
sinful mortal--where is the child of God who cannot confess to the same discovery,
and conclude that such a one is utterly unworthy of the
least of the mercies of a righteous and gracious Judge?
Some of these,
least willing to screen themselves from that light
which shows _all unrighteousness_ to be sin,
have so felt the terrors of the Lord,
as to become willing to persuade men to submit themselves under the cross of Christ.

I hope you will yet have to speak well of the Almighty Name,
for that He will give you grace and glory, and will not withhold any good thing from you;
no, nothing that is best for you; nothing that would prove a _real blessing._
Oh! it seems to me that you are taught of the Lord,
and will yet be taught of Him whose name is "`Wonderful, Counsellor, the Mighty God,
the Everlasting Father, and Prince of Peace.`"
Indeed I think I have the promise, that if you maintain your integrity,
and seek to love God entirely, great shall be your peace and comfort, even in this life.
Be patient, my dear +++_______+++, and endure the trial of your faith with noble fortitude;
having your eye singly to your Savior, who, in a body of flesh,
felt all the infirmities and sufferings of human nature,
that through His blood our sins might be purged,
and by His stripes all the wounds inflicted in any way upon us, might be healed.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Third Month 8th, 1832.

According to my engagement yesterday, I begin a letter to you this day.
After we saw you quite off,
we went to +++_______+++`'s. They were talking of the observation of the fast day impending,
and appeared undecided about closing the shop-doors;
saying that "`the thing should be seriously considered,`" etc.; but I replied,
that if we fully understood our religious principles, and embraced them,
it did not appear to me that we had the case before us as something new;
rather as that with which we were well acquainted,
and knew how to meet according to our christian profession;
and that I should have supposed, at his maturity of years,
he had come to a decision on such points.
For my part, I was of the old school, I said,
and did not now find that it was necessary for me to call in question the propriety
of the high standing our religious body had always taken in such matters;
being clearly convinced that this is not the _true fast._

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Third Month 16th^
footnote:[Ten years from this date, namely, Third Month 16th, 1842,
S+++.+++ G. entered on her everlasting rest.]
1832.

[.salutation]
My Dear +++_______+++,

This being the twenty-first anniversary of your coming into existence,
I feel particularly inclined to talk a little to you.
Early this morning I recollected the circumstance,
and have dwelt with peculiar delight on that happy morning,
when my infant was brought to my view as a boon from Heaven;
in some degree filling the chasm which the bereavement
of my sweet Joseph had made in my maternal feelings.

In proportion to the depths of sorrow, so are the heights of joy which affect our hearts.
I was glad, even beyond the usual pleasure of which the mind is capable,
on the occasion of receiving such a treasure, because I had, not many months before,
suffered all that a mother could endure, of tender and not inordinate grief,
in losing a lovely infant from my breast; snatched away by the unrelenting hand of death,
almost before I was able to realize my situation; but I have you, my child, still;
so at least I trust; and that you will be spared to the end of my pilgrimage.
May religion influence the good understanding of my precious +++_______+++,
and correct the defects of a heart that feels everything too keenly.
May she be altogether what her Heavenly Father designs she should be,
and thus have the truest enjoyment of this life, and everlasting riches, and honor,
and glory, in the world of spirits.
With dearest love,

[.signed-section-closing]
I remain your own tender mother,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Third Month 18th, 1832.

[.salutation]
My Dear Friend,

You did not, in your remarks at the Yearly Meeting, on the desirableness of silence,
minister discouragement to me: I am one with you,
in wishing that we might separate under the _immediate_ covering of the heavenly wing.
I _was,_ however, discouraged, and cramped in my exercise;
and thought I discovered in part where it arose.
It was in a quarter from which I have, for years,
been accustomed to find a damp to my exertions in pursuit of religious duty,
but I desire to leave it all to the Lord.

It seems to me to be a day of perplexity and of treading down;
a day of gloominess and of thick darkness;
a time wherein opinion takes the place of faith to an alarming degree;
which is manifest in the lack of unanimity respecting our testimonies,
and in the contrariety of practice, as relates to some of them in particular.
It is indeed a trying time many ways, and puts me in mind of that scripture,
"`If the foundations be destroyed, what can the righteous do?`"
but surely the Lord knows the way of the righteous,
and although He may permit these to be much tried for a season,
He will one day bring them forth as gold; yes, I believe that the remnant among us,
who keep fast hold of their integrity,
will yet appear in the same brightness that the sons of the morning did,
and show forth the praises of the Most High,
as was the case with Friends before the gold became dim, or the fine gold was changed.
May the simple-hearted therefore strengthen themselves in their God,
even in this evil day, though it may yet show itself to be still more an evil day,
and notwithstanding terrible things may be spoken in righteousness,
by the Judge of all the earth.

We hear that the cholera in London is lessening.
Should the visitation be comparatively slight, it is not for our deserts,
but for mercy`'s sake, and to evince that an offended God is "`slow to anger.`"
Trusting to your indulgence for my procrastination in writing,
and for the freedom now taken,

[.signed-section-closing]
I remain Your affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Fourth Month 9th, 1832.

I have been anxious about you on several accounts,
not knowing what company you might be introduced into, under your present circumstances,
nor how far you might be enabled to show _decidedly_ that
you were not ashamed of the meek and lowly Savior,
nor of _His words._
This latter testimony for the truth,
I have indeed frequently prayed that you might see the propriety
of bearing with true greatness and firmness of soul.
With earnest desires for your preservation and furtherance
in the path cast up for the redeemed,
I take my leave.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, Fourth Month 14th, 1832.

I think that First day is a day wherein we may be particularly
brought near to those we are bound to by religious,
as well as social ties,
inasmuch as it is a day especially set apart for retirement from temporal pursuits,
and when we wait much on the Lord.
Be assured that you and your brother are very present with your dear father and myself,
at all times.
Think of us tomorrow evening: a large meeting is appointed at Devonshire House.
The _two_ here have been much favored.
Many of our poor people attended both.
It was my wish, and, after the first, theirs too.

Though our allotments are distant outwardly, you are ever with me in mind.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Stoke Newington, Fifth Month 1st, 1832.

The meeting on First day was very large, and got through _well;_ truth making its own way,
until it rose into blessed dominion.
I hear there are many inquiries where the next is to be,
but I never mention a meeting until I cannot avoid doing so.
I got home very comfortable in mind and body, only a little fatigued;
and I am very thankful for being helped through these formidable engagements.

The meeting at Westminster was the most favored of any I have had,
so far as I am capable of judging.
There was great enlargement, and such relief to my poor, oppressed spirit,
as I had not known for a long time, either among Friends or others.

Oh! my soul magnifies the mercy, and wisdom, and power that is not of man,
but of the Lord our God!

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Stoke Newington, Fifth Month 3rd, 1832.

We are glad you engage your time and talents in things likely to benefit your fellow-men,
and bring glory to the great Creator;
and much hope you will have the leadings and assistance
of that Divine influence which can do all without us,
but nevertheless prompts our minds to useful acts,
and enables to labour in the cause of righteousness and truth;
that this may spring forth in all the earth, to the praise of the Great Name,
and to the happiness of mankind.

Yes, my dear +++_______+++,
your sensibilities are indeed strong and quick--more so than can promote your own ease;
but never mind; go on as well as you can, and you will yet be happy.

The principle of grace, with which we are endued, is all correcting; and,
as you grow in this, you will increase in wisdom,
and be formed for the glory and honor of your God;
and great will be your peace in a world of trouble and perplexity.
Farewell, my dear +++_______+++.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fifth Month 11th, 1832.

I hope, my dear +++_______+++,
you will avoid engaging in _too many_ benevolent plans or pursuits: it may be overdone,
and rather weaken than strengthen the best life in individuals;
and I think I have seen the gift of the holy anointing turned from its own channel,
by great devotedness to these things,
to the disqualification of some for advancing the cause
of truth in the way designed by infinite and unerring Wisdom.
At the same time I quite believe that your philanthropy
is regarded by the Judge of all the earth,
and the sincerity of your heart will no doubt meet its happy reward.

I do, my dear +++_______+++,
desire your encouragement in everything given you to do by the great Giver of all good,
and wish the work of your hands to prosper.

[.letter-heading]
To Mary Davis.

[.signed-section-context-open]
Stoke Newington, Fifth Month 23rd, 1832.

It is with feelings of peculiar sympathy that I take the pen to address you.
I want, if possible, to hand you "`a cup of cold water,
in the name of a disciple`" of our Lord.
I seem fully persuaded of your willingness to accept
of even such refreshment to your panting spirit,
should it be sent by never so poor a servant.
I still hope your faith will be so renewed as to enable
you to rise superior to depressing thoughts and feelings;
yes,
to "`mount up with wings as eagles,`" and to "`finish your course with
joy:`" then life will be found to have been worth toiling through,
and all its afflictions appear light in the balance,
because of "`the far more exceeding and eternal weight of glory`" "`which shall be revealed.`"
While inhabitants of these earthly, frail bodies, we often groan,
and feel that we are in bondage, because our infirmities are heavy upon us;
and I believe we sometimes know not how to discriminate
between their pressure and another kind of weight,
and think that we are suffering the displeasure of our Judge,
and that we shall not know Him as our Savior; while, at the same time,
He is sustaining the spirit by His invisible power.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Fifth Month 30th, 1832.

I hope, as you launch forth more fully,
as a vessel steered by the all-skillful hand of your Lord,
and freighted with the things of His heavenly kingdom,
you will find even your bodily health improve; your mind having to rejoice at times.

To some of us this Yearly Meeting has been a trying time, beyond what I can remember;
for the lowly life has, in my apprehension, been borne down by that which,
with a specious appearance, seems to me to be much devoid of substance.
I have once more been constrained to sound an alarm, and set forth our danger;
which some believe, and many set at nought.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Sixth Month 8th, 1832.

Feeling much for you in your tried state of mind, I want to tell you,
that in endeavoring to look to Him who knows our frame, and remembers that we are dust,
I have had renewedly to believe, that as you seek after patience in tribulation,
your peace will, by and by, be great indeed.

He who has shown you that vanity is inscribed on all earthly things, will,
in establishing your soul in godliness,
grant the living experience that it is profitable unto all things;
having the promise of the life that now is, and of that also which is to come.
Oh!
My dear +++_______+++, I well know what it is to be shut up in darkness, as in a low dungeon;
to be hedged about that one cannot make their escape, and to feel the chain heavy; but,
I say it again, be patient in tribulation, steadfast in hope,
and you cannot think how the Almighty Arm will be made bare for you, to bring you,
in due time, into a large place.

[.small-break]
'''

In Sarah R. Grubb`'s journal we read a beautiful verse, in which she thus writes:--

[verse]
____
When heaven seems brass, and earth, with iron bars,
Doth hold its cheering goodliness from thee,
Then with a calm, resigned mind, give up--
Freely surrender all thou callest thine.
No longer rest on Jordan`'s banks, but with
Stability step in, and learn to know
That stones there are, which for memorial serve;
Then bring them up from thence, as proofs where thou
Hast been, and therewith raise thine Ebenezer.
____

I have thought that those endowed with more than ordinary talents are peculiarly tried,
before they come to devote all to the Lord, the Giver of every good and perfect gift.
Then He is pleased to say, "`I have refined you, but not with silver.
I have chosen you in the furnace of affliction.`"

Ah! my dear +++_______+++, you are designed to be a golden vessel.

Be not dismayed; the Lord is with you, even when He hides His face.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Sixth Month 18th, 1832.

We had a very full meeting yesterday at Peckham, in the evening,
and a time of Divine life and favor it was,
to the humbling our hearts in the presence of the Most High.
The people were, I believe, nearly all of the upper class of community; and when,
at last, I bid them all farewell in our dear Savior, they bowed their heads,
and looked very serious.
Oh! these are truly weighty engagements,
and should be felt as such to _all_ who enter upon them;
but how must it be with such a one as I am?
for truly I find that in me, that is in my flesh, dwells no good thing.

All important and weighty as these concerns are,
they give some heavenly delight to the soul,
when one finds the minds of one`'s fellow-mortals
impressed with the solemn truths of the Gospel.
This Gospel leads down into great abasedness of the creature, and exalts the Creator,
the Redeemer, the Everlasting Father, the Prince of Peace.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Seventh Month 5th, 1832.

Yesterday we gave in to the Monthly Meeting the Minute, as expected.
The first meeting was remarkable; I had so much enlargement in the ministry,
and yet the congregation was small.
Your dear father uttered a few words kneeling, after we had returned the Minute,
and I had to follow in the same line.

I am glad you value [.book-title]#Job Scott`'s Journal.#
He was a great example of dedication, and knew well what it was to renounce his own will.
He suffered with his Divine Master,
and obtained a glorious crown that will never fade away.
We lack such among us now: there are very,
very few who hate their own life as this valiant soldier did,
who stood in the first rank of the Lamb`'s army in his day.
We are now reading [.book-title]#George Fox`'s Journal# again: your father enjoys it,
and I am gratified too, in reading it to him.

You may rest assured, that even for _your_ sakes, I am disposed to take care of myself.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Eighth Month 20th, 1832.

Ah! we had not been more than a very few days separated from our dear Newington friends,
before the sad tidings reached us,
of the awfully sudden removal of poor +++_______+++ from all he held dear in this world;
leaving his bereaved widow and near connections to mourn his loss to them.
My heart has indeed ached with sympathy, both by day and by night,
in looking toward the circle in which he moved, as a husband, a father, a son,
and a brother.
I have been tenderly touched with sorrow, and have dwelt upon the emphatic language,
"`All flesh is grass.`"
Your testimonial of the christian fortitude with which the afflicted widow bears this
more than common stroke from the hand that waits to sever the nearest ties of nature,
has afforded me some comfort.
May Almighty Kindness pour into the wounded spirit the healing balm of His heavenly love,
which,
while it renders the mind all passive and resigned
to the sovereign will of our Heavenly Father,
brings down the high places, and prepares the soul to worship, to praise,
and to give thanks as in "`Jerusalem, the quiet habitation;`" producing the language,
"`Just and true are all your ways, O King of saints.`"
My tender love is to her, to whom all things once owned by him she loved,
must seem to wear the garment of mourning.
Tell her to be encouraged to look to Him who takes judicial notice of all her sighs,
and the inexpressible feelings with which she views
the dear pledges of their mutual affection.
Tell her to pray that her Maker will be her husband--the Lord of hosts is His name.
Oh! may she also beg of Him to be a Father to her fatherless little ones.
He is a God hearing prayer.

My love is likewise particularly to our dear friends +++_______+++
and +++_______+++. I have thought much of them in this sore trial,
which I am persuaded they have largely shared with their sister;
and as none of these tribulations leave us as they find us, I tenderly desire for them,
that they may feel an increase of firmness, as to their standing on the sure Foundation,
the Rock of safety in the boisterous sea of life.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Eleventh Month 4th, 1832.

[.salutation]
My Beloved Friend,

It is long, very long, since you and I have communed in this way;
I trust it has not been so in mind.
As for me, my thoughts are frequently turned toward you with affectionate solicitude;
yes, more than merely affectionate feelings fill my heart,
in remembrance of you and of yours.

I should be glad to know how you are in bodily health, and if you wax strong in the Lord,
and in the power of His might; that so the soul`'s enemies may be vanquished,
even the most potent of them; which are also the enemies of truth, and of all real peace.
The world seems to gain much ascendancy in the present day among us, as a people,
both with parents and children; so that little room is left for the simplicity, purity,
and meekness of the Gospel of Christ; and we have few noble standard-bearers,
and few of our children promising, by their humble deportment,
to become valiant upon earth,
in the great and glorious cause of promoting the kingdom of the Redeemer among men.
Is it not so?
I wish I could take a more encouraging view of things immediately
relating to our Society than I am capable of doing,
when my mind is in an abstracted state; but fear takes hold upon me,
lest we should be assimilating more and more to spiritual Babylon, in too general a way.

Shall not we who are parents, endeavor to see, in the light which deceives not,
how it is in our own families, as well as in the Church?
and is it not for us to labour with our dear children,
to bring them to a just sense of the necessity of taking up their daily cross,
if they would have a crown of everlasting righteousness and joy; and if, indeed,
they would be owned by the Savior upon earth, as His people?
Oh! my dear friend, I often fear lest I should not say, in the loud language of example,
Follow me, as I follow Christ;
yet it is my earnest desire to bear about in this body the dying of the Lord Jesus,
that His blessed life may also be made manifest in my mortal flesh.
Nothing will do, after all our speculations, but a dying to self, and living that life,
of which an eminent Christian speaks, "`I live; yet not _I,_ but Christ lives in me.`"
If _we_ are without this knowledge of the great work of regeneration, it will,
nevertheless, manifest itself through others;
for the true Church must take the place of the false,
and all that appertains to "`Mystery, Babylon`" must fall, as certainly as God is true,
righteous, and just.

I know not how it is that I have allowed my pen to run on thus,
but my heart feels interested in those I have long loved,
that they may be found walking worthy of the high vocation wherewith we are called.
With love unfeigned,

[.signed-section-closing]
I am your sincerely attached friend,

[.signed-section-signature]
S+++.+++ Grubb.

[.letter-heading]
To Mary Davis.^
footnote:[Mary Davis died on the 12th of First Month, 1833]

[.signed-section-context-open]
Lexden, Eleventh Month 12th, 1832.

[.salutation]
My Long Beloved Sister,

I may say that you have been brought very near to my best feelings of late;
and when I remembered the many years which have been
measured out to you in a world of probation,
and how you have been enabled to maintain your integrity through all,
my heart has been made thankful to the Great Dispenser of every good; and in His love,
which I have felt flowing towards you, my spirit has said,
"`God speed;`" wishing that you may be enabled to descend the hill of life,
with firm reliance on Him who is the staff of old age, to His humble, dependent ones.
Of this description I fully believe you to be; and, when present with you in mind,
I have thought, and am sensible of some humble assurance,
that the state of a little child fit for the kingdom of heaven, applies to you,
my dear sister.
Do not, oh do not be afraid of the dark valley to be passed through,
as at the foot of that hill, down which you are taking some painful steps;
endeavor to look beyond all suffering, all darkness,
to those regions of joy and light where redeemed souls forever live to praise His name,
who has purchased for them eternal rest and peace.
But possibly you may be ready to say,
there is little or no ability to lift up your head
in the blessed hope of everlasting felicity;
even so, I cannot but believe that the preparation is going forward,
however imperceptibly, to rise superior to all depression, and wing your way to glory.
I long for those powers of expression which some possess, to describe to you, my sister,
the sweetness, the sense of the innocent life that accompanies my thoughts of you;
which makes me hope that the leaven of the pure, heavenly kingdom,
is rendering you more and more like itself; and I do commend you to Him who,
in His love and mercy, has paid for us poor, frail creatures,
a ransom which we could never purchase for ourselves;
the benefit whereof all do richly partake, who, like you, do love Him,
our Lord Jesus Christ, in sincerity; so, my dearly beloved friend and sister, farewell,
in your Savior and mine.
Your dear brother`'s near sympathy and affection is with you,
which he wishes you to be assured of.
We are all three in the last stage of life, and shall we regret that it is so?
True, we see that we have proved ourselves to be poor, erring mortals; but yet,
could we bring ourselves back to even middle age,
we do not know that there would be one defect less to blot out of the book of remembrance,
when the final settling day should arrive.

Should all be remitted and cleared off, it is mercy, mere mercy;
for which our immortal spirits will be prepared forever
to sing Halleluia to the Lord God and the Lamb.

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Twelfth Month 11th, 1832.

I sit down after a day of company to address you,
feeling assured that your mind is sometimes turned
toward your poor old uncle and aunt with affection,
and that therefore you will have no objection to receive
a little fresh testimonial of our regard for you,
and our other dear nieces.

I begged for a letter from you in mine to our mutual, endeared _friend,_ and near relative,
your aunt Davis.
Poor dear creature! she is, I suppose, about to land in a glorious eternity,
after being safely conducted over the sea of life,
even through some storms and difficulties, permitted her in common with others;
notwithstanding, to the transient observer,
she may have seemed to glide along more smoothly than many;
but every heart knows its own sorrows, and sorrows we must partake of,
in the nature of things, as it regards our present state.

I often think how I should like to sit half an hour with you; but do you not think,
that as members one of another in the Lord,
and even when there may not be any outward communion (no,
not in this way) we may nevertheless be helpful to each other; yes,
and _that_ when not aware of it ourselves?
Surely there is such a thing as being found in the precious oneness of the living body,
in our various outward allotments;
then are not these a strength and assistance one unto another,
through the sufficiency of Him who is the holy Head?
I sometimes hope I derive benefit from the members of the
Church militant who are even altogether unknown to me.

Ah! poor T. F.;
how inscrutable is his removal! and now our friend
G+++.+++ R. taken from his loved family and his usefulness.
It has been for many months, and still is a truly awful time: such a one as some of us,
who are far advanced in life, never saw before.

The noisome pestilence, how has it brought many to the grave,
and occasioned much affliction to survivors; while it has been most signally marked,
as sent by Him whose ways are past finding out.
One has been taken and another left, under circumstances exactly similar,
like "`two women grinding together,`" etc.
Some of those to whom the last messenger has come in the form of the dreadful cholera,
were no doubt prepared for the sudden and unlooked for summons;
while they were concerned to glorify their Creator and Judge "`with their
spirit and with their body,`" remembering they were not their own.
Others appear to have been the servants of sin to the last;
yet these all no doubt had their twelve hours allotted them,
wherein to do their day`'s work.
We will not sorrow for the first class as without hope; no,
let us rather give thanks that they are taken from the evil to come.
We may and ought to "`lay it to heart;`" yet with a reverent
acknowledgement that the Judge of all the earth does right.

Oh! my dear +++_______+++,
I think that the righteous are indeed taken from a day of overturning,
at least among ourselves as a people;
for it seems to me our departure from the true and ancient standard almost generally,
is becoming more and more apparent, from the foremost in rank down to the children.
Alas!
I do not recollect to have been so much of a mourner in all my life, with respect to us;
and will not the Most High visit for these things?
But enough;
there remains to us that which is immutable and safe to attend to and build upon;
and there are preserved those who have no other dependence,
and who will prove themselves truly wise in their choice and in their obedience,
when the sandy foundation will be discovered and shaken,
and all will give way that has been erected on it.
