== Chapter 16. Letters from 1834

[.letter-heading]
From Sarah Grubb To John Wilber

[.signed-section-context-open]
Lexden, near Colchester, 20th, of 1st mo., 1834.

[.salutation]
Mr Dear And Valued Friend,

The only letter I ever received from you bears date 8th mo., 22nd, 1833.
I have perused it repeatedly, and, I think, as often been comforted,
and my faith strengthened by what it conveys.
I know you must consider it an honor to suffer with
the lowly innocent life of your dear Lord,
which is now under peculiar (and with respect to our Society) novel persecution.
Was there ever a time among this people,
when the language of the lip of Truth became so applicable?--"`False
Christs and false prophets shall rise,
and shall show signs and wonders, to seduce, if it were possible,
even the elect;`" but may the little ones be strengthened and encouraged,
seeing that that which comes into obedience to the Truth is ever chosen of God;
and abiding in that which brings to the election, these shall never fall,
but are indeed kept by the power of Him who is mightier than all
that ever did or can oppose itself to his righteous government.
Oh! dear friend, it seems to me that this is indeed a sad time among us in old England.
It falls to my lot still to proclaim war, in the midst of a general cry of "`peace,
peace!`"

Did you hear anything of dear Ann Moore standing up after me in the Yearly Select Meeting?
When I had uttered a warning voice,
and declared that the jealousy of the Lord was kindled
against that spirit which had crept in among us,
to draw away from the ancient and invincible foundation, etc., Ann repeated the text:
"`Oh, sword of the Lord! when will you be quiet?
Put yourself up into your scabbard; rest and be still.
How can it be still?
For the Lord has given it a charge against Ashkelon, and against the sea-shore.
There has he appointed it.`"
This did not fail to produce an expression of disapprobation;
and poor Ann was counseled against siding with me,
or being influenced by us and Thomas Shillitoe;
but she was conscious that none of us had the inclination,
even if we possessed the ability,
to turn her eye from its close attention to the pointings of that unerring Guide,
by which she was brought among us in this land.
I hope this dear handmaiden of the Lord has written to you since her return home.
She is often deeply proved, and again she comes forth as gold from the furnace.

I wish we had more truly baptized living ministers;
we have copious and eloquent communications from our galleries,
and there is an effect produced on very large audiences that is very striking;
the attention seems riveted to the speaker, and to the subject-matter delivered;
and when the address is closed a solemn silence ensues,
which is as a seal to such ministry.
Is it the seal of our immortal King?
Does his holy hand stamp these offerings, as of his own preparing?
If not, from where have they their origin?
Alas, I often fear that creaturely activity takes the place
of the movings of the all-enlivening Spirit of Truth,
the holy anointing; with which we have no need that any man teach us;
and to teach and preach in the absence hereof,
seems to me to be even taking the name of the Lord our God in vain.
But what I consider a very awful matter for reflection is,
that should the reality of what we profess in ministry and worship be lacking,
then is it very evident that there is a substitute set up among us,
and a substitute too which many times bears an exact resemblance to what comes from God.
Then from where proceeds this likeness?
Must it not be the work and device of "`Mystery Babylon,`" who
can and does disguise herself so as to pass for what she is not?
The eye which is not anointed cannot discover the false
coloring nor the counterfeit gloss of which she is capable.
Is there anything in the true church of Christ,
the likeness of which may not be found in this grand
adept at the deceivableness of unrighteousness?

Many, very many, of our religious community are easily beguiled, being unwary; indeed,
not thinking it possible that those to whom they have been accustomed
to look as "`ensamples to the flock,`" should be misled.
Our dear youth too, are in numerous instances staggered, saying,
which way shall we look for the right path, and who will show us any good?
I trust, however, that the Almighty will be the protection of the humble,
sincere-hearted ones among the children,
gathering their spirits into communion with himself,
evidencing that "`as a hen gathers her chickens under her wings,`"
even so does he shelter these tender ones from harm.

I often remember your saying to me, by our fireside at Stoke Newington,
that some of us would be stigmatized as Hicksites; and so it has proved.
You expressed your apprehension of things getting worse before they improved,
which is indeed sorrowfully the case;
nor can I think the magnitude of this evil is yet fully manifest,
there remains such a disposition to cover it up and thus keep it from view.
But, oh,
there is nothing secret that the all-searching spirit
of Omniscience will not bring to light!

A conference has been proposed, again and again, at the Morning Meeting,
and in the Quarterly Select Meeting, but strongly opposed.
Dear Thomas Shillitoe renewed it in our Quarterly
Meeting of ministers and elders last month.
It was then deferred, and on opening the matter this day week, at the Morning Meeting,
some got so irritable, and there appeared such a great reluctance to it,
that we who had wished it yielded.
I thought it right to confess that I could not be tenacious,
remembering that "`the servant of the Lord must not strive,`" expressing, however,
my conviction that the state of things called for an exchange of views,
and free open communication one with another;
for I apprehended that there was increasingly a going off from the sure foundation;
and that which vaunts itself against the Truth stalks forth with power,
defying the simple, lowly thing, so long professed by Friends.
J+++.+++ F. spoke to everything many times through the meeting; he is restless,
and appears very zealous in the novel doctrine.
P+++.+++ B., G. S., and W. A. would have been glad had way opened for a conference; indeed,
many whose cry was to be still, and not think there was any approach to schism,
now see they were mistaken, and that, had the early appearance of danger been arrested,
much mischief might possibly have been avoided.

All this while I have said nothing of a highly talented Friend +++[+++Elisha Bates]
lately come from your land.
Some of us cannot get at him, at least not so as to admit of any freedom of conversation.
He is constantly accompanied by such as are not of the old school.
I+++.+++ B. has travelled with him so far, I believe,
ever since he commenced his visit to this nation,
and now holds a minute from his Monthly Meeting to continue with him,
although he is likely to stop a considerable time in and about London;
but probably you are in possession of all this from some other pen.
I heard the Friend preach in our Quarterly Meeting;
it was a beautiful exposition of Scripture,
and the doctrines of the New Testament were brought into view, in sublime language;
his delivery is also excellent, yet somehow I felt a chasm which tried me.
In our last Morning Meeting, the said Friend spoke near the close,
in answer to what some of us had ventured to assert as giving us alarm.
I gathered from Elisha Bates that we need not, in his opinion,
yield to so much uneasiness, recommended charity, brotherly love, etc.,
and to "`beware lest any root of bitterness springing up`" should trouble us.
This did not tend to the relief of some of us, but the contrary.
I thought it savored of the same spirit which has for years been opposing
itself to that which lays open our real condition as a people,
in this country.

What a very sad thing it will be should the seceding party gain over E. B. as a champion!
Oh, my dear friend,
I can say that my soul weeps in secret and is troubled for my own dear people!
Surely we are fast mingling with the world at large,
and not a few of the most active are taking retrograde steps, as though,
having begun in the Spirit, we could be made perfect by the flesh.
What a precious pillar must that dear Moses Brown be,
of whom your letter speaks so sweetly!
How I should like to set my eyes on the patriarchal form!
I am truly glad you have such a friend.
These are days of peril among false brethren;
but we do find a few prepared to sympathize with each other,
and to bear one another`'s burdens, and so fulfill the law of Christ.
You judged rightly in concluding that my dear husband and I have much
to bear in endeavoring to keep firmly to the ancient testimonies of Friends;
we are considered "`very narrow-hearted,
ignorant,`" and "`blind by prejudice;`" but while
we long that self may be of no reputation with us,
we do believe that the straitness is in that which
moves off from the immutable and invincible foundation,
even "`Christ within, the hope of glory,`"--yes,
while there may be great profession of faith in the
outward and visible appearance of him,
our blessed Redeemer, and of his being the propitiation for our sins;
all of which we old-fashioned Quakers as assuredly believe in as the rest,
and possibly feel full as thankful for,
in unfeigned and humble gratitude to him whose name is above every name.

You would feel for that dear old servant of our great Master, Thomas Shillitoe,
could you see how he is persecuted and set at naught.
He, however, keeps firmly fixed on the Rock of Ages,
against which even "`the gates of hell shall not prevail.`"
I should not wonder if his health gives way under the pressure of deep travail and concern,
not for his own honor, but for that of the unchangeable Truth as it is in Jesus.
Our friend J. J. Gurney has been engaged in his usual line of religious work,
in and about London, for a long time past, taking intervals of rest at home, writing,
etc. etc. Some Friends think him much deepened; I have not yet discovered it.
I always considered him very desirous of promoting good,
but as not having seen so far as the real Friend.
The same applies to his amiable sister E. Fry.
E+++.+++ Dudley is very active with her natural abilities for speaking and doing.
All these latter names I consider as not of the old school; many others I could mention,
ministers and elders, in town and country--east, west, north and south.
I have heard nothing lately of our mutual friend,
Ann Coning--think I shall write to her soon.
I have been engaged in company with my husband, holding public meetings,
and visiting those of Friends in this county and Suffolk.
We received a certificate for the engagement last eighth month;
some objection was started by one member in the Monthly Meeting,
and I know he was not alone in sentiment,
but there was an overpowering expression of unity.

Should you favor me with another epistle soon, direct--Jonathan Grubb, Lexden,
near Colchester, Essex.
We have been up to London twice to attend our Quarterly Meeting, etc.,
but expect to remain mostly here at our son`'s house, for some months to come.
I find some opposition in Suffolk to the ancient doctrines of Friends;
it has not yet made so much way in this county.
I am indeed exposed to the arrows of the archers in a peculiar manner;
yet can at times rejoice in being permitted to stand against
that which is estranged from the real cross of Christ,
the commonwealth of Israel, although my measure is small, and it is only as,
or "`when I am weak, that I am strong`" in the Lord,
and in the power of his might;--and all the while we are
assured that the cause which we are called upon to advocate,
is not ours, but that of our immortal King, who has no need of us, his poor frail worms,
but who nevertheless calls into his service, in wisdom inscrutable,
and that his power may be exalted, while the creature is laid in the dust.
We have heard but little of Charles Osborn since his return home;
some of our spirits are nearly united to him, a mourner in Zion;
we should be glad to hear of him and dear Christopher Healy.
We have been made thankful in your peaceful feelings on
returning to the bosom of your dear family and friends,
yet do not doubt your having to pass through many baptisms and exercises,
in filling up your measure of suffering and of active service in the militant Church,
and that the kingdom of a once crucified and forever
glorified Redeemer may prosper in the earth.
The last Yearly Meeting in London was still more strongly marked
by novel doctrine than the one you were at the preceding year,
and there was more manifest proof that we were not prepared to "`see eye to eye.`"
I fear the next will find us more widely differing still,
and I should not wonder if the liberal party (so called) are permitted to show
themselves as the "`scornful men`" that ruled in Jerusalem of old,
according to the sacred record; yet,
I believe that the tried foundation--the sure foundation, will be made manifest;
and that it will be seen that many have not forsaken it,
but do know it to be "`a hiding-place in the day of trouble,`"
"`as the shadow of a mighty rock in a weary land.`"

I am not in the habit of much writing,
but thought for once I would make a substitute for verbally communing with a far distant,
yet near and dear brother.
So fare-you-well.

I am in tender sympathy and regard, your affectionate friend.

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To Henry Hull.

[.signed-section-context-open]
Lexden, near Colchester, Second Month 2nd, 1834.

[.salutation]
My Dear Friend Henry Hull,

My husband`'s sight having failed a good deal of late,
he wishes me to take the pen and assure you,
that it is very pleasant to receive from your hand some
testimonial of continued remembrance and brotherly love,
after a lapse of time nearly amounting to _three and twenty years,_
when we had the privilege of your company, and could exchange sentiment,
or compare views in the freedom of children of one family.
Not less grateful to our best feelings is the sense which covers our minds,
while enjoying your communication,
that the unchangeable power of the Most High has kept you
in a state prepared to sympathize with His Church militant,
and to travail for the preservation of our poor Society;
that it might not slide from the sure foundation unto which it was originally gathered,
and on which it stood safe and strong,
through the fire of persecution in the days of our forefathers.

We do not marvel that you should bestir yourself to inquire concerning
the rumour of something like schism among us in this land.
The testimonies given the people called Quakers to bear,
have long been too lightly esteemed by many under our name; yes,
by some filling very conspicuous stations in this community.
And now there seems to be no inconsiderable leaning to _that,_
out of which the sons of the morning of our day as a people,
were brought by the strong hand and mighty arm of Jehovah.
Alas! alas! we are fast going back to Episcopalianism; little being lacking, with many,
to range on this side, except partaking of the outward ordinances of that Church.

Faith in the atoning sacrifice is abundantly enforced,
while there is little said inviting us to yield up the _will,_
with the "`affections and lusts,`" _to be crucified._
But without this knowledge of the power and Spirit of Christ,
what will a literal faith do for us?
or how can we learn duly to appreciate the adorable love
and mercy which brought the Son of God among men,
in a body of flesh, to live a life of sorrow,
and die in ignominy and in agony for sinful man--the just for the unjust?
They tell us that we are come now to the dispensation of reconciliation,
and to that which speaks better things than the blood of Abel, etc., etc.
Yes; but how can we, as individuals, experience this;
or how receive the ministration of justification,
save as we know the day of the Lord to be come to our souls, which burns as an oven,
even inwardly and powerfully; wherein all the proud, and all that does wickedly,
is as stubble, and the root and branch of the corrupt tree is destroyed?
Truly some of us have not so learned Christ,
as to conclude that He does the great work of salvation for us without us,
or that we have nothing to do with cooperation.
But fleshly indulgence is what we naturally wish for,
and here is a newly devised bait of the serpent to ensnare us in this country;
for he knew that the same make and shape in the way of temptation,
which laid waste in America, would not allure here just now,
and he has succeeded in a sorrowful degree;
so that there are those in the ministry who appeared
to be established in the true faith of the Gospel,
who, for lack of dwelling deep with the humbling power, preach up a literal Gospel,
as well as a literal faith, to be comprehended by the human understanding alone;
at least this is what I gather from their sermons;
but sometimes it is the case that the most orthodox among
us can by no means object to the doctrine held forth,
and yet the life seems lacking, even "`the demonstration of the Spirit and of power.`"

You will believe that it is a very trying time, and has occasioned the lowly,
the faithful ones among us, to go mourning on their way.
This has been the case for a long while past, yet there are those who,
trusting in the Lord, and not leaning to their own understanding, are indeed "`steadfast,
immovable.`"
I have a firm hope that a remnant will be found adhering, through all difficulty,
to the invincible Rock, against which, the very highest authority declares,
"`the gates of hell shall not prevail.`"
But oh! how is the innocent life now trampled upon!
How is the mystical body of Christ despised within our pale!
Surely if the members are set at nought, so is the Head;
and I am persuaded that the true Christ is crucified afresh, and put to open shame,
under the very pretence of extolling Him.
We have indeed the "`lo here,`" and the "`lo there,`" come with power,
but concerning which, we had need attend to the warning and prohibition,
"`Go not forth to meet them.`"

Whether these things will bring to any outward line of separation or not,
is yet to be proved.
Great lack of unity is apparent.
We who do not profess to see further than our first Friends did,
and who consider that the boast of greater light
on gospel truth than they were to speak of,
is not safe, I say, we are styled "`ignorant,`" "`prejudiced, and "`uncharitable.`"
But is not the straitness in that which thinks it knows
anything without the Spirit that searches all things,
even the deep things of God?
And is not that out of the true charity, which denies "`Christ within,
the hope of glory?`"
It has been my painful lot, from year to year, for many years past,
to utter a warning voice in our annual assemblies, and at other times,
against the very things that are come upon us;
but I was told again and again that I must be mistaken,
and recommended to endeavor to look on the bright side of things, etc.; and even now,
in effect, the cry is, "`Prophesy peace; prophesy smooth things;`" or else keep silence.

My dear husband and I, with our family of three children,
removed to this country in 1818; residing at Bury, in Suffolk, five years; at Chelmsford,
in Essex, six years; and since at Stoke Newington, about four miles from London,
where we have lived four years, and which is still our home.

The motive for leaving Clonmel, in Ireland,
was no other than to be found following our dear Master;
nor have we taken any fresh steps of the same kind in this land,
without the same thing in view.
It has not been very pleasant to our nature to be thus thrown about,
nor to relinquish my husband`'s prospects in business,
yet we must acknowledge to a portion of that peace in making the sacrifice,
which is of more value than outward ease, or than all the treasures of this world.
Many, very many, have nevertheless been our trials of various kinds.
We are now in the last stage of life, still moving about a little in religious service;
holding at present a certificate for appointing public meetings in this county and Suffolk.
We have never been long at a time without active engagements from a sense of duty,
since we last saw you.

We are much pleased to find you have temporal as well as
spiritual blessings bestowed upon you and yours.
May He who has been with you to this day continue near!
May He who has redeemed and delivered your soul out of all adversity,
still prove your sufficiency; guiding you in the remaining steps down the hill of life,
even by His counsel,
and afterwards crown all your labors and sufferings with ineffable and eternal glory.
So farewell, says

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Fourth Month 29th, 1834.

I sympathized with the state of your dear mind when we parted.
Oh! my dear +++_______+++, what is like the tendering influence of truth on our hearts?
I had rather that my dear children were favored with this than with thousands, yes,
hundreds of thousands of gold and silver.
Be encouraged to conclude that all things relating
to you are ordered in the wisdom that cannot err;
so will you marvelously be delivered from perplexity and woe,
and the Lord will be magnified through you, as well as in you,
more than has even yet been the case.

[.letter-heading]
To Mary Capper.

[.signed-section-context-open]
London, Fifth Month 27th, 1834.

[.salutation]
Dear And Precious Friend,

Your lively communication, received a few days since, has done me good.
How sweet is the sympathy of a mind regulated by the pure
principle of Divine grace placed in our hearts!
Few letters that come to my hand are fraught with so much encouragement as yours;
so genuine is the desire breathed by your expressions for our preservation every way,
and that the good cause may prosper in, by, and through us; and so evident is it,
that He who was your morning light is now your evening song;
as well as that He remains to be like dew which keeps you fresh and fruitful still.
Yes, your address to my dear husband and me seems to invite
us forward in the race set before us,
while we often feel far from either swift or strong.
Sometimes I cannot run, only wade through difficulty and much impediment;
yet so far my poor mind can acknowledge that they
who wait upon the Lord renew their strength;
that herein ability is received to mount upward too at seasons,
even with wings as eagles; to run, and not be weary; to walk, and not utterly faint.
The present is a time peculiarly calculated to depress some of our souls; for yet,
within the borders of our religious Society,
we find there is too generally a sliding from that situation in
which Infinite Wisdom and Power placed our early predecessors;
when their light shone as from the hill of the Lord, and men, seeing their good works,
were induced to glorify our Heavenly Father.
Oh! we are indeed sadly mingled as with the crowd,
and it looks as if this might be more the case.

We have heard a great deal of preaching already during this Yearly Meeting,
but really we can select but little that has been like the old sort;
even as an Apostle spoke of the true gospel ministry, when he said,
"`Not with enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power.`"

I could say much more in a plaintive strain,
but forbear--let me watch well over my own heart.
Besides there is room, amidst all our occasions of sadness,
to be humbly thankful that the sure foundation is kept to by a living remnant,
and also that a little, yet firm faith is vouchsafed,
that the ancient testimonies of the immutable truth
will continue to be upheld by at least a few,
and the standard raised in its own dignity and simplicity;
for let the great and the learned among us say what they will,
of further light being manifested to them on gospel truths,
than was known in former days, surely,
as there is nothing beyond the meridian brightness of the Gospel,
and that it was long since proved the sons of the morning of our day as a people,
were brought to this, that which has stood the test of ages will stand through all,
being truth and righteousness unfailingly;
and it requires not the torch of human reason to search it out.

I remain, I trust in that which knows no change,

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stock Newington, Fifth Month 29th, 1834

[.salutation]
My Dear +++_______+++,

I have to acknowledge yours written on First day, which was indeed truly grateful.
I know you all think of us, and I trust desire our help in the spirit of true prayer.
As for me, until this day, my mouth has been sealed in silence in our Women`'s Meeting;
but at length "`the word was like a fire in my bones,
and I could not stay;`" and this I was engaged to tell them.
I had a brave time of unburdening, which I am sure you will be glad to hear.
Notwithstanding I feel that I have not lost more than a
_part_ of my load with respect to this Yearly Meeting,
and whether any further way may open or not, must be left.
On First day our meetings here were very large.
In the morning I had to lift up my voice like a trumpet for perhaps nearly an hour,
which brought considerable relief to my exercised and oppressed spirit.
I certainly do not see that things are any better with us this year than last,
although there appears to be a disposition to accommodate
the mode of expression to the wish of those of the old school;
but however cloaked up, the same thing exists which prevents our being united in spirit,
and feeling that we are each other`'s joy in the Lord.

_Sixth Day._--Now I have to acquaint my precious children
with further relief being mercifully granted me,
by a visit to the Men`'s Meeting,
in which I had to allude to former messages being delivered there in the Great Name,
warning against that which has already in part come upon us,
and inviting from the subtlety of the serpent, etc., etc.
Oh! what a mercy to be enabled to do the Lord`'s work without deceit,
or keeping back _part_ of His counsel, however little may be required,
or however mean the one employed!
Oh! my loved children,
already I feel as if an almost intolerable weight was laid down among my own dear people,
to whom I have often been sent, and they will not hear;
for they will not hear Him who sends by whom He will send--sometimes the
things that are _not_ (like myself) to bring to nought things that _are;_
but I find the unity of a precious few among us,
who are glad that I am enabled to speak _boldly._
And I do believe there will yet be those preserved who will evidence that they
are kept by the power of the Lord on that foundation that cannot be shaken;
and that the same testimonies given to our early predecessors to bear,
will be upheld and flocked unto,
even though many among us may be of those that were first, but shall be last.
I had to speak of the holy propriety of keeping to plainness of language, dress, etc.,
as well as of doctrine; which those who do the will of the Father become acquainted with,
beyond all reading, hearsay, or study.
I must conclude, as we are going to the last sitting of the Yearly Meeting.
The Select Meeting tomorrow I tremble to think of.

[.signed-section-closing]
I am, most tenderly, your affectionate mother,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Stoke Newington, Sixth Month 3rd, 1834.

Many now see their mistake in supposing that we only
_imagined_ causes of uneasiness in our Society,
for things are manifesting themselves more and more;
and yet there is every effort made to put a covering over the false spirit,
so as to render it like what it professes to be.
The mask, however, will and must fall off; and I think is removing already,
in some instances.
Oh!
I have suffered much since I saw you last;
and during this annual assembly my bonds were great and heavy.
I thought it unlikely that they would be loosened at all, until First day week last,
when I had to stand forth in our First day Morning Meeting,
and then again in the Women`'s Meeting, the day before it closed.
Next day I was under the necessity of avowing a concern to visit the Men`'s Meeting,
and also I have found my way to obtain some relief in the Select Meeting;
so that my spirit has been much eased in an endeavor to speak the word faithfully.

It was upon my spirit to propose, once more, that Friends should hold a conference,
which I ventured to do in the Divine fear: it was, however, rejected.
My husband revived the words of scripture--"`Sanctify a fast;
call a solemn assembly,`" etc.

All the error of those who oppose the true ministry of the Gospel can be met,
with the humble boldness which the Gospel furnishes;
but I confess to discover a jealousy in _some_ quarters,
with respect to one`'s being rightly influenced and guided, is hard to bear;
after having, _through much suffering,_
endeavored simply and singly to follow the Shepherd`'s voice; however,
in waiting still upon the Lord, "`as a servant`'s eye is to his master,
and that of the handmaiden to her mistress,`" I was favored with this intimation,
to remember that _one_ is our Master, even Christ, and that all we are as brethren;
therefore it was for me to mind my Master, while I may hear the brethren;
and I was to be deaf and blind, save to the light that is self-evident,
and to the voice from heaven.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sixth Month 18th, 1834.

Yours by yesterday`'s post is very interesting to us;
and the way in which you speak of meetings, etc.,
differs not at all from my own views of things.
It is for us to dwell deep in our spirits with that which is of the truth,
and it will preserve us every way,
and give us to try the spirits whether they are of God.

Let us humbly trust that all things will be for our ultimate good,
as our hearts are really given up to the Lord.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Lexden, Sixth Month 27th, 1834.

You will not be in any doubt of my bearing each of you upon my heart continually,
nor of the earnest desire I feel that you may know a blessing to be stamped upon
your present visit to the land which gave you and your dear sister birth.

It is an unspeakable favor from the great Head of the Church, that true,
living Gospel ministers are yet raised up in that land,
and sent forth in the High and Holy Name.

I may now tell you that we came down here under feelings of quiet, having, I hope,
endeavored to be faithful to manifested duty, both in the Select Quarterly Meeting,
and at other times.
I stand no higher in the estimation of those who have long opposed me,
for these late effusions of my heart, which have gone forth, I humbly trust,
with innocent boldness.
Dear Thomas Shillitoe looks poorly and low.
I almost fear his days may be shortened by the present state of things,
he suffers so much.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Lexden, Seventh Month 6th, 1834.

I have tried how far I could visit you in mind, from time to time, in Clonmel;
and often say in my heart, that were we poor mortals gifted with _second sight,_
we might _sometimes_ be glad; but with a mind of my complexion it would, I fear,
greatly increase the propensity to solicitude, already too much alive.
You and I must try and not feel things too keenly.
I have fancied you much gratified by the society in which you have been,
and with the views you have seen--those of simple nature; some of them bold and grand.

I apprehend there are inward and nearly indescribable sensations and emotions,
occasioning no inconsiderable conflict;
and for which there remains to be no repository like the bosom of Him who was,
_in all points,_ tempted as we are, yet without sin.
Oh! may my beloved children find rest and consolation in Him,
even by leaving all to follow Him.
One said,
"`let me first do this,`" and another "`that;`" but we may instructively
take into account that the present time only is ours;
and the reply to these excuses evinced that _prompt_ obedience to the call was requisite,
and this remains to be the case.

I write between meetings.
We have been favored with a living, powerful meeting this morning.
I went there devoid of every sense of good.

Since the Quarterly Meeting at +++_______+++,
I spoke to a friend or two of the Morning Meeting;
suggesting the propriety of their interference;
but it seems things are still to be let alone! Where are our judges and counsellors?

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Seventh Month 27th, 1834.

[.salutation]
Oh! my dear +++_______+++,

I feel good for little;
but such a one is nevertheless often raised up in the mighty
power of the great and awful "`I AM,`" to declare His truth:
latterly this has been the case with much humble boldness.
I feel clear and eased in my spirit a good deal, with respect to London, etc.
Many are sadly beguiled,
which it pleased the Great Master to enable so mere a worm to point out clearly,
and with almost invincible authority, before we came down here.

I had, at Yearly Meeting,
several hints to keep "`in the quiet,`" after the Captain of the Hosts
of Israel had put weapons into my hands (all weak without Him),
and strengthened for the battle.

May Heavenly Goodness keep Ireland from the grievous snare
that has caught and entangled so many in this country!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Eighth Month 15th, 1834.

My love flows freely to you, our dear friends,
and I thought to have come and communed a little with you, but have been prevented.
I quite anticipated taking the corner seat by dear +++_______+++,
and that we might together feel ability to rise above all transitory things,
for a short time; and I hoped, be baptized in His presence,
who remains to be as "`a place of broad rivers and streams.`"

I may tell you, my true, sympathizing friend,
that I never experienced more of the living power of truth,
in the exercise of the gift bestowed, than since coming down here this time;
from meeting to meeting it has been so, with scarcely an exception.
I have indeed been a wonder to myself; for no one could sit down more empty,
or a greater blank: and oh! the word would come,
like the bubbling up of a well of living water, or like the flowing tide; and then again,
when it receded, I was dry as the sand on the sea shore.

I have been very abundantly convinced that the authority and heart-melting influence
of the Divine Spirit is indeed distinct and separate from all that is of the mere man;
and no more at the command of even the best informed and most sagacious human being,
than the descending of rain, or the flowing wave.

I think we are not without fellow-feeling with those who remain on the invincible foundation,
who must in this day find the building tried indeed; and must, if faithful,
suffer with that which is oppressed, while the spirit of Goliath vaunts itself.
I cannot but secretly mourn at what seems to me to be holding back among you, instead of,
as it were, "`coming up to the help of the Lord against the mighty.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eighth Month 25th, 1834.

How vain are all human efforts that are now making to give people faith;
a _literal_ faith it is, which we find so much recommended as essential to salvation.
Surely true faith is a gift from the Highest, and must be waited for with diligence,
and creaturely abasement.

[.letter-heading]
To Elisha Bates.^
footnote:[For many years,
Elisha Bates was a useful minister and author in the Society of Friends.
Sadly, in the 1830`'s, he was captivated by the novel views of the Beacon party,
and led away from the faith he had promoted for many years.
Finding that his principles and practices were becoming increasingly unsound,
Friends on both sides of the Atlantic were obliged to disown him.
His latter years were spent speaking and writing
against the writings of George Fox and early Friends.]

[.signed-section-context-open]
Near London, Ninth Month 12th, 1834.

[.salutation]
Dear Friend,

As I mentioned to you after meeting last evening, I feel much regret,
that during your visit to this nation, some of us have been shut out from your society.
As an individual I can truly say that my heart has been, and still is,
sensible of tender love toward you, and interest in your passing along, as a brother,
and as a minister.
Your often interrupted health has given me affectionately to sympathize with you,
knowing from experience how trying this is;
and perhaps increased by the remembrance of the wide separation from home.
I am, however, aware that those of the social circle in which you have moved,
are not only _disposed_ to alleviate the suffering permitted,
but abundantly calculated to do so.

Now allow me to pen a little of my sense of deep interest
respecting your engagements in word and doctrine;
having never before addressed you on paper,
and fearing there will be no opportunity for verbal communication.
Perhaps both you and I think that we speak under
the same influence that enabled our first Friends,
called to the ministry, to preach _Christ:_ we do, however,
differ with respect to our views,
if I gather what yours are from your communications in the gallery; for it seems to me,
that while you recommend and enforce faith in the outward coming of the Redeemer,
and in all that He did and suffered for mankind,
in that prepared body in which He offered Himself
up a propitiation for the sins of the whole world,
you do not call us unto His inward coming,
by which _all_ may partake of salvation through Him,
even those who are without the privilege of the Holy Scriptures;
and unless we who have them, and profess belief therein,
come to this revelation of the Savior in our hearts, we are yet in our sins.
I have never once heard you preach universal grace, and I confess, as an individual,
I cannot recognise your ministry in the anointing;
for it does not seem to me that the power of God
and the wisdom of God is evidenced therein,
while exposition of scripture, in the "`wisdom of words,`" is largely set forth.
Oh! my dear brother, I am sorely grieved for you.
Was it always thus with you?
I know not how to rest in my spirit, without acquainting you with the pain that I feel,
lest your best judgment should be warped.
Great is the influence of one circumstanced as you are:
would it not be sorrowful to become the instrument of bringing any to
rest in that which is short of the gospel dispensation?

I am, in a sense of travail of soul for your truest interests,
and with sincere affection, your real friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Stoke Newington, Ninth Month, 1834.

We have been at the Morning Meeting:
I had ability to deliver what was on my mind both yesterday and today.
I have not been once at meeting since coming, without being permitted to unburden.

Your account of the increase of disease at Colchester is affecting.
I expected something would come there, and a year ago was led to say so in public.
How glad I am you could keep in view the notice and care
of Him whose tender mercies are over all His works;
without whom even a sparrow falls not to the ground!
It is, as you remark, very awful indeed;
and we can only find rest in committing ourselves into the Divine Hand.
It is thus, that come what will come,
we need not be afraid for ourselves with any amazement: no,
not "`for the pestilence that walks in darkness;
nor for the destruction that wastes at noon-day.`"

Many rather gay Friends seem glad to shake hands with me,
although despised by some who make a very high profession as Friends.
I think of being at the General Meeting at Hereford,
and have obtained credentials from the Monthly Meeting yesterday,

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Ninth Month 13th, 1834.

I am glad to find the disposition allotted you of late has been so peaceful.
It made me think of poor John Bunyan`'s "`delectable mountains,`" which,
though the pilgrim might not stay there always,
were no doubt the means of strengthening his faith for _after difficulties,_
as well as _present_ relief.

Many are my probations, but I wish to find,
that to be in _that_ work allotted me is my element, as it were; in my measure, to say,
as George Fox did in his greater measure,
"`I am in my holy element in the Lord`'s holy work.`"
Oh!
I do delight in being despised and rejected by those among _us,_
to whom the stone laid in Zion is a "`stone of stumbling, and a rock of offence.`"
I have much to share of that which sets at nought the simplicity of Christ,
and yet in word enforces faith in His blood;
but it feels to me there is a trampling under foot His lowly, innocent life.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 14th, 1834.

If the love of father or mother, etc., more than Christ, renders us unworthy of Him,
surely the preference being given to our own reputation, and ease of the natural mind,
must indeed render us utterly unworthy of the love and favor of Him who, for our sakes,
became a man of no reputation; being as He was, "`despised and rejected of men;
a man of sorrows, and acquainted with grief.`"

[.letter-heading]
To her Husband.

[.signed-section-context-open]
High Wycombe, Tenth Month 2nd, 1834.

I thought your letter breathed a sweetness which nothing short of the heavenly
dew could produce--that this will never wholly be withdrawn from you,
I fully believe.
No, no.
The same blessed influence that has been with you all your life long,
will still preserve the immortal part in a state in which the Lord smells a sweet savor;
even as the same integrity of heart is still maintained,
which has hitherto been mercifully yours.

The Quarterly Meeting in London was very formidable in prospect.
My spirit was bowed down greatly on second and third days;
and I rose on third day morning with an awful weight upon me.
Under this I went to meeting, where I sat in great exercise of spirit before the Lord.
It was long before I found my way to utter anything.
W+++.+++ R. and W. A. both spoke.
My way being clearly made straight for me,
I stood up soon after the latter Friend took his seat.
It was truly awful work.
I had to lay things open, as they were opened to me, in the freshness of the Divine life.
It seemed to me that the authority of truth was almost _invincible._
Error was detected, and Mystery Babylon`'s devices set forth;
and her deceivableness of unrighteousness,
her making _likenesses_ of all that is found in the true Church,
and her artful contrivances to pass for the Lamb`'s Bride,
were all described (as I believe) in the demonstration of the eternal Spirit.
My mind was abundantly relieved--yes, more than for a long time past;
yet a remaining sense is with me, that few could go all the way with me;
but if ever the Captain of Israel`'s host gave the victory in my experience,
He gave it _that day._
All the praise and the glory be ascribed to His adorable Name.
Amen.

My physical powers were so exhausted after this meeting,
that I was not able to attend that for discipline;
and missing dear Thomas Shillitoe from the gallery,
walked slowly to P. B.`'s to enquire for him.
He had been ill in the night, and was then asleep; so I waited some hours,
and after seeing him, went to my lodgings.

Yesterday morning B. Reed brought us to Uxbridge to meeting.
It was a remarkable time with Friends,
and I could see no way rightly to escape a public meeting in the evening.
This also was much favored, and very large.

We came here today.
William Hull, and John Hull`'s wife, accompanied us.
The meeting has been to me truly wonderful,
as has now been the case in every opportunity for speaking in the Great Name,
since I parted with you.

I have ventured to appoint another meeting here for the people this evening,
under which I now lie again very much bowed.

[.letter-heading]
To the Same.

[.signed-section-context-open]
High Wycombe, Tenth Month 3rd, 1834.

The public meeting yesterday was long gathering,
and I did not see my way to stand up for a considerable time,
which I afterwards attributed to the circumstance
of _all_ not having arrived whom I was to address.
In the end the meeting proved very large.
Many respectable inhabitants were present,
as well as others of different classes in community;
and once more "`my soul did magnify the Lord,
and my spirit rejoiced in God my Savior,`" who, I humbly trust,
led me safely through the engagement, to the exaltation of His truth,
which again was _over all._
Oh! what a living sense of the power of the Most High, and of His infinite love,
covered that large mixed assembly, as well as the previous one at Uxbridge!
I did not know that these formidable engagements
were likely to fall to my lot on this journey,
which always plunge me into baptism peculiar to the service.
May I be enabled to stand faithful in doing or suffering the will of my Great Master;
and oh! may He keep me from all that would in the least degree dishonor His holy,
excellent Name!

The two meetings I have yet had with Friends were remarkable
for an opening into the different conditions of souls present.
They each held long, and although my exercise was deep, and sometimes sore and painful,
I have found great relief in being mercifully enabled to mind my Guide,
in the truly dangerous steppings in the line of ministry.
Oh! how fearful a thing it is to be led clearly to speak
to the state of things among us in this trying day.

I lodged at Anna Hull`'s at Uxbridge.
After visiting Friends at meeting, the young men called on us so kindly,
and appeared so willing to assist about getting the public meeting, that I felt glad,
not merely for my own sake, but likewise for theirs;
as their taking interest in these things looks well with respect to some religious sensibility.

The family where we now are, are as kind as possible.
My companion is a very agreeable Friend to travel with.
I quite hope his coming is in right ordering.

_Evesham, First Day._--This morning the meeting here was, I think,
as those I have before mentioned: various states were addressed.
A public meeting is appointed for this evening in the town-hall,
Friends`' meetinghouse being far too limited for the number who wish to attend.
Thus, from time to time,
I do not escape these trials of my allegiance to our Immortal King.
Very far from what would be my own choice are such concerns, as you well know.

The meeting lies heavy upon my mind.
Oh! may Divine Goodness be a very present help in the moment of extremity;
and may the same precious influence accompany you and our dear children!
