== Chapter 18. Letters from 1836--1837

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Fourth Month 13th, 1836.

Sometimes, when I feel considerable depression,
I think surely there is no occasion to be "`afraid with any amazement.`"
We have a compassionate Judge, who is also our Savior and Father;
and when I endeavor to flee to Him,
away from painful cogitations about things of this life, I find that,
gathering near as well as I can, His Name proves indeed a strong tower of safety,
and my mind is at least in measure quieted.

We are indeed come to strange times (as regards our Society) but of this I am persuaded,
that the standard of truth, ancient and new, cannot be lowered by the wisdom of man,
or any of the devices of the serpent;
though a disposition may prevail and be operated upon,
to square things to the notions of such as are "`wise in their own eyes,
and prudent in their own sight.`"
Let us be simple and humble;
keeping with the lowly life of Christ Jesus in our own hearts;
then will it keep us from all that could harm us.

Be assured I bear you on my heart before Him who is omnipotent as well as omniscient;
and of whose mercies, I humbly trust,
you will partake as I have done all my life long unto this day, a poor creature as I am.
My dear, my very precious child, may it be shown you in due time,
that your labour to be faithful to your soul`'s Beloved is not in vain in Him,
your Savior and your Judge.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month 22nd, 1836.

I am glad of the clearness afforded you in your views
as to passing events among us as a Society,
both in this country and yours.
I am also made to rejoice that you are counted worthy
to suffer in advocating nobly the cause of truth;
a cause "`dignified`" indeed, "`with immortality, and crowned with eternal life.`"
I humbly trust that nothing will be able to move
you from your steadfastness in "`Him who was,
and is, and is to come;`" but rather that, enduring the contradiction of that spirit,
opposed to the simplicity which is in the holy, heavenly anointing,
you will be endued more and more with wisdom and strength that comes from above;
"`and so stand fast in the Lord, dearly beloved.`"

In the prospect of finishing our course, now so nearly run,
it is consolatory to see a few of you, in the prime of life,
giving up your names to be lastingly enrolled in the list
of those who fight under the banner of the Lamb,
and to mark your willingness to endure hardness for His sake,
even as good and valiant soldiers.
Oh! what signify all our trials and buffetings,
if we may but know a continuing with our dear Lord in the temptations which were His;
seeing that He appoints unto them a "`kingdom;`" seeing He grants
them "`a crown of righteousness that fades not away.`"
Yes, and during the stay of His devoted followers in a probationary world,
I verily believe that He gives them the dominion over the powers of darkness;
"`He sets them upon thrones,`" and grants gifts; enabling them to be judges in Israel,
and counsellors among His people.

In our Women`'s Meetings we have at times a stream from Babylon`'s waters,
which makes sad the Lord`'s heritage;
but oh! it never fails to produce its own deplorable effects.
+++_______+++ says as much as that we have been wrong from our beginning;
particularly as regards our views of placing the sacred writings secondarily; that is,
as a rule of faith and practice, but not the primary rule.
But the long-disguised Episcopalianism is at last showing itself in its true colors;
and indeed all things seem to be searching out,
that the way may be prepared to discern between that which serves the Most High,
and that which serves Him not; and all these novel doctrines will, before a great while,
be as a fading flower, I do believe.
Oh! some of us are prepared to have fellow feeling with you in your Yearly Meeting,
if it were only from what we ourselves suffer at this.

I trust, through all, that the immutable truth sometimes shines forth,
as the sun dissipates the clouds in the firmament.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
London, Fifth Month, 1836.

I had a very awful requiring, on fourth day morning, of a visit to the Men`'s Meeting,
where my Great Master opened the way for me to lay down a heavy load indeed;
and for which relief I felt and feel humbly thankful.

I still hope the little humble ones will be comforted and strengthened,
by the all-tranquillizing influence of the Spirit of truth,
spreading over them before this annual assembly closes.

+++[+++The following is the substance of what was delivered
by Sarah Grubb in the visit to the Men`'s Meeting,
alluded to in the foregoing letter;
and has been supplied by a friend who took it down shortly after.]

[quote]
____
I am come among you, a poor, weak creature, laden with a burden,
the weight of which cannot be expressed even by the tongue of the eloquent,
much less by mine; but I must endeavor to lay it down.

The time is now come, often foretold,
when the Lord would descend among this people as the rain, the storm,
and the overflowing flood.
It must indeed be acknowledged that a weighty shaking has come upon us.
There are among you those who have been as fruitful branches,
but for lack of abiding in the root, and retaining the sap, are withering,
and will wither.

The foundation of every individual in this Society will be discovered,
whether it be '`upon the rock`' or '`upon the sand.`' '`Whosoever
hears my sayings,`' said our blessed Savior,
'`and does them, I will show you to whom he is like.
He is like a man which built a house, and dug deep`' (Friends,
you do not like the trouble of digging deep) '`and laid the foundation
on a rock.`' The Jews heard this saying of Christ with their outward ears,
but, having their inward ears closed, they would not build on Him, the Rock;
and when the rain descended, the floods came, and the winds blew, they fell.

How painful were the sufferings of our forefathers in coming to this foundation!
Their opponents were strong in the words of scripture,
like those formerly who thought that in them they had eternal life;
to whom our dear Savior addressed these words--'`You search the scriptures,
for in them you think you have eternal life, and they are they which testify of me;
and you will not come to me, that you might have life.`' Thus,
though they studied the scriptures,
and imagined they were skilled in the knowledge of them, yet,
resting in their outward knowledge, they would not come unto Him of whom they testified,
and in whom alone there is life.
You, too, study the scriptures by the strength of your rational, intellectual faculties,
and doubt not you comprehend their meaning; and here you stop:
you refuse to come unto Christ in His inward and spiritual appearance;
you will not hear His voice speaking in your hearts, and are therefore rejecting Him.

Man is a dark, benighted creature.
By his natural powers he cannot know himself; he cannot discover his way out of the fall,
into a lasting union with his Maker: his heart is deceitful above all things,
he must therefore come unto Him who searches the heart; and how does He search the heart?
by His Spirit; '`for the Spirit searches all things; yes,
the deep things of God.`' '`For what man knows the things of a man,
save the spirit of man which is in him?
even so the things of God knows no man,
but the Spirit of God.`' The light of Christ is imparted to each of us;
a measure of the same Spirit that gave forth the scriptures.
When Adam had transgressed the commands of his Maker,
he lost the Divine image in which he was created;
he died to the heavenly life he had in God; but our Lord Jesus Christ,
in His infinite mercy, entered into his heart, as the true light, wisdom, and power;
and it is only in His light that we can see light.

Oh! my friends, there were some in ancient days who said one to another, '`Go to,
let us make brick, and burn them thoroughly;`' '`let us build us a city and a tower,
whose top may reach unto heaven.`' Some of you are laying hand to hand,
and shoulder to shoulder, to erect a tower whose height may reach to heaven;
beautiful indeed to the eye, and of fair proportions; and you are saying to others,
'`Come and behold what we are doing; join yourselves unto us,
and we will show you the gospel path unto heaven; a path full of charity and love;
an easy and a comfortable path, wherein you may avoid the cross;`' but '`say not,
a confederacy, to all them to whom this people shall say,
a confederacy.`' Oh! beware of that subtle spirit
which would lead you from the pure truth,
under such delusive pretensions; for though these talk of the unity of the Spirit,
it is not the cementing influence with which Christ
unites His disciples in precious fellowship.
And I am commanded to tell you that, as in the instance of the tower of Babel,
the Lord came down and confounded their language,
so will it be with the Babel-builders among us; for when they come together,
they will not understand each other`'s speech;
and their building on the sand will crumble to pieces, and they themselves will wither,
wither, wither; and be scattered to the north and to the south,
to the east and to the west.

And oh! let me earnestly entreat you of this description, in the love of the Gospel,
to stand still and see what you are doing.
I believe there have been times when some of you have seen, in the true light,
that you were wrong, but the pride of your hearts would not allow you to acknowledge it;
but remember, it is an awful thing to tempt the Lord your God:
you know not how long these convictions may be granted you;
and '`if the light that is in you be darkness, how great is that darkness!`'

And now, my beloved young people--you, dear children,
on whose behalf I have often raised the secret petition in my chamber,
and the more public one in the assemblies of the people,
be not dismayed at the prospect before you;
for I have to tell you (and I wish you to take notice of it,
and to write it down) that all this that now causes so much stumbling and perplexity,
and produces such a sensation, will fade away,
and the authors of it will go back to the world and the beggarly elements;
and on looking round, you will wonder and say,
'`What is become of the great work that was doing, and where are the authors of it?
for we cannot discern a trace of it.`'

What became of those who, in former days, caused divisions in this Society?
Were they not all blighted and scattered?

And you, faithful ones, to whom the principles of truth are yet precious;
who love the pure cause, and are often bowed down in spirit on its behalf,
you have no cause to fear;
for though you be left as the gleanings of the grapes of the vintage,
yet shall you be planted on a very fruitful hill; not one of self-exaltation,
but a hill above the level of the spirit of this world; and you shall spread abroad,
and increase, and flourish; for this Society was planted '`a noble vine;
wholly a right seed;`' and it is not the will of the Almighty
that this people should ever cease to be a people.

I brought nothing with me into this meeting,
for I remembered our Savior`'s command to His disciples,
not to take thought how they might speak; with the promise,
'`for it shall be given you in that same hour what you shall speak.
____

[.letter-heading]
To Mary Capper.

[.signed-section-context-open]
London, Fifth Month 24st, 1836

[.salutation]
My Dearly Beloved Friend,

This day your precious, sweet letter, was handed me.
Oh! how truly cheering it is to witness and contemplate the state
in which Divine Goodness has kept you to this day!
I can look back to my childhood,
when I first saw with wonder the tears flowing from your eyes in meetings;
when you were an example to many, of nobly denying self, taking up the cross,
and following Him "`that endured such contradiction of sinners against Himself,`"
and who has been pleased to lead about and instruct you ever since;
yes, He has kept you as the apple of His eye;
and so I humbly believe He will keep you to the end; guiding your feet,
the few steps which remain,
and ultimately granting an entrance into those blessed regions where none can say,
"`I am sick;`" where there is no more pain, neither any more sorrow;
but the Lamb that is in the midst of the throne does lead to living fountains of water,
and all tears are wiped from the eyes forever and ever!

Some, in this our day, are almost ready to adopt the language,
"`Oh! that my head were waters, and my eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of my people;`"
for truly there is among us that which lays low the pure,
innocent life, that ought to be in the ascendancy;
yet my faith is that better times will come, even to this religious Society.
There is, I do believe, a living remnant left, who,
in being preserved through the shaking which has come terribly upon us,
will shine forth by and by, even as the light, and many will come to its brightness,
so that there will be Quakers still;
those who hold the precious testimonies of the everlasting
Gospel in their primitive simplicity and unmixed purity.
And surely it is unto the truth as it is in Jesus, that the nations must come,
in the fulfilment of the prophecy,
"`The kingdoms of this world shall be the kingdoms of God, and of His Christ.`"

We have had some favored meetings,
amidst the opposition to the first principles of Friends, at this our annual gathering.
Yes, at seasons, the Lord`'s own blessed presence and power has been over all,
to His own praise; to whom all honor and glory belongs, now and ever.
Amen!

My husband sends you much unfeigned christian love, in which I tenderly unite, and remain

[.signed-section-closing]
Your ever attached friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Sixth Month 15th, 1836.

Your kind letter met me last night, on returning from our Ipswich Quarterly Meeting.
There was also one from M. W.,
acquainting me with the departure of our much loved Thomas Shillitoe.
While I feel it to be very moving, that we should thus be deprived of a prince in Israel,
in these times of dismay, I rejoice for his escape from all suffering,
and that his measure was filled up, not only as regards His own safety,
but the good of the Church.
Oh! may his dear children and grandchildren walk in his steps.
His example has said, and his memory will yet say, "`Follow me,
even as I have followed Christ.`"
Ah! he was a valiant man for the truth upon earth.
As "`the sword of Saul returned not empty,
and the bow of Jonathan turned not back from the blood of the slain,
from the fat of the mighty,`" so was it with him: he was faithful also unto death,
which could not be said of Saul.
How weighty, how glorious is the crown he wears forever!
Blessed and adored be the name of his Divine Master on His behalf!
Amen.

Will those who have added to his bonds of later years,
feel that they touched the Lord`'s anointed with unhallowed hands?
Whether this be the case or not, I believe that they, and many more,
will be obliged to know that a prophet has been among them.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Sixth Month 21st, 1836.

So our dear honorable elder in the truth, Thomas Shillitoe,
has made his escape from this sea of troubles,
into which we are introduced as a religious Society.
It is cause of giving thanks on his behalf, yet he must be missed;
for he had attained to the state of "`a pillar in the temple that
should go no more out;`" and is it not lamentable to look around,
without being able to discover the same preparation in others for upholding the building,
even as those formed by the all-powerful and skilful Hand to supply the places of such?
It is quite my apprehension that dear Thomas`'s days were shortened,
by what he had passed through for years previous to his departure,
on account of the things that have happened to the children of his people.
Others are still mourning out their days, under inexpressible pressure of spirit;
yet I do believe that, in this thing which has appeared among us,
the head has already received a deadly bruise or wound;
for it is indeed of "`the beast that goes downward,`"
although it has caused so much wonder;
and oh! it will come to nought, insidious as it is; strong as it makes itself,
or may yet show itself; for I fear it will spread further, and,
having "`a mouth speaking great things,`" prevail much,
where it is not seen in its own character.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, 1836.

My mind is just now at liberty to enjoy your society,
and for anything of this world that is truly enjoyable;
for although I had a deep baptism about yesterday`'s engagement, the meeting was so good,
the blessed, eternal power of truth was to gloriously in dominion,
that I feel almost like one who was loosened from fetters of iron,
and delivered from the dark dungeon.
Oh! my dear children, there is nothing that gives capacity for knowing, in experience,
the definition of the term felicity, like being wholly devoted to our God and Savior;
to be, to do, or to suffer His will.
His ways are not our ways, nor His thoughts our thoughts.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Seventh Month, 1836.

There really is nothing in this world so precious as the
union granted to redeemed souls with the Lord of glory,
the Spouse of His Church.
Oh!
I know you will subscribe to the truth of all this,
therefore wait upon that power which can enable you to take unto you "`the
whole armour of God,`" that you may be able "`to stand in the evil day,
and having done all, to stand.`"
Stand therefore, having the loins girt about with truth,
and having on the breast-plate of righteousness,
and the feet shod with the preparation of the Gospel of peace.
Above all, taking the shield of faith,
wherewith the fiery darts of the wicked are quenched;
and take (in the eternal power) the helmet of salvation, and the sword of the Spirit,
which is the word of God: praying always, with all prayer and supplication in the Spirit,
and watching thereunto with all perseverance.
Thus, my dear +++_______+++,
may you be put into the blessed capacity to stand fast in the Lord,
as dearly beloved of Him, and in His family!
Oh! I know that, when your heart is tendered by Divine love,
you are aware of the comparative insignificance of every mundane thing:
keep with that which contrites: this is wisdom, Divine wisdom; a fountain of life,
preserving from the snares of death.
Let her not go, but hold her in your right hand.
"`Her ways are ways of pleasantness,`" (true pleasantness) "`and all her paths are peace.`"

Yesterday I avowed my concern to have a meeting at Boxford on First day:
it is in preparation, about seven miles from hence.
Oh! that nothing may dishonor the immutable truth!

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Seventh Month, 1836.

How desirable it is, and how essential to our peace, to commit our way to the Lord,
and that our will should be conformed to His blessed mind!
Much as there may be yet to do in any of us to attain to such a condition,
surely it behooves us to seek earnestly after it, as our only safe state.
Yes, this is the way to have peace in the midst of trouble,
finding the soul anchored in the Eternal Rock.
Life is compared to the ocean or sea, where are many dangers;
but if we have Him abiding with us, who can do all things, though our bark be frail,
He will, in our reliance on Him, conduct us safely through all,
and land us on the shores of uninterrupted repose, and delight ineffable.

What a pity to venture on steering our own course,
by which folly we are sure to be much injured and out of the way!
While I think I could suffer anything for others, still I know that, to be happy,
we must each suffer for ourselves; even enduring the crucifixion of the will,
with the affections and the lusts, that we may no longer live to ourselves,
but to Him who died for us; whom the grave could not hold, but who rose again,
displaying His omnipotence; who remains to be the resurrection and the life,
to all who are willing to be buried with Him, by baptism into death.

The meeting was held at Melford on First day.
It was very large and quiet.
Your dear father says, "`If there can be a good meeting, it was one.`"
I found, in my labour, that no fountain rises higher than its level.
There was not an elevated sense among the people,
of the beauty and splendour of the religion of our Lord Jesus Christ,
and I had to be where they were; yet was it "`a good meeting.`"
I have thought of a village about five miles from Bury, for next First day,
where the sign of "`The Manger`" is attached to a small public house,
and where I believe James Parnell was refused admittance.
I forget the name of the place.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Seventh Month 21st, 1836.

[.salutation]
My Dear Friend,

It is much to be regretted that Elisha Bates is not arrested in his course,
appearing as he does, to wish to pass for a minister among us as a people;
whereas he and his adherents are at complete variance with our principles.
Nothing could be more straight-forward than for the Morning Meeting,
or Meeting for Sufferings, to correspond with America,
and have the great apostate disowned as a member of our Society.
I am grieved beyond what I can describe,
at the apathy which seems to pervade us as a body, while truth is trampled upon,
and laid waste in so great a degree.
We have few indeed, who appear to be so accoutred with the whole armor of light,
as to be valiant in its cause,
and able to stand firm against the attacks of that spirit which has "`a mouth
speaking great things,`" filled with the deceivableness of unrighteousness;
but surely there is a remnant of the true seed,
who will shine forth by and by in the kingdom of their Father,
even as the light which is terrible to darkness, "`as an army with banners.`"
May we not hope that the darkness will flee before it,
and that the language will be produced,
from blessed knowledge of the power which is above every power, "`Thanks be to God,
who always gives us to triumph, through Jesus Christ our Lord!
May we both hope and quietly wait for the period
when this shall be given as a song of victory;
at the same time attending to all the motions of the Divine life,
in our high calling of God in Jesus Christ our Lord.
Farewell my dear friend.

[.signed-section-closing]
I am, in much tender sympathy, your affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Seventh Month 22nd, 1836.

Great has been my exercise of mind lately, in various ways.
I am liberated by my Monthly Meeting, to hold meetings with the people at large.
There is one impending about six miles from hence.
No Friends live near, nor in the other places we have visited.
It is truly awful work, yet hitherto the Lord has helped us.
And is it any wonder that the feet of the messengers should be
turned from those who have persisted in quenching the Spirit,
and despising prophesying,
unto such as are glad in the Gospel being sounded forth to them?

I know not how long this engagement may be filling up,
but you will believe me when I say, that as soon as the motion of life ceases therein,
I shall be glad to resign the work into the immediate hands of Him whose own cause it is,
and not man`'s.

Oh! the unwillingness that judgment should be laid to the line,
and righteousness to the plumb-line, in discriminating between truth and error,
light and darkness! but the Lord will evidence that He is turning His hand upon us;
and I trust that, as a people, it will yet be known that the dross, the tin,
and the reprobate silver, are taken away.
Do, my dear +++_______+++, be encouraged,
in the hope of witnessing the ancient lustre to return upon the gold that has become dim,
and the fine gold that is changed, through corruption and neglect.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Ninth Month, 1836.

The evening Meeting at Halstead was crowded to excess:
I believe as many went away as were in-doors.
We met the people turning back as if the meeting was over, when we were going;
and we could hardly get to the gallery.
All the passages, etc., were quite full, and once more,
I humbly trust the power of the unchangeable, eternal truth did rise into dominion,
to the honor of the Great Name: but oh! it is fearful work in which I am engaged.
I come to nothing in myself through deep baptism,
but the Great Master gives me to be bold as a lion in His cause,
where the people are prepared to receive the truth.
Think what a poor timid creature I am naturally, and adore the all-sufficient One,
who is mouth and wisdom, tongue and utterance, at seasons, beyond all gainsaying.

That at A. was not so large as would have been the case in fine weather.
Many were on their way from Boxford, where we had had a meeting,
and were obliged to turn back, it proved so extremely wet;
but the meeting did tend to my relief.
It seemed to me that the minds of the people were very shallow, and even ignorant,
as to religion; but as more came in, and I endeavored to do as well as I felt able,
things improved; the life of truth seemed to me to reach to the hearts of many,
and I was like a vessel that got off safely with the flowing tide.
I had to offer up thanksgiving and prayer near the close:
the dear creatures assembled attended to my request (as
in other places) to keep solemn on my taking my seat;
and I humbly trust all was well.
The person who let us have the barn was very civil to us:
he also said he did not care if both squire and parson took him to task for it.

I am glad you advised +++_______+++ to employ herself;
anything else is injurious to both mind and body; for, as you say,
it is not the design of Him who has bestowed faculties upon us,
that they should not be used.
I am pleased you have read the life of that great man, yet humble Christian,
William Penn; and more pleased that it interested you so much.
Oh! for our dear young people daring to be right! then we
should soon have a precious revival in our religious Society,
and it would shine forth in ancient lustre and beauty;
the gold that has become dim would resume its true brightness,
and the fine gold that is changed, its original splendour,
to the praise of the great and everlasting Name of Him,
who was magnified over all among our forefathers.

I am not surprised at the intelligence of +++_______+++ and others.
Yes, it is "`all in the confusion,`" as you express it;
the very confusion of "`Mystery Babylon.`"

[.letter-heading]
To the Same.

[.signed-section-context-open]
Sudbury, Ninth Month 21st, 1836.

We had a meeting, as proposed, on First day, at Lavenham.
It was large; very many went away for lack of room, and the place being much crowded,
some at first were not so quiet as could be wished;
but the authority of truth rose higher and higher, until it reigned over all.
I had to stand long; afterwards to kneel; in the close of which Alleluias were sung, yes,
even sung to the Lord God and the Lamb.
I found the people so gathered under the power,
that although the meeting had held more than two hours,
they were by no means glad to be told it was concluded, and separated in a solemn manner.

I was abundantly relieved,
for great and deep had been my conflicts and baptisms previously: yet the peace,
in due season, flows as a river, in fulfilling the Divine will.
It is as the "`pure river of water of life, clear as crystal,
proceeding out of the throne of God and of the Lamb,`" all refreshing and sweet.
It is here that those who follow the Lord Jesus Christ lie down;
even resting by the still waters.

I had not long to enjoy this quiet: this Quarterly Meeting came on,
and its accompanying exercises.
Yesterday I could not hold my peace: was led forth and much enlarged.
Once more it seemed to me that the seed of life everlasting
was set over the heads of all who opposed it,
and the hidden works of dishonesty shown in the light; and the youth invited,
and warned to be separated from all that could keep them from their Savior,
and so destroy their peace.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Ninth Month 21st, 1836.

Oh! there is nothing like living under a sense of our own insufficiency,
and looking to that unction from the Holy One which teaches us all things, and which,
as you observe, is "`truth, and is no lie;`" is,
in other words used by you, "`the unflattering witness.`"
Where you have suffered loss has chiefly been in concluding too hastily or readily,
that others were as ingenuous as yourself,
and so trusting their professions beyond what they deserved.
This has brought you into trouble again and again,
but the gracious eye of Israel`'s Shepherd has watched over you;
He has reached forth the crook of His judgments, and raised the voice of His love,
and I believe has not had to deal with one willfully wandering; one whom, I humbly hope,
He yet cares for in the sheepfold, and whom He will feed in the pastures of life,
making strong for Himself.

Your tender and humble expressions put me in mind
of what the children of Israel were given to understand,
when Moses addressed them in the language,
"`Behold I set before you this day a blessing and a curse:
a blessing if you obey the commandments of the Lord your God,
and a curse if you will not obey the commandments of the Lord your God,
but turn aside out of the way.`"

I humbly trust the first will indeed be your happy experience,
and I would have you thank the Author of all blessing, as I know is your desire,
and take courage; committing your way to Him your Savior, who will direct your paths,
in the eye being turned to Him; yes,
He will guide you by His counsel through every intricacy in life,
and afterwards receive you into glory.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Ninth Month 30th, 1836.

Just now I recal to mind that Christopher Healy, from America,
told us in the Select Yearly Meeting, in a very impressive manner,
to "`let nothing move us from our steadfastness in Christ Jesus.`"
And oh! my loved +++_______+++, instead of anything moving you,
may your steadfastness increase! for surely "`flesh and blood has not
revealed to you`" that to which you make so full an acknowledgment,
but our Father who is in heaven; and who, I trust,
designs to accomplish His own work in you.
He has already brought you through many painful feelings,
like the furnace being heated to try and refine, and now He would choose you.
Be faithful to every manifestation of His will, who would thoroughly sanctify, yes,
who would dignify with the blessed gifts and graces of His Holy Spirit.
I have often thought that you have been privileged in having dear, affectionate +++_______+++,
with you in your conflicts;
and may you be bound up together in the Divine life and love everlasting.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 30th, 1836.

How brotherly it is of you to remember my dear J. G. and self,
among those who continue to feel interested in knowing how
the Yearly Meeting`'s Committee fared in the late combat!
Yes, it is a warfare to those who wish to be found having their loins girt about with truth;
and indeed they find the necessity of taking to them
the whole armour of Him who is light,
and in whom is no darkness at all.
Such as these, deputed by the Society in the important business alluded to,
must have proved that they had to "`wrestle not against flesh and blood,
but against principalities, against powers,
against the rulers of the darkness of this world,
against spiritual wickedness in high places.`"
We have not heard if all attended who were under appointment,
nor if all were of one mind and of one heart; but if this is happily the case,
I am persuaded a great work must have been effected in some individuals of your number,
since your last visit to Lancashire, and this change is more than I dare hope,
as relates to many;
but surely the great Head of the Church does evidence
that He is not unmindful of the labour of love,
as it regards those who, in integrity, have done what they could.
Nevertheless it is a grievous thing and bitter,
that so much weakness and indecision should pervade us as a community;
that even those who have, for years, shown themselves not of us,
but have gone into things, which it cost the sons of the morning of our day,
their liberty, their property, their health, yes, sometimes even life itself,
to testify against, are still retained members of our Society.
Where is the ancient zeal for "`clearing the truth before the eyes of the people?`"

We have held a good many meetings in the country, mostly occupying barns for this purpose.
Sometimes these have been as much as a mile from any village,
but the people have shown great readiness to come.
I think it may be said that in each of them the power of the Lord had the dominion,
sooner or later;
and although many of the poor dear people were wholly unacquainted with Friends`' meetings,
they behaved very becomingly.
Oh! the love that overflowed towards those who assembled!
I have thought I could be willing to suffer with and for them, could it avail,
or could it raise their minds at all up to Him,
who would have all to come to the knowledge of Himself, and be saved.

Alas! for and a few more, once enlightened;
for they will not see from where they have fallen.
Oh! my poor heart seems sometimes almost agonized, in thinking of some;
but let me look well to myself, for I know there is need.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Tenth Month 5th, 1836.

Oh! the darkness that must have taken the place of light,
with poor Elisha Bates and a few more!
It is truly awful.
Yes, I should like, with you,
that his own conviction of the inutility of ceremonial performances
in religion should be placed before him,
and the pure views he has expressed in his "`Doctrines.`"

How truly lamentable are these things!
Your letter, received this morning, has excited fresh,
or rather increased sympathy with you.
Remember what George Fox says--"`Are you in darkness, heed it not,
or it will increase upon you;
but wait in that which brings up into the light,`" or to this effect.

May you be established upon that Eternal Rock and Foundation,
against which all the combined powers of darkness can never prevail!
Mutable as is this world, and strong its temptations,
as are those of the flesh and the evil one, grace divine is stronger than all.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Sudbury, Tenth Month 18th, 1836.

You will be pleased to know that the Quarterly Meeting at +++_______+++ was memorable,
for the Lord`'s power, and His immutable truth, were set over all opposition;
and yet individuals are just in the same confusion they have long loved;
professing and recommending charity, while out of its spirit;
and seeking to unite light and darkness, yes, Christ and Belial.
They must be let alone, as to any conference with them now; there remains no room.
Our Monthly Meeting at Bury was favored with life,
in a renewed invitation to the different states present.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Tenth Month 26th, 1836.

It would be sad to me, could you suppose your old friend had forgotten you and yours.
No, I still continue to feel an affectionate and religious solicitude in your welfare;
and much do I desire that each of you may be laying
up a good foundation against the time to come;
that so, when nothing will stand any in stead but an interest in the Lord of glory,
He may be found "`a covert from heat and from storm,
a hiding-place in the day of trouble; as rivers of waters in a dry place,
and the shadow of a great rock in a weary land.`"

Since the Yearly Meeting I have had to endure much affliction of body,
and inexpressible exercise of mind; for several things have pressed me down,
so that I frequently remembered the expressions, "`pressed out of measure,`" etc.;
but still,
when it has pleased the Lord to make way for me to
lay down the burden of the word of life in meetings,
either among my own people or others, my spirit has been eased;
and for a little while I have found what it is to "`mount upward with wings as eagles;
to run and not be weary,`" etc.

Oh! it is indeed a day in which we must,
at least ought to be willing to mourn and lament in secret for the desolations,
and even abominations that there are within our borders as a people; the scattering,
the outgoing on every hand; and, what appears to me worst of all,
the disposition of some to temporize still,
and shake hands with that which should be testified against, for the clearing of truth,
and yet would also make a fair show as to maintaining the principles of Friends.
Surely such a spirit holds the truth in unrighteousness; and, for self-reputation,
there is dissembling; but it must all be searched out,
for the controversy of the Most High is with everything that cannot bear the light;
and I do believe that when we are thoroughly sifted and cleansed from the chaff,
it will be seen that "`not one grain is fallen to the earth;`"
and all will redound to the honor of His Name,
who remains to be the strength and salvation of His people;
and He will evidence that they are "`a people near to Him, the Lord.`"

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Twelfth Month 2nd, 1836.

From the improvements in navigation, and other circumstances,
I have often been impressed with the idea of the nations of the
world being brought into more intimate acquaintance with each other,
and, as it were, blending their interests; so that possibly, one day,
mankind may become more fully sensible of what it is to be one family.
And oh! how nice the thought of being one fold, and having one Shepherd!
Ah! this would make the globe a paradise;
and I believe men would not have to contend with conflicting elements then,
and that there would be nothing hurtful nor destructive.
But I had no intention of writing thus when I began,
but to encourage you to be very inward with that which (you
well know) is alone able to preserve you on every hand.
I humbly trust your sincerity in the Divine sight will be accepted, so that,
as you are watchful every moment, nothing will be able to influence your dear,
tender mind, to your hurt.

My heart commends you to the care of Israel`'s Shepherd.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Lexden, Twelfth Month 29th, 1836.

My spirit is made measurably glad in the persuasion confirmed,
that the Lord is with His people;
that He will "`turn their captivity;`" that "`Jacob shall rejoice,
and Israel shall be glad,`" even in that which His own holy, omnipotent hand creates.
Oh! now I trust some of us, who have seen many days, and much vicissitude,
may lift up the head in hope,
as regards the people (whom I think I feel near to Him) from whom
so many of us have nevertheless most grievously departed,
that the time will come, when the language of the prophet shall be fulfilled, where,
speaking not his own words, he says,
"`You shall be a crown of glory in the hand of the Lord,
and a royal diadem in the hand of your God,`" etc.
Since the text occurred to me, I have looked for it.
Only think what blessings are pronounced upon the true Church,
in its visible and gathered state among men.
Read the sixty-second chapter of Isaiah.
Surely the least of the family, the abased ones, who are made willing to own their Lord,
when in the character of a man "`of no reputation,`" may
"`thank God and take courage,`" as dear +++_______+++ said.

It was much my desire, in your company, that, in the dignity of the truth unchangeable,
you may each stand with increased strength, against all that shows itself,
or may yet be discovered, as out of the precious unity, held in the life, in the light,
in the love everlasting.
May I say, that really it was my humble belief, while with you, that,
in waiting upon the Lord, you are individually made to partake, at times,
of His gracious promise to such,
even to "`mount upward with wings as eagles;`" rising above depressing thoughts;
finding the soul in the high rock, that is out of the reach of the troubled sea.
Here is the secure hiding-place,
known to those who are given up to suffer for Jesus Christ`'s sake.
So in Him, my dear friends, I bid you farewell.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Second Month 20th, 1837.

Thinking that you would wish to have some intelligence of us after the journey to Bardfield,
I take the pen today.
I am thankful to say that the meeting (though very close and warm,
being much crowded) was an open, good time.
The Lord`'s power did seem to be over us:
great attention was manifested to what was delivered,
and we separated under a lively sense of Divine goodness.
It was half-past ten when we got home; a very moonlight night;
and when the people were dispersing and going home, the rain had ceased:
afterwards it came on again.

I shall continue to bear you and my dear +++_______+++ upon my heart,
as our Almighty Helper may enable me; that I may travail for you,
desiring your preservation and furtherance in the way so
clearly cast up before each of you--a high and holy way,
raised above the willings and runnings of the natural man,
and in which the mind is sensible of a holy indifference to both
the frowns and the laugh of this vain and delusive world;
accounting it true honor to suffer shame, and even be persecuted for Christ`'s sake,
who promised that those who left what was dear to them for His sake and the Gospel`'s,
should receive a hundred-fold of the comforts afforded in time, with persecutions,
and in the world to come, life everlasting.

I was concerned to hear that +++_______+++ was going to take his family to London.
They may possibly receive a little more money,
but I fear their temptations will be much increased,
and the inducements strengthened to barter the well-being of the soul,
and all the best interests, for the sake of this present world.

Should they not be gone, tell them that, in the love of God,
I charge them to live in His fear; for "`the fear of the Lord is a fountain of life,
preserving from the snares of death.`"
If they value true happiness for themselves and their poor dear little ones,
they will seek the approbation of Him who can bless a little that a man has,
and blast a great deal.
I cannot but feel much about them.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Second Month 21st, 1837.

I have wished once more to send you a line expressive of my remembrance,
and also of my sympathy in the late chasms which
have been permitted to be made in your circle.
Poor dear Ann Cruikshank and Rebecca Christy being
snatched away from all they held dear in this world!
Yet these are not times to lament the safe departure of our friends;
let us rather take the injunction formerly given, "`Weep not for the dead,
but weep sore for him that goes away;`" and it is to be feared the annexed will apply,
with reference to some taken captive in our day, "`for he shall return no more,
nor see his native country.`"

I suppose dear Alexander Cruikshank bears this severing stroke with christian resignation,
in the full persuasion that the Judge of all the earth does right.
I fancy him saying amen, under the dispensation,
and maintaining that meekness and quietness of mind which
so peculiarly distinguishes him in his walk through life.
I feel much for Thomas Christy in his bereavement.
Dear man! how solitary he must feel!
It was a comfort to me to hear of his late loved companion expressing
herself as having a clear prospect in the awful hour of separation,
and of the testimony she bore to the evil effects
of a too ardent pursuit after the things of time.

How many around us have been summoned of late to give in
the account of what they have done with their talents!
I do not remember the like.
We are every few days hearing of some in our religious community, about to be interred;
and our fellow-mortals at large, how are they swept away!
The prevailing epidemic has been an awful visitation, sent, no doubt,
as the rod of correction,
for the great departure of heart which too generally
has caused that good to be withheld from us,
which an all-beneficent Creator designs for us, as we love Him entirely.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Third Month 11th, 1837.

Tomorrow we think of going to Colne, to hold an evening meeting with the people at large.
Perhaps, when that is accomplished, I can more clearly discover about Coggeshall;
but I am persuaded that all my own mere striving to know what is right avails nothing,
so I only lend an ear and eye to the guidance which
does not fail to attend the watchful soul.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Near Ipswich, Third Month 20th, 1837.

[.salutation]
My Dear Friend,

It is no easy matter to learn the lesson of being "`careful for nothing,
but in everything, by prayer and supplication,
making the requests known unto God;`" or leaving all to
Him in waiting for resignation under every trial.

I observe your concern respecting our present condition,
amidst the conflict and solicitude felt in consequence of your sister`'s severe illness.
It is truly painful to witness those we tenderly love, sinking under disease:
these things are, however, attendant on a probationary state of being,
and no doubt the righteous find that forever, as their joyous portion,
which makes life worth living, with all its sufferings, in every shape,
dispensed by Him who "`afflicts not willingly,
nor grieves the children of men,`" but sends just
what we need to fit us for union with Himself.
What a mercy that all things, without exclusion,
"`work together for good to them that love God.`"
Let us then, in the ability vouchsafed, however small, gird up the loins of our minds,
and "`hope to the end.`"

As regards the sad schism within our borders,
I trust that which openly and vauntingly declared itself against the principles of Friends,
has already begun to wax feeble;
but what is to be done with that spirit that is still temporizing,
and standing between the decision of truth,
and that which seems to expect to be made perfect in the letter,
after having known what it was to begin the great work of salvation in the spirit?
I cannot think that this middle rank will be able
to escape the scrutinizing power of that living word,
which is quick and powerful; sharper than any two-edged sword;
dividing asunder even with such accurate discrimination,
that it is compared to separating between the joints and the marrow.

I was at the last Quarterly Meeting in London, and enabled to clear my mind once more,
both in the Select Meeting, and that at large.
It seemed to me, that although something had been done, in a Society capacity,
to put down that which defies the armies of Israel,
yet that "`the best of the sheep and the oxen`" were reserved;
and there was Agag in his gorgeous attire, saying,
"`Surely the bitterness of death is past.`"
And although my soul heard the pleading, "`Yes,
we have fulfilled the Lord`'s command,`" yet had I to declare that
my inward ear was assailed with "`the bleating of the sheep,
and the lowing of the oxen;`" and to say, "`What does it mean?`"
I do not know how far I may be excused being at their next,
but I am not allowed to be much at rest, as in my ceiled house.
I was last week at Essex Quarterly Meeting--have
held a great many meetings with the people at large,
in that county and this.
A very great one was here last evening,
which was to me a time of renewal of strength indeed,
and wherein the immutable truth was largely and powerfully declared.
Oh! the seed immortal did reign,
to the glory of Him who told His disciples that they could do nothing without Him.
I am here to attend our Quarterly Meeting tomorrow.
My dear husband is not with me, being very feeble and dimsighted;
but I trust the inner man is renewed,
and that his spiritual faculties are clear and vigorous.

[.signed-section-closing]
I am your affectionate friend,

[.signed-section-signature]
Sarah Grubb.
