== Chapter 22. Letters from 1840--1841

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Sixth Month 10th, 1840.

Your great city is indeed a place which occasions my poor mind much deep exercise.
I have, however, resigned the Minute granted by my Monthly Meeting,
believing the way to do so opened with clearness.
At present I am without anything of this kind liberating me for religious engagements,
yet is it my desire to have the inward eye to our unerring Guide;
even "`as the eye of the servant is to his master,
and the eye of the handmaiden to her mistress,`" that the
mercy of the Most High may be still made known;
for oh! what should I do but for it?

We met my loved partner in life quite as well as when I left him.
It is, however, very affecting to see him so helpless, and his sight nearly gone,
but I believe that the "`inner man is still renewed day by day;`" and if I may be permitted
to see him in his everlasting mansion before my own departure from hence,
I think my poor spirit could give thanks in his being spared the bereaving stroke,
under which he would be likely to suffer beyond description;
but my heart subscribes to the language,
"`Your will be done;`" for our Heavenly Father is consummate wisdom,
as well as omnipotent; and He is pitiful to His poor children who fear Him.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sixth Month 16th, 1840.

Do tell me how it is with you, for I am sensible of tender solicitude about you,
beyond what I can put into words.
May the Shepherd of Israel be your keeper.
He sleeps not by day, neither does He slumber by night; so that,
if you love Him perfectly, your heart may confide humbly in His protecting arm.
Oh! how has He loved you!
This has been evidenced in His not permitting you to take your case,
but suffering your attention to be aroused, from time to time, to the language,
"`This is not your rest;`" even showing how vain
it is to seek any fixed repose in what earth affords.

Well, my dear +++_______+++,
may all the dispensations of unerring Wisdom be blessed in your experience;
inducing or inciting you to set your affections on
those things that are of eternal duration,
and soul-satisfying.
Thus may you be prepared more fully for the service of our Divine Master,
before your energies begin to weaken, or the meridian of your day pass.

Dear William Hull "`passed quietly away,`" his son tells me,
in a letter giving the intelligence of his removal.
He was one who kept the faith, who fought the good fight, and, I believe,
has won the crown of everlasting righteousness, through adorable mercy.

Farewell, my loved +++_______+++, and believe that I bear you on my heart.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sixth Month, 1840.

The true leadings of Christ are gentle, and the sure voice is heard in the stillness:
then, however small it may be, there is safety in attending thereto,
and in being guided by it.
We are not to mind the great and strong wind, nor the earthquake, nor the fire,
but to let them all pass by, because the Lord is in none of them.
Oh! may each come to the experience of what it is to be broken, even thoroughly so,
that they may be "`built up in the most holy faith;`" that faith by which
victory is obtained over the potent enemies of man`'s felicity.
Farewell, my dear brother, in the Lord.
I believe He is near you, and that His everlasting arms are underneath,
however imperceptible to yourself.
Then fear not the waves that sometimes seem ready to swallow you up,
but look to Him who "`is mightier than the noise of many waters.`"

[.letter-heading]
To J. H.

[.signed-section-context-open]
Sudbury, Sixth Month 23rd, I840.

[.salutation]
My Dear Afflicted Friend,

Although my way did not open to mingle personally with you last sixth day,
on the mournful occasion of committing to the grave the remains of your dear husband,
I was nevertheless much present in mind.
The removal of my dear and long known friend was no surprise to me,
after the very poor accounts which repeatedly reached us; and indeed,
when my lot was cast among you some months back, his race seemed nearly run:
what a mercy that he was enabled to _pursue_ it in his day, through many difficulties;
being one who held out to the end!
How glorious a prize is won!
It was grateful to me to learn that your dear partner was _gently_ let down,
as the letter mentioned "`he passed quietly away;`" and while the
bereavement must leave a chasm which nothing earthly can fill,
yet is there much to mitigate the sorrowful feelings of your heart,
and that of your family,
who are capable of reflecting on the happy exchange from a life of anxiety and of groaning,
in the earthly, worn-down tabernacle of clay, to a mansion of eternal rest and peace.
As for yourself,
I trust that He who has vouchsafed the Angel of His presence unto you all your life long,
as unto one who feared Him, will not now leave you,
but continue to uphold your spirit by the right arm of His power,
and in His matchless love, lead you on to an inheritance incorruptible,
and that fades not away; even as a kindred spirit with the dear departed.
You (as well as he) have passed through much tribulation, and I do believe that,
in each case, the robes are washed and made white in the blood of the Lamb; so that,
however unworthy in your own estimation,
I do hope you will be prepared to walk with Him in white forever and ever.

You have some dear children who are precious in the sight of Him who sees not as man sees.
May you be mutually a comfort to one another, and remember, in every trial,
that although sorrow shall endure for a night, yet joy comes in the morning;
that the darkness and the light are both alike to our covenant-keeping God.
I have not improved in health since coming home.
I humbly hope that the decay of the poor frame will have the effect of inciting to diligence,
as to preparation to meet the awful summons to come
before that tribunal from which there is no appeal.
Farewell, my long-loved sister.
May we each be mercifully favored to hear the sentence at last, of "`Well done,
good and faithful servant; enter into the joy of your Lord.`"

[.signed-section-closing]
I remain your sincere and sympathizing friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Seventh Month 31st, 1840.

Could you know of my low, suffering state,
it would suffice as to the _seeming_ forgetfulness of one so near and dear to my best life;
although _this_ life has been, and still is, much hidden from myself;
for many are the suggestions of the adversary of all true peace, which, if listened to,
would occasion shipwreck of faith.
It is not safe to lend an ear to any _strange_ voice therefore,
for we are unacquainted with it.
We have endeavored to hear Him whom we _love;_
whose voice is sweeter than any music on earth (even the softest and most fascinating)
and whose "`countenance is comely,`" surpassing that of any of the children of men,
although these are His workmanship.
Ah! my dear friend, when there seems to be a _dense cloud_ between our soul`'s Beloved,
and our prayers and sighs to Him, let us not say in our hearts,
"`The Lord has forsaken me, and my Lord has forgotten me.`"
Let us not thus lean to our own understanding, but trust in His mercy and providence,
who leads His children in paths they have not seen, and in ways they know not;
for they are as the _blind,_ yet servants of the Lord; and they are _deaf,_
yet are His messengers.
It will not do for such, even for ambassadors of the Prince of life, to have to say,
"`I see,`" except with the anointed eye;
or "`I hear,`" unless as the ear is "`wakened to
hear as the learned`" in Christ`'s school,
which is no easy thing to our nature.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Eighth Month 3rd, 1840.

[.salutation]
My Dear Friend,

Yours of the thirteenth of last month
was the earliest intimation received here,
of the escape from all "`the evil to come,`" of that singularly devoted,
chosen servant of the Lord, Daniel Wheeler,
whose course was marked with trials of no common weight in the scale of human suffering;
yet how like Job was the bent of his mind! for _he_ was prepared to adopt a language,
at once ascribing righteousness, and wisdom, and praise to the Most High.
"`The Lord gave, and the Lord has taken away; blessed be the name of the Lord.`"
Thus this great and good man "`kept the faith,
fought a good fight;`" passing on through a world of probation,
_finishing his course in the fulness of time,_
and has won a crown which eclipses the splendour of the richest earthly diadem,
and which shall never, never fade away.
Oh! how delightful is the thought of such glory!
Words would fail in the attempt to set it forth,
and it is too dazzling for us to behold in all its refulgence,
while inhabiting these decaying tabernacles;
yet is there an evidence indubitable accompanying the new,
"`seen through a glass darkly.`"
You will unite with me in the confession,
that even this sight is frequently veiled from us: yes,
even our prayers (at times) seem not to penetrate
the thick cloud with which the poor mind is covered.
It is for us to bow low, under a sense of our own helplessness, and wait on;
for "`Have _you_ commanded the morning since your days,
and caused the dayspring to know his place?`"
The "`faithful Creator,`" the mighty God, is known,
to those whose eye is singly and constantly turned to Him,
to keep His covenant with the night as with the day;
for the darkness and the light are both alike to Him.

My love is to your dear +++_______+++, and your precious little flock.

May the blessing attached to the persevering soul be yours; and to the dear young man,
your assistant, I desire to be kindly remembered;
and to each of the circle in your family, whom I have seen and felt interested about.
To them that "`_follow on_ to know the Lord, His going forth is prepared as the morning;
and He shall come unto them as the rain, as the latter and former rain unto the earth.`"

You, my dear and _truly disinterested_ medical friend,
will almost naturally look for some account of the state of my health.
I fancy the nervous system is weak and irritable,
but I seek after "`a meek and quiet spirit,`" _so high in its value._
I am able to assume cheerfulness in demeanour, for which my mind feels truly thankful.

[.signed-section-closing]
I remain your sincerely affectionate and obliged friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Eighth Month, 1840.

Give my dear love to J. H., and say I do not forget her and hers.
She has a variety of sorrow, but I trust all will be turned into joy by and by.
She is stepping on toward the end of her race; sometimes far from _lightly,_
but looking to Him who "`gives power to the faint,`"
and "`increases strength to them that have no might.`"

Our united love awaits you,
my +++_______+++. Your mother prays that every trying feeling may be sanctified in your experience,
and tend to bring you nearer and still nearer in spirit,
to Him who is the "`chiefest among ten thousand.`"
Look for the text quoted to you years ago, "`I will allure her,`" etc.
Your dear father says he has prayed for you, if he knows anything of prayer: indeed,
my dear,
he need not have put in that _"`if`"_ for his heart
is sensible of aspirations to the Most High,
on behalf of himself and others.
We had rather an extraordinary afternoon meeting yesterday:
your dear father was strengthened to kneel.
It seemed to have the effect of bringing solemnity over us.

[.letter-heading]
To J. H.

[.signed-section-context-open]
Sudbury, Eighth Month 30th, 1840.

[.salutation]
My Very Dear Friend,

Your sending me a _written_ testimonial of your remembrance was more than I could look for,
under the pressure of sorrow which at present is your portion;
and while the acknowledgment is made to Divine support under accumulated trial,
I can believe you feel often as if the furnace was heated beyond past experience;
but surely He who suffered for us in a body of flesh, goes before His _afflicted,_
yet _chosen_ ones, even while these are _in_ the ordeal:
as we read of the three faithful ones in the midst of the fire,
"`the form of the fourth is like the Son of God,`" so they were unhurt; yes, more,
they lost the bands which were upon them before, or when cast in:
thus was the arm of Omnipotence magnified _through_ His poor helpless children,
as _well_ as _in_ them.
It is in my heart to say to you,
"`Fear not,`" for I do believe that the promise is to you,
"`The flames shall not kindle upon you,`" neither shall the floods drown you.
Why? Because God has said, _"`You are mine;`"_ and, "`I am the Lord your God,
the Holy One of Israel, your Savior.`"
Surely His redeeming, preserving power has already done much for you:
you have good ground for hoping that, having been kept,
and in due time delivered by the Almighty Hand,
as "`in six troubles,`" the same all-sufficiency will yet be known;
your eye being in the same waiting state for the "`mercies that are new
every morning,`" coming from Him whose "`faithfulness is great.`"
It seems to me that the savor of your spirit is sweet and clean.
I am ready to say, she is more what I _wish_ to be, than what I _am._

Dear, dear R. F.! we ask, in submission of our will,
that she may be spared to all around her;
while yet we do not forget _that_ teaching word of our dear and holy Master,
"`You know not what you ask.`"
Oh! the deep baptisms the Lord`'s precious ones have to pass through!
Oh! the bitter cup they have to drink of,
as years revolve! and to be enabled to _continue_ with
Christ through all temptation or proving,
is indeed that which sorely tries the faith, and exercises the patience:
but it is not suffering _alone,_ which Infinite Wisdom dispenses to His own;
their consolations abound likewise; and I fully believe that the truly dedicated,
lowly followers of the crucified Immanuel, would not barter their privileges, and peace,
and rest in the soul`'s Beloved, for all the ease, the fleshly indulgence,
the transient joy and gratification of such as seek their "`good things`" in this life,
too regardless of pursuing the "`one thing needful.`"

I feel yearnings towards your children, even in that (I trust) which outlives all sorrow,
and all temptation.
In this feeling salute the partner of dear +++_______+++`'s life,
and say that I have a little hope he not only reveres the innocent life of his Redeemer,
but desires to cherish it in himself.
May he _grow_ in grace, and in saving knowledge!
Your longed for sons and daughters
are far from being forgotten by me;
some of whom are _clear-sighted_ individuals,
who are being prepared to be skillful in lamentation in this sad day.

The rejecting of the Lord`'s commandments must be punished, that it may be made manifest,
"`to obey is better than sacrifice; and to hearken, than the fat of rams.`"
Oh! the pleadings of human wisdom that I fear are still with us as a Society!
Oh! the gorgeous array which takes the place of the true glory!
For Israel`'s King is _higher_ than Agag, "`and _His_ kingdom shall be exalted.`"

My love to +++_______+++ and +++_______+++.
I believe affliction has been sanctified in that quarter,
and I trust the raiment of wrought gold will yet more appear; all dross, all tin,
all reprobate silver purged away; and the work of that hand conspicuous, which engraves,
"`Holiness to the Lord,`" and, "`the Lord our righteousness.`"

Farewell, sister beloved, in Him who pities those who fear Him;
who "`remembers that we are dust.`"

[.signed-section-closing]
Your sympathizing friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ninth Month 4th, 1840.

If we should mark out for ourselves a line in which to move for the honor of truth,
we then interfere with the work of Infinite Wisdom; yes, we mar this work.

May +++_______+++ be strengthened to submit the whole man to _His_ hand,
who condescended to wash the feet of His disciples, and who, when poor Peter said,
"`Lord, You shall never wash my feet,`" made this awful reply, "`If I wash you not,
you have no part with me;`" how quickly then did this man respond, "`Lord,
not my _feet_ only,
but also my hands and my head;`" and how instructive that which still followed,
"`He that is washed needs not, save to wash his feet, but is clean every whit.`"
Thus, if a merciful Savior and Guide do but take from us that which we may contract,
in our walk among men, and give us to walk more in His blessed company,
the invitation is louder, "`Follow me, as you see I follow Christ.`"

My mind is often led to visit mentally many parts of our fold as a people,
and earnestly do I desire that our tender lambs may
not be induced to gather where there is not safety;
and to pray that the arms of the Good Shepherd may
be extended and opened to them for their preservation.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 14th, 1840.

I am glad that it is given you and yours to refer
the preservation of your son through so many dangers,
to Him who takes cognizance of His creature, man, every moment;
and who follows him with love and mercy, yes, with _chastisement,_ in this _love,_
and in this _mercy,_ all the day of visitation, for complete redemption from sin,
and the corruptions of the world.
How often has my poor heart sighed after +++_______+++, in his peregrinations far off;
desiring the care and protection of the Great Shepherd for him,
not more on account of his traversing different climes,
and so being subjected to outward dangers and difficulties in _person,_
than on account of the mind being often in peril many ways.
Surely now, should this dear youth give himself wholly to follow Christ,
he will be prepared to exclaim, "`Oh! that men would praise the Lord for His goodness,
and for His wonderful works to the children of men.`"
What is life without (in effect) speaking such a language?
for we cannot otherwise answer the end of our existence on the earth.
_This_ state of being is soon at an end, with all that can be enjoyed or acquired,
of a transitory nature;
therefore to live here without glorifying the great
Creator with the body and with the spirit,
is to render life a mere bubble, and to have no well-grounded hope of eternal,
soul-satisfying delight.

I am much as usual in health; have symptoms of a decaying tabernacle;
sometimes humbly hoping for the assurance,
"`that when the earthly house of this tabernacle
shall be dissolved,`" a building in the heavens,
which is of eternal duration, may be prepared by the Divine Hand,
for even such a one as myself.
Thomas Shillitoe said,
"`I am going to a good home "`--"`all in mercy "`--"`no merit of mine.`"

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ninth Month 22nd, 1840.

May Heavenly Goodness grant you more and more of that which
is declared to be of great price in His sight,
who sees not as man sees, even a "`meek and quiet spirit.`"
There is no situation in life, in which we can realize the _comfort,_
the joy of temporal good, without this inward regulating of the Divine principle;
and thus it is that "`the meek shall inherit the earth.`"

The votaries of this world may possess _all_ that earth affords,
but be devoid of the capacity to _use_ and not _abuse,_
the providence of Him who is Sovereign of the universe.
But I write not these things to you, my loved +++_______+++, because you know them not,
only that your best resolves may be strengthened,
and that you may be encouraged to confess your blessed Master nobly, who said,
"`Learn of Me, for I am meek and lowly in heart.`"

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Ninth Month, 1840.

Now my loved +++_______+++, our Quarterly Meeting has closed.
I have remembered dear Samuel Emlen`'s saying, when visiting families in London,
"`The Thames has not been set on fire _today._`"
_We_ have no authority for acknowledging to the _marvelous_ display of Divine power,
and that the fire from above "`licked up all the water of Baal`'s
worshippers,`" yet were we not left _quite_ without the Holy Spirit;
its quickening virtue was felt.
In the meeting preceding that for discipline there was long silence.
+++_______+++ kneeled--another pause--then your mother stood, beginning with,
"`Friends, the Lord _will_ have a _lowly_ people.`"
I was led on, with tender expostulation,
and with a call to come home to the heavenly gift, the _lowly_ life;
to follow Him who took not upon Him the nature of angels, nor the splendour of princes,
but who appeared in this world in "`the form of a servant;`" who said,
"`The foxes have holes, and the birds of the air have nests,
but the Son of man has not where to lay His head.`"

We have had a larger meeting here this morning than I have seen,
except on some extraordinary occasion:
it appeared to me to be an extraordinary time in the _best sense._
We have before felt the celestial showers here, and as yet but little fruit.
When the Lord of the vineyard will command the clouds
to rain no more rain upon this part of it,
I cannot say, but really it is lamentable to see our present condition.

Have you seen the [.book-title]#Memoirs of Susan Huntingdon,# an American?
I have just read it.
What a remarkable woman! highly talented, and possessing vital religion,
which was her balm in afflictions of a very poignant character,
and which pursued her path through life in an uncommon manner.
After all, how soon her race was run!
It seemed a pity that this dear servant of Christ had not an apostle among her people,
who could show her the more excellent way than that of adhering to types and shadows.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 23rd, 1840.

Such as live the nearest to our Great Master are
not distinguished by exemption from suffering,
or from being subject to humiliating dispensations, but, by Divine support,
and in due time, there comes deliverance,
that the life of Jesus may be made manifest in their mortal flesh, _more and more;_
and that all things appertaining to these, His followers,
may redound to the glory of His own excellent name.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Ninth Month 28th, 1840.

Although there seems little new to communicate, I wish to assure you, in this way,
of my continued, daily remembrance,
with unabated tender interest in all that concerns you.
Truly, more often than the morning,
is my heart raised to the Father of mercies on your behalf,
that He may fit you for His service,
and engage the prime of your life therein to His glory.

Many have been your sore trials, and deep your baptisms already:
oh! that the great end hereof might be fully answered;
for it is not _exclusively_ as regards yourself,
that the great work of redemption and salvation should be accomplished,
but that this necessary work should, through you, be promoted in your fellow-mortals.
I know that you are a good deal tied to business, but with a mind like yours,
by no means grovelling,
and a spirit far removed from what may be called "`money-getting,`" I can scarcely
conclude your engagements are likely to produce an injurious effect.
I once heard of a Friend saying of a person obliged to use great industry,
that there was, through all, sweet incense ascending to the throne of glory,
from the heart of that individual.
Be encouraged, my dear +++_______+++, to hope for the same heavenly-mindedness.

And now I seem to be come to the end of my little fund for writing,
except dear love to you.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Ninth Month, 1840.

Your letter received yesterday, gratifies us much.
How glad will your mother be to see you again in the fulness of time!
Ah! my dear,
did I not tell you I saw the gorgeously attired Agag coming forth among us,
with the language, "`Surely the bitterness of death is past?`"
and so it seems; for what else mean the eloquence, the mouth which utters fine things;
things pleasing to the natural ear, but void of the _life,_ the _power,_ the _demonstration,_
which is of the _spirit,_ not the _mere letter?_
"`With stammering lips, and _another_ tongue,
will He speak to this people;`" so _dwell deep in your spirit,_
that you may discern between that which serves God, and that which serves Him not;
and when that which is out of the Divine life gives you pain, _bear it;_ and He,
the rich Rewarder, will reward your patience,
and grant you more and more of the heavenly anointing, which teaches,
so that we may "`know all things.`"

So you attended the Quarterly Meeting at +++_______+++.
Dear +++_______+++! I should be glad of some of her company.
Ah! how few there are who can say to the great, the learned, the wise,
the noble among men, "`We have not _so_ learned Christ;`" for it is common, ah! too common,
to try to learn Him, without learning _of_ Him; for He says,
"`I am meek and lowly in heart.`"
Now, as this meekness and lowliness is the groundwork of all true religion,
does it not behoove us to submit to the experience
of "`the axe`" being "`laid to the _root_ of the tree?`"
that, as in the fallen nature, we cherish pride,
and are repugnant to that which annihilates _self,_
the heart being prepared for the growth of the true
seed or "`root,`" our "`fruit`" may be "`unto holiness,
and the end everlasting life.`"
This likewise produces peace to all those who seek peace, and pursue it,
in a way to find it; even in humble acquiescence with the Divine will.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Sudbury, Ninth Month, 1840.

I look to that protection for you every way, which, without presumption,
I humbly may style, "`the Rock of my salvation,`" hitherto.
You do not need to be told that we dearly love you.
May we look from all _created_ things, for true and settled comfort or peace,
even to the _uncreated_ power in which our consolation and strength is to be found!

In my walk this forenoon, on the Cornard Road, I saw a poor worm.
It lay in the path, exposed to the foot of man.
It seemed to be my brother or sister; for oh!
I thought, _how like myself,_ a worm of the dust, just in the way to be trodden on!
I will put you in a place of safety: so I removed it; and, rather unexpectedly,
found there was _life_ in it, though it looked battered, and almost covered with dust.

I do not wonder that the First day Morning Meeting wearied you.
I am confirmed in my judgment, long since formed, that +++[+++some among us]
are Episcopalians, not Quakers.

Your views, my dear,
are correct (I will venture to assert this _without the shadow
of a doubt_) as to the appointed means of our salvation.
Would it not be derogating from the character of the Creator,
to conclude that _He made man sinful?_
He who pronounced all His works "`good,`" "`very good;`" He who is goodness itself!
He who is perfection itself!--yes, my daughter, it would.
But, seeing that our first parents fell from that happy and dignified state,
in which they were formed by the Divine Hand, they entailed upon their offspring,
_not sin,_ but the _propensity_ to sin: this propensity, as yet, is not wholly overcome,
for "`_all_ have sinned and come short of the glory of God;`" and thus "`in Adam all die.`"
But it is as unsound to assert that we are born into
this world in a condition polluted by iniquity,
as to say, that He who _so pitied,_ and _so loved mankind, after the fall,_
as to send His beloved, and only begotten Son into the world,
to propitiate for the sins of the world, created man for destruction.
As you remark, we ought to be thankful,
and accept with humility the way of escape pointed out by matchless mercy,
without presuming on the impossibility of things _not revealed;_
for "`things _revealed_ belong unto us, and to our children;
but _secret_ things belong unto God.`"
We may be assured that "`as in Adam all die,
even so in Christ shall all be made alive;`" by which I understand,
that all are visited by the quickening virtue of the Holy Spirit: now,
as this is the spirit which gives life, so we may all come from sin and death,
to holiness and life, into the holy image and blessed likeness,
in which man was originally created.

Ah! we have few among us now who are clear-sighted, and who, therefore,
do not "`err in judgment, and stumble in vision;`" but still there are a _few,_ or we,
as a people, had become extinct.
Our ministry is much in the mixture.
Our "`silver`" is become dross, and our "`gold is cankered.`"
Even some of the _real metal,_ which has come through the fire,
has great need of being melted down again, that whatever is contracted,
which will not stand the ordeal, may be removed.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Tenth Month 5th, 1840.

My dear,
kind friend E. M. gave me the first intimation of
the exit of that valiant in the Lamb`'s army,
Daniel Wheeler.
It may be confessed that he sacrificed his life to the ever blessed,
and most glorious cause, and that he died in the field of battle.
I have no idea that _such a man`'s_ laying down his bones in a certain
place is without a peculiar call to that part of our community,
to see how far they are found in the same faith, in the same _self-denial,_
and giving up of _all_ to the Lord.

Do tell me, if you can, how far are we sensible of the cloud being dispelled,
which has covered us in the season of the Lord`'s anger;
and whether the joyful language applies unto this people, "`Arise, shine;
for your light is come, and the glory of the Lord is risen upon you.`"
Could my spirit be assured of this being the case,
then would gladness fill this fluttering heart;
for I think it would be more to me than the possession of all earthly good, yes,
even of health itself; or to be as Moses in his last old age, whose "`eye was not dim,
nor his natural force abated.`"

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Sudbury, Tenth Month, 1840.

Your remark that "`there is _One_ who remains to be no respecter of persons,`" is comforting.
It is the _same,_ the _very same,_ who for our sakes "`made Himself of no reputation.`"
Ah! were it not for that which weans from dependance on _man,_ yes, the _best_ of men,
all support had long since failed your mother.
We must learn to live without being as the _ivy,_ which clings to something near,
in order to flourish, or to be borne up.
It is sorrowful that poor M. W. should seem likely to sink under her present complaint,
like her late brother;
yet if it be the will of Providence to take dear children out of a world of temptation,
in their state of innocence, we ought to submit, and for their sakes rejoice.

It is with pleasure I now address you in London;
not half the distance from us that you have been so many weeks.
_This_ is a state of vicissitude in which we are placed,
so that the language cannot fail of being loudly proclaimed in our ears,
"`Here we have no continuing city.`"
Oh! that, through all, we may be seeking one that is to come!

The post which brought your note this morning,
conveyed one from our dear friend Hannah Southall,
giving some circumstantial account of the illness of her dear brother,
Richard Burlingham.
He appeared to be sinking fast, and perhaps his spirit has, before this,
taken its flight to those regions where no darkness can come.
"`The righteous is taken away from the evil to come,`" in the _fit time,_
and we should consider and weigh the removal of such; yes,
and see how far _we_ are preparing to fill up the vacant seats in the house,
far exceeding in glory that of Solomon`'s, which was nevertheless glorious,
as a _type_ of the beauty and order of the "`house from heaven,`"
built up by the "`Greater than Solomon;`" whose wisdom,
power, and economy, are consummate.
Many have been the painful feelings of your heart, my ever dear +++_______+++;
may you profit thereby,
and become "`settled and established in the truth,`"
which remains immutable to all generations!
You have great cause to commemorate the gracious care and
providence of the good Shepherd towards you,
as one of His poor, helpless lambs, and to trust in His mercy.
We live in a world of trouble,
but the "`Comforter`" and "`Preserver of men`" is omnipresent, and has all power;
may our trust be in Him!
We wish to be found in the will of our Heavenly Father,
and that our children may be found therein in all things:
this is "`choosing the Lord for our portion,
and the God of Jacob for the lot of our inheritance.`"
Oh! happy portion!
Oh! rich inheritance--soul-satisfying, never-fading!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Tenth Month 30th, 1840.

[.salutation]
My Dear Friend,

In returning the letter from +++_______+++ which, with brotherly kindness,
you sent for my perusal, I may acknowledge that the sentiments he expressed,
on reading [.book-title]#Barclay`'s Selections from Penington,# are such as I should have anticipated;
while they cannot indeed be comprehended, save by those who know from experience,
that the heart of man (as man) receives not the things of the Spirit of God.
I suppose +++_______+++ does not join himself in membership with any religious community:
he is certainly with Friends in principle, almost to a hair`'s breadth,
yet there seems to me to be something lacking, to make him quite an Isaac Penington,
and I can scarcely define in what the deficiency consists: perhaps there is more fulness,
less sense of hunger and thirst, or of fasting,
as in the _mournful absence_ of the Bridegroom, than one would look for,
in a disciple who is _tempted,_ yet _continues_ with the Great Master through all trial:
but mind, I judge not, only wish to be understood.
The carpenter`'s letter is truly gladdening, and very interesting.
As you did not consider his illness alarming, we may hope that his life is spared,
and that he may have to tell others what the Redeemer has done for his soul; or,
should his day`'s "`work be cut short in righteousness,`"
that it is all in wisdom and mercy,
from Him who sees the end from the beginning, and who gives some to be like Sampson,
that slew more enemies dying, than in all his life-time before.

No doubt you are one, as well as your dear +++_______+++,
among the many whose souls are deeply affected,
in viewing the stripped state of our Society.
Dear Richard Burlingham`'s removal is as a place
left in the militant Church occasioning lamentation,
for that a prince in Israel must no more be seen among us;
and ah! how are the seats of such left vacant, even from year to year,
for lack of those rightly prepared to sit down in the heavenly fellowship,
under the blessed government of the King immortal!
for He will accept none in the linsey-woolsey garment,
too much worn in the present day.
No, He will have Jerusalem in her beautiful attire, in the true wedding garment,
made white by being washed in the blood of the Lamb,
and which is granted to those who come through great tribulation.
Let us hope that there remains a remnant of such, seen in the light of truth,
occupying their seats among the servants of His house,
the "`greater than Solomon`'s`" yes,
and that there are of our children under the Divine Hand, who,
as they abide with the power, will be brought forward in due time,
and richly qualified to show forth the praise of Him who first gathered us to be a people,
and who may be instrumental in bringing others to see for themselves,
the wonderful economy and glory of the Church, the very type or representation of which,
made the Queen of Sheba confess that "`there was
no more spirit in her,`" in taking a view thereof.
Well, dear friend, I have now penned a long letter, which my eyes,
and general sense of weariness, admonish me to close.

[.signed-section-closing]
Your sincere and grateful friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Twelfth Month 16th, 1840.

Should you, my brother, be permitted to give up the view that has so long tried you,
I can joy in _your_ joy, as coming from the compassionate Judge,
who requires of us that "`perfect love that casts
out _fear._`" No doubt the ordeal you have endured,
proved thoroughly equal to any strength or patience afforded; but oh! how watchful,
how careful is the Refiner!
"`He shall _sit_ as a Refiner and Purifier of silver.`"
He sits to watch the critical time for removing the precious metal from the fining pot,
that it be not injured.

The sons of Levi were to be tried as gold and as silver,
that they might offer an offering unto the Lord in righteousness.
I trust this is not inapplicable to you.
The offering of your _all_ seems to me to have been made,
through the preparation appointed; and if my poor mind be influenced aright,
the sacrifice is _complete,_ and is no _partial_ offering.
I should be sorry to presume on anything of this solemn and fearful nature, as of myself,
or as knowing anything without the Lord;
and dearly and tenderly commending you and yours to Him, I remain

[.signed-section-closing]
Your sincere and affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Twelfth Month 22nd, 1840.

I think a deal of you,
and much hope you will be rightly directed and helped through difficulties,
as has before been your experience;
that Divine goodness and mercy may follow you all the days of your life.
We must be inward and watchful, as you know, in order to be thus favored,
and that all our steps may be "`ordered of the Lord.`"

Each dispensation of Divine Providence has a time to be fulfilled in our passing along,
and is designed for our establishment in the truth.
We had need take care and endeavor to possess our souls in patience,
having faith in the promises of Him who has the name of "`Faithful and True.`"
Oh! that my +++_______+++ may rely on Him, and wait for Him with whom all things are possible.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, First Month 24th, 1841.

Yes, I bear you on my heart in tender solicitude,
and sympathize in the afflictive dispensation lately
permitted to come upon your whole family,
by the illness of your loved husband;
and while there may be no utterance with the tongue,
I cease not to remember you in my prayers.
Often is that language before me,
"`All things work together for good to them that love God.`"
Oh! that we may seek to love Him with the perfect
love that casts out fear! come what will come,
all will then be well with us, and bring to the blessed experience,
that truly (without exclusion) all things work together for our good.

My very soul has travailed with and for the dear sufferer,
who must feel his situation to be an awful one.
Could I sit by him, I have sometimes thought it would, in some sense, answer my desires;
but I can commend Him to the omnipresent and omnipotent One,
who orders all things in wisdom, and whose omniscience has noticed your dear partner,
when he could deplore his own defects, and yet appeal to the God of knowledge,
"`You know that I love You.`"
And now, my loved, tried friend, farewell in our Almighty Helper;
the eternal Refuge in every storm;
who weighs every atom of our painful feelings in His righteous balance,
as we look to Him for succour.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, First Month 31st, 1841.

[.salutation]
My Dear Friend,

Your testimonial of remembrance of me is consoling to my heart.
Oh! we had need be endued with that wisdom that is of an opposite character
from __his__--"`the crooked serpent;`" even what comes "`from above;`" which,
while it is "`gentle, and easy to be entreated,`" gives true discernment,
and penetrates the false covering, however gilded, and calculated to deceive.

Well, my dear friend, we are yet favored to see a few _overcomers,_
who are made pillars in the temple, hewn out and established by an almighty,
all-skillful Hand.
What a mercy!
Yes, "`Wisdom has built her house, she has hewn out her seven pillars.`"

It is my humble trust that yet the Great Head of the Church
will separate more manifestly that which does serve Him,
from that which serves Him not; even the precious from the vile, to His own glory;
bringing the righteous to shine forth as the light in the kingdom of their Father;
evidencing that they are truly under His government,
whose right it is to sway His sceptre in the hearts of the children of men,
and whose dominion is forever and ever.

Amen.

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Second Month 11th, 1841.

I am truly glad of the relief afforded you; rejoicing with you and yours,
as I have also wept with you in my heart.
Oh! the mercy, the wisdom, the power of our Heavenly Father, who wounds to heal,
who breaks down to build up, who chastises to make us cry, "`Abba,
Father;`" even becoming His own dear children, "`born, not of flesh,
nor of the will of man, but of God.`"

How often have I thought (under a sense of sympathy in the sore trial of your loved
husband`'s illness) of Saul being "`found among the stuff,`" and called forth;
having been told by Samuel that he should be turned into another man; and so it proved,
after the vial of oil was poured upon him.
Your husband seems to me to be in the hand of Omnipotence.
Oh! the endearing love of our holy Redeemer! how sweet it
is! how uniting! beyond all the ties of our mere nature.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Second Month 12th, 1841.

Often, in looking towards some of you, my long-loved friends,
I see a sadness of countenance, or at least I think so;
a sadness not altogether on account of yourselves,
but something like putting on sackcloth and ashes,
although not very perceptible to beholders: but do we not lack those in this day,
who may indeed be styled "`mourners in Zion?`"
Was there ever more of the transformations of him who, in so many and various ways,
seeks to bring into that state that "`calls evil good, and good evil;
that puts darkness for light, and light for darkness; that puts bitter for sweet,
and sweet for bitter?`"
and how many are beguiled and deceived, so that we are ready to say,
Alas! who shall stand?
We can truly say, in our own religious community, "`All is not gold that glitters.`"
Oh! for some Daniel Wheelers, some Thomas Shillitoes, and John Barclays,
to be raised up among us; more in substance than show,
and yet evidencing the refinement which the most precious metal endures,
and how it is prepared for use, and has the true stamp upon it!

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Second Month 19th, 1841.

You seem now to be enabled to leave the past more than was the case for years,
and are favored with a considerable degree of tranquillity of mind, in which I rejoice.
That sore bereavement that has befallen you being still keenly felt, I do not marvel at:
"`that which is lacking cannot be numbered;`" and a chasm such
as the severing hand has been permitted to make in your family,
must, I apprehend, remain a source of tender sorrow,
until eternal joy forever reigns in the soul,
and more than compensates for the losses and vicissitudes of the present state of being.

Your feelings in the Morning Meeting respecting what was produced,
were such as I should expect.
It is well there are a few left,
who are jealous lest the ancient standard should be lowered
by unskillful meddlers in things too high for them.
Oh! how tried my poor mind is,
under a sense of a great lack among us of true discernment;
and even in my very secluded allotment here,
I think my inward eye sees a covering in our Society that is prohibited in the truth;
a mixture as surely disapproved in the sight of the Great Head of the Church,
as ever the forbidden linsey-woolsey garment was of old;
and which must one day be taken off, for the all-scrutinizing eye will not wink thereat.
