== Chapter 23. Letters from 1841--1842

[.letter-heading]
To a Friend, on his Recovery From an Alarming Illness.

[.signed-section-context-open]
Sudbury, Third Month 31st, 1841.

[.salutation]
My Dear Friend,

Your testimonial of remembrance cheered me,
in the confirmed report of health being restored to you,
and your strength nearly what it was,
previous to the visitation of illness lately your experience.

I am indeed glad to be prepared to "`rejoice with them that
do rejoice,`" as well as to "`weep with them that weep.`"
Your dear wife must feel much relief,
and I believe is at heart humbly thankful for the
mercies still extended to your family circle.
Oh! how needful it is for us to keep in view the end of those means
our Heavenly Father appoints for our being qualified to cry,
"`Abba, Father.`"
May you, my loved friend, be very watchful, and, like Enoch of old, and like Abraham,
walk in the Divine presence; henceforth renouncing the world;
remembering continually that it is utterly impossible to serve God and Mammon.
"`You cannot serve God and Mammon.`"
Neither will it do to cherish forgetfulness of what an Almighty hand has wrought for us,
after we have witnessed His wonderful interposition, and have sung His praise.
Let us not plead necessity for holding back anything from the Giver of all good:
this would be calling the blessed Master "`an austere man,`" etc.
We must have nothing that we call ours,
and then we shall "`possess all things;`" an attainment which often
appears impracticable to the mind of the natural man.
"`Well, I want you to be one of those who walk worthy of this high vocation.
"`Be perfect and entire, lacking nothing.`".

To persevere in pressing toward the mark for the prize has been found possible,
and still remains to be so: be that your constant aim, my brother;
so will your God forbid that anything whatever should prevent
your so running as to obtain the glorious prize.
Farewell in much sincere desire for the real good of yourself and all yours.
I remain affectionately your friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
London, 1841.

Your letter written yesterday I have now read to my comfort.
Oh! my dear, there is a resting-place for us in this wearisome world,
even the holy bosom of Him who "`has borne our griefs, and carried our sorrows.`"
What a mercy!
It seems to me that the scripture is in some measure verified, even to me,
"`You shall go out with joy, and be led forth with peace.
The mountains and the hills shall break forth before you into singing,
and all the trees of the field shall clap their hands.`"
I have had deep baptisms, but there is occasion to adopt the precious language,
"`Thanks be to God, which gives us the victory, through our Lord Jesus Christ.`"
Many private exhortations, salutations,
and sometimes living prayer to the Source of all-sufficiency are offered.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Fourth Month 1st, 1841.

You bids me think of you: I do so,
particularly in your present state of deep consideration,
and that with respect to a matter, that, if carried forward,
can only meet a change with the termination of life,
with one or the other more nearly concerned.
You know that I have always felt love for you,
as a dear child who loved your Heavenly Father,
as well as that natural affection has been kept alive in my heart through our long separation.
There seems even now a savor from your spirit sweet to me.

I have only to say, take heed that all your steppings are in that light which never did,
nor ever can prove an ignis-fatuus; and may He who sees the end from the beginning,
guide you by His counsel; thus rewarding the sincerity of your intentions,
and granting you the peace which passes all natural conception!

[.letter-heading]
To J. H.

[.signed-section-context-open]
Sudbury, Fourth Month 14th, 1841.

[.salutation]
Dear Afflicted Friend,

You will believe that, for some time past,
my tender sympathy has been more than usually alive toward you and yours,
on account of the severe illness of your precious daughter,
which has at length terminated in the removal of
so sweet and lovely a branch of your family;
but what shall we say?
Is it not permitted in that wisdom which remains to be consummate,
and that love which is infinite?

Often are we ready to fear that the severing hand is sent in displeasure,
when indeed it may be because the Lord accounts His
dear children worthy to be made mighty to suffer,
as well as to do His blessed will.
No doubt, in due time,
the darkness of His providence will be made light before such as fear His Name.

As for you, it certainly appears to me that great honor is conferred on you,
in having been instrumental in preparing the way for some of your loved
offspring to join "`the innumerable company of saints and angels,
and the spirits of just men made perfect,`" (among whom
is your late dear partner in life) who forever sing "`Alleluia,`"
and ascribe "`salvation to our God which sits upon the throne,
and unto the Lamb.`"

Somehow I feel as if your dear spirit was already partaking of that purity,
described by the being "`arrayed in white robes;`" for through
much tribulation are they measurably washed,
and made white in the blood of the Lamb; yes,
I trust are still more and more surpassing the snow--so
admirable as that is to the natural eye.
The Lord give you to say "`Amen`" in every trying dispensation;
to number your remaining blessings, and to give thanks for His mercies.
Some of your dear children, yet in a probationary state,
are favored to know the God of Jacob to be their Refuge as well as their Guide;
these are, no doubt, some consolation to their loved, bereaved mother.
There are of those that the Lord has given you, not only by nature, but also by grace,
in answer to your prayers,
who have some experience of what it is to be "`buried
with Christ by baptism into death;`" and who,
I trust, witness His reigning over all, at times,
and are in a precious degree prepared to reign with Him.

Tell dear +++_______+++ that I remember her with joy, and that I trust,
amidst every conflict and exercise, she may receive the salutation,
"`Hail! you that are highly favored,`" etc.
How truly dignifying is the truth!
Let her loved +++_______+++ be encouraged to possess the truth and hold it,
by giving the full price for it, and never bartering it for aught else.

Farewell, my long-loved friend.
I do think we should be thankful that another of your dear
family was made ready for a mansion in eternal glory.

I am your sincerely sympathizing and attached friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Fourth Month 15th, 1841.

I trust the Shepherd of Israel will continue to protect you on every hand,
as you love and fear Him.
Walk through life lowly, so will you walk safely, dear child;
and may your spirit be more and more deepened in the best things,
to your own establishment on the invincible foundation,
and to the praise of Him who has called you to glory and virtue.
Amen.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fourth Month 16th, 1841.

Somehow I want to put you in mind peculiarly of dear John Woolman`'s remark,
"`In this world, which may be compared to a thorny wilderness, how precious,
how comfortable, how safe are the leadings of Christ, the great and good Shepherd!`"
May He be your blessed Guide and Protector always, and on every hand!
May He make the rough ways smooth, and the crooked paths straight for you!
I much desire you may ascend together to the mountain of the Lord,
to the house of the God of Jacob; where He teaches of His ways,
and gives ability to walk in His paths: His ways being those of wisdom,
and His paths too, they are pleasantness, and they are peace; for how high and holy,
how new and living,
is the way cast up for the redeemed of the Lord to walk in! separate from
all that stands in the contrariety to that which is of the holy,
harmless nature of the Redeemer Himself.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
1841.

I do believe our ministry now requires an ordeal that would take away,
not the dross only, but the tin and the reprobate silver: yes, in no very slight degree,
has our very "`silver`" become dross, and our "`gold is cankered.`"

The day will come when every substitute for the reality
and dignity that is in the immutable truth,
will be as stubble; for "`what is the chaff to the wheat?
says the Lord.`"
The superficial observer may mistake the one for the other,
but that "`Spirit which searches all things,`" where it is received and heeded,
discovers the emptiness of the chaff, and the fulness and weightiness of the wheat;
therefore these must be separated, the one from the other,
that the wheat lose none of its usefulness by the mixture.

Let us each remember we can do no better than to follow the Lamb perseveringly,
whithersoever He goes; even if it be to Calvary`'s Mount.
To be with Him in suffering is the way to reign with Him in glory.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Fifth Month 7th, 1841.

We must all be in earnest for the presence of the
sure and skilful Pilot on board our vessel,
in order to steer clear of the manifold dangers that lie in the way,
or to which we may be subjected.

We are ignorant and powerless of ourselves; even the wisest, the most knowing,
and the strongest of men.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Fifth Month, 1841.

The Yearly Meeting now commencing affects my poor mind awfully,
yet do I not see that I ought to be one of those present.
I am nevertheless deeply interested, as regards the concerns of our religious community;
desiring that "`the unction from the Holy One`" may be with Friends,
"`teaching all things.`"
Oh! there is much to correct within our borders; yes,
there is a great deal of "`tin and reprobate silver`" to be purged away,
before we "`arise and shine`" in the original lustre of this Society.
I feel afraid lest "`mighty works`" should be pleaded,
as spreading the knowledge of the Redeemer`'s kingdom,
and lest creaturely activity should assume the character of gospel labour.
May the "`watchers`" be faithful to their trust.
Oh! may many go deeper in their spirits to feel with the innocent life,
which does not strive, nor cry, nor lift up,
nor cause the voice to be heard in the street.
Ah! my friend, my dear, kind brother, the Great Head of the Church is requiring a humble,
yet faithful acknowledgment of His interposition for His poor, helpless servants.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Fifth Month, 1841.

It is truly kind of you to remember your poor, afflicted correspondent,
as evinced by an address since you and your dear daughter gave us your company,
on the mournful occasion of interring the remains of my beloved one.
The tender sympathy of a brother who has drunk of the same bitter cup,
is peculiarly grateful.
You do not even yet forget "`the wormwood and the gall,`"
then no wonder it should be very fresh with me.
May it not, however, be a part of those ingredients,
seen fit by the all-skilful "`Physician of value`" to be mingled for us,
that the immortal part may be strengthened thereby: then let us resolve,
as one did of whom we read, "`I will take the cup of salvation,
and call upon the name of the Lord.`"
At the same time we are not required to render the potion more trying to our nature,
by adding our own bitter self-reproaches from time to time,
until our feelings become almost intolerable.
Shall we not watch against such a propensity, lest it weaken our faith,
and we become less qualified to pursue the path cast up for us?

Come, my brother, we are both alike tempted to dwell upon omission in gone-by days;
with the temptation there is, however, a way to escape;
only let us come to Him who is able and willing to "`do exceeding abundantly for us,
above all we ask or think:`" but indeed, while endeavoring to encourage you,
I am myself much depressed; seeking refuge in the hiding-place in the day of trouble.
When we seem to ourselves too devoid of strength to run there,
it remains for us to wait for the fulfilling of the promise,
"`They that wait upon the Lord shall renew their strength.`"

[.letter-heading]
To J. H.

[.signed-section-context-open]
Sudbury, Fifth Month 20th, 1841.

[.salutation]
My Tenderly Beloved Friend,

Inured to sorrow as I know you to be,
my mind is assured of your sympathy with me and my remaining family,
when I acquaint you with the departure of my dear husband,
who is gone to his everlasting mansion of rest and peace,
as well as your precious partner in life,
and more than one of your sweetly endeared offspring.
Last First day morning all our family expected to be at our worship publicly.
I had assisted my loved J. G. as usual to dress, and he walked downstairs to breakfast.
H+++.+++ pointed out some alteration in him, and we sent for the doctor and for our sons,
who were here in a few minutes.
Presently, however, my beloved one became unconscious, was carried to his bed,
where he revived a little, and recognized us all;
but soon after lost all power of reflection, became restless,
and then sunk into a state of stupor, from which he never revived, yet lived two days.
Perhaps I have entered too much into the detail of this trying scene,
but it is to a sisterly friend, who can see that, in this world,
we often have to meet with what is very severe to our nature,
and who knows the sensitiveness of some minds.

He was one of those who became as "`a little child,`" fit for the heavenly kingdom.
Sometimes, since I saw you last,
I have had to exercise closely the little grain of faith vouchsafed;
even that which remains to be "`the substance of things hoped for,
the evidence of things not seen.`"
Under this sense of what the true faith really is, I cordially salute you;
hoping that both yourself and your poor correspondent may eventually be favored
to enter that state where there is found uninterrupted and perfect felicity,
faith and hope being consummated;
as we believe to be the case with each of our nearest earthly ties, now dissolved.
So farewell, says

[.signed-section-closing]
Your sorrowful, yet ever affectionate friend,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Fifth Month 30th, 1841.

No doubt all has been ordered in that wisdom which cannot err, and in adorable mercy too.
My love, the only one I ever loved,
so as to wish to be united to in the solemn covenant of marriage,
became insensible to every effort to relieve him, made by any mortal,
and breathed out his natural life; in consequence,
free from being aware of the pangs of that stroke which was to sever our earthly union.
For this my heart became thankful--even that he knew nothing of the rending
asunder which was so hard to me to endure with quiet acquiescence:
yet no murmuring thought was permitted to enter my mind.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Sixth Month, 1841.

I had much rather drink this bitter cup in separation,
and go softly the rest of my days in sorrow, than that it should have been his lot.
So you see I am able indeed to say amen to what is dealt out in this dispensation,
by the hand of an all-wise and compassionate Judge.
Think not that I mean to say I have any other than a bleeding heart.
Yes, I feel deeply the wound inflicted, which has left half of myself,
and I sincerely conclude,
taken away that half which was the most purified and made fit for the holy kingdom.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sixth Month.

I feel stripped and lonely; missing my loved companion much,
with whom I travelled so long in the path of life, and who was very tender of me,
and thankful for our union as well as myself;
and although his mental powers were giving way in some degree,
through the infirmities of age, yet I loved to be near him, and assist him what I could.
Ah! he has left me to take some weary steps without him,
but my children are all very attentive to their widowed mother,
and my mind is consoled in contemplating the felicity
of one almost dearer to me than myself,
and that felicity uninterrupted forevermore.
There often seems to me to be granted something like heavenly
fellowship with the spirit at rest even now.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Sixth Month 18th, 1841.

Although my eyes are rather painful, I send just a little salutation to you,
wishing you to be assured of my constant sense of interest and love as regards you.
I do indeed commend you to the "`Great Preserver of men;`" to Him
who keeps in the hollow of His hand all those that fear Him,
and look for His gracious care.

Be very watchful, my +++_______+++, wherever you are.
Remember our adversary watches over our unguarded moments,
to draw us from the Good Shepherd; be therefore "`sober,
be vigilant;`" let your words be seasoned with grace.
You know not how your Heavenly Father may make use of you in His own cause,
and to the forwarding His designs as regards others.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Dorking, Seventh Month 30th, 1841.

[.salutation]
My Dear Friend,

Your loved brother`'s letter, which I now return,
is indeed just suited to the state of things among us in this day,
and very instructive,
not only as regards the youth receiving the knowledge of the Holy Scriptures,
but with respect to every class turning inward,
and obeying the teachings and leadings of truth.
"`What a sad thing it is that such a striking testimony
to the inefficiency of all that man can do by his own powers,
should be withheld from the public!
Oh! my heart cordially unites with the views held by our late highly gifted,
and highly valued brother.
Would there were more raised up,
and faithful like him! "`What a glorious crown he now inherits eternally,
in that he was "`faithful unto death!`"

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Eighth Month 20th, 1841.

Your letter cheered me in some respects,
finding that you and your dear husband were permitted to enjoy that blessing which,
in my estimation, stands first on the list of temporal good, even health;
and hoping also that the valuable boon is considered by you to be that which,
with all you have, and all you are,
is at the disposal of the Giver of "`every good and perfect gift.`"
It is my concern that, while the energies of life are in vigor,
each of you may stand at the disposal of our Divine Master.
None will ever have to regret being His, entirely His--possessing all in Him:
so will He realize the language to these, "`Fear not; you are mine.
When you pass through the waters, I will be with you; and through the rivers,
they shall not overflow you: when you walk through the fire you shall not be burned;
neither shall the flame kindle upon you.
For I am the Lord your God, the Holy One of Israel, your Savior.`"
That your husband should accompany you in your religious engagements from home,
is in accordance with my view.

Now I may tell you that, since my J. G.`'s removal to his eternal home,
I am sensible continually of my widowed state.
Ah! none can tell what such a severing is, but those to whom it is sent.
I am always sorrowful, yet rejoicing at his being fixed in his happy mansion,
and that he knows nothing of my mourning as a dove.
I am far from repining, yet my affectionate feelings are much awake; full as much now,
as on his departure I am very far from well,
but desirous that my last days may be such as will not discourage others from resolving--

[verse]
____
My life (if Thou preserv`'st my life)
Thy sacrifice shall be,
____

You and I think alike about our poor, degenerated Society.
I only wish that they who are not of us would go right out, and leave a little band,
who are united in the Gospel of the lowly Jesus,
and who cannot do mighty works merely by extolling Him in name; yes,
are faint without the renewings of the Holy Spirit upon them.
There is a little stirring among our youth in some places,
but alas! where are the fathers and the mothers?
Oh! how little true discernment is left.
Ministers are acknowledged, and elders are chosen; but, in too many instances,
it evidences itself to be the work of man;
at least there is a deplorable mixture still among us.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Eighth Month, 1841.

[verse]
____
When heaven seems brass, and earth, with iron bars,
Doth hold its cheering goodliness from us,
____

[.no-indent]
&hellip;then may we not forget that the trial of our faith
is much more precious than of gold that perishes,
even though it be tried with fire; yes,
and it is well to remember that the same things happen
to our brethren that are in the world.

Can I wish to recall my days, my years that are gone by?
I tremble at the thought.
I might not do better.
I might do worse.
It is for me to lie low, and hope against hope,
under a humiliating and painful sense of the weakness of my nature.

Mercy is what I hope for; mercy is all I ask.
This, if granted, will bring at last to that rest and peace my soul pants after,
and which I believe is the eternal portion, both of your dear partner in this life,
and of mine.
May we be eventually admitted into the company of these blessed spirits,
joined indeed to saints and angels, an innumerable multitude, yet all known individually,
and each owned, as helping to constitute the Church triumphant,
whose names are written in heaven.
So dearly farewell, and tell your dear children all, that life is worth living,
only as the will of our Heavenly Father takes the place of our own untoward will.
I feel interested in their implicit obedience to
the manifestations of the heavenly anointing in themselves.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Ninth Month 9th, 1841.

I hasten to tell you that my health is now restored to its usual standard,
for which I am ready to say,
What shall I render to Him who is indeed the Physician of value?
Well, it is the interest of all to acquiesce with the dealings of Infinite Wisdom,
and say amen to His will.
Now I, a worm, a thing of no account in my own view, and I believe in that of many,
very many, am nevertheless induced to avow a concern to visit the Churches in this land,
in their collective capacity, as way may open;
and also any other religious service that may be from time to time required among Friends,
or others where my lot may be cast.

I cannot say that "`I am sure,
that when I come,`" (among Friends or others) "`I shall come in the fulness of
the blessing of the Gospel of Christ,`" but oh! for some portion of this blessing.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Ninth Month 29th, 1841.

We are privileged with this mode of communication,
and besides we can be each other`'s companions in mind; all of which I esteem a favor.
Great is my desire for you, that the day`'s work may keep pace with the day.
May you be found diligently working in the Lord`'s vineyard,
and receiving those wages which, I well know,
you value above all that a fading world can give.`"
"`He that reaps receives wages, and gathers fruit unto life eternal;
that both he that sows and he that reaps may rejoice together;`" that thus the
laborers may all find their account in pursuing the appointed work.

I know that there is much discouragement presented to the diffident mind in this time,
but such things are like the "`clouds,`" which are not to be observed;
and those "`winds`" which are to be disregarded,
with respect to our individual engagements, in true dedication to the Most High.

In low times, and when we see our own deficiencies,
it behooves us to cleave to our Almighty Helper,
in humble desire after ability to "`leave the things that are behind, and,
reaching forth to them that are before,
to press toward the mark for the prize of our high calling of God in Christ Jesus.`"
We are sometimes prone to waste our precious time in sitting
under an unavailing lamentation as to the past:
this weakens us still more,
and we begin to fear that now it can be no use to hope for the future.
What a pity this would be!
Come then, let us now and henceforth,
"`give all diligence to make our calling and election sure.`"
I speak as to our places in the Church on earth, and the glory of the world above.

There is no occasion for me to fill my sheet of paper because it is a large one, yet,
before closing this,
would just acknowledge to the mercy and lovingkindness of my Great Master,
in providing for me a way to fulfill my prospect of service so far,
to the unspeakable satisfaction and relief of my own mind mostly.
Yesterday was an exception, for I was deeply plunged into travail and exercise of soul,
before the great Quarterly Meeting commenced, and in it, after it gathered;
but believed it right for me to keep silence a long while,
and there was little said by any one for an hour.
Then, as I was near breaking forth, another stood up;
after which my way did not open for a word;
and most thankful I am that nothing was attempted, on my part,
to lay down my burden out of the right time and ordering.
I must now take my leave, and subscribe myself

[.signed-section-signature]
S+++.+++ G.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Tenth Month, 1841.

The Quarterly Meeting yesterday was a time to be remembered.
Truth`'s authority rose high, and there was solemn silence a good while,
after enlargement in testimony.
Dear A. D. was there, and kneeled, to edification and consolation,
toward the close of the meeting.

I was glad you did not meet our aged friend, J. Grant.
His appearance altogether was so strikingly like your dear father,
the resemblance was such as to require some nerve to bear the sight calmly.
When he made an effort to walk, and in getting into his carriage to go to meeting,
it was very moving to me.
He was rejoiced to see me.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Tenth Month, 1841.

+++_______+++ seemed glad that he had attended the Quarterly Meeting in Waterford,
and indeed it was an extraordinary time of truth triumphing over error;
for it seemed as if there was given, in the Lord`'s own time, mouth and wisdom,
tongue and utterance, which could not be gainsaid.
The small company in the Select Meeting appeared to me to be sound in the faith,
and closely bound together in that which knows no change.
They are among the marked ones, who sigh, and are often heavy-hearted,
yet who do know that, if the sufferings of Christ abound,
the consolations do likewise abound.
There are some, I think, prepared, and others under the forming hand to join them;
yet many harden the heart, and stiffen the neck; not being disposed to bear the yoke,
and carry the burden which is made light and easy to the truly humble soul.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Tenth Month 26th, 1841.

Oh! the deep baptisms I had to pass through in Waterford!
fully equal to any I had ever experienced,
which have been renewed in this place also.
Yet never did I witness greater strength in meetings to fight the Lord`'s battles;
nor was my mind without the living, joyful sense of complete victory;
truth reigning over all.

I humbly trust the power of the Most High bowed the
hearts of some that were like Bashan`'s oaks.
I am now weak and low, as to the best things, and my faith sorely tried,
but not shipwrecked; blessed be the goodness and mercy of Him whose invisible,
everlasting arm is underneath, for the most timid souls that trust in Him alone.

+++_______+++ has entered "`the vineyard`" as at the "`eleventh hour`" of the day of visitation,
and is a striking instance of Divine mercy,
through much painful regret as to time past unimproved.
Who would desire to have all this bitter repentance at last,
instead of reaping early the fruits of obedience, and receiving wages,
in prosecuting the work assigned in the daytime?

[.letter-heading]
To her Son.

[.signed-section-context-open]
Clonmel, Tenth Month 27th, 1841.

H.`'s illness is a source of great anxiety to me,
yet I may acknowledge that more composure clothes my mind than I could have anticipated,
under present circumstances.
In the retrospect, I cannot find that I missed my way in turning to Ireland.
I looked towards home many times before deciding on coming,
but could not rid myself of a dimness in the prospect, so that I was afraid to go;
and no further service opening in England,
and a strong drawing to the Quarterly Meeting in Waterford being felt,
I ventured to yield to it in great exercise of mind,
and with some apprehension that affliction awaited me,
beyond what had recently been my portion.
What should I do, but for the privilege allowed the meanest followers of the Lamb,
even that of endeavoring to bring all to Him, which loads us with heaviness and sorrow.
He carried our sorrows; He bore our griefs in His own body, and said, "`Not my will,
but Yours be done,`" in address to the Father:
He invited to learn of Him meekness and lowliness of heart.
This is my first desire,
for in such a condition we do feel that every wish to control
or alter what is dealt out to us by the Divine Hand is hushed,
and we learn to drink the cup submissively, however bitter,
and to say "`Amen,`" even in darkness and distress; waiting for the return of light;
for "`weeping may endure for a night, but joy comes in the morning.`"

I have paid several visits to invalids the two last days, and many friends come to see me.

[.letter-heading]
To the Same.

[.signed-section-context-open]
Clonmel, Eleventh Month 3rd, 1841.

I have to report favorably of our dear H. She is, I think, in a fair way now to recover.

How very moving it is about that fine girl, C. C.,
being taken from her parents and friends.
I feel greatly for the bereaved, especially for the mother and sister where C. was.
I am taught to "`remember them which suffer adversity,
as being myself also in the body,`" therefore subject to the same thing.

My love is to +++_______+++, and to dear E. E. W.,
who is filling up her measure of service and suffering, and will, I believe,
rest from her labors in due time, and her works will follow her,
although she has so mean an opinion of her works;
oh! it will be manifest that they were "`wrought in God.`"
My love also to R. H.

May I find my dear +++_______+++ grown in grace, and knowledge of the best kind, on my return.
This is my heart`'s desire and prayer for you,
my +++______+++. Be watchful with what you revere and love sincerely.
Farewell.

[.letter-heading]
To one of her Children.

[.signed-section-context-open]
Clonmel, Eleventh Month 13th, 1841.

Last fifth day, at meeting here, some of the Ranters were coming in,
but were prevented by the door-keepers.
I neither saw nor heard what was going on, but am told there was terrible vociferation.
In the midst of all this I stood up, saying,
"`What a mercy it is to have access to Jerusalem,
the quiet habitation;`" alluding to the scripture, "`Your eyes shall see Jerusalem,
a quiet habitation.`"
"`You shall not see a fierce people,`" etc.; the passage was quoted.
I thought this remarkable: indeed there have occurred many things,
since coming to Ireland, very striking, both as to ministerial labour and in other ways.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Clonmel, Eleventh Month, 1841.

My mind being drawn to Cork, ever since coming to Ireland,
I was afraid to omit going there (the time also opening for it).
You would have felt for me, had you witnessed the great weight that I was under,
and which I could not lay down among the people in the morning; but,
after rising in the prospect of relief, and standing half an hour,
was under the necessity of confessing that I could not believe
it safe to do otherwise than take my seat,
and wait for more of truth`'s authority, should I say more to them.
I did not, however, again leave my seat before the meeting closed: it was a trial,
for I had much in my heart that appeared to be for those then assembled.
My distress of mind was such as to call forth all the patience
and humble confidence my capacity was equal to sustain.
What my mind was suffering, I concealed from those who came to see me as well as I could.

Well, but in the afternoon I was raised up in the Lord`'s power,
in a manner marvelous to myself.
Perhaps I stood an hour and three-quarters, speaking with increased life and energy,
even of the deep things of the gospel dispensation; after which,
a short and solemn address to Almighty God closed the meeting,
and I was relieved from feelings that had pressed me sore.
Oh! may all the praise be ascribed to Him to whom belong honor and glory forever and ever.
Amen.

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Twelfth Month 8th, 1841.

Although I did not produce my certificate in any meeting in Ireland,
the religious engagements there were close,
and I was much enlarged in the ministry in several places--perhaps never more so.
The visit there brought some of the deepest baptisms upon me that I ever experienced:
the retrospect, however, brings no cloud nor condemnation; on the contrary,
a consciousness of having done as well as I knew how.

[.letter-heading]
To a Daughter.

[.signed-section-context-open]
Twelfth Month 21st, 1841.

How often, this day, have I commended you to Him who can make hard things easy,
who has heard us in the day of trouble, defended by His name,
sent help from the sanctuary, and strengthened out of Zion!
He is, I do believe, now accepting this sacrifice, in our separation from each other,
for the sake of obeying His blessed will, and in pursuit of peace.
I hope your sister was told of the little season of prayer, in your chamber this morning,
when she was not forgotten.

_24th._--It is intended for us to leave for Exeter on second day.
The meeting at Truro is held on fourth day week; perhaps I may then come home for a while.
Having a little confidence in our all-efficient Caretaker, and Heavenly Parent,
I try to leave it.

Farewell,
my loved +++_______+++. May your mind be stayed upon the "`Comforter,`" the Spirit of truth,
who leads into all truth.

[.letter-heading]
Extract From S. G.`'s Last Letter to her Son.

[.signed-section-context-open]
West Hill, Twelfth Month 26th, 1841.

[.salutation]
My Dear J.,

Your letter telling of H. not being so well on fifth day,
was brought to me this morning before day.
I should be grateful for a few lines from home immediately, directed John Dymond, Exeter.

It seems hard for me to look towards going further from home,
but I do not know how to do better.
I commend each and all of you to Him who is omnipresent,
and who pities those who fear Him even as a father does his child.
Oh! may you, my dear J., be entirely His, to serve Him and glorify +++[+++Him.]

+++[+++Here she was interrupted by the arrival of her son,
with whom she returned to her home the following day, and quitted it no more.]

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Twelfth Month 31st, 1841.

Your sympathizing lines of 25th instant are what I wished for,
and let me say I am glad you and your husband are now in armor.
You speaks of conflicts, but I should be sorry if you had much rejoicing just now.
"`Let not him that puts on the armor, rejoice as him that puts it off.`"

When I left my H. last, it was for the Quarterly Meeting at Hitchin.
We felt it hard to part, but we parted, as offering our all to Him who said,
"`He that loves,`" etc., "`more than me, is not worthy of me.`"
I was favored to get through the Hitchin Meeting
under a living sense that truth had the victory,
and had a remarkable day at Wandsworth, on First day, at two meetings.
In the evening I said I had not felt easy about home,
and was writing to J. when he came to fetch me.

Farewell, my dear +++_______+++. You and your loved companion be "`strong in the Lord,
and in the power of His might,`" says Your afflicted and loving aunt,

[.signed-section-signature]
Sarah Grubb.

[.postscript]
====

P+++.+++ S. I should have been in the west now, but for this call home.
How baffling to our rational powers are these things!

====

[.letter-heading]
To +++_______+++.

[.signed-section-context-open]
Sudbury, Twelfth Month 31st, 1841.

As it seems probable you are even yet without full
information of how it is with our family,
under the renewed affliction which is dispensed, I wish to send you a line.

You have perhaps heard of my return,
after being at a highly favored Quarterly Meeting at Hitchin,
and at Wandsworth on First day, which was also "`a day that the Lord had made.`"
I came home on second day, and found +++_______+++ at the very "`gates of death.`"
I saw her for a little while, and waited on the Author of life,
in whose hand is our breath.
At first I felt all the awfulness and silence of the grave.
My soul said amen--the debt must be paid sooner or later.
I was about to leave the room,
when it occurred to me to stay a little longer in abstractedness of mind.
Unexpectedly I saw the darkness dispelled, as I thought,
and like the sun breaking forth--the way opened into another scene.
It seemed to me that there was more to suffer, and that,
did my child escape the scythe made ready to cut her down,
it would indeed be a peculiarly narrow respite from being laid low forever.
Since then the prospect of that moment has been realized,
her mother having witnessed the most moving scene that ever was her lot to experience,
in seeing her child plunged into inexpressible distress, both of mind and of body.
I sat in the sick room while this lasted, endeavoring after stayedness of mind,
when the way seemed to open for me to pray to Him who could give ability
to "`pass by the gates of death,`" if such indeed were His purpose.

Thus, my dear, you see that this is not the place of our rest.
"`Here we have no continuing city,
but we seek one to come;`" where all our sorrows shall be forgotten eternally,
and ineffable joy take their place, should we indeed hold out to the end.

I remain your deeply tried and closely exercised, yet, I trust, humbly dedicated,
and truly affectionate relative,

[.signed-section-signature]
Sarah Grubb.

[.letter-heading]
To a Young Friend.

[.signed-section-context-open]
Sudbury, First Month 13th, 1842.

Be assured that you, and our other friends at L., are not out of mind with us here,
while so long out of sight.
We have not heard of any of you since parting with your uncle at Birmingham.

The Quarterly Meeting at Southampton was a very favored time.
That which occurred at Hitchin likewise appeared to be remarkably owned.

+++[+++After speaking of severe illness in her family.]--We
cannot doubt that in such adversity being permitted,
it is designed that we should deepen in the root of vital religion,
and witness "`all things to work together for good.`"
Do not you sometimes give thanks that your loved and lovely mother
knew her sufferings to be sanctified abundantly to her,
and that she is forever out of the reach of all that could make her feelings painful?
Do you now rejoice that the "`afflictions of the present time wrought
out for her a far more exceeding and eternal weight of glory?`"

Ask your bereaved remaining parent is it so with him?
and may each of her dear family walk in her steps, in the narrow,
the self-denying path that leads from death to life.
There is no better way.

[.asterism]
'''

After writing the last letter, date First Month 13th, 1842,
our beloved mother feeling more unwell than usual, retired early to her room,
never again to leave it.
Her indisposition being the commencement of that
illness which proved the last of her trials,
confined her to her bed,
and continued during the remaining nine weeks of her life so severe,
as to allow of her sitting up but a few times, and not at all for the greater part of it.
She suffered much at the beginning, but expressed a hope of recovery; evidently, however,
desiring it more for our sakes than her own; and saying one day,
after some anticipations of returning strength,
"`But I think I have not been one day without resignation.`"

To a friend who was giving her a message of love from his brother, she replied, "`Ah!
I never felt greater love for my friends, or sorer exercise on their account;
but the body is weak--it won`'t do;`" meaning she was unable to express her feelings.
Then, after a pause, "`Oh! there`'s but one way after all.
The good old way is the only one for us,
though some think me too much a stickler for this.`"

Her thoughts were evidently much occupied respecting our religious Society,
and its low state; yet she said she did not despair;
saying she thought she could see "`one here and another
there,`" who would be raised up for the cause of truth,
though she knew not who they might be.
She mourned that so few appeared to "`prefer Jerusalem above their
chief joy,`" as she thought she might thankfully say she had done;
acknowledging a consoling sense, at times,
of having done her part in submitting to be made use of as a stone of the street;
and also of having been enabled to "`fight the good
fight,`" and to "`keep the faith;`" adding,
"`Oh! it is a fine thing to have done this--to have '`kept the faith`' through all.
The horizon of our little world, our little Society, looks dull to me.
There must be more shaking, more overturning, I believe.`"

Alluding to her suffering illness, when sending a message to a friend, she said,
"`Tell her I call these the hailstones,
but I believe they have all passed through the righteous balances.`"
Also, "`In searching myself, I do not find anything laid to my charge--no condemnation.
There are things I do not forgive myself, but I hope, through adorable mercy,
to be forgiven.`"
On being asked one morning, how she had passed the night, she said,
"`Out of heaven I could not have been quieter.
It was all peace, peace;`" and added,
"`It seemed almost as if my dear Savior condescended to converse with me;
and oh! the sweetness, the meekness of His spirit.`"
Another time, something fresh in the way of nourishment having been offered to her,
she said, "`I have been thinking of being fed with the finest of the wheat.
Everything that human ingenuity can devise seems to be done for me, but all of no use.`"
"`Well! though my heart and my strength fails, the Lord is (still) my delight,
and my portion forever--THAT forever.`"

"`I want to say that I have seen, in the clearness of Divine light,
(oh! such clearness) that +++_______+++ has given me up,
a sacrifice highly acceptable to her Heavenly Father; but, my dear,
I could never say so until now.
What it has cost you is known only to yourself; my joy and gratitude is great,
to know your will at length given up,
as it regards one (I may say) interwoven with your very existence.
Cleave close to Him who will do abundantly for you, who indeed cares for you,
and will never leave you.
Repose all your cares and sorrows in His bosom.
He will be with you, though you may not always or often be favored sensibly to feel it.`"

For a time, suffering of any kind had almost ceased,
and our beloved mother was anxious we should know this, saying,
"`But if it were yet to come, I believe both you and I should be supported.
I have been thinking of the extreme sufferings of many Christians in leaving this world.`"
At this period she had little or no expectation of being restored to us,
and became often rambling in her expressions, though sweet and quiet as a little child.
She sent the following message most distinctly to
some young friends--"`Give my love to them,
and tell them I have thought a great deal of that text, '`Rejoice, oh young man,
in your youth,`' etc., etc.;
and tell them that whatever we pursue of profit or of pleasure,
it can only do us good so far as it is in the fear of God.`"

About ten days before the close, she expressed a wish to have us all at her bedside,
when she spoke to us nearly as follows:--"`At first
I thought I should recover from this illness,
but now it seems as if I must quite give myself up.
You see that everything in nature points that way.
When I got worse about three weeks ago, I went down very deep in my spirit, and I said,
'`Oh! my Heavenly Father, is it your will to take me now,
or at some other time?`' and it was answered, '`Whether I take you now,
or at some other time, be ready;`' and I said,
'`Oh! but it is a very awful thing to die,`' (and it is an awful thing).
Then it was said, '`Fear not: I can make hard things easy;
and what more is there for you to do?`' So it was shown me there was nothing left to do,
nothing more to do; and my rejoicing is unspeakable, that my children are resigned,
It it not so?`"
She was told we tried to be: we knew it was better for her than to remain with us, etc.

After some further expressions of tender affection and interest,
she remarked how many ways there are of sliding off the right foundation.
"`I told a friend, many years ago, to mind his little anointing.
I called it little,
and this may lead us in a direction very contrary to our natural inclinations;
like the kine that bore the ark, lowing as they went.
It needs constant watching too,
like that fire,`" (pointing to the one in her chamber) "`which must be often minded,
and fuel added to prevent its going out.
I think we need to get deeper, so that when anything like storms and temptations come,
we may be like the oaks, firmly rooted.
Be watchful and quiet; that`'s the thing.`"

The next day after the deeply affecting occasion just described,
our beloved mother spoke in a sweet and striking manner to her medical attendant,
for whom she had a sincere regard.
He inquired if her position was comfortable.
"`Oh!`" she said, "`I hardly ever lie comfortably, but I`'m very comfortable in myself.
Ah! creeds and forms, and a literal faith, will do nothing for us.
We must give up our own wills entirely, and become like little children:
it is the only way we can enter the kingdom.
I have known no other religion all my life than the will of God; and now,
whether I live or die, I shall be with my dear Savior.
Farewell, my dear friend; farewell.`"

The doctor was affected, and surprised to hear her speak thus.
It was indeed very remarkable to us all,
that although immediately before and after such occasions,
her faculties often appeared obscured,
yet when thus giving utterance to her feelings on religious subjects,
they were as clear as ever.
She made the remark herself, "`I have been much lost in my mind in this illness,
which I suppose is not uncommon; but I can speak to things of importance.`"
At this time, when the medical man had left the room, she smiled most sweetly, and said,
"`I feel so comfortable now I have said that to him.`"
She continued in the same strain; speaking of Lazarus,
and saying she believed this illness would be "`for the glory of God;`" adding, "`Mind,
I am not telling you it is '`not unto death.
'`I would have said that long ago, for your sakes, if I could; but whichever way it is,
it will tend more to His glory in that way, than it could have done in any other.`"
Something she also said signifying, as we understood it,
that when the creature and its works were in the grave, when self was entirely dead,
then the Creator was the most glorified;
but her powers of expression were now much exhausted.

This was the last occasion on which our beloved mother
spoke collectedly more than a sentence or two,
and we trust that, during the trying period of bodily suffering that followed,
her own words were fulfilled in some measure, that the sufferer was inwardly supported,
and those around her were not wholly forsaken.
Once after this time, she said to her son, when he raised her in bed,
"`It is for you I feel, and there is One that feels for you more than I can;`" and,
"`I am going to rest.`"

For nearly the last twenty-four hours our precious parent was in a kind of sleep,
from which it was plain she would wake only in death; and about one o`'clock,
on the sixteenth of the Third Month, 1842, she breathed her last; leaving us,
on her account, nothing but rejoicing,
in the firm belief that an everlasting and glorious rest is her portion; but,
as regards ourselves, and for the Church on earth, mourning indeed,
for the unspeakable loss sustained.

[.the-end]
The End.
